- plugins/inputs/sqlserver/sqlqueriesV2.go
> fix(inputs.sqlserver): set lower deadlock priority

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
fix: topic parsing error  when topic having prefix /
resolves: #11528
> fix(inputs.mqtt_consumer):  topic parsing error  when topic having prefix /

- plugins/outputs/redistimeseries/redistimeseries_test.go
resolves #11523
This PR adds a rudimentary integration test for the new `redistimeseries` output plugin.
> feat(outputs.redistimeseries): Add integration test.

- go.mod
- go.sum
- plugins/outputs/groundwork/README.md
- plugins/outputs/groundwork/groundwork.go
- plugins/outputs/groundwork/groundwork_test.go
- plugins/outputs/groundwork/sample.conf
> feat(outputs.groundwork): Improve metric parsing to extend output

- plugins/inputs/syslog/README.md
- plugins/inputs/syslog/nontransparent_test.go
- plugins/inputs/syslog/octetcounting_test.go
- plugins/inputs/syslog/rfc3164_test.go
- plugins/inputs/syslog/rfc5426_test.go
- plugins/inputs/syslog/syslog.go
resolves #4762
This diff adds capturing of the remote IP Address (syslog sender) and adds it as a `source` tag for each Metric:
```
$ telegraf --test --config /etc/telegraf/telegraf.conf --input-filter syslog --test-wait 15
2021-06-25T17:55:06Z I! Starting Telegraf 
> syslog,appname=docker-compose,facility=daemon,host=bb8,hostname=droplet,location=home,severity=info,source=10.0.0.12 facility_code=3i,message="<redacted>",severity_code=6i,timestamp=1624643706396113000i,version=1i 1624643706400667198
> syslog,appname=tailscaled,facility=daemon,host=bb8,hostname=dev,location=home,severity=info,source=10.0.0.15 facility_code=3i,message="<redacted>",severity_code=6i,timestamp=1624643706403394000i,version=1i 1624643706407850408
```
> feat: Syslog input plugin logs remote IP to source tag

- config/config.go
- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/azure_data_explorer/azure_data_explorer_test.go
- plugins/outputs/event_hubs/event_hubs_test.go
- plugins/outputs/http/http_test.go
- plugins/outputs/stomp/stomp_test.go
- plugins/serializers/json/README.md
- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
- plugins/serializers/json/testcases/transformation_batch.conf
- plugins/serializers/json/testcases/transformation_batch_out.json
- plugins/serializers/json/testcases/transformation_single.conf
- plugins/serializers/json/testcases/transformation_single_out.json
- plugins/serializers/registry.go
replaces #11205
This PR adds a new `json_transformation` option to the JSON serializer. This new option can be used to transform the JSON output using the [JSONata language](https://jsonata.org/) to accommodate for requirements on the receiver side. Additional benefits are the various filtering and processing capabilities of the introduced language (see README for a few basic examples).
> feat: Allow JSONata based transformations in JSON serializer

- plugins/inputs/snmp_trap/netsnmp.go
- plugins/inputs/snmp_trap/snmp_trap.go
resolves #11428
This PR fix the nil map panic when running with default snmp_trap config and fix timeout config not work issue.
> fix(inputs.snmp_trap): nil map panic when use snmp_trap with netsnmp translator

- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
resolve: #11429
The Graphite output plugin would only retry a server connection if it failed to send on all connections, this behavior wasn't obvious and if one server always remains up the other servers would never reconnect. This pull requests updates the retry logic to track the failed servers and reconnect to them after each send. I could also add a `retry_delay` configuration option similar to the [inputs.cloud_pubsub](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloud_pubsub) and [inputs.jti_openconfig_telemetry](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jti_openconfig_telemetry) plugins, but from the issue the author mentioned this might not be necessary so I thought maybe we could add the config option if someone does require it?
I also …
> feat(outputs.graphite): Retry connecting to servers with failed send attempts

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/sample.conf
- plugins/inputs/modbus/sample_request.conf
Just came across the same problem, hoping it'll save a couple of minutes for others in the future.
resolves #10965
> docs(inputs.modbus): README changes regarding request.tags

- plugins/inputs/kafka_consumer/sample.conf
#11220 edited sample config in the readme.md but not in the sample.conf. I evidently didn't notice the PR didn't pass ci and merged it. This caused master ci to start failing.
This PR adds the missing section to the sample.conf
> docs: Run `make docs` to fix CI on master

- plugins/inputs/mysql/README.md
resolves #4810
This PR adds a notice in inputs.mysql's readme to tell the user that the performance schema needs to be enabled.
> docs: add link to docs on how to enable mysql's performance schema

- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
resolves #9164 
opcua is panicking if the `identifier_type` does not match the actual type of `identifier`. This pr checks the type for strings and ints. I could not come up with a way to check guid or opaque types. And added a unit test
> fix(inputs.opcua): return an error with mismatched types

- config/config.go
- config/config_test.go
- plugins/inputs/directory_monitor/directory_monitor_test.go
- plugins/inputs/http/http_test.go
- plugins/parsers/json/parser.go
- plugins/parsers/registry.go
- plugins/parsers/registry_test.go
This PR removes some code that was required for handling old-style parsers. Since we converted all of them, let's clean up a bit and simplify the code...
> chore: More parser cleanup

- .circleci/config.yml
Fixes nightly build's license checking... Hopefully...
> fix: Remove shell execution for license-checker.

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
resolves #11498
The golang SQL API exposes a few settings related to pooled connections. (see https://pkg.go.dev/database/sql#DB) These settings need to be changed for some SQL drivers to connect reliably to some databases.
This PR adds telegraf settings that mirror the golang sql settings. This allows users to set them through telegraf.conf and be able to connect to databases that require specific settings.
The golang sql settings have defaults and since telegraf didn't set the settings, it was using the defaults. I mirrored the default values in the new telegraf settings. This should make the sql output behave the same as before.
> feat: add settings for go sql.DB settings

- plugins/inputs/cloudwatch/README.md
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
- plugins/inputs/cloudwatch/sample.conf
> fix: customizable cloudwatch batch size when querying aws

- go.mod
- go.sum
- plugins/outputs/wavefront/README.md
- plugins/outputs/wavefront/sample.conf
- plugins/outputs/wavefront/wavefront.go
- plugins/outputs/wavefront/wavefront_test.go
The Wavefront output plugin uses APIs from the Wavefront Go SDK that have been deprecated. This PR updates the SDK version and adopts the currently recommended APIs for configuring the Wavefront sender.
> fix(outputs.wavefront): update wavefront sdk and use non-deprecated APIs

- go.mod
- go.sum
This updates the github.com/harlow/kinesis-consumer to c2b9f79d7ab6, the latest commit on its master branch. Telegraf was previously using commit 5a873d6e9fec which is on a PR branch.
This module hasn't made a release since Sept 2021. The latest commits on its master are from Dec 2021.
> chore: update github.com/harlow/kinesis-consumer

- plugins/inputs/ntpq/README.md
- plugins/inputs/ntpq/ntpq.go
- plugins/inputs/ntpq/sample.conf
resolves #4746
partially replaces #7840 
This PR adds an `options` setting to specify flags passed on to the `ntpq` command. This way you can both add additional flags or remove default flags (e.g. `-p`). Due to it's capabilities the new `options` setting replaces the `dns_lookup` option which is deprecated in the PR.
> feat(inputs.ntpq): Add option to specify command flags

- plugins/inputs/kube_inventory/README.md
- plugins/inputs/kube_inventory/client.go
- plugins/inputs/kube_inventory/client_test.go
- plugins/inputs/kube_inventory/kube_inventory.go
- plugins/inputs/kube_inventory/sample.conf
Currently, Telegraf will read a token file and provide that as a string
to the K8s client. This will prevent the K8s client from attempting to
auto-refresh the token. In newer versions of K8s, tokens will expire
every hour as a security measure.
This, instead will pass the file location rather than having telegraf
read it directly. Because of this new K8s behavior, this also deprecates
and warns the user when using a hard-coded string token.
fixes: #11267
> fix(inputs.kube_inventory): send file location to enable token auto-refresh

- plugins/outputs/amqp/amqp.go
- plugins/outputs/amqp/client.go
- plugins/outputs/cloudwatch/cloudwatch.go
- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/kafka_test.go
- plugins/outputs/logzio/logzio.go
- plugins/outputs/opentelemetry/opentelemetry.go
- plugins/outputs/opentsdb/opentsdb.go
- plugins/outputs/opentsdb/opentsdb_http.go
- plugins/outputs/opentsdb/opentsdb_test.go
- plugins/outputs/prometheus_client/v1/collector.go
- plugins/outputs/stackdriver/stackdriver_test.go
- plugins/outputs/timestream/timestream.go
- plugins/outputs/timestream/timestream_test.go
This PR fixes linter issues in `plugins/outputs`. After applying this only two issues in `plugins/outputs/socket_writer` and `plugins/outputs/syslog` regarding deprecation of `err.Temportary()` remain. However, fixing those is not straight forward and should be tackled in another PR.
> fix(outputs): Linter issues

- plugins/inputs/kube_inventory/README.md
- plugins/inputs/kube_inventory/sample.conf
- plugins/inputs/kubernetes/README.md
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/kubernetes/sample.conf
Similar to #11267, this allows for the token contained in the provided
file to get re-read at each interval. This way, if the token is
updated/refreshed Telegraf will also get the newer token.
> fix(inputs.kubernetes): refresh token from file at each read

- .gitignore
- Makefile
- README.md
When building Telegraf on a Windows machine, the new tools were being built without `exe` extension causing the following error:
`plugins\inputs\wireguard\wireguard.go:1: running "../../../tools/readme_config_includer/generator": exec: "H:\\Sandbox\\telegraf\\tools\\readme_config_includer\\generator": file does not exist` for each plugin
Updated the makefile to add `exe` extension if `GOOS` is set to windows.
> chore: Using Windows, add exe extension to tools

- plugins/processors/starlark/starlark_test.go
- testutil/metric.go
This PR adds a benchmark for concatenating tags in the `starlark` processor. Furthermore, it adds the possibility to compare metrics in benchmark runs.
> feat: Add starlark benchmark for tag-concatenation

- go.mod
"go list -m all" will not fail anymore, GoLand will index all dependencies.
Workaround for: https://github.com/lxc/lxd/issues/10745
resolves: https://github.com/influxdata/telegraf/issues/11442
> fix: Workaround for failing "go list -m all"

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/kubernetes.go
- plugins/inputs/prometheus/kubernetes_test.go
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/sample.conf
resolves #11383
When using `monitor_kubernetes_pods` for Prometheus input plugin, currently the label `namespace` is added for the pod that is scraped. This however overwrites the `namespace` label if a metric that is scraped on that pod has that label. This PR adds a new setting that allows you to change the namespace label name for the pod so that this conflict does not occur.
> feat: prometheus monitor_kubernetes_pods add setting to change namespace label name of the pod to avoid conflicts

- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
resolves #11623 
This PR fixes an issue for `https`, `tcp` and `smtp` certificate validation when using multiple sources with non-overlapping DNS entries in the certificates. That is if the DNS name of the first source is not valid in, at least one, other certificates.
The error results from a stateful behavior of the `serverName()` function, evaluating the `c.tlsCfg.ServerName` entry and returning this with priority in combination with setting exactly this field (`c.tlsCfg.ServerName`) when getting the certificate via `getCert()`. After getting the first source (e.g. `server-A.org`), the, previously empty, `c.tlsCfg.ServerName` field is set to `server-A.org` in `getCert()`. While the `https` and `tcp` variants of the function is emptying the field (leading to issues where the name was …
> fix(inputs.x509): Multiple sources with non-overlapping DNS entries.

- plugins/outputs/opentelemetry/README.md
- plugins/outputs/opentelemetry/opentelemetry.go
- plugins/outputs/opentelemetry/sample.conf
resolves #
Added an Coralogix dialect to opentelemetry output plugin so that users can send metrics to Coralogix.
> feat: add coralogix dialect to opentelemetry

- plugins/parsers/json_v2/parser_test.go
- plugins/parsers/json_v2/testdata/wrong_path/expected.err
This PR update the json_v2 parser tests to reuse the new `testutil.ParseMetricsFromFile()` function.
> chore(parsers.json_v2): Cleanup test by reusing testutil function

- CHANGELOG.md
- plugins/common/tls/config.go
- plugins/common/tls/config_test.go
- plugins/common/tls/utils.go
- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/http/README.md
- plugins/inputs/http/sample.conf
- plugins/inputs/http_listener_v2/README.md
- plugins/inputs/http_listener_v2/sample.conf
- plugins/inputs/jti_openconfig_telemetry/README.md
- plugins/inputs/jti_openconfig_telemetry/sample.conf
resolves #8699
resolves #8171
resolves #8124 (at least partially)
replaces #8959
All credits for this PR go to @jdstrand! This PR allows to set a minimum TLS version required by the client for all plugins that use `common/tls` to configure their TLS setup. This includes, but is probably not limited to, `inputs.http`, `inputs.gnmi` and `inputs.jti_openconfig_telemetry`. This allows to change Golang's default of TLS 1.2 in both directions, i.e. downgrade (which implies some security risk) as well as setting it to TLS 1.3.
Unit-tests are added by the PR to check if lower server versions are rejected successfully.
> feat: Implement minimum TLS version for clients

- go.mod
- go.sum
The bump is required to be able to run tests with glibc 2.36 see https://github.com/lxc/lxd/issues/10738.
> fix: Bump github.com/lxc/lxd to latest git to fix issue with glibc 2.36

- plugins/outputs/amqp/README.md
- plugins/outputs/amqp/amqp.go
- plugins/outputs/amqp/client.go
- plugins/outputs/amqp/sample.conf
resolves #11626 
This PR adds support for setting a SOCKS proxy for the AMQP output plugin.
> feat(outputs.amqp): Add proxy support

- plugins/inputs/zookeeper/README.md
Rather than modify the existing zookeeper plugin to parse prometheus
metrics, point users at the existing prometheus plugin.
fixes: #11520
> docs(inputs.zookeeper): document use of prometheus plugin

- docs/CONFIGURATION.md
PowerShell 5 is the default version of PowerShell in Windows 10 and
older versions. It does not default to UTF-8 encoding, which can cause
issues with Telegraf trying to parse the file.
Rather than adding lots of weird logic to Telegraf, document the
the requirement to specify the encoding when using PowerShell 5.
Newer versions of PowerShell now use UTF-8 encoding.
Fixes: #11614
Fixes: #4880
Fixes: #6662
> docs: explain PowerShell 5 encoding

- plugins/inputs/sql/drivers_sqlite.go
This PR copies the build constraints found in the `sql` output for the `sqlite` driver to have both in sync and to handle the new `loong64` in go1.19. If we do not exclude `loong64` we get the following errors:
```text
linux/loong64
package github.com/influxdata/telegraf/cmd/telegraf
imports github.com/influxdata/telegraf/plugins/inputs/all
imports github.com/influxdata/telegraf/plugins/inputs/sql
imports modernc.org/sqlite
imports modernc.org/libc
imports modernc.org/libc/errno: build constraints exclude all Go files in /home/sven/go/pkg/mod/modernc.org/libc@v1.16.7/errno
package github.com/influxdata/telegraf/cmd/telegraf
imports github.com/influxdata/telegraf/plugins/inputs/all
imports github.com/influxdata/telegraf/plugins/inputs/sql
imports modernc.org/sqlite
imports modernc.org/libc …
```
> fix(inputs.sql): Sync build constraints for sqlite from output

- .github/workflows/readme-linter.yml
Update changed-files library to grab a [fix to the glob library](https://github.com/tj-actions/changed-files/issues/565) that was outputting all changed files if no file matched the pattern. Additionally, update the glob to be clear about where to start and put a check to only run the markdown linter with the changed files matching the previous filter.
Test Examples:
- [one readme updated](https://github.com/influxdata/telegraf/runs/7845373608?check_suite_focus=true) - expected one readme to be linted and find an issue
- [only a .go file updated](https://github.com/influxdata/telegraf/runs/7845361877?check_suite_focus=true) - expected no readme to be linted
- [no plugin code updated](https://github.com/influxdata/telegraf/runs/7845341912?check_suite_focus=true) - expected no readme to be …
> chore: only lint READMEs when changed

- agent/agent.go
When Telegraf processes a very large amount of data, such that the
batch size is constantly hit, then Telegraf may be sending batches
constantly. At the same time, the flush interval could be hit. During
the sending of a batch, the ticker for the flush interval can go to
zero, and as a result, the batch will produce a warning about not
sending within the interval time.
Sending batches should not send messages to the user that the interval
expired as they are separate paths.
Previously, #8953 attempted to reset the ticker while sending a
batch. This introduced an issue where the buffer was never fully
flushed.
fixes: #8941
> fix(agent): add flushBatch method

- Makefile
- cmd/telegraf/telegraf.go
- internal/internal.go
- internal/internal_test.go
- plugins/inputs/internal/internal_test.go
- plugins/outputs/opentelemetry/opentelemetry.go
resolves https://github.com/influxdata/telegraf/issues/11655
Additionally tested locally:
Here is how the userAgent looks: 
```
telegraf 1.24.0-35803efd (linux/amd64)`
```
```
./telegraf --version             
Telegraf 1.24.0-35803efd (git: master 35803efd)
```
Message printed during startup:
```
/telegraf --config telegraf.conf
2022-08-10T08:32:05Z I! Starting Telegraf 1.24.0-35803efd
```
> fix: refactor telegraf version

- plugins/inputs/sqlserver/azuresqlmanagedqueries.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries_test.go
Similarly to the query used for SQL Server, it adds the database name to the io stats output for Azure Managed Instance. It helps to better visualize and link collected data.
> feat(inputs.sqlserver): Add db name to io stats for MI

- config/config.go
- plugins/serializers/prometheus/README.md
- plugins/serializers/prometheus/collection.go
- plugins/serializers/prometheus/prometheus.go
- plugins/serializers/prometheus/prometheus_test.go
- plugins/serializers/registry.go
resolves #11390 (as much as is possible within Telegraf itself)
implements @srebhan feedback from https://github.com/influxdata/telegraf/pull/11417
Give option to reduce payload size by removing the HELP metadata from the payload.
> feat(serializers.prometheus): give option to reduce payload size by removing HELP from payload

- .github/workflows/golangci-lint.yml
Update both [golangci-lint to v1.48](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0) and [the github action to v3](https://github.com/golangci/golangci-lint-action/releases/tag/v3.2.0)
> chore: Update golangci-lint

- scripts/rpm/post-install.sh
- scripts/rpm/post-remove.sh
Instead of having an ever growing list of distros and releases, this
collapses the logic to switch based on whether systemd is detected or
not.
This also removes the sysv logic as all supported Fedora and RHEL
distros are only systemd at this point. This does leave the check for
systemd in place to ensure installs in containers work without errors.
Fixes: #4507
> fix: use os-agnositc systemd detection, remove sysv in RPM packaging

- plugins/inputs/sqlserver/azuresqldbqueries.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries.go
PR [#10553](https://github.com/influxdata/telegraf/pull/10553) for an issue [#10741](https://github.com/influxdata/telegraf/issues/10741) introduced a wrong filtering which leads to the state that all sessions are shown in the output - disregarding if they are running requests or not. 
The filtering condition:
`[request_id] IS NOT NULL	--A request must exists`
couldn't be ever true as in the previous code the [request_id] has been already changed to NonNullable inside the inner query:
`NULLIF(r.[blocking_session_id],0) AS [blocking_session_id]`
> fix(inputs.sqlserver): fixing wrong filtering for sqlAzureMIRequests and sqlAzureDBRequests

- plugins/inputs/all/linux_cpu.go
- plugins/inputs/linux_cpu/README.md
- plugins/inputs/linux_cpu/linux_cpu.go
- plugins/inputs/linux_cpu/linux_cpu_nonlinux.go
- plugins/inputs/linux_cpu/linux_cpu_test.go
- plugins/inputs/linux_cpu/sample.conf
This pull request adds an input plugin for monitoring Linux' CPUFreq subsystem. This pull request builds upon the work #4215 and #8342, but given that they haven't seen any activity in a while, I would like to complete the integration of this plugin into the Telegraf repository.
Currently, the plugin only exposes `cpufreq/scaling_cur_freq`, `cpufreq/scaling_min_freq`, `cpufreq/scaling_cur_freq` and `thermal_throttle/core_throttle_count`. If desirable, we could also add other fields exposed by the CPUFreq subsystem. 
**Question to the maintainers:** the `thermal_throttle/core_throttle_count` field is a bit out of place in this plugin, since it is not part of the CPUFreq subsystem in Linux. We could limit this plugin to only expose properties from the CPUFreq subsystem and have a separate …
> feat(inputs.linux_cpu): Add CPUFreq input plugin for Linux (v3)

- plugins/inputs/opcua/opcua.go
resolve: https://github.com/influxdata/telegraf/issues/11719
The ID was being set to the local copy of "node" in the loop, in order for the to be saved so it can be used later in the code: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/opcua/opcua.go#L516 it needs to be assigned using the index so that the original value gets updated. More context of this behavior: https://stackoverflow.com/questions/61605727/why-does-normal-for-loop-allows-assigning-value-to-struct-fields-while-for-range
> fix(inputs.opcua): Assign node id correctly

- plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
resolves #9365
This ensures that metrics output by the prometheusremotewrite serializer have correct label ordering. This is an alternative fix to #11674 that would be more robust but also more intrusive. We need this because we have 2 telegraf processes that run in different environments (with different locales with different uppercase letter ordering).
I'm okay with both solutions or even to make this fix configurable, ie. via a `order_labels` boolean flag.
> fix: sort labels in prometheusremotewrite serializer

- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/azuresqldbqueries.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries.go
- plugins/inputs/sqlserver/sqlqueriesV2.go
The output from sys.dm_exec_requests contains a static request from telegraf which has no added value and only makes the output larger and harder to read. The only situation, when this should be shown is when it becomes a heading blocker. This unlikely possibility is taken into account in a code. Similar filter is used by other monitoring tools and is included in Glenn Berry's [diagnostic queries solution](https://glennsqlperformance.com/resources/)
This is a sample ouput before this feat on idle system. It contains a telegraf request to gain the requests:
This is a sample output after this change on idle system:
> feat(inputs.sqlserver): improved filtering for active requests

- README.md
Now everyone will know we are A+ Go developers.
https://goreportcard.com/report/github.com/influxdata/telegraf
> docs: Add go report badge

- plugins/inputs/jolokia2/common/client.go
- plugins/inputs/jolokia2/jolokia2_agent/README.md
- plugins/inputs/jolokia2/jolokia2_agent/jolokia2_agent.go
- plugins/inputs/jolokia2/jolokia2_agent/sample.conf
- plugins/inputs/jolokia2/jolokia2_proxy/README.md
- plugins/inputs/jolokia2/jolokia2_proxy/jolokia_proxy.go
- plugins/inputs/jolokia2/jolokia2_proxy/sample.conf
> fix(inputs.jolokia2): add optional origin header

- plugins/inputs/directory_monitor/README.md
- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/directory_monitor/directory_monitor_test.go
- plugins/inputs/directory_monitor/sample.conf
resolves #11718
resolves https://github.com/influxdata/feature-requests/issues/441
This resolves a feature request to have the input plugin `directory_monitor` also process sub-directories. This does change the default behavior, I suppose this could be a breaking change? Not sure if this would be a problem for users? I could add a configuration flag but the best idea I have for this is a boolean flag called "recurse=true/false", so if you think a config option should be required be happy to hear suggestions.
edit: This feature has been put behind the boolean configuration option "recursive" to make this behavior optional
> feat(inputs.directory_monitor): Traverse sub-directories

- plugins/inputs/statsd/statsd.go
resolves #11775 
Currently, the statsd plugin stops when receiving malformed lines in data-dog mode as the parsing will return an error which in turn stops the eternally running parsing function. As a result, no more messages can be received after the first parsing error is encountered.
This PR changes the behavior for the data-dog mode to the non-data-dog behavior by just logging the malformed line and continue.
> fix(inputs.statsd): Do not error out for parsing errors in datadog mode.

- config/config.go
This fixes the error `2022-09-08T09:13:14Z E! [telegraf] Error running agent: Error loading config file test.config: plugin outputs.http: line 27: configuration specified the fields ["json_transformation"], but they weren't used` when using json_transformation
Adds what was forgotten in https://github.com/influxdata/telegraf/pull/11251
> fix: Add missing entry json_transformation to missingTomlField

- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/directory_monitor/directory_monitor_test.go
https://github.com/influxdata/telegraf/pull/11773 introduced the feature to traverse sub-directories, @Hipska pointed out the configuration options `files_to_ignore` and `files_to_monitor` doesn't support paths. So when two files have the same name but one is in a sub-directory there is now way to distinct one over the other.
This pull request updated the functions for matching files to the regexs that were provided to ignore and monitor to send the path instead of the name.
> feat(inputs.directory_monitor): Support paths for files_to_ignore and files_to_monitor

- .circleci/config.yml
Noticed it has been a while since our tiger bot made a PR to update the config, this process requires the amd64 package step to be run so that the config is generated. This was being skipped, so I am removing the ignore master filter so that it will run.
From the config:
```yaml
- 'generate-config':
requires:
- 'amd64-package'
filters:
branches:
only:
- master
```
> chore: Run amd64 package on master so config is generated

- plugins/parsers/xpath/json_document.go
- plugins/parsers/xpath/testcases/name_expansion/expected.out
- plugins/parsers/xpath/testcases/name_expansion/telegraf.conf
- plugins/parsers/xpath/testcases/name_expansion/test.json
This PR fixes the name expansion for JSON arrays by adding the correct array index to the name.
> fix(parsers.xpath): Add array index when expanding names.

- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
resolves #11782 
In the current implementation the modbus plugin will error out as soon as the first slave fails. This is a problem when querying multiple slaves over one interface (as in #11782) or when using ModbusTCP gateways as we loose one gather cycle for all devices after a failing one.
The current PR changes this behavior and only skips the failing slave (after busy-retry) but continues with other ones in the row.
> fix(inputs.modbus): Do not fail if a single slave reports errors

- agent/agent.go
- config/config.go
- config/config_test.go
resolves #11809 
When input plugins (or processors) use the passed `ParserFunc`, the new parser gets added to the list of running parsers in `config.Parsers`. As this instantiation of parsers can happen often and is out of the control of Telegraf's general framework, the array of running parsers will keep growing and is newer cleaned up. This means that a reference to the no-longer-used parsers is kept, garbage collection cannot free the parsers' space and we slowly eat up all memory.
The PR completely removes tracking the running parsers and thus solves the memory leak. However, once we want to go to dynamic plugin starting/stopping this problem will hit us for other categories as well as there is currently no way to remove running plugin instances from the corresponding lists.
> fix(parsers): Memory leak for plugins using ParserFunc.

- .circleci/config.yml
- scripts/installgo_windows.sh
The windows tests are timing out due to requiring user input for installing mingw, the script to install Go resolved this issue by calling `choco feature enable -n allowGlobalConfirmation` so I moved this outside of the script to always run.
e.g. https://app.circleci.com/pipelines/github/influxdata/telegraf/12709/workflows/4d70fb4e-921c-4060-a605-d0d41100afbb/jobs/204886
```
mingw v11.2.0.07112021 [Approved]
mingw package files install completed. Performing other installation steps.
The package mingw wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): 
```
> fix: Enable global confirmation for installing mingw

- plugins/inputs/exec/exec.go
- plugins/inputs/execd/execd.go
- plugins/inputs/execd/execd_test.go
- plugins/parsers/prometheus/parser.go
partially resolves #11820 
resolves: #11811 
replaces #11821 
This PR removes as much special handling of parsers as possible and unwraps the remainders from `models.RunningParse` correctly.
> fix(parsers): Unwrap parser and remove some special handling

- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/directory_monitor/directory_monitor_test.go
- plugins/inputs/tail/tail.go
- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
- plugins/parsers/errors.go
partially resolves #11820 
This PR introduces a new error (`ErrNotEnoughData`) for parsers that need to consume more data to output metrics. This is the case for CSV when fed linewise with skipping rows, metadata or other headers involved.
As a consequence, we can remove the direct check for the CSV parser in `inputs.tail` and `inputs.directory_monitor` and open the possibility for other parsers to also use this error.
> fix(parsers.csv): Remove direct checks for the parser type

- internal/snmp/translate.go
- plugins/inputs/consul_agent/consul_agent_test.go
- plugins/inputs/http/http.go
- plugins/inputs/hugepages/hugepages.go
- plugins/inputs/intel_pmu/intel_pmu.go
- plugins/inputs/nomad/nomad_test.go
- plugins/inputs/varnish/varnish_test.go
- plugins/inputs/vault/vault_test.go
- plugins/inputs/webhooks/filestack/filestack_webhooks.go
- plugins/inputs/webhooks/mandrill/mandrill_webhooks.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks.go
- plugins/inputs/xtremio/xtremio.go
- plugins/inputs/xtremio/xtremio_test.go
- plugins/outputs/groundwork/groundwork_test.go
- scripts/generate_versioninfo/main.go
This PR removes all usages of `io/ioutils` which is deprecated since go 1.16.
> chore: Remove deprecated io/ioutils

- config/config.go
There was logic in the parser registry that was lost in recent parser consolidation that allowed a user to specify which parser they wanted. In the case of exec, execd, and other plugins that use the older parsers.ParserInput, this logic was no longer applied.
Additionally, there were errors about the influx_parser_type config option not getting used.
fixes: #11801
> fix: reallow specifying the influx parser type

- plugins/inputs/mongodb/mongodb.go
- plugins/inputs/mongodb/mongodb_server_test.go
The start method handler did not match the interface, nor was there a
stop function. As a result, start was never called and the plugin was
never setting up the servers to connect to and collect from correctly.
This was introduced in #11629.
fixes: #11830
> fix(inputs.mongodb): actually start plugin correctly

- go.mod
- go.sum
resolves #
```
go build -tags "" -ldflags " -X github.com/influxdata/telegraf/internal.Commit=f899eb5c -X github.com/influxdata/telegraf/internal.Branch=master -X github.com/influxdata/telegraf/internal.Version=1.25.0-f899eb5c" ./cmd/telegraf
../go/pkg/mod/github.com/moby/sys/mount@v0.2.0/mounter_bsd.go:9:10: fatal error: 'sys/_iovec.h' file not found
#include <sys/_iovec.h>
^~~~~~~~~~~~~~
1 error generated.
```
and
```
go vet $(go list ./... | grep -v ./plugins/parsers/influx)
../go/pkg/mod/github.com/vmware/govmomi@v0.29.0/toolbox/hgfs/server.go:323:4: a.sysStat undefined (type *AttrV2 has no field or method sysStat)
```
and
```
go vet $(go list ./... | grep -v ./plugins/parsers/influx)
../go/pkg/mod/github.com/goburrow/serial@v0.1.0/serial_bsd.go:30:18: undefined: syscall.B460800 …
```
> fix: Update dependencies for OpenBSD support

- .github/workflows/golangci-lint.yml
- .github/workflows/linter.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> build: github Workflows security hardening

- plugins/inputs/internet_speed/README.md
- plugins/inputs/internet_speed/internet_speed.go
- plugins/inputs/internet_speed/internet_speed_test.go
- plugins/inputs/internet_speed/sample.conf
- plugins/inputs/processes/processes_test.go
`memory_saving_mode` is a more appropriate name for this variable, as this is the upstream feature that is toggled.
Also add a paragraph to the README to explain what this option does, and why it might be required.
resolves influxdata/telegraf#11870
> fix: Rename inputs.internet_speed.enable_file_download to match upstream intent

- plugins/inputs/opcua/README.md
- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/sample.conf
resolves #11559
Added workaround to use regular reads instead of registered reads.
> feat(inputs.opcua): add use regular reads workaround

- plugins/common/kafka/config.go
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
Since the enable_tls configuration option in the Kafka config plugin was
deprecated, TLS is enabled only when other TLS configuration options
are also set (ie, custom CA, client certificate, or skipping TLS
verification).  In effect, TLS cannot be enabled without setting any of those options.
This change is essentially a reversion to the pre-1.17 behavior, to
undeprecate enable_tls and thusly re-enable TLS for the general use
case.
> fix: Enable TLS in Kafka without custom config

- internal/content_coding.go
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/amqp_consumer/amqp_consumer_test.go
- plugins/inputs/amqp_consumer/sample.conf
resolves https://github.com/influxdata/telegraf/issues/6998
Adds a new content encoding option called `auto` to allow a more flexible input that can be gzipped or not, the content encoding is determined by the set "ContentEncoding" header in the message.
> feat(inputs.amqp_consumer): Determine content encoding automatically

- config/config.go
- config/config_test.go
- config/testdata/processors_with_parsers.toml
- parser.go
- plugins/processors/execd/execd.go
- plugins/processors/execd/execd_test.go
- plugins/processors/parser/parser.go
- plugins/processors/parser/parser_test.go
This PR converts the processors `execd` and `parser` to derive their parsers from the config instead of fiddling with `data_format` directly. To do so, the PR creates the necessary infrastructure in `config` and the adds the `SetParser` functions to the two plugins mentioned.
This is in preparation of deprecating the old parser initialization style completely.
> chore(processors): Convert processors to `ParserPlugin`s

- plugins/inputs/opcua/README.md
- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/sample.conf
resolves #
[This](https://github.com/influxdata/telegraf/pull/11630#issuecomment-1259705882) comment recommends a rename from `use_regular_reads` to `use_unregistered_reads` to reduce confusion.
> chore(inputs.opcua): rename regular reads to unregistered reads

- go.mod
- go.sum
To address potential problem described here: https://github.com/advisories/GHSA-qq97-vm5h-rrhg
> chore(deps): github.com/docker/distribution from v2.7.1 to v2.8.1

- plugins/inputs/diskio/README.md
- plugins/inputs/diskio/diskio.go
- plugins/inputs/diskio/diskio_linux.go
- plugins/inputs/diskio/diskio_other.go
- plugins/inputs/diskio/sample.conf
resolves #11685 
This PR will try to resolve all given devices on Linux, i.e. follow the (potential) symlinks of each device to their native "name"/device file which is helpful when specifying disk-ids or uuids. Furthermore, the PR adds the WWID of disks as tag.
**Note:** All of the above will only work on Linux and only if there are **no wildcards** used!
> feat(inputs.diskio): Allow selecting devices by ID

- plugins/inputs/influxdb_listener/influxdb_listener.go
- plugins/parsers/influx/influx_upstream/parser.go
The upstream parser does not support the m and h precision values. This will throw and error rather than silently dropping metrics.
Adds the following message to the telegraf log:
> 2022-09-22T15:34:55Z D! [inputs.influxdb_listener] error in upstream parser: time precision 'm' is not supported
Returns this response to the user:
> influxdb.exceptions.InfluxDBClientError: 400: {"error":"time precision 'm' is not supported"}
fixes: #11771
> fix(inputs.influxdb_listener): error on invalid precision

- Makefile
The RPM build process uses all of the cross-compiling infrastructure to build an RPM that contains correct binaries for the target OS, but, unfortunately the RPM itself would be tagged for the host OS, preventing installation.
Now we use GOOS for the target OS for the RPM as well, making cross-building possible.
> build(rpm): Allow building RPMs cross-OS

- config/config.go
- config/config_test.go
Noticed multiple linter issues in config.go and config_test.go.
* Multiple unused functions, I assume this happened when migrating to new parser style
* Not defering response body close in a loop
* The `empty-lines` linter wants a function into multiple lines
* Unused "_embed" import, was being used for the agent config but that has been moved to `cmd/`
> chore: Resolve linter issues in config.go and config_test.go

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/jti_openconfig_telemetry/README.md
- plugins/inputs/jti_openconfig_telemetry/sample.conf
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
- plugins/inputs/memcached/README.md
- plugins/inputs/memcached/sample.conf
- plugins/inputs/zookeeper/README.md
- plugins/inputs/zookeeper/sample.conf
- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
It should be `false` for every plugin which uses this config (to match code behaviour).
> fix: enable_tls has incorrect default value (true) in sample.conf and README.md

- .circleci/config.yml
**Scheduled workflows will be phased out by the end of 2022.**, this will effect how the nightly workflow gets triggered. The alternative is to define a trigger within the project settings that triggers nightly which I've setup:
You will need permissions to see this: https://app.circleci.com/settings/project/github/influxdata/telegraf/triggers
From the docs: `As a scheduled pipeline is essentially a triggered pipeline, it will run every workflow in the config.` while not obvious, it seems this means every workflow defined in the config will run unless you filter it not to. The most straightforward way to migrate our config (based on: https://github.com/influxdata/influxdb-client-python/pull/513) is to filter our nightly workflow to run when the `pipeline.trigger_source` variable is set to …
> chore(ci): Migrate to scheduled pipeline

- plugins/inputs/cloud_pubsub_push/cloud_pubsub_push_test.go
recent example: https://app.circleci.com/pipelines/github/influxdata/telegraf/13122/workflows/af708f74-8b50-4440-9d01-b43eb1fa6ede/jobs/210110
`TestServeHTTP` is failing randomly on Windows, adding build tags to only run it on linux and darwin.
> chore(inputs.cloud_pubsub_push): Don't run flaky test on Windows

- plugins/inputs/powerdns/powerdns_linux_test.go
- plugins/inputs/powerdns/powerdns_test.go
The test `TestPowerdnsGeneratesMetrics` has been failing randomly on Windows with `read unix @->C:\Users\CIRCLE~1.PAC\AppData\Local\Temp\pdns5239846799706671610.controlsocket: i/o timeout` 
recent example: https://app.circleci.com/pipelines/github/influxdata/telegraf/13161/workflows/570a6b15-97a1-46ed-bc5e-b5e20f32fc12/jobs/210212
Moving the test to only run on linux and darwin to avoid this, refactoring the test to also support Windows would be nice.
> chore(inputs.powerdns): Don't run  flaky test on Windows

- plugins/outputs/event_hubs/README.md
- plugins/outputs/event_hubs/event_hubs.go
- plugins/outputs/event_hubs/event_hubs_test.go
- plugins/outputs/event_hubs/sample.conf
resolves #11990
Made the existing batch option for max message size configurable using the Telegraf config. The default value of 1,000,000 is not suitable for all use cases. The basic event hub tier is 262144 bytes and the other tiers are 1048576 bytes.
> feat(outputs.event_hubs): Expose max message size batch option

- plugins/inputs/conntrack/README.md
- plugins/inputs/conntrack/conntrack.go
- plugins/inputs/conntrack/conntrack_test.go
- plugins/inputs/conntrack/sample.conf
- plugins/inputs/system/mock_PS.go
- plugins/inputs/system/ps.go
Current `conntrack` module is quite limited, it supports only single metric `ip_conntrack_count` (the other stats usually don't change over time).
This PR adds support for collecting `conntrack` stats while relying on [github.com/shirou/gopsutil](https://github.com/shirou/gopsutil/blob/master/net/net_linux.go) module. By default no stats will be collected, must be explicitly enabled:
```
[[inputs.conntrack]]
collect = ["all", "percpu"]
``` 
The idea is to support netfilter stats that are available on Linux systems via `conntrack -S / --stats` command:
```
$ conntrack -S
cpu=0           found=0 invalid=41 insert=0 insert_failed=0 drop=0 early_drop=0 error=0 search_restart=17 
cpu=1           found=0 invalid=14 insert=0 insert_failed=0 drop=0 early_drop=0 error=0 search_restart=12 
cpu=2 …
```
> feat(inputs.conntrack): Parse conntrack stats

- plugins/inputs/syslog/syslog.go
There are scenarios where the syslog libraries that telegraf uses no message or error is returned. In these cases, it is helpful to print a message saying that the message was received, but failed to parse.
fixes: #11989
> fix(inputs.syslog): print error when no error or message given

- plugins/inputs/statsd/statsd_test.go
A previous change caused statsd to stop processing metrics after an invalid metric is set. This test reproduces this scenario to ensure that it does not regress.
fixes: #9434
> test: add integration test for recovering after invalid data

- scripts/installgo_mac.sh
https://app.circleci.com/pipelines/github/influxdata/telegraf/13218/workflows/4d7b46cf-c3cb-46d4-9da5-403a5b969f06/jobs/210992
The Mac installation script broke after I refactored it to help with automating the Go version updates: https://github.com/influxdata/telegraf/pull/11968
This fixes the mistake of not assigning the values of the variables, I assume it didn't break the tests originally because it was cached.
> chore: Fix installgo_mac.sh using correct hash

- plugins/outputs/wavefront/wavefront.go
- plugins/outputs/wavefront/wavefront_test.go
- plugins/serializers/wavefront/wavefront.go
- plugins/serializers/wavefront/wavefront_test.go
Signed-off-by: Devon Warshaw <warshawd@vmware.com>
- [Won't fix] Updated associated README.md. -- I didn't, since this was a refactor, rather than a change.
- [Won't fix] Wrote appropriate unit tests. -- Fixed existing tests but did not write any new ones.
resolves #12003
<!-- Finally, include a summary of the code change itself. This
description should tell reviewers how the issues were resolved.
example: Fixed a potential dependency cycle by having Wavefront output plugin import the Wavefront serializer, rather than the other way around.
> refactor: Prevent import from going the wrong way

- agent/agent.go
fixes: https://github.com/influxdata/telegraf/issues/12012
Reverts https://github.com/influxdata/telegraf/commit/85b7590ff9c5a1abbf83aad034b8b7a4be3daf2e#diff-62b6ad581fe3a3059ae8c85ef0f31dde4092bfdecfa7d6857c470bcacaa8cc8bL284-L333 and fix possible resource leak (defer was called in the `for` loop) properly.
> fix(regression): Fixes problem with metrics not exposed by plugins.

- etc/telegraf.conf
- etc/telegraf_windows.conf
- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/sample.conf
- plugins/inputs/modbus/sample_general_end.conf
resolves feature request #11919
Allows to add a pause (warm-up time) for the slave device after modbus connect. E.g. Huawei solar inverter ethernet dongles need this pause to response the first request.
> feat(inputs.modbus): add pause after connect config parameter

- plugins/inputs/mongodb/mongostat.go
resolves #12047
`db.runCommand("serverStatus")` on mongo 2.6 returns a float or an int depending on the value for several fields. If the value is a whole number then the result is a whole number. This always uses a float64 to prevent serialization issues.
> fix: mongodb input incorrect type int64 for ServerStatus

- plugins/inputs/mysql/mysql_test.go
- plugins/outputs/sql/sql_test.go
* inputs.mysql: wait for 2nd occurrence of connection messages due to the container reloading after setup
* outputs.sql: postgres: wait for 2nd occurrence of connection messages due to the container reloading after setup
* outputs.sql: clickhouse: wait for last metric to get written and available
> test: add additional checks, waits in integration tests

- plugins/inputs/zookeeper/README.md
- plugins/inputs/zookeeper/sample.conf
- plugins/inputs/zookeeper/zookeeper.go
- plugins/inputs/zookeeper/zookeeper_test.go
Zookeeper currently sends anything not able to be parsed as an int to become a string. This means even other numerical data like a float becomes an string. This add an optional setting to let the user attempt to parse floats. If that fails then the field still becoms a float.
fixes: #7567
> fix(inputs.zookeeper): add the ability to parse floats as floats

- plugins/inputs/conntrack/conntrack_test.go
This PR skips the `inputs.conntrack` tests for machines where the conntrack kernel module is not loaded. In those cases tests currently fail with
```shell
plugins/inputs/conntrack# go test -v -race
=== RUN   TestNoFilesFound
--- PASS: TestNoFilesFound (0.00s)
=== RUN   TestDefaultsUsed
--- PASS: TestDefaultsUsed (0.00s)
=== RUN   TestConfigsUsed
--- PASS: TestConfigsUsed (0.00s)
=== RUN   TestCollectStats
conntrack_test.go:131: 
Error Trace:    /home/sven/Development/InfluxData/telegraf/plugins/inputs/conntrack/conntrack_test.go:131
Error:          Received unexpected error:
Conntrack input failed to collect metrics. Is the conntrack kernel module loaded?
Test:           TestCollectStats
panic.go:540: PASS: NetConntrack(bool)
--- FAIL: TestCollectStats (0.00s)
=== RUN …
```
> fix(inputs.conntrack): Skip gather tests if conntrack module not loaded

- plugins/inputs/modbus/modbus.go
> fix(inputs.modbus): add slave id to failing connection

- plugins/inputs/kafka_consumer/kafka_consumer.go
Sarama recently changed the consumer group rebalance strategy setting. I think telegraf updated to a version that uses the new setting in #11980. This PR uses telegraf's existing setting with the new sarama setting.
The old setting is deprecated but it is backward compatible
See https://github.com/Shopify/sarama/pull/2352
Although it's backward compatible, sarama logs that a deprecated setting is used, so it is useful to switch to the new setting.
The new setting allows consumers to choose more than one strategy. We may need to add a similar setting to telegraf in the future so users of inputs.kafka can choose which strategies they want instead of being limited to one.
> fix: switch to sarama's new consumer group rebalance strategy setting

- config/config.go
- config/config_test.go
- config/testdata/invalid_field_in_parser_table.toml
- config/testdata/invalid_field_in_parserfunc_table.toml
- config/testdata/invalid_field_processor.toml
- config/testdata/invalid_field_processor_in_parser.toml
- config/testdata/invalid_field_processor_in_parser_table.toml
- config/testdata/invalid_field_processor_in_parserfunc.toml
- config/testdata/invalid_field_processor_in_parserfunc_table.toml
- config/testdata/invalid_field_processor_with_parser.toml
- config/testdata/invalid_field_processor_with_parserfunc.toml
- config/testdata/invalid_field_with_parser.toml
- config/testdata/invalid_field_with_parserfunc.toml
resolves #12000 
In the course of parser cleanup (PR #11532) the handling of unused options was oversimplified and as a result, no warning was issued on unused config options. This PR restores the old behavior of warning on unused config options. Moreover it fixes a previously existing issue of not warning for invalid options in table-based parsers (`json_v2` and `xpath`). To guard the fix, we also add a bunch of unit-tests to ensure proper functionality in the future.
> fix: Restore warning on unused config option(s)

- agent/agent.go
When we were declaring the slice, it was given a length, which then grew and doubled when a ticker was added. Really wanted to set the capacity to the number of inputs.
fixes: #12072
> fix(agent): panic as tickers slice was off-by-one in size

- plugins/inputs/pgbouncer/pgbouncer_test.go
- plugins/inputs/sql/sql_test.go
- plugins/inputs/supervisor/supervisor_test.go
- plugins/outputs/mongodb/mongodb_test.go
Many of the database integration tests will start the database up, then do some initialization of settings or load some data and then reload or reboot the database.
These tests generally work because there is only 1-2 second delay, but sometimes that is enough to cause a failure trying to connect during a container/service reload.
fixes: #12083
> test: update integration test occurrences

- plugins/outputs/sql/sql_test.go
This effectively waits for the data we are looking for to exist, then checks that exists again. It seems there is a race in CircleCI, so waiting for some data was not enough.
fixes: #12082
> test(outputs.sql): further wait for clickhouse writes

- config/config.go
resolves #12080 
resolves https://github.com/influxdata/influxdata-docker/issues/647
This PR fixes a processor conversion fallout leading to potentially missing metrics when using processors in combination with aggregators, here especially the `dedup` processor. The background is that PR #11600 changed the way processors are initialized. Before the mentioned PR new and independent instances of a processors were created to be run before and after an aggregator. #11600 then changes this to only create a single instance, shared between the processing steps (before and after the aggregator) leading to side-effects. This is especially noticeable in the `dedup` processor as in the second processing step (after aggregation) **the same instance** sees the same metric twice and removes it while no …
> fix(processors): Correctly setup processors

- config/config.go
- config/config_test.go
- config/testdata/default_parser.toml
- config/testdata/default_parser_exec.toml
If the data_format value is omitted use the default values previously used. Influx for everything, except exec, which uses json.
fixes: #11978
> fix(config): set default parser

- plugins/inputs/ethtool/README.md
- plugins/inputs/ethtool/ethtool.go
- plugins/inputs/ethtool/ethtool_linux.go
- plugins/inputs/ethtool/ethtool_test.go
- plugins/inputs/ethtool/sample.conf
Some interfaces can expose a few thousands fields. It may not be necessary to gather and expose metrics for interfaces which are not `UP`.
This PR adds possibility to skip such metrics (but it defaults to exposing them - to be backward compatible):
```
```
Moreover, creation of `IncludeExcludeFilter` was moved from `Gather` to `Init` (input to this filter doesn't change so it makes sense to create it only once).
> feat(ethtool): Possibility to skip gathering metrics for downed interfaces

- go.mod
- go.sum
- plugins/common/opcua/client.go
- plugins/common/opcua/client_test.go
- plugins/common/opcua/input/input_client.go
- plugins/common/opcua/input/input_client_test.go
- plugins/common/opcua/opcua_util.go
- plugins/inputs/all/opcua_listener.go
- plugins/inputs/opcua/README.md
- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/read_client.go
- plugins/inputs/opcua/sample.conf
- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/opcua_listener.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/sample.conf
- plugins/inputs/opcua_listener/subscribe_client.go
resolves #8083
Refactored the opc ua plugin to use a more generic structure. This allows easy injection of either the read client or a subscription client.  
I extracted the logic for an opc ua client into an `/internal/opcua` package, as the same client logic could be reused for creating an opcua client output plugin.
It has become quite a big pull request, so please be thorough with your reviews.
There should be no breaking changes, as by default the `request` service is used. This PR is purely additive.
> feat(inputs.opcua_listener): OPC UA Event subscriptions

- plugins/inputs/kafka_consumer/kafka_consumer_test.go
Re-enables test added in #12058 and disabled in #12100 because it failed `go test -race`
CI logs seemed to show that the race was detected after the test was done. I think the consumer plugin continued to run after the containers were shut down and the race was happening when the consumer was trying to reconnect to the nonexistent broker.
This PR gracefully shuts down the plugins. I ran this `go test -run Integration -race -count 1000` for 30 min or so and it didn't detect a race.
> chore: shut down plugins gracefully to prevent race

- .github/workflows/golangci-lint.yml
Noticed golangci-lint github action is failing https://github.com/influxdata/telegraf/actions/runs/3328072758/jobs/5503637845
error:
`level=error msg="Timeout exceeded: try increasing it by passing --timeout option"`
This pull request increases the timeout from 1m to 3m, relevant upstream issue: https://github.com/golangci/golangci-lint-action/issues/297
> chore: Increase golangci-lint timeout

- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/testcases/duplicate_fields_issue_12091/expected.out
- plugins/inputs/modbus/testcases/duplicate_fields_issue_12091/telegraf.conf
resolves #12091 
This PR fixes an issue where measurements are defined for individual registers and handles those cases correctly. Before, only the global (plugin-instance/request-instance wide) measurement name was considered when checking for duplicate fields. Now also the field-individual measurement name is considered.
> fix(inputs.modbus): Handle field-measurement definitions correctly on duplicate field check

- plugins/processors/parser/parser.go
- plugins/processors/parser/parser_test.go
resolves #12115
With PR #11600 parsers for processors are no longer initialized with an empty metric name by default. Instead they now use the name of the parent plugin. However, `processors.parser` tries to use the original metric-name in case the parser does not provide an individual name (e.g. for `parsers.value`) for the returned metric. To do so, the processor checks for an empty name which is no longer valid as the parser's default metric name is now `"parser"`.
This PR fixes the check for the default name to restore the old behavior.
> fix(processors.parser): Keep name of original metric if parser doesn't return one

- plugins/serializers/json/README.md
The JSONata spec has rolled a number of times and as such added a number of other very helpful functions for use. Unfortunately, the library that telegraf uses has not been updated to support these newer versions. At first glance there also does not seem to be a replacement library at this time.
fixes: #12070
> docs(serializers.json): specify version of jsonata used

- plugins/aggregators/derivative/README.md
This comment states that *if* the variable option is used, the name of the resulting variable is generated differently. However, in practice the name of the resulting variable will always just use the (specified or default) suffix, regardless of whether the variable option is set.
It seems this behavior and this comment were both already present when the plugin was first introduced in PR #3762 (commit 927d34f) by @KarstenSchnitter, probably a remnant of changes during PR discussion.
> docs(aggregators.derivative): Remove incorrect comment

- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/opcua/opcua.go
- plugins/inputs/opentelemetry/grpc_services.go
- plugins/outputs/opentelemetry/opentelemetry.go
- plugins/outputs/opentelemetry/opentelemetry_test.go
- plugins/processors/parser/parser_test.go
Fixing:
```
plugins/inputs/kafka_consumer/kafka_consumer_test.go:556:13  errcheck     Error return value of `parser.Init` is not checked
```
introduced here: https://github.com/influxdata/telegraf/pull/12058
```
plugins/inputs/opcua/opcua.go:24:2                           unused       field `codes` is unused
```
introduced here: https://github.com/influxdata/telegraf/pull/11786
```
plugins/inputs/opentelemetry/grpc_services.go:30:56          staticcheck  SA1019: ptraceotlp.Request is deprecated: [v0.63.0] use ExportRequest. 
plugins/inputs/opentelemetry/grpc_services.go:32:9           staticcheck  SA1019: ptraceotlp.NewResponse is deprecated: [v0.63.0] use NewExportResponse. 
plugins/inputs/opentelemetry/grpc_services.go:63:58          staticcheck  SA1019: pmetricotlp.Request is …
```
> chore: Fix linter findings introduced in last PRs

- plugins/inputs/socket_listener/packet_listener.go
- plugins/inputs/socket_listener/socket_listener.go
- plugins/inputs/socket_listener/socket_listener_test.go
- plugins/inputs/socket_listener/stream_listener.go
This PR moves both packet and stream socket to individual files and reorganizes the code to have a proper interface for a listener. This work is done in preparation of fixing the hard-coded splitting of packets and make the code more readable.
> chore(inputs.socket_listener): Reorganize plugin code

- config/config.go
- plugins/serializers/registry.go
- plugins/serializers/splunkmetric/README.md
- plugins/serializers/splunkmetric/splunkmetric.go
- plugins/serializers/splunkmetric/splunkmetric_test.go
> fix(serializers.splunkmetric): put event metric tag behind option

- plugins/inputs/system/README.md
- plugins/inputs/system/system.go
- plugins/inputs/system/system_test.go
> fix(inputs.system): collect unique user count logged in

- plugins/outputs/sql/sql_test.go
This is a flaky test that does not always fail. When it does fail it says the file does not exist. My guess is that the file is not fully written or present.
fixes: #12148
> test(outputs.sql): wait for db dump file to exist

- go.mod
- go.sum
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/processes/processes_test.go
resolves [#12137](https://github.com/influxdata/telegraf/issues/12137)
Add support for double_val for [gnmi v0.8.0](https://github.com/openconfig/gnmi/blob/480bf53a74d21bb0a82d5d716264874de1070120/proto/gnmi/gnmi.proto#L121) in gnmi input plugin. 
Updated go.mod to use import latest gnmi spec.
> fix: inputs.gnmi add support for decimal_val as per gnmi v0.8.0 

- plugins/common/kafka/config.go
- plugins/common/kafka/config_test.go
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
- plugins/outputs/kafka/kafka.go
This PR adds the ability to start the kafka_consumer input even if the kafka broker is down. The default behavior of the plugin is to require connection for a successful plugin start, but users can set `connection_strategy = "defer"` to choose to connect after the plugin has started.
Since starting up without a connection means the plugin will immediately start to retry making a connection, this PR also adds settings to configure retries through sarama's Metadata.Retry.* settings. Previously telegraf always used the sarama defaults of 3 retries and 250ms delay before each retry. Now the Metadata.Retry.* settings are exposed through kafka_consumer's telegraf config so users can choose how many times to retry and configure the retry delay.
The PR also adds exponential backoff of connection …
> feat: Add exponential backoff when connecting or reconnecting and allow plugin to start without making initial connection

- cmd/telegraf/printer.go
Looks like I mistakenly added `PluginNameCounts` to `printer.go` which isn't being used, the function also exists in `config.go` where it is being used. Also removed unnecessary calls to `sort.String` because the plugin names get sorted again in the following functions when the slice is updated by the filters.
> chore: Cleanup printer.go

- .golangci.yml
- plugins/inputs/neptune_apex/neptune_apex_test.go
[tparallel](https://github.com/moricho/tparallel) - detects inappropriate usage of `t.Parallel()` method in your Go test codes.
Fix 3 new findings:
```
plugins/inputs/neptune_apex/neptune_apex_test.go:380:6  tparallel  TestSendRequest should call t.Parallel on the top level as well as its subtests
plugins/inputs/neptune_apex/neptune_apex_test.go:430:6  tparallel  TestParseTime should call t.Parallel on the top level as well as its subtests
plugins/inputs/neptune_apex/neptune_apex_test.go:476:6  tparallel  TestFindProbe should call t.Parallel on the top level as well as its subtests
```
> chore: Enable tparallel linter

- .golangci.yml
- plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
- plugins/outputs/kafka/kafka.go
- [asciicheck](https://github.com/tdakkota/asciicheck) - Simple linter to check that your code does not contain non-ASCII identifiers
- [asasalint](https://github.com/alingse/asasalint) - check for pass []any as any in variadic func(...any)
- [bidichk](https://github.com/breml/bidichk) - Checks for dangerous unicode character sequences
- [exportloopref](https://github.com/kyoh86/exportloopref) - checks for pointers to enclosing loop variables
Fix two new findings:
```
plugins/outputs/cloudwatch_logs/cloudwatch_logs.go:179:14  exportloopref  exporting a pointer for the loop variable logGroup
plugins/outputs/kafka/kafka.go:83:10                       asasalint      pass []any as any to func l.Print func(v ...interface{})
```
> chore: Enable asciicheck, asasalint, bidichk and exportloopref linters

- .golangci.yml
- plugins/common/logrus/hook.go
- plugins/common/shim/config.go
- plugins/common/shim/logger.go
- plugins/inputs/snmp/netsnmp.go
`depguard` is a great linter which can combine multiple allow and deny lists. Highly configurable.
> chore: Use depguard instead of revive.imports-blacklist

- plugins/inputs/tomcat/README.md
- plugins/inputs/tomcat/tomcat.go
- plugins/inputs/tomcat/tomcat_test.go
This adds a source tag which will help determine what server metrics are coming from. Currently, as there is no tag to determine where metrics are coming from, users have to use different tomcat plugins for each server. This would allow one plugin which would set the source field.
fixes: #3780
> feat(inputs.tomcat): add source tag

- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring_test.go
> fix(outputs.yandex_cloud_monitoring): catch int64 values

- plugins/outputs/sql/sql_test.go
There is still a race or something wrong with clickhouse sql test from time to time. It appears that even waiting for output it does not always get written to a file. This changes the test to stop waiting on files and instead parses the CLI output directly.
> test(outputs.sql): simplify clickhouse test

- cmd/telegraf/printer.go
resolve: https://github.com/influxdata/telegraf/issues/11074
From the discussion in the issue, it seems the intention was to have `outputs.influxdb_v2` be an exception to the alphabetically sorted outputs and be the first in the list. `outputs.influxdb` will still be first because it is enabled by default, this will change come 2.0 (https://github.com/influxdata/telegraf/pull/12158)
> chore: Move influxdb_v2 to be first in sample config

- plugins/outputs/prometheus_client/v1/collector.go
Currently, we are only expiring data is someone is getting the data. This means that if data is continuously pushed but not gathered, the usage can grow and grow. This change forces expiration during add, similar to how v2 handles this.
fixes: #9821
> fix(outputs.prometheus): expire during add

- plugins/common/opcua/client.go
- plugins/common/opcua/input/input_client.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/sample.conf
Resolves #12006
This PR adds support for returning OPCUA DateTime values via the opc-ua input plugin. Prior to this PR, we silently drop those values. Reopened because I made a mistake in #12020. 
The `gopcua` library returns these values as the time.Time type, which telegraf doesn't handle in `metric.go:convertField`. To make the smallest change possible, we simply convert the datetime value to a string in the default golang format before returning the updated value.
Example telegraf.toml
```yaml
[inputs.opcua]
nodes = [
{name="TimeEnded", namespace="4", identifier_type="s", identifier="TimeEnded"},
]
```
Notice the TimeEnded value has `Quality=OK` but the time value itself has failed to parse or be returned. This is because it falls into the `default` case in `metric.go:convertField` …
> fix: Add support for opcua datetime values

- cmd/telegraf/telegraf.go
- config/config.go
- config/config_test.go
resolves #9985
Another iteration on the fix from #10379 by @conorevans. 
Extracted config.WalkDirectory to collect a list of config files to load configuration from. Reuse the same list later to schedule automatic reloads for changed files.
> fix(agent): watch for changes in configuration files in config directories

- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
This PR makes some changes to the integration tests of both opcua_listener and opcua:
* Wait for log messages as well to give the service some additional time incase the port is up too early
* Remove an extra error message check
* For opcua_listener, allow init some additional time to complete without error
fixes: #12105
> tests(inputs.opcua_listener): harden tests

- plugins/inputs/ping/ping_notwindows.go
This aligns the ping6 behavior of FreeBSD greater than version 13 with the other BSD commands. Because it is breaking, we need to check the major version of FreeBSD and for 12 and older we use the older -x option.
fixes: #10743
> fix(inputs.ping): Use -W on newer version of FreeBSD with ping6

- plugins/aggregators/quantile/quantile.go
- plugins/aggregators/quantile/quantile_test.go
fixes #12040
In this plugin, the add method of the algorithm interface returns an error. Both places the method is called, the error is ignored. 
There are three types that implement the interface: exact r7, exact r8, and t-digest. The exact types never return an error but the t-digest does. In cases when t-digest returns an error, it is ignored and not passed to the user.
This PR adds a logger to this plugin and uses the logger to log the error in places where it was previously ignored. Thanks @zak-pawel for finding this by adding linters to the project!
> chore: log errors when adding to quantile aggregator

- plugins/processors/enum/enum_test.go
- plugins/processors/parser/parser_test.go
- plugins/processors/regex/regex_test.go
- plugins/processors/template/template_test.go
> chore: Wrap long lines in plugins/processors

- plugins/aggregators/histogram/histogram_test.go
> chore: Wrap long lines in plugins/aggregators

- go.mod
- plugins/inputs/elasticsearch/elasticsearch.go
- plugins/inputs/google_cloud_storage/google_cloud_storage_test.go
- plugins/inputs/google_cloud_storage/testdata/file_listing.json
- plugins/inputs/google_cloud_storage/testdata/first_file.json
- plugins/inputs/google_cloud_storage/testdata/first_file_listing.json
- plugins/inputs/google_cloud_storage/testdata/fourth_file.json
- plugins/inputs/google_cloud_storage/testdata/fourth_file_listing.json
- plugins/inputs/google_cloud_storage/testdata/second_file.json
- plugins/inputs/google_cloud_storage/testdata/second_file_listing.json
- plugins/inputs/google_cloud_storage/testdata/single_file_list.json
- plugins/inputs/google_cloud_storage/testdata/single_object_not_found.json
- plugins/inputs/google_cloud_storage/testdata/third_file.json
- plugins/inputs/google_cloud_storage/testdata/third_file_listing.json
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/hugepages/hugepages.go
> chore: Wrap long lines in plugins/inputs/[e-h]*

- plugins/outputs/postgresql/README.md
Fix example template queries that manage a view
The correct SQL syntax is "DROP view IF EXISTS viewname"
> docs(outputs.postgresql): fix example template queries

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Adds a Contributor Covenant Code of Conduct in the customarily expected location by GitHub. I linked to it from our contributing guide as well.  Based on the latest version of the upstream contributor covenant.
fixes: #12208
> docs: Add Contributor Covenant Code of Conduct

- .golangci.yml
- metric.go
- plugins/inputs/procstat/process.go
[interfacebloat](https://github.com/sashamelentyev/interfacebloat) - A linter that checks the number of methods inside an interface.
Address two new findings (add `//nolint` as @reimda suggested):
```
metric.go:35:13                                 interfacebloat  the interface has more than 10 methods: 24
plugins/inputs/procstat/process.go:11:14        interfacebloat  the interface has more than 10 methods: 17
```
> chore: Enable interfacebloat linter

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/request.go
- plugins/inputs/modbus/sample_request.conf
- plugins/inputs/modbus/testcases/duplicate_fields_same_slave_and_request/init.err
resolves #12222
This PR adds a `optimization` parameter that allows for optimizing requests sent to the device. Currently there are four modes,
- `none` doing nothing besides confirming to the max request size and ignoring empty requests
- `shrink` removing leading and trailing fields that are omitted
- `rearrange` moving the request boundaries in order to reduce the total request size further while keeping the number of requests
- `aggressive` automatically fill gaps in requests in order to reduce their number
to try to reduce the number of requests sent to the device while covering all fields.
> feat(inputs.modbus): Optimize requests

- plugins/inputs/nfsclient/nfsclient.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/smart/smart.go
- plugins/inputs/snmp/snmp_mocks_test.go
- plugins/inputs/sqlserver/sqlserver.go
- plugins/inputs/tcp_listener/tcp_listener.go
- plugins/inputs/varnish/varnish.go
- plugins/inputs/wireguard/wireguard.go
- plugins/outputs/azure_monitor/azure_monitor.go
- plugins/outputs/event_hubs/event_hubs.go
- plugins/outputs/graylog/graylog.go
- plugins/outputs/groundwork/groundwork.go
- plugins/outputs/iotdb/iotdb.go
- plugins/outputs/loki/stream_test.go
- plugins/outputs/postgresql/table_manager.go
- plugins/outputs/riemann/riemann.go
- plugins/outputs/sql/sql.go
- plugins/outputs/stackdriver/counter_cache.go
Address findings for [prealloc](https://github.com/alexkohler/prealloc) - Finds slice declarations that could potentially be pre-allocated.
After not pre-allocated slices in whole project are handled, we can enable proper linter to guard this.
> chore: Fix linter findings for prealloc (part2)

- plugins/inputs/mongodb/mongodb_server_test.go
These tests were expecting specific log messages, that were flaky. While looking at these tests I also realized that these should be testing how servers are handled not with changes, but from the start. Therefore, this updates the logic a bit to ensure a) on error, we actually error out quickly and b) on skip, that no errors are returned.
> test(inputs.mongodb): update integration test logic

- plugins/inputs/sqlserver/azuresqldbqueries.go
resolves #11406
Currently, available_storage_mb value doesn't include all available space (only space available in database file). Azure SQL DB available / used space takes into account allocated space as well. 3 new additional metrics related to data and log space usage for each Azure SQL DB including used_space_data_mb / total_log_mb / used_space_log_mb. They allow to compute database real space used and available space for both data and log.
> feat(inputs.sqlserver): adding data and log used space metrics for Azure SQL DB

- plugins/parsers/binary/README.md
- plugins/parsers/binary/parser.go
- plugins/parsers/binary/parser_test.go
resolves #12234
This PR adds an option `hex_encoding` to enable handling of hex-encoded input data. If `true`, the input data is interpreted as a string containing the binary data in a hex-encoding, e.g. `40490e56` for the 32-bit IEE754 (big-endian) representation of`pi`.
Input data containing spaces can be handled correctly (e.g. `40 49 0E 56`) and encoding is case _insensitive_.
> feat(parsers.binary): Handle hex-encoded inputs

- plugins/inputs/redis_sentinel/redis_sentinel.go
- plugins/inputs/redis_sentinel/redis_sentinel_test.go
resolves #12152
---
I improved the integration test by making sure the plugin gets Initialized and talks to an actual Redis Sentinel instance.
> fix(input.redis_sentinel): fix sentinel and replica stats gathering

- plugins/inputs/tcp_listener/tcp_listener_test.go
- plugins/outputs/graylog/README.md
- plugins/outputs/graylog/graylog.go
- plugins/outputs/graylog/graylog_test_linux.go
- plugins/outputs/graylog/sample.conf
- plugins/outputs/influxdb/http_test.go
- testutil/capturelog.go
This PR adds code to retry to connect to the given endpoints if `connection_retry` is set to `true`. This is helpful in cases where Telegraf is started, but the servers are not up or not reachable yet. The wait-time between retry attempts can be specified via `connection_retry_wait_time` option.
Please note, Telegraf will try to connect only 3 times if `connection_retry = false` (default) and will terminate if not successful. To connect forever set `connection_retry = true`, but be aware that metrics might get lost if the metric buffer overflows before a successful connection was made.
> feat(outputs.graylog): Implement connection retries

- config/config.go
- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/azure_data_explorer/azure_data_explorer_test.go
- plugins/outputs/event_hubs/event_hubs_test.go
- plugins/outputs/http/http_test.go
- plugins/outputs/stomp/stomp_test.go
- plugins/serializers/json/README.md
- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
- plugins/serializers/json/testcases/nested_fields_exclude.conf
- plugins/serializers/json/testcases/nested_fields_include.conf
- plugins/serializers/json/testcases/nested_fields_out.json
- plugins/serializers/registry.go
resolves #12070
This PR allows the user to specify fields that contain JSON object nested in a string value. When serializing these fields, the string is first unmarshalled to it's JSON object. The un-nesting happens before transformation in order to allow for arbitrary processing.
> feat(serializers.json): Support serializing JSON nested in string fields

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/sample_general_end.conf
resolves #12071
This PR adds a workaround to force the modbus plugin to read each field in a separate request. This is necessary for devices not conforming to the spec as described in #12071.
> fix(input.modbus): Add workaround to read field in separate requests

- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/testdata/mariadb/expected_metric_one.sql
- plugins/outputs/sql/testdata/mariadb/expected_metric_three.sql
- plugins/outputs/sql/testdata/mariadb/expected_metric_two.sql
Instead, use the output of the commands and compare that to the expected values. Due to some extra encoding bytes, some need to be stripped before comparing so each metric was split out into different files.
> test(outputs.sql): do not write to file during testing

- .github/workflows/linter.yml
- .github/workflows/readme-linter.yml
- plugins/inputs/activemq/README.md
The node version used by these plugins is old and suddenly causing issues due to deprecation and changes by GitHub. This updates the versions used to ensure we are only reporting issues with files that have changed.
You can look at the 2nd and 3rd commits for examples of failures.
> chore: update readme linter changed files version

- go.mod
- go.sum
resolves #12213 
Bump version of the library to include a fix needed for #12213.
> chore(deps): bump github.com/showwin/speedtest-go from 1.1.5 to 1.2.1

- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/gnmi_test.go
resolves #12257
When used with a  Sonic switch (4.0.2), the GNMI plugin produces an empty measurement name and in turn bails-out with `Could not serialize metric: invalid name` on the output side. The root cause of this is that the mentioned device reports the _origin_ of the data as part of the first element in the form `openconfig-platform:components` for the update. This leads to a lookup error in the internal aliases map as usually the path is considered to be absolute and not including the origin.
This PR first adds two test-cases reflecting the debug data gathered from the (non-working) Sonic device as well as a working Arista device. It then adds an error in case the name cannot be determined to better track-down the root cause of future error cases. The PR then checks for the …
> fix(inputs.gnmi): Fix empty name for Sonic device

- plugins/inputs/filecount/filecount.go
- plugins/inputs/jenkins/jenkins.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/timestream/timestream.go
- plugins/outputs/warp10/warp10.go
- plugins/parsers/influx/machine_test.go
- plugins/parsers/json_v2/parser.go
- plugins/parsers/xpath/json_document.go
- plugins/parsers/xpath/parser.go
- plugins/parsers/xpath/protocolbuffer_document.go
- plugins/parsers/xpath/xml_document.go
- plugins/processors/regex/regex_test.go
- plugins/processors/tag_limit/tag_limit.go
- plugins/serializers/influx/influx.go
- plugins/serializers/wavefront/wavefront.go
- selfstat/selfstat.go
Address findings for [makezero](https://github.com/ashanbrown/makezero) - Finds slice declarations with non-zero initial length.
After all findings in whole project are handled, we can enable `makezero` linter to guard this.
> chore: Fix linter findings for makezero (part1)

- .golangci.yml
- internal/internal.go
- plugins/inputs/system/ps.go
- plugins/outputs/influxdb/http.go
Address findings for [errname](https://github.com/Antonboom/errname) - Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`.
> chore: Fix linter findings for errname

- .golangci.yml
- plugins/inputs/hddtemp/go-hddtemp/hddtemp.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/pgbouncer/pgbouncer.go
- plugins/inputs/postgresql/postgresql.go
- plugins/inputs/postgresql_extensible/postgresql_extensible.go
- plugins/inputs/sqlserver/sqlserver.go
- plugins/inputs/zipkin/cmd/thrift_serialize/thrift_serialize.go
- plugins/outputs/timestream/timestream.go
- plugins/outputs/timestream/timestream_test.go
- plugins/parsers/influx/machine_test.go
- plugins/parsers/json_v2/parser.go
- plugins/parsers/prometheus/parser.go
- plugins/serializers/graphite/graphite.go
- plugins/serializers/nowmetric/nowmetric.go
- testutil/container.go
Address findings for [prealloc](https://github.com/alexkohler/prealloc) - Finds slice declarations that could potentially be pre-allocated.
This is the last part of addressing findings found by this linter, thus linter was also enabled in this PR.
related https://github.com/influxdata/telegraf/pull/12228 https://github.com/influxdata/telegraf/pull/12242
> chore: Fix linter findings for prealloc (part3)

- plugins/outputs/datadog/datadog.go
- plugins/outputs/datadog/datadog_test.go
resolves: NA
Add a debug log to print the response string obtained from API in case of a non 2XX status.
> fix(output.datadog): log response in case of non 2XX response from API

- plugins/inputs/socket_listener/stream_listener.go
resolves #12276 
This PR fixes an issue where the socket-listener leaks connections in case the client (correctly) waits for the server to close the connection after sending FIN. This PR closes the connection correctly after `read` finishes and thus avoids the leakage.
> fix(inputs.socket_listener): Correctly close connection

- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
field and labels selectors were ignored unless `pod_scrape_scope = "node"` was specified, this breaks `monitor_kubernetes_pods_method != "annotations"` (default), because then all pods become candidate for scraping.
This PR enables field and label selectors. I am keeping existing behaviour where field and label selectors are not used with default pod scraping (`monitor_kubernetes_pods_method == "annotations"`) for now, but I'd prefer any pod scraping to respect selectors same as it currently respects namespace.
> fix(inputs.prometheus): respect selectors when scraping pods

- docs/developers/DEPRECATION.md
- models/log.go
- models/log_test.go
This will make it possible for plugin authors to deprecate option values they do not support/use anymore.
At the same time, the docs for deprecating options is updated a bit to also include sample for unused options.
> feat: Add method to inform of deprecated plugin option values

- plugins/inputs/kube_inventory/README.md
It seems that the kubernetes sdk now wants a valid token nevertheless. This fixes the documentation for k3s.
- ~[ ] Wrote appropriate unit tests.~
> kube_inventory: update k3s integration guide

- plugins/inputs/tail/README.md
- plugins/inputs/tail/multiline.go
- plugins/inputs/tail/multiline_test.go
- plugins/inputs/tail/sample.conf
In case of multi-line input data, currently the tail plugin removes the newline characters. This can be bad for e.g. preserving log messages. This PR adds a new option, `preserve_newline`, which allows to keep the trailing newline characters for the multiline elements.
> feat(inputs.tail): Add option to preserve newlines for multiline data

- plugins/inputs/gnmi/gnmi.go
resolves #12273 
Do use a `nil` pointer instead of an empty path for `prefix` when creating a subscription request. This is necessary for (at least one) Huawei router(s) as they do not implement `prefix` support.
> fix(inputs.gnmi):  Do not provide empty prefix for subscription request

- plugins/inputs/directory_monitor/directory_monitor.go
resolves #12287 
Contrary to other OS, on Windows we cannot remove a file when it is still open as in this case Windows thinks that someone still uses this file. So let's close the file before removing it to make all OSes happy.
> fix(inputs.directory_monitor): Close input file before removal

- plugins/parsers/csv/README.md
- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
- plugins/parsers/registry.go
> feat(parsers.csv): Overwrite tags

- config/config.go
- config/config_test.go
- models/running_processor.go
follow-up on #12113
PR #12113 improved the processor ordering by keeping the loading order within a file. This PR is a follow-up to make the ordering less intrusive, keeping the `addProcessor()` similar to other `add...` function and remove the input-file information from the model. 
This is achieved by sorting the loaded processors by the line number (similar to #12113) _within the loaded file_ and then add the new chunk to the config's processor array. This way, the loading order of the _files_ is also preserved. To also take the `order` option into account the processor array is sorted a second time, this time by the `order` flag using a stable sort. This way all plugins containing an `order` option are sorted by this value, whereas all other plugins will keep their loading order …
> chore: Improve processor ordering

- docs/NIGHTLIES.md
Prior to this PR, nightly builds were at noon UTC, which is in the middle of the day for EU users, causing confusion, so let's move this to be midnight UTC while at least the EU and most of the US are done of the day.
The change has already been made in CircleCI config, this is only to update the docs to be more specific.
> docs: specify the time for nightly builds

- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/http_response_test.go
If merged, this PR would auto-set the HTTP User-Agent header for outgoing requests from the http_response input plugin according to industry best-practice, rather than relying on the default `Go-http-client/1.1` value. Additionally, it is backwards compatible as we respect any UA header that the user may have configured for themselves and do not override it.
> feat: add User-Agent header to http_response input plugin

- etc/telegraf.conf
- etc/telegraf_windows.conf
- plugins/inputs/zfs/README.md
- plugins/inputs/zfs/sample.conf
- plugins/inputs/zfs/zfs_freebsd.go
Introduce explicit dataset type filter for `zfs list` command. We are interested in filesystems and volumes only.
fixes: #12314
> fix(inputs.zfs): Unbreak datasets stats gathering in case listsnaps is enabled on a zfs pool

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/sample_general_begin.conf
resolves #12331
Windows users need to specify a COM port when dealing with serial devices. Currently, this is not easily possible as, without this PR, the `file://` scheme will parse `file://comX` into a _host_ instead of a path.
The present PR allows Windows users to specify a COM-port either via `controller = 'file://comX'` or directly via `controller = 'comX'` which is more intuitive. Furthermore, we fix relative paths and error out if we get strange paths to the controller.
> fix(inputs.modbus): Fix Windows COM-port path

- plugins/common/tls/config.go
- plugins/inputs/http_response/README.md
- plugins/inputs/http_response/sample.conf
This allows the user to specify the renegotiation method used by the TLS client. By default, this is and will continue to be set to never. However, a user can now also set this to once or freely to allow for additional renegotiation attempts.
fixes: #3832
> feat(tls): allow setting renegotiation method

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration.go
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/sample_register.conf
- plugins/inputs/modbus/sample_request.conf
- plugins/inputs/modbus/type_conversions.go
- plugins/inputs/modbus/type_conversions16.go
resolves #11907
This PR adds support for IEE754 half-precision floating points using a 16-bit representation. The new datatype is called `FLOAT16-IEEE` for the `register`-style configuration and `FLOAT16` for the `request`-style configuration.
> feat(inputs.modbus): Add support for half-precision float (float16)

- plugins/outputs/wavefront/wavefront.go
- plugins/outputs/wavefront/wavefront_test.go
- plugins/serializers/wavefront/replacers.go
- plugins/serializers/wavefront/wavefront.go
Currently, the wavefront output plugin and serializer plugin have identical definitions for string replacers called `sanitizedChars` and `strictSanitizedChars`.
This PR deletes the output plugin's copy of these replacers and has the output plugin use the version from the serializer instead. To avoid exporting the replacers, this PR also introduces a `Sanitize` function wrapping these replacers, which simplifies calling code slightly.
Finally, the replacers are moved into their own .go file within the serializer's package.
> chore(outputs.wavefront): Reduce code duplication

- go.mod
- go.sum
> chore(deps): Bump github.com/wavefrontHQ/wavefront-sdk-go from v0.10.4 to v0.11.0

- plugins/parsers/grok/README.md
- plugins/parsers/grok/influx_patterns.go
- plugins/parsers/grok/parser.go
- plugins/parsers/grok/parser_test.go
- plugins/parsers/grok/testdata/test_multiline.log
- plugins/parsers/registry.go
Recently, in PR #12281, the `tail` plugin was empowered to read multi-line messages and pass them on to the parser.
When passing those message  (i.e. text containing newline characters `\n`) to the grok parser's `Parse()` function, it will split the message at the newline character. While this is a sensible default, some error messages might span multiple lines and will thus be truncated, making it hard to pass them on to log-specific outputs. 
This PR adds a new option `grok_multiline` as well as a new pattern `MULTILINEDATA` (as `GREEDYDATA` will not match newlines) to the grok parser allowing to parse multi-line messages correctly, retaining the newline characters and message layout.
> feat(parsers.grok): Add option to allow multiline messages

- plugins/processors/parser/parser.go
resolves #12115
This fixes the name override described in #12115 (this time for real) for parsing tags which was forgotten in #12116.
> fix(processors.parser): Handle empty metric names correctly

- plugins/inputs/sql/sql.go
resolves: #12322 
This PR casts measurement columns to string in case they are represented as byte- or uint8- array.
> fix(inputs.sql): Cast measurement_column to string

- internal/host_endianess_be.go
- internal/host_endianess_le.go
- plugins/parsers/binary/entry_test.go
- plugins/parsers/binary/parser.go
- plugins/parsers/binary/parser_test.go
required-by #9633
This PR makes the host-endianness accessible to all plugins by moving it to the `internal` library. This is necessary as some binary protocols use the host's endianness to transport data (even though this is not a good idea).
The PR furthermore, extends the list of big-endian architecture according to @OrfeasZ's research in #9633.
> chore: Move host-endianness definition to `internal`

- plugins/aggregators/quantile/quantile.go
- plugins/aggregators/quantile/quantile_test.go
- plugins/common/jolokia2/client.go
- plugins/common/shim/processor_test.go
- plugins/common/starlark/builtins.go
- plugins/common/starlark/field_dict.go
- plugins/inputs/azure_monitor/azure_monitor.go
- plugins/inputs/azure_monitor/azure_monitor_test.go
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/redis_sentinel/redis_sentinel.go
- plugins/outputs/graylog/graylog.go
Address findings for [makezero](https://github.com/ashanbrown/makezero) - Finds slice declarations with non-zero initial length.
After all findings in whole project are handled, we can enable `makezero` linter to guard this.
> chore: Fix linter findings for makezero (part2)

- plugins/inputs/mongodb/mongodb.go
resolves #12336
Fixed an mongo connections leak triggered by auto reload config mechanism.
> fix(inputs.mongodb): Fix connection leak

- plugins/inputs/smart/smart.go
- plugins/inputs/smart/smart_test.go
Additional critical SMART metrics that are helpful in indicating/predicting device failure. From https://en.wikipedia.org/wiki/Self-Monitoring,_Analysis_and_Reporting_Technology#Known_ATA_S.M.A.R.T._attributes
> feat(inputs.smart): Add additional SMART metrics that indicate/predict device failure

- plugins/inputs/kubernetes/README.md
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/kubernetes/sample.conf
There is no reason to run daemonset to access kubelets, it can be done remotely. This PR makes `inputs.kubernetes` plugin to fetch node information from all the nodes when URL is set to empty value. Example config:
```
[[inputs.kubernetes]]
url = ""
bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
insecure_skip_verify = true
```
Tested with following kubernetes cluster role:
```
- verbs:
- get
apiGroups:
- ''
resources:
- nodes
- nodes/stats
- nodes/proxy
- pods
- verbs:
- get
nonResourceURLs:
- /stats/summary
```
> feat(inputs.kubernetes): allow fetching kublet metrics remotely

- etc/telegraf.conf
- etc/telegraf_windows.conf
- plugins/inputs/kube_inventory/README.md
- plugins/inputs/kube_inventory/client.go
- plugins/inputs/kube_inventory/kube_inventory.go
- plugins/inputs/kube_inventory/sample.conf
- plugins/inputs/kubernetes/README.md
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/kubernetes/sample.conf
> fix(inputs.kube_inventory): change default token path, use in-cluster config by default

- plugins/inputs/statsd/statsd_test.go
This test waits for 3 metrics to appear. On Windows, in CircleCI this test has become flaky and timing out after 10mins waiting for those metrics to show up. My hunch is that the microsecond sleep and expiration are too short and small even when the Windows machines tend to be very slow.
fixes: #12341
> test(inputs.statsd): increase sleep + expiration on test

- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/influxdb_listener/influxdb_listener_benchmark_test.go
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_benchmark_test.go
- plugins/inputs/mysql/mysql.go
- plugins/inputs/opcua/read_client.go
- plugins/inputs/procstat/native_finder.go
- plugins/inputs/redis/redis.go
- plugins/inputs/redis_sentinel/redis_sentinel.go
- plugins/inputs/sql/sql_test.go
- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/vsphere.go
- plugins/inputs/vsphere/vsphere_test.go
- plugins/inputs/zipkin/codec/codec.go
- plugins/inputs/zipkin/codec/jsonV1/jsonV1.go
Address findings for [makezero](https://github.com/ashanbrown/makezero) - Finds slice declarations with non-zero initial length.
After all findings in whole project are handled, we can enable `makezero` linter to guard this.
> chore: Fix linter findings for makezero (part3)

- plugins/common/opcua/client.go
- plugins/common/opcua/client_test.go
Fixed an issue where [all OPC UA status codes](https://reference.opcfoundation.org/v104/Core/docs/Part6/A.2/) could not be used as `additional_valid_status_codes`.
> fix(common.opcua): parse additional_valid_status_codes as uint32

- plugins/parsers/csv/README.md
- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
[https://github.com/influxdata/telegraf/issues/12243](url)
resolves #12243
Fixing null delimiters in csv, change the selected bytes before parsing to pipeline.
> fix(parsers.csv): Allow null-delimiters

- EXTERNAL_PLUGINS.md
Added a link to an external plugin to collect metrics from BACnet devices.
> docs: add bacnet to external plugins list

- cmd/telegraf/printer.go
- config/secret.go
- plugins/inputs/http/http.go
- plugins/secretstores/jose/README.md
- plugins/secretstores/jose/jose.go
- plugins/secretstores/jose/jose_test.go
- plugins/secretstores/jose/sample.conf
- plugins/secretstores/os/README.md
- plugins/secretstores/os/os.go
- plugins/secretstores/os/os_darwin.go
- plugins/secretstores/os/os_linux.go
- plugins/secretstores/os/os_test.go
- plugins/secretstores/os/os_windows.go
This PR adds a helper to check for uninitialized and/or empty secrets without the need to decode them. It also removes the duplicate "secret store plugins" section (and plugins) in the generated sample config.
Furthermore, the PR addresses the comments of @Hipska in #11232, e.g. making the secret-path a mandatory option for the JOSE store.
> fix(secretstores): Cleanup

- tools/package_lxd_test/container.go
The default config is no longer valid, so it will not attempt to start. As previously done with only the rpm/dnf based distros, provide a basic config for the deb based distros as well.
This is a fix for the new nightly failures:
https://app.circleci.com/pipelines/github/influxdata/telegraf/14270/workflows/e0117982-a55e-4365-a717-9a8c7274a35f/jobs/226539
> test: always create test config for package testing

- plugins/inputs/x509_cert/x509_cert.go
resolves #12402 
When adding intermediate certificates we always omit the first certificate, thus we need to add +1 when comparing the inputs as index 0 of the intermediates is actually index 1 in the certs.
> fix(inputs.x509_cert): Fix off-by-one when adding intermediates

- scripts/deb/post-install.sh
- scripts/deb/pre-remove.sh
Because the default config is no longer valid, telegraf will error out, and the systemd service will be marked as failed. Instead, no longer start the service on installation.
Additionally, if the service is already running on an upgrade, restart the service, but again do not start it if it was not already started.
fixes: #12397
> chore: do not start service on deb install

- plugins/common/starlark/field_dict.go
- plugins/common/starlark/tag_dict.go
resolves #12042 
Disable linter for two false-positives.
> chore(linter): Disable linter warning for Freeze() in starlark

- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/azuresqldbqueries.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries.go
- plugins/inputs/sqlserver/sqlserverqueries.go
example: Fixed an off by one error in counter variable in type FooBar.
SqlRequests did not include sleeping sessions with open transactions. This can make troubleshooting slightly problematic in some cases, where you see a blocked SPID but you don't see how long the blocking session has been sleeping. This fix will allow tracking sleeping sessions that keep transactions open.
> fix(inputs.sqlserver): SqlRequests include sleeping sessions with open transactions

- plugins/inputs/sqlserver/sqlserverqueries.go
This filter has been set on all other source files (azureSqlDB and azureSqlMI) but not on the on-prem version
resolves #11709 also for on-prem
> fix(inputs.sqlserver): Add SPID filter for sqlserverqueries.go

- plugins/inputs/mysql/mysql.go
Reverts (`mysql.go` only): https://github.com/influxdata/telegraf/pull/12371
Fixes: https://github.com/influxdata/telegraf/issues/12398
Pointer to `rawBytes := sql.RawBytes{}` wrongly used (instead of pointer to slice).
In that case, enforcing slices declarations with zero initial length doesn't make much sense.
> fix(inputs.mysql): Revert slices declarations with zero initial length

- .golangci.yml
- plugins/common/opcua/input/input_client.go
- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/zipkin/codec/thrift/thrift.go
- plugins/outputs/cloud_pubsub/cloud_pubsub.go
- plugins/outputs/cloud_pubsub/topic_stubbed.go
- plugins/outputs/cloudwatch/cloudwatch_test.go
- plugins/outputs/cratedb/cratedb.go
- plugins/outputs/datadog/datadog.go
- plugins/outputs/kinesis/kinesis_test.go
- plugins/outputs/opentsdb/opentsdb.go
- plugins/outputs/opentsdb/opentsdb_test.go
- plugins/outputs/postgresql/postgresql_bench_test.go
- plugins/outputs/postgresql/sqltemplate/template.go
- plugins/outputs/postgresql/table_manager.go
- plugins/outputs/postgresql/table_source.go
- plugins/serializers/influx/reader_test.go
Address findings for [makezero](https://github.com/ashanbrown/makezero) - Finds slice declarations with non-zero initial length.
This is the last part of addressing findings found by this linter, thus linter was also enabled in this PR.
related https://github.com/influxdata/telegraf/pull/12254 https://github.com/influxdata/telegraf/pull/12362 https://github.com/influxdata/telegraf/pull/12371
> chore: Fix linter findings for makezero (part4)

- EXTERNAL_PLUGINS.md
Added a link to an external plugin to collect metrics from tado
> docs: Add tado to external inputs list

- cmd/telegraf/telegraf.go
PR #12127 added the ability to reload on files in configuration directories. However, this broke any and all reloading. The PR assumed that the list of config files was initialized and set up, however, it is always empty as-is.
To populate the config files variable, the secret-store PR, #11232, added the loadConfiguraiton call. This needs to be run first before attempting to watch any files.
> fix(agent): correctly reload files

- plugins/common/kafka/sasl.go
- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/pgbouncer/pgbouncer_test.go
- plugins/inputs/postgresql/README.md
- plugins/inputs/postgresql/postgresql_test.go
- plugins/inputs/postgresql/sample.conf
- plugins/inputs/postgresql/service.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
- plugins/inputs/snmp_trap/README.md
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/azuresqldbqueries_test.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries_test.go
- plugins/inputs/sqlserver/azuresqlpoolqueries_test.go
- plugins/inputs/sqlserver/sample.conf
- plugins/inputs/sqlserver/sqlserver.go
- plugins/inputs/sqlserver/sqlserver_test.go
- plugins/inputs/vsphere/client.go
- plugins/inputs/vsphere/vsphere.go
- plugins/inputs/vsphere/vsphere_test.go
This PR is based on #11232 and adds secret- and thus secret-store support for more plugins, namely:
- `inputs.http_response` for username and password
- `inputs.kafka_consumer` and `outputs.kafka` via `common/kafka`
- `inputs.mqtt_consumer` for username and password
- `inputs.postgres` for `address`
- `inputs.postgres_extensible` for `address`
- `inputs.pgbouncer` for `address`
- `inputs.snmp_trap` for `sec_name`, `auth_password` and `priv_password`
- `inputs.sqlserver` when used with `auth_method = "connection_string"` (default)
- `inputs.vsphere` for username and password as well as token authentication
> feat(secretstores): Add support for more plugins

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/sample.conf
resolves #11778
This PR updates the `sample.config` according to the changes in #11019, deprecates the old `tag_only` way to specify tag-subscriptions and adds some helpful debugging information.
> docs(inputs.gnmi): Update configuration documentation

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/request.go
- plugins/inputs/modbus/sample_general_end.conf
resolves #8905
This PR allows to enforce reading coil-registers starting at zero which is required for some devices (see issue #8905). This replaces a workaround to define all fields between the register you want to read (e.g. 1000) and zero with the omit flag being set to true.
> feat(inputs.modbus): Add workaround to enforce reads from zero for coil registers

- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/stackdriver/stackdriver_test.go
- plugins/outputs/stackdriver/counter_cache.go
- plugins/outputs/stackdriver/counter_cache_test.go
- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/stackdriver/stackdriver_test.go
Fix deprecated `monitoringpb` in `stackdriver` plugins.
Introduced in https://github.com/influxdata/telegraf/pull/12385.
Fixed using:
```
go run cloud.google.com/go/internal/aliasfix/cmd/aliasfix@latest .
go mod tidy
```
proposed in https://github.com/googleapis/google-cloud-go/blob/main/migration.md
Following linter findings will not be shown anymore:
```
plugins/inputs/stackdriver/stackdriver.go:110:51          staticcheck  SA1019: monitoringpb.ListMetricDescriptorsRequest is deprecated: Please use types in: cloud.google.com/go/monitoring/apiv3/v2/monitoringpb 
plugins/inputs/stackdriver/stackdriver.go:111:44          staticcheck  SA1019: monitoringpb.ListTimeSeriesRequest is deprecated: Please use types in: cloud.google.com/go/monitoring/apiv3/v2/monitoringpb …
```
> chore: Fix deprecated monitoringpb

- plugins/inputs/sqlserver/sqlserverqueries.go
Some queries do not work with 2008R2 RTM, but they need at least SP2
Queries changed: 
- sqlServerProperties
- sqlServerVolumeSpace
> fix(inputs.sqlserver): More precise version check

- Makefile
- plugins/inputs/win_eventlog/event.go
- plugins/inputs/win_eventlog/win_eventlog.go
resolves #12328
This PR fixes a panic in `inputs.win_eventlog` for cases where events are sent by a remote machine (i.e. via Windows-event-forwarding) which is unavailable at the time Telegraf gathers those events. The root cause is that Windows' `EvtFormatMessage` syscall is expecting a handle to the publisher (i.e. the machine that sent the event) which is becoming invalid if that publisher is down. As a consequence Windows throws an exception (read Golang panic) instead of returning a simple error.
The implemented approach is to completely avoid the `EvtFormatMessage` syscall for remote events and instead use the `RenderingInfo` attached to the event itself (only existing for remote events).
> fix(inputs.win_eventlog): Handle remote events more robustly.

- plugins/inputs/socketstat/README.md
- plugins/inputs/socketstat/sample.conf
resolves #12479 
Fix the name of the option.
> docs(inputs.socketstat): Fix wrong TOML option name.

- config/config.go
Currently the default snmp reader is set after reading every file. This can lead to unnecessary deprecation messages that do not make sense to the user. Instead, only set the default, deprecated snmp reader after all files are read in. This way the user is only notified of the deprecation if they actually choose to use that value in their config.
fixes: #12454
> fix(agent): only set default snmp after reading all configs

- config/types.go
- config/types_test.go
In the course of #12490 I found an issue when specifying a duration with fractions of seconds as a plain floating point value e.g. `timeout = 1.5`, where you would expect the timeout to be 1500 milliseconds. However the current code will just floor that value to 1 second.
This PR fixes the handling of plain floating point values that contain fractions of seconds and also gets rid of the necessity for TOML quotation handling by using the `UnmarshalText` interface.
> fix(agent): Handle float time with fractions of seconds correctly

- plugins/secretstores/README.md
- plugins/secretstores/os/README.md
Telegraf will now panic when launched in a systemd-nspawn. This is because of the memguard dependency. It requires the CAP_IPC_LOCK capability to correctly lock and secure memory.
fixes: #12403
> docs(secretstores): document systemd-nspawn requirement

- plugins/parsers/json_v2/parser.go
Currently the log only says "Error in plugin: invalid JSON provided, unable to parse". 
Most other error cases in this parser already emit the message to debug log, use the same pattern for this error case as well
- [x ] Updated associated README.md.
- [ x] Wrote appropriate unit tests.
- [ x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)
resolves #
> fix(json_v2): In case of invalid json, log messsage to debug log

- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
… prefixes
fix metrics getting overwritten when there are multiple class policies and operation metrics
resolves #8261
> fix(inputs.cisco_telemetry_mdt): add operation-metric and class-policy

- plugins/inputs/influxdb/influxdb.go
- plugins/inputs/influxdb/influxdb_test.go
- plugins/inputs/influxdb/testdata/influx_return.json
- plugins/inputs/influxdb/testdata/influx_return2.json
Collect the system stats from influxdb metrics as well. These include the current time, started time, and uptime of the database.
fixes: #11071
> feat(inputs.influxdb): collect uptime statistics

- plugins/inputs/influxdb/README.md
This document how to use the existing Prometheus input plugin to collect metrics from InfluxDB v2. V1 uses a JSON document, while v2 uses a standard Prometheus text format. As such, users do not need to second plugin.
fixes: #10459
> docs(inputs.influxdb): collect v2 with prometheus plugin

- plugins/inputs/upsd/upsd.go
> fix(inputs.upsd): ensure firmware is always a string

- plugins/inputs/openweathermap/README.md
- plugins/inputs/openweathermap/openweathermap.go
- plugins/inputs/openweathermap/openweathermap_test.go
Add support for snow field in OpenWeatherMap input plugin
New fields: snow
> feat: Add snow parameter to OpenWeathermap input plugin

- plugins/inputs/redfish/redfish.go
- plugins/inputs/redfish/redfish_test.go
This adds the ability to parse the power control data. This includes values like the power consumed watts as well as other metrics.
fixes: #9575
> feat(inputs.redfish): add power control metric

- plugins/common/cookie/cookie.go
> fix(common.cookie): allow 204 status code

- plugins/inputs/intel_powerstat/README.md
- plugins/inputs/intel_powerstat/intel_powerstat.go
- plugins/inputs/intel_powerstat/intel_powerstat_test.go
- plugins/inputs/intel_powerstat/msr.go
- plugins/inputs/intel_powerstat/sample.conf
Introduced multiple changes:
- New `cpu_base_frequency_mhz` metric added (if configured by adding `cpu_base_frequency` to `package_metrics` configuration option).
- New supported platforms added: 
- **Intel Lakefield**
- **Intel RocketLake**
- **Intel AlderLake**
- **Intel RaptorLake**
- **Intel MeteorLake**
New metric:
`cpu_base_frequency_mhz` - will expose base frequency of CPU's package (in MHz)
Example of output for new metric:
```
powerstat_package,host=ubuntu,package_id=0 cpu_base_frequency_mhz=2400i 1669118424000000000
```
> feat(intel_powerstat): Add CPU base frequency metric and add support for new platforms

- plugins/inputs/dns_query/README.md
- plugins/inputs/dns_query/dns_query.go
- plugins/inputs/dns_query/dns_query_test.go
- plugins/inputs/dns_query/sample.conf
resolves #10452
This PR adds a new `include_fields` option which, if containing `"IP"` or `"all IPs"`, will allow to output the IP address or all IP addresses for the queried domain as field(s). Please note that the IPs are not ordered in any way but are output in the order they arrive in the DNS response.
> feat(inputs.dns_query): Add IP field(s)

- plugins/inputs/prometheus/kubernetes.go
- plugins/inputs/prometheus/kubernetes_test.go
- plugins/inputs/prometheus/prometheus.go
Deleted pods were not always unregistered. It was happening when telegraf is briefly disconnected from Kubernetes API server, in that case Informer OnDelete doesn't just return corev1.Pod object, but a special marker indicating that pod was deleted, but it's state might not be up to date. This PR accounts for such behaviour.
It also reworks Informer is used to track pods, summary is like following:
- register/unregister Pod now tracks each pod by their ID "$namespace/$podName"
- state of the pod passed in the Informer handler funcs is used as is to simplify tracking logic
Fixes #12527
> fix(inputs.prometheus): correctly track deleted pods

- plugins/outputs/elasticsearch/README.md
- [X ] Updated associated README.md.
- [ N/A] Wrote appropriate unit tests.
- [ X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)
Documents written to an Elasticsearch output include a RFC3339 timestamp, using whichever timezone the host system is configured to use.
If documents are later queried out of ES, the same timestamp will be returned. If Telegraf is running on machines in different timezones (or *using* different timezones) this can cause issues for some downstream pipelines which don't fully parse the timestamp and assume a consistent timezone.
Because Go's `time.time` honour's the `TZ` environment variable, it's possible to influence the reported timezone without having to change the system's timezone. …
> docs: Add details on overriding timezone used by Elasticsearch output plugin

- internal/snmp/translate.go
- metric.go
- plugins/common/opcua/client.go
- plugins/common/opcua/input/input_client.go
- plugins/inputs/burrow/burrow_test.go
- plugins/inputs/ceph/ceph.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
- plugins/inputs/cloud_pubsub_push/cloud_pubsub_push_test.go
- plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams.go
- plugins/inputs/dcos/client.go
- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/diskio/diskio_linux.go
- plugins/inputs/diskio/diskio_linux_test.go
- plugins/inputs/docker_log/docker_log.go
- plugins/inputs/exec/exec.go
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/jenkins/client.go
- plugins/inputs/jenkins/jenkins_test.go
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry_test.go
Address findings for [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/) - Finds ill-formed or insufficiently explained `//nolint` directives.
After all findings in whole project are handled, we can enable `nolintlint` linter to guard this.
```
internal/snmp/translate.go:251:3                                                nolintlint  directive `//nolint:nilerr` should provide explanation such as `//nolint:nilerr // this is why`
metric.go:35:1                                                                  nolintlint  directive `// nolint:interfacebloat // conditionally allow to contain more methods` should be written without leading space as `//nolint:interfacebloat // …
```
> chore: Fix linter findings for nolintlint (part1)

- plugins/inputs/icinga2/README.md
- plugins/inputs/icinga2/icinga2.go
- plugins/inputs/icinga2/icinga2_test.go
- plugins/inputs/icinga2/sample.conf
This PR adds possibility to collect both `hosts` and `services` metrics from Icinga 2 API at the same time. Furthermore it adds possibility to parse Icinga2 endpoint metrics.  These metrics are crucial for evaluating bottlenecks in Icinga2 setup.
Currently only partial stats endpoints support:
- `/v1/status/ApiListener`
- `/v1/status/CIB`
- `/v1/status/IdoMysqlConnection`
- `/v1/status/IdoPgsqlConnection`
Test output:
```
> icinga2_status,component=CIB,host=test active_host_checks=4.483333333333333,active_host_checks_15min=3496,
active_host_checks_1min=269,active_host_checks_5min=1191,active_service_checks=620.85,
active_service_checks_15min=579580,active_service_checks_1min=37251,
active_service_checks_5min=192239,avg_execution_time=0.03036015721774434, …
```
> feat(inputs.icinga2): Support collecting hosts,services and endpoint metrics

- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/leofs/leofs.go
- plugins/inputs/mesos/mesos.go
- plugins/inputs/mesos/mesos_test.go
- plugins/inputs/mongodb/mongodb.go
- plugins/inputs/net_response/net_response.go
- plugins/inputs/nsq_consumer/nsq_consumer_test.go
- plugins/inputs/passenger/passenger_test.go
- plugins/inputs/phpfpm/child.go
- plugins/inputs/phpfpm/fcgi.go
- plugins/inputs/phpfpm/phpfpm_test.go
- plugins/inputs/postgresql/service.go
- plugins/inputs/powerdns/powerdns_test.go
- plugins/inputs/powerdns_recursor/powerdns_recursor_test.go
- plugins/inputs/procstat/process.go
- plugins/inputs/sflow/sflow.go
- plugins/inputs/smart/smart.go
- plugins/inputs/snmp/gosmi.go
- plugins/inputs/snmp/netsnmp.go
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
Address findings for [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/) - Finds ill-formed or insufficiently explained `//nolint` directives.
After all findings in whole project are handled, we can enable `nolintlint` linter to guard this.
```
plugins/inputs/kafka_consumer/kafka_consumer.go:208:5                           nolintlint  directive `//nolint:errcheck,revive` is unused for linter "revive"
plugins/inputs/kafka_consumer/kafka_consumer.go:208:5                           nolintlint  directive `//nolint:errcheck,revive` should provide explanation such as `//nolint:errcheck,revive // this is why`
plugins/inputs/leofs/leofs.go:207:2 …
```
> chore: Fix linter findings for nolintlint (part2)

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/sample.conf
Adds an option to let a user set the max gRPC message size. By default, this is set to 4MB and allows a user to receive larger messages if required by the end device.
fixes: #12463
> feat(inputs.gnmi): set max gRPC message size

- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
resolves #12485 
*Description:*
The issue was related to a missed timeout configuration inside http client to establish a connection to an slow responsed Promtheus endpoint.
> fix(inputs.prometheus): Set the timeout for slow running API endpoints correctly

- plugins/common/opcua/client.go
- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/read_client.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
The Gopcua/opcua client was never properly initialized, which meant that authentication to the opcua server was never configured. My guess is this got lost in the shuffle of the addition of the opcua_listener plugin.
In testing before this change, without calling init, the server gave an error like
```
2023-01-20T20:27:06Z E! [inputs.opcua] Error in plugin: error in Client Connection: The user identity token is not valid. StatusBadIdentityTokenInvalid (0x80200000)
```
After Init(), the plugin works and is able to ingest data as expected.
> fix(inputs.opcua): Fix opcua and opcua-listener for servers using password-based auth

- plugins/outputs/prometheus_client/v1/collector.go
The current method of expiration is to check at every adding or collecting of metrics. However, this blocks and slows a lot of things down. Instead, create a ticker that will launch the expiration process when we actually need to expire.
fixes: #12481
> fix(outputs.prometheus_client): expire with ticker, not add/collect

- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
Currently, the plugin registers its TLS configuration as key `"custom"` to the MySQL driver. However, this registration is global to the driver package and therefor potential side-effects between multiple plugin instances arise if those instances register __different__ TLS configurations.
This PR fixes the issue by replacing the `"custom"` key with a unique key while keeping the user-facing configuration the same. Furthermore, we move the initialization to the `Init()` function in order to save some cycles and avoid the necessity to frequently create random registrations.
> fix(inputs.mysql): Avoid side-effects for TLS between plugin instances

- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
Fix a linter issue caused by always returning a `nil` error. So we simply remove the returned error param and simplify the code.
> chore(inputs.x509_cert): Fix linter warning

- go.mod
- go.sum
PR https://github.com/influxdata/telegraf/pull/12561 requires a lot of dependency updates, so breaking them out into separate PRs.
Updating github.com/prometheus/client_golang and github.com/prometheus/common triggers a few other updates as well. This change includes just these, to isolate any regression related to prometheus to one commit/PR.
It appears that no code changes were required to support this update.
resolves #
> chore(deps): update prometheus dependencies

- docs/LICENSE_OF_DEPENDENCIES.md
This PR fixes the link to the license to make nightly builds happy again.
> fix(docs): Fix link to license for Google flatbuffers

- internal/internal.go
- internal/internal_test.go
- plugins/inputs/http/http.go
- plugins/outputs/http/http.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/loki/loki.go
- plugins/outputs/sensu/sensu.go
resolves #12044 
This PR fixes the linter issue described in #12044. While on it, I cleaned-up the `CompressWithGzip()` function, clarified and documented the error propagation and added unit-tests to ensure errors are propagated correctly.
> chore(internal.gzip): Cleanup `CompressWithGzip`

- cmd/telegraf/main.go
- cmd/telegraf/printer.go
- plugins/inputs/dns_query/dns_query_test.go
- plugins/inputs/vsphere/client.go
- plugins/inputs/x509_cert/x509_cert_test.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb/http_test.go
- plugins/parsers/grok/parser_test.go
Fixes linter findings (issues accidentally created in last weeks) with little cleanup:
```
cmd/telegraf/printer.go:114:1                      revive  argument-limit: maximum number of arguments per function exceeded; max 6 but got 7
plugins/inputs/dns_query/dns_query_test.go:33:2    revive  import-shadowing: The name 'metric' shadows an import name
plugins/inputs/dns_query/dns_query_test.go:55:2    revive  import-shadowing: The name 'metric' shadows an import name
plugins/inputs/vsphere/client.go:99:74             revive  empty-lines: extra empty line at the end of a block
plugins/inputs/x509_cert/x509_cert_test.go:429:11  revive  indent-error-flow: if block ends with a return statement, so drop this else and outdent its block
plugins/outputs/influxdb/http.go:124:20            revive …
```
> chore: Fix existing linter findings

- plugins/inputs/postgresql/README.md
- plugins/inputs/postgresql/sample.conf
This adds notes about connecting to postgresl using a local unix socket. While the issue below was hopeful in changing the default behavior at the very least documenting that you can connect to a local socket via the connection string is helpful to users.
The default will remain the same however.
fixes: #4872
> docs(inputs.postgresql): provide socket connection details

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
- plugins/inputs/http/http.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb_v2/http.go
- Merge `golangci-pr` and `golangci-master` jobs into `golangci` job run both in PRs and on master branch. It will fail (for both cases) when any issue is found for whole codebase.
- bump `golangci-lint-action` from `v1.50.0` to `v1.50.1`
- Fix last findings introduced in https://github.com/influxdata/telegraf/pull/12587:
```
plugins/inputs/http/http.go:209:70          unparam  makeRequestBodyReader - result 1 (error) is always nil
plugins/outputs/influxdb/http.go:484:83     unparam  (*httpClient).requestBodyReader - result 1 (error) is always nil
plugins/outputs/influxdb_v2/http.go:390:83  unparam  (*httpClient).requestBodyReader - result 1 (error) is always nil
```
> chore: Lint whole codebase both in PR and master branch

- plugins/inputs/mongodb/mongodb.go
Resolves #12598.
Using `%w` in logs is not valid, it should only be used with `fmt.Errorf`.
> fix(inputs.mongodb): fix error logging

- plugins/inputs/mongodb/mongostat.go
- plugins/inputs/mongodb/mongostat_test.go
Below is an example of the SIGSEGV I occasionally get when restarting a MongoDB node that is being monitored by Telegraf MongoDB plugin. I think it rather happens during the node shutdown, though. Because according to the stacktrace, it's the `newStat` variable that doesn't have `Locks` populated as the code expects. The proposed fix is quite straightforward. It just adds adds necessary `nil` checks that are the same (symmetric) as those performed on the `oldStat` data.
The stacktrace below is for Telegraf 1.24.2. The line with "nil pointer dereference" can be found at https://github.com/influxdata/telegraf/blob/9550e7a533dd00632e14435e87ed3eb4b04832c6/plugins/inputs/mongodb/mongostat.go#L1227
```
[signal SIGSEGV: …
```
> fix(inputs.mongodb): resolve SIGSEGV when restarting MongoDB node

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
- plugins/inputs/jti_openconfig_telemetry/collection.go
- plugins/inputs/leofs/leofs.go
- plugins/inputs/pf/pf.go
- plugins/inputs/postgresql_extensible/postgresql_extensible.go
- plugins/inputs/snmp_legacy/snmp_legacy.go
- plugins/inputs/systemd_units/systemd_units.go
- plugins/outputs/graphite/graphite.go
- chore: bump `golangci-lint` from v1.50.1 to [v1.51.0](https://github.com/golangci/golangci-lint/releases/tag/v1.51.0)
- enable new [gocheckcompilerdirectives](https://github.com/leighmcculloch/gocheckcompilerdirectives) linter:
> Check that go compiler directives (`//go:` comments) are valid and catch easy mistakes.
> Compiler directives are comments like `//go:generate`, `//go:embed`, `//go:build`, etc.
>
> ## Why
> 
> Go compiler directives are comments in the form of `//go:` that provide an instruction to the compiler.
> The directives are easy to make mistakes with. The linter will detect the following mistakes:
> 1. Adding a space in between the comment bars and the first character, e.g. `//go:`, will cause the compiler to silently ignore the comment.
> 2. Mistyping a directives …
> chore: bump golangci-lint from v1.50.1 to v1.51.0

- .github/workflows/golangci-lint.yml
- internal/internal.go
- plugins/inputs/mock/mock.go
- plugins/inputs/mock/mock_test.go
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/statsd/statsd.go
- plugins/inputs/tcp_listener/tcp_listener.go
- plugins/outputs/file/file_test.go
- plugins/outputs/mqtt/mqtt_v3.go
- plugins/outputs/mqtt/mqtt_v5.go
- tools/update_goversion/main.go
- Bump go to 1.20 for `golangci-lint-action`
- Bumping go version for `.github/workflows/golangci-lint.yml` added to `tools/update_goversion`
- Fixed issues found for go 1.20:
```
internal/internal.go:92:2         staticcheck  SA1019: rand.Read has been deprecated since Go 1.20 because it shouldn't be used: For almost all use cases, crypto/rand.Read is more appropriate. 
plugins/inputs/mock/mock.go:68:2  staticcheck  SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a …
```
> chore: Bump go to 1.20 for golangci-lint-action

- cmd/telegraf/telegraf.go
Pass the contents of the config from the reloadLoop into runAgent. Currently the behavior is to go through and read the config twice.
fixes: #12606
> fix(agent): only read the config once

- plugins/inputs/processes/README.md
- plugins/inputs/processes/processes_notwindows.go
- plugins/inputs/processes/processes_test.go
- plugins/inputs/processes/sample.conf
Allows the use of `sudo` when running `ps` on BSD systems. Linux systems will read from /proc, and Windows is not supported.
fixes: #5004
fixes: #11103
> feat(inputs.processes): add use_sudo option for BSD

- docs/CONFIGURATION.md
This might be a more convenient and compact syntax for specifying these
attributes, so show some examples. This syntax has been available since
TOML 0.4.0 defined in 2015.
> docs: Show TOML inline table syntax for tags/tagpass/tagdrop

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/all/p4runtime.go
- plugins/inputs/p4runtime/README.md
- plugins/inputs/p4runtime/p4runtime.go
- plugins/inputs/p4runtime/p4runtime_fake_client_test.go
- plugins/inputs/p4runtime/p4runtime_test.go
- plugins/inputs/p4runtime/sample.conf
Co-Authored-By: Jakub Sikorski <jakub.sikorski@intel.com>
resolves  #12470
[P4Runtime](https://github.com/p4lang/p4runtime) is a gRPC server whose API is used to interact with a control plane specification for controlling the data plane elements of a device defined or described by a P4 program.
P4Runtime Specification: https://p4.org/p4-spec/docs/p4runtime-spec-working-draft-html-version.html
P4 programmable pipelines provide the flexibility of adding custom counters that can help observe the pipeline's operation. We provide the means to evaluate the effectiveness of those pipelines via exposed counters. That is the motivation why we would like to have a Telegraf input plugin that exposes P4Runtime Counters metrics.
> feat(inputs.p4runtime): Implementation of P4Runtime input plugin

- plugins/inputs/conntrack/conntrack.go
- plugins/inputs/conntrack/conntrack_test.go
Enabling stats feature in `conntrack` input by setting `collect` field (affected versions `v1.25.0`, `v1.25.1`) causes segfault
minimal config:
```toml
[[inputs.conntrack]]
collect = ["all"]
```
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1387053]
goroutine 70 [running]:
github.com/influxdata/telegraf/plugins/inputs/conntrack.(*Conntrack).Gather(0xc00046a000, {0x6cb41a0, 0xc0000c33a0})
/go/src/github.com/influxdata/telegraf/plugins/inputs/conntrack/conntrack.go:109 +0x133
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc0007c2730)
/go/src/github.com/influxdata/telegraf/agent/agent.go:419 +0x2f8
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs …
```
> fix(inputs.conntrack): resolve segfault when setting collect field

- cmd/telegraf/telegraf.go
- config/config.go
- config/config_test.go
This will add /etc/telegraf/telegraf.d to the list of default
configuration locations to load from.  A common use case is for
Docker where users want to upload an entire directory of 
configurations and run telegraf. Right now they have to add
a custom launch command, when in reality we should include this
directory by default.
This also means that the --config option can be omitted from the CLI
if a user is only using --config-directory. Currently, users need to specify
an empty /etc/telegraf/telegraf.conf file and specify they want to
include only a configuration directory.
fixes: https://github.com/influxdata/telegraf/issues/5656
fixes: https://github.com/influxdata/telegraf/issues/5571
> feat(agent): add /etc/telegraf/telegraf.d to default config locations

- .github/workflows/golangci-lint.yml
- metric.go
Right now there file names and line numbers are not shown in github action logs:
This PR implements workaround provided here https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648
> chore: Show file names and line numbers for found issues in github action logs

- .golangci.yml
- config/config_test.go
- plugins/common/shim/config_test.go
- plugins/inputs/google_cloud_storage/google_cloud_storage_test.go
- plugins/outputs/azure_monitor/azure_monitor_test.go
- testutil/testutil_test.go
Address findings for [tenv](https://github.com/sivchari/tenv) - analyzer that detects using os.Setenv instead of t.Setenv since Go1.17.
```
config/config_test.go:483:2                                             tenv  os.Setenv() can be replaced by `t.Setenv()` in TestConfig_getDefaultConfigPathFromEnvURL
plugins/common/shim/config_test.go:17:2                                 tenv  os.Setenv() can be replaced by `t.Setenv()` in TestLoadConfig
plugins/common/shim/config_test.go:19:2                                 tenv  os.Setenv() can be replaced by `t.Setenv()` in TestLoadConfig
plugins/inputs/google_cloud_storage/google_cloud_storage_test.go:419:2  tenv  os.Setenv() can be replaced by `t.Setenv()` in emulatorSetEnv …
```
> chore: Fix linter findings for tenv

- plugins/inputs/internet_speed/README.md
- plugins/inputs/internet_speed/internet_speed.go
- plugins/inputs/internet_speed/sample.conf
This adds the ability to exclude or include specific speedtest server IDs. If a user excludes a server ID that server is always excluded from selection. If a user includes a specific server ID, we will look for only that ID.
This does not let a user pick a random server ID. The speedtest-go library will receive the 10 closet servers. As such, users need to be careful as they can prevent any server from being picked.
fixes: #11449
fixes: #11625
fixes: #12595
> feat(inputs.internet_speed): server ID include and exclude filter

- config/config.go
- config/secret.go
- config/secret_test.go
- docs/CONFIGURATION.md
Make sure we inform the user (i.e. error out) about missing or invalid secret-store IDs to avoid silent fails.
> fix(secretstores): Check id format and presence

- plugins/inputs/syslog/README.md
Whilst support for the BSD syslog protocol (RFC 3164) has recently been added to this plugin, the introduction section still stated that only the newer RFC5424 protocol was supported. This was despite the subsequent sections of the readme explaining how to optionally use the BSD syslog protocol.
Update the introduction section of the readme to clarify that both the RFC5424 or RFC3164 protocols are supported.
> docs(inputs.syslog): Add BSD syslog to readme intro

- plugins/inputs/http_listener_v2/README.md
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/http_listener_v2/sample.conf
This allows the user to add custom HTTP headers that are included in the response of the HTTP listener itself.
fixes: #8175
> feat(inputs.http_listener_v2): add custom server http headers

- Makefile
fixes: #9521
Test Cases: run on RHEL/CentOS 7 + Fedora 37
> chore: prevent RPM from changing permissions on telegraf.d

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/inputs/prometheus/sample.conf
Rename the Timeout Prometheus Input Plugin variable inside the configuration and the code to parse the corresponding value directly
**Be aware it's a breaking change for older versions and should be merged into the next major version.**
resolves #12565
Fix the corresponding case and renames the variable as already discussed inside #12565
> fix: Rename the Prometheus Input Plugin Timeout variable

- config/config_test.go
- config/secret_test.go
- plugins/inputs/disk/disk_test.go
- plugins/inputs/ecs/ecs_test.go
- plugins/inputs/execd/shim/shim_test.go
- plugins/inputs/leofs/leofs_test.go
- plugins/inputs/prometheus/prometheus_test.go
- testutil/testutil_test.go
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
oldVal := os.Getenv("key")
defer os.Setenv("key", oldVal)
os.Setenv(key, "new value")
// after
t.Setenv(key, "new value")
}
```
> test: use `t.Setenv` to set env vars

- plugins/inputs/cloudwatch/cloudwatch.go
If a user specifies a specific region and endpoint, then the cloudwatch client needs to be set up to use those two values and override the default values that are provided.
fixes: #12653
> fix(inputs.cloudwatch): enable custom endpoint support

- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
resolves #10580
This PR fixes the handling of Windows paths by directly creating the URL instead of using a fragile indirection parsing a hand-crafted string.
> fix(inputs.x509_cert): Fix Windows path handling

- plugins/inputs/bond/bond.go
- plugins/inputs/bond/bond_test.go
Previously the `status` value has been initialized to 0 only when starting to parse a whole bond. If any single interface in the bond is up the `status` is set to 1 for all following interfaces (even if they are down).
To fix this we reset all collected fields after each interface is finished. This should also resolve the unlikely case that some interfaces have different fields than others.
---
CLA signing is still in progress
> fix(inputs.bond): Reset slave stats for each interface

- plugins/outputs/mqtt/README.md
- plugins/outputs/mqtt/mqtt.go
- plugins/outputs/mqtt/mqtt_test.go
- plugins/outputs/mqtt/mqtt_v5.go
- plugins/outputs/mqtt/sample.conf
resolves: https://github.com/influxdata/telegraf/issues/12526
Add optional support for MQTT 5 publish properties in the config
> feat(outputs.mqtt): add support for MQTT 5 publish properties

- go.mod
- plugins/inputs/x509_cert/README.md
- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
resolves #10550
This PR adds OCSP stapling information from tls connectionstate(https://pkg.go.dev/crypto/tls#ConnectionState) (https://pkg.go.dev/golang.org/x/crypto/ocsp#ParseResponse). OCSPResponse signature is not checked against issuer certificate.
New fields: ocsp_status(Good=0,Revoked=1,Unknown=2), ocsp_produced_at, ocsp_this_update, ocsp_next_update and ocsp_revoked_at (when ocsp_status=2).
New tags: ocsp_stapled yes/no
> feat(inputs.x509_cert): Add OCSP stapling information for leaf certificates (#10550)

- etc/telegraf.conf
- etc/telegraf_windows.conf
- plugins/inputs/haproxy/README.md
- plugins/inputs/haproxy/haproxy.go
- plugins/inputs/haproxy/haproxy_test.go
- plugins/inputs/haproxy/sample.conf
resolves #12672 
- Added support for tcp endpoints in haproxy input plugin. For example, if haproxy is configured to expose stats endpoint with `stats socket ipv4@127.0.0.1:9999 level admin`, the plugin will be able to communicate with it with `servers = ["tcp://127.0.0.1:9999"]` configuration
> feat: add support for tcp endpoints in haproxy plugin

- plugins/inputs/statsd/README.md
- plugins/inputs/statsd/sample.conf
- plugins/inputs/statsd/statsd.go
- plugins/inputs/statsd/statsd_test.go
resolves #12432
This PR adds a stat for the number of pending messages accessible through the `inputs.internal` plugin. Furthermore, it allows to configure the number of parallel threads used to parse incoming data.
> feat(inputs.statsd): Add pending messages stat and allow to configure number of threads

- EXTERNAL_PLUGINS.md
This PR adds a listing for the [PlayFab Insights](https://github.com/dgkanatsios/telegraftoplayfabinsights) external plugin.
> adding PlayFab Insights external plugin

- plugins/inputs/net_response/net_response.go
- plugins/inputs/net_response/net_response_test.go
Plugin cleanup so users don't receive configuration errors every gather cycle:
> chore(inputs.net_response): Use Init to check configuration issues

- agent/agent.go
- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- config/config.go
- config/deprecation.go
- config/secret.go
- internal/content_coding.go
- internal/http.go
- internal/internal.go
- internal/process/process.go
- internal/snmp/translate.go
- models/filter.go
- testutil/container.go
- testutil/file.go
- tools/custom_builder/config.go
- tools/package_lxd_test/container.go
- tools/package_lxd_test/lxd.go
- tools/readme_config_includer/generator.go
- tools/update_goversion/main.go
Address findings for [errorlint](https://github.com/polyfloyd/go-errorlint) - finds code that can cause problems with the error wrapping scheme introduced in Go 1.13.
After all findings in whole project are handled, we can enable `errorlint` linter to guard this.
Following findings in `agent`, `cmd`, `config`, `internal`, `models`, `testutil` and `tools` packages were fixed:
```
agent/agent.go:200:22                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:207:26                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:214:27                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format …
```
> chore: Fix linter findings for errorlint (part1)

- cmd/telegraf/telegraf.go
In a recent change we moved to loading the config only once during the initial load of telegraf. This saves time and is more efficient from reading files on disk, however, it ignored the fact that we need to reload the config if someone is watching a config. This reload occurs in runAgent, where the second reading was always taking place.
This updates the logic, so that we only re-read the configs in runAgent if we are calling it a second time from the reload loop.
fixes: #12718
> fix(agent): reload config on config update

- plugins/inputs/wireguard/README.md
- plugins/inputs/wireguard/wireguard.go
- plugins/inputs/wireguard/wireguard_test.go
Adds a new field with a csv list of allowed CIDR addresses.
fixes: #12705
> feat(inputs.wireguard): add allowed_peer_cidr field

- plugins/inputs/lvm/README.md
- plugins/inputs/lvm/lvm.go
- plugins/inputs/lvm/lvm_test.go
- plugins/inputs/lvm/sample.conf
Fixes [this problem](https://github.com/influxdata/telegraf/pull/9771#issuecomment-1129038389) mentioned by @rafaelreis-r to @powersj.
I basically followed what is done in other plugins when it comes to make it possible for user to specify path to binary files.
In this specific situation, I need to be able to modify path for `lvs`, `vgs` and `lvs` as they are located in `/sbin/` on my Linux system (Debian Bullseye) rather than `/usr/sbin/` like it is currently hard-coded.
> fix(inputs.lvm): Allow to specify path to binaries in config file

- plugins/inputs/jti_openconfig_telemetry/README.md
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry_test.go
- plugins/inputs/jti_openconfig_telemetry/sample.conf
Allows a user to use the _timestamp from the data rather than the collection time.
fixes: #12695
> feat(inputs.jti_openconfig_telemetry): set timestamp from data

- docs/TLS.md
- plugins/common/tls/config.go
- plugins/common/tls/config_test.go
Currently, TLS is disabled if no `tls_*` option is specified. This prevents users from using e.g. TLS on TCP connections using the system defaults. This PR adds a `tls_enable` flag to the common TLS client configuration. When not given, the behavior of Telegraf is unchanged. However, if explicitly set to `false` all TLS settings are ignored and TLS is disabled. When set to `true`, TLS is enforced even if no other TLS option is given, allowing for using the system's default settings.
> feat(common.tls): Add enable flag

- EXTERNAL_PLUGINS.md
Renaming Telegraf to PlayFab insights plugin to be consistent with the new plugin name https://github.com/dgkanatsios/telegraftoplayfab
Thanks!
> chore(external): Renaming Telegraf to PlayFab insights plugin

- plugins/common/mqtt/mqtt_v3.go
- plugins/outputs/mqtt/README.md
- plugins/outputs/mqtt/homie.go
- plugins/outputs/mqtt/mqtt.go
- plugins/outputs/mqtt/mqtt_test.go
- plugins/outputs/mqtt/sample.conf
resolves #12589
resolves #10732 
This PR adds a new `layout` option to specify how topics are generated from metrics. While preserving the original _batch_ and _non-batch_ options (rendering `batch` deprecated), the PR adds two new options, `field` and `homie-v4`. The `field` layout will generate one topic per metric field only containing the field value in string format (solving #10732). The `homie-v4` layout allows to output metrics in topics adhering to the [Homie v4.0 specification](https://homieiot.github.io/specification/spec-core-v4_0_0), a standard used for M2M and home-automation purposes.
> feat(outputs.mqtt): Add option to specify topic layouts

- plugins/inputs/win_eventlog/README.md
- plugins/inputs/win_eventlog/sample.conf
- plugins/inputs/win_eventlog/win_eventlog_notwindows.go
- plugins/inputs/win_perf_counters/README.md
- plugins/inputs/win_perf_counters/sample.conf
- plugins/inputs/win_perf_counters/win_perf_counters_notwindows.go
- plugins/inputs/win_services/README.md
- plugins/inputs/win_services/sample.conf
- plugins/inputs/win_services/win_services_notwindows.go
- plugins/inputs/win_wmi/README.md
- plugins/inputs/win_wmi/sample.conf
- plugins/inputs/win_wmi/win_wmi_notwindows.go
Using the existing `telegraf config` subcommand we can generate the included sample config for users. With the goal of having all sample config options in one file, versus having one for Windows and one for non-Windows, this enables creating the file on non-Windows systems.
> chore: Enable printing Windows sample configs on non-Windows

- plugins/aggregators/derivative/README.md
Some of the derivative calcs are a little confusion and not straightforward. This adds the explanation column to one of the examples and updates it with the correct values.
> docs(aggregators.derivative): add explanation of calculations

- internal/rotate/file_writer.go
- internal/rotate/file_writer_test.go
The current code will rotate a log on a SIGHUP. Whether the log needs to be rotated or not. There are checks at start-up and at each write if a log needs to be rotated. Meaning that we should not be forcing a rotation at close, and instead check to verify the conditions are even met first.
fixes: #12709
> fix(agent): Only rotate log on SIGHUP if needed

- plugins/inputs/intel_pmu/README.md
- plugins/inputs/intel_pmu/sample.conf
- plugins/inputs/intel_rdt/README.md
- plugins/inputs/intel_rdt/sample.conf
- plugins/inputs/mdstat/README.md
- plugins/inputs/mdstat/sample.conf
- plugins/inputs/postfix/README.md
- plugins/inputs/postfix/sample.conf
- plugins/inputs/ras/README.md
- plugins/inputs/ras/sample.conf
- plugins/inputs/sensors/README.md
- plugins/inputs/sensors/sample.conf
- plugins/inputs/slab/README.md
- plugins/inputs/slab/sample.conf
- plugins/inputs/socketstat/README.md
- plugins/inputs/socketstat/sample.conf
- plugins/inputs/sysstat/README.md
- plugins/inputs/sysstat/sample.conf
- plugins/inputs/varnish/README.md
- plugins/inputs/varnish/sample.conf
Adds a note to the config for linux-only or non-windows only plugins as well as any arch limitations.
> chore: document linux only plugins (part 2)

- cmd/telegraf/main.go
In v1.25.0 we introduced secret-stores (PR #11232) and with this added a call to `memguard.CatchInterrupt()` however, this created a race-condition with the usual signal handling in  [telegraf](https://github.com/influxdata/telegraf/blob/f87916aaa96368ca6d8a2de3e38a513785a1ee99/cmd/telegraf/telegraf.go#L127) where almost always `memguard` was successful in calling `os.Exit` __before__ the agent finished shutting down the plugins etc.
This PR removes the call to `memguard.CatchInterrupt()`. This is safe as we handle interrupts already and use the `defer memguard.Purge()` statement to safely erase all secrets.
> fix(agent): Allow gracefull shutdown on interrupt (e.g. Ctrl-C)

- .github/workflows/golangci-lint.yml
- Makefile
- internal/docker/docker.go
- internal/internal_test.go
- plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go
- plugins/inputs/ping/ping_notwindows.go
- plugins/inputs/sqlserver/connectionstring.go
Bump contains two patch releases:
https://github.com/golangci/golangci-lint/releases/tag/v1.51.1
https://github.com/golangci/golangci-lint/releases/tag/v1.51.2
New findings fixed:
```
internal/docker/docker.go:19:2                                                       ineffassign  ineffectual assignment to imageName
internal/internal_test.go:47:39                                                      nolintlint   directive `//nolint:unused // Used in skipped tests` is unused for linter "unused"
plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go:83:1  nolintlint   directive `//nolint:unused // Used in skipped tests` is unused for linter "unused"
plugins/inputs/ping/ping_notwindows.go:204:2                                         ineffassign  ineffectual …
```
> chore: Bump golangci-lint from v1.51.0 to v1.51.2

- plugins/inputs/statsd/statsd.go
If we attempt to close a listener that is nil, telegraf will panic. This
can occur if the port is already in use and we never start the listener.
For example, in test mode.
fixes: #12744
> fix(inputs.statsd): On close, verify listener is not nil

- go.mod
- plugins/common/opcua/opcua_util.go
- plugins/inputs/aliyuncms/aliyuncms.go
- plugins/inputs/aliyuncms/aliyuncms_test.go
- plugins/inputs/aliyuncms/discovery.go
- plugins/inputs/ethtool/ethtool_linux.go
- plugins/inputs/ethtool/ethtool_test.go
- plugins/inputs/filecount/filecount.go
- plugins/outputs/sumologic/sumologic.go
[github.com/pkg/errors](https://github.com/pkg/errors) has been deprecated and archived: https://github.com/pkg/errors/issues/245
I don't think we still need to use it after all error wrapping done in https://github.com/influxdata/telegraf/pull/12701 https://github.com/influxdata/telegraf/pull/12702 https://github.com/influxdata/telegraf/pull/12704 https://github.com/influxdata/telegraf/pull/12723 https://github.com/influxdata/telegraf/pull/12731 https://github.com/influxdata/telegraf/pull/12733 https://github.com/influxdata/telegraf/pull/12772 and enabling [errorlint](https://github.com/polyfloyd/go-errorlint) for guarding it in https://github.com/influxdata/telegraf/pull/12785.
It needs to still be our indirect dependency and cannot be removed from `LICENSE_OF_DEPENDENCIES.md` because …
> chore: Remove usages of github.com/pkg/errors dependency (archived)

- Makefile
This will use cat in the makefile for all systems and prompts, except for on Windows where a user is using PowerShell or Command Prompt. That way existing usage of bash on Windows continues to work as expected.
Using file is only supported on Makefile 4.2.1 and newer. Which is not available in OS X and older RHEL 7 for example.
fixes: #12573
> chore: use type on powershell/command prompt only

- plugins/inputs/cgroup/README.md
- plugins/inputs/cgroup/sample.conf
- plugins/inputs/diskio/README.md
- plugins/inputs/diskio/sample.conf
- plugins/inputs/dmcache/README.md
- plugins/inputs/dmcache/sample.conf
- plugins/inputs/ethtool/README.md
- plugins/inputs/ethtool/sample.conf
- plugins/inputs/infiniband/README.md
- plugins/inputs/infiniband/sample.conf
- plugins/inputs/kernel/README.md
- plugins/inputs/kernel/sample.conf
- plugins/inputs/nats/README.md
- plugins/inputs/nats/sample.conf
- plugins/inputs/processes/README.md
- plugins/inputs/processes/sample.conf
- plugins/inputs/synproxy/README.md
- plugins/inputs/synproxy/sample.conf
- plugins/inputs/wireless/README.md
- plugins/inputs/wireless/sample.conf
- plugins/inputs/zfs/README.md
- plugins/inputs/zfs/sample.conf
Specify distro support for a few more input plugins that were missed in previous versions.
> chore: specify distro support (part 3)

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/sample.conf
The Prometheus input plugin uses the `plugins/common/tls`, hence this alignment of the tls parameters documenatation.
resolves #
> Add optional tls parameters to the documentation of the Prometheus Input Plugin

- plugins/inputs/docker_log/README.md
- plugins/inputs/docker_log/docker_log.go
- plugins/inputs/docker_log/sample.conf
finalizes PR #7749
finalizes PR #6863
follow up on PR #12166
This PR adds the ability to save the last processed message per container and continue reading those logs after a restart of Telegraf. It thus completes the attempts made in #6863 and #7749.
> feat(inputs.docker_log): Add state-persistence capabilities

- models/filter.go
- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/kubernetes.go
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/sample.conf
> feat(inputs.prometheus): use namespace annotations to filter pods to be scraped

- plugins/inputs/bcache/bcache_notlinux.go
- plugins/inputs/conntrack/conntrack_notlinux.go
- plugins/inputs/dpdk/dpdk_notlinux.go
- plugins/inputs/hugepages/hugepages_notlinux.go
- plugins/inputs/intel_dlb/intel_dlb_notlinux.go
- plugins/inputs/intel_pmu/intel_pmu_notamd64linux.go
- plugins/inputs/intel_powerstat/intel_powerstat_notlinux.go
- plugins/inputs/intel_rdt/intel_rdt_windows.go
- plugins/inputs/iptables/iptables_notlinux.go
- plugins/inputs/ipvs/ipvs_notlinux.go
- plugins/inputs/kernel/README.md
- plugins/inputs/kernel/kernel_notlinux.go
- plugins/inputs/kernel/sample.conf
- plugins/inputs/kernel_vmstat/kernel_vmstat_notlinux.go
- plugins/inputs/linux_cpu/linux_cpu_nonlinux.go
- plugins/inputs/lustre2/lustre2_notlinux.go
- plugins/inputs/mdstat/mdstat_notlinux.go
- plugins/inputs/postfix/postfix_windows.go
- plugins/inputs/ras/ras_notlinux.go
- plugins/inputs/sensors/sensors_notlinux.go
- plugins/inputs/slab/slab_notlinux.go
- plugins/inputs/socketstat/socketstat_windows.go
- plugins/inputs/sysstat/sysstat_notlinux.go
- plugins/inputs/varnish/varnish_windows.go
This will enable producing the same sample config across all OSes. This way no matter what binary a user has they can use the "config" subcommand to always get the full and complete sample configuration.
> chore: unify sample configs across OSes

- go.mod
- go.sum
To resolve #11823, we needed to downgrade the library version. I do have an upstream fix PR waiting to be reviewed, but it still needs to be. We already reverted this library once before, but dependobot came by and updated it and we both missed it :( I'll add a ban on this repo to dependobot until the PR is merged.
fixes: #11823
> chore(deps): bump github.com/karrick/godirwalk from v1.17.0 to v1.16.2

- plugins/inputs/cgroup/cgroup_linux.go
- plugins/inputs/cgroup/cgroup_test.go
- plugins/inputs/cgroup/testdata/cpu/cpu.stat
cgroup v2 mounted with `hierarchy=unified` do not provide cpuacct [0], so this PR adds `.` to valid characters in keys for key-value pairs, which in turn fixes parsing `cpu.stat`, making it possible to measure cpu usage on v2 cgroup mounts with hierarchy=unified (default since systemd v243).
[0] https://github.com/systemd/systemd/issues/13477
> feat(inputs.cgroup): Added support for cpu.stat

- cmd/telegraf/cmd_secretstore.go
- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- config/config.go
- plugins/secretstores/jose/jose.go
- [] Updated associated README.md.
resolves #12651
This PR adds a `--password` option to specify a secret-store password  via command-line to for example set-up Telegraf using a script.
> feat(agent): Add command-line option to specify password

- plugins/inputs/ethtool/ethtool_linux.go
Close the namespace to prevent constantly chewing up file descriptors on a system.
fixes: #12813
> fix(inputs.ethtool): close namespace

- plugins/inputs/amqp_consumer/amqp_consumer.go
If the connection to the brokers fails, stopping Telegraf will result in a panic as neither `cancel` nor `conn` is set. Prevent the panic by exiting early on `Stop()`.
> fix(inputs.amqp_consumer): Fix panic on Stop() if not connected successfully

- plugins/processors/converter/README.md
- plugins/processors/converter/converter.go
- plugins/processors/converter/converter_test.go
- plugins/processors/converter/sample.conf
This adds the timestamp and timestamp_format options to the converter processor. This allows users to take a tag or field and make it the metric timestamp. It uses the same format parsing code that is used throughout Telegraf.
fixes: #12746
> feat(processors.converter): convert tag or field as metric timestamp

- plugins/outputs/postgresql/README.md
The suggested values are dangerous unless there is a retention policy of only a few days because the amount of chunks being generated will require a staggering amount of JOINs leading to extremely bad query performance.
> docs(outputs.postgresql): Improve TimescaleDB config examples

- config/config.go
Print the config files or URLs that the agent loads to make clear what files are actually used.
fixes: #12826
> feat(agent): print configs that are loaded

- plugins/common/oauth/config.go
- plugins/outputs/http/README.md
- plugins/outputs/http/sample.conf
resolves #7847
Add `audience` parameter required for Auth0 tokens.
> feat(common.oauth): Add audience parameter

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/sample_register.conf
- plugins/inputs/modbus/sample_request.conf
- plugins/inputs/modbus/type_conversions.go
resolves #9284
This PR adds the ability to specify an output-datatype for _coil_ and _discrete_ registers. You can choose between `UINT16` (default) and `BOOL`. The former is used currently and will be used as default when the datatype is omitted. The latter will case all non-zero registers to be emitted as `true` or `false` otherwise.
> feat(inputs.modbus): Allow to convert coil and discrete registers to boolean

- Makefile
This should not have been removed and not sure why it was part of a previous PR.
fixes: #12846
> fix(makefile): re-add build tags flag to go build

- config/config.go
- plugins/outputs/graphite/README.md
- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/sample.conf
- plugins/outputs/instrumental/instrumental.go
- plugins/serializers/graphite/README.md
- plugins/serializers/graphite/graphite.go
- plugins/serializers/graphite/graphite_test.go
- plugins/serializers/registry.go
The graphite serializer is very strict as to what characters are allowed to pass through. This allows the user to override the regex used and specify their own.
fixes: #12832
> fix(serializers.graphite): allow for specifying regex to sanitize

- plugins/inputs/internet_speed/README.md
- plugins/inputs/internet_speed/internet_speed.go
This avoids conflict with the global 'host' tag.
fixes: #12876
> fix(inputs.internet_speed): rename host tag to source

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/inputs/prometheus/sample.conf
* Only print deprecation warning if response_timeout is used
* Only set timeouts with response_timeout if it is set
* Allow the use of the timeout param in TOML
* Use HTTPClientConfig default of 5s timeout (versus 3s)
* Update tests
fixes: #12859
> fix(inputs.prometheus): correctly set timeout param

- plugins/common/opcua/client.go
- plugins/common/opcua/opcua_util.go
- plugins/inputs/opcua/README.md
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/subscribe_client.go
resolves #12862
This PR adds support for secret-store secrets for the `username` and `password` setting in `inputs.opcua` and `inputs.opcua_listener`.
> feat(common.opcua): Add support for secret-store secrets

- .circleci/config.yml
The gen1 macos runners are deprecated and getting removed in the fall of this year. Update to gen2 and update the version of code.
https://discuss.circleci.com/t/macos-resource-deprecation-update
> chore: update circleci macos runners

- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
Missed adding this correctly to the graphite output, only the parser in a previous PR.
fixes: #12832
> fix(outputs.graphite): add custom regex to outputs

- .github/workflows/govulncheck.yml
Bump github action to latest version.
> chore(deps): Bump govulncheck-action from 0.0.9 to 0.10.0

- plugins/common/proxy/socks5_test.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/x509_cert/x509_cert_test.go
Do not bind to all interfaces during tests, specify localhost
> chore: fix gosec G102 issues

- .golangci.yml
Enable following rules for [gosec](https://github.com/securego/gosec) (agreed with community):
- G106: Audit the use of ssh.InsecureIgnoreHostKey
- G108: Profiling endpoint automatically exposed on /debug/pprof
- G109: Potential Integer overflow made by strconv.Atoi result conversion to int16/32
- G111: Potential directory traversal
- G201: SQL query construction using format string
- G203: Use of unescaped data in HTML templates
resolves: https://github.com/influxdata/telegraf/issues/12893 https://github.com/influxdata/telegraf/issues/12895 https://github.com/influxdata/telegraf/issues/12896 https://github.com/influxdata/telegraf/issues/12898 https://github.com/influxdata/telegraf/issues/12902 https://github.com/influxdata/telegraf/issues/12904
> chore: Enable G106, G108, G109, G111, G201, G203 rules for gosec

- .github/workflows/govulncheck.yml
The latest govulcheck version changed the report formatting which is not yet picked up by the github action. Bug filed upstream as https://github.com/Templum/govulncheck-action/issues/33.
> fix(govulncheck): Downgrade govulncheck to fix github action

- plugins/inputs/execd/README.md
- plugins/inputs/execd/execd.go
- plugins/inputs/execd/sample.conf
Resolves #12934
- Fixed code for reading stdout from the underlying command. See #12934 for details.
- Introduced additional parameter to control the buffer size (in kb) used to read the stream. Not strictly required, but handy.
> fix(inputs.execd): read from stdout using ReadLine instead of scanner.Scan to overcome 64kb buffer limit

- .golangci.yml
- plugins/common/proxy/socks5_test.go
resolves https://github.com/influxdata/telegraf/issues/12890
> chore: Enable G102 rule for gosec

- plugins/outputs/http/README.md
- plugins/outputs/http/sample.conf
Updated outputs.http README & sample.conf to reflect un-documented requirement for aws_service to be set to a non-empty string in order for Amazon Credentials to be attempted, as was pointed out to me in the code:
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/http/http.go#L77-L82
On branch aws_service_docs
Changes to be committed:
modified:   README.md
modified:   sample.conf
resolves #
> Tweak outputs.http Docs For aws_service Reqs.

- cmd/telegraf/telegraf.go
- cmd/telegraf/telegraf_posix.go
- cmd/telegraf/telegraf_windows.go
- config/config.go
- config/secret.go
relates to #12980 
Plugins using secrets rely on locked memory in Telegraf. Due to limitations in the underlying library, each secret will use two pages of (locked) memory for the access time. Some operating systems or operators set a low limit on the maximum allowed amount of locked memory, making Telegraf hang (see #12924 or #12980) or panic of too many secrets are accessed at the same time. To be on the safe-side, warn the user if the limit set by the OS is too low for the number of secrets managed.
> fix(secrets): Warn if OS limit for locked memory is too low

- config/secret.go
- config/secret_test.go
- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
- plugins/inputs/sqlserver/azuresqldbqueries_test.go
- plugins/inputs/sqlserver/azuresqlmanagedqueries_test.go
- plugins/inputs/sqlserver/azuresqlpoolqueries_test.go
- plugins/inputs/sqlserver/sqlserver.go
- plugins/inputs/sqlserver/sqlserver_test.go
resolves #12916
When dealing with arrays of secrets (`[]config.Secret`) the unlinked secret is not kept in the array leading to unresolved secrets. The main reason is that the array is referenced by value and thus the modifications done by config during unlinking are discarded. This PR changes the occurrences of secret arrays to be an array of pointers and thus fixing the issue.
> fix(secretstores): Handle array of secrets correctly

- plugins/inputs/sqlserver/sqlserverqueries.go
resolves #12978
In SQLServerRequests, converted THROW to RAISERROR for 2008 compatibility
> fix(inputs.sqlserver): Converted THROW to RAISERROR for 2008 compatibility

- .golangci.yml
- plugins/outputs/cratedb/cratedb_test.go
resolves https://github.com/influxdata/telegraf/issues/12903
> chore: Enable G202 rule for gosec

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/system/ps.go
Updates the version of gopsutil as well as re-adds the warning check.
fixes: #12841
> chore(deps): Bump github.com/shirou/gopsutil from 3.23.2 to 3.23.3

- plugins/inputs/procstat/procstat.go
> fix(inputs.procstat): return tags of pids if lookup_error

- .golangci.yml
- tools/license_checker/package.go
resolves https://github.com/influxdata/telegraf/issues/12894
> chore: Enable G107 rule for gosec

- .golangci.yml
- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
resolves https://github.com/influxdata/telegraf/issues/12889
> chore: Enable G101 rule for gosec

- .golangci.yml
- plugins/inputs/filestat/filestat.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook.go
- plugins/inputs/webhooks/github/github_webhooks.go
resolves https://github.com/influxdata/telegraf/issues/12946
resolves https://github.com/influxdata/telegraf/issues/12948
resolves https://github.com/influxdata/telegraf/issues/12950
resolves https://github.com/influxdata/telegraf/issues/12951
resolves https://github.com/influxdata/telegraf/issues/12952
resolves https://github.com/influxdata/telegraf/issues/12954
> chore: Enable G401, G403, G501, G502, G503 and G505 rules for gosec

- .golangci.yml
resolves https://github.com/influxdata/telegraf/issues/12942
resolves https://github.com/influxdata/telegraf/issues/12944
> chore: Enable G303 and G305 rules for gosec

- tools/package_lxd_test/main.go
Ubuntu Bionic is about to hit EOL at the end of the month. Debian Buster is about to become old, old stable.
> chore: update lxd images for testing

- plugins/inputs/socket_listener/socket_listener_test.go
- plugins/inputs/socket_listener/stream_listener.go
This fixes an issue where the code would lose track of unix sockets. The remote end of a unix socket does not have a unique address representation, thus multiple entries may overwrite each other in the map. This changes the map to key off the net.Conn object itself, basically using the map as a set.
Fixes #13058
resolves #
> fix(inputs.socket_listener): fix tracking of unix sockets

- .circleci/config.yml
Apparently, CircleCI doesn't sanitize against misspellings of "fingerprints" as this was able to run in my personal CircleCI without issue.
> fix: correct spelling of "fingerprints".

- plugins/inputs/prometheus/kubernetes.go
resolves #12780 
Fixed creation of Informer Factory to include given namespace, if present in the config under `monitor_kubernetes_pods_namespace` option. This is needed because if the option is specified, then only that namespace will be scraped, meaning only a Role is needed, not a ClusterRole. Until now a ClusterRole was always needed, because the Informer by default always used resources across all namespaces. This is an issue if you only have access to create a Role, but not a ClusterRole.
> fix(inputs.prometheus): Pass namespace to k8s informer factory

- plugins/parsers/grok/parser.go
- plugins/parsers/grok/parser_test.go
When parsing multiline inputs that do not match the given pattern the parser currently returns a `nil` metric in the `metrics` array. In turn this can lead to a panic when the parent plugin loops through the returned metrics and tries to process them  (e.g. `inputs.tail`).
This PR checks if the metric is `nil` and does not add it to the returned metrics array. Thus the array is empty and upstream plugins will not panic.
> fix(parsers.grok): Fix nil metric for multiline inputs

- .golangci.yml
- internal/content_coding.go
- internal/content_coding_test.go
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/amqp_consumer/amqp_consumer_test.go
- plugins/inputs/amqp_consumer/sample.conf
- plugins/inputs/socket_listener/README.md
- plugins/inputs/socket_listener/packet_listener.go
- plugins/inputs/socket_listener/sample.conf
- plugins/inputs/socket_listener/socket_listener.go
- plugins/outputs/graylog/graylog_test_linux.go
- plugins/outputs/logzio/logzio_test.go
- plugins/outputs/sumologic/sumologic_test.go
resolves https://github.com/influxdata/telegraf/issues/12897
> chore: Enable G110 rule for gosec

- plugins/processors/aws/ec2/README.md
- plugins/processors/aws/ec2/ec2.go
- plugins/processors/aws/ec2/ec2_test.go
- plugins/processors/aws/ec2/sample.conf
This patch adds opt-in caching of ec2 tags and imds data. This can be useful in improving performance of telegraf for tags which do not change frequently (or ever).
resolves #12881 
Three new fields were added to the AWS EC2 processor
* cache_ttl
* tag_cache_size
* log_cache_stats
The code itself was modeled after the postgresql output plugin which uses the freecache golang module. This was deemed to be a more simple approach than the original idea of re-using patterns in the dns_resolver plugin. For the purposes here, the simplicity of the freecache approach overruled the features of the dns_resolver approach.
The changes are opt-in. The existing behavior of the processor is retained for users who do not wish to use caching.
For those who do wish to use caching, the log_cache_stats …
> feat(processors.aws_ec2): add caching of imds and ec2 tags

- metric/tracking.go
- plugins/processors/lookup/lookup.go
- plugins/processors/lookup/lookup_test.go
- plugins/processors/lookup/testcases/non_existing_tag/expected.out
- plugins/processors/lookup/testcases/non_existing_tag/input.influx
- plugins/processors/lookup/testcases/non_existing_tag/lut.json
- plugins/processors/lookup/testcases/non_existing_tag/telegraf.conf
resolves #13077 
When using the lookup processor with **tracking** metrics the template cannot access the template-specific functions of the embedded metric. Therefore, the lookup processor will fail as described in #13077.
This PR adds the possibility to "unwrap" the tracked metric and directly access the inner raw metric. We then use the new possibility to fix the lookup processor.
> fix(processors.lookup): Fix tracking metrics

- plugins/outputs/warp10/warp10.go
- plugins/outputs/warp10/warp10_test.go
- testutil/testutil.go
> fix(outputs.warp10): Support Infinity/-Infinity/NaN values

- logger/event_logger.go
- logger/event_logger_test.go
- plugins/inputs/win_eventlog/util.go
- plugins/inputs/win_eventlog/win_eventlog.go
- plugins/inputs/win_eventlog/zsyscall_windows.go
- plugins/inputs/win_perf_counters/pdh.go
- plugins/inputs/win_perf_counters/pdh_amd64.go
- plugins/inputs/win_perf_counters/performance_query.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_test.go
- plugins/inputs/win_services/win_services_test.go
It is only part of the bigger job: https://github.com/influxdata/telegraf/issues/13036
After all findings in whole project are handled for `Windows`, linter CI job for Windows can be enabled.
Fixes for following linters have been made:
- `gosec`
- `ineffassign`
- `interfacebloat`
- `lll`
- `nakedret`
- `nilerr`
- `prealloc`
- `staticcheck`
- `unconvert`
Following findings were addressed:
```
logger\event_logger.go:42:2                                                   nakedret        naked return in func `Write` with 18 lines of code
logger\event_logger_test.go:33                                                lll             line is 162 characters
plugins\inputs\win_eventlog\util.go:47:82                                     unconvert       unnecessary conversion …
```
> chore: Fix linter findings for Windows (part2)

- .circleci/config.yml
This fixes several issues with the `release` workflow. `packages-sign` now generates a `*.DIGESTS` file each artifact. It also accumulates all artifact checksums and signatures into `telegraf-${CIRCLE_TAG}-digests`. The release workflow has been updated to only upload filenames that begin with `telegraf*` to avoid uploading the unsigned `dmg` images.
This also corrects the misspelling of "fingerprints". Which, surprisingly, didn't cause the CircleCI workflow to fail.
> fix: update release workflow

- Makefile
follow-up: https://github.com/influxdata/telegraf/pull/13110
> chore: Bump golangci-lint from v1.51.2 to v1.52.2

- go.mod
- go.sum
- plugins/inputs/intel_pmu/README.md
- plugins/inputs/intel_pmu/intel_pmu.go
Intel PMU plugin stopped working after introducing new version of json perfmon format.
This PR fixes this bug. More info can be found inside on [issue](https://github.com/intel/perfmon/issues/22). 
Old event format is still accepted.
> fix(inputs.intel_pmu): fix handling of the json perfmon format

- plugins/inputs/gnmi/handler.go
Creates metric for each connection source, with 1 as connected and 0 as disconnected.
fixes: #13088
> fix(inputs.gnmi): create selfstat to track connection state

- plugins/inputs/filecount/README.md
- plugins/inputs/filecount/filecount.go
- plugins/inputs/filecount/filecount_test.go
- plugins/inputs/filecount/sample.conf
Add fields like :
oldest_file_timestamp
newest_file_timestamp
Use case:
With this two fields, we can generate alarming if nothing append in the directeory.
For exemple if we wait for daily file reception.
resolves https://github.com/influxdata/telegraf/issues/11087
> feat(inputs.filecount): Add oldestFileTimestamp and newestFileTimestamp

- go.mod
- go.sum
this PR bumps the wavefront golang SDK version to the new v0.13.0 release
resolves #13166
> chore(deps): Bump github.com/wavefronthq/wavefront-sdk-go from 0.12.0 to 0.13.0

- internal/content_coding.go
- plugins/inputs/cloud_pubsub/README.md
- plugins/inputs/cloud_pubsub/cloud_pubsub.go
- plugins/inputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/inputs/cloud_pubsub/sample.conf
- plugins/outputs/cloud_pubsub/README.md
- plugins/outputs/cloud_pubsub/cloud_pubsub.go
- plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/outputs/cloud_pubsub/sample.conf
- plugins/outputs/cloud_pubsub/topic_stubbed.go
resolves #9157 
Revives a [PR](https://github.com/influxdata/telegraf/pull/9159) that was adding support for Cloud PubSub gzip compression
> feat(cloud_pubsub): Add support for gzip compression

- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/stackdriver/stackdriver_test.go
In a perfect world, metrics come in to stackdriver grouped by timestamp
and all the timestamps are the same. This means that metrics go out
together and a user never has to worry about out of order metrics.
The world however is not perfect.
In the event that the connection to stackdriver goes down, telegraf will
start to save metrics to a buffer. Once reconnected, telegraf will send
a batch size of data to stackdriver to send. Stackdriver would then
ensure the metrics are sorted, but then break the metrics into
timeseries. In doing so metrics would no longer be in any order and
metrics could send duplicate time series. Meaning two idential metrics,
but with different time stamps.
What the user would see is first a message about duplicate timeseries
and then an error about out of order …
> fix(outputs.stackdriver): group batches by timestamp

- plugins/outputs/loki/README.md
- plugins/outputs/loki/loki.go
- plugins/outputs/loki/loki_test.go
- plugins/outputs/loki/sample.conf
This allows the user to specify the label name used to store the metric name. This label was added in #10001, but a user may not want this value in which case they could set it to an empty string or use some other customer value.
fixes: #13146
> feat(outputs.loki): add option for metric name label

- plugins/inputs/win_perf_counters/kernel32.go
- plugins/inputs/win_perf_counters/pdh.go
- plugins/inputs/win_perf_counters/pdh_386.go
- plugins/inputs/win_perf_counters/pdh_amd64.go
- plugins/inputs/win_perf_counters/pdh_arm64.go
- plugins/inputs/win_perf_counters/performance_query.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_test.go
It is only part of the bigger job: https://github.com/influxdata/telegraf/issues/13036
After all findings in whole project are handled for `Windows`, linter CI job for Windows can be enabled.
Fixes for following findings in `plugins/inputs/win_perf_counters/...` have been made:
```
plugins/inputs/win_perf_counters/kernel32.go:40:2                              unused  field `wYear` is unused
plugins/inputs/win_perf_counters/kernel32.go:41:2                              unused  field `wMonth` is unused
plugins/inputs/win_perf_counters/kernel32.go:42:2                              unused  field `wDayOfWeek` is unused
plugins/inputs/win_perf_counters/kernel32.go:43:2                              unused  field `wDay` is unused
plugins/inputs/win_perf_counters/kernel32.go:44:2 …
```
> chore: Fix linter findings for Windows (part3)

- plugins/common/kafka/sasl.go
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
A common question from users is why this is experimental or what is left. To my knowledge, nothing about it is experimental and at this time any issues found are real issues, either in telegraf or in the upstream sarama library.
> docs(common.kafka): remove experimental notes

- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
lint and tests summary:
make lint	Unrelated error: `SECURITY.md:6:46 MD034/no-bare-urls Bare URL used [Context: "security@influxdata.com"]`?
make check  	OK
make check-deps OK
make test	OK
make docs	OK
resolves #13228
- Fixes the logic of which servers to reconnect to when they were not up on initial connect
- In the previous code, failed servers were appended to a local variable but then the code checks a different variable if a reconnect is needed
- This PR adds a fix and a test to verify the correct variable is used
> fix(outputs.graphite): Fix logic to reconnect with servers that were not up on agent startup (#13228)

- docs/DATA_FORMATS_OUTPUT.md
- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/serializers/all/cloudevents.go
- plugins/serializers/cloudevents/README.md
- plugins/serializers/cloudevents/cloudevents.go
- plugins/serializers/cloudevents/cloudevents_test.go
- plugins/serializers/cloudevents/testcases/batch-events/expected.json
- plugins/serializers/cloudevents/testcases/batch-events/input.influx
- plugins/serializers/cloudevents/testcases/batch-events/telegraf.conf
- plugins/serializers/cloudevents/testcases/batch-metrics/expected.json
- plugins/serializers/cloudevents/testcases/batch-metrics/input.influx
- plugins/serializers/cloudevents/testcases/batch-metrics/telegraf.conf
- plugins/serializers/cloudevents/testcases/cloudevents-v0.3-schema.json
- plugins/serializers/cloudevents/testcases/cloudevents-v1.0-schema.json
- plugins/serializers/cloudevents/testcases/single-multiple/expected.json
- plugins/serializers/cloudevents/testcases/single-multiple/input.influx
- plugins/serializers/cloudevents/testcases/single-multiple/telegraf.conf
- plugins/serializers/cloudevents/testcases/single-source-overwrite/expected.json
- plugins/serializers/cloudevents/testcases/single-source-overwrite/input.influx
- plugins/serializers/cloudevents/testcases/single-source-overwrite/telegraf.conf
- plugins/serializers/cloudevents/testcases/single-sourcetag-overwrite/expected.json
- plugins/serializers/cloudevents/testcases/single-sourcetag-overwrite/input.influx
- plugins/serializers/cloudevents/testcases/single-sourcetag-overwrite/telegraf.conf
- plugins/serializers/cloudevents/testcases/single/expected.json
- plugins/serializers/cloudevents/testcases/single/input.influx
- plugins/serializers/cloudevents/testcases/single/telegraf.conf
resolves #10170
This PR adds a serializer to convert Telegraf metrics into the [CloudEvents](https://cloudevents.io/) JSON format.
> feat(serializers): Add CloudEvents serializer

- plugins/processors/scale/README.md
- plugins/processors/scale/sample.conf
- plugins/processors/scale/scale.go
- plugins/processors/scale/scale_test.go
resolves #9725
This PR allows to specify a factor and offset to scale input fields instead of using input and output ranges. This is helpful if the ranges are arbitrary but linear scaling properties are known.
> feat(processors.scale):  Add scaling by factor and offset

- .golangci.yml
resolves https://github.com/influxdata/telegraf/issues/13172 (argOrder)
resolves https://github.com/influxdata/telegraf/issues/13173 (badCall)
resolves https://github.com/influxdata/telegraf/issues/13174 (badCond)
resolves https://github.com/influxdata/telegraf/issues/13175 (badLock)
resolves https://github.com/influxdata/telegraf/issues/13177 (badSorting)
resolves https://github.com/influxdata/telegraf/issues/13178 (builtinShadowDecl)
resolves https://github.com/influxdata/telegraf/issues/13179 (caseOrder)
resolves https://github.com/influxdata/telegraf/issues/13180 (codegenComment)
resolves https://github.com/influxdata/telegraf/issues/13185 (dupBranchBody)
resolves https://github.com/influxdata/telegraf/issues/13186 (dupCase)
resolves https://github.com/influxdata/telegraf/issues/13187 …
> chore: Enable the easiest checkers for gocritic

- plugins/inputs/directory_monitor/README.md
- plugins/inputs/directory_monitor/directory_monitor.go
This to better distinguish between 2 directory_monitor instances and the files they processed/dropped.
> feat(inputs.directory_monitor): Improve internal stats

- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/azurearcsqlmiqueries.go
- plugins/inputs/sqlserver/azurearcsqlmiqueries_test.go
- plugins/inputs/sqlserver/sample.conf
- plugins/inputs/sqlserver/sqlserver.go
resolves [#13145](https://github.com/influxdata/telegraf/issues/13145)
Add an sqlserver input plugin to support Azure Arc-enabled SQL Managed Instance. Currently, the plugin is not able to support the Azure Arc-enabled SQL MI due to engine edition checking.
> feat(inputs.sqlserver): add Azure Arc-enabled SQL MI support

- plugins/processors/template/README.md
- plugins/processors/template/sample.conf
- plugins/processors/template/template.go
- plugins/processors/template/template_test.go
This PR allows the `tag` option to also be a Go template to make it more flexible.
> feat(processors.template): Allow `tag` to be a template

- cmd/telegraf/main.go
Clarify that the watch config option only works with the --config and --config-directory options.
fixes: #13272
> docs: clarify watch config behavior

- plugins/inputs/nats_consumer/README.md
- plugins/inputs/nats_consumer/nats_consumer.go
- plugins/inputs/nats_consumer/nats_consumer_test.go
resolves #11736
This PR adds the receiver subject as tag to the metrics. Furthermore, the PR adds a simple integration test to check sending and receiving of topics.
> feat(inputs.nats_consumer): Add receiver subject as tag

- config/config.go
- config/config_test.go
- plugins/outputs/sumologic/sumologic.go
- plugins/outputs/sumologic/sumologic_test.go
- plugins/serializers/all/carbon2.go
- plugins/serializers/carbon2/carbon2.go
- plugins/serializers/carbon2/carbon2_test.go
- plugins/serializers/registry.go
This PR migrates the carbon2 serializer to the new-style framework.
> chore(serializers.carbon2): Migrate to new-style framework

- plugins/inputs/socket_listener/socket_listener_test.go
This PR tries to fix a race in the unit-test observed on CI.
```text
=== Failed
=== FAIL: plugins/inputs/socket_listener TestSocketListener/TCP_with_TLS (0.28s)
2023/05/19 19:23:12 I! [] Listening on tcp://127.0.0.1:49719
==================
WARNING: DATA RACE
Read at 0x00c0005a6960 by goroutine 51:
reflect.maplen()
C:/Program Files/Go/src/runtime/map.go:1394 +0x0
reflect.Value.lenNonSlice()
C:/Program Files/Go/src/reflect/value.go:1704 +0x26d
reflect.Value.Len()
C:/Program Files/Go/src/reflect/value.go:1693 +0x290
github.com/stretchr/testify/assert.isEmpty()
C:/Users/circleci.PACKER-64370BA5/go/pkg/mod/github.com/stretchr/testify@v1.8.2/assert/assertions.go:567 +0x281
github.com/stretchr/testify/assert.NotEmpty()
C:/Users/circleci.PACKER-64370BA5/go/pkg/mod/github.com/stretchr/testify@v1.8 …
```
> fix(inputs.socket_listener): Fix race in tests

- plugins/inputs/system/ps.go
Currently, we are ignoring errors and only returning an "error" for warnings. This is the opposite of what we want. Instead, we are supposed to check for warnings and ignore these, but error on anything else.
fixes: #13308
> fix(inputs.temp): ignore warnings, return errors

- plugins/processors/lookup/lookup.go
- plugins/processors/lookup/lookup_test.go
resolves #
Currently, the tracking info of tracking-metrics is stripped by the lookup processors resulting in input plugins never receiving a notification from the output side as the output cannot know about tracking. This PR keeps the tracking info and extends the test-cases to verify that the tracking works.
The issue is described in a [community forum thread](https://community.influxdata.com/t/inputs-mqtt-consumer-stops-when-using-processors-lookup-after-some-time/29854/5),
> fix(processors.lookup): Do not strip tracking info

- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/testcases/issue_12931/expected.out
- plugins/inputs/gnmi/testcases/issue_12931/responses.json
- plugins/inputs/gnmi/testcases/issue_12931/telegraf.conf
- plugins/inputs/gnmi/utils.go
resolves #12931
The origin is optional and only required to disambiguate paths. This PR adapts the code to lookup both paths with and without origin to determine the metric name.
> fix(inputs.gnmi): Allow optional origin for update path 

- config/config.go
- plugins/serializers/all/csv.go
- plugins/serializers/csv/csv.go
- plugins/serializers/csv/csv_test.go
- plugins/serializers/registry.go
This PR migrates the csv serializer to the new-style framework.
> chore(serializers.csv): Migrate to new-style framework

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
This is a companion piece to https://github.com/influxdata/telegraf/pull/11816 and builds on top of it.  It uses a connection to the Kafka broker to determine which topics are available, match them with a regular expression.  This requires the set-metric-from-measurement in the Avro handler, which requires the schema registry, and therefore this is only useful in conjunction with the Avro parser.
In the Rubin Observatory use case, we connect to a Kafka broker with a large number of topics, which are added to dynamically, and we therefore require something like this.  (For the time being, we will restart the broker to pick up new topics; dynamic detection is a planned future enhancement.)
The motivation is that this is essentially the behavior that lensesio/stream-reactor gives with its …
> feat(inputs.kafka_consumer): Add regular expression support for topics

- plugins/outputs/wavefront/wavefront.go
resolves #10009
Fixes bug introduced in telegraf 1.25.0 where after brief period of ~10mins depending on metric load, telegraf begins erroring with `Error writing to outputs.wavefront: wavefront sending error: buffer full, dropping line`. This patch flushes the buffer when it becomes full and continues outputting as expected.
> fix(outputs.wavefront): flush metric buffer before reaching overflow

- plugins/inputs/netflow/netflow_decoder.go
related to #13305
related to #13320
This PR fixes a wrong element-ID to name mapping and decodes MAC addresses as such.
> fix(inputs.netflow): Fix field mappings

- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
This creates the stated default statefile directory and the file itself during package install. This does not enable the state file feature itself, but makes it available to a user post-install.
fixes: #13290
> chore: create default statefile and folder during package install

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/gnmi/testcases/canonical_field_names/expected.out
- plugins/inputs/gnmi/testcases/canonical_field_names/responses.json
- plugins/inputs/gnmi/testcases/canonical_field_names/telegraf.conf
resolves #12352
This PR adds an option to get the canonical path as field name instead of the name being a path relative to the subscription. This allows for a consistent field-name output when changing the configuration to subscribe more specific paths.
> feat(inputs.gnmi): Allow canonical field names

- config/config.go
- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
- plugins/outputs/instrumental/instrumental.go
- plugins/outputs/instrumental/instrumental_test.go
- plugins/outputs/sumologic/sumologic_test.go
- plugins/serializers/all/graphite.go
- plugins/serializers/graphite/graphite.go
- plugins/serializers/graphite/graphite_test.go
- plugins/serializers/registry.go
This PR migrates the graphite serializer to the new-style framework.
> chore(serializers.graphite): Migrate to new-style framework

- plugins/serializers/all/msgpack.go
- plugins/serializers/msgpack/msgpack.go
- plugins/serializers/registry.go
This PR migrates the message-pack serializer to the new-style framework.
> chore(serializers.msgpack): Migrate to new-style framework

- plugins/serializers/all/nowmetric.go
- plugins/serializers/nowmetric/nowmetric.go
- plugins/serializers/nowmetric/nowmetric_test.go
- plugins/serializers/registry.go
This PR migrates the nowmetric serializer to the new-style framework.
> chore(serializers.nowmetric): Migrate to new-style framework

- plugins/serializers/all/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
- plugins/serializers/registry.go
This PR migrates the prometheus remote-write serializer to the new-style framework.
> chore(serializers.prometheusremotewrite): Migrate to new-style framework

- config/config.go
- plugins/serializers/all/wavefront.go
- plugins/serializers/registry.go
- plugins/serializers/wavefront/wavefront.go
- plugins/serializers/wavefront/wavefront_test.go
This PR migrates the wavefront serializer to the new-style framework.
> chore(serializers.wavefront): Migrate to new-style framework

- plugins/inputs/cisco_telemetry_mdt/README.md
- plugins/inputs/cisco_telemetry_mdt/sample.conf
> docs(inputs.cisco_telemetry_mdt): specify max msg upper limit

- CONTRIBUTING.md
- plugins/inputs/bind/README.md
- plugins/outputs/clarify/README.md
This PR fixes the following linter issues found with markdownlint version 0.34.0:
```text
docs/developers/README.md:57:68 MD034/no-bare-urls Bare URL used [Context: "security@influxdata.com"]
plugins/inputs/bind/README.md:44:15 MD034/no-bare-urls Bare URL used [Context: "http://localhost:8053/xml/v3"]
plugins/outputs/clarify/README.md:86:1 MD053/link-image-reference-definitions Link and image reference definitions should be needed [Unused link or image reference definition: "clarifydoc"] [Context: "[clarifydoc]: https://docs.cla..."]
```
> docs: Fix markdownlinter issues

- .circleci/config.yml
This will update the name of the digests file that is produced to ensure it is uploaded to S3. Additionally, it removes the unneeded signatures and switches the order so that the hash is listed first, then the filename as is more common. As this is already produced in the individual digests we are essentially only combining them all into one.
> chore: produce single digest file with sha256sum

- config/config.go
- plugins/outputs/prometheus_client/v2/collector.go
- plugins/serializers/all/prometheus.go
- plugins/serializers/prometheus/collection.go
- plugins/serializers/prometheus/collection_test.go
- plugins/serializers/prometheus/prometheus.go
- plugins/serializers/prometheus/prometheus_test.go
- plugins/serializers/registry.go
This PR migrates the prometheus serializer to the new-style framework.
> chore(serializers.prometheus): Migrate to new-style framework

- config/config.go
- docs/CONFIGURATION.md
- models/running_input.go
- models/running_input_test.go
resolves #12361
Currently _all_ tags of a plugin are filtered using `taginclude` and `tagexclude`. This also includes tags explicitly declared in the plugin. As a result when defining
```toml
[[inputs.myplugin]]
taginclude = [ "namespace", "url" ]
[inputs.myplugin.tags]
app = "myapp"
```
the explicitly defined `app` tag will be filtered out. This PR adds a new `always_include_local_tags` agent option to override this behavior. When set to `true` _all_ locally defined tags are preserved and pass filtering.
> feat(agent): Add option to avoid filtering of explicit plugin tags

- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
The -h option is used to update a timestamp, but the file does not exist, so we do not want this option. Touch will not create the file when using this option either.
> chore: fix touch command

- go.mod
- go.sum
- plugins/inputs/internet_speed/internet_speed.go
This PR updates the speedtest-go package to get the fix https://github.com/showwin/speedtest-go/issues/127. Without this, Telegraf will discard all log messages after the `inputs.internet_speed` plugin is imported due to a `log.SetOutput(io.Discard)` call in that package.
> chore(deps): Bump github.com/showwin/speedtest-go from 1.5.2 to 1.6.2

- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/testcases/canonical_field_names/expected.out
- plugins/inputs/gnmi/testcases/canonical_field_names/telegraf.conf
resolves #12352
Fix canonical field names for cases where we do not have a subscription that exactly matches the path. Also adapted the unit-test to cover that code-path.
> fix(inputs.gnmi): Handle canonical field-name correctly for non-explicit subscriptions

- config/config.go
- config/config_test.go
- config/internal_test.go
- plugins/common/shim/config.go
- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/azure_data_explorer/azure_data_explorer_test.go
- plugins/outputs/event_hubs/event_hubs_test.go
- plugins/outputs/http/http_test.go
- plugins/outputs/stomp/stomp_test.go
- plugins/processors/lookup/lookup_test.go
- plugins/processors/registry.go
- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
When trying to fix the JSON serializers `json_timestamp_units` field-type to `config.Duration` a cyclic import was triggered for tests
```text
go test -short -race ./...
package github.com/influxdata/telegraf/config
imports github.com/influxdata/telegraf/plugins/serializers/json
imports github.com/influxdata/telegraf/plugins/serializers/all: import cycle not allowed in test
FAIL    github.com/influxdata/telegraf/config [setup failed]
```
This is due to the fact that `config_test.go`(being part of the `config` package) imports _all_ serializers (and parsers) and now the JSON serializer import `config`. The present PR moves all external tests of `config_test.go` to the `config_test` package and splits the internal ones to `internal_test.go` being part of the `config` package.
We then …
> chore(config): Split tests to avoid cyclic import

- CHANGELOG.md
- internal/internal.go
- internal/internal_test.go
- plugins/inputs/consul_agent/consul_agent.go
- plugins/inputs/nomad/nomad.go
- plugins/inputs/vault/vault.go
- plugins/parsers/binary/entry.go
- plugins/parsers/grok/parser.go
- plugins/parsers/grok/parser_test.go
- plugins/processors/converter/converter_test.go
resolves #12960
upstream issues https://github.com/golang/go/issues/56528, https://github.com/golang/go/issues/9617
Golang does not handle ambiguous timezones which holds true for almost all abbreviated timezones. As a workaround, (see [Golang discussion](https://groups.google.com/g/golang-nuts/c/hDMdnm_jUFQ/m/yeL9IHOsAQAJ)) we can parse times with abbreviated timezones first to get the timezone's _name_ and then forcefully parse the time-string in the found timezone. By doing this we can handle many of the abbreviated timezones correctly assuming the "most probable" of the ambiguous timezone abbreviations, e.g. "Mountain Standard Time" for "MST".
> fix(internal): Fix time parsing for abbreviated timezones

- plugins/outputs/wavefront/README.md
- plugins/outputs/wavefront/sample.conf
- plugins/outputs/wavefront/wavefront.go
- plugins/outputs/wavefront/wavefront_test.go
This PR adds configuration fields for the Wavefront output allowing users to provide TLS configuration and to set an HTTP Timeout. The underlying Wavefront SDK recently added its own hooks for configuring these settings.
> feat(outputs.wavefront): Add TLS and HTTP Timeout configuration fields

- plugins/processors/execd/testcases/defaults/telegraf.conf
This replaces the last `cat` instance in the `processors.execd` unit-tests that leads to flaky tests especially for MacOS...
> fix(CI): Replace last 'cat' instance in tests

- plugins/secretstores/os/README.md
- plugins/secretstores/os/sample.conf
Clarify the ordering of the Window's secret store and give better
instructions as to how to use it.
fixes: #13001
> docs(secretstores.os): clarify windows credential usage

- cmd/telegraf/cmd_secretstore.go
- cmd/telegraf/telegraf.go
- plugins/secretstores/README.md
- plugins/secretstores/http/README.md
- plugins/secretstores/http/sample.conf
This makes the following updates:
* Update generic secret store README with additional details
* Ensure `id` is in each sample config & README
* Hide loading files log message
* Enhance the enter secret message to make clearer
> chore: Clean up secret store usage

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
Currently, the paho.mqtt.golang client will ack messages as they come in. When the persistent session option a user would expect telegraf to ack the messages only once they have been sent or parsed sucessfully.
This disables the client's auto ack if persistent session is enabled. It also sets up telegraf to ack messages once they were sent. Additionally, if we fail to parse the message we will ack the message.
> fix(inputs.mqtt): ack messages when persistence enabled

- cmd/telegraf/cmd_config.go
- cmd/telegraf/cmd_secretstore.go
- cmd/telegraf/main.go
- config/config.go
- config/config_test.go
- config/internal_test.go
- config/migration.go
- migrations/all/all.go
- migrations/all/inputs_cassandra.go
- migrations/common/filter_options.go
- migrations/common/input_options.go
- migrations/inputs_cassandra/migration.go
- migrations/inputs_cassandra/migration_test.go
- migrations/inputs_cassandra/testcases/filter_options/expected.conf
- migrations/inputs_cassandra/testcases/filter_options/telegraf.conf
- migrations/inputs_cassandra/testcases/general_options/expected.conf
- migrations/inputs_cassandra/testcases/general_options/telegraf.conf
- migrations/inputs_cassandra/testcases/simple/expected.conf
- migrations/inputs_cassandra/testcases/simple/telegraf.conf
- migrations/registry.go
- tools/custom_builder/config.go
- tools/custom_builder/main.go
relates to ##13375
relates to ##13376
This PR adds a framework for migrating configurations containing deprecated plugins (and options). For new the use is demonstrated for the `inputs.cassandra` input plugin. The PR adds a `migrate` sub-command to the `config` command.
> feat(config): Add framework for migrating deprecated plugins

- plugins/outputs/all/nebius_cloud_monitoring.go
- plugins/outputs/nebius_cloud_monitoring/README.md
- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go
- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go
- plugins/outputs/nebius_cloud_monitoring/sample.conf
> feat(outputs): Add plugin for nebius cloud monitoring

- plugins/inputs/ravendb/README.md
- plugins/inputs/ravendb/ravendb.go
- plugins/inputs/ravendb/ravendb_dto.go
- plugins/inputs/ravendb/ravendb_test.go
- plugins/inputs/ravendb/testdata/databases_full.json
Added new disk storage metrics that are exposed in RavenDB. Changes are backward compatible with older versions that we still support.
> feat(inputs.ravendb): Added new disk metrics fields

- tools/package_lxd_test/container.go
The latest fedora image was not printing newlines during the echo, causing the repo file to be ignored and not being able to install telegraf as a result. Adding the -e to ensure the new lines are included. I was able to locally test the fedora images, but not the centos images as I don't have cgroup1 support.
This also prints out any repo file that is put into place to aid with debugging.
> test(package): fix set up of yum files

- .github/workflows/golangci-lint.yml
- .golangci.yml
- CODE_OF_CONDUCT.md
- Makefile
- SECURITY.md
Fixes issues with latest version of golanglint-ci and the changed depguard settings in the config.
Updates a few markdown linter bare URLs.
> chore: update golanglint-ci

- plugins/inputs/bcache/bcache_test.go
- plugins/inputs/lustre2/lustre2_test.go
- plugins/inputs/zfs/zfs_linux_test.go
Rather than using a hard-coded `/tmp/telegraf` path as a place for tmp files during testing, this updates the bcache, lustre2 and zfs input's tests to uses MkdirTemp function to create a unique path. This was discovered after checking out telegraf to `/tmp` and then running tests. Each of those tests will remove the directory I have checked out to.
> test: do not use /tmp/telegraf

- scripts/mac-signing.sh
Apple has deprecated `altool` and intends for `notarytool` to replace it. This replaces the `altool` in the mac signing script. The output for `notarytool`  uses a different syntax than `altool`. So, the code that validates that the notarization occurred had to be changed as well.
> fix: replace altool with notarytool

- config/config.go
- config/config_test.go
- config/internal_test.go
- config/testdata/single_plugin_env_vars.toml
resolves #13432 
This PR changes the shell-like expansion for environment variables to use a double dollar sign i.e. `$${...}` instead of `${...}` to prevent the substitution from rushing over previously valid, and non-substituted, uses of the single dollar expression in options (e.g. for templates).
By doing so, previous configurations using `$VAR` and `${VAR}` work as before, i.e. the former gets substituted by the environment variable content and the latter is left untouched. To use the new substitution with e.g. fallback use `$${VAR:-${FALLBACK}}`.
> fix(config): Move bracketed environment variable substitution to double-dollar

- plugins/inputs/fail2ban/README.md
- plugins/inputs/fail2ban/fail2ban.go
- plugins/inputs/fail2ban/sample.conf
This PR allows to specify the `socket` for `fail2ban-client` to read from via config setting. This is relevant if you host multiple fail2ban servers (each with a different socket). Another use-case is when running fail2ban in a Docker container and export the socket to a custom location via
```shell
```
> feat(inputs.fail2ban): Allow specification of socket

- tools/package_lxd_test/container.go
In #13435, the tests which use `dnf` as a package manager were updated to ensure newlines were printed. This updates the tests which use `yum`, which is the one test I was not able to run locally. 
Looking at the test output it is the same issue, when doing an `yum update`:
```s
File contains no section headers.
file: file:///etc/yum.repos.d/influxdata.repo, line: 1
'[influxdata]\\nname = InfluxData Repository - Stable\\nbaseurl = https://repos.influxdata.com/stable/x86_64/main\\nenabled = 1\\ngpgcheck = 1\\ngpgkey = https://repos.influxdata.com/influxdata-archive_compat.key\\n\n'
```
The echo did not format the entry correctly.
> test: Use -e to print newlines on yum tests

- plugins/inputs/openstack/README.md
- plugins/inputs/openstack/openstack.go
- plugins/inputs/openstack/sample.conf
> feat(inputs.openstack): Gather cinder services

- plugins/processors/execd/README.md
- plugins/processors/execd/sample.conf
- tools/custom_builder/config.go
- tools/custom_builder/main.go
- tools/custom_builder/packages.go
resolves #13441
This PR fixes the handling of serializers and solves #13441. During debugging I also noticed that, in case of multiple plugin instances, the default parser and serializer is not correctly selected if one of the other plugins already defines a `data_format`. Furthermore, `processors.execd` requires a special treatment as it requires both a serializer _and_ parser of the same type with the defined `data_format`. To handle those cases correctly the internal code had to be changed quite a bit but is much cleaner and much more robust IMO.
> fix(custom_builder): Correctly handle serializers and parsers

- internal/content_coding.go
- internal/content_coding_test.go
- plugins/inputs/amqp_consumer/amqp_consumer_test.go
replaces #13424
This PR maps the given, standardized compression level to the individual values for each compression algorithm. Furthermore, we add a function to map a string configuration value to the defined levels.
> fix: Handle compression level correctly for different algorithms

- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/testcases/field_request_too_short_issue_13482/init.err
- plugins/inputs/modbus/testcases/field_request_too_short_issue_13482/telegraf.conf
resolves #13482 
Check if the number of registers matches the field's datatype to prevent a panic.
> fix(inputs.modbus): Check number of register for datatype

- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/request.go
Currently the `max_insert` optimization cannot handle overlapping requests if e.g. requesting address `100` of type `INT64` (equals 4 registers) is followed by a field with address `102`. This PR fixes the optimization but warns the user about the overlap as this is only seldom a valid use-case.
> fix(inputs.modbus): Fix optimization of overlapping requests and add warning

- plugins/inputs/phpfpm/phpfpm.go
> fix: check address length to avoid crash

- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/amqp_consumer/sample.conf
resolves #13479
Add `QueueConsumeArguments` to manage the `x-stream-offset` for RabbitMQ stream queue.
> feat(inputs.amqp_consumer): Add support to rabbitmq stream queue

- plugins/serializers/splunkmetric/README.md
- plugins/serializers/splunkmetric/splunkmetric.go
resolves #13510
In the course of migrating serializers to the new-style framework TOML annotations where created based in the `Config` structure in `registry.go`. However, there are subtle differences between those and the actual option parsing that was done in `config.go`. This is one instance of such a difference.
The present PR reverts the TOML option back to `splunkmetric_multimetric` as used before v1.27.0.
> fix(serializers.splunkmetric): Fix TOML option name for multi-metric

- plugins/outputs/mqtt/mqtt_test.go
- plugins/parsers/value/README.md
- plugins/parsers/value/parser.go
- plugins/parsers/value/parser_test.go
This PR adds `auto_integer` and `auto_float` options to the value parser. Those two options allow to fallback to string if the parsing into the numeric types fails. This is helpful when the data-source produces multiple streams with mixed numeric and string data such as subscriptions to multiple MQTT topics.
> feat(parsers.value): Add support for automatic fallback for numeric types

- agent/agent.go
- models/running_input.go
- plugins/inputs/internal/README.md
resolves #13470
Added field `timeout_warnings` to measurement `internal_agent` to count warnings generated when collection timeouts occur. This is highly useful when exec based inputs lock up but there is no error generated.
> feat(internal): Add gather timeout metric

- plugins/inputs/cloud_pubsub/cloud_pubsub.go
resolves #13513
During #13094 the decompression code was reworked and with it the locking of the decompressor changed slightly. As a consequence the mutex is unlocked just *before* copying the decompressed data out of the internal buffer leaving a small window where the next decompression could overwrite the internal buffer content partially or as a whole.
The present PR holds the lock until after copying thus avoiding the previous race condition.
> fix(inputs.cloud_pubsub): Properly lock for decompression

- plugins/parsers/grok/parser.go
> fix(parsers.grok): use UTC as the default timezone

- plugins/common/opcua/client.go
- plugins/inputs/opcua/read_client.go
resolves #13260 
This PR ensures that the client is _really_ connected after reconnect. This might not be the case if the connect actually fails and the client is stuck in a disconnected state as described in #13260. In the course of the fix we also remove the redundant connection-state tracking now done within the gopcua library we depend on.
> fix(inputs.opcua): Ensure we are connected after reconnect

- plugins/outputs/sumologic/sumologic.go
resolves #13520 
With the serializer migration the passed-on serializers are now of type `models.RunningSerializer` and need unwrapping for type-checking. Do this for the SumoLogic output and also simplify the code.
> fix(outputs.sumologic): Unwrap serializer for type check

- plugins/inputs/pgbouncer/README.md
- plugins/inputs/pgbouncer/pgbouncer.go
- plugins/inputs/pgbouncer/pgbouncer_test.go
- plugins/inputs/pgbouncer/sample.conf
In PR #11706 it was proposed to add the show_commands parameter to select the metrics to be collected.
Added the ability to choose which metrics to collect
Added the ability to collect metrics using show lists and show databases
> feat(inputs.pgbouncer): Added show_commands to select the collected pgbouncer metrics

- config/migration.go
- migrations/all/inputs_httpjson.go
- migrations/common/filter_options.go
- migrations/common/input_options.go
- migrations/inputs_cassandra/migration.go
- migrations/inputs_httpjson/migration.go
- migrations/inputs_httpjson/migration_test.go
- migrations/inputs_httpjson/testcases/array/expected.conf
- migrations/inputs_httpjson/testcases/array/input.json
- migrations/inputs_httpjson/testcases/array/output.influx
- migrations/inputs_httpjson/testcases/array/telegraf.conf
- migrations/inputs_httpjson/testcases/headers/expected.conf
- migrations/inputs_httpjson/testcases/headers/telegraf.conf
- migrations/inputs_httpjson/testcases/params/expected.conf
- migrations/inputs_httpjson/testcases/params/telegraf.conf
- migrations/inputs_httpjson/testcases/single/expected.conf
- migrations/inputs_httpjson/testcases/single/input.json
- migrations/inputs_httpjson/testcases/single/output.influx
- migrations/inputs_httpjson/testcases/single/telegraf.conf
- migrations/registry.go
- testutil/metric.go
This PR adds migrations for the deprecated `inputs.httpjson` plugin.
> feat(migrations): Add migration for 'inputs.httpjson'

- config/migration.go
- migrations/all/inputs_httpjson.go
- migrations/all/inputs_io.go
- migrations/common/filter_options.go
- migrations/common/input_options.go
- migrations/inputs_cassandra/migration.go
- migrations/inputs_httpjson/migration.go
- migrations/inputs_httpjson/migration_test.go
- migrations/inputs_httpjson/testcases/array/expected.conf
- migrations/inputs_httpjson/testcases/array/input.json
- migrations/inputs_httpjson/testcases/array/output.influx
- migrations/inputs_httpjson/testcases/array/telegraf.conf
- migrations/inputs_httpjson/testcases/headers/expected.conf
- migrations/inputs_httpjson/testcases/headers/telegraf.conf
- migrations/inputs_httpjson/testcases/params/expected.conf
- migrations/inputs_httpjson/testcases/params/telegraf.conf
- migrations/inputs_httpjson/testcases/single/expected.conf
- migrations/inputs_httpjson/testcases/single/input.json
- migrations/inputs_httpjson/testcases/single/output.influx
- migrations/inputs_httpjson/testcases/single/telegraf.conf
- migrations/inputs_io/migration.go
- migrations/inputs_io/migration_test.go
- migrations/inputs_io/testcases/empty/expected.conf
- migrations/inputs_io/testcases/empty/telegraf.conf
- migrations/inputs_io/testcases/full/expected.conf
- migrations/inputs_io/testcases/full/telegraf.conf
- migrations/registry.go
- testutil/metric.go
based on #13532 
This PR adds migrations for the deprecated `inputs.io` plugin replaced by `inputs.diskio`.
> feat(migrations): Add migration for 'inputs.io'

- plugins/outputs/graphite/README.md
- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
- plugins/outputs/graphite/sample.conf
resolves #13483  
resolves #13491
The graphite connection handling was complex and error prone as the connection information was split among three three struct members (`Servers`, `conns` and `failedServers`). This PR centralizes the information into a struct shared by all functions. This way, we can always know which servers are available, mark them unavailable and reconnect correctly.
> fix(outputs.graphite): Rework connection handling

- docs/CONFIGURATION.md
This reverts a change in #12636 that switched a table to an inline table in the configuration example. This change was not correct, but works when using a table.
fixes: #13521
> docs: revert table example change

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/gnmi/testcases/canonical_field_names/expected.out
- plugins/inputs/gnmi/testcases/canonical_field_names_trim/expected.out
- plugins/inputs/gnmi/testcases/canonical_field_names_trim/responses.json
- plugins/inputs/gnmi/testcases/canonical_field_names_trim/telegraf.conf
- plugins/inputs/gnmi/testcases/issue_13512/expected.out
- plugins/inputs/gnmi/testcases/issue_13512/responses.json
- plugins/inputs/gnmi/testcases/issue_13512/telegraf.conf
resolves #13512 
This PR adds an option to explicitly trim leading dots and slashes from field-names defaulting the new option to false (i.e. keep the leading dots and slashes). This is required to fix a regression where the field-names contain a leading slash for Telegraf versions before v1.27.0 in case a subpath matched the subscription. In this case the field-name still contained a leading slash.
> fix(inputs.gnmi): Add option to explicitly trim field-names

- plugins/processors/printer/printer.go
Print the serialized data as string as usually humans are bad at reading byte-arrays. ;-)
> fix(processors.printer): Convert output to string

- tools/custom_builder/config.go
- tools/custom_builder/main.go
resolves #13473 
This PR makes `custom_builder` to error out on plugins in a configuration that are unknown to Telegraf.
> fix(tools.custom_builder): Error out for unknown plugins in configuration

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
The recent changes to the mqtt_consumer to ack messages would not
release semaphores when an error occured during parsing. This resulted
in Telegraf to seemingly to receving metrics once it reached the limit
of the max undelievered messages.
The change ensures that whenever we error or do not have any metrics
during the initial message handling we also decrement the semaphores.
Additionally, this ensures that we only ack messages when persistence is
enabled.
fixes: #13476
> fix(inputs.mqtt_consumer): Correctly handle semaphores on messages

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
~With a caveat: I do not see how, in the current test framework, to dynamically add/remove topics from the test broker.  So all we're really testing in the new test is that the configuration is valid and if the topics never change, then the consumer works.~
~I've tested this at my installation, where I can use Kafdrop to mess around with the topic list, and verified that when the periodic timer goes off, the right thing happens...but being told how to get this test suite to change the available topics would be good.~
resolves #13409 
New feature: if kafka_consumers regular expressions are given for topic matching, periodically rescan topics to see whether there are topics that should be added or removed.
In installations like Rubin Observatory's, topics are created and destroyed with some …
> feat(inputs.kafka_consumer): Refresh regexp topics periodically

- plugins/processors/parser/parser.go
- plugins/processors/parser/parser_test.go
resolves #13546
This PR allows to parse non-string fields in the parser processor to e.g. decode binary data. In the example from #13546 the input data looks like
```
mes,t1=y operating_state=13u,value=42.0 1688556620000000000
```
and the `operating_state` should be decoded into its bit-values. With the present PR this can easily be done using
```toml
[[processors.parser]]
parse_fields = ["operating_state"]
drop_original = false
merge = "override"
data_format = "binary"
[[processors.parser.binary]]
entries = [
{ name = "alarm_0", type = "bool", bits=1 },
{ name = "alarm_1", type = "bool", bits=1 },
{ name = "alarm_2", type = "bool", bits=1 },
{ name = "alarm_3", type = "bool", bits=1 },
{ name = "alarm_4", type = "bool", bits=1 },
{ name = "alarm_5", type = "bool", bits=1 },
{ name = …
```
> feat(processors.parser): Allow also non-string fields

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
> fix(inputs.mqtt_consumer): print warning on no metrics generated

- plugins/outputs/instrumental/instrumental.go
- plugins/outputs/instrumental/instrumental_test.go
Primarily for testing to avoid using the already busy and often used port 8000.
> test(outputs.instrumental): Allow setting custom port

- config/config.go
- config/internal_test.go
- go.mod
- go.sum
resolves #13565
Previous attempts (e.g. PR #13457) to restore the pre-1.27.0 environment-variable-replacement behavior missed one corner case where the environment variable exists but is empty. Versions before v1.27.0 will replace those variables (with an empty string) but the current code does not (see #13565).
This PR restores the old behavior by using the additional information about the application of the default replacement, indicating if an interpolation happened  or if the variable could be mapped.
> fix(config): Replace environment variables if existing but empty

- metric.go
- plugins/processors/template/README.md
- plugins/processors/template/template.go
- plugins/processors/template/template_metric.go
- plugins/processors/template/template_test.go
resolves #13034 
This PR unifies the template metrics as far as possible currently. The PR deprecates the `FieldList` and `TagList` functions as those are already existing with a different signature in `metric`. Once those functions are removed we can remove the surrounding `TemplateMetric` implementation in `processors.template` and use the `metric` implementation.
> feat(processors.template): Unify template metric

- plugins/inputs/pgbouncer/pgbouncer.go
- plugins/inputs/postgresql/postgresql.go
- plugins/inputs/postgresql/service.go
- plugins/inputs/postgresql_extensible/postgresql_extensible.go
resolves #9735 
- Fixing the default DB in the absence of the "datname" field. Now the default DB definition is taken from the connection string.
- Fixing the default database for pgbouncer. System database pgbouncer -> pgbouncer (https://www.pgbouncer.org/usage.html)
> fix(inputs.postgresql): Default database definition

- tools/custom_builder/config.go
resolves #13592 
Ignore non-plugin sections when loading the configuration.
> fix(tools.custom_builder): Ignore non-plugin sections during configuration

- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
- plugins/parsers/influx/README.md
- plugins/parsers/influx/influx_upstream/parser.go
- plugins/parsers/influx/influx_upstream/parser_test.go
- plugins/parsers/influx/parser.go
- plugins/parsers/influx/parser_test.go
> feat(parsers.influx): Allow a user to set the timestamp precision

- plugins/outputs/nebius_cloud_monitoring/README.md
- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go
- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring_test.go
> fix(outputs.nebius_cloud_monitoring): replace reserved label names

- plugins/parsers/avro/README.md
- plugins/parsers/avro/parser.go
- plugins/parsers/avro/testdata/json-format/expected.out
- plugins/parsers/avro/testdata/json-format/message.json
- plugins/parsers/avro/testdata/json-format/telegraf.conf
resolves #13155 
This PR adds support for Avro's JSON message format using a new `avro_format` option.
> feat(parsers.avro): Add support for JSON format

- agent/agent.go
- agent/agent_test.go
- agent/testcases/processor-order-appearance/expected.out
- agent/testcases/processor-order-appearance/input.influx
- agent/testcases/processor-order-appearance/telegraf.conf
- agent/testcases/processor-order-explicit/expected.out
- agent/testcases/processor-order-explicit/input.influx
- agent/testcases/processor-order-explicit/telegraf.conf
- agent/testcases/processor-order-mixed/expected.out
- agent/testcases/processor-order-mixed/input.influx
- agent/testcases/processor-order-mixed/telegraf.conf
- agent/testcases/processor-order-no-starlark/expected.out
- agent/testcases/processor-order-no-starlark/input.influx
- agent/testcases/processor-order-no-starlark/telegraf.conf
resolves #12849
Processor and aggregators are sensitive to order changes in Telegraf as their order defines the actual processing done and the metrics that are taken into account. When loading the configuration files, the order of those plugins is preserved taking the `order` option into account. However, the agent itself sorts the processors _again_ before actually setting up the processing pipeline. While this on itself does not cause an issue, there is a subtle twist as the "order" is reversed using the sorting. This is necessary because the agent constructs the pipeline from _output to input_ and thus needs to start with the "last" processor.
However, the sorting _only_ affects the processors with an _explicit_ `order` setting, leaving all other processors in the initial order. As a …
> fix(agent): Respect processor order in file

- plugins/inputs/http/README.md
- plugins/inputs/http/http.go
- plugins/inputs/http/sample.conf
- plugins/inputs/http/sample.conf.in
relates to #9455
This PR adds a new `token` option that allows to directly specify a token _or_ to reference a secret store entry. Together with PR #13621 (and potentially other secret-stores) this offers a powerful way to dynamically update the tokens in an arbitrary manner. Furthermore, this PR renames the `bearer_token` option to `token_file` for clarity and deprecates the former.
> feat(inputs.http): Rework token options

- plugins/outputs/opentelemetry/opentelemetry.go
- plugins/outputs/opentelemetry/opentelemetry_test.go
This will group open telemetry metrics from oldest to newest and group them by timestamp. This ensures they are kept in order in the event that old and new metrics become grouped up after buffering metrics.
fixes: #13233
> fix(outputs.opentelemetry): group metrics by age and timestamp

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
This reverts commit de8a9c514c398640fdc1b9c265000c38655c82aa.
go1.20.6 introduces a change that breaks our integration tests. This is tracked at https://github.com/testcontainers/testcontainers-go/issues/1306 which links to https://github.com/moby/moby/pull/45942
> Revert "chore: Update to go1.20.6 (#13618)"

- plugins/inputs/postgresql_extensible/README.md
- plugins/inputs/postgresql_extensible/postgresql_extensible.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
- plugins/inputs/postgresql_extensible/sample.conf
resolves #13568
Rename `version` to `minversion` and introduce `maxversion` to limit DB version query should run on.
> feat(inputs.postgresql_extensible): introduce MaxVersion

- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/outputs/prometheus_client/prometheus_client_v1_test.go
- plugins/outputs/prometheus_client/prometheus_client_v2_test.go
resolves https://github.com/influxdata/telegraf/issues/13393#issuecomment-1630857894
> feat(inputs.prometheus): always apply kubernetes selectors

- plugins/inputs/prometheus/kubernetes.go
resolves #13405
Plugins share SharedInformerFactory so that they reuse single connection to K8S API servers. If a plugin limits scope to just one namespace it can't share InformerFactory with another plugin which specifies different namespace.
To handle it correctly create a map of Namespace -> InformerFactory so that plugins can hook up to the right one.
> fix(inputs.prometheus): fix missing metrics when multiple plugin instances specified

- plugins/inputs/postgresql_extensible/README.md
- plugins/inputs/postgresql_extensible/sample.conf
No code change, just documenting missing config option
> docs(inputs.postgresql_extensible): document 'measurement' query config option

- go.mod
- go.sum
- internal/http.go
- plugins/inputs/dcos/client.go
- plugins/inputs/dcos/client_test.go
- plugins/inputs/dcos/dcos.go
- plugins/inputs/dcos/dcos_test.go
- plugins/inputs/influxdb_listener/README.md
- plugins/inputs/influxdb_listener/influxdb_listener.go
- plugins/inputs/influxdb_listener/influxdb_listener_test.go
- plugins/inputs/influxdb_listener/sample.conf
- plugins/outputs/health/health.go
- plugins/outputs/prometheus_client/prometheus_client.go
resolves #9445
This PR adds token based authentication to the InfluxDB v1 listener to complement the authentication methods supported. This is especially relevant to get a forward compatibility with v2.x.
> feat(inputs.influxdb_listener): Add token based authentication

- plugins/parsers/xpath/cbor_document.go
- plugins/parsers/xpath/json_document.go
- plugins/parsers/xpath/msgpack_document.go
- plugins/parsers/xpath/parser.go
- plugins/parsers/xpath/protocolbuffer_document.go
- plugins/parsers/xpath/testcases/json_array_expand_simple_types/expected.out
- plugins/parsers/xpath/testcases/json_array_expand_simple_types/telegraf.conf
- plugins/parsers/xpath/testcases/json_array_expand_simple_types/test.json
- plugins/parsers/xpath/testcases/json_array_simple_types/expected.out
- plugins/parsers/xpath/testcases/json_array_simple_types/telegraf.conf
- plugins/parsers/xpath/testcases/json_array_simple_types/test.json
- plugins/parsers/xpath/xml_document.go
When looking at the output in issue #13655 there is some strange field naming for arrays of simple types (e.g. float or string). This PR addresses those strange names and makes array naming consistent as much as possible by _always_ appending the array index and make sure we got the array names.
> fix(parsers.xpath): Fix field-names for arrays of simple types

- go.mod
- go.sum
- plugins/parsers/xpath/parser.go
- plugins/parsers/xpath/testcases/json_array_expand/telegraf.conf
- plugins/parsers/xpath/testcases/json_native_nonnested/expected.out
- plugins/parsers/xpath/testcases/json_native_nonnested/telegraf.conf
- plugins/parsers/xpath/testcases/json_native_nonnested/test.json
- plugins/parsers/xpath/testcases/json_string_representation/expected.out
- plugins/parsers/xpath/testcases/json_string_representation/telegraf.conf
- plugins/parsers/xpath/testcases/json_string_representation/test.json
- plugins/parsers/xpath/testcases/name_expansion/telegraf.conf
resolves #13655 
This PR improves the handling of map and array types, delivering those types _at all_ for native-type queries. Furthermore, we work-around issue #https://github.com/antchfx/jsonquery/issues/15 for maps and arrays in JSON to return a valid string representation of those nodes.
> fix(parsers.xpath): Improve handling of complex-type nodes

- config/config.go
- config/internal_test.go
resolves #13643 
PR #13229 added a function to remove comments, however, the logic did ignore escaping and thus any string of the form `"\"#...` was treated as a comment starting from the hash. This PR adds logic to handle escaping correctly this fixing #13643 while keeping the ability to add comments in arrays...
> fix(config): Handle escaping and quotation correctly

- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/logger.go
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/mqtt_consumer/sample.conf
This enables the ability to get logs from the client via an option. These messages are essential to debugging connection issues or understanding what the client is doing.
The option produces an enormous amount of data so it is disabled by default.
> fix(inputs.mqtt_consumer): client logs via option

- plugins/outputs/execd/README.md
- plugins/outputs/execd/execd.go
- plugins/outputs/execd/execd_test.go
- plugins/outputs/execd/sample.conf
refs #13654
Adds `use_batch_format` option to execd output plugin. This allows user to specify that the serializer should use the batch format when serializing metrics. Most useful for `json` serializer, and upcoming `template` serializer, as they can create completely different payloads when in batch mode.
> feat(outputs.execd): Add option for batch format

- tools/config_includer/generator.go
- tools/readme_config_includer/generator.go
resolves #13681
`config_includer` and `config_readme_includer` currently don't work on Windows. This fixes that.
The underlying issue is that the tools test for 'absolute' includes, which are relative to the telegraf directory rather than the directory of the current file. Using `filepath.IsAbs` does not work for this test on Windows, and Go doesn't provide a way to do posix path tests/manipulation when running on Windows.
> chore(tools): Fix doc inclusion tools on Windows

- plugins/inputs/jti_openconfig_telemetry/README.md
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
- plugins/inputs/jti_openconfig_telemetry/sample.conf
resolves #12017
This PR adds a setting to define a keep-alive period for the GRPC connection to detect broken connections.
> feat(inputs.jti_openconfig_telemetry): Add keep-alive setting

- plugins/common/opcua/input/input_client.go
- plugins/inputs/opcua/read_client.go
- plugins/inputs/opcua_listener/subscribe_client.go
resolves #13594 
Issue #13594 suggests that the node IDs of a OPCUA connections are not longer valid if the server was restarted. As we cannot decide if the connection was lost due to client or server side, we re-initialize the node IDs on reconnect to be on the safe side.
> fix(inputs.opcua): Register node IDs again on reconnect

- plugins/serializers/nowmetric/README.md
- plugins/serializers/nowmetric/nowmetric.go
- plugins/serializers/nowmetric/nowmetric_test.go
The nowmetric serializer by default produces metrics in the Operational
Intelligence format. This adds a format object, which can be set to
jsonv2 to produce metrics compatible with the JSONv2 endpoint.
The primary difference is in the JSON format. The JSONv2 endpoint is
based around an object, while the previous OI format is based around a
list of metrics.
> feat(serializers.nowmetric): Add option for JSONv2 format

- plugins/inputs/vsphere/README.md
- plugins/inputs/vsphere/client.go
- plugins/inputs/vsphere/sample.conf
- plugins/inputs/vsphere/vsphere.go
resolves #12557 
This PR allows to explicitly set a proxy for the vsphere input plugin.
> feat(inputs.vsphere): Support explicit proxy setting

- plugins/inputs/opcua_listener/subscribe_client.go
Fix case where the client stops without finishing the subscription
```
023-08-09T12:39:47Z D! [inputs.opcua_listener] Opc Subscribe Stopped
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2fb91ec]
goroutine 27 [running]:
github.com/gopcua/opcua.(*Subscription).Cancel(0x0, {0x80afc80, 0xc0024351d0})
/home/sven/go/pkg/mod/github.com/gopcua/opcua@v0.4.0/subscription.go:86 +0x4c
github.com/influxdata/telegraf/plugins/inputs/opcua_listener.(*SubscribeClient).Stop(0xc000782340, {0x80afc80, 0xc0024351d0})
/home/sven/Development/InfluxData/telegraf/plugins/inputs/opcua_listener/subscribe_client.go:82 +0x72
github.com/influxdata/telegraf/plugins/inputs/opcua_listener.(*OpcUaListener).Stop(0xc000330900) …
```
> fix(inputs.opcua_listener): Avoid segfault if subscription was not successful

- .golangci.yml
- plugins/common/opcua/client.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/google_cloud_storage/google_cloud_storage.go
- plugins/inputs/intel_pmu/intel_pmu.go
- plugins/inputs/intel_powerstat/intel_powerstat.go
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
- plugins/inputs/kinesis_consumer/kinesis_consumer.go
- plugins/inputs/mongodb/mongodb.go
- plugins/inputs/nfsclient/nfsclient.go
- plugins/inputs/opensearch_query/opensearch_query.go
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/socket_listener/stream_listener.go
- plugins/inputs/upsd/upsd.go
- plugins/inputs/win_eventlog/win_eventlog.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/outputs/cloud_pubsub/cloud_pubsub.go
- plugins/outputs/mqtt/mqtt.go
- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go
- plugins/outputs/opentelemetry/opentelemetry.go
- plugins/outputs/postgresql/table_manager.go
- plugins/outputs/timestream/timestream.go
- plugins/outputs/wavefront/wavefront.go
- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
- plugins/processors/scale/scale.go
- plugins/serializers/cloudevents/cloudevents.go
Check all telegraf logger functions for the right number of arguments and the correct formatting directives. This enables the linter for those functions and fixes the fallout.
> chore: Check logging functions like printf

- internal/host_endianness_be.go
- internal/host_endianness_le.go
- plugins/inputs/modbus/type_conversions16.go
- plugins/inputs/modbus/type_conversions32.go
- plugins/inputs/modbus/type_conversions64.go
- plugins/inputs/modbus/type_conversions8.go
- plugins/inputs/powerdns_recursor/protocol_commons.go
- plugins/inputs/socket_listener/socket_listener.go
- plugins/parsers/binary/README.md
- plugins/parsers/binary/entry_test.go
- plugins/parsers/binary/parser.go
- plugins/parsers/binary/parser_test.go
- plugins/parsers/binary/testcases/multiple_messages/telegraf.conf
- plugins/processors/parser/parser.go
A forums user tried using `endianness` as a setting for the binary plugin. However, that is not what the plugin is using, instead, it is using `endianess` (one less `n`).
This PR changes all internal uses to use `endianness` and deprecates the binary parser's current `endianess` setting in favor of `endianness`.
> chore: Spell endianness correctly

- .golangci.yml
- config/config_test.go
- internal/globpath/globpath_test.go
- plugins/inputs/diskio/diskio_linux.go
- plugins/inputs/file/file_test.go
- plugins/inputs/powerdns_recursor/powerdns_recursor.go
- plugins/inputs/prometheus/kubernetes.go
- plugins/inputs/system/ps.go
- plugins/processors/port_name/services_path.go
- testutil/socket.go
resolves https://github.com/influxdata/telegraf/issues/13193
> chore: Enable filepathJoin checker for gocritic

- plugins/outputs/postgresql/README.md
- plugins/outputs/postgresql/columns.go
- plugins/outputs/postgresql/postgresql.go
- plugins/outputs/postgresql/postgresql_test.go
- plugins/outputs/postgresql/sample.conf
- plugins/outputs/postgresql/table_manager.go
- plugins/outputs/postgresql/table_source.go
resolves #13744 
This PR adds an option to specify the name of the column used for storing the metric timestamp.
> feat(outputs.postgresql): Add option to rename time column

- cmd/telegraf/telegraf.go
- config/config.go
- config/config_test.go
> feat(agent): Watch default config files if none specified

- plugins/inputs/amqp_consumer/amqp_consumer.go
Actually print the error to the user when an error occurs during a connection attempt. This should actually aid the user into what might be going on.
> fix(inputs.amqp_consumer): Print error on connection failure

- .circleci/config.yml
- scripts/installgo_windows.sh
Caches are grouped by os/arch (`linux-amd64`, `linux-386`, `darwin-amd64`, `windows-amd64`) and by type (`Go caches` and `binaries`).
- `Go caches` contains:
- downloaded dependencies: `go\pkg\mod`
- `GOCACHE` directory: `go-build` dir
- caches for `golangci-lint`
- `binaries` contains;
- `gotestsum` binary (for all OSes)
- `Go` directory (for `darwin` and `windows`)
- `go`/`gofmt` binaries (for `darwin`)
Cache contains right now 8 entries with total size around: **8-9 GB**.
Fixes/improvements made:
- Incorrect `~/go/src/github.com/influxdata/telegraf/gotestsum` path corrected to valid `/go/src/github.com/influxdata/telegraf/gotestsum` (for `linux`)
- Incorrect `/go/src/github.com/influxdata/telegraf/gotestsum` path corrected to valid `~/go/src/github.com/influxdata/telegraf/gotestsum` …
> chore: Cache rework for `.circleci` jobs

- Makefile
- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
Permissions on /etc/telegraf and /etc/telegraf.d will now be 750 and on the initial configuration file 640. This would only be if these files do not exist, for new installs, or if the user removed them.
fixes: #8685
> chore: Update permissions on new installs

- plugins/inputs/fibaro/README.md
- plugins/inputs/fibaro/fibaro.go
- plugins/inputs/fibaro/fibaro_test.go
- plugins/inputs/fibaro/hc2/parser.go
- plugins/inputs/fibaro/hc2/types.go
- plugins/inputs/fibaro/hc3/parser.go
- plugins/inputs/fibaro/hc3/types.go
- plugins/inputs/fibaro/sample.conf
- plugins/inputs/fibaro/testdata/device_hc2.json
- plugins/inputs/fibaro/testdata/device_hc3.json
- plugins/inputs/fibaro/testdata/rooms.json
- plugins/inputs/fibaro/testdata/sections.json
> feat(inputs.fibaro): Support HC3 device types

- .circleci/config.yml
- Makefile
- plugins/inputs/aliyuncms/aliyuncms.go
- plugins/inputs/couchbase/couchbase.go
- plugins/inputs/couchbase/couchbase_test.go
- plugins/inputs/kube_inventory/kube_inventory.go
- plugins/inputs/logstash/logstash.go
- plugins/inputs/vsphere/endpoint.go
- plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
- plugins/outputs/iotdb/iotdb_test.go
- plugins/parsers/influx/escape.go
We need to bump the linter in order to be compatible with go 1.21 (see nightly build error for Windows). This PR bumps the linter and fixes the newly found issues.
> chore(tools): Bump golangci-lint from v1.53.2 to v1.54.2

- .golangci.yml
- cmd/telegraf/cmd_plugins.go
- cmd/telegraf/main.go
- cmd/telegraf/main_test.go
> feat(cli): Add plugins subcommand to list available and deprecated

- plugins/inputs/internal/README.md
- plugins/inputs/internal/internal.go
- plugins/inputs/internal/internal_test.go
- plugins/inputs/internal/sample.conf
This allows users to set an option to collect the official runtime go metrics via the new interface introduced in Go 1.16. This is hidden behind an option due to the additional values that do overlap with the existing memstat option.
Sanitizes the names as such:
```diff
-- /cpu/classes/gc/mark/assist:cpu-seconds
++ cpu_classes_gc_mark_assist_cpu_seconds
```
fixes: #8645
> feat(inputs.internal): Add Go metric collection option

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/sample_register.conf
resolves #13827
Improve documentation on FLOAT32 in register configuration style.
Add deprecation warning on use of FLOAT32
> chore(inputs.modbus): improve deprecation documentation

- cmd/telegraf/telegraf.go
My name is Rick Spencer and I am the VP of Product at InfluxData.
I am proposing this change to raise brand awareness of InfluxDB and InfluxData among Telegraf users. 
I left out any punctuation in an effort to avoid breaking any parsing than any users might doing on the output.
> chore: Add InfluxDB and InfluxData branding to output

- tools/license_checker/data/whitelist
- tools/license_checker/main.go
- tools/license_checker/whitelist.go
This PR fixes the handling of versions for whitelisting as before, the name was not trimmed correctly and thus the version was always empty. Furthermore, we whitelist `github.com/gorilla/websocket` due to a license change in current master of that project.
relates to #13835
> fix(tools.license_checker): Determine version correctly and whitelist gorilla/websocket

- plugins/common/opcua/input/input_client.go
Provides a check to a user's config to ensure that they have provided a group and or root node to collect data from.
fixes #13834
fixes #10817
> fix(inputs.opcua): Verify groups or root nodes included in config

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
resolves #13869 
This PR fixes the location of the `conversion_style` option which really belongs to the `convert` table. Furthermore, we add the TOML tags for all settings.
> fix(outputs.sql): Move 'conversion_style' option to the right place

- .circleci/config.yml
- tools/update_goversion/main.go
Ensures that all cache restore and save include the specific go version that we are on. Additionally, because some were updated, but not all, this updates the version to v2.
> chore: Update all cache strings with go version

- .circleci/config.yml
- scripts/installgo_windows.sh
This PR forcefully deletes the cached go versions and thus forces a reinstall. This is the only way currently to avoid errors in combination with go 1.21 and golint-ci.
> chore: Force reinstall of go on Windows

- scripts/rpm/post-install.sh
- tools/package_lxd_test/container.go
- tools/package_lxd_test/main.go
Fixes the check for permissions and update the test CLI to require the package parameter and verify that the package is real.
> fix(rpm): Resolve nightly rpm tests

- docs/CONFIGURATION.md
Add note about failing `metricpass` expressions being valued as true
resolves #13815
> docs: Improve behavior documentation of metricpass

- plugins/inputs/redis/README.md
- plugins/inputs/redis/redis.go
- plugins/inputs/redis/redis_test.go
> feat(inputs.redis): Add additional commandstat fields

- plugins/inputs/vsphere/README.md
- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/sample.conf
- plugins/inputs/vsphere/vsphere.go
resolves #13880
This PR allows the user to set the sampling interval for vSAN performance metrics. This is important to make full use of vSAN 8 U1 supporting intervals as low as 30 seconds compared to the hard-coded 5 minute interval.
> feat(inputs.vsphere): Allow to set vSAN sampling interval

- go.mod
- go.sum
This patch fixed the [memory leak](https://github.com/showwin/speedtest-go/pull/142) in telegraf caused by plugin internet speed.
> chore(deps): Bump github.com/showwin/speedtest-go from 1.6.2 to 1.6.6

- config/config_test.go
- plugins/outputs/prometheus_client/README.md
- plugins/outputs/prometheus_client/prometheus_client.go
- plugins/outputs/prometheus_client/prometheus_client_v1_test.go
- plugins/outputs/prometheus_client/prometheus_client_v2_test.go
- plugins/outputs/prometheus_client/sample.conf
- plugins/outputs/prometheus_client/v1/collector.go
- plugins/outputs/prometheus_client/v2/collector.go
- plugins/serializers/prometheus/README.md
- plugins/serializers/prometheus/collection.go
- plugins/serializers/prometheus/prometheus.go
- plugins/serializers/prometheus/prometheus_test.go
resolves #13844 
resolves #13079
This PR allows to explicitly set the metric type for the prometheus serializer and the `prometheus_client` output plugin. This is required as a large number of plugins will not or cannot type Telegraf metrics but prometheus uses those types.
> feat(prometheus): Allow to specify metric type

- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
Using parsers like json_v2 will result in undesired parser results. This switches to the ParserFunc pattern to create a dedicated parser in each thread.
fixes #13888
> fix(inputs.kafka_consumer): Use per-message parser to avoid races

- plugins/outputs/prometheus_client/README.md
- plugins/outputs/prometheus_client/prometheus_client.go
resolves #13898
Changes the Prometheus Client output basic_password option to support using the secretstore.
> feat(outputs.prometheus_client): Add secretstore support for basic_password

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/all/intel_pmt.go
- plugins/inputs/intel_pmt/README.md
- plugins/inputs/intel_pmt/filtering.go
- plugins/inputs/intel_pmt/filtering_test.go
- plugins/inputs/intel_pmt/intel_pmt.go
- plugins/inputs/intel_pmt/intel_pmt_notamd64linux.go
- plugins/inputs/intel_pmt/intel_pmt_test.go
- plugins/inputs/intel_pmt/sample.conf
- plugins/inputs/intel_pmt/tags_extraction.go
- plugins/inputs/intel_pmt/tags_extraction_test.go
- plugins/inputs/intel_pmt/xml_parser.go
- plugins/inputs/intel_pmt/xml_parser_test.go
resolves #13800
Intel® Platform Monitoring Technology Input Plugin collects metrics from
the Telemetry capability of the Intel® PMT kernel driver.
Intel® Platform Monitoring Technology (Intel® PMT) is an architecture for
enumerating and accessing hardware monitoring capabilities on a device.
Intel PMT support has been added to the mainline Linux kernel
under the platform driver (`drivers/platform/x86/intel/pmt`).
This driver exposes the Intel PMT telemetry space as a sysfs entry
at `/sys/class/intel_pmt/`.
Each discovered Intel PMT telemetry aggregator is exposed as a directory named
with a `telem` prefix. Every directory contains a file named `guid` identifying
the unique PMT space. This file is associated with a set of XML specification
files.
Intel PMT XML files are available at …
> feat(inputs): New Intel PMT plugin

- plugins/parsers/avro/README.md
- plugins/parsers/avro/parser.go
- plugins/parsers/avro/schema_registry.go
resolves #13334
superseeds #13820 
Allow to connect to HTTPS schema registry including custom certificates and basic authentification.
> feat(parsers.avro): Allow connection to https schema registry

- plugins/inputs/systemd_units/README.md
- plugins/inputs/systemd_units/systemd_units.go
> fix(inputs.systemd_units): Add missing upstream states

- plugins/outputs/sql/sqlite_test.go
The test file was not removed after testing. Additional runs of the test would conflict if this file still existed.
> test(outputs.sql): Fix clean up of sql database file

- plugins/inputs/smart/smart.go
Rather than error out on a parsing error, ignore the error and continue on parsing other fields. This avoids tossing all the data and not returning any metrics. This is the behavior for other parsing functions and fields throughout the plugin.
fixes: #13926
> fix(inputs.smart): Remove parsing error message

- plugins/outputs/cloudwatch/cloudwatch.go
Previously this was limited to only 20 per write. It appears AWS has increased this to no more than 1000.
fixes: #13929
> fix(outputs.cloudwatch): Increase number of metrics per write

- plugins/parsers/avro/schema_registry.go
- [n/a] Updated associated README.md.
- [n/a] Wrote appropriate unit tests.
resolves #13938
Moved the attempted opening of the CA cert file inside the check that that filename is not the empty string.
> fix(parsers.avro): Only attempt to read CA Cert file if filename is not empty string

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/sample.conf
resolves #13822
Added 2 options to `kafka_consumer`:
- `kafka_version` - used to specify version in the Sarama config to enable different features. For example message headers won't be received if Kafka version lower 0.11.
- `msg_headers_to_tags` - string array of header names that should be added as tags to metric.
> feat(inputs.kafka_consumer): Add message headers as metric tags.

- metric.go
- plugins/processors/lookup/lookup.go
- plugins/processors/template/template.go
- plugins/processors/template/template_test.go
resolves #13936 
Handle tracking metrics correctly as those cannot be casted directly to a template-metric...
> fix(processors.template): Handle tracking metrics correctly

- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
If a user gets a message that we failed to decode the message it would be super helpful to know what message failed to decode in the first place.
fixes: #13928
> fix(inputs.cisco_telemetry_mdt): Print string message on decode failure

- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/stackdriver/stackdriver_test.go
Rather than rely on specific error messages that have in fact changed over time, let's instead drop metrics whenever we get an InvalidArgument gRPC error. These are not retry-able errors and should instead be dropped.
fixes: #13826
> fix(outputs.stackdriver): Drop metrics on InvalidArgument gRPC error

- plugins/inputs/nfsclient/README.md
- plugins/inputs/nfsclient/nfsclient.go
- plugins/inputs/nfsclient/nfsclient_test.go
Provide error messages on permission denied or file does not exist, rather than panics. Does not change how the plugin operates or reads the file, only does some additional checks.
Document the environment variable for changing the location of the file to read.
fixes: #13979
> fix(inputs.nfsclient): Avoid panics, better error messages

- plugins/inputs/intel_pmt/intel_pmt.go
When the intel_pmt input plugin is enabled currently, it will cause telegraf to fail on startup like so:
```
telegraf[47878]: 2023-09-21T22:27:09Z E! [telegraf] Error running agent: could not initialize input inputs.intel_pmt: error while exploring pmt sysfs: error while evaluating symlink "/sys/class/intel_pmt/telem0/numa_node": lstat /sys/devices/pci0000:00/0000:00:0a.0/intel_vsec.telemetry.0/intel_pmt/telem0/numa_node: no such file or directory
```
While intel_pmt telem devices do not have a numa_node attribute, their parent intel_vsec devices do. For example the current behavior:
```
$ ls -l /sys/class/intel_pmt/telem0/device/numa_node
ls: cannot access '/sys/class/intel_pmt/telem0/device/numa_node': No such file or directory
```
Versus traversing up to intel_vsec device:
```
$ ls -l …
```
> fix(input.intel_pmt): Handle telem devices without numa_node attribute

- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
resolves #13917 
This does not block the GRPC dial and restores the old behavior (hopefully).
> fix(inputs.jti_openconfig_telemetry): Do not block GRPC dial

- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/stackdriver/stackdriver_test.go
This does not shallow copy the resource label map and instead makes a deep copy of the values. This was causing additional metrics to end up with all the same resource labels, rather than their unique set.
fixes: #13911
> fix(outputs.stackdriver): Do not shallow copy map

- plugins/outputs/prometheus_client/README.md
- plugins/outputs/prometheus_client/sample.conf
resolves #14005 
Fix the naming of `metric_types` in the `sample.conf` to match the actual code.
> docs(outputs.prometheus_client): Fix metric-type parameter naming

- plugins/processors/regex/README.md
- plugins/processors/regex/converter.go
- plugins/processors/regex/regex.go
- plugins/processors/regex/regex_test.go
- plugins/processors/regex/sample.conf
resolves #5505
This PR restructures and simplifies the regexp-processor and then implements the possibility to transform multiple tags/fields using named capture-groups. In the course, it unifies the ability to specify wildcards on tags and fields (previously only possible on tags) by using standard `filter` expressions.
Finally, it improves the README explaining behavior of the possible operations and modi in more detail.
> feat(processors.regex): Allow batch transforms using named groups

- scripts/windows-signing.ps1
This updates the version of the PowerShell archive tooling to ensure we are creating an archive with forward slashes only.
I SSH'ed into a CircleCI runner to confirm this runs and that the zip file extracts. We can double check the run on a nightly build after this is added.
fixes: #13974
> chore: Update Windows zip archive creation

- docs/APPARMOR.md
Adds a page to our docs about AppArmor. The goal is to detail that this is not directly under Telegraf's control, but that a user needs to analyze the denial and make a decision about whether to make changes to AppArmor or not. I avoided any specific recommendations.
fixes: #6574
> docs(apparmor): Add page explaining apparmor denials

- plugins/outputs/opensearch/opensearch.go
Fixes newly added opensearch output plugin to use the already introduced secrets-wrapper.
> fix(outputs.opensearch): Migrate to new secrets API

- plugins/outputs/stackdriver/README.md
- plugins/outputs/stackdriver/sample.conf
- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/stackdriver/stackdriver_test.go
This adds two new user config options that take metric names, with globs
as well. Metric's matching these names will have their type set before
sending to Stackdriver.
fixes: #14006
> feat(outputs.stackdriver): Add metric type config options

- .circleci/config.yml
The latest version of mingw causes issues with the -race test flag and messages about cgo needing gcc. Binds us to the last known working version.
> chore: Force previous version of mingw

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/sample_request.conf
The `aggressive` optimization has a worst-case runtime of `O(N!)` with Telegraf appearing to hang on startup with big configurations. To avoid this veritable foot-gun let's deprecate the option in favor of the `max_insert` strategy leading to good results in most cases and being much faster `O(N)`.
> chore(inputs.modbus): Deprecate aggressive optimization

- go.mod
- go.sum
> chore(deps): Bump github.com/vmware/govmomi from v0.28.0 to v0.32.0

- plugins/inputs/infiniband/infiniband_linux.go
resolves #8135
Not all rdma devices have counters parsable by `GetRdmaSysfsStats`.
This PR add `continue` statement to ignore such device (and continue with next device/port) instead of throwing an error and failing
> fix(inputs.infiniband): Handle devices without counters

- plugins/outputs/azure_data_explorer/azure_data_explorer.go
resolves #14046
<!-- Finally, include a summary of the code change itself. This
description should tell reviewers how the issues were resolved.
Add headers in the connection string for telemetry (azure_data_explorer). When customers ask for support, this will help us determine options used
> feat(outputs.azure_data_explorer): Set user agent string

- plugins/inputs/s7comm/README.md
- plugins/inputs/s7comm/s7comm.go
- plugins/inputs/s7comm/sample.conf
- plugins/inputs/s7comm/type_conversions.go
resolves #14042 
Moved `const maxRequestsPerBatch` to be set from config file by keyword `pdu_size`
> fix(inputs.s7comm): Allow PDU-size to be set as config option

- plugins/common/mqtt/mqtt_v5.go
For me, connecting to MQTT with username/password and mqttv5 stopped working.
Not sure, but shouldn't it be cfg.Password instead of the config.Password Type?
> fix(inputs.mqtt): Reference correct password variable

- plugins/inputs/kube_inventory/README.md
- plugins/inputs/kube_inventory/client.go
- plugins/inputs/kube_inventory/kube_inventory.go
- plugins/inputs/kube_inventory/node.go
- plugins/inputs/kube_inventory/pod.go
- plugins/inputs/kube_inventory/sample.conf
resolves #13878
superseeds #13893
Add the option to filter nodes and pods by node name in the kuberetes_inventory input plugin
> feat(inputs.kube_inventory): Support filtering pods and nodes by node name

- plugins/inputs/redis_sentinel/redis_sentinel_test.go
Force the specific exposed port for the base redis container to prevent a timeout from getting hit and avoid scanning the entire port range.
> test(inputs.redis_sentinel): Resolve timeout looking for port

- plugins/common/opcua/input/input_client.go
- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/sample.conf
- plugins/inputs/opcua_listener/subscribe_client.go
resolves #13891
new structs have been added to input client representing monitoring and data change filter parameters
new function has been added to subscribe client in order to override default values for parameters that have been specified in the config
monitoring parameters have been added to existing tests for subscribe client
> feat(inputs.opcua_listener): Add monitoring params

- plugins/inputs/all/ldap.go
- plugins/inputs/ldap/389ds.go
- plugins/inputs/ldap/README.md
- plugins/inputs/ldap/ldap.go
- plugins/inputs/ldap/ldap_test.go
- plugins/inputs/ldap/openldap.go
- plugins/inputs/ldap/sample.conf
- testutil/tls.go
This is a now plugin that superseeds the OpenLDAP plugin. It generalizes the metric gathering and adds support for the 389ds directory server.
> feat(inputs): Add LDAP input plugin supporting OpenLDAP and 389ds

- go.mod
- go.sum
resolves #14024 
Update dependency to solve a potential panic in the xpath-parser.
> chore(deps): Bump github.com/jhump/protoreflect from 1.15.1 to 1.15.3

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update golang to v1.21.3 to fix CVE-2023-44487.
> chore: Update go to 1.21.3

- plugins/outputs/mqtt/README.md
- plugins/outputs/mqtt/sample.conf
resolves #14072
Renamed `protocol` to match [common/mqtt](https://github.com/influxdata/telegraf/blob/master/plugins/common/mqtt/mqtt.go) configuration definition
> docs(outputs.mqtt): Correct typo in protocol config parameter

- docs/LICENSE_OF_DEPENDENCIES.md
- plugins/outputs/exec/README.md
- plugins/outputs/exec/exec.go
- plugins/outputs/exec/exec_test.go
- plugins/outputs/exec/sample.conf
refs #13654
This adds a mode to the exec plugin which will run the command once per metric, rather than once per batch. 
Open questions:
- Is the option name `batch_exec` good?
- I wasn't too sure how errors should be handled in this mode. Right now it:
- Aborts if there is an error serializing a metric.
- Continues running the command for all metrics even if one has an error, then returns all the errors Joined at the end.
- Not sure how to do unit tests for this either. If someone has some ideas I'd love to hear them.
> feat(outputs.exec): Add ability to exec command once per metric

- agent/agent.go
- plugins/processors/dedup/README.md
- plugins/processors/dedup/dedup.go
resolves #14059
This adds the state persistence interface to the processors.dedup plugin. It's implemented by using the influx serializer/parser to store the metrics.
Turns out there was a bug that non-streaming processors couldn't have state persistence, also fixed that issue in here to make it work.
> feat(processors.dedup): Add state persistence between runs

- plugins/inputs/postgresql/service.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
The database name should either be postgres or the value from a correctly parsed dsn.
fixes: #14007
> fix(inputs.postgresql_extensible): Restore default db name

- plugins/processors/regex/converter.go
- plugins/processors/regex/regex.go
resolves #14028
This PR adds an information log-message on the used modus (explicit vs. named-groups) and warns in case no explicit options are given but unnamed or mixed (named & unnamed) groups are used.
> chore(processors.regex): Inform and warn user on operation modus

- plugins/inputs/win_services/win_services.go
resolves #13382 
This PR tries to reduce the requested-rights to a minimum for gathering the service information. With the PR we request `GENERIC_READ` which cannot modify the services. There might be room for trimming this down further if there is need...
> feat(inputs.win_service): Reduce required rights to GENERIC_READ

- migrations/all/inputs_tcp_listener.go
- migrations/inputs_tcp_listener/migration.go
- migrations/inputs_tcp_listener/migration_test.go
- migrations/inputs_tcp_listener/testcases/allow_pending_messages/expected.conf
- migrations/inputs_tcp_listener/testcases/allow_pending_messages/telegraf.conf
- migrations/inputs_tcp_listener/testcases/parser/expected.conf
- migrations/inputs_tcp_listener/testcases/parser/telegraf.conf
- migrations/inputs_tcp_listener/testcases/simple/expected.conf
- migrations/inputs_tcp_listener/testcases/simple/telegraf.conf
This PR adds migrations for the deprecated `inputs.tcp_listener` plugin replaced by `inputs.socket_listener`.
> feat(migrations): Add migration for inputs.tcp_listener

- migrations/all/inputs_udp_listener.go
- migrations/inputs_udp_listener/migration.go
- migrations/inputs_udp_listener/migration_test.go
- migrations/inputs_udp_listener/testcases/all_deprecated_messages/expected.conf
- migrations/inputs_udp_listener/testcases/all_deprecated_messages/telegraf.conf
- migrations/inputs_udp_listener/testcases/allow_pending_messages/expected.conf
- migrations/inputs_udp_listener/testcases/allow_pending_messages/telegraf.conf
- migrations/inputs_udp_listener/testcases/parser/expected.conf
- migrations/inputs_udp_listener/testcases/parser/telegraf.conf
- migrations/inputs_udp_listener/testcases/simple/expected.conf
- migrations/inputs_udp_listener/testcases/simple/telegraf.conf
This PR adds migrations for the deprecated `inputs.udp_listener` plugin replaced by `inputs.socket_listener`.
> feat(migrations): Add migration for inputs.udp_listener

- migrations/all/outputs_riemann_legacy.go
- migrations/common/output_options.go
- migrations/outputs_riemann_legacy/migration.go
- migrations/outputs_riemann_legacy/migration_test.go
- migrations/outputs_riemann_legacy/testcases/general_options/expected.conf
- migrations/outputs_riemann_legacy/testcases/general_options/telegraf.conf
- migrations/outputs_riemann_legacy/testcases/simple/expected.conf
- migrations/outputs_riemann_legacy/testcases/simple/telegraf.conf
This PR adds migrations for the deprecated `outputs.riemann_legacy` plugin replaced by `outputs.riemann`.
> feat(migrations): Add migration for outputs.riemann_legacy

- migrations/all/inputs_snmp_legacy.go
- migrations/inputs_snmp_legacy/migration.go
- migrations/inputs_snmp_legacy/migration_test.go
This PR adds migrations for the deprecated `inputs.snmp_legacy` plugin that requires manual intervention.
> feat(migrations): Add migration for inputs.snmp_legacy

- migrations/all/inputs_kafka_consumer_legacy.go
- migrations/inputs_kafka_consumer_legacy/migration.go
- migrations/inputs_kafka_consumer_legacy/migration_test.go
This PR adds migrations for the deprecated `inputs.kafka_consumer_legacy` plugin that requires manual intervention.
> feat(migrations): Add migration for inputs.kafka_consumer_legacy

- migrations/all/inputs_jolokia.go
- migrations/inputs_jolokia/migration.go
- migrations/inputs_jolokia/migration_test.go
- migrations/inputs_jolokia/testcases/agent_default/expected.conf
- migrations/inputs_jolokia/testcases/agent_default/telegraf.conf
- migrations/inputs_jolokia/testcases/agent_more_complex/expected.conf
- migrations/inputs_jolokia/testcases/agent_more_complex/telegraf.conf
- migrations/inputs_jolokia/testcases/agent_response_timeout/expected.conf
- migrations/inputs_jolokia/testcases/agent_response_timeout/telegraf.conf
- migrations/inputs_jolokia/testcases/proxy_default/expected.conf
- migrations/inputs_jolokia/testcases/proxy_default/telegraf.conf
This PR adds migrations for the deprecated `inputs.jolokia` plugin replaced by `inputs.jolokia2_agent` and `inputs.jolokia2_proxy`.
> feat(migrations): Add migration for inputs.jolokia

- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
This removal was added before 1.x was officially out. It was due to an alias setting in systemd causing a naming loop. This check currently prevents a user from masking the service and running their own custom service file.
fixes: #14052
> chore(packaging): Remove unnecessary service file removal

- plugins/processors/ifname/README.md
- plugins/processors/ifname/sample.conf
> docs(processors.ifname): Document better agent tag name

- plugins/inputs/jenkins/jenkins.go
- plugins/inputs/jenkins/jenkins_test.go
Currently, the Jenkins plugin will apply the user filter to directory
names immediately. If the directory does not match the filter it would
toss the folder. This prevents traversing into the folder itself where a
user might want a job inside the folder.
This change will move the filtering operation to occur after we kick off
directory traversal. The changes to the tests were necessary since we
never went into the folders correctly. The test results are the same,
the changes are to the response our mock jenkins server provides.
fixes: #14054
> fix(inputs.jenkins): Filter after searching sub-folders

- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
resolves #14142 
Add a trailing newline to the batch-serialization output to match the non-batch behavior.
> fix(serializers.json): Append newline for batch-serialization

- config/migration.go
- migrations/all/inputs_disk.go
- migrations/inputs_disk/migration.go
- migrations/inputs_disk/migration_test.go
- migrations/inputs_disk/testcases/deprecated_mountpoints/expected.conf
- migrations/inputs_disk/testcases/deprecated_mountpoints/telegraf.conf
- migrations/inputs_disk/testcases/deprecated_mountpoints_existing/expected.conf
- migrations/inputs_disk/testcases/deprecated_mountpoints_existing/telegraf.conf
- migrations/registry.go
relates to #13375 
This PR adds migrations for the deprecated `mountpoints`  option of `inputs.disk` replaced by `mount_points`.
> feat(migrations): Add option migration for inputs.disk

- plugins/outputs/kafka/kafka.go
This PR simplifies the error handling for SendMessages and thus removes a nolint directive.
> fix(outputs.kafka): Simplify send-error handling

- .circleci/config.yml
- Makefile
- plugins/inputs/aerospike/aerospike.go
- plugins/inputs/chrony/chrony_test.go
- plugins/inputs/csgo/csgo.go
- plugins/inputs/dcos/dcos.go
- plugins/inputs/disk/disk.go
- plugins/inputs/ipmi_sensor/ipmi_sensor_test.go
- plugins/inputs/kube_inventory/kube_inventory.go
- plugins/inputs/monit/monit.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/sensors/sensors_test.go
- plugins/inputs/snmp/snmp.go
- plugins/inputs/statsd/running_stats.go
- plugins/inputs/win_eventlog/util.go
- plugins/outputs/opentsdb/opentsdb.go
- plugins/parsers/influx/escape.go
This PR bumps `golangci-lint` from `v1.54.2` to `v1.55.0` and fixes the newly found issues:
```
plugins/inputs/aerospike/aerospike.go:441:9             revive      indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
plugins/inputs/chrony/chrony_test.go:99:2               revive      early-return: if c { ... } else { ... os.Exit() } can be simplified to if !c { ... os.Exit() } ...
plugins/inputs/csgo/csgo.go:180:9                       revive      indent-error-flow: if block ends with a return statement, so drop this else and outdent its block
plugins/inputs/dcos/dcos.go:352:9                       revive      indent-error-flow: if block ends with a return statement, so drop this …
```
> chore(tools): Bump golangci-lint from v1.54.2 to v1.55.0

- plugins/inputs/swap/README.md
- plugins/inputs/swap/sample.conf
Based on https://docs.influxdata.com/telegraf/v1/plugins/#input-swap and personal experience
> docs(inputs.swap): Add message about plugin limitation

- plugins/inputs/openstack/README.md
Being a novice, I struggled with TOML errors. Found it to be missing quotes.
```
$ make lint
golangci-lint run
ERRO Running error: unknown linters: 'gocheckcompilerdirectives', run 'golangci-lint help linters' to see the list of supported linters 
make: *** [lint] Error 3
```
```
$ make check-deps
+github.com/99designs/go-keychain
The docs/LICENSE_OF_DEPENDENCIES.md file does not contain the expected entries.
Lines prefixed with '+' should be added to LICENSE_OF_DEPENDENCIES.md and '-'
lines should be removed.
Include a link to the appropriate licenses for any additions.
make: *** [check-deps] Error 1
```
```
$ make test  # ✅ 
```
```
$ make docs  # ✅ 
```
resolves #
> docs(openstack): put quote around interval value

- agent/tick_test.go
- internal/internal_test.go
- plugins/inputs/pgbouncer/pgbouncer_test.go
- plugins/inputs/ping/ping_test.go
- plugins/inputs/postgresql/postgresql_test.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
- plugins/inputs/processes/processes_test.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/inputs/vsphere/vsphere_test.go
- plugins/parsers/json/parser_test.go
- plugins/processors/starlark/starlark_test.go
Address findings for [testifylint: compares](https://github.com/Antonboom/testifylint#compares) - checks usage of github.com/stretchr/testify.
```
❌   assert.True(t, a == b)
assert.True(t, a != b)
assert.True(t, a > b)
assert.True(t, a >= b)
assert.True(t, a < b)
assert.True(t, a <= b)
// And other variations (with assert.False too)...
✅   assert.Equal(t, a, b)
assert.NotEqual(t, a, b)
assert.Greater(t, a, b)
assert.GreaterOrEqual(t, a, b)
assert.Less(t, a, b)
assert.LessOrEqual(t, a, b)
```
After all type of findings in whole project are handled, we can enable `testifylint` linter in `golangci-lint`.
> chore(linters): Fix findings found by testifylint: compares

- plugins/inputs/opensearch_query/opensearch_query_test.go
- plugins/outputs/opensearch/opensearch_test.go
The performance analyzer agent is known to be heavy-weight, and not something we need for our testing. As such let's disable it to prevent issues with starting up a container.
> test(opensearch): Disable perf analyzer in test images

- plugins/inputs/beat/beat_test.go
Address findings for [testifylint: error-is-as](https://github.com/Antonboom/testifylint#error-is-as) - checks usage of github.com/stretchr/testify.
```
❌   assert.Error(t, err, errSentinel) // Typo, errSentinel hits `msgAndArgs`.
assert.NoError(t, err, errSentinel)
assert.True(t, errors.Is(err, errSentinel))
assert.False(t, errors.Is(err, errSentinel))
assert.True(t, errors.As(err, &target))
✅   assert.ErrorIs(t, err, errSentinel)
assert.NotErrorIs(t, err, errSentinel)
assert.ErrorAs(t, err, &target)
```
In the first two cases, a common mistake that leads to hiding the incorrect wrapping of sentinel errors.
For single finding in Telegraf code it seems that `require.NoError` was used correctly but `err` should not be passed at all.
After all type of …
> chore(linters): Fix findings found by testifylint: error-is-as

- agent/accumulator_test.go
- filter/filter_test.go
- internal/templating/engine_test.go
- models/running_input_test.go
- plugins/inputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/inputs/intel_rdt/publisher_test.go
- plugins/inputs/nginx_plus/nginx_plus_test.go
- plugins/inputs/p4runtime/p4runtime_test.go
- plugins/outputs/postgresql/table_manager_test.go
- selfstat/selfstat_test.go
- testutil/accumulator.go
Address findings for [testifylint: require-error](https://github.com/Antonboom/testifylint#require-error) - checks usage of github.com/stretchr/testify.
```
❌   assert.NoError(t, err)
s.ErrorIs(err, io.EOF)
s.Assert().Error(err)
// And other error assertions...
✅   require.NoError(t, err)
s.Require().ErrorIs(err, io.EOF)
s.Require().Error(err)
```
Such "ignoring" of errors leads to further panics, making the test harder to debug.
After all type of findings in whole project are handled, we can enable `testifylint` linter in `golangci-lint`.
> chore(linters): Fix findings found by testifylint: require-error

- internal/globpath/globpath_test.go
- plugins/inputs/aliyuncms/aliyuncms_test.go
- plugins/inputs/gnmi/gnmi_test.go
- plugins/inputs/intel_powerstat/msr_test.go
- plugins/inputs/intel_rdt/intel_rdt_test.go
- plugins/inputs/intel_rdt/publisher_test.go
- plugins/inputs/interrupts/interrupts_test.go
- plugins/inputs/kinesis_consumer/kinesis_consumer_test.go
- plugins/inputs/mcrouter/mcrouter_test.go
- plugins/inputs/prometheus/kubernetes_test.go
- plugins/inputs/smart/smart_test.go
- plugins/inputs/syslog/rfc5426_test.go
- plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
- plugins/outputs/signalfx/signalfx_test.go
- plugins/outputs/timestream/timestream_test.go
- plugins/parsers/csv/parser_test.go
- plugins/processors/enum/enum_test.go
Address findings for [testifylint: error-nil](https://github.com/Antonboom/testifylint#error-nil) - checks usage of github.com/stretchr/testify.
```
❌   assert.Nil(t, err)
assert.NotNil(t, err)
assert.Equal(t, err, nil)
assert.NotEqual(t, err, nil)
✅   assert.NoError(t, err)
assert.Error(t, err)
```
After all type of findings in whole project are handled, we can enable `testifylint` linter in `golangci-lint`.
> chore(linters): Fix findings found by testifylint: error-nil

- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/parsers/json_v2/parser.go
resolves #14025 
builds on #14148
A new parser for each measurement wrecks performance for at least kafka_consumer input if you're using a schema registry, because the schema cache is kept in the parser, and without that you're making a network call per measurement.
What this does is to undo the work done for #13886 and instead to just throw a mutex around json_v2's Parse() contents (since the original bug was reported with the json_v2 parser).  The idea here is that we can investigate what that method is actually doing and gradually shrink the critical section until we've identified what's not threadsafe, and either leave the mutex around the minimal part of the action, or rewrite that section so it is threadsafe.
> fix(parsers.json_v2): Prevent race condition in parse function

- plugins/inputs/http_response/README.md
- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/http_response/sample.conf
With this option users can provide items to encode as a form. Combined with the POST option and header option this can be used to replicate the Post Form method.
fixes: #10839
> feat(inputs.http_response): Add body form option

- plugins/inputs/prometheus/kubernetes.go
The current implementation uses the config.BearerToken which is being read from the service account token file as part of the initialization. This  service account token becomes invalid, if the service account configured with time bound token after the specified expiry interval or service account signing key being rotated by either Kubernetes platform providers (such as AKS ) or the customer initiated signing key rotation in case of the Workload identity enabled clusters.
Fix is to read the bearer token from service account token file every time and instead of reading once at the initialization.
Fixes https://github.com/influxdata/telegraf/issues/14188
> fix(input.prometheus): read bearer token from file every time

- plugins/inputs/netflow/sflow_v5.go
Currently, the sysUptime field was used, but that isn't a unix timestamp:
>The time (in hundredths of a second) since the network management portion of the system was last re-initialized.
This PR rectifies this and uses the same as for the netflow decoders.
```diff
-netflow,source=127.0.0.1,version=sFlowV5 sys_uptime=12414u,agent_ip="192.168.119.184",agent_subid=100000u,seq_number=2u,in_snmp=3u,port_name="eno1",ip_version="IPv4" 12414000000
+netflow,source=127.0.0.1,version=sFlowV5 sys_uptime=12414u,agent_ip="192.168.119.184",agent_subid=100000u,seq_number=2u,in_snmp=3u,port_name="eno1",ip_version="IPv4" 16983296530
```
> fix(inputs.netflow): Fix sFlow metric timestamp

- .golangci.yml
- plugins/common/opcua/input/input_client.go
- plugins/inputs/eventhub_consumer/eventhub_consumer.go
- plugins/inputs/filestat/filestat.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
- plugins/inputs/intel_baseband/intel_baseband.go
- plugins/inputs/intel_rdt/intel_rdt.go
- plugins/inputs/ipvs/ipvs.go
- plugins/inputs/passenger/passenger.go
- plugins/inputs/phpfpm/phpfpm_test.go
- plugins/inputs/webhooks/github/github_webhooks_models.go
- plugins/outputs/http/http.go
- plugins/outputs/loki/loki.go
- plugins/outputs/postgresql/postgresql_bench_test.go
- plugins/outputs/warp10/warp10.go
- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
[perfsprint](https://github.com/catenacyber/perfsprint#perfsprint) is a linter for performance, aiming at usages of `fmt.Sprintf` which have faster alternatives.
This PR enables mentioned linter and addresses (by using `perfsprint --fix ./...`) following findings:
```
plugins/common/opcua/input/input_client.go:423:40                          perfsprint  fmt.Sprint can be replaced with o.LastReceivedData[nodeIdx].Quality.Error()
plugins/inputs/eventhub_consumer/eventhub_consumer.go:298:40               perfsprint  fmt.Sprintf can be replaced with faster strconv.Itoa
plugins/inputs/filestat/filestat.go:134:9                                  perfsprint  fmt.Sprintf can be replaced with faster hex.EncodeToString
plugins/inputs/gnmi/handler.go:145:34 …
```
> chore(linters): Enable `perfsprint` linter and fix all findings.

- plugins/inputs/cpu/README.md
- plugins/inputs/cpu/cpu.go
- plugins/inputs/cpu/cpu_test.go
- plugins/inputs/cpu/sample.conf
resolves #6306
This PR adds a comment stating the fact that `time_active` contains/includes `iowait` which might be counter-intuitive. Additionally, the PR moves the test-only `NewCPUStats` function to the test file.
> docs(inputs.cpu): Clarify 'time_active' contains 'iowait'

- plugins/inputs/cgroup/cgroup_linux.go
- plugins/inputs/cgroup/cgroup_test.go
- plugins/inputs/cgroup/testdata/backslash/machine-qemu-1-ubuntu/cpu.stat
Ensure we escape backslashes before the glob to avoid missing directories.
fixes: #8340
> fix(inputs.cgroup): Escape backslashes

- plugins/outputs/timestream/README.md
- plugins/outputs/timestream/timestream.go
- plugins/outputs/timestream/timestream_test.go
Timestream does not support uint64 values. Instead of returning an error, this will return values less than the max uint64 and cap values larger.
fixes: #14212
> fix(outputs.timestream): Clip uint64 values

- CHANGELOG.md
- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/native_finder.go
- plugins/inputs/procstat/procstat.go
resolves #2627 
This PR removes the useless fields
- `cpu_time_guest`
- `cpu_time_guest_nice`
- `cpu_time_idle`
- `cpu_time_irq`
- `cpu_time_nice`
- `cpu_time_soft_irq`
- `cpu_time_steal`
as those are never set by the underlying gopsutil library. Thus those fields are always zero. The PR keeps `cpu_time_iowait` which is zero for all platforms except Linux and adds a notice to the README about that fact.
> feat(inputs.procstat)!: Remove useless zero cpu_times

- plugins/inputs/jolokia2_agent/jolokia2_agent_test.go
There is a race in some cases where the tag set during integration testing is switched between two metrics.
> test(inputs.jolokia2_agent): ignore tags as order is not consistent

- migrations/all/inputs_mqtt_consumer.go
- migrations/inputs_mqtt_consumer/migration.go
- migrations/inputs_mqtt_consumer/migration_test.go
- migrations/inputs_mqtt_consumer/testcases/deprecated_metric_buffer/expected.conf
- migrations/inputs_mqtt_consumer/testcases/deprecated_metric_buffer/telegraf.conf
- migrations/inputs_mqtt_consumer/testcases/deprecated_metric_buffer_parser/expected.conf
- migrations/inputs_mqtt_consumer/testcases/deprecated_metric_buffer_parser/telegraf.conf
relates to #13375
This PR adds migration for the deprecated and ignored `metric_buffer` option of `inputs.mqtt_consumer`.
> feat(migrations): Add option migration for inputs.mqtt_consumer

- migrations/all/inputs.nats_consumer.go
- migrations/inputs_nats_consumer/migration.go
- migrations/inputs_nats_consumer/migration_test.go
- migrations/inputs_nats_consumer/testcases/deprecated_metric_buffer/expected.conf
- migrations/inputs_nats_consumer/testcases/deprecated_metric_buffer/telegraf.conf
- migrations/inputs_nats_consumer/testcases/deprecated_metric_buffer_parser/expected.conf
- migrations/inputs_nats_consumer/testcases/deprecated_metric_buffer_parser/telegraf.conf
relates to #13375
This PR adds migration for the deprecated and ignored `metric_buffer` option of `inputs.nats_consumer`.
> feat(migrations): Add option migration for inputs.nats_consumer

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
The lock for the messages map was collected after sending the metric to the accumulator. This was not the right behavior, as the accumulator could send the metric before we even got to the next step to lock and add the message to the map. As a result, in some scenarios the metric could get sent and attempt to mark it delivered before we even record the metric.
fixes: #14242
> fix(inputs.mqtt_consumer): Resolve could not mark message delivered

- config/config.go
- config/envvar.go
- config/internal_test.go
- config/testdata/envvar_comments.toml
- config/testdata/envvar_comments_expected.toml
resolves #14237
The current code for removing comments from TOML files is not aware of multi-line strings. As a consequence, hashes embedded in multi-line strings (as shown in #14237) will be considered a comment and all text until the end-line is removed.
This PR completely reworks the parsing by implementing a state machine matching the start and end of comments, strings, multi-line strings and handles escaping. It also adds a test case including (but not limited to) #14237.
> fix(config): Fix comment removal in TOML files

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration.go
- plugins/inputs/modbus/configuration_metric.go
- plugins/inputs/modbus/configuration_metric_test.go
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_register_test.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/configuration_request_test.go
- plugins/inputs/modbus/sample_metric.conf
- plugins/inputs/modbus/sample_register.conf
- plugins/inputs/modbus/sample_request.conf
- plugins/inputs/modbus/type_conversions.go
- plugins/inputs/modbus/type_conversions_string.go
resolves #9062 
This PR adds support for `STRING` fields to all available configuration-styles. For the `request` and `metric` style this requires the introduction of a new `length` parameter specifying the length of the string in "number of registers" i.e. half-number-of-bytes.
> feat(inputs.modbus): Add support for string-fields

- plugins/inputs/win_perf_counters/README.md
- plugins/inputs/win_perf_counters/performance_query.go
- plugins/inputs/win_perf_counters/sample.conf
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_test.go
resolves #14097
might resolve #9809 
In the current implementation we rely on the buffer-size returned by the Microsoft API in e.g. `GetCounterPath()`. However, as stated in the [API documentation](https://learn.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhexpandwildcardpatha#return-value) we should not rely on this returned value to allocate the buffer as the data might for example grow while querying.
This PR fixes the instances that currently relies on the returned size by preallocate a buffer with a start size (currently 1KiB) and grow exponentially until the data fits or the maximum size is reached. The "maximum size" can be specified by a new `MaxBufferSize` config option (default 4MiB). As an optimization we short-cut some iterations by jumping to the size returned by the …
> fix(inputs.win_perf_counter): Do not rely on returned buffer size

- plugins/inputs/ipset/ipset.go
- plugins/inputs/ipset/ipset_test.go
Parsing raw CLI output, and lines with a timeout shift the values over by two. This checks for timeout, and if it exists adds it as a field as well.
fixes: #14259
> fix(inputs.ipset): Parse lines with timeout

- plugins/inputs/disk/README.md
- plugins/inputs/disk/disk.go
- plugins/inputs/disk/disk_test.go
> fix(inputs.disk): Add inodes_used_percent field

- plugins/parsers/dropwizard/parser_test.go
- plugins/parsers/form_urlencoded/parser_test.go
- plugins/parsers/grok/parser_test.go
- plugins/parsers/logfmt/parser_test.go
- plugins/parsers/nagios/parser_test.go
- plugins/parsers/opentsdb/parser_test.go
- plugins/parsers/prometheus/parser_test.go
- plugins/parsers/value/parser_test.go
- plugins/parsers/wavefront/parser_test.go
I try to use the same two metrics throughout, obviously that does not work for value. Additionally, not all parsers accept a timestamp or multiple metrics at once.
> chore(parsers): Add additional parser benchmarks

- plugins/inputs/snmp/README.md
- plugins/inputs/snmp/sample.conf
- plugins/inputs/snmp/snmp.go
Related to #8011 and #4413
Add hint to use the source tag to standardise the snmp input by marking others as deprecated.
> feat(inputs.snmp): Hint to use source tag

- plugins/inputs/zfs/README.md
- plugins/inputs/zfs/zfs_linux.go
- plugins/inputs/zfs/zfs_linux_test.go
> fix(inputs.zfs): Gathering poolMetrics failed on zfs 2.2.0

- plugins/inputs/s7comm/type_conversions.go
resolves #
Change string parsing to truncate string at actual length instead of the max string length. 
Byte 0 reflects the max string length, 
Byte 1 reflects the actual length
Behavior before this PR: 
`got [30 17 76 95 50 52 48 95 84 75 49 52 95 51 48 46 112 114 100 112 114 100 97 111 46 112 114 100 76 79 0 0] for field "ProgrammName" @ 24 --> L_240_TK14_30.prdprdao.prdLO (string)`
now:
`got [30 17 76 95 50 52 48 95 84 75 49 52 95 51 48 46 112 114 100 112 114 100 97 111 46 112 114 100 76 79 0 0] for field "ProgrammName" @ 24 --> L_240_TK14_30.prd (string)`
> fix(inputs.s7comm): Truncate string to actual length

- plugins/inputs/elasticsearch/README.md
- plugins/inputs/elasticsearch/elasticsearch.go
- plugins/inputs/elasticsearch/sample.conf
- plugins/inputs/elasticsearch_query/README.md
- plugins/inputs/elasticsearch_query/elasticsearch_query.go
- plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
- plugins/inputs/elasticsearch_query/sample.conf
- plugins/inputs/kibana/README.md
- plugins/inputs/kibana/kibana.go
- plugins/inputs/kibana/sample.conf
- plugins/inputs/logstash/README.md
- plugins/inputs/logstash/logstash.go
- plugins/inputs/logstash/sample.conf
Enable elasticsearch, elasticsearch_query, kibana, and logstash plugins to use environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions) in order to connect through a proxy
resolves #14206
Adds Proxy to Transport struct, as in many other plugins.
> feat: Use HTTPClientConfig struct in elastic stack plugins

- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/native_finder.go
- plugins/inputs/procstat/native_finder_test.go
- plugins/inputs/procstat/native_finder_windows_test.go
- plugins/inputs/procstat/pgrep.go
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/procstat/sample.conf
> feat(inputs.procstat): Obtain process information through supervisor

- plugins/inputs/intel_rdt/intel_rdt.go
Instead, continue the loop as some PIDs can be so short-lived that they do not exist by the time we look for them.
fixes: #14272
> fix(inputs.intel_rdt): Do not fail on missing PIDs

- plugins/common/starlark/metric.go
- plugins/processors/starlark/starlark.go
- plugins/processors/starlark/starlark_test.go
The starlark process is used to make modifications to metrics, create
new metrics, or even remove metrics. When the starlark script returns it
does not return a metric with tracking information, only a generic
metric.
Currently we test to see if the metric returned is the same, but even if
they are idential, the tracking informiation is lost and the metric is
never marked accepted or dropped, hence we lose the tracking
information.
Instead of accepting everything, track the hash ID of each metric.
If the metric is the same, then continue on with the original metric.
For tracking metrics, we accept the new metric, since we can count on the
original metric to get ack'ed or nack'ed by the output.
> fix(processors.starlark): Maintain tracking information post-apply

- .golangci.yml
- plugins/inputs/gnmi/path.go
- plugins/serializers/graphite/graphite.go
Resolves one issue with gnmi where there was overlap in the values. The other issues were with graphite serializer. There are two regex that specify all the valid characters, which include ranges. The linter was marking this as suspect given the use of - in the middle of a regex, meaning a range. It is indeed the case of what we want.
fixes: #13176
> chore: Enable bad regex gocritic linter

- docs/LICENSE_OF_DEPENDENCIES.md
- docs/SQL_DRIVERS_INPUT.md
- go.mod
- go.sum
- plugins/inputs/sql/drivers.go
Added support for IBM Netezza data warehouse to inputs/sql plugin.
> feat(inputs.sql): Add support for IBM Netezza

- plugins/inputs/vault/vault_test.go
Additional support for vault test to ensure we wait for the minimum 50 metrics we are expecting due to the way that vault takes time to start up. 
If we continue to have issues with vault not having all the right metrics I will suggest we just ensure we get something back.
> test: Have vault wait for minimum number of metrics

- plugins/parsers/influx/influx_upstream/parser_test.go
- plugins/parsers/influx/parser_test.go
This adds a similar benchmark to the other parsers. While there are existing benchmarks, this aids in automation and having more consistent usage.
> chore(parsers.influx): Add benchmark

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/sample.conf
resolves #13980
Adds a mechanism to Kafka_consumer input for overriding metric name with a value from the kafka message header.
> feat(inputs.kafka_consumer): Use metric name from message header

- plugins/common/oauth/config.go
- plugins/outputs/http/http_test.go
Initialize `EndpointParams` map to prevent the panics when setting an endpoint-parameter.
> fix(common.oauth): Initialize 'EndpointParams' to avoid panic with 'audience' settings

- migrations/all/outputs_influxdb.go
- migrations/outputs_influxdb/migration.go
- migrations/outputs_influxdb/migration_test.go
- migrations/outputs_influxdb/testcases/convert_url/expected.conf
- migrations/outputs_influxdb/testcases/convert_url/telegraf.conf
- migrations/outputs_influxdb/testcases/merge_url/expected.conf
- migrations/outputs_influxdb/testcases/merge_url/telegraf.conf
- migrations/outputs_influxdb/testcases/merge_url_overlap/expected.conf
- migrations/outputs_influxdb/testcases/merge_url_overlap/telegraf.conf
relates to #13375
This PR adds migration for the deprecated `url` option replaced by `urls` in `outputs.influxdb`.
> feat(migrations): Add option migration for outputs.influxdb

- plugins/outputs/opensearch/README.md
- plugins/outputs/opensearch/opensearch.go
- plugins/outputs/opensearch/sample.conf
resolves #14334 
This PR exposes the `insecure_skip_verify` option correctly by embedding `commontls.TLSConfig` (instead of the full HTTP option set). By doing so, we also expose all other TLS options reflected by the `sample.conf` update.
> fix(outputs.opensearch): Expose TLS setting correctly
