release.sh
This can help with Raspberry Pis, embedded devices, and other IoT applications.
=> Add linux/arm to list of built binaries

README.md, plugins/all/all.go, plugins/mysql/mysql_test.go, plugins/postgresql/postgresql_test.go, plugins/prometheus/prometheus.go, plugins/prometheus/prometheus_test.go, plugins/system/system_test.go, testutil/accumulator.go
See #15, add prometheus plugin.
=> Prometheus plugin only

plugins/kafka_consumer/README.md
Adds a README for the Kafka consumer plugin.
=> Adds README for Kafka consumer plugin

scripts/telegraf.service
=> systemd unit support

plugins/redis/redis.go
see issue https://github.com/influxdb/telegraf/issues/74
=> add tag "port" to every redis metric

package.sh
Reverts influxdb/telegraf#87
fixes issue #95 
@ajohnstone
@srfraser
=> Revert "Add log rotation to /etc/logrotate.d for deb and rpm packages"

cmd/telegraf/telegraf.go, config.go
The following PR adds some missing pieces due to the large amount of merge conflicts that had to be dealt with for https://github.com/influxdb/telegraf/pull/109
=> add missing import and Tag marshalling

CHANGELOG.md, README.md
\cc @beckettsean @toddboom I'm updating the README to clarify InfluxDB/Telegraf version compatibility, let me know if you think this needs to be explained better!
see the README here: https://github.com/influxdb/telegraf/tree/cs-113
=> README update to address issue #113

CHANGELOG.md, config.go, outputs/kafka/kafka.go, plugins/all/all.go, plugins/ping/ping.go, plugins/ping/ping_test.go, testutil/accumulator.go
Closes #167
@exzz First go at a ping plugin, let me know how it looks and if it covers what you were looking for
=> Ping plugin

CHANGELOG.md, CONTRIBUTING.md, README.md, package.sh, scripts/telegraf.service
Deals with most of #170 
/cc @beckettsean
=> Update telegraf.service and packaging script for systemd

Godeps/Godeps.json, Godeps/_workspace/src/github.com/shirou/gopsutil/docker/docker_linux.go, Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_linux.go
=> Godep update: gopsutil

Makefile, accumulator.go, agent.go
=> Race condition fix: copy BatchPoints into goroutine

plugins/mysql/mysql.go, plugins/mysql/mysql_test.go, plugins/mysql/parse_dsn.go
=> Fix MySQL DSN -> tags parsing

CHANGELOG.md, agent.go, agent_test.go, cmd/telegraf/telegraf.go, config.go
@daviesalex This should fix interval jittering to be a completely random distribution
=> Fixup random interval jittering

outputs/prometheus_client/prometheus_client.go
Deals with part of #405, although it doesn't deal with the underlying
label error that is occuring.
=> Don't use panic-happy prometheus client With() function

CHANGELOG.md, plugins/jolokia/jolokia.go
=> Add optional auth credentials to Jolokia plugin

etc/telegraf.conf
=> Fix typo in telegraf.conf

CHANGELOG.md, README.md
This replaces https://github.com/influxdata/telegraf/pull/437
=> Release 0.10.0

CHANGELOG.md, plugins/inputs/system/net.go, plugins/inputs/system/net_test.go
=> Add an interface:"all" tag to the net protocol counters

README.md, agent.go, cmd/telegraf/telegraf.go, internal/config/config.go
=> Add a quiet mode to telegraf

CHANGELOG.md, plugins/inputs/all/all.go, plugins/inputs/nsq/nsq.go, plugins/inputs/nsq/nsq_test.go
- Polls a set of NSQD REST endpoints and collects counters for all topics, channels, and clients
Signed-off-by: Jeff Nickoloff <jeff@allingeek.com>
closes #492
=> NSQ Plugin

etc/telegraf.conf, plugins/inputs/system/disk.go, plugins/inputs/system/disk_test.go, plugins/inputs/system/mock_PS.go, plugins/inputs/system/ps.go
=> Filter mount points before stats are collected

plugins/inputs/elasticsearch/elasticsearch.go
=> Gather elasticsearch nodes in goroutines, handle errors

CONTRIBUTING.md, plugins/inputs/EXAMPLE_README.md, plugins/inputs/system/DISK_README.md, plugins/inputs/system/disk.go, plugins/inputs/system/disk_test.go
fixes #513
TODO: write a readme for disk plugin
=> Fixup some disk usage reporting, make it reflect df

CONFIGURATION.md, etc/telegraf.conf, internal/config/config.go, plugins/inputs/snmp/snmp_test.go, plugins/inputs/system/disk.go
=> Fix SNMP unit tests on OSX, improve tag config doc

plugins/outputs/datadog/datadog.go
=> Fix datadog json marshalling

CHANGELOG.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
=> statsd: allow template parsing fields. Default to value=

CHANGELOG.md, plugins/inputs/docker/docker.go
=> Fix possible panic if stat is nil

plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go, plugins/inputs/ping/ping_windows.go
=> Don't compile ping plugin on windows.

CHANGELOG.md, plugins/inputs/httpjson/httpjson.go
=> cleaned up the httpjson POST function.

CHANGELOG.md, agent/agent.go, internal/config/config.go
=> Set running output quiet mode in agent connect func

CHANGELOG.md, etc/telegraf.conf, plugins/outputs/influxdb/influxdb.go
=> Support specifying influxdb retention policy

CHANGELOG.md, Godeps, internal/config/config.go
=> Remove naoina/toml dependency, use influxdata/toml

CHANGELOG.md, plugins/inputs/all/all.go, plugins/inputs/tcp_listener/README.md, plugins/inputs/tcp_listener/tcp_listener.go, plugins/inputs/tcp_listener/tcp_listener_test.go
=> Adding a TCP input listener

CHANGELOG.md, plugins/inputs/mqtt_consumer/mqtt_consumer.go, plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
=> Provide option to set persistent session and client ID

agent/accumulator.go, agent/accumulator_test.go
=> Prevent Inf and NaN from being added, and unit test Accumulator

CHANGELOG.md, plugins/inputs/system/SYSTEM_README.md, plugins/inputs/system/system.go
=> Add number of users to 'system' plugin

README.md
@sparrc As suggested here influxdata/telegraf#851
=> Add FreeBSD tarball location to README

CHANGELOG.md, internal/models/running_output.go
=> Do not write metrics if there are 0 to write

CHANGELOG.md, plugins/outputs/influxdb/influxdb.go
=> influxdb output: quote the database name

CHANGELOG.md, agent/agent.go, agent/agent_test.go, internal/config/config.go
=> Allow users to tell telegraf Agent not to include host tag

CHANGELOG.md, plugins/inputs/udp_listener/udp_listener.go, plugins/outputs/prometheus_client/prometheus_client.go
=> Fix prometheus label names, and dont panic if invalid

CHANGELOG.md, plugins/inputs/memcached/memcached.go
=> Do not set deadline on connection with deadline already set

plugins/outputs/prometheus_client/prometheus_client.go
seems unnecessarily heavy to log every single time the prometheus output processes a metric that it doesn't support.
cc @jipperinbham @davidbirdsong @e11it
=> Don't log every string metric that prometheus doesnt support

CHANGELOG.md, Godeps
=> Godeps: update wvanbergen/kafka dependency

CHANGELOG.md, agent/agent.go
=> Set default tags in test accumulator

CHANGELOG.md, Godeps, plugins/outputs/influxdb/influxdb.go
closes #1058
closes #1059
also see https://github.com/influxdata/influxdb/pull/6425
=> influxdb output: close connections & dont always overwrite

plugins/inputs/tcp_listener/tcp_listener.go
leaving as comments for whenever I rig up global debug logging.
closes #1062
=> Do not log every tcp connect/disconnect

plugins/inputs/system/system.go
=> Add n_cpu field to system plugin

CHANGELOG.md, plugins/inputs/cloudwatch/cloudwatch.go, plugins/outputs/cloudwatch/cloudwatch.go, plugins/outputs/kinesis/kinesis.go
=> Dont specify AWS credential chain, use default

CHANGELOG.md, etc/telegraf.conf, plugins/inputs/docker/docker.go
=> Use a timeout for docker list & stat cmds

scripts/build.py
- Fix for --name build parameter
- Remove rc parameter from build script
- Fix regression on first-level tarball directory structure
- Convert any dashes/underscores in version tag to tilde
- Fix regression for packaging Windows configuration
=> Minor fixes to build script

plugins/inputs/snmp/snmp.go
=> Make OidInstanceMapping a field of the snmp host

plugins/inputs/ntpq/ntpq.go, plugins/inputs/ntpq/ntpq_test.go
=> Remove ntpq state prefixes and make their own tag

plugins/inputs/redis/redis.go
Fix #1203 
Just added the tags and compiled/tested the binary, looks to works correctly.
As I'm new in Go language, don't hesitate to tell me it looks wrong or unsafe.
=> Add role tag to redis plugins

plugins/inputs/influxdb/README.md, plugins/inputs/influxdb/influxdb.go, plugins/inputs/influxdb/influxdb_test.go
=> influxdb input: Add shard counter

plugins/inputs/ntpq/ntpq.go
=> ntpq input: ignore lines that are '-'

CHANGELOG.md, plugins/inputs/http_response/http_response.go, plugins/inputs/http_response/http_response_test.go
=> http_response: override req.Host header properly

CHANGELOG.md, Godeps
=> update gopsutil to commit with timeout support

plugins/inputs/github_webhooks/github_webhooks.go, plugins/inputs/github_webhooks/github_webhooks_test.go
=> Refactor GitHub webhooks

plugins/inputs/snmp/snmp.go
This update adds support for strings values. Not sure why this was missed.
=> Add the OctetString OID value support

CHANGELOG.md, scripts/telegraf.service
=> Log to /var/log/telegraf/telegraf.log on systemd

CHANGELOG.md, etc/telegraf.conf, plugins/outputs/influxdb/influxdb.go
=> influxdb output: write consistency parameter

CHANGELOG.md, README.md
=> Release 0.13.1

plugins/inputs/tail/tail.go
=> prevent potential tail datarace

CHANGELOG.md, plugins/inputs/http_response/README.md, plugins/inputs/http_response/http_response.go
=> http_response plugin: Add SSL config options

CHANGELOG.md, docs/DATA_FORMATS_INPUT.md, plugins/parsers/graphite/parser.go, plugins/parsers/graphite/parser_test.go
=> graphite parser: support multiple tag keys

CHANGELOG.md, Godeps, internal/internal.go, internal/internal_test.go, internal/models/filter.go, plugins/inputs/varnish/varnish.go, plugins/inputs/varnish/varnish_test.go
=> Allow wildcard filtering of varnish stats

plugins/outputs/influxdb/README.md
Added write_consistency to InfluxDB output documentation
=> write_consistency documentation

CONTRIBUTING.md
I think I have already signed CLA.
=> Fix typo in output plugin example

README.md, etc/telegraf.conf, plugins/outputs/all/all.go, plugins/outputs/graylog/README.md, plugins/outputs/graylog/graylog.go, plugins/outputs/graylog/graylog_test.go
=> Revert graylogrevert

CHANGELOG.md, plugins/inputs/system/ps.go
=> Disk plugin: return immediately if usage fails

plugins/inputs/tail/tail_test.go
=> Sleep longer in tail test

CHANGELOG.md, plugins/inputs/system/memory.go, plugins/inputs/system/memory_test.go
=> Adding active & inactive memory to mem plugin

internal/errchan/errchan.go, plugins/inputs/cloudwatch/cloudwatch.go, plugins/inputs/elasticsearch/elasticsearch.go, plugins/inputs/exec/exec.go, plugins/inputs/haproxy/haproxy.go, plugins/inputs/rabbitmq/rabbitmq.go
=> New object: ErrChan for concurrent err handling

plugins/inputs/system/MEM_README.md
=> fix used_percent Calculation formula

CHANGELOG.md, plugins/inputs/system/processes.go
=> Use glob match for finding /proc/<pid>/stat files

plugins/inputs/exec/README.md
=> Add timeout param to exec readme

CHANGELOG.md, Godeps
=> Fix rare panic in RHEL 5.2 diskio plugin

Makefile, plugins/outputs/opentsdb/opentsdb_test.go
=> OpenTSDB test problems, disabling output integration tests

CHANGELOG.md, README.md
=> Beta 1 Release 1.0

CHANGELOG.md, plugins/inputs/exec/exec.go
=> Fix exec plugin panic with single binary

CHANGELOG.md, etc/telegraf.conf, plugins/inputs/kafka_consumer/kafka_consumer.go
=> Change default zookeeper chroot to empty string

CHANGELOG.md, etc/telegraf.conf, plugins/inputs/ping/ping.go
=> Kodek patch 1

CHANGELOG.md, plugins/inputs/statsd/statsd.go, plugins/inputs/tcp_listener/tcp_listener.go, plugins/inputs/udp_listener/udp_listener.go
=> statsd: do not log every dropped metric.

CHANGELOG.md, etc/telegraf.conf, plugins/outputs/influxdb/influxdb.go
=> change "default" retention policy to ""

CHANGELOG.md, README.md
=> Beta 2 Release 1.0

plugins/inputs/sqlserver/sqlserver.go
I added Rows/Logs max size counters for tracking databases that do not have autogrowth enabled. The counters return numbers in 8KB pages since there are a few special values (such as -1 for no max size) that can't directly be multiplied by 8192 to get size in bytes.
Also added Rows/Logs size in 8KB pages for comparison from the same system table. Even though it returns the same size as sizes from sys.dm_io_virtual_file_stats which are already collected.
=> Updated sqlserver.go - Added Rows/Logs max size

CHANGELOG.md, CONTRIBUTING.md, Makefile, plugins/inputs/kafka_consumer/README.md
=> Remove docker-machine/boot2docker dependencies & references

CHANGELOG.md, internal/config/config.go
=> Trim BOM from config file for windows support

CHANGELOG.md, plugins/outputs/prometheus_client/prometheus_client.go
=> Recover from prometheus multiple handler panic

.gitignore
=> Add build directory to git ignore

plugins/inputs/logparser/README.md
=> Add note about influxdb compatability

README.md
Github and Rollbar are now part of the webhooks plugin.
=> Cleanup the list of plugins.

CHANGELOG.md, plugins/outputs/prometheus_client/prometheus_client.go
=> prometheus_client, implement Collector interface

Makefile, plugins/inputs/aerospike/aerospike_test.go
see http://www.aerospike.com/docs/operations/upgrade/stats_to_3_9
TODO change aerospike input plugin to use official go client library.
=> temp ci fix, aerospike changed their metrics

CHANGELOG.md, Makefile, agent/agent.go, plugins/inputs/tcp_listener/tcp_listener.go, plugins/inputs/udp_listener/udp_listener.go, plugins/outputs/graphite/graphite.go, plugins/outputs/librato/librato.go, plugins/serializers/graphite/graphite.go, plugins/serializers/graphite/graphite_test.go, scripts/circle-test.sh
=> Graphite write deadline

CHANGELOG.md, plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/spec_processor.go
=> procstat plugin: store PID as a field

CHANGELOG.md, plugins/inputs/cassandra/cassandra.go
=> cassandra plugin lower version support added

plugins/outputs/prometheus_client/prometheus_client.go
=> Change prometheus replacer to reverse regex replacer

CHANGELOG.md, plugins/inputs/logparser/grok/grok_test.go, plugins/inputs/logparser/grok/influx_patterns.go, plugins/inputs/logparser/grok/patterns/influx-patterns
=> Change resp_code from field to tag in logparser

CHANGELOG.md, Godeps, README.md, plugins/inputs/aerospike/aerospike.go
=> Telegraf v1.0 beta 3

plugins/inputs/aerospike/README.md, plugins/inputs/aerospike/aerospike.go, plugins/inputs/ceph/README.md
=> clean up and finish aerospike refactor & readme

CHANGELOG.md, plugins/inputs/dns_query/dns_query.go, plugins/inputs/dovecot/dovecot.go, plugins/inputs/memcached/memcached.go, plugins/inputs/mongodb/mongodb.go, plugins/inputs/mysql/mysql.go, plugins/inputs/mysql/mysql_test.go, plugins/inputs/nginx/nginx.go, plugins/inputs/nsq/nsq.go
closes #1439
closes #1440
closes #1441
closes #1442
closes #1443
closes #1444
closes #1445
cc @phemmer
=> Fix err race condition and partial failure issues

CHANGELOG.md, plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
=> Strip container_version from container_image tag

agent/accumulator.go
minor code cleanup. This code isn't used anywhere
=> remove unused accumulator.prefix

plugins/inputs/tcp_listener/tcp_listener.go, plugins/inputs/tcp_listener/tcp_listener_test.go, plugins/inputs/udp_listener/udp_listener.go, plugins/inputs/udp_listener/udp_listener_test.go, testutil/accumulator.go
=> tcp/udp listeners, remove locks & improve test coverage

etc/telegraf.conf, plugins/inputs/logparser/README.md, plugins/inputs/logparser/grok/grok.go, plugins/inputs/logparser/grok/grok_test.go, plugins/inputs/logparser/grok/influx_patterns.go, plugins/inputs/logparser/grok/patterns/influx-patterns, plugins/inputs/logparser/logparser.go
=> Begin implementing generic timestamp logparser capability

plugins/outputs/influxdb/influxdb.go
=> Remove IF NOT EXISTS from influxdb output

agent/accumulator.go, agent/accumulator_test.go, agent/agent.go, internal/config/config.go, internal/config/config_test.go, internal/models/filter.go, internal/models/filter_test.go, internal/models/running_input.go, internal/models/running_output.go, internal/models/running_output_test.go
=> Rename internal_models package to models

CONTRIBUTING.md, plugins/inputs/EXAMPLE_README.md, plugins/inputs/mock_Plugin.go
=> Add request for sample queries

plugins/outputs/kafka/README.md
=> Add Kafka output readme

plugins/inputs/zookeeper/README.md
=> Modernize zookeeper readme

CHANGELOG.md, plugins/inputs/ntpq/ntpq.go, plugins/inputs/ntpq/ntpq_test.go
=> ntpq: don't index ntp fields that dont exist

plugins/inputs/mysql/mysql.go
=> Added missing column fix for #1646

docs/WINDOWS_SERVICE.md
Added quotes around spaces in files paths.
Slight change to wording on point 4.
=> Update to WINDOWS_SERVICE.md

docs/WINDOWS_SERVICE.md
Reverts influxdata/telegraf#1663
=> Revert "Update to WINDOWS_SERVICE.md"

CHANGELOG.md, CONTRIBUTING.md, accumulator.go, agent/accumulator.go, agent/accumulator_test.go, metric.go, metric_test.go, plugins/inputs/mysql/mysql.go, plugins/inputs/sqlserver/sqlserver.go, plugins/inputs/sqlserver/sqlserver_test.go, plugins/inputs/system/cpu.go, plugins/inputs/system/disk.go, plugins/inputs/system/kernel.go, plugins/inputs/system/memory.go, plugins/inputs/system/memory_test.go, plugins/inputs/system/net.go, plugins/inputs/system/processes.go, plugins/inputs/system/ps.go, plugins/inputs/system/system.go, plugins/outputs/prometheus_client/prometheus_client.go, testutil/accumulator.go
=> Implementing Gauge and Counter types

agent/accumulator.go, agent/accumulator_test.go, docs/CONFIGURATION.md, filter/filter.go, filter/filter_test.go, internal/config/config.go, internal/config/config_test.go, internal/models/filter.go, internal/models/filter_test.go, internal/models/running_output.go, internal/models/running_output_test.go, plugins/inputs/varnish/varnish.go
started working on this with the idea of fixing #1623, although I
realized that this was actually just a documentation issue around
a toml eccentricity.
closes #1623
=> Refactor and code cleanup of filtering

CHANGELOG.md, internal/internal_test.go, plugins/inputs/kafka_consumer/kafka_consumer_test.go, plugins/inputs/mongodb/mongostat.go
=> mongodb input: fix version 2.2 panic

CHANGELOG.md, plugins/inputs/influxdb/influxdb.go, plugins/inputs/influxdb/influxdb_test.go
=> Fix unmarshal of influxdb metrics will null tags

CHANGELOG.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
=> Fix statsd scientific notation parsing

CHANGELOG.md, plugins/inputs/sensors/sensors.go, plugins/inputs/sensors/sensors_test.go
=> fix issue #1716

CHANGELOG.md, plugins/outputs/prometheus_client/prometheus_client.go
=> Fix prometheus output panic on reload

CHANGELOG.md, plugins/inputs/kafka_consumer/kafka_consumer.go
=> kafka panic: Check that error is non-nil before

plugins/inputs/statsd/statsd_test.go
=> add statsd parsing benchmarks

CHANGELOG.md, plugins/inputs/influxdb/influxdb.go, plugins/outputs/prometheus_client/prometheus_client.go
=> Prometheus output: do not remake metrics map each write

plugins/inputs/sysstat/sysstat.go
=> Fix sysstat resource leak

plugins/inputs/mysql/mysql.go
=> add mysql uptime

CHANGELOG.md, plugins/inputs/powerdns/powerdns.go, plugins/inputs/powerdns/powerdns_test.go
=> Fix powerdns integer parse error handling

CHANGELOG.md, plugins/inputs/varnish/varnish.go
=> Fix varnish plugin to use default values

CHANGELOG.md, internal/globpath/globpath.go
=> globpath: only walk tree if ** is defined

plugins/inputs/sqlserver/sqlserver.go
=> SQL Server plugin: Fix collation issue

plugins/inputs/sqlserver/sqlserver.go
=> SQL Server plugin: Fix WaitStats issue

CHANGELOG.md, scripts/telegraf.service
=> Ririsoft log to systemd

CHANGELOG.md, plugins/outputs/graylog/graylog.go
=> adding the tags in the graylog output plugin

plugins/inputs/snmp/CONFIG-EXAMPLES.md, plugins/inputs/snmp/README.md
Added a standard example for collecting interface metrics from switches or routers and tagging them properly.
closes #1666
=> Create CONFIG-EXAMPLES.md with a switch interface example

plugins/inputs/snmp/DEBUGGING.md
=> Add doc for SNMP debug tips

CHANGELOG.md, plugins/inputs/phpfpm/phpfpm.go
=> Fix phpfpm fcgi client panic when URL doesnt exist

CHANGELOG.md, plugins/inputs/ping/ping.go
=> Set reasonable defaults in ping plugin

plugins/inputs/mysql/mysql.go
---
There are minor typos in MySQL plugin's sampleConfig.
=> MySQL Plugin sampleConfig Comment Typo

circle.yml
=> Update Go version: 1.7.1->1.7.3

plugins/inputs/cassandra/README.md
Just a small update to fix the typo in the cassandra metrics and be more precise about the availability of some metrics for Cassandra 3 only.
=> Just fix typo

plugins/inputs/nats_consumer/nats_consumer.go, plugins/inputs/nats_consumer/nats_consumer_test.go
=> nats_consumer: buffer incoming messages

etc/telegraf.conf, plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch.go
=> Update docs on Cloudwatch. Set default period to 5m.

README.md, docs/AGGREGATORS_AND_PROCESSORS.md, plugins/aggregators/minmax/README.md, plugins/processors/printer/README.md
- fully document aggregator and processor plugins
- improve readme.md
closes #1989
=> Documentation improvements

CHANGELOG.md, internal/internal.go, internal/internal_test.go
=> Fix single quote parsing of TOML durations

plugins/inputs/apache/README.md, plugins/inputs/apache/apache.go
This PR will add enhancements to the input plugin related to https://github.com/influxdata/telegraf/issues/1961
- [ X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ X] README.md updated (if adding a new plugin)
=> Apache input enhancements ( added Basic Auth and SSL skipverify )

plugins/inputs/system/disk.go
IopsInProgress (i.e. DiskQueueLength) is exported
=> Added IopsInProgress to diskio stats

CHANGELOG.md, plugins/inputs/rabbitmq/rabbitmq.go
=> Configurable RabbitMQ HTTP timeouts #1997

agent/agent.go, metric.go
=> Add Copy() function to Metric interface

CHANGELOG.md, README.md, plugins/outputs/all/all.go, plugins/outputs/discard/README.md, plugins/outputs/discard/discard.go
=> 'discard' output plugin

CHANGELOG.md, circle.yml
=> Go version 1.7.3 -> 1.7.4

README.md
Updates the README links from 1.0.1 to 1.1.1.
=> Update README download links

plugins/inputs/win_perf_counters/win_perf_counters.go
=> Fixed bug that you cannot gather data on non english systems #1730 

CHANGELOG.md, plugins/inputs/filestat/filestat.go
=> Fix possible panic when file info cannot be gotten

CHANGELOG.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
=> Support strings in statsd set measurements

CHANGELOG.md, plugins/inputs/statsd/README.md, plugins/inputs/statsd/statsd.go
=> Set default values for delete_ configuration options

plugins/inputs/ping/README.md
=> ping: fix typo in README

plugins/inputs/mysql/mysql.go
This adds the Questions status variable to mysql input plugin as per #1988
=> Add Questions status variable to mysql input plugin

CHANGELOG.md, Godeps_windows, plugins/inputs/win_perf_counters/pdh.go, plugins/inputs/win_perf_counters/win_perf_counters.go
rebasing and pushing #2017 so that unit tests will run
closes #1763
closes #2017
=> Importing pdh from github.com/lxn/win

CHANGELOG.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
=> Support negative statsd counters

CHANGELOG.md, plugins/inputs/elasticsearch/elasticsearch.go
=> Mask username/password from error messages

plugins/inputs/mongodb/mongodb.go
=> mongodb: dont print unecessary & inaccurate auth failure

plugins/inputs/haproxy/README.md
I updated haproxy readme file to include basic authentication
=> Document basic auth for haproxy

plugins/inputs/http_listener/http_listener.go, plugins/inputs/http_listener/http_listener_test.go
=> Accept an HTTP request body without newline at end

plugins/outputs/opentsdb/opentsdb.go
=> OpenTSDB filter types for HTTP AND telnet

plugins/inputs/sqlserver/sqlserver.go
Hello, 
Pull request for bug #2077 
Regards,
=> Fixed Bug #2077 SQL Server

README.md, plugins/outputs/amqp/README.md
=> Direct people to downloads page for installation

CHANGELOG.md, plugins/inputs/http_listener/http_listener.go, plugins/parsers/influx/parser.go, plugins/parsers/influx/parser_test.go
=> Add newline to influx line-protocol if not present

scripts/post-install.sh
=> Debian package: check for group before useradd

plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go
The changes in #1848 resulted in lines being dropped if they had an empty
tag. Let's allow all lines that have empty or missing tags!
See #1927 for discussion about only allowing empty tags
=> snmp: Allow lines with empty or missing tags

plugins/outputs/riemann/riemann_test.go
=> Fix riemann output unit tests

CHANGELOG.md, internal/models/running_output.go, internal/models/running_output_test.go
=> running output: Drop nil metrics

CHANGELOG.md, circle.yml
=> Go version 1.7.4 -> 1.7.5

README.md
=> Update readme to link to k8s plugin

internal/globpath/globpath_test.go
=> Add more nested globpath tests

Godeps, metric.go, metric/metric.go, metric/metric_test.go
=> Remove metric.Point from metric interface

Godeps, internal/config/config.go
=> don't use influxdata/config, just use influxdata/toml

agent/agent.go
=> Skip service input plugins in test mode

plugins/inputs/apache/README.md
=> Fix typo - Default from Defalt

CHANGELOG.md, agent/agent.go, circle.yml, plugins/outputs/prometheus_client/prometheus_client.go
This PR will fix issue #2282 but requires Go 1.8 in order to merge
fixes #2282
=> Fix prometheus_client reload behavior

CHANGELOG.md, plugins/inputs/mysql/mysql.go
=> Check for errors in user stats & process list

plugins/outputs/file/README.md
=> Added default config to file output pugin's README

plugins/inputs/webhooks/github/github_webhooks.go, plugins/inputs/webhooks/github/github_webhooks_test.go
=> Respond 200 when receiving a ping event.

Godeps
=> update gopsutil for file close fixes

docs/CONFIGURATION.md
Add information about default configuration file locations.  Also mention that the config directory option is available.
=> Add location + config-dir details to CONFIGURATION.md

CHANGELOG.md, scripts/build.py
=> create telegraf.d directory in tarball

Godeps, plugins/inputs/logparser/logparser.go, plugins/inputs/tail/tail.go, plugins/inputs/tail/tail_test.go
This primarily solves issues we ran into when implementing #2555.
=> Use fork of hpcloud/tail

CHANGELOG.md, internal/buffer/buffer.go
=> Fix possible deadlock when output cannot write.

plugins/inputs/EXAMPLE_README.md, plugins/inputs/httpjson/README.md, plugins/inputs/httpjson/httpjson.go
=> Update httpjson documentation

plugins/inputs/system/CPU_README.md
Even though simple, a total novice might find a sample config stanza handy. For the TLDR; generation
=> Add sample config stanza for CPU

CHANGELOG.md, Godeps, README.md, docs/DATA_FORMATS_INPUT.md, docs/LICENSE_OF_DEPENDENCIES.md, internal/config/config.go, logger/logger.go, logger/logger_test.go, plugins/inputs/socket_listener/socket_listener.go, plugins/parsers/collectd/parser.go, plugins/parsers/collectd/parser_test.go, plugins/parsers/registry.go
=> Collectd parser

internal/config/config.go
Basically just pulled the documentation from AgentConfig into the sample config. #2638
=> Clarify precision documentation

Godeps, plugins/inputs/logparser/grok/grok_test.go
=> Update grok version

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go
The documentation I found misleading/not complete. Took my suggested changes from here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ping/ping.go#L49-L61
=> Update ping-input-plugin Readme

plugins/inputs/logparser/README.md, plugins/inputs/logparser/grok/grok.go
=> Improve logparser README

CHANGELOG.md, plugins/inputs/internal/internal.go
This field does not contain bytes
fixes #2671
=> Rename heap_objects_bytes to heap_objects in internal plugin.

CHANGELOG.md, plugins/inputs/webhooks/README.md, plugins/inputs/webhooks/papertrail/README.md, plugins/inputs/webhooks/papertrail/papertrail_test.go, plugins/inputs/webhooks/papertrail/papertrail_webhooks.go, plugins/inputs/webhooks/papertrail/papertrail_webhooks_models.go, plugins/inputs/webhooks/webhooks.go, plugins/inputs/webhooks/webhooks_test.go
=> Add input for receiving papertrail webhooks

plugins/inputs/memcached/README.md
=> Memcached input documentation

CHANGELOG.md, plugins/inputs/sysstat/sysstat.go, plugins/inputs/sysstat/sysstat_interval_test.go
=> Use C locale when running sadf

plugins/inputs/procstat/README.md
=> Improve procstat input documentation

CHANGELOG.md, plugins/outputs/file/file.go
=> Don't close stdout on config reload.

plugins/inputs/postgresql_extensible/README.md
=> Update postgresql_extensible README.md

plugins/outputs/kafka/kafka.go
=> it's -> its

CHANGELOG.md, plugins/inputs/rabbitmq/README.md, plugins/inputs/rabbitmq/rabbitmq.go
=> Add initial documentation for rabbitmq input.

plugins/outputs/socket_writer/socket_writer.go, plugins/outputs/socket_writer/socket_writer_test.go
=> fix close on closed socket_writer

plugins/inputs/kafka_consumer/README.md
=> reflect zookeeper chroot config in readme

scripts/build.py, scripts/init.sh, scripts/post-install.sh
=> Add SLES11 support to rpm package

plugins/inputs/postgresql_extensible/README.md
I suppose I don't have to update `CHANGELOG.md` in a case of such a trivial fix, do I?
=> Improve PostgreSQL plugin documentation

plugins/inputs/consul/README.md
=> Consul plugin README.md typo

README.md, plugins/inputs/prometheus/README.md
=> Add documentation for fetching metrics on Caddy HTTP and Prometheus

CHANGELOG.md, plugins/inputs/cassandra/cassandra.go
Changes for https://github.com/influxdata/telegraf/issues/2607
=> More explicit 404 error(cassandra input)

plugins/outputs/prometheus_client/prometheus_client.go, plugins/outputs/prometheus_client/prometheus_client_test.go
=> Remove label value sanitization in prometheus output

plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
=> Use strings.Join in statsd input

plugins/inputs/system/linux_sysctl_fs.go, plugins/inputs/system/processes.go
=> Fix build on Windows

Godeps, docs/LICENSE_OF_DEPENDENCIES.md
=> Update elastic dependency

plugins/inputs/chrony/README.md, plugins/inputs/chrony/chrony.go, plugins/inputs/chrony/chrony_test.go
=> Fix #2988 - Add system time field to chrony input

plugins/inputs/ping/ping_windows.go, plugins/inputs/ping/ping_windows_test.go
Adding newlines in ping input plugin to fix vet under windows
=> fix go vet under windows

plugins/inputs/postgresql_extensible/README.md
=> Fix typo in postgresql_extensible/README.md

plugins/inputs/mysql/mysql.go
=> Correct spelling

plugins/outputs/prometheus_client/prometheus_client.go
=> Prometheus reload

plugins/inputs/logparser/logparser.go
=> Fix panic in logparser if file cannot be opened

plugins/inputs/zookeeper/zookeeper.go
=> Default to localhost if zookeeper has no servers set

plugins/inputs/iptables/iptables.go, plugins/inputs/iptables/iptables_test.go
=> Allow iptable entries with trailing text

appveyor.yml
Creating an appveyor.yml build file so that telegraf can be compiled and tested under windows for CI.  This is intended to supplement the existing CircleCI pipeline.
Corresponding issue https://github.com/influxdata/telegraf/issues/1719
- [Y] Signed [CLA](https://influxdata.com/community/cla/).
- [N/A] Associated README.md updated.
- Changes aren't functional
- [N/A] Has appropriate unit tests.
- Runs existing unit tests
=> Windows Appveyor Build

appveyor.yml
=> Add Appveyor continuous integration

plugins/inputs/zipkin/convert.go, plugins/inputs/zipkin/convert_test.go
Addresses https://github.com/influxdata/telegraf/pull/3080#discussion_r130704773
=> Change default hostname value when no endpoint is provided in zipkin plugin

plugins/inputs/zipkin/convert.go, plugins/inputs/zipkin/convert_test.go
Addresses influxdata/telegraf#3080 (comment)
=> Change default service name when no endpoint is provided

plugins/inputs/zipkin/zipkin.go, plugins/inputs/zipkin/zipkin_test.go
Addresses [this comment](https://github.com/influxdata/telegraf/pull/3080/files/59634af5129a1f6ac386ce1893c7d59ebc922ed0#r130703677) and [this comment](https://github.com/influxdata/telegraf/pull/3080#discussion_r130704773)
=> Zipkin service fixes

plugins/inputs/docker/README.md
=> remove tag_env duplicate from inputs/docker/README

plugins/inputs/logparser/logparser.go, plugins/inputs/logparser/logparser_solaris.go, plugins/inputs/tail/tail.go, plugins/inputs/tail/tail_solaris.go
=> Skip logparser and tail on solaris

plugins/inputs/ntpq/ntpq.go, plugins/inputs/ntpq/ntpq_windows.go
- [na ] Associated README.md updated.
- [na ] Has appropriate unit tests.
=> Build NTPQ on Windows, as it builds fine and works with a port of NTPQ

plugins/inputs/apache/README.md, plugins/inputs/apache/apache.go
=> Improve apache input documentation

plugins/inputs/system/system.go
=> Allow using system plugin in Windows

plugins/inputs/logparser/logparser.go, plugins/inputs/tail/tail.go
=> Discard logging from tail library

plugins/outputs/influxdb/influxdb.go, plugins/outputs/influxdb/influxdb_test.go
Add special handling for errors from InfluxDB.
closes: #3144
=> Don't retry points beyond retention policy

scripts/post-install.sh
=> Don't start Telegraf on install in Amazon Linux

plugins/inputs/system/DISK_README.md
=> docs: fix docker image name

internal/internal_test.go
This is not sufficient to fix #3059 but is hopefully a start.
=> Fix short tests on darwin

scripts/build.py
=> Fix arm64 linux packages contain 32bit executable

plugins/inputs/httpjson/httpjson_test.go, plugins/parsers/json/parser.go, plugins/parsers/json/parser_test.go
=> Allow JSON data format to contain zero metrics

plugins/inputs/sqlserver/sqlserver.go
=> Fix case sensitivity error in sqlserver input

plugins/inputs/http_response/http_response.go
=> Add support for proxy environment variables to http_response

CHANGELOG.md
=> fixed link for wavefront plugin

filter/filter.go, plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
=> Fix container name filters in docker input

plugins/inputs/sqlserver/sqlserver.go
closes #3329 
@valerian1978 Can you test?  Here is the [Windows 64-bit build](https://8531-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.EbtouJX/build/windows/amd64/telegraf-1.5.0%257Ee92ad1e_windows_amd64.zip)
=> Fix case sensitivity issue in sqlserver query

plugins/inputs/mongodb/mongostat.go
=> Fix mongodb input panic when restarting mongodb

docs/WINDOWS_SERVICE.md
=> Fix small typo

plugins/parsers/json/parser.go
=> Remove warning when JSON contains null value

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go, plugins/inputs/ping/ping_windows.go, plugins/inputs/ping/ping_windows_test.go
=> DNS lookup before ping

plugins/inputs/docker/README.md
Updated README with docker_swarm metrics content.
=> updated docker plugin README

plugins/inputs/varnish/README.md
This PR complete the README with the new configuration option (as I forgot to do so in #3398).
=> Update input-varnish config example in README

plugins/outputs/datadog/datadog.go
=> Redact datadog API key in log output

Godeps
closes #3311 
closes #3339 
- [] Has appropriate unit tests.
=> Update gopsutil to v2.17.10

plugins/inputs/docker/docker.go
=> Use current time if container read time is zero value

plugins/inputs/system/ps.go
=> Always ignore autofs filesystems in disk input

plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/procstat_test.go
=> add tests for procstat systemd & cgroup matching

Godeps
Potential fix for #3486, will add links to packages for further testing when build completes.
closes #3486
=> Update gopsutil version to include netstat fix

Godeps
=> Update sarama-cluster to latest release

plugins/inputs/smart/smart.go
=> Use auto type detection for scanned devices

plugins/inputs/mysql/mysql.go, plugins/inputs/mysql/mysql_test.go
This PR includes a number of fixes for MySQL's data types. As pointed out in the comments of #1896, many global variables and global statuses had incorrect reporting or were missing. Also many items that would be helpful to check against that were strings would never be reported at all. 
The Global Statuses were all being forced into an Integer type and this led to things like the wsrep_ready status always reporting a zero. 
Other fields that were being parsed by the parseValue function were being missed or were incorrectly typed as well. Some were being missed because the output of SHOW GLOBAL STATUS reports an uppercase "YES" or "NO" rather than "Yes" or "No". 
parseValue is used in a few places. The way it used to work it would try and check for MySQL booleans, set 0 or 1 accordingly, …
=> mysql fixes for #1896

docs/CONFIGURATION.md
- [N/A] Associated README.md updated.
- [N/A] Has appropriate unit tests.
=> Typo and sentence consistency

plugins/inputs/webhooks/github/README.md
This fixes a tiny bit of documentation.
Relevant lines:
- https://github.com/influxdata/telegraf/blob/master/plugins/inputs/webhooks/github/github_webhooks_models.go#L119
- https://github.com/influxdata/telegraf/blob/master/plugins/inputs/webhooks/github/github_webhooks_models.go#L149
=> Fix documentation for GitHub webhooks

etc/telegraf.conf, plugins/inputs/jolokia2/jolokia_agent.go
=> Fix name error in jolokia2_agent sample config

plugins/inputs/dcos/client.go
=> Fix DC/OS login expiration time

plugins/outputs/influxdb/client/http.go
=> Set content-type charset in influxdb output and allow it be overridden

docs/DATA_FORMATS_INPUT.md, plugins/parsers/dropwizard/parser.go, plugins/parsers/dropwizard/parser_test.go
- Parse string and boolean fields 
- Handle special characters in parsed tags and fields
=> Dropwizard format improvements

plugins/serializers/graphite/graphite.go
=> Remove graphite serializer replacement of dot with underscore in field

plugins/inputs/system/disk_test.go, plugins/inputs/system/ps.go
=> Set path to / if HOST_MOUNT_PREFIX matches full path

plugins/inputs/apache/README.md, plugins/inputs/zipkin/README.md
This is just a doc update.  No code is changing.
=> Propose small spelling changes

Makefile, appveyor.yml
=> Fix Makefile on Windows and use in AppVeyor build

plugins/inputs/mesos/README.md, plugins/inputs/mesos/mesos.go, plugins/inputs/mesos/mesos_test.go
=> Add TLS support to the mesos input plugin

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
=> Support deadline in ping plugin

plugins/outputs/mqtt/README.md
- [  ] Signed [CLA](https://influxdata.com/community/cla/).
- [  ] Associated README.md updated.
- [  ] Has appropriate unit tests.
=> Create README.md for mqtt output

plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
Fixes bug #3816, I will add unittest tomorrow.
=> Add host to ping timeout log message

plugins/inputs/tail/tail_test.go
Fixes bug https://github.com/influxdata/telegraf/issues/3746
=> Fix intermittent TestTailBadLine failures

CHANGELOG.md, plugins/inputs/socket_listener/socket_listener.go, plugins/inputs/socket_listener/socket_listener_test.go
=> fix socket_listener setting ReadBufferSize on TCP sockets

plugins/inputs/phpfpm/README.md, plugins/inputs/phpfpm/phpfpm.go, plugins/inputs/phpfpm/phpfpm_test.go
=> Add tag for target url to phpfpm input

plugins/inputs/dcos/client.go, plugins/inputs/dcos/client_test.go
=> Fix DC/OS URL creation race

plugins/inputs/passenger/README.md
=> Update passenger input documentation

plugins/inputs/consul/README.md, plugins/inputs/consul/consul.go
=> Add TLS settings to consul README

plugins/outputs/influxdb/README.md, plugins/outputs/influxdb/influxdb.go
=> Add support for skipping database creation

plugins/outputs/influxdb/http.go, plugins/outputs/influxdb/http_test.go, plugins/outputs/influxdb/influxdb.go
=> Add support for connecting to InfluxDB over a unix domain socket

plugins/inputs/amqp_consumer/amqp_consumer.go
This PR will fix [#3933](https://github.com/influxdata/telegraf/issues/3933) and reconnect AMQP consumer correctly
No need to modify README.md as no change in behaviour
=> Reconnect AMQP consumer to broker

CHANGELOG.md, plugins/inputs/zookeeper/README.md, plugins/inputs/zookeeper/zookeeper.go
=> Add TLS support to zookeeper input

plugins/inputs/smart/smart.go
=> Fix parsing of dos line endings in smart input

plugins/outputs/influxdb/influxdb.go, plugins/outputs/influxdb/influxdb_test.go
=> Fix bug preventing database from being recreated

README.md, plugins/inputs/all/all.go, plugins/inputs/fibaro/README.md, plugins/inputs/fibaro/fibaro.go, plugins/inputs/fibaro/fibaro_test.go
For review, comments & discussion:
- The plugin is in place in my environment and polling devices value(s) from my Fibaro controller
=> Add Fibaro input plugin

plugins/inputs/logparser/grok/grok.go, plugins/inputs/logparser/grok/grok_test.go
=> Allow grok pattern to contain newlines

cmd/telegraf/telegraf.go, cmd/telegraf/usage.go, cmd/telegraf/usage_windows.go
=> Add --console and --service to usage message in Windows

plugins/parsers/syslog/parser.go
=> Handling best effort parsing output (syslog/rfc5424)

plugins/parsers/syslog/parser.go, plugins/parsers/syslog/parser_test.go
=> Update: SD-ID without params reflects in a bool tag with true value

Godeps
=> Last syslog parser version

plugins/inputs/all/all.go, plugins/inputs/nvidia_smi/README.md, plugins/inputs/nvidia_smi/nvidia_smi.go, plugins/inputs/nvidia_smi/nvidia_smi_test.go
This PR implements a simple version of a GPU monitoring plugin. 
This PR closes https://github.com/influxdata/telegraf/issues/2642
=> Add `nvidia_smi` Plugin to help monitor GPU heavy rigs

.circleci/config.yml, appveyor.yml, plugins/inputs/statsd/statsd_test.go, plugins/inputs/zipkin/zipkin.go, plugins/inputs/zipkin/zipkin_test.go, plugins/outputs/influxdb/udp_test.go
=> Test using Go 1.8-1.10; official builds with 1.10

Godeps
=> Update github.com/gorilla/mux version

plugins/inputs/cassandra/cassandra.go
=> Add only valid field types in cassandra input

metric/metric.go, metric/metric_test.go
=> Fix duplicate tags when overriding tag

plugins/inputs/mongodb/mongodb.go
=> Return errors in mongodb SSL/TLS configuration

CHANGELOG.md, README.md, plugins/inputs/cassandra/README.md, plugins/inputs/cassandra/cassandra.go, plugins/inputs/jolokia2/README.md, plugins/inputs/jolokia2/examples/cassandra.conf, plugins/inputs/jolokia2/jolokia_proxy.go
=> Deprecate the cassandra input plugin

plugins/outputs/file/file.go
=> Fix one writer failing others in file output

plugins/inputs/nvidia_smi/nvidia_smi.go
Closed https://github.com/influxdata/telegraf/pull/4069 in favor of this.
=> Fix timeout parsing error [nvidia-smi]

plugins/inputs/mysql/mysql.go
=> Only lowercase mysql slave metrics with metric_version = 2

Godeps
Fix for https://github.com/influxdata/telegraf/issues/4127
=> Update aerospike-client-go version to latest. Fix #4127.

plugins/inputs/jolokia2/jolokia_agent.go
=> Reuse transport on next interval in jolokia agent

plugins/outputs/librato/librato.go
=> Fix librato output support for uint and bool

plugins/inputs/elasticsearch/elasticsearch.go, plugins/inputs/elasticsearch/testdata_test.go
=> Added 3 important elasticsearch cluster health metrics

plugins/inputs/apache/apache.go
Fix possible lock on `wg.Wait()` in case url is incorrect.
=> fix potential waitgroup lock

plugins/inputs/all/all.go, plugins/inputs/aurora/README.md, plugins/inputs/aurora/aurora.go, plugins/inputs/aurora/aurora_test.go, testutil/accumulator.go
=> Add aurora input plugin

plugins/inputs/sensors/README.md, plugins/inputs/sensors/sensors.go, plugins/inputs/sensors/sensors_test.go
=> Add timeout option to sensors input

plugins/inputs/jolokia2/examples/activemq.conf, plugins/inputs/jolokia2/examples/bitbucket.conf, plugins/inputs/jolokia2/examples/hadooop-hdfs.conf, plugins/inputs/jolokia2/examples/jboss.conf, plugins/inputs/jolokia2/examples/tomcat.conf, plugins/inputs/jolokia2/examples/weblogic.conf
Added 6 new examples for Jolokia2, in reference to: #3998 
- ActiveMQ
- Bitbutcket
- Hadoop HDFS
- JBoss
- Tomcat
- Weblogic
=> new examples for jolokia2

plugins/outputs/cloudwatch/cloudwatch.go
=> Handle uint64 on cloudwatch output

plugins/outputs/http/README.md, plugins/outputs/http/http.go
Nested toml config was placed at the bottom to correct the configuration to reflect it correctly. Issues related to this can be found below.
https://github.com/influxdata/telegraf/issues/4224
=> Change config to match toml parsing rule.

plugins/inputs/amqp_consumer/README.md, plugins/inputs/amqp_consumer/amqp_consumer.go, plugins/outputs/amqp/README.md, plugins/outputs/amqp/amqp.go, plugins/outputs/amqp/amqp_test.go, plugins/outputs/amqp/client.go
=> Add additional amqp output/consumer input options

plugins/inputs/ping/ping.go
=> Use same flags for all bsd family ping varients

plugins/inputs/nvidia_smi/README.md, plugins/inputs/nvidia_smi/nvidia_smi.go, plugins/inputs/nvidia_smi/nvidia_smi_test.go
=> Added power draw measurement to nvidia_smi plugin

plugins/inputs/nvidia_smi/README.md
=> Fixed typos in nvidia_smi plugin doc

plugins/inputs/system/SWAP_README.md, plugins/inputs/system/memory.go, plugins/inputs/system/memory_test.go, plugins/inputs/system/swap.go, plugins/inputs/system/swap_test.go
=> Resolves #4290 - no clear documentation on swap input plugin

plugins/inputs/procstat/README.md
=> add procstat_lookup metric to readme

plugins/inputs/http_listener/http_listener.go
=> Add mutex to prevent handler precision from changing during parse

agent/agent.go
=> Fix data race with default tags

CONTRIBUTING.md, Makefile
=> Fixes for Makefile

plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go, plugins/inputs/docker/docker_testdata.go
=> Filter on all container names, use proper name for container

plugins/processors/printer/printer.go
=> Fix output format of printer processor

metric/metric.go, metric/metric_test.go
=> Fix metric can have duplicate field

plugins/inputs/http_listener/http_listener_test.go, plugins/inputs/http_response/http_response_test.go, plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go, plugins/inputs/socket_listener/socket_listener_test.go, plugins/inputs/syslog/rfc5425_test.go, plugins/inputs/syslog/rfc5426_test.go, plugins/inputs/syslog/syslog_test.go, plugins/outputs/influxdb/udp_test.go, plugins/outputs/socket_writer/socket_writer_test.go
resolves issue: https://github.com/influxdata/telegraf/issues/4420
=> Bugfix/4420 - fix mac unit tests

README.md
- [ O ] Signed [CLA](https://influxdata.com/community/cla/).
- [ O ] Associated README.md updated.
- [ O ] Has appropriate unit tests.
=> update netstat link in README.md

etc/telegraf_windows.conf
=> Remove duplicate "Network Interface" Section

Gopkg.lock, README.md, appveyor.yml, scripts/ci-1.10.docker, scripts/ci-1.9.docker
=> Use dep v0.5.0

internal/models/running_output.go, plugins/inputs/kafka_consumer/README.md, plugins/inputs/kafka_consumer/kafka_consumer.go, plugins/outputs/kafka/README.md, plugins/outputs/kafka/kafka.go
=> Drop message batches in kafka output if too large

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go
This PR addresses the issue https://github.com/influxdata/telegraf/issues/4549
=> Ping throws error during ping failure

plugins/inputs/sqlserver/sqlserver.go
=> Issue 4398 - Track forwarded records

plugins/inputs/cgroup/cgroup_linux.go
=> Close the channel if an error occurs in cgroup input

scripts/build.py
=> Use the correct GOARM value in the armel package

cmd/telegraf/telegraf.go, internal/usage.go, internal/usage_windows.go
=> Document all supported arguments

plugins/inputs/jolokia2/README.md, plugins/inputs/jolokia2/examples/zookeeper.conf
Small PR to add an example zookeeper jolokia2 plugin config.
=> Added Zookeeper Jolokia2 Config

Gopkg.lock, Gopkg.toml
=> Bump sarama to version 1.18.0 to support Kafka 2.0

plugins/inputs/tail/tail.go, plugins/inputs/tail/tail_test.go
=> Support tailing files created after startup in tail input

Godeps, README.md, plugins/processors/all/all.go, plugins/processors/aws/README.md, plugins/processors/aws/ec2/README.md, plugins/processors/aws/ec2/ec2.go, plugins/processors/aws/ec2/ec2_test.go, plugins/processors/aws/elb/README.md, plugins/processors/aws/elb/elb.go, plugins/processors/aws/elb/elb_test.go, plugins/processors/aws/rds/README.md, plugins/processors/aws/rds/rds.go, plugins/processors/aws/rds/rds_test.go, plugins/processors/aws/sqs/README.md, plugins/processors/aws/sqs/sqs.go, plugins/processors/aws/sqs/sqs_test.go, plugins/processors/aws/utils/utils.go
=> AWS Metadata Processor Plugins

plugins/outputs/cloudwatch/cloudwatch.go
=> Remove the startup authentication check from the cloudwatch output.

plugins/inputs/postgresql_extensible/postgresql_extensible.go, plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
=> Fix null value crash in postgresql_extensible input

plugins/parsers/nagios/parser.go, plugins/parsers/nagios/parser_test.go
Resolves #4087 
Resolves #4088
=> Enhance performance data for nagios parser

internal/config/config.go
=> type of "csv_skip_rows", "csv_skip_columns" should be integer

plugins/inputs/sqlserver/sqlserver.go
Corrected spelling of Forwarded Records and added correct state status of 6 for offline databses on permise
=> Forwarded Records and Offline

plugins/parsers/registry.go
=> Fix rune conversion in csv parser

plugins/parsers/json/README.md, plugins/parsers/json/parser.go
=> Fix panic if JSONNameKey is not found

cmd/telegraf/telegraf.go, docs/WINDOWS_SERVICE.md, internal/usage_windows.go
=> Define custom name/display name when installing telegraf as a windows service

plugins/outputs/cloudwatch/cloudwatch.go, plugins/outputs/cloudwatch/cloudwatch_test.go
=> Skip tags with empty values

CONTRIBUTING.md
=> Fix contributing guidelines

plugins/inputs/nvidia_smi/README.md
More explicit about configuring  nvidia-smi for Windows machines
=> Windows bin_path

docs/CONFIGURATION.md
=> Document that taginclude/tagexclude can remove ANY tag

plugins/inputs/dns_query/dns_query.go
=> Fix hang in dns_query plugin

plugins/outputs/influxdb_v2/influxdb.go
=> update the comment

plugins/inputs/dns_query/dns_query_test.go
=> Report timeout as error in dns_query plugin

plugins/inputs/vsphere/README.md
Add examples for how to set up some parameters like `max_query_objects`, `collect_concurrency` and `discover_concurrency`.
=> Enhancement of README.md for the vSphere input plugin.

plugins/aggregators/basicstats/basicstats_test.go, plugins/aggregators/valuecounter/valuecounter.go, plugins/inputs/procstat/native_finder_notwindows.go, plugins/outputs/cratedb/cratedb.go, plugins/outputs/graphite/graphite.go, plugins/outputs/influxdb/http.go, plugins/parsers/grok/parser_test.go, plugins/processors/topk/topk.go, plugins/serializers/splunkmetric/splunkmetric.go
Fixes some spelling mistakes caught by [misspell](https://github.com/client9/misspell).
=> Fix spelling mistakes

plugins/outputs/amqp/amqp.go, plugins/outputs/amqp/client.go
=> Prevent connection leak by closing unused connections in amqp output

plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go
=> Print error for login issues in jti_openconfig plugin

plugins/inputs/ipvs/README.md, plugins/inputs/ipvs/ipvs.go
For each ipvs virtual server, we now report metrics for the real
servers that are backing the virtual server.
=> [ipvs] Add metrics for real servers

plugins/parsers/json/parser.go, plugins/parsers/json/parser_test.go
=> Remove the time_key from the field values in JSON parser

plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/win_service_windows.go
=> Minor updates for 'win_service' procstat changes

plugins/outputs/influxdb/README.md
Additional explanation for UDP influxdb endpoint.
=> Clarify UDP influxdb endpoint

plugins/inputs/kubernetes/README.md
=> Update kubernetes input docs

plugins/inputs/mysql/mysql.go
=> Handle non-tls columns for mysql input

plugins/inputs/influxdb_listener/http_listener.go
=> Prevent panic in influxdb_listener

internal/models/buffer.go
=> Remove metrics from the buffer on write

Gopkg.lock, Gopkg.toml
Includes TLS support among other things.
closes #3817
=> Update to pgx 3.2.0

plugins/inputs/kafka_consumer/kafka_consumer.go
=> Prevent panic when marking the offset

internal/models/running_aggregator.go, internal/models/running_aggregator_test.go
=> Aggregate early metrics, rather than ignore

internal/models/running_input.go, internal/models/running_input_test.go
=> Apply global and plugin level metric modifications before filtering

Gopkg.lock
=> Update golang.org/x/sys to latest revision

filter/filter_test.go
=> Add test for include/exclude filter

docs/CONFIGURATION.md
=> Improve config file environment variable documentation

plugins/inputs/sqlserver/sqlserver.go
Add Mirroring state SQLServer
- Log Send Queue KB
- Redo Queue KB
=> Add forwarded records to sqlserver input

plugins/parsers/grok/parser_test.go
Fixes https://github.com/influxdata/telegraf/issues/5211
=> Happy new year: updated unittests

plugins/processors/topk/README.md, plugins/processors/topk/topk.go
=> Add example to topk readme. Fix defaults to skip loop

.circleci/config.yml, Makefile, scripts/ci-1.10.docker, scripts/ci-1.11.docker
=> Use Go 1.11.4 and 1.10.7

plugins/inputs/graylog/README.md
=> Fix a typo

plugins/parsers/graphite/parser_test.go
Just fix one error in graphite parser_test.go
=> Fix err in graphite parser_test

internal/models/running_aggregator.go, internal/models/running_aggregator_test.go
=> Add a copy of the input metric when adding to aggregator

plugins/inputs/all/all.go, plugins/inputs/neptune_apex/README.md, plugins/inputs/neptune_apex/neptune_apex.go, plugins/inputs/neptune_apex/neptune_apex_test.go
- [ ✓] Signed [CLA](https://influxdata.com/community/cla/).
- [ ✓] Associated README.md updated.
- [ ✓] Has appropriate unit tests.
This PR closes #5164 and adds an input plugin for the Neptune Apex aquarium controller. General format was taken from the "httpjson" input plugin.
I've been running this at home for 24 hours and all stats look good.
=> Issue #5164 Input plugin for Neptune Apex aquarium controller.

Gopkg.lock, plugins/outputs/all/all.go, plugins/outputs/cloud_pubsub/README.md, plugins/outputs/cloud_pubsub/pubsub.go, plugins/outputs/cloud_pubsub/pubsub_test.go, plugins/outputs/cloud_pubsub/topic_gcp.go, plugins/outputs/cloud_pubsub/topic_stubbed.go
Related to #2776.
I want to submit this after https://github.com/influxdata/telegraf/pull/5136 goes in.
=> GCP Cloud Pubsub Output Plugin

plugins/outputs/cloud_pubsub/pubsub.go, plugins/outputs/cloud_pubsub/pubsub_test.go, plugins/outputs/cloud_pubsub/topic_stubbed.go
=> Fix intermittent test cases in cloud_pubsub

Gopkg.lock, Gopkg.toml
=> Use gopsutil 2.18.12

plugins/inputs/amqp_consumer/amqp_consumer.go
=> Ack delivery if it is unparseable in amqp_consumer input

README.md, plugins/inputs/all/all.go, plugins/inputs/nginx_upstream_check/README.md, plugins/inputs/nginx_upstream_check/nginx_upstream_check.go, plugins/inputs/nginx_upstream_check/nginx_upstream_check_test.go
Add an input for the nginx_upstrem_check nginx module
Add and input for this nginx module
https://github.com/yaoweibin/nginx_upstream_check_module
=> Add nginx_upstream_check input

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/mongodb_data.go
=> Fix typo: `wtcache_pages_read_info` -> `wtcache_pages_read_into`

plugins/parsers/grok/README.md
=> Add note on performance to grok parser documentation

CHANGELOG.md
=> fixed spelling mistake

plugins/inputs/jenkins/README.md, plugins/inputs/jenkins/client.go, plugins/inputs/jenkins/jenkins.go
=> Always send basic auth in jenkins input

.circleci/config.yml, Makefile, scripts/ci-1.10.docker, scripts/ci-1.11.docker
https://groups.google.com/forum/#!msg/golang-announce/mVeX35iXuSw/Flp8FX7QEAAJ
=> Use Go 1.10.8 and 1.11.5

plugins/inputs/vsphere/README.md
Address issue #5343 by adding a performance section to README.
=> Added performance section to README

docs/AGGREGATORS_AND_PROCESSORS.md
Clarify documentation about using `taginclude` to do grouping within an aggregator.
=> Updated docs for #5203

plugins/outputs/azure_monitor/README.md
=> Remove unimplemented auth options from azure_monitor documentation

plugins/inputs/syslog/syslog.go
=> Return new Syslog instance for each plugin

Gopkg.lock
=> Update to gopsutil v2.19.01

plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
=> Continue checking cert from other sources if error occurs

plugins/inputs/kube_inventory/README.md, plugins/inputs/kube_inventory/kube_state.go
Update readme to align with fix in #5400
=> Note how to use all namespaces in readme

plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
=> Append host if arguments are specified for ping input

README.md, metric/series_grouper.go, plugins/inputs/all/all.go, plugins/inputs/stackdriver/README.md, plugins/inputs/stackdriver/stackdriver.go, plugins/inputs/stackdriver/stackdriver_test.go, testutil/metric.go
=> Add stackdriver input plugin

plugins/inputs/cloud_pubsub/README.md, plugins/inputs/cloud_pubsub/pubsub.go, plugins/inputs/cloud_pubsub/pubsub_test.go, plugins/inputs/cloud_pubsub/subscription_stub.go
=> Retry restarting receiver on PubSub service error

plugins/outputs/stackdriver/stackdriver.go, plugins/outputs/stackdriver/stackdriver_test.go
I completely overlooked this in #5407 ; should have known better than to use range :sweat_smile:
=> fix delete in place of keys

Gopkg.lock, Gopkg.toml
Update dep version dependency reference for Wavefront to use major range instead of specific version.
=> update wavefront-sdk-go version

plugins/inputs/sqlserver/sqlserver.go
=> Disable results by row in azuredb query

plugins/parsers/influx/handler.go, plugins/parsers/influx/machine.go, plugins/parsers/influx/machine.go.rl, plugins/parsers/influx/machine_test.go, plugins/parsers/influx/parser.go, plugins/parsers/influx/parser_test.go, plugins/serializers/influx/escape.go, plugins/serializers/influx/influx_test.go
closes #4743
closes #4426
closes #4942
=> Influx parser fixes

plugins/inputs/filecount/README.md, plugins/inputs/filecount/filecount.go
=> Log permission error rather than add to filecount input

plugins/outputs/prometheus_client/prometheus_client.go
This fixes an intermittent failure in the testcase by ensuring we are listening before returning.
=> Listen before returning from returning from Connect

plugins/outputs/prometheus_client/prometheus_client.go
Attempted fix to resolve #5511
=> Handle errors better in prometheus output

README.md
- [x ] Associated README.md updated.
=> Add a link to x509_cert plugin in the README.

metric/metric.go
=> Dereference pointer fields in metrics

plugins/outputs/prometheus_client/prometheus_client.go
=> Sort metrics by timestamp in prometheus output

Gopkg.lock
=> Update gopsutil to v2.19.02

plugins/outputs/prometheus_client/prometheus_client.go, plugins/outputs/prometheus_client/prometheus_client_tls_test.go
https://circleci.com/gh/influxdata/telegraf/29069
=> Use random available port in prometheus output tests

plugins/inputs/vsphere/finder.go
Fixed an issue causing error messages in the vCenter log. The issue is benign, but creates unsightly junk in the vCenter log.
=> Removed calls to destroy on ViewManager

plugins/inputs/system/system.go
Minimize needed calls to collect system uptime.
Resolves #5589
=> Decrease CPU usage in system input

plugins/inputs/consul/consul.go
=> Don't add empty healthcheck tags to consul input

plugins/outputs/influxdb_v2/influxdb.go
=> Fix plugin name in influxdb_v2 output

CONTRIBUTING.md
=> Fix Makefile Target Name in Contributing Docs

plugins/parsers/logfmt/README.md
=> Remove unused config option from logfmt parser

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
Hopefully make it more straightforward to create issues/feature requests.
=> Update issue templates to include code block and comments

plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch.go
=> Add missing quote

plugins/outputs/http/http.go
=> Set host header if configured on http output

plugins/inputs/disk/README.md, plugins/inputs/disk/disk.go
=> Add iso6990 to telegraf disk ignore_fs 

Gopkg.lock, Gopkg.toml
=> Require github.com/jackc/pgx v3.4.0

plugins/inputs/fibaro/fibaro.go
=> Set default timeout of 5s in fibaro input

plugins/inputs/solr/README.md, plugins/inputs/solr/solr.go
=> fr5829 solr auth

plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
=> Improve Docker image identifier parsing

plugins/inputs/pgbouncer/README.md, plugins/inputs/postgresql/README.md
Update docs about https://github.com/influxdata/telegraf/issues/4872 questions
=> Update postgres/pgbouncer docs about #4872 questions

plugins/outputs/amqp/amqp.go
=> Fix publishing direct exchange routing key

plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
=> Log actual url on wrong status code

plugins/inputs/nvidia_smi/README.md, plugins/inputs/nvidia_smi/nvidia_smi.go, plugins/inputs/nvidia_smi/nvidia_smi_test.go
As an avid overclocker I feel these metrics are important to collect.
=> Extend metrics collected from Nvidia GPUs

plugins/inputs/nginx_upstream_check/nginx_upstream_check.go
=> Fix typo in nginx_upstream_check

internal/http.go, internal/internal.go, plugins/outputs/all/all.go, plugins/outputs/health/README.md, plugins/outputs/health/compares.go, plugins/outputs/health/compares_test.go, plugins/outputs/health/contains.go, plugins/outputs/health/contains_test.go, plugins/outputs/health/health.go, plugins/outputs/health/health_test.go
=> Add health output plugin

plugins/inputs/all/all.go, plugins/inputs/openweathermap/README.md, plugins/inputs/openweathermap/openweathermap.go, plugins/inputs/openweathermap/openweathermap_test.go, testutil/accumulator.go
Hi, it's a first implementation of the Open Weather Map plugin. This plugin pulls the current weather information and forecasts for a number of cities using openweathermap.org API.
This first implementation is missing snow information, needs more testing on the snow data reported by openweathermap.org before pushing one extra commit.
Let me know your comments.
=> Open weather map input plugin

internal/http_go1.11.go, internal/http_go1.12.go, plugins/outputs/influxdb/http.go, plugins/outputs/influxdb/influxdb.go, plugins/outputs/influxdb/influxdb_test.go, plugins/outputs/influxdb/udp.go, plugins/outputs/influxdb_v2/http.go, plugins/outputs/influxdb_v2/influxdb.go
=> Close idle connections in influxdb outputs when reloading

plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go, plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go
https://circleci.com/gh/influxdata/telegraf/34148
=> Fix race conditions in gnmi telemetry tests

plugins/inputs/ecs/README.md, plugins/inputs/ecs/ecs.go
=> Make case insensitive container status comparison

internal/models/buffer.go, internal/models/running_output.go
=> Log a warning on write if the metric buffer has overflowed

internal/rotate/file_writer.go
=> Fix double close error with log rotation

plugins/inputs/dns_query/dns_query.go
=> Reduce linter suggestions

plugins/inputs/zookeeper/zookeeper.go
=> Compile regexp once

plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go
Fix for:
```
--- FAIL: TestGNMIError (0.00s)
require.go:44: 
Error Trace:	cisco_telemetry_gnmi_test.go:109
Error:      	"[failed to send subscription request: EOF]" does not contain "aborted GNMI subscription: rpc error: code = Unknown desc = testerror"
Test:       	TestGNMIError
```
=> Fix race condition in cisco telemetry tests

plugins/inputs/disk/disk.go
=> Fix setting mount_points option in disk input

plugins/inputs/http_response/README.md, plugins/inputs/http_response/http_response.go
=> Support array of addressses in http_response input

.circleci/config.yml, README.md
=> Drop support for Go 1.9

plugins/inputs/filecount/filecount.go, plugins/inputs/filecount/filecount_test.go, plugins/inputs/filecount/filesystem_helpers.go, plugins/inputs/filecount/filesystem_helpers_test.go
=> fix filecount plugin size tests #6011

plugins/inputs/system/README.md, plugins/inputs/system/system.go
- [x ] Associated README.md updated.
Replacement for: https://github.com/influxdata/telegraf/pull/5734
=> skip when utmp is missing

plugins/inputs/smart/smart.go, plugins/inputs/smart/smart_test.go
=> Add device, serial_no, and wwn tags to synthetic attributes

plugins/inputs/statsd/datadog.go, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go, testutil/metric.go
=> Fix parsing of remote tcp address in statsd input

plugins/inputs/elasticsearch/elasticsearch.go, plugins/inputs/elasticsearch/elasticsearch_test.go, plugins/inputs/elasticsearch/testdata_test.go
Small patch to add node_rules.
Closes #2158
=> Elasticsearch: add node_roles tag

plugins/inputs/statsd/datadog.go, plugins/inputs/statsd/statsd_test.go
=> Fix panic with empty datadog tag string

plugins/inputs/vsphere/client.go
This fixes issue #6054. When the connection was lost to vCenter, a new authentication attempt was made using the current client. However, the client internally stored some references to vCenter objects that were deleted when vCenter was rebooted. Because is this, the reconnection to vCenter didn't succeed and the Telegraf process had to be restarted.
Solved this by deleting the vCenter client and recreating it, which prevents references to stale vCenter objects from being reused.
closes #6054
=> Fixed reconnection issue when vCenter is rebooted (issue 6054)

Gopkg.lock
=> Update go-mssqldb version to latest release

plugins/inputs/docker/README.md, plugins/inputs/docker/docker.go
=> example in docker config and readme.md

plugins/parsers/json/parser.go, plugins/parsers/json/parser_test.go
=> Treat empty array as successful parse

plugins/inputs/all/all.go, plugins/inputs/fireboard/README.md, plugins/inputs/fireboard/fireboard.go, plugins/inputs/fireboard/fireboard_test.go
New plugin to import data from fireboard servers to gather real time temps from their WiFi connected thermometers.
Resolves #6051
=> Fireboard Input Plugin

plugins/inputs/github/github.go
Resolves #6151 
Use builtin getters to avoid a panic.
=> Avoid panic in github input

scripts/build.py
https://github.com/influxdata/telegraf/issues/3096#issuecomment-513554121
=> Add Linux mips build

agent/agent.go
=> Call Init before Start in test mode

plugins/inputs/fluentd/README.md
=> Update links in fluentd input readme

plugins/inputs/x509_cert/x509_cert.go
=> Add intermediates when verifying cert in x509 input

plugins/inputs/smart/README.md, plugins/inputs/smart/smart.go
closes: https://github.com/influxdata/telegraf/issues/4632
=> updating smart input docs for attributes clarity

plugins/inputs/cassandra/README.md
yes i know it's deprecated, but i hate misformatted markdown files :)
=> cleaning up cassandra input readme

plugins/inputs/disque/README.md
=> Added README to disque input

plugins/inputs/socket_listener/socket_listener.go
=> Fix possible panic in socket_listener input plugin (resolves #6209)

plugins/inputs/docker_log/docker_log.go
=> Ignore context cancelled error in docker_log

plugins/inputs/powerdns_recursor/README.md, plugins/inputs/powerdns_recursor/powerdns_recursor.go
=> Document permission setup for powerdns_recursor

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/mongodb_server.go
=> Mongodb refactor collection stat errors

plugins/inputs/mailchimp/README.md
=> Create readme for mailchimp input

plugins/inputs/rethinkdb/README.md
=> adding readme to rethinkdb input

plugins/inputs/logparser/README.md
=> Updated logparser readme

README.md, plugins/inputs/all/all.go, plugins/inputs/openntpd/README.md, plugins/inputs/openntpd/openntpd.go, plugins/inputs/openntpd/openntpd_test.go
=> Input plugin for openntpd

internal/internal.go, internal/internal_test.go
=> Stop timer when command exits in WaitTimeout

.gitignore, internal/choice/choice.go, internal/internal.go, plugins/inputs/logstash/README.md, plugins/inputs/logstash/logstash.go, plugins/inputs/logstash/logstash_test.go
Changes based on my review of #4910
=> Logstash followup

internal/exec.go, internal/exec_unix.go, internal/exec_windows.go, internal/internal.go
=> Send TERM to exec processes before sending KILL signal

.circleci/config.yml, Makefile, appveyor.yml, scripts/ci-1.11.docker, scripts/ci-1.12.docker
=> Update to Go 1.12.9 and 1.11.13

plugins/inputs/vsphere/README.md
closes #6305
Added a note about supported versions of vSphere to README.md.
=> Added supported versions to README

Gopkg.lock, Gopkg.toml, docs/LICENSE_OF_DEPENDENCIES.md, plugins/inputs/all/all.go, plugins/inputs/azure_storage_queue/README.md, plugins/inputs/azure_storage_queue/azure_storage_queue.go
=> Add azure_storage_queue input plugin

README.md
Easy fix, so I skipped opening an issue.
=> Fix broken output/exec plugin link in README

.github/ISSUE_TEMPLATE/Bug_report.md
=> Fixing spelling in bug template

plugins/inputs/apcupsd/README.md
=> Fix apcupsd documentation to reflect actual plugin

plugins/parsers/json/parser.go
=> Allow booleans as json string fields again

Gopkg.lock, Gopkg.toml
=> Update apcupsd library

Gopkg.lock, Gopkg.toml
=> Use gopsutil fork with backported disk lvm fix

plugins/inputs/sqlserver/README.md, plugins/inputs/sqlserver/sqlserver.go
This PR was requested by @danielnelson here:  https://github.com/influxdata/telegraf/issues/6260#issuecomment-521459628
=> updated doc for tls connections

plugins/inputs/cpu/README.md
=> Update cpu docs

CHANGELOG.md, plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go
=> Update ping documentation

.circleci/config.yml, Makefile, scripts/ci-1.12.docker
=> Use Go 1.12.10 for builds

plugins/inputs/tail/tail.go
=> feat(tail): supress error to debug when file doesn't exist

.github/ISSUE_TEMPLATE/Bug_report.md
=> Update GitHub bug issue template

docs/CONFIGURATION.md, internal/config/config.go
=> Default logtarget to file for backwards compatibility

internal/models/running_aggregator.go, internal/models/running_input.go, internal/models/running_output.go, internal/models/running_processor.go, selfstat/selfstat.go, selfstat/selfstat_test.go, selfstat/stat.go, selfstat/timingStat.go
=> Exclude alias tag if unset from plugin internal stats

plugins/inputs/kapacitor/README.md
Updates the Kapacitor input README to describe measurements and fields collected from Kapacitor. This was requested by an InfluxDB Enterprise customer and resolves a documentation assistance request (DAR).
=> Added descriptions for kapacitor input metrics

agent/accumulator.go
=> Change plugin error message to debug message

Gopkg.lock, Gopkg.toml, plugins/inputs/openldap/openldap.go, plugins/inputs/openldap/openldap_test.go
Include GitHub https://github.com/go-ldap/ldap/pull/126: Require explicit intention for empty password.
=> Use gopkg.in/ldap.v3 3.1.0

Gopkg.lock, Gopkg.toml
Bring in fix for https://github.com/miekg/dns/issues/742
=> Use github.com/miekg/dns 1.0.10

plugins/inputs/sqlserver/README.md, plugins/inputs/sqlserver/sqlserver.go
=> Add missing ServerProperties query to sqlserver input docs

Gopkg.lock
=> Use latest golang.org/x/crypto

plugins/inputs/mongodb/mongostat.go
MongoDB documentation: https://docs.mongodb.com/manual/reference/command/serverStatus/#connections
=> Fix mongodb field name: total_created -> totalCreated

plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
=> Fix uptime_ns calculation when container has been restarted

plugins/inputs/nvidia_smi/nvidia_smi.go, plugins/inputs/nvidia_smi/nvidia_smi_test.go
=> Update nvidia-smi input to use xml

plugins/inputs/jenkins/README.md, plugins/inputs/jenkins/jenkins.go, plugins/inputs/jenkins/jenkins_test.go
=> Add source and port tags to jenkins plugin

plugins/inputs/ping/ping.go
=> Fix interface option with method = native in ping input

plugins/processors/all/all.go
Clone processor merged in commit 89c4c1d02
=> Clone processor was added but not made available

etc/telegraf.conf, plugins/inputs/all/all.go, plugins/inputs/synproxy/README.md, plugins/inputs/synproxy/synproxy.go, plugins/inputs/synproxy/synproxy_notlinux.go, plugins/inputs/synproxy/synproxy_test.go
[influxdata_ccla_190404.pdf](https://github.com/influxdata/telegraf/files/3047208/influxdata_ccla_190404.pdf)
Signed [CLA](https://influxdata.com/community/cla/).
plugins/inputs/synproxy/README.md
plugins/inputs/synproxy/synproxy_test.go
=> Synproxy input plugin

plugins/parsers/json/parser.go, plugins/parsers/json/parser_test.go
=> Remove trailing underscore trimming from json flattener

Gopkg.lock
=> Update to gopsutil v2.19.11

plugins/serializers/prometheus/collection.go, plugins/serializers/prometheus/convert.go, plugins/serializers/prometheus/prometheus_test.go
=> Allow colons in the prometheus metric name

plugins/serializers/prometheus/collection.go, plugins/serializers/prometheus/collection_test.go
=> Fix prometheus histogram and summary merging

plugins/inputs/mongodb/mongodb_data.go, plugins/inputs/mongodb/mongodb_data_test.go
=> #6730 - report page_faults for wired tiger system

plugins/inputs/uwsgi/uwsgi.go
=> Fix unix socket dial arguments in uwsgi input

plugins/inputs/snmp_trap/snmp_trap.go, plugins/inputs/snmp_trap/snmp_trap_test.go
=> Interpret SNMP v1 traps as described in RFC 2576 3.1

plugins/inputs/sqlserver/sqlserver.go
=> Azure SQL Database Query Fix

plugins/inputs/ipmi_sensor/README.md, plugins/inputs/ipmi_sensor/ipmi.go
=> Add use_sudo option to ipmi_sensor input

plugins/inputs/logparser/logparser_test.go
Fix intermittent test failure:
```
2019/12/20 16:36:55 D! [] Tail added for file: /go/src/github.com/influxdata/telegraf/plugins/inputs/logparser/testdata/test_a.log
2019/12/20 16:36:55 D! [] Tail added for file: /go/src/github.com/influxdata/telegraf/plugins/inputs/logparser/testdata/test_b.log
2019/12/20 16:36:55 D! [] Tail added for file: /go/src/github.com/influxdata/telegraf/plugins/inputs/logparser/testdata/test_c.log
2019/12/20 16:36:55 D! [] Tail dropped for file: /go/src/github.com/influxdata/telegraf/plugins/inputs/logparser/testdata/test_a.log
2019/12/20 16:36:55 D! [] Tail dropped for file: /go/src/github.com/influxdata/telegraf/plugins/inputs/logparser/testdata/test_b.log
2019/12/20 16:36:55 D! [] Tail dropped for file: …
```
=> Fix race condition in logparser tests

README.md
=> fix doc error

plugins/processors/pivot/README.md
=> Fix example error in doc
