influxdata/telegraf

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- plugins/common/kafka/config.go
- plugins/common/kafka/logger.go
- plugins/common/kafka/sasl.go
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go
- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/kafka_test.go
Updates the kafka dep to point at the IBM version of the repo and updates away from deprecated strategies due a data race. This is not changed for kafka consumer due to a second dependency that does not know about the IBM version.
> chore(deps): Point kafka dependency to IBM organization

- plugins/inputs/http/http.go
We deprecated bearer token, and switched to using token file everywhere, except the actual reading of it ;)
fixes: #14347
> fix(inputs.http): Use correct token variable

- plugins/parsers/json_v2/README.md
- plugins/parsers/json_v2/parser.go
This PR fixes minor errors in the documentation of input filter `json_v2`. This is a follow-up on a comment on my [PR](https://github.com/influxdata/docs-v2/pull/5240#pullrequestreview-1750865654) to the InfluxDB 2.0 documentation repo.
> fix(parsers.json v2): Correct wrong name of config option

- plugins/parsers/json_v2/README.md
This PR adds links to the `testdata` folder in the GitHub repo in the `README`file for the json_v2 plugin.
**Motivation:** this `README`file is re-used in the {go package description](https://pkg.go.dev/github.com/influxdata/telegraf/plugins/parsers/json_v2). In this context is is not clear what `testdata` refers to. This PR mitigates that situation by adding a link that allows the reader to directly jump to the `testdata` examples folder.
> docs(parsers.json_v2): Add links to testdata folder

- migrations/all/inputs_procstat.go
- migrations/inputs_procstat/migration.go
- migrations/inputs_procstat/migration_test.go
- migrations/inputs_procstat/testcases/deprecated_supervisor_unit merge/expected.conf
- migrations/inputs_procstat/testcases/deprecated_supervisor_unit merge/telegraf.conf
- migrations/inputs_procstat/testcases/deprecated_supervisor_unit/expected.conf
- migrations/inputs_procstat/testcases/deprecated_supervisor_unit/telegraf.conf
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
resolves #14327 
This PR renames the `supervisor_unit` setting to the plural version as the option takes a list of units.
> chore(inputs.procstat): Use plural for supervisor_units option

- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/sample.conf
Provide the users with additional caveat that using a persistent session will not update topics, even after a restart of telegraf.
resolves #9703
> docs(inputs.mqtt_consumer): Clarify persistent session and topic behavior

- plugins/parsers/json_v2/parser.go
resolves #13805
Running json_v2 parser leaves `p.subPathResults` dirty, affecting subsequent runs. This is a problem for input plugins reusing json_v2 parser instance instead of creating a new one.
Following the pattern of `csv` parser, added a `Reset()` method, which clears `subPathResults`. It is called in `Init()` and when starting `Parse()`.
> fix(parsers.json_v2): Reset parser before parsing (#13805)

- plugins/inputs/nats_consumer/README.md
- plugins/inputs/nats_consumer/nats_consumer.go
- plugins/inputs/nats_consumer/sample.conf
This PR makes it possible for the nats_consumer input plugin to authenticate with NATS via an [nkey](https://docs.nats.io/using-nats/developer/connecting/nkey) seed file.
resolves #14374
> feat(inputs.nats_consumer): Add nkey-seed-file authentication

- tools/package_lxd_test/main.go
Updates to the latest Fedora images as well as updates to the Amazon Linux 2 image as the original image no longer exists.
resolves #
> test: Update lxc images

- plugins/outputs/dynatrace/README.md
At Dynatrace, the documentation URLs now have an overhauled format, including new shortlinks. This PR swaps out the "old" links with the new style of shortlink in the documentation.
Skipping this for a small docs update. Please let me know if you want me to open an Issue for this anyway.
> docs(outputs.dynatrace) Update links to documentation

- metric.go
- metric/tracking.go
- plugins/common/starlark/builtins.go
- plugins/inputs/statsd/statsd_test.go
- plugins/inputs/tail/tail_test.go
- plugins/processors/starlark/README.md
- plugins/processors/starlark/starlark.go
- plugins/processors/starlark/starlark_test.go
- plugins/processors/starlark/testdata/value_filter.star
- testutil/accumulator.go
- testutil/metric.go
Tracking metrics are currently aggressively accepted and dropped by the starlark processor. In turn, those metrics might be double tagged (accept or drop) especially in cases where we use the `deepcopy` starlark command. Moreover, the current `testutil.Accumulator` implementation just strips the tracking information and thus those errors have gone unnoticed in the tests.
This PR fixes the `testutil.Accumulator` implementation to mimic the behavior of the actual accumulator and uncover refcount or unacknowledged-metric issues. The PR also modifies the starlark processor to _not_ accept metrics but leaves this to the output plugins. To be on the safe-side, `deepcopy`s are modified to strip the tracking information by default as metrics might be deep-copied and then dropped, which will go …
> fix(processors.starlark): Avoid negative refcounts for tracking metrics

- config/migration.go
- migrations/all/general_metricfilter.go
- migrations/general_metricfilter/migration.go
- migrations/general_metricfilter/migration_test.go
- migrations/general_metricfilter/testcases/deprecated_drop/expected.conf
- migrations/general_metricfilter/testcases/deprecated_drop/telegraf.conf
- migrations/general_metricfilter/testcases/deprecated_fielddrop/expected.conf
- migrations/general_metricfilter/testcases/deprecated_fielddrop/telegraf.conf
- migrations/general_metricfilter/testcases/deprecated_fieldpass/expected.conf
- migrations/general_metricfilter/testcases/deprecated_fieldpass/telegraf.conf
- migrations/general_metricfilter/testcases/deprecated_pass/expected.conf
- migrations/general_metricfilter/testcases/deprecated_pass/telegraf.conf
- migrations/general_metricfilter/testcases/merge_all_overlap/expected.conf
- migrations/general_metricfilter/testcases/merge_all_overlap/telegraf.conf
- migrations/general_metricfilter/testcases/merge_fieldexclude/expected.conf
- migrations/general_metricfilter/testcases/merge_fieldexclude/telegraf.conf
- migrations/general_metricfilter/testcases/merge_fieldexclude_overlap/expected.conf
- migrations/general_metricfilter/testcases/merge_fieldexclude_overlap/telegraf.conf
- migrations/general_metricfilter/testcases/merge_fieldinclude/expected.conf
- migrations/general_metricfilter/testcases/merge_fieldinclude/telegraf.conf
- migrations/general_metricfilter/testcases/merge_fieldinclude_overlap/expected.conf
- migrations/general_metricfilter/testcases/merge_fieldinclude_overlap/telegraf.conf
- migrations/inputs_disk/migration.go
- migrations/inputs_procstat/migration.go
- migrations/outputs_influxdb/migration.go
- migrations/registry.go
- migrations/utils.go
PR #14012 deprecated `fieldpass` and `fielddrop` and replaced those options with the better-named `fieldinclude` and `fieldexclude` respectively. Additionally, the deprecated `pass` and `drop` options exist.
This PR adds a migration to consolidate all those settings into the new `fieldpass` and `fielddrop`.
> feat(migrations): Add migration for fieldpass/fielddrop

- docs/LICENSE_OF_DEPENDENCIES.md
- tools/license_checker/package.go
This PR fixes the license check error on nightly by correctly spelling the license of `github.com/jmhodges/clock`. The PR also improves the error message of the checker to be able to find issues easier.
> fix(license): Correct spelling of jmhodges/clock license

- CHANGELOG.md
Fixed the link in changelog entry regarding 13791 to point to correct PR.
- [X ] No AI generated code was used in this PR
resolves #14426
> docs(Changelog): Fix reference to python-syntax removal

- plugins/outputs/bigquery/bigquery.go
- plugins/outputs/bigquery/bigquery_test.go
The `project` config isn't a required field anymore since #14086, but telegraf did not use the auto-detected project ID, this PR fixes that.
The client now also identifies telegraf as the user agent.
> fix(outputs.bigquery): Correct use of auto-detected project ID

- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
PR #13417 renamed the `systemd_unit` option to `systemd_units`, while this was  unintended. This PR reverts the renaming to `systemd_unit`.
resolves #14438
> fix(inputs.procstat): Revert unintended renaming of 'systemd_unit' option

- plugins/inputs/ldap/README.md
- plugins/inputs/ldap/sample.conf
Fixes bug with ldap configuration
resolves #14445
> docs(inputs.ldap): Correct plugin name in sample config

- plugins/inputs/memcached/README.md
There's a typo in the documentation that I've reading for days
> docs(inputs.memcached): Correct typo in README.md

- plugins/inputs/clickhouse/README.md
- plugins/inputs/clickhouse/clickhouse.go
- plugins/inputs/clickhouse/clickhouse_test.go
- plugins/inputs/clickhouse/sample.conf
fixes: #14436
Removes the zookeeper queries when connecting to a URL with clickhouse.cloud in the connection string. I used a string to more easily test this, however, it might be wise to constrain this to the hostname. Obviously if a user is using an IP address this check won't catch that.
resolves #14436
> fix(inputs.clickhouse): Omit zookeeper metrics on clickhouse cloud

- plugins/processors/filter/filter.go
processors.filter was named Filter, I guess incorrectly. The sample file didn't work.
https://github.com/influxdata/telegraf/issues/14459
resolves #14459
> fix(processors.filter): processors.Filter -> processors.filter

- plugins/inputs/dpdk/dpdk_connector_test.go
- plugins/inputs/dpdk/dpdk_test.go
These changes will clean up created directories during the execution of unit tests and resolve issues with CI passing.
resolves https://github.com/influxdata/telegraf/issues/14456
> test(inputs.dpdk): Cleanup directories after unit tests

- .golangci.yml
- logger/logger.go
- plugins/common/cookie/cookie.go
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/http/http.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/httpjson/httpjson.go
- plugins/inputs/intel_dlb/intel_dlb.go
- plugins/inputs/intel_dlb/intel_dlb_test.go
- plugins/inputs/logstash/logstash.go
- plugins/inputs/mysql/mysql.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/sflow/binaryio/minreader_test.go
- plugins/inputs/x509_cert/x509_cert_test.go
- plugins/outputs/amqp/amqp.go
- plugins/outputs/http/http.go
- plugins/outputs/loki/loki.go
- plugins/parsers/logfmt/parser.go
- plugins/secretstores/http/http.go
- plugins/secretstores/oauth2/oauth2.go
- tools/readme_config_includer/generator.go
resolves https://github.com/influxdata/telegraf/issues/14403 (equalFold)
resolves https://github.com/influxdata/telegraf/issues/14408 (preferStringWriter)
resolves https://github.com/influxdata/telegraf/issues/14413 (stringXbytes)
> chore(linters): Enable `equalFold`, `preferStringWriter` and `stringXbytes` checkers for gocritic.

- plugins/outputs/bigquery/bigquery.go
When one of the fields contain a NaN, +Inf or -Inf, the following message is emitted and the whole metric gets discarded:
> W! [outputs.bigquery] could not prepare metric as compact value: serializing fields: json: unsupported value: NaN
The JSON serialiser is ignoring those fields, so we do that here as wel.
> fix(outputs.bigquery): Ignore individual fields containing NaN or infinity

- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb_v2/http.go
The outputs.influxdb and outputs.influxdb_v2 plugins currently do not support setting the Host header in the `http_headers` config parameter. If set, it is silently dropped by Go's HTTP client.
The Go HTTP client requires the Host header to be set on the http.Request struct instead. This is already done in other plugins, e.g. inputs.http, outputs.http and secretstores.http.
https://github.com/influxdata/telegraf/blob/448260a90a47f72d4d395f1c070c5cb7143778bb/plugins/inputs/http/http.go#L143-L149
This PR updates the outputs.influxdb and outputs.influxdb_v2 plugins to bring it inline with the other plugins, i.e. allow setting the Host header using the `http_headers` config parameter.
resolves #14482
> fix(outputs.influxdb*): Support setting Host header

- .golangci.yml
resolves https://github.com/influxdata/telegraf/issues/14405 (indexAlloc)
resolves https://github.com/influxdata/telegraf/issues/14409 (preferWriteByte)
resolves https://github.com/influxdata/telegraf/issues/14410 (rangeExprCopy)
resolves https://github.com/influxdata/telegraf/issues/14412 (sliceClear)
> chore(linters): Enable `indexAlloc`, `preferWriteByte`, `rangeExprCopy` and `sliceClear` checkers for gocritic

- plugins/inputs/vsphere/endpoint.go
the serverFaultCode "A specified parameter was not correct: querySpec.startTime, querySpec.endTime" results from requests for metrics from the future.
Those requests get planned (check: hiwater mark, hwMark) for a plugin-run (-> plugin "interval") in the future in relation to the estimated time the vcenter will have collected the next metrics.
This estimated time/interval gets mangled up on a connection error (e.g. connection reset), because the est. interval gets reset to 1.
Solution: If we realize (ourselves) that the metric we are about to request is from the future, then... don't request it. Skip it.
resolves #12500
> fix(inputs.vsphere): Resolve occasional serverFault

- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
Correctly set the tags on procstat_lookup, we stopped adding the collected tags in the refactor.
fixes: #14487
> fix(inputs.procstat): Correctly set tags on procstat_lookup

- go.mod
- go.sum
Update github.com/dvsekhvalnov/jose2go dependency for GHSA-mhpq-9638-x6pw
resolves #
> chore(deps): Bump github.com/dvsekhvalnov/jose2go from v1.5.0 to v1.5.1-0.20231206184617-48ba0b76bc88

- plugins/inputs/opcua_listener/README.md
In opcua-listener nodes' settings `NodeSettings`, `FieldName` in Go is mapped to `name` in toml configuration.  However it's `field_name` in the README.
`NodeSettings`'s definition is as below:
```go
type NodeSettings struct {
FieldName        string               `toml:"name"`
Namespace        string               `toml:"namespace"`
IdentifierType   string               `toml:"identifier_type"`
Identifier       string               `toml:"identifier"`
DataType         string               `toml:"data_type" deprecated:"1.17.0;option is ignored"`
Description      string               `toml:"description" deprecated:"1.17.0;option is ignored"`
TagsSlice        [][]string           `toml:"tags" deprecated:"1.25.0;use 'default_tags' instead"`
DefaultTags      map[string]string …
```
> docs(inputs.opcua_listener): Fix nodes example

- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/phpfpm/phpfpm_test.go
Use logger without causing panic.
Resolves #14485
> fix(inputs.phpfpm): Use logger without causing panic

- plugins/processors/reverse_dns/reverse_dns_test.go
The reverse DNS processor integration test is failing constantly. It seems the usage of Google's 8.8.8.8 server is returning with a server misbehaving error. This switches the servers and updates the test to not compare the `source_name` as well. The `source_name` already has a comment about not being localhost on windows, and I now see that on my local system, so simplify the check to ensure it exists.
> test(processors.reverse_dns): Switch DNS server to avoid misbehaving test

- plugins/outputs/prometheus_client/prometheus_client.go
https://github.com/influxdata/telegraf/pull/14108 introduced the ability to listen on vsock. In that PR, telegraf parses the URL and determines which function to call based on the scheme of the URL. This function was missing what to do when there is no scheme, breaking backwards compatibility. Additionally, if using a URL like `mgt:3839`, scheme will report as `mgt`. To maintain backwards compatibility we should always try TCP.
resolves #14468
> fix(outputs.prometheus_client): Always default to TCP

- go.mod
- go.sum
Updates collectd.org dependency. Also will resolve issues for users using a goproxy as the previous collectd.org version had a checksum mismatch: https://github.com/collectd/go-collectd/issues/94
resolves #10408
> chore(deps): bump collectd.org from v0.5.0 to v0.6.0

- plugins/common/kafka/sasl.go
The username password settings were destroyed before the gssapi config could set them.
fixes: #14514
> fix(common.kafka): Correctly set gssapi username/password

- plugins/common/starlark/metric.go
- plugins/processors/starlark/starlark.go
- plugins/processors/starlark/starlark_test.go
To handle tracking-metrics correctly in the starlark processor, we need to identify tracking metrics and if they are "swallowed" by the processor.
Currently this process is based on comparing the returned metric hash-ID with the one if the input metric. However, this is fragile because the the hash-ID changes as soon as the metric is modified (e.g. renamed, tags are added/removed or tag-values are modified). As this is a very common use-case of the starlark processor, the present PR used the tracking-ID to identify returned tracking metrics. The PR furthermore adds  some more unit-tests for stateful processing scripts.
resolves #14484
> fix(processors.starlark): Use tracking ID to identify tracking metrics

- plugins/inputs/directory_monitor/README.md
- plugins/inputs/directory_monitor/sample.conf
Corrected the documentation of the files_to_monitor variable: using the documentation data an error is returned, corrected by adding an escape
resolves #14531
> fix(docs): regex files_to_monitor variable

- README.md
Go 1.21 has raised OS requirements once again, and the previous README was no longer accurate.
Resolves #14535
> docs(README): Update minimum system requirements

- plugins/outputs/opensearch/README.md
- plugins/outputs/opensearch/sample.conf
TOML format errors if quotes are not escaped.
Fixed syntax errors
-
resolves #
> docs(outputs.opensearch): Correct sample config format

- plugins/inputs/win_perf_counters/win_perf_counters.go
This adds the use of check error to an additional error call. This way users who want to opt of additional errors can in fact do so.
resolves #14486
> fix(inputs.win_perf_counters): Check errors post-collection for skip

- go.mod
- go.sum
- plugins/common/starlark/starlark.go
> chore(deps): Bump go.starlark.net from go.starlark.net v0.0.0-20220328144851-d1966c6b9fcd to v0.0.0-20231121155337-90ade8b19d09

- go.mod
- go.sum
This PR bumps [github.com/intel/powertelemetry](https://github.com/intel/powertelemetry) from 1.0.0 to 1.0.1, used as third-party dependency by Intel Powerstat input plugin.
- Proportionally decrease offset deltas to avoid overflow and values above 100% in C-state metrics.
- Handle error in `activeEventsAsGroup` to avoid panic.
- Upgrade `gopsutil` to `v3.23.11`.
> chore(deps): Bump github.com/intel/powertelemetry from 1.0.0 to 1.0.1

- docs/developers/SAMPLE_CONFIG.md
- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/opcua_listener.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/sample.conf
- plugins/inputs/opcua_listener/subscribe_client.go
We have several sites with multiple OPC UA servers that may or may not be on at a given time. We would like the ability to for Telegraf to still collect information from other successfully initiated inputs even if it can't talk to the OPC UA server. Now, we have three options when Telegraf fails to start subscriptions:
- error: Exit out of Telegraf (current behavior, new default)
- ignore: Ignore this plugin failure, and continue running all others
- retry: Continue running other plugins, and try to re-establish the connection every collection interval
resolves #14533
> feat(inputs.opcua_listener): Add retry options for connection failures

- plugins/inputs/win_perf_counters/win_perf_counters.go
Ignore the `PdhCstatusNoInstance` error so we do not stop collecting data for other counters. This PR builds on top of the change from #14526.
resolves #14557
> fix(inputs.win_perf_counters): Ignore PdhCstatusNoInstance as well

- plugins/inputs/kafka_consumer/kafka_consumer.go
Mark kafka messages if they failed parsing so that consumer group's partition offsets are committed properly for messages that do not parse properly.
resolves #14579
> fix(inputs.kafka_consumer): Mark messages that failed parsing

- plugins/outputs/mqtt/mqtt_test.go
- plugins/outputs/mqtt/topic_name_generator.go
When using the output plugin [MQTT Producer Output Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/mqtt) and setting the topic with leading forward slash (e.g. `/sys/productKey/deviceId/thing/event/property/post`), the plugin sends messages to the topic with the leading forward slash trimmed (e.g. `sys/productKey/deviceId/thing/event/property/post`)
Though it's not recommended to use leading forward slash in MQTT topic in many places, some of the cloud IoT platform uses the topics with it, unfortunately (e.g. Aliyun IoT platform 😕 ). 
resolves #14583
> fix(outputs.mqtt): Preserve leading slash in topic

- plugins/inputs/redis/README.md
- plugins/inputs/redis/sample.conf
Extend Readme for using TLS on Redis because it was not clear how to use without cerfiticate.
> docs(inputs.redis): Add more examples for TLS

- plugins/outputs/loki/loki.go
We use the response body in the error message, but were closing the response body before we had the chance to read it.
resolves #
> fix(outputs.loki): Closed body before reading it

- plugins/parsers/prometheus/parser.go
In the current state we are unconditionally removing leading newlines from the input data and adding a trailing newline. However, this procedure is harmful for protocol-buffer inputs as they usually do start with a `VARINT` (aka `0a ...` aka newline) and binary data should not be tampered with anyway.
Therefore, this PR _only_ applies the newline magic to the text-based prometheus format.
> fix(parsers.prometheus): Do not touch input data for protocol-buffers

- plugins/outputs/nats/README.md
- plugins/outputs/nats/nats.go
- plugins/outputs/nats/nats_test.go
- plugins/outputs/nats/sample.conf
- plugins/outputs/nats/testcases/js-config.conf
- plugins/outputs/nats/testcases/js-default.conf
- plugins/outputs/nats/testcases/js-no-stream.conf
- plugins/outputs/nats/testcases/js-subjects.conf
- plugins/outputs/nats/testcases/no-js.conf
> feat(outputs.nats): Introduce NATS Jetstream option

- internal/snmp/translate.go
This addresses #14598 and #10444 
The previous error message was unclear, especially to newcommers to SNMP, SMI and MIBs. With this slight rephrasing, users may have a better clue as to what the issue might be and can start looking for issues approprietly.
resolves #14598 and #10444 - at least partially.
> chore(internal.snmp): Rephrase error message is about translating OID

- plugins/inputs/smart/README.md
- plugins/inputs/smart/sample.conf
- plugins/inputs/smart/smart.go
- plugins/inputs/smart/smart_test.go
When multiple disks are standing behind the same controller, we currently cannot tell them apart.
With these changes, an extra tag `device_type` can be added to help differentiate them.
This tag can be enabled from the config with the `tag_with_device_type` property, and is disabled by default to preserve backward compatibility.
Sample output of a Dell server with 8 physical disks:
```shell
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/bus/0 -d megaraid,0 # /dev/bus/0 [megaraid_disk_00], SCSI device
/dev/bus/0 -d megaraid,1 # /dev/bus/0 [megaraid_disk_01], SCSI device
/dev/bus/0 -d megaraid,2 # /dev/bus/0 [megaraid_disk_02], SCSI device
/dev/bus/0 -d megaraid,3 # /dev/bus/0 [megaraid_disk_03], SCSI device
/dev/bus/0 -d megaraid,4 # /dev/bus/0 [megaraid_disk_04], SCSI device
/dev/bus/0 -d …
```
> feat(inputs.smart): Add a "device_type" tag to differentiate disks behind a RAID controller

- plugins/outputs/iotdb/README.md
- plugins/outputs/iotdb/iotdb.go
- plugins/outputs/iotdb/iotdb_test.go
- plugins/outputs/iotdb/sample.conf
Support for IoTDB ILLEGAL_PATH error when tags contains an illegal character, explained more in detail in issue.
resolves #14518
> fix(outputs.iotdb): Handle paths that contain illegal characters

- internal/type_conversions.go
- plugins/inputs/sql/sql.go
- plugins/inputs/suricata/suricata.go
The current type conversions for `uint64` and `int64`  might underflow/overflow when e.g. used with floating-point numbers. We should detect those cases and report the issue to the caller while also returning the "malformed" value in case the caller wants to use it.
Furthermore, the PR adds conversions for the 32-, 16- and 8-bit types for reuse e.g. in #14474.
> chore(internal): Handle ranges in type-conversion and add missing types

- plugins/inputs/mysql/README.md
Add to docs how to convert some string fields that may have a variety of values using the enum processor for outputs that require a numeric field.
fixes: #14510
fixes: #10697
> docs(inputs.mysql): Add section on how to convert string to numeric

- docs/CONFIGURATION.md
Add note about single vs double quote usage in TOML config.
> docs(config): Add comment about single vs double quotes

- .circleci/config.yml
The windows lint job keeps getting killed due to memory pressure. This reduces the GOGC value even further to 1. We may need to look at a large size, at a cost, if this still does not reduce memory usage.
> chore: Drop windows lint gogc value to 1

- plugins/common/encoding/decoder_reader.go
We have a local defined error (ie ErrShortDst, ErrShortSrc) objects in **decoder_reader.go** which has transferred from an original transformer package. Those uses inside the Read() function to properly manage a slice allocations. It does not work
cause **errors.Is** never set to true cause local errors object it's not the same transformer defined errors objects.
I got this error on my production when _character_encoding = "utf8"_ option was used for _inputs.file_ and dst buffer size is not enough to decode obviously.
Well, we need just to use a proper error objects. This PR to solve the problem. Thx.
> fix(common.encoding): Remove locally-defined errors and use upstream ones

- plugins/processors/parser/parser.go
- plugins/processors/parser/parser_test.go
When tracking metrics are used, the parser processor is not currently marking the tracking metrics as dropped if they are not continued on. This means that the messages are not acknowledged at the input.
fixes: #14648
> fix(processors.parser): Drop original tracking metrics

- plugins/inputs/temp/temp_linux.go
See discussion in #14645. tl;dr a warning is overkill and a nuisance.
resolves #14645
> chore(inputs.temp): Convert warning on missing sensors to debug message

- Makefile
- tools/package_incus_test/container.go
- tools/package_incus_test/main.go
Enables SuSE support by ensuring telegraf is installed after useradd.
resolves #3833
> fix(rpm): Ensure telegraf is installed after useradd

- plugins/inputs/redfish/README.md
- plugins/inputs/redfish/redfish.go
- plugins/inputs/redfish/redfish_test.go
- plugins/inputs/redfish/sample.conf
- plugins/inputs/redfish/testdata/hp_thermal_ilo4.json
HP's iLO 4 was released before redfish support as present. They have added compatibility along the way and we carry a change to add a header to ensure this compatibility occurs. However, this header is not always needed and explains why iLO 4 devices were not returning fan data.
User's of iLO 4, which we have no way of knowing, will need to enable this workaround to get fan data.
resolves #14488
> fix(inputs.redfish): Resolve iLO4 fan data

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/chrony/README.md
- plugins/inputs/chrony/chrony.go
- plugins/inputs/chrony/chrony_test.go
- plugins/inputs/chrony/sample.conf
- plugins/inputs/chrony/testdata/chrony.conf
- plugins/inputs/chrony/testdata/start.sh
This PR removes the dependency for `chronyc` to be installed in preparation of tackling #2798. That change now also allows to check remote chrony daemons if they are configured to allow this (see `bindcmdaddress` and `cmdallow` of [chronyd documentation](https://chrony-project.org/doc/4.5/chrony.conf.html)).
Furthermore, we do add an integration test against a chrony docker container and improve the non-integration test.
related to #2798
> feat(inputs.chrony): Remove chronyc dependency

- plugins/inputs/snmp_trap/README.md
- plugins/inputs/snmp_trap/sample.conf
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
SHA224, SHA256, SHA384 and SHA512 ciphers had been commented out when SNMPv3 support was implemented because they were not at that time yet sufficiently supported by gosnmp. Gosnmp has advanced and the ciphers are now fully working, so they can be added to the list of valid options for the snmp_trap plugin
resolves #14664
> fix(inputs.snmp_trap): Enable SHA ciphers

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/inputs/prometheus/sample.conf
Introduce a new config option to ensure that the length of the response body is less than the specified limit.
If the body length exceeds the limit, input.prometheus plugin doesn't send the metrics to subsequent plugins. This can prevent running out of buffer space and dropping metrics when very large data is received.
This is to redo the previous PR(https://github.com/influxdata/telegraf/pull/14548) in order to clean up the commit logs and contain the fix for review comments at the PR.
resolves #14437
> feat(inputs.prometheus): Add option to limit body length

- plugins/outputs/graphite/README.md
- plugins/outputs/graphite/graphite.go
- plugins/outputs/graphite/graphite_test.go
- plugins/outputs/graphite/sample.conf
Allow to set a local IP address to use in the dialer.
resolves #14614
> feat(outputs.graphite): Allow to set the local address to bind

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
Correctly change Kafka telegraf's configuration variable name to `msg_headers_as_tags` from `msg_headers_to_tags`
resolves #
> fix(inputs.kafka_consumer): Correctly setting name to `msg_headers_as_tags`

- plugins/inputs/win_services/win_services.go
This PR allows to specify the services to include or exclude in a case-insensitive way.
resolves #8796
> feat(inputs.win_services): Make service selection case-insensitive

- plugins/inputs/filecount/filecount.go
- plugins/inputs/filecount/filesystem_helpers.go
- plugins/inputs/filecount/filesystem_helpers_notwindows.go
`godirwalk` does not automatically filter out symlink files with its `FollowSymbolicLinks` config option. Changes to calling `Fstat` if needed to respect the settings, where before it would call `Stat` and automatically follow the link
resolves #13250
> fix(inputs.filecount): Respect symlink files with FollowSymLinks

- internal/internal_test.go
Fix test failure on macOS with a time zone check resolving differently on macOS and linux
> chore: Fix timezone test case failure on macOS

- plugins/inputs/redfish/README.md
- plugins/inputs/redfish/redfish.go
- plugins/inputs/redfish/redfish_test.go
- plugins/inputs/redfish/sample.conf
Updates the redfish input plugin to allow secrets to be used for the username and password fields.
resolves #14682
> feat(inputs.redfish): Allow secrets for username/password configuration

- plugins/processors/date/date.go
- plugins/processors/date/date_test.go
Add unit-test for date processor and fix error-message formatting.
resolves #14711
> test(processors.date): Add unit-test for tracking metrics

- plugins/processors/converter/converter_test.go
> test(processors.converter): Add unit-test for tracking metrics

- plugins/processors/enum/enum_test.go
Adds test case for tracking metrics in the enum processor. No code changes needed
resolves #14714
> test(processors.enum): Add unit-test for tracking metrics

- plugins/inputs/postgresql_extensible/postgresql_extensible.go
Fixes postgresql_extensible to support bool tags.
Previous behavior was to silently ignore the provided configuration and convert the tag into a field, which is pretty bad behavior IMHO. While I would argue that if the configuration can't be followed, an error should be emitted and the metric dropped, that's out of scope. This PR only fixes the specific bool issue.
resolves #
> fix(inputs.postgresql_extensible): Add support for bool tags

- plugins/processors/defaults/defaults_test.go
> test(processors.defaults): Add unit-test for tracking metrics

- cmd/telegraf/telegraf.go
- go.mod
- go.sum
Remove git dependency and use tagged version instead.
> chore(deps): Use github.com/coreos/go-systemd/v22 instead of git version

- go.mod
- go.sum
> chore(deps): Bump github.com/gwos/tcg/sdk from v0.0.0-20220621192633-df0eac0a1a4c to v8.7.2

- go.mod
- plugins/inputs/intel_pmt/filtering.go
- plugins/inputs/intel_powerstat/intel_powerstat.go
- plugins/inputs/p4runtime/p4runtime.go
- plugins/outputs/clarify/clarify_test.go
Use the built-in "slices" version instead of referencing the experimental implementation.
> chore(deps): Get rid of golang.org/x/exp and use stable versions instead

- .github/workflows/readme-linter.yml
- tools/update_goversion/main.go
Updates readme-linter to Go 1.22 and adds it to the list of files updated by update_goversion
resolves #
> chore: Fix readme linter not using correct Go version

- plugins/processors/execd/execd.go
- plugins/processors/execd/execd_test.go
Currently, this plugin drops incoming metrics as we cannot decide if a metric passes the processor or not. However, it is very likely that the metric passes the processor. In any case, the processor does something with the metric and thus we should accept it.
The PR also adds a unit-test for tracking metrics.
resolves #14715
> fix(processors.execd): Accept tracking metrics instead of dropping them

- .github/dependabot.yml
- .github/workflows/linter.yml
This PR bumps `super-linter` action to latest released version `v6.0.0`. It also configures dependabot to check for updates of the GitHub actions on a weekly basis.
> dependabot: check for updates to GitHub actions

- plugins/inputs/prometheus/prometheus_test.go
Fix remaining linter issues
```
plugins/inputs/prometheus/prometheus_test.go:594:72  revive  unused-parameter: parameter 'r' seems to be unused, consider removing or renaming it as _
plugins/inputs/prometheus/prometheus_test.go:635:72  revive  unused-parameter: parameter 'r' seems to be unused, consider removing or renaming it as _
plugins/inputs/prometheus/prometheus_test.go:671:72  revive  unused-parameter: parameter 'r' seems to be unused, consider removing or renaming it as _
```
> chore(inputs.prometheus): Fix linter warnings

- plugins/processors/override/override.go
- plugins/processors/override/override_test.go
> test(processors.override): Add unit-test for tracking metrics

- plugins/processors/filepath/filepath_test.go
> test(processors.filepath): Add unit-test for tracking metrics

- plugins/processors/printer/printer_test.go
> test(processors.printer): Add unit-test for tracking metrics

- plugins/processors/port_name/port_name_test.go
> test(processors.port_name): Add unit-test for tracking metrics

- plugins/inputs/aerospike/README.md
- plugins/inputs/deprecations.go
Deprecate the plugin in favor of the use of Prometheus.
fixes: #14450
> feat(inputs.aerospike): Deprecate plugin

- plugins/processors/tag_limit/tag_limit_test.go
> test(processors.tag_limit): Add unit-tests for tracking metrics

- .github/dependabot.yml
This will force the use of only "dependencies" as the only label dependabot adds to PRs.
> chore: Update dependabot labels

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_metric.go
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/sample_general_end.conf
- plugins/inputs/modbus/type_conversions.go
- plugins/inputs/modbus/type_conversions_string.go
Some devices seem to only use the upper/lower byte of the 16-bit register value to store string bytes. This PR adds a workaround to handle those...
resolves #14748
> feat(inputs.modbus): Add workaround for unusual string-byte locations

- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
- plugins/inputs/nvidia_smi/sample.conf
As per #14603 adding a capability to ignore absence of GPUs e.g. in compute clusters that share a `telegraf.conf` file across multiple nodes via an optional `startup_error_behavior` parameter. The default is to error out as before.
addresses NVIDIA part of #14603
Once accepted the AMDGPU one will follow
> feat(inputs.nvidia_smi): Add startup_error_behavior config option

- plugins/processors/reverse_dns/reverse_dns_test.go
I am a little concerned about this one running every time given the need to use the network. The other unit test is considered an integration test.
fixes: #14727
> test(processors.reverse_dns): Add unit-tests for tracking metrics

- plugins/processors/unpivot/unpivot.go
- plugins/processors/unpivot/unpivot_test.go
resolves #14735
resolves #14685
> fix(processors.unpivot): Handle tracking metrics correctly

- plugins/processors/converter/converter_test.go
- plugins/processors/date/date_test.go
- plugins/processors/defaults/defaults_test.go
- plugins/processors/execd/execd_test.go
- plugins/processors/filepath/filepath_test.go
- plugins/processors/ifname/ifname_test.go
- plugins/processors/lookup/lookup_test.go
- plugins/processors/regex/regex_test.go
- plugins/processors/rename/rename_test.go
- plugins/processors/reverse_dns/reverse_dns_test.go
- plugins/processors/s2geo/s2geo_test.go
- plugins/processors/scale/scale_test.go
- plugins/processors/tag_limit/tag_limit_test.go
- plugins/processors/template/template_test.go
- plugins/processors/topk/topk_test.go
When checking tracking metrics' acknowledgement, we need to
1. Accept all **outputs** of the processor as this is what the output will do.
2. Check if we get the delivery information for all **inputs** of the processor.
However, some processors use the number of expected output when checking the number of delivered/acknowledged metrics, one even directly acknowledges the input, which defeats the purpose of the test.
This PR makes sure, we do the right thing when testing tracking metrics.
> test(processors): Fix unit-test for tracking metrics

- plugins/outputs/websocket/README.md
- plugins/outputs/websocket/websocket.go
- plugins/outputs/websocket/websocket_test.go
Make the header values secrets instead of plain strings to support setting bearer tokens properly.
resolves #14835
> feat(outputs.websocket): Allow specifying secrets in headers

- internal/internal_test.go
In the case where a user is actually in the timezone the error message may not print out. Trying multiple timezones ensures the message appears in this case.
resolves #14853
> test(internal): Try multiple timezone abbrevations

- plugins/inputs/procstat/procstat_test.go
A user could actually have the PID requested in this test. Meaning that the result is more than one result. Therefore, to ensure this is not flaky, ensure we get at least one metric back.
resolves #14855
> test(inputs.procstat): Resolve flaky test when PID exists

- config/config.go
- config/config_test.go
We get 1-2 bugs a month about this error message showing up. Let's clarify that it is either a typo or the config option doesn't exist in their version.
> fix(config): Reword error message about missing config option

- plugins/inputs/sqlserver/sqlserverqueries.go
Adds stolen target memory ratio to track additional memory usage.
fixes: #14751
fixes: #9112
> feat(inputs.sqlserver): Add stolen target memory ratio

- .circleci/config.yml
This reverts PR #14035 to use the latest version of mingw again.
> chore(circleci): Use latest mingw

- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/phpfpm/phpfpm_test.go
Currently, the plugin does not gather any data if a single socket cannot be connected. This PR changes the behavior to collect all available data and output the errors for the other ones.
resolves #14261
> fix(inputs.phpfpm): Continue despite erroneous sockets

- plugins/processors/override/override.go
TOML tag is incorrectly named.
fixes: #14879
> fix(processors.override): Correct TOML tag name

- plugins/inputs/docker_log/docker_log.go
Copied the fix from docker.go file.
This fix should change how docker logs plugin searches for the correct container name. 
We found out that there was similar fix done in docker plugin few years ago. 
https://github.com/influxdata/telegraf/issues/4376
resolves #
> fix(inputs.docker_log): Use correct name when matching containers

- CHANGELOG.md
When setting a read-timeout on stream connections such as TCP, the server (in this case the syslog plugin) reads from an initiated connection. In case no new message arrives during the set period, the read times out and the plugin expects the connection to be dead. As a consequence, the connection is closed.
In case of syslog, this means that the remote logger needs to send logs with a maximum time-distance of the set timeout. By default we set a timeout of 5 seconds which forces the logger to send log every 5 seconds as otherwise the connection times-out and is closed. This causes errors such as
```
Feb  4 22:18:17 logserver rsyslogd: omfwd: remote server at 127.0.0.1:6514 seems to have closed connection. This often happens when the remote peer (or an interim system like a load balancer …
```
> docs(inputs.syslog): Document change of default read timeout to infinite

- CHANGELOG.md
Add an "important changes" note about the plugin removal to the changelog.
resolves #13376
> docs(changelog): Add note about removed deprecated plugins

- plugins/inputs/disk/disk.go
Remove the deprecated plugin option scheduled for removal in v1.30.0
related to #13375
> chore(inputs.disk)!: Remove deprecated 'mountpoints' option

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
Remove the deprecated plugin option scheduled for removal in v1.30.0
related to #13375
> chore(inputs.mqtt_consumer)!: Remove deprecated 'metric_buffer' option

- plugins/inputs/nats_consumer/nats_consumer.go
Remove the deprecated plugin option scheduled for removal in v1.30.0
related to #13375
> chore(inputs.nats_consumer)!: Remove deprecated 'metric_buffer' option

- plugins/outputs/influxdb/http_test.go
- plugins/outputs/influxdb/influxdb.go
- plugins/outputs/influxdb/influxdb_test.go
Remove the deprecated plugin option scheduled for removal in v1.30.0
related to #13375
> chore(outputs.influxdb)!: Remove deprecated 'url' option

- CHANGELOG.md
- plugins/inputs/postgresql/postgresql_test.go
- plugins/inputs/postgresql/service.go
The current implementation of `SanitizedAddress()` does not handle quoted parameter values containing spaces or equal signs (e.g. `host=localhost user=john password='a secret=good'`). Additionally to those issues, the parsing of URI connection strings is completely broken for spaces and equal signs as values containing those need to be single-quoted  which does not happen. Furthermore, that function escapes "special characters" (space, backslash and single-quote) which subsequently breaks the sanitize function.
This PR adds unit-tests for both of the mentioned functions. It also removes the useless escaping of spaces during URI handling and replaces this part by quoting the value. Finally, the PR improves the regular-expression used to remove sensitive data to correctly handle quoted …
> fix(inputs.postgres*)!: Prevent leaking sensitive data in server tag

- plugins/inputs/netflow/netflow_decoder.go
Some devices send IPFIX elements encapsulated in Netflow v9 packets. As a workaround, this PR falls back to IPFIX mappings if none of the Netflow v9 or user mappings worked.
resolves #14902 
resolves #14903
> fix(inputs.netflow): Fallback to IPFIX mappings for Netflow v9

- .golangci.yml
> chore(lint): Add gosec G602 - slice out of bounds

- plugins/processors/snmp_lookup/store_test.go
This fixes a race-condition in test-cases (see [CI run](https://app.circleci.com/pipelines/github/influxdata/telegraf/20547/workflows/bbb751d7-f400-4da4-8c45-d72c100e4464/jobs/315363)) that do not perform proper locking.
> test(processors.snmp_lookup): Fix race in test

- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
The statefile should be a valid JSON file, not an empty file.
fixes: #14935
> fix(statefile): Ensure valid statefile

- plugins/parsers/xpath/README.md
- plugins/parsers/xpath/parser.go
Prevent excessive output in debug mode due to node-selection-path debug messages by introducing a new trace option.
resolves #14922
> chore(parsers.xpath): Add tracing mode to output empty-node-selection messages

- docs/specs/tsd-006-startup-error-behavior.md
Add specification for Telegraf's behavior on startup errors including a unified naming of the option and option values.
related to #14803
> docs(specs): Add specification for startup-error behavior

- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/testcases/issue_14946_canonical_field_names/expected.out
- plugins/inputs/gnmi/testcases/issue_14946_canonical_field_names/responses.json
- plugins/inputs/gnmi/testcases/issue_14946_canonical_field_names/telegraf.conf
PR #14553 fixed path handling for field names. In this course the canonical-field-name handling was overlooked because now the path is no longer a simple string leading to
```
2024-03-07T12:44:38Z E! [inputs.gnmi] Invalid empty path "/system/memory/state/reserved" with alias "/system/memory/state"
2024-03-07T12:44:38Z E! [inputs.gnmi] Invalid empty path "/system/memory/state/used" with alias "/system/memory/state"
```
errors (see #14946).  This PR fixes the issue and restores the previous functionality.
related to #14946
> fix(inputs.gnmi): Handle canonical field-name correctly

- migrations/all/inputs_gnmi.go
- migrations/inputs_gnmi/migration.go
- migrations/inputs_gnmi/migration_test.go
- migrations/inputs_gnmi/testcases/deprecated_guess_path/expected.conf
- migrations/inputs_gnmi/testcases/deprecated_guess_path/telegraf.conf
- migrations/inputs_gnmi/testcases/deprecated_guess_path_false/expected.conf
- migrations/inputs_gnmi/testcases/deprecated_guess_path_false/telegraf.conf
- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/gnmi/testcases/issue_14044/telegraf.conf
- plugins/inputs/gnmi/testcases/issue_14946/expected.out
- plugins/inputs/gnmi/testcases/issue_14946/responses.json
- plugins/inputs/gnmi/testcases/issue_14946/telegraf.conf
Some devices omit the prefix when sending only a single value in an update. Add the possibility to use the subscription path as `path` tag.
resolves #14946
> fix(inputs.gnmi): Add option to guess path tag from subscription

- plugins/inputs/chrony/README.md
- plugins/inputs/chrony/sample.conf
This updates the documentation and sample code of the `chrony` input plugin to reflect the code changes done in PR #14629 which was dropping the runtime dependency on a locally installed `chronyc` executable.
resolves #14964
> feat(inputs.chrony): Remove chronyc depdendency in documentation

- plugins/outputs/bigquery/bigquery.go
- Scope was missing for bigquery Client causing ADC to fail.
- Timeout context needs to be removed from connection init, since the dialing happens asynchronously.  https://cloud.google.com/go/docs/reference/cloud.google.com/go/0.94.1#hdr-Timeouts_and_Cancellation
resolves #14957
> fix(outputs.bigquery): Add scope to bigquery and remove timeout context

- plugins/inputs/systemd_units/README.md
- plugins/inputs/systemd_units/sample.conf
- plugins/inputs/systemd_units/systemd_units.go
- plugins/inputs/systemd_units/systemd_units_linux.go
Current systemd DBUS implementation cannot be queried for disabled multi-instance data such as for example `serial-getty@.service` if not enabled for a specific `serial`.
resolves #14980
> fix(inputs.systemd_units): Handle disabled multi-instance units correctly

- config/config.go
- config/config_test.go
- config/secret.go
- config/secret_test.go
Currently, a secret-count underflow can occur if uninitialized secrets are destroyed. This can for example be triggered by the following config part
```tom
[[secretstores.os]]
id = "secrets"
keyring = "telegraf"
```
without actually referencing any secret. In this example, the `password` setting of the secret-store is not set and thus the struct's "secret" member is not initialized (`init(...)` is not called). As a consequence we do not count the secret. However, when the `Init()` function in the OS secret-store terminates it calls `Destroy()` on the `password` secret which unconditionally subtracts one from the secret count. Remember, the `password` secret was not initialized and thus not counted in the first place! As a result, the count underflows.
This PR only counts _initialized_ …
> fix(secrets): Avoid count underflow by only counting initialized secrets

- plugins/inputs/dns_query/dns_query.go
- plugins/inputs/dns_query/dns_query_test.go
> fix(inputs.dns_query): Fill out additional record fields

- docs/specs/tsd-003-output-buffer-strategy.md
- docs/specs/tsd-005-output-buffer-strategy.md
Add specification for Telegraf's behavior on persisting output buffer metrics to disk
Related to #802 and #14805
> docs(specs): Add specification for output buffer persistence strategy

- plugins/inputs/radius/README.md
- plugins/inputs/radius/radius.go
- plugins/inputs/radius/radius_test.go
- plugins/inputs/radius/sample.conf
- plugins/inputs/radius/testdata/invalidSourceIP/clients.conf
- plugins/inputs/radius/testdata/invalidSourceIP/mods-config/files/authorize
- plugins/inputs/radius/testdata/invalidSourceIP/radiusd.conf
> feat(inputs.radius): Provide setting to set request IP address

- go.mod
- go.sum
- plugins/inputs/s7comm/README.md
- plugins/inputs/s7comm/s7comm.go
- plugins/inputs/s7comm/sample.conf
When we use the S7 protocol to access the PLC, we can do so by modifying the
the third byte in the Called (Dst) TSAP (in COTP) to select whether to connect as PG( a program) or OP ( monitor.....) or S7_basic_communication.
But the existing S7Comm plugin can only be used as a PG connection because of this parameter fixed in the robinson/gos7 NewTCPClientHandler() function。
I often encountered when using telegraf to connect to Siemens PLCs that the PLC supports fewer PG connections and more OP connections, so I'd like to add a parameter to change this connect parameter.
In order to be able to change this connect_type when connecting again I've submitted the new connection function NewTCPClientHandlerWithConnectType to robinson/gos7 and have merged the …
> feat(inputs.s7comm):  Add optional connection type setting

- plugins/inputs/smart/smart.go
change attribute regexp to support flags like this kind PO-RC-+
support smart attitudes data like this
```
SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
1 Raw_Read_Error_Rate     PO-RC-+  200   200   051    -    30
3 Spin_Up_Time            POSRCK+  230   230   021    -    5466
4 Start_Stop_Count        -OS-CK+  100   100   000    -    6
5 Reallocated_Sector_Ct   POS-C-+  200   200   140    -    0
7 Seek_Error_Rate         PO-RCK+  200   200   051    -    0
9 Power_On_Hours          -OSRCK+  092   092   000    -    5867
10 Spin_Retry_Count        POS-CK+  100   253   051    -    0
11 Calibration_Retry_Count -OSRCK+  100   253   051    -    0
12 Power_Cycle_Count …
```
> fix(inputs.smart): Improve regexp to support flags with a plus

- plugins/inputs/lustre2/README.md
- plugins/inputs/lustre2/lustre2.go
- plugins/inputs/lustre2/lustre2_test.go
- plugins/inputs/lustre2/sample.conf
Continuation of #7733
resolves #13636
> feat(inputs.lustre2): support reading bulk read/write stats

- plugins/inputs/knx_listener/knx_listener.go
- plugins/inputs/knx_listener/knx_listener_test.go
If the connection to the router or tunnel device is lost for whatever reason, the plugin will make no attempt to reconnect and is thus left dysfunctional. This PR adds a retry logic triggered in every gather cycle to reconnect the plugin.
resolves #14695
> fix(inputs.knx_listener): Reconnect after connection loss

- go.mod
- go.sum
- plugins/outputs/application_insights/application_insights_test.go
Updates testify in prep for parquet parser plugin. There is one test regression where a float and a uint64 were trying to be compared and now fails. The update ensures both comparisons are of the same type.
> chore(deps): Bump github.com/stretchr/testify v1.8.4 to v1.9.0

- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
Percona 8 uses floating-point columns for `connectedTime`, `busyTime`, and `cpuTime` instead of unsigned integers. This PR fixes the code for Percona and provides an integration test.
resolves #7360
> fix(inputs.mysql): Use correct column-types for Percona 8 userstats

- tools/readme_linter/plugin.go
To avoid parsing readmes that are below the plugin directory (e.g. a readme in a testcase) as a plugin readme, let's only mark plugin readmes if they are in the immediate folder under a plugin folder.
> chore(readme_linter): Update plugin type guess logic

- plugins/inputs/knx_listener/knx_listener.go
Ignore KNX GroupValueRead requests as they don't contain any value. Yet DPT 1 typed requests are treated as telegrams with `0` value.
These are my first lines of Go, so please be patient with me 😬
resolves #15006
> fix(inputs.knx_listener): Ignore GroupValueRead requests

- plugins/inputs/prometheus/prometheus.go
- plugins/parsers/prometheus/parser.go
Initialize the otherwise uninitialized logger of the underlying prometheus parser. Furthermore, this PR converts the "unknown format" warning in the parser to debug level to prevent spamming the log-file by default.
resolves #15020
> fix(inputs.prometheus): Initialize logger of parser

- plugins/inputs/dns_query/dns_query.go
This includes the canonical name as a result of a DNS lookup as an additional field. For example, if you look up `gmail.google.com`, the canonical result is `www3.l.google.com.`.
fixes: #11116
> fix(inputs.dns_query): Include the canonical CNAME target

- plugins/inputs/ping/README.md
- plugins/inputs/ping/ping.go
- plugins/inputs/ping/sample.conf
Similar to ipv6 option, add ipv4 option and ensure both are not true.
fixes: #15005
> fix(inputs.ping): Add option to force ipv4

- plugins/inputs/win_wmi/README.md
- plugins/inputs/win_wmi/query.go
- plugins/inputs/win_wmi/sample.conf
- plugins/inputs/win_wmi/win_wmi.go
This PR adds support to query remote hosts via WMI if a host (and credentials) are specified.
resolves #14942
> feat(inputs.win_wmi): Add support for remote queries

- plugins/inputs/dns_query/dns_query.go
- plugins/inputs/dns_query/dns_query_test.go
Allows the user to specify ignoring certain error types from printing in the logs.
fixes: #14941
> feat(inputs.dns_query): Allow ignoring errors of specific types

- plugins/aggregators/basicstats/README.md
- plugins/aggregators/basicstats/basicstats.go
- plugins/aggregators/basicstats/basicstats_test.go
- plugins/aggregators/basicstats/sample.conf
Adds a `last` field to the basic stats aggregator to track the last aggregated value of a metric.
resolves #6263
> feat(aggregators.basicstats): Add "last" field

- docs/specs/tsd-003-state-persistence.md
Publish internal specification for the state-persistence feature of Telegraf.
> docs(specs): Add specification for state-persistence

- plugins/inputs/phpfpm/fcgi_client.go
- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/phpfpm/phpfpm_test.go
The input PHP-FPM don't have timeout when talking (F)CGI protocol, which could lead to input blocked forever.
The timeout exists and was used for HTTP, but not for fcgi.
resolves #15035
> fix(inputs.phpfpm): Add timeout for fcgi

- plugins/inputs/syslog/syslog_test.go
This test is incredibly flaky on Windows. It possibly has some sort of hang occurring which hits a test timeout.
> test(inputs.syslog): Skip test on Windows

- plugins/inputs/lustre2/README.md
- plugins/inputs/lustre2/lustre2.go
- plugins/inputs/lustre2/lustre2_test.go
- plugins/inputs/lustre2/sample.conf
Adds support for https://review.whamcloud.com/c/fs/lustre-release/+/40528.
I'll rebase after https://github.com/influxdata/telegraf/pull/15042 is merged.
NOTE: according to https://wiki.lustre.org/Lustre_Monitoring_and_Statistics_Guide#Reading_/proc_vs_lctl it is technically safer to use `lctl get_param *.*.eviction_count` than parsing files in sysfs/procfs. In this MR I am simply following the existing convention for the plugin. Perhaps in the future we should switch to using `lctl get_param` for maximum portability. Tests would require mocking the `exec.Command` output, as is done for other plugins.
> feat(inputs.lustre2): Add eviction_count field

- plugins/inputs/kubernetes/README.md
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/kubernetes/kubernetes_test.go
- plugins/inputs/kubernetes/sample.conf
The k8s and kube_node plugins produce the same metric name that can conflict. Provide an option in the k8s plugin to change the name.
fixes: #9451
> feat(inputs.kubernetes): Add option to node metric name

- plugins/inputs/lustre2/lustre2.go
Before this commit, the plugin entirely fails when run as anyone other than root, because brw_stats files are symlinks to /sys/kernel/debug/:
```
/sys/kernel/debug/lustre/osd-ldiskfs/MGS/brw_stats
```
Which was causing errors like this:
```
2024-03-22T02:40:40Z E! [inputs.lustre2] Error in plugin: failed to read file /proc/fs/lustre/osd-ldiskfs/MGS/brw_stats: open /proc/fs/lus
tre/osd-ldiskfs/MGS/brw_stats: permission denied
```
After this change, the plugin continues to run and gather whatever metrics it can, even if brw_stats files are unreadable.
I'll rebase after https://github.com/influxdata/telegraf/pull/15042 is merged.
> feat(inputs.lustre2): Skip brw_stats in case of insufficient permissions

- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
The current code for metric version 1 parses everything as an integer for global status queries. This leads to zero values for boolean values such as "ON" or "true" which are in turn perceived as "wrong" on the database side. 
This PR fixes parsing of boolean values and emits a (single-time) warning for other values which might contain strings, floats etc resulting in zero values. The PR does **not** change the behavior for those other values to prevent changes of field-types for the metric output.
resolves #6417
> fix(inputs.mysql): Parse boolean values in metric v1 correctly

- plugins/inputs/knx_listener/README.md
- plugins/inputs/knx_listener/knx_listener.go
- plugins/inputs/knx_listener/knx_listener_test.go
- plugins/inputs/knx_listener/sample.conf
Some DPT's, especially DPT1.xxx, do have more speaking values in their string representation. Allow the user to choose between the two by introducing a new `as_string` flag.
resolves #15039
> feat(inputs.knx_listener): Allow usage of DPT string representation

- plugins/outputs/cratedb/README.md
- plugins/outputs/cratedb/cratedb.go
- plugins/outputs/cratedb/cratedb_test.go
- plugins/outputs/cratedb/sample.conf
- testutil/container.go
This PR allows to define the behavior for startup errors of the cratedb output plugin. If `startup_error_behavior = "retry"` is specified, errors for table creation will not lead to a startup error.
resolves #13278
> feat(outputs.cratedb): Allow configuration of startup error handling

- plugins/outputs/cratedb/README.md
Document the newly available options for the output plugin.
> docs(outputs.cratedb): Document startup error behavior options

- plugins/outputs/postgresql/README.md
- plugins/outputs/postgresql/postgresql.go
- plugins/outputs/postgresql/postgresql_test.go
This PR allows to define the behavior for startup errors of the postgresql output plugin. Doing so you can make Telegraf error out on startup errors (default), to retry connecting to the server or to ignore the output...
resolves #14365
> feat(outputs.postgresql): Allow configuration of startup error handling

- docs/specs/tsd-004-configuration-migration.md
Publish internal specification for the configuration-migration framework and sub-command of Telegraf.
> docs(specs): Add specification for configuration migration

- cmd/telegraf/pprof.go
Pretty sure net/http/pprof got accidentally lost in this commit bd516ae587a27d040b457c593e3d5fa6aaf40269
This MR adds it back in
resolves #15053
> fix(agent): Ensure import of required package for pprof support

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
- plugins/inputs/prometheus/sample.conf
In #14153, the HTTP client config struct gained a response timeout config option with TOML tags. This meant that there were two defined for both Prometheus plugin and the HTTP client config struct. 
This removes the one in the Prometheus plugin, which allows users to correctly load previously existing plugins. However, the `response_timeout` option will now set the HTTP Client config's `ResponseHeaderTimeout`, which is the time spent reading the headers of the response. While `timeout` will set the `Timeout`, which sets the timeout for the entire connection.
This would also get rid of the deprecation warning. Because this now sets a different value and there is no deprecation warning, I'm not sure this is the right thing to do, but it does allow a user to correctly load a config. The …
> fix(inputs.prometheus): Remove duplicate response_timeout option

- plugins/inputs/systemd_units/systemd_units_linux.go
- plugins/inputs/systemd_units/systemd_units_test.go
This PR tries to reconnect to the systemd DBUS daemon in case the connection is lost.
resolves #15111
> fix(inputs.systemd_units): Reconnect if connection is lost

- plugins/inputs/diskio/diskio_linux.go
Avoid spamming the log with warnings if optional udev properties are not available.
resolves #15113
> chore(inputs.diskio): Add udev properties only if available

- plugins/processors/scale/README.md
- plugins/processors/scale/sample.conf
The example code caused 2 different types of errors like this
> error parsing scale, unmarshalling failed: line 19: cannot unmarshal TOML table into []scale.Scaling (need struct or map)
> error parsing scale, unmarshalling failed: line 22: (scale.Scaling.OutMin) cannot unmarshal TOML integer into float64
resolves #15134
> docs(processors.scale): Correct example configuration

- plugins/inputs/jolokia2_agent/examples/cassandra.conf
#15139 -> pull request to add extra metrics to the example configuration
update the cassandra.conf example jolokia2_agent configuration to include commented out per table and all table metrics configuration.
- [ x ] No AI generated code was used in this PR
resolves #15139
> docs(inputs.jolokia2_agent): Add example configs for table and all table metrics

- plugins/processors/all/processors.go
- plugins/processors/timestamp/README.md
- plugins/processors/timestamp/sample.conf
- plugins/processors/timestamp/timestamp.go
- plugins/processors/timestamp/timestamp_test.go
The following introduces a new timestamp processor. This allows a user to specify a field which contains a timestamp and convert it from one format to another. Traditionally telegraf assumes data has a single timestamp and uses that as the timestamp for the metric itself. However, if a user's data contains additional timestamps that they also wish to parse into a different format, there was no existing method for that.
The date processor exists today to take a metric's timestamp and add a tag or field with a subset of that timestamp. Trying to adapt that config to do both features made for a complex configuration that was not straightforward and error prone.
resolves #10524
> feat(processors.timestamp): Introduce timestamp processor

- plugins/processors/clone/README.md
Clarify that metric filtering applies to both the clone and the original
resolves #15116
> docs(processors.clone): Clarify filtering applies to all metrics

- plugins/inputs/modbus/configuration_metric.go
- plugins/inputs/modbus/configuration_metric_test.go
- plugins/inputs/modbus/configuration_register_test.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/configuration_request_test.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/request.go
When using addresses at the end of the address range, the batch-limitation calculation might overflow the `uint16` range.  This PR checks the range now before doing the computation to make sure we do not overflow.
Furthermore, users might provide invalid configuration by using an address at the end of the address-range with a too-large data-type in `metric` and `request` configuration-styles. This PR also checks this overflow.
Note: The `register` style is safe as there you explicitly need to specify the addresses.
resolves #15138
> fix(inputs.modbus): Avoid overflow when calculating with uint16 addresses

- CHANGELOG.md
- plugins/inputs/systemd_units/README.md
- plugins/inputs/systemd_units/sample.conf
- plugins/inputs/systemd_units/systemd_units.go
- plugins/inputs/systemd_units/systemd_units_linux.go
- plugins/inputs/systemd_units/systemd_units_test.go
With PR #14814 we also produce metrics for unloaded units. However, for unspecific filters (like `*` being the default) this touches a lot of files and forces systemd to lookup those unit-files which is expensive.
Therefore, this PR reverts the behavior to pre-v1.30.0 versions and only collects units already loaded by systemd. To allow collecting disabled/unloaded units you can use the new `collect_disabled_units`.
Additionally to this change, the PR also optimizes the interaction with systemd for cases where non-detailed metrics are requested.
This leads to the following improvements when gathering _all_ units (`pattern = "*"`) in non-detailed mode
```
goos: linux
goarch: amd64
pkg: github.com/influxdata/telegraf/plugins/inputs/systemd_units
cpu: AMD Ryzen 7 3700X 8-Core Processor 
``` …
> fix(inputs.systemd_units): Revert to only gather loaded units by default

- plugins/inputs/http_response/README.md
- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/sample.conf
Add http cookie auth to the http_response input plugin, similar to the http input plugin
resolves #11913
> feat(inputs.http_response): Add cookie authentication

- plugins/inputs/knx_listener/knx_listener.go
- plugins/inputs/knx_listener/knx_listener_test.go
KNX has string data types like DPT 16.000 (ASCII text) which can transfer up to 14 bytes of ASCII text. knx_listener didn't support these yet and therefore couldn't log telegrams of this type; this PR adds the required support.
Please review this carefully; I've never written Go before.
resolves #15158
> feat(inputs.knx_listener): Add support for string data type

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/sample.conf
This is a simple PR to plumb through the keep alive settings for the gRPC connections used by the gnmi input plugin, see the related issue for more details.
resolves #15148
> feat(inputs.gnmi): Add keepalive settings

- scripts/telegraf.service
The 5 second timeout was a little aggressive as a default value for users. Instead use the systemd default and/or let a user to set this to what they want.
fixes: #15167
> fix(systemd): Remove 5 second timeout, use default (90)

- plugins/inputs/diskio/diskio_linux.go
Update default path from `/sys/block` to `/sys/class/block`. This change was made to the kernel 16 years ago and is the default location: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=edfaa7c36574f1bf09c65ad602412db9da5f96bf
resolves #15151
> fix(inputs.diskio): Update path to in /sys

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/gnmi_test.go
Add secret store support to username and password config options.
fixes: #15172
> feat(inputs.gnmi): Add secret store support for username and password

- plugins/inputs/phpfpm/fcgi_client.go
- plugins/inputs/phpfpm/phpfpm_test.go
The PHP-FPM input could crash with a nil pointer dereferencing when timeout is used and the connect can't be established (e.g. the PHP-FPM server isn't running).
resolves #15175
> fix(inputs.phpfpm): Check error before continue processing

- agent/agent.go
- config/config.go
- models/running_input.go
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/amqp_consumer/amqp_consumer_test.go
- plugins/inputs/amqp_consumer/sample.conf
A frequently requested feature is to retry startup for plugins in case of error e.g. if the connection to a remote machine fails.
Instead of implementing the logic for retrying in each plugin, this PR provides a framework **for input-plugins** to use if they wish to support retries. As an example, the AMQP input plugin is converted to use the new framework
More details can be found in the [TSD-006 specification](https://github.com/influxdata/telegraf/blob/master/docs/specs/tsd-006-startup-error-behavior.md).
resolves #14803
resolves #13746
> feat(inputs): Add framework to retry on startup errors

- plugins/aggregators/final/README.md
- plugins/aggregators/final/sample.conf
The statements seem switched around currently and are causing confusion for users. Periodic is used to avoid gaps in the data, while timeout is used to only show the last value when a whole bunch come in, i.e. downsample.
https://community.influxdata.com/t/get-at-least-every-5-min-datapoint-by-mqtt-consumer/33911/8
> docs(aggregators.final): Swap useful statements

- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/filter.go
- plugins/inputs/procstat/os_linux.go
- plugins/inputs/procstat/os_others.go
- plugins/inputs/procstat/os_windows.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/sample.conf
- plugins/inputs/procstat/service_finders.go
This PR adds the possibility to specify multiple filter expressions for the process list. Each filter is independent of the other ones, intra-criterion lists are combined using logical **or** whereas different criteria are combined via logical **and**.
```toml
[[inputs.procstat]]
[[inputs.procstat.filter]]
name = "shells"
patterns = ['fish']
users = ["sv*"]
```
resolves #6174
> feat(inputs.procstat): Allow multiple selection criteria

- plugins/inputs/prometheus/prometheus.go
Host header needs to be treated differently, via the Host value. Previously had to do this with influxdb in https://github.com/influxdata/telegraf/pull/14481/
fixes: #15192
> fix(inputs.prometheus): Correctly handle host header

- plugins/inputs/opcua/read_client.go
Always create a request to not panic in case the registration fails.
resolves #15174
> fix(inputs.opcua): Make sure to always create a request

- plugins/inputs/sqlserver/sqlserverqueries.go
We have been testing the sql server input in monitoring our production server and for the last_full_backup/last_differential_backup/last_log_backup we can see that if the timezone is different than UTC on the server, the time is not displayed properly. By adding the timezone offset in the query, we have removed the issue.
If it provided in the issue.
- [X ] No AI generated code was used in this PR
Timezone Not Inlcuded in Backup in SQL Server input #15153
resolves #
> fix(inputs.sqlserver): Honor timezone on backup metrics 

- CHANGELOG.md
- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/os_linux.go
- plugins/inputs/procstat/os_others.go
- plugins/inputs/procstat/os_windows.go
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat_test.go
The fields `read_bytes` and `write_bytes` do report the **overall** I/O including network etc on operating systems such as Windows. However on Linux, those two fields are filled by the I/O to the **storage layer** which causes inconsistent metrics across operating-systems.
This PR changes the behavior on Linux and is now consistently reporting the overall I/O in `read_bytes` and `write_bytes` (using the `rchar` and `wchar` information). It furthermore reports the previous (storage-only I/O) via the new `disk_read_bytes` and `disk_write_bytes` fields.
resolves #9189
> feat(inputs.procstat): Report consistent I/O  on Linux

- plugins/inputs/sysstat/sysstat.go
On reload, telegraf throws away the `sysstat.Sysstat` instance it has and creates a new one; however, this plugin also relies on package-global state (the `firstTimestamp` variable), which leads to sysstat running sadc with increasingly long intervals following a reload, if the interval to use is not explicitly set via `sadc_interval`. Fix this by moving the `firstTimestamp` state into the plugin struct.
resolves https://github.com/influxdata/telegraf/issues/15102
> fix(inputs.sysstat): Prevent default sadc_interval from increasing on reload

- models/running_input.go
- plugins/inputs/amd_rocm_smi/README.md
- plugins/inputs/amd_rocm_smi/amd_rocm_smi.go
- plugins/inputs/amd_rocm_smi/amd_rocm_smi_test.go
- plugins/inputs/amd_rocm_smi/sample.conf
Use the common implementation of startup-retry-behavior implementation.
> chore(inputs.amd_rocm_smi): Consolidate startup_retry_behavior to model implementation

- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer.go
- plugins/inputs/elasticsearch/elasticsearch.go
- plugins/inputs/elasticsearch_query/elasticsearch_query.go
- plugins/inputs/http/http.go
- plugins/inputs/kibana/kibana.go
- plugins/inputs/logstash/logstash.go
- plugins/inputs/openstack/openstack.go
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/vault/vault.go
- plugins/outputs/cloudwatch/cloudwatch.go
- plugins/outputs/http/http.go
- plugins/secretstores/http/http.go
On reload, telegraf rebuilds its plugins, which means creating a new `*http.Client` (and `*http.Transport`) in each of the files touched in this PR. In general, transports should be long-lived; they carry state and possibly idle HTTP connections.
Without explicitly calling `CloseIdleConnections()`, in cases where no `idle_conn_timeout` is set, we leave it up to the go runtime to decide when to drop the connections - and it can easily decide "never", leading to open connections accumulating over time, especially with repeated reloads of the telegraf config in a single process, and eventually telegraf failing with `EMFILE` problems.
Fix this by telling the Go runtime (by calling `CloseIdleConnections()`) when we're done with a given transport.
resolves …
> fix(http): Stop plugins from leaking file descriptors on telegraf reload

- Makefile
In the telegraf building process `make` doesn't do any dependency checking as the process relies on the automatic dependency checking of `go build`. The `package` target previously used non-phony targets `$(buildbin)`, whose recipe, due to the absence of prerequites, is not reexecuted if the `$(buildbin)` files exist. This PR fixes this issue by defining the `$(buildbin)` target as phony.
Resolves #15222
> fix(Makefile): Use go's dependency checker for 'per platform' builds

- agent/agent.go
- plugins/common/starlark/starlark.go
- plugins/processors/starlark/starlark.go
- plugins/processors/starlark/starlark_test.go
Add the possibility to persist the state of the starlark processor. To use the feature you should **not** define the global `state` explicitly but rather rely on the implicit declaration!
resolves #14704
> feat(processors.starlark): Allow persistence of global state

- plugins/outputs/graphite/graphite.go
The original PR #14628 which resolved #14614 mishandled the case in which no port is given together with the local address. The integrated code expected `net.SplitHostPort` to return the address even when no port is given, however, `net.SplitHostPort` instead returns an emptry string. (https://github.com/golang/go/blob/master/src/net/ipsock.go)
resolves #14614 further
> fix(outputs.graphite): Handle local address without port correctly

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/sample.conf
- The change updates the documentation of the Prometheus Input plugin. The `response_timeout` parameter is generally no longer obsolete and is [reused](https://github.com/influxdata/telegraf/pull/15078) by the HTTP header timeout.
> docs(inputs.prometheus): Remove invalid deprecation statement

- plugins/outputs/influxdb/README.md
- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb/influxdb.go
- plugins/outputs/influxdb/influxdb_test.go
- plugins/outputs/influxdb/sample.conf
- plugins/outputs/influxdb/udp.go
Add option to set local ip (and port) which allows to select the interface over which the influx server is contacted.  Based on #14628.
resolves #4287 (which was closed but never really resolved)
> feat(outputs.influxdb): Add option to define local address

- plugins/outputs/influxdb_v2/README.md
- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/influxdb_v2.go
- plugins/outputs/influxdb_v2/influxdb_v2_test.go
- plugins/outputs/influxdb_v2/sample.conf
Add option to set local ip (and port) which allows to select the interface over which the influxdb v2 server is contacted. Based on #14628.
resolves #4287 (which was closed but never really resolved)
> feat(outputs.influxdb_v2): Add option to set local address

- plugins/parsers/json_v2/parser.go
When a timestamp fails to parse it produces a very vauge message:
```s
2024-04-26T12:45:22Z E! [inputs.file] Error in plugin: could not parse "data": invalid number
```
This does not tell you what the data is, or even that it is the timestamp that failed to parse. Instead this PR changes to this:
```s
2024-04-26T12:47:34Z E! [inputs.file] Error in plugin: could not parse "data": unable to parse timestamp "12a34567890": invalid number
```
fixes: #15237
> fix(inputs.http_listener_v2): Wrap timestamp parsing error messages

- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/sample.conf
The currently used TOML parser does not support converting (nested) inline notations to a struct. Therefore, this PR removes the misleading example in the `sample.conf`.
resolves #15252
> docs(inputs.opcua_listener): Remove invalid inline notation

- plugins/inputs/mock/README.md
- plugins/inputs/mock/mock.go
- plugins/inputs/mock/mock_test.go
- plugins/inputs/mock/sample.conf
We would like to simulate a sine wave that does not rotate around 0.0
resolves #15269
> feat(inputs.mock): Add baseline option to sine

- plugins/outputs/loki/README.md
- plugins/outputs/loki/loki.go
- plugins/outputs/loki/loki_test.go
- plugins/outputs/loki/sample.conf
Add option, disabled by default, to sanitize label names.
fixes: #15274
> fix(outputs.loki): Option to sanitize label names

- plugins/inputs/procstat/filter.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/service_finders.go
Change code to report only running processes as running if an orphan PID-files is used, which can happen if the process died unexpectedly.
resolves #15107
> fix(inputs.procstat): Do not report dead processes as running for orphan PID files

- plugins/aggregators/final/README.md
- plugins/aggregators/final/final.go
- plugins/aggregators/final/final_test.go
- plugins/aggregators/final/sample.conf
Changing the data schema is not always wanted. Especially when originals are dropped or the final value needs to be routed to a different output.
resolves #15267
> feat(aggregators.final): Add option to disable appending _final

- plugins/outputs/influxdb/README.md
- plugins/outputs/influxdb/influxdb.go
- plugins/outputs/influxdb/sample.conf
- plugins/outputs/influxdb_v2/README.md
- plugins/outputs/influxdb_v2/influxdb_v2.go
- plugins/outputs/influxdb_v2/sample.conf
- plugins/serializers/influx/README.md
- plugins/serializers/influx/influx.go
- plugins/serializers/influx/influx_test.go
- plugins/serializers/registry.go
> feat(serializers.influx): Add option to omit timestamp

- plugins/inputs/ceph/ceph.go
- plugins/inputs/ceph/ceph_test.go
Run ceph perf schema to determine the metric types and use that information to correctly parse metrics.
resolves #
> feat(inputs.ceph): Use perf schema to determine metric type

- docs/QUICK_START.md
Adds a quick start page, there exists something similar from the main readme, but will be removed in a revamp of that page. This is meant to get someone going with Telegraf as quickly possible and then point them to what they might need to use next.
> docs: Add quick start

- plugins/inputs/redis/README.md
- plugins/inputs/redis/redis.go
- plugins/inputs/redis/redis_test.go
"ALL" info contains latency percentile statistics, and these were not parsed. This creates problems in e.g. the Prometheus output.
resolves #15294
> feat(inputs.redis): Add latency percentiles metric

- plugins/common/tls/client.conf
- plugins/common/tls/common.go
- plugins/common/tls/config.go
- plugins/common/tls/utils.go
- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/gnmi/sample.conf.in
- plugins/inputs/http/README.md
- plugins/inputs/http/sample.conf
In [grpc-go v1.60.0](https://github.com/grpc/grpc-go/releases/tag/v1.60.0) insecure cipher-suites were disabled by default. As some devices might still require those, this PR adds the possibility to explicitly set accepted ciphers using the 
`tls_cipher_suites` setting for client TLS.
resolves #15236
> feat(inputs.gnmi): Allow to pass accepted cipher suites

- .circleci/config.yml
- Makefile
- models/buffer.go
- plugins/outputs/dynatrace/dynatrace.go
- plugins/processors/topk/topk.go
Update golangci-lint and remove our min functions, in favor or using the builtin min function.
> chore(deps): Bump golangci-lint from v1.57.2 to v1.58.0

- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
Improve debug information for reproducing issues quicker...
related to #15286
> chore(inputs.gnmi): Add more response information for easier debugging

- plugins/parsers/grok/parser.go
When providing Grok patterns without a named field (or tag) Telegraf will currently report that no match was found for the pattern(s). This PR extends the message to also cover that case.
resolves #15315
> chore(parsers.grok): Improve non-matching debug message

- plugins/inputs/win_eventlog/README.md
- plugins/inputs/win_eventlog/sample.conf
- plugins/inputs/win_eventlog/win_eventlog.go
Currently, we are fetching five events at a time and process them. The new option allows to tweak the number of events to fetch as one batch to potentially improve performance when larger volumes of events occur.
resolves #15242
> feat(inputs.win_eventlog): Add option to define event batch-size

- plugins/outputs/postgresql/README.md
A user had a speed issue and requested help to create indexes for the auto generated table in PostgreSQL on [this Slack thread](https://influxcommunity.slack.com/archives/CH99HUH8V/p1715133186596159). We figured out  how to solve this, so returning the knowledge into an extra sample config in the documentation.
N/A
> docs(outputs.postgresql): Add example to create index for tag columns

- plugins/aggregators/merge/README.md
- plugins/aggregators/merge/merge.go
- plugins/aggregators/merge/merge_test.go
- plugins/aggregators/merge/sample.conf
This PR allows to specify the rounding of metric timestamps to be able to merge metrics that have spread-out timestamps
but should be merged.
resolves #11807
> feat(aggregators.merge): Allow to round metric timestamps

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update go version.
fixes: #15331
> chore(deps): Bump go from v1.22.2 to v1.22.3

- go.mod
- go.sum
- plugins/inputs/internet_speed/README.md
- plugins/inputs/internet_speed/internet_speed.go
- plugins/inputs/internet_speed/sample.conf
1. Bump to new version to improve test precision and fix bugs.
2. Support packet_loss field.
> feat(inputs.internet_speed): support packet loss

- plugins/inputs/execd/README.md
- plugins/inputs/execd/examples/count.py
Adds a python example, and removes the duplicated code and instead tells the user which signal each requires.
fixes: #15333
> docs(inputs.execd): Add python example, clean up doc

- plugins/inputs/file/README.md
- plugins/inputs/file/file.go
- plugins/inputs/file/file_test.go
- plugins/inputs/file/sample.conf
Add option to add a tag with the absolute path to the file (e.g. `/tmp/myfile.toml`)
fixes: #15133
> feat(inputs.file): Add tag with absolute path of file

- plugins/inputs/win_wmi/README.md
- plugins/inputs/win_wmi/method.go
- plugins/inputs/win_wmi/query.go
- plugins/inputs/win_wmi/sample.conf
- plugins/inputs/win_wmi/win_wmi.go
- plugins/inputs/win_wmi/win_wmi_test.go
This PR allows to invoke WMI methods similar to the `Invoke-Method` command. This way it is possible to e.g. extract registry keys and create a metric from the returned value(s).
resolves #14653
> feat(inputs.win_wmi): Allow to invoke methods

- cmd/telegraf/main.go
When exiting a program with `log.Fatal`, the program does not execute any deferred calls and will also exit immediately. For logging with the Windows event-logger interface, this means that the connection to the logger is not shut down gracefully and thus the final  (and most important) log message is lost.
This PR does not use `log.Fatal` to log the message but rather rely on `log.Print` which allows for a graceful exit. Furthermore, we move the logging into the `runApp` function which really is the core processing loop.
resolves #14144
> fix(windows): Make sure to log the final error message

- go.mod
- go.sum
- plugins/inputs/internet_speed/internet_speed.go
Bump to new version and fix measurement error bug.
https://github.com/heathcliff26/speedtest-exporter/issues/25
> chore(deps): Bump github.com/showwin/speedtest-go from 1.7.5 to 1.7.6

- docs/CONFIGURATION.md
> docs(agent): Specify jitter value must be non-zero

- plugins/inputs/net/net.go
Clarifies the deprecation notice for the `ignore_protocol_stats` option to be more clear about only the option being deprecated, not the plugin
> chore(inputs.net): Clarify option deprecation notice

- docs/specs/tsd-007-url-config-behavior.md
Introduce a new spec to define URL-based config behavior.
> docs: Add URL config behavior spec

- docs/PROFILING.md
Clean up the docs, add some additional notes.
> docs: Update profiling docs

- plugins/inputs/statsd/README.md
- plugins/inputs/statsd/sample.conf
- plugins/inputs/statsd/statsd.go
- plugins/inputs/statsd/statsd_test.go
By default counters are stored as ints. However, if a user is using a value as both a float or a int it can lead to type conflicts. This maintains the interal representation as an int to avoid messing with the caching code, but allows the counter to be reported as a float when a metric is reported.
fixes: #1978
> feat(inputs.statsd): Allow counters to report as float

- metric/metric.go
Export the internal fields on the metric struct so that they can be serialized by things like `gob`
Part of #15221
> chore(agent): Export internal metric fields

- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- config/config.go
- config/internal_test.go
This introduces a new cli option to allow the user to set the number of retry attempts to something other than 3. It also allows the user to set the attempt count to -1 to infinitely retry.
fixes: #8854
> feat(agent): Introduce CLI option to set config URL retry attempts

- plugins/inputs/statsd/README.md
- plugins/inputs/statsd/sample.conf
- plugins/inputs/statsd/statsd.go
- plugins/inputs/statsd/statsd_test.go
Currently statsd input fails to parse statsd metrics emitted by datadog client from inside kubernetes as they contains additional field described in DogStatsD protocol v1.2 which is the container id.
This will add the handling of such metrics and drop it or include it as a tag depending on the configuration.
resolves #12991
> feat(inputs.statsd): Add support for DogStatsD v1.2 (#12991)

- plugins/processors/parser/README.md
- plugins/processors/parser/parser.go
- plugins/processors/parser/parser_test.go
- plugins/processors/parser/sample.conf
Adds a base64 decode option for any field specified in the `parse_fields` config option.
resolves #15130
> feat(processors.parser): Add base64 decode for fields

- plugins/processors/parser/parser_test.go
CircleCI complained about test failures where results were not in the same order. Sort the metrics to ensure a consistent ordering. This was due to landing #15328 
https://app.circleci.com/pipelines/github/influxdata/telegraf/21557/workflows/481fee41-db19-44d7-a014-7bdc9ca83014/jobs/332868
> test(processors.parser): Sort test metrics

- internal/process/process.go
- plugins/inputs/execd/README.md
- plugins/inputs/execd/execd.go
- plugins/inputs/execd/execd_test.go
- plugins/inputs/execd/sample.conf
In some cases it is required to not restart the underlying process if it exits with an error, e.g. when those programs might go havoc and might cause out-of-memory conditions or are in other was sensitive to errors. This PR adds an option to stop the underlying program on error (exit code is non-zero) instead of trying to restart it every time it exits.
resolves #14244
> feat(inputs.execd): Add option to not restart program on error

- .circleci/config.yml
- Makefile
Updates the CircleCI config and Makefile for Xcode 15. For the CircleCI testing container this should be inconsequential. For the Makefile, these new options are (currently) necessary for macOS 13.5+, but will not work on macOS 13.4 and below.
> chore: Update to Xcode 15 in CI

- config/config.go
Users sometimes try to use multiple agent sections, but this leads to undefined behavior. We should start to warn and eventually error on these types of issues.
> fix(agent): Warn on multple agent configuration tables seen

- plugins/inputs/cloudwatch/cloudwatch.go
If not account IDs are returned we need to avoid a panic.
fixes: #15422
> fix(inputs.cloudwatch): Ensure account list is larger than index

- plugins/inputs/influxdb_v2_listener/README.md
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go
It should be possible to use a secret as the token source.
resolves #15406
> feat(inputs.influxdb_v2_listener): Support Secret for token

- plugins/inputs/exec/README.md
- plugins/inputs/exec/exec.go
- plugins/inputs/exec/exec_test.go
- plugins/inputs/exec/sample.conf
This allows the exec plugin to ignore any errors returned and continue to parse the output.
fixes: #9483
> feat(inputs.exec): Add option to ignore return code

- plugins/inputs/cloudwatch/cloudwatch.go
There was one case, where a user defined a metric, but no dimensions. In this case, the accounts were never added when IncludeLinkedAccounts was set to true.
fixes: #15422
> fix(inputs.cloudwatch): Add accounts when enabled

- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- config/config.go
This introduces a new config-url-watch-interval option, which when set will, at each interval, check the Last-Modified header of the file to determine if telegraf should reload.
If the header is not available then the watcher is disabled for the file.
fixes: #8730
> feat(config): Allow reloading on URL config change

- cmd/telegraf/cmd_win_service.go
- cmd/telegraf/cmd_win_service_notwindows.go
- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- cmd/telegraf/telegraf_posix.go
- cmd/telegraf/telegraf_windows.go
- docs/LICENSE_OF_DEPENDENCIES.md
- docs/WINDOWS_SERVICE.md
- go.mod
- go.sum
This PR reworked the Windows service handling of Telegraf, including the replacing a 3rd-party library with standard calls as well as introducing the `service` command instead of the `--service flag`.
resolves #14834
> chore(windows): Rework Windows service handling

- plugins/processors/printer/README.md
- plugins/processors/printer/printer.go
- plugins/processors/printer/sample.conf
Add all options of the Influx serialised also to the Printer processor.
related #15433
> feat(processors.printer): Embed Influx serializer options

- .golangci.yml
- cmd/telegraf/telegraf.go
- config/config.go
- config/config_test.go
- config/envvar.go
- filter/filter_test.go
- internal/globpath/globpath.go
- internal/globpath/globpath_test.go
- internal/internal_test.go
- internal/process/process.go
- internal/rotate/file_writer_test.go
- internal/snmp/field.go
- internal/snmp/translator_gosmi.go
- internal/templating/engine_test.go
- logger/default_logger_test.go
- migrations/inputs_httpjson/migration_test.go
- testutil/accumulator.go
- tools/package_incus_test/container.go
Resolves all of the warnings returned by the `errcheck` linter in files outside of the `plugins/` directory and enables the errcheck `check-blank` option. This excludes errcheck from running in the plugins/ directory, as well as `nolintlint` checking for `nolint:errcheck` lines in that directory temporarily until a follow-up PR which will resolve the remaining errcheck warnings.
Part of #13013
> chore: Fix errcheck CI warnings outside of plugins directory

- internal/snmp/field.go
- internal/snmp/field_test.go
- internal/snmp/translator_gosmi_test.go
- internal/snmp/translator_netsnmp_test.go
- plugins/inputs/snmp/README.md
> feat(inputs.snmp): Convert octet string with invalid data to hex

- plugins/inputs/swap/README.md
- plugins/inputs/swap/sample.conf
gopsutil does have support for swap information for linux, windows, *bsd, and others.
fixes: #15449
> docs(inputs.swap): Remove linux only comment

- plugins/inputs/http_listener_v2/README.md
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/http_listener_v2/sample.conf
> feat(inputs.http_listener): Allow setting custom success return code

- plugins/outputs/sql/sql_test.go
It turns out there are additional messages and set up that occur after the message we were currently waiting for. This means that there were a few seconds were the DB was not ready for a connection. hence the error message was correct and the DB was not ready.
> test(outputs.sql): Update wait for log message

- go.mod
- go.sum
- plugins/inputs/azure_monitor/README.md
- plugins/inputs/azure_monitor/azure_monitor.go
- plugins/inputs/azure_monitor/sample.conf
This allows Telegraf authenticating with Workload Identity on K8S or with
VM identity when running directly on a virtual machine.
> feat(input.azure_monitor): Use default azure credentials chain when no secret provided

- internal/internal.go
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/cloud_pubsub/cloud_pubsub.go
- plugins/inputs/cloud_pubsub_push/cloud_pubsub_push.go
- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/eventhub_consumer/eventhub_consumer.go
- plugins/inputs/exec/exec.go
- plugins/inputs/execd/execd.go
- plugins/inputs/file/file.go
- plugins/inputs/file/file_test.go
- plugins/inputs/http/http.go
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kinesis_consumer/kinesis_consumer.go
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/nats_consumer/nats_consumer.go
- plugins/inputs/socket_listener/socket_listener.go
- plugins/inputs/tail/tail.go
To aid debugging and users, this now will print, once, that no messages were generated after parsing a message. This already existed with the MQTT plugin. This has proven useful and helpful to guide users to their parser settings.
> chore: Print debug message when no messages generated from parse

- .circleci/config.yml
The project does not build in Windows or macOS packages for those OSes. Instead, all packages are cross-built in a linux container. As such, there is little reason to wait to build the Windows package till after the Windows tests pass. This can help reduce our total CI time down by around 10mins, or 1/3 of the total time.
Yes, if a test fails it could mean issues, but our CI would still report failed. This is more concerned with speeding up CI.
> chore(circleci): Build Windows package after linux testing

- plugins/inputs/syslog/syslog_test.go
This is the most flaky test we currently have. It was omitted from Windows testing because it was failing consistently and then started happening on Linux as well.
The Test fails after waiting 9mins waiting to read from the socket. With no timeout set in the config the connection is expected to stay open indefinitely as described in #10121.
This re-enables the Windows tests as well to ensure it is actually fixed.
> test(inputs.syslog): Add timeout to closed socket test

- plugins/processors/snmp_lookup/lookup.go
- plugins/processors/snmp_lookup/lookup_test.go
Returning a `tagMap` with empty `rows` but `created` set, makes sure the rebuild of the table will only happen after `min_time_between_updates`.
Telegraf crashes:
```log
2024-06-05T08:32:43Z E! [processors.snmp_lookup] Building table for "172.16.43.2" failed: performing bulk walk for field ifName: request timeout (after 3 retries)
Worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
Stack trace: goroutine 160 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/alitto/pond.defaultPanicHandler({0x70a8180, 0xdc68f90})
/go/pkg/mod/github.com/alitto/pond@v1.8.3/pond.go:26 +0x25
github.com/alitto/pond.(*WorkerPool).executeTask.func1()
/go/pkg/mod/github.com/alitto/pond@v1.8.3/pond.go:437 +0x4a
panic({0x70a8180?, …
```
> fix(processors.snmp_lookup): Return empty tag-map on error to avoid panic

- plugins/inputs/ldap/README.md
- plugins/inputs/ldap/ldap.go
- plugins/inputs/ldap/sample.conf
- plugins/inputs/ldap/sample.conf.in
Document all TLS client options in the plugin's `sample.conf`.
related to #15436
> docs(inputs.ldap): Document all TLS options

- plugins/inputs/ecs/types.go
Avoid a panic when trying to use a nil pointer.
fix: #15455
> fix(inputs.ecs): Check for nil pointer before use

- .circleci/config.yml
- Makefile
- models/running_output_test.go
- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/directory_monitor/directory_monitor_test.go
- plugins/inputs/linux_cpu/linux_cpu_test.go
We certainly should not be using 777 permissions anywhere, the directory monitor change is the only possible regression here. The others are all in tests.
> chore: Update golangci-lint from v1.58.0 to v1.59.0

- plugins/inputs/openstack/openstack.go
Querying available services via the services API requires admin permissions, however when registering to a v3 endpoint, the server sends a [service catalog in the response](https://docs.openstack.org/keystone/latest/api_curl_examples.html).
This PR checks if we got the service catalog in the response and if so, skips the querying of the services endpoint.
partially solves #11769
> feat(inputs.openstack): Use service catalog from v3 authentication if available

- plugins/outputs/elasticsearch/README.md
- plugins/outputs/elasticsearch/elasticsearch.go
- plugins/outputs/elasticsearch/sample.conf
Allow settings extra headers for elasticsearch output's client
resolves #15476
> feat(outputs.elasticsearch): Allow settings extra headers for elasticsearch output

- .circleci/config.yml
- .golangci.yml
- Makefile
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/dovecot/dovecot.go
- plugins/inputs/dovecot/dovecot_test.go
- plugins/inputs/http_response/http_response.go
- plugins/inputs/logparser/logparser.go
- plugins/inputs/net_response/net_response.go
- plugins/inputs/raindrops/raindrops.go
- plugins/inputs/sqlserver/sqlserver.go
- plugins/inputs/win_eventlog/win_eventlog.go
- `golangci-lint` bumped to `v1.59.1`
- Addressing numerous findings caused by updates in several linters:
```
plugins/inputs/cloudwatch/cloudwatch.go:461:3         unparam     (*CloudWatch).aggregateMetrics - result 0 (error) is always nil
plugins/inputs/dovecot/dovecot.go:123:90              unparam     gatherStats - result 0 (error) is always nil
plugins/inputs/http_response/http_response.go:296:28  nolintlint  directive `//nolint:nilerr // error is handled properly` is unused for linter "nilerr"
plugins/inputs/logparser/logparser.go:151:60          unparam     (*LogParserPlugin).tailNewfiles - result 0 (error) is always nil
plugins/inputs/net_response/net_response.go:125:28    nolintlint  directive `//nolint:nilerr // error encoded in result` is unused for linter "nilerr" …
```
> chore(linters): Bump golangci-lint to v1.59.1

- plugins/outputs/elasticsearch/README.md
- plugins/outputs/elasticsearch/elasticsearch.go
- plugins/outputs/elasticsearch/elasticsearch_test.go
- plugins/outputs/elasticsearch/sample.conf
Allows users to provide custom template index settings for the Elasticsearch output plugin. Fully flexible for any allowed setting rather than only allowing specific ones.
resolves #13053
> feat(outputs.elasticsearch): Allow custom template index settings

- agent/agent.go
When running Telegraf with `--test` startup errors of plugins are supposed to be logged and the plugin to be ignored. However, currently the plugin is added to the processing units despite reporting errors on startup. Therefore, the `Gather()` method of those erroneous plugins is called leading to problems due to partial startup (or no startup at all). As an example the following configuration
```toml
[[inputs.openstack]]
username = "admin"
password = "password"
```
will cause Telegraf to panic because parts of the internal plugin structure are not initialized but `Gather()` is called.
The PR ignores plugins reporting startup errors and makes Telegraf to behave as expected in testing mode.
> fix(agent): Ignore startup-errors in test mode

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/http_response_test.go
This PR solves the problem that existed in the scenario where the `urls` list contains mix of IPv4 and IPv6 addresses and the `interface` is config file set.
Until now, the plugin chooses the first available address for the given interface. In my case, it was IPv6 for Windows and IPv4 for Linux. Because of this, the plugin worked incorrectly with IPv4 addresses for Windows and IPv6 addresses for Linux.
Here is a list of the most important things done in this PR:
- Each `URL` now has its own `httpClient` (until now, one `httpClient` was used to handle all `URLs`).
- Each `URL` provided in the config and each address for the given `interface` in the config is parsed and checked to see if it is an IPv4 or IPv6 address.
- I didn't find methods in the standard library (or in other …
> fix(inputs.http_response): Fix for IPv4 and IPv6 addresses when interface is set

- logger/default_logger.go
- logger/logger.go
Before v1.31.0, Telegraf had some public constants inside logging package: https://github.com/influxdata/telegraf/blob/release-1.30/logger/logger.go#L20~#L23. Starting from v1.31.0, these constants are removed and hard-coded strings are used instead in the code. This seems to be a breaking change for some projects referring to these constants. This change is not announced in the release announcement of v1.31.0 as well. It would be great if we can add back those constants to Telegraf source code to have a consistent behavior as the historical code and avoid hard-coded string in the source code.
resolves #15513
> fix(logging): Add back constants for backward compatibility

- .golangci.yml
- plugins/inputs/aerospike/aerospike.go
- plugins/inputs/dovecot/dovecot.go
- plugins/inputs/file/file.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/x509_cert/x509_cert.go
> test(linters): Enable sloppyLen

- docs/LICENSE_OF_DEPENDENCIES.md
There seems to be some serious drama in this project with a recent update. There was a huge revert that took place late last week that also changed the license. We should keep an eye on this and be careful when updating the package version.
> chore: Update github.com/gorilla/websocket license

- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
It seems that the Mysql driver now more strictly checks TLS configuration names when parsing the DSN. Therefore, our current strategy of parsing the DSN and then conveniently replace the TLS configuration name in the struct fails as the `custom` alias is not a registered configuration.
This PR literally replaces the `tls=custom` part of the configuration with the actual name using a regular expression. This circumvents the parsing issue. The PR also adds unit-test to make sure the regexp is safe.
resolves #15490
> fix(inputs.mysql): Handle custom TLS configs correctly

- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
- plugins/inputs/mqtt_consumer/sample.conf
- testutil/accumulator.go
This PR allows to use the startup-error-behavior options `error`, `retry` and `ignore`. It furthermore provided integration test for the different options and one for a "normal" startup.
resolves #10694
> feat(inputs.mqtt_consumer): Implement startup error behaviors

- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
- plugins/inputs/mqtt_consumer/sample.conf
- plugins/inputs/mqtt_consumer/topic_parser.go
This PR allows to use a variable length indicator for topic parsing. The hash (`#`) sign indicates zero to `N` arbitrary path elements that are ignored during parsing.
resolves #10716
> feat(inputs.mqtt_consumer): Add variable length topic parsing

- plugins/inputs/ipmi_sensor/README.md
- plugins/inputs/ipmi_sensor/ipmi_sensor.go
- plugins/inputs/ipmi_sensor/ipmi_sensor_test.go
- plugins/inputs/ipmi_sensor/sample.conf
Introduces the ability to specify some additional sensor paths to collect. Specifically, dcmi power reading and chassis power status.
fixes: #1566
> feat(inputs.ipmi_sensor): Collect additional commands

- plugins/secretstores/oauth2/oauth2.go
- plugins/secretstores/oauth2/oauth2_test.go
> fix(secretstores.oauth2): Ensure endpoint params is not nil

- plugins/inputs/elasticsearch/README.md
- plugins/inputs/elasticsearch/elasticsearch.go
- plugins/inputs/elasticsearch/sample.conf
This PR adds support for custom HTTP headers to the Elasticsearch input plugin. We have some clusters that utilize a custom plugin which require a few particular HTTP headers to be present in order to interact with standard APIs.
resolves #15543
> feat(inputs.elasticsearch): Add support for custom headers

- plugins/parsers/binary/README.md
> docs(parsers.binary): Fix wording in README

- plugins/inputs/chrony/chrony.go
Local sources are directly connected to the server (PPS inputs from oscillators, GPS, etc..). They can be seen as stratum-0 sources.
The standard way of getting their name doesn't work as it is stored into their RefID instead.
This fixes that
resolves #15550
> fix(inputs.chrony): Support local (reference) sources

- plugins/inputs/systemd_units/README.md
- plugins/inputs/systemd_units/sample.conf
- plugins/inputs/systemd_units/systemd_units.go
- plugins/inputs/systemd_units/systemd_units_linux.go
- plugins/inputs/systemd_units/systemd_units_test.go
Systemctl allows to monitor both system- and user-scoped units while `systemd_units` plugin currently supports only system units. PR aims to solve this limitation.
resolves #12053
> feat(inputs.systemd_units): Support user scoped units (#12053)

- plugins/common/tls/client.conf
- plugins/common/tls/utils.go
- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/http/README.md
- plugins/inputs/http/sample.conf
- plugins/inputs/ldap/README.md
- plugins/inputs/ldap/sample.conf
Allow to specify `all`, `secure` and `insecure` for the `tls_cipher_suites` setting to be able to select whole suites of ciphers instead of specifying them one-by-one. This can be combined with individual ciphers e.g.
```toml
tls_cipher_suites = ["secure", "TLS_RSA_WITH_AES_256_GCM_SHA384"]
```
to e.g. allow specific insecure ciphers.
related to #15436
> feat(common.tls): Allow group aliases for ciphersuites

- go.mod
- go.sum
- plugins/inputs/chrony/chrony.go
Chrony ≥ 4.4 introduces a new ServerStats response with u64 numbers and more fields.
Fixes #15553
NB: The plugin still doesn't work due to #15549. To test this commit, please make sure you use #15552.
Support chrony versions ≥ 4.4
resolves #15553
> fix(inputs.chrony): Handle ServerStats4 response

- plugins/common/starlark/field_dict.go
- plugins/processors/starlark/README.md
- plugins/processors/starlark/starlark_test.go
Print nonconvertible data when being unable to convert a Starlark integer to `int64`. Furthermore, document the limitation in the README of the processor.
resolves #15499
> chore(common.starlark): Print nonconvertible data

- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/path.go
- plugins/inputs/gnmi/tag_store.go
- plugins/inputs/gnmi/testcases/issue_15546/expected.out
- plugins/inputs/gnmi/testcases/issue_15546/responses.json
- plugins/inputs/gnmi/testcases/issue_15546/telegraf.conf
The current code fails to resolve aliases for cases where the subscription update contains YANG-model namespaces in path elements. This PR explicitly handles the namespace elements the right way.
resolves #15546
> fix(inputs.gnmi): Handle YANG namespaces in paths correctly

- plugins/inputs/opcua_listener/README.md
- plugins/inputs/opcua_listener/sample.conf
The rationale behind this change is to clarify that setting the subscription_interval does not guarantee the server will update at this rate. The server might reject the interval if it cannot meet the required update rate due to hardware or software limitations. These notes aim to prevent misunderstandings and guide users to refer to their server's documentation, ensuring correct system configuration.
resolves #
> docs(inputs.opcua_listener): Enhance explanation of subscription interval

- plugins/outputs/elasticsearch/README.md
- plugins/outputs/elasticsearch/elasticsearch.go
- plugins/outputs/elasticsearch/elasticsearch_test.go
- plugins/outputs/elasticsearch/sample.conf
This provides a basic way to use Telegraf with Elasticsearch's data streams feature [1]. Usually you will manage the template yourself. This follows support upstream in the elasticsearch client library. [2]
[1] https://www.elastic.co/guide/en/elasticsearch/reference/7.17/set-up-a-data-stream.html
[2] https://github.com/olivere/elastic/issues/1464
resolves #15051
> feat(outputs.elasticsearch): support data streams

- plugins/outputs/syslog/README.md
> docs(outputs.syslog): Doc syslog message format length limits

- plugins/inputs/ping/ping.go
This will check the length of the slice to avoid a crash and moves this set up to Gather and out of Init to allow continued operation.
fixes: #15591
> fix(inputs.ping): Check addr length to avoid crash

- plugins/common/socket/socket.go
- plugins/common/socket/socket_test.go
- plugins/common/socket/stream.go
Switching the socket-close implementation to context cancellation avoids the complexity to keep track of all open connection. As side effects, this PR avoids the memory leak described in #15509 and avoids race conditions when closing the socket while new connections arrive.
resolves #15509
> fix(common.socket): Switch to context to simplify closing

- tools/custom_builder/config.go
- tools/custom_builder/main.go
- tools/custom_builder/main_test.go
- tools/custom_builder/packages.go
- tools/custom_builder/testcases/issue_13592/expected.tags
- tools/custom_builder/testcases/issue_13592/telegraf.conf
- tools/custom_builder/testcases/issue_15627/expected.tags
- tools/custom_builder/testcases/issue_15627/telegraf.conf
The existing code only handles the data-format field correctly for single instances of the same plugin as we overwrite the parsers/serializers for each instance.
This PR fixes the issue and additionally restructures the code to be able to add test-cases and do so for previous issues.
resolves #15627
> fix(tools.custom_builder): Handle multiple instance of the same plugin correctly

- go.mod
- go.sum
- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/os_linux.go
- plugins/inputs/procstat/os_others.go
- plugins/inputs/procstat/os_windows.go
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/procstat/sample.conf
This PR allows to collect socket statistics per process when specifying `sockets` in the `properties` setting. Furthermore, the PR adds an `socket_protocols` option to select only a subset of socket-types to collect.
resolves #3436
> feat(inputs.procstat): Add ability to collect per-process socket statistics

- cmd/telegraf/telegraf.go
During a reload, we were not cleaning up goroutines that exist for other files being watched. A user could suddenly see multiple config file modified messages, one for every go routine that was still alive:
```sh
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Config file modified
2024-07-19T18:57:05Z I! Reloading Telegraf config
2024-07-19T18:57:05Z D! [agent] Stopping service inputs
```
> chore(agent): Clean up watch goroutines

- scripts/mac-signing.sh
This uses the correctly capitalized "Info.plist" file and avoids signing the entry script as that is done again later. See discussion in bug for additional background.
fixes: #15646
> chore(mac): Create Info.plist, avoid signing entry script

- plugins/inputs/tail/tail.go
When we try to close the tailer, tail will block until the goroutine is in a dead state. When a tailer had read more than the max undelivered this condition was never hit and we deadlocked. This ensures that when the tailer is trying to die we clear out the channel to close successfully.
This was not an issue when the max undelivered was not hit.
fixes: #15641
> fix(inputs.tail): Prevent deadlock when closing and max undelivered lines hit

- cmd/telegraf/telegraf.go
Currently, the agent will recognize when config files are deleted and then block the watcher, waiting for them to re-appear. If the file shows back up, the watcher will trigger a reload. This is not likely the intended behavior, instead a user wants to remove a configuration and have telegraf remove that configuration from the running Telegraf.
Note this only works on watched directories. If a user specifies a specific file to load and then deletes it, Telegraf will fail to start as that file is now missing.
In order to avoid any additional error messages on reload, the list of known configs needs to update as well since the file was removed. Therefore, right before the reload we go get a new list of files based on the CLI options + reading any configuration directories.
Related to …
> feat(agent): Watch for deleted files

- plugins/inputs/s7comm/README.md
- plugins/inputs/s7comm/s7comm.go
- plugins/inputs/s7comm/s7comm_test.go
Allow to specify the `startup_error_behavior` for the plugin.
resolves #15609
> feat(inputs.s7comm): Implement startup-error behavior settings

- plugins/outputs/dynatrace/README.md
- plugins/outputs/dynatrace/dynatrace.go
- plugins/outputs/dynatrace/dynatrace_test.go
- plugins/outputs/dynatrace/sample.conf
Adding support for metric to be treated and reported as a delta counter using regular expression using a new configuration variable:
```
AddCounterMetricsPatterns []string        `toml:"additional_counters_patterns"`
```
resolves #15659
> feat(outputs.dynatrace): add support for metric to be treated and reported as a delta counter using regular expression

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
- plugins/inputs/mqtt_consumer/mqtt_logger.go
In #15429, I added trace logging to the mqtt outputs for v3 and v5. I removed trace logging settings from the input, moving it to the common code. However, the input does not even use the common code *facepalm*. This restores the trace option for the input. I discovered this while testing out the new logging mechanisms.
> fix(inputs.mqtt_consumer): Restore trace logging option

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration.go
- plugins/inputs/modbus/configuration_metric.go
- plugins/inputs/modbus/configuration_metric_test.go
- plugins/inputs/modbus/configuration_register.go
- plugins/inputs/modbus/configuration_register_test.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/configuration_request_test.go
- plugins/inputs/modbus/sample_metric.conf
- plugins/inputs/modbus/sample_register.conf
- plugins/inputs/modbus/sample_request.conf
- plugins/inputs/modbus/type_conversions.go
- plugins/inputs/modbus/type_conversions_bit.go
Allow to read single bits of holding and input registers. This can be necessary if multiple bits are interlaced into a single 16-bit register value.
resolves #15416
> feat(inputs.modbus): Allow reading single bits of input and holding registers

- config/config.go
- docs/CONFIGURATION.md
- models/running_output.go
Fixes buffer directory agent level config and documents the option.
resolves #15656
> fix(agent): Fix buffer directory config and document

- config/config.go
- docs/CONFIGURATION.md
- logger.go
- logger/logger.go
- models/running_aggregator.go
- models/running_input.go
- models/running_output.go
- models/running_parsers.go
- models/running_processor.go
- models/running_serializer.go
This PR allows to override the Telegraf-wide log-level on a per plugin basis allowing to e.g. debug a certain plugin without being spammed by debug messages of other plugins.
resolves #6584
> feat(plugins): Allow to override log-level per plugin

- plugins/inputs/statsd/statsd.go
`allowed_pending_messages` is a config described as:
```
```
Currently `statsd_pending_messages` is exported which allows you to see the number of pending messages. However exporting the config value for `allowed_pending_messages` is helpful to then set up alerting on when that limit has been reached.
I'm open to changing the name of the stat away from `max_pending_messages`. I don't mind setting it to `allowed_pending_messages` but then I think I would need code similar to below to avoid the conflict in names. MaxPendingMessages to me indicates that pending messages cannot go above this value.
```go
s.AllowedPendingMessagesStat = selfstat.Register("statsd", "allowed_pending_messages", tags)
s.AllowedPendingMessagesStat.Set(int64(s.AllowedPendingMessages))
```
resolves #15686
> feat(inputs.statsd): Expose allowed_pending_messages as internal stat

- plugins/inputs/opcua/read_client.go
Rather than checking if we are only disconnected, we should also check if the connection is closed to try to reconnect.
fixes: #15693
> fix(inputs.opcua): Reconnect if closed connection

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/sample.conf
By default the non-negative, metric timestamp is used on the kafka producer message. This adds a new option to allow the producer message to instead use the current time, set by the library when not set.
fixes: #15675
> feat(outputs.kafka): Option to set producer message timestamp

- plugins/inputs/elasticsearch/README.md
- plugins/inputs/elasticsearch/elasticsearch.go
- plugins/inputs/elasticsearch/elasticsearch_test.go
- plugins/inputs/elasticsearch/sample.conf
- plugins/inputs/elasticsearch/testdata_test.go
Introduces a new option to collect from another endpoint.
fixes: #15685
> feat(inptus.elasticsearch): Gather enrich stats

- docs/CONFIGURATION.md
- logger.go
- logger/logger.go
- logger/stdlog_redirector.go
- plugins/common/kafka/logger.go
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/sample_general_begin.conf
- plugins/inputs/netflow/README.md
- plugins/inputs/netflow/netflow.go
- plugins/inputs/netflow/sample.conf
- plugins/inputs/s7comm/README.md
- plugins/inputs/s7comm/s7comm.go
- plugins/inputs/s7comm/sample.conf
- plugins/inputs/upsd/README.md
- plugins/inputs/upsd/sample.conf
- plugins/inputs/upsd/upsd.go
- plugins/outputs/kafka/kafka.go
- plugins/outputs/postgresql/postgresql_test.go
- plugins/parsers/xpath/README.md
- plugins/parsers/xpath/parser.go
- testutil/capturelog.go
- testutil/log.go
Add a `trace` log-level below the existing `debug` one to be able to trace plugin internal messages such as connection debugging etc potentially producing large amounts of messages. Please note, currently there is no means to enable this on an agent-wide scale. This is intentionally!
The PR furthermore, converts several plugins to use the new log-level instead of home-brewed settings.
> feat(logging): Add 'trace' log-level

- docs/INPUTS.md
- docs/METRICS.md
- plugins/common/shim/goshim.go
- This PR enables external plugins to use metric tracking within their isolated environment
resolves #15572
> feat(common.shim): Enable metric tracking within external plugins

- plugins/common/cookie/cookie.go
- plugins/common/cookie/cookie_test.go
- plugins/inputs/http/README.md
- plugins/outputs/http/README.md
common.cookie does not support secretstores, it may be required to send header values based on secretstores
resolves https://github.com/influxdata/telegraf/issues/15639
> feat(common.cookie): Allow usage of secrets for header

- plugins/parsers/value/README.md
- plugins/parsers/value/parser.go
- plugins/parsers/value/parser_test.go
Introduce data type to encode raw data as base64 to allow for further parsing down the line.
fixes: #15694
> feat(parsers.value): Add base64 datatype

- plugins/outputs/datadog/README.md
- plugins/outputs/datadog/datadog.go
- plugins/outputs/datadog/datadog_test.go
- plugins/outputs/datadog/sample.conf
Telegraf's outputs.datadog plugin is incompatible with submitting statsd metrics alongside the Datadog agent, as the dd-agent submits counter metrics as rates instead. Telegraf does not do this in order to reflect raw data more accurately. See #10979 for that change.
This PR enables a new config `should_rate_counts` which will convert count metrics to rates via the defined `rate_interval` (defaults to 10s - the same default as the Datadog agent) if those metrics are eligible. See below for eligibility.
- Counts
- [Source](https://docs.datadoghq.com/metrics/types/?tab=count#definition)
- [Logic](https://github.com/DataDog/datadog-agent/blob/main/pkg/metrics/counter.go#L42-L43)
- rate
- Histogram
- [Source](https://docs.datadoghq.com/metrics/types/?tab=histogram#definition)
- [Logic]( …
> feat(outputs.datadog): Add support for submitting alongside dd-agent

- plugins/inputs/chrony/README.md
- plugins/inputs/chrony/chrony.go
- plugins/inputs/chrony/sample.conf
We must use the DGRAM type when connecting to the chrony socket. On top of that, the socket must be duplicated in order to allow concurrent calls to it.
resolves #15549
> fix(inputs.chrony): Use DGRAM for the unix socket

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/sample.conf
Adds metric name as kafka record header. Allows checking metric name before consumer will deserialize record.
resolves #15721
> feat(outputs.kafka): Option to add metric name as record header

- plugins/serializers/template/template.go
Allow serialization with a template even if a metric is a TrackingMetric - which can happen with many inputs (e.g. MQTT). The template *processor* already accounts for this, the template *serializer* does not yet have this check & handling. This PR just adds the same behavior for the serializer as well. As the change is local to the method, I would not expect side effects.
resolves #15739
> fix(serializers.template): Unwrap metrics if required

- agent/agent.go
- cmd/telegraf/cmd_config.go
- cmd/telegraf/main.go
This PR adds a `telegraf config check` sub-command to check if the configuration is valid and can be successfully parsed. All plugins are initialized to validate options but are **NOT** started or executed. The sub-command will exit with a non-zero error code if an error occurs and with a zero error-code otherwise.
resolves #15726
> feat(agent): Add config check sub-command

- plugins/inputs/mysql/README.md
- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/sample.conf
Add replica status command when collect mysql
resolves #15748
> feat(inputs.mysql): Add support for replica status

- plugins/outputs/zabbix/zabbix_test.go
This is only the first part of a larger effort to address the findings identified by `testifylint: go-require`: https://github.com/influxdata/telegraf/issues/15535
In this PR, I'm focusing on just one test file: `zabbix_test.go`, to start a discussion on whether this approach to fixing `go-require` issues works for us.
```
plugins/outputs/zabbix/zabbix_test.go:478:17  testifylint  go-require: listenForZabbixMetric contains assertions that must only be used in the goroutine running the test function
plugins/outputs/zabbix/zabbix_test.go:489:6   testifylint  go-require: require must only be used in the goroutine running the test function …
```
> chore(linters): Fix findings found by `testifylint`: `go-require` for `zabbix`

- plugins/inputs/kinesis_consumer/kinesis_consumer.go
Passing endpoint from config to input kinesis plugin
Otherwise running locally in docker-compose it cannot connect to kinesis
resolves #
> fix(inputs.kinesis_consumer): Honor the configured endpoint

- plugins/outputs/kinesis/kinesis.go
When trying to run telegraf locally in docker-compose and trying to connect to localstack kinesis, it tries to call public aws url instead of one in the config
resolves #
> fix(outputs.kinesis): Honor the configured endpoint

- plugins/outputs/syslog/README.md
- plugins/outputs/syslog/syslog.go
- plugins/outputs/syslog/syslog_test.go
Allow to set the startup error behavior for the plugin
resolves #15770
> feat(outputs.syslog): Implement startup error behavior options

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
This PR adds a new `timestamp_source` setting allowing to use the "inner" or "outer" timestamp of the Kafka message as metric timestamp.
resolves #15783
> feat(inputs.kafka_consumer): Allow to select the metric time source

- logger/stdlog_redirector.go
When introducing the `trace` log-level the standard logger has been forgotten. This PR handles the trace log-level correctly when using golang's standard `log` facility.
> fix(logger): Handle trace level for standard log

- .golangci.yml
- plugins/inputs/kube_inventory/client_test.go
- plugins/secretstores/docker/docker_test.go
Fixes following findings:
```
plugins/inputs/kube_inventory/client_test.go:32:2  testifylint  formatter: require.Errorf call has arguments but no formatting directives
plugins/secretstores/docker/docker_test.go:25:2    testifylint  formatter: require.ErrorContainsf does not support error-wrapping directive %w
```
Enables following checkers:
> test(linters): Enable `testifylint`: `formatter`, `suite-broken-parallel` and `suite-subtest-run`

- plugins/inputs/mqtt_consumer/mqtt_consumer.go
The context:
switching parser from "json" to "json_v2" is not equivalent.
Not sure if this is expected behavior or not.
In my config I have only
```
data_format = "json"
```
If I switch it to 
```
data_format = "json_v2"
```
then Telegraf **just stops working and not printing any output**. 
It is very confusing, even though it may be expected.
What happens in that case that as I don't have any parser configuration for json_v2, parser does not produce any metric.
It is fine except that the message is being printed only once and also with DEBUG level.
So you would never see it on production.
I'm not sure if it is possible or even worth making json and json_v2 equivalent or not.
But at least we need to print the message more loudly.
Thus changing it to WARN.
Also could be nice to include …
> chore(inputs.mqtt): Increase log-level to warning if no message is created by parser

- go.mod
- go.sum
https://github.com/showwin/speedtest-go/commit/332a0d73ab71db4e4246ffd478ffdec329a785c1 fix: data races  
https://github.com/showwin/speedtest-go/commit/96bd45ad30880720fc77351dc15f86f711929c72 fix: keepalive state broken  
resolves #11449
> chore(deps): Bump github.com/showwin/speedtest-go from 1.7.7 to 1.7.9

- internal/snmp/translator_gosmi.go
There is an upstream PR to resolve an issue when a nil value is passed. However that PR has not been looked at or merged. As such, this attempts to catch that scenario in Telegraf first.
See: https://github.com/sleepinggenius2/gosmi/pull/45
fixes: #15200
> fix(inputs.snmp): Avoid sending a nil to gosmi's GetEnumBitsFormatted

- plugins/processors/aws_ec2/README.md
- plugins/processors/aws_ec2/ec2.go
- plugins/processors/aws_ec2/ec2_test.go
- plugins/processors/aws_ec2/sample.conf
Allow to use instance metadata to annotate metrics according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html.
resolves #15789
> feat(processors.aws_ec2): Allow to use instance metadata

- plugins/inputs/mysql/v2/convert.go
Avoid type conflicts by pinning more Galera fields to float.
resolves #15786
> fix(inputs.mysql): Enforce float for all known floating-point information

- plugins/inputs/execd/README.md
- plugins/inputs/execd/execd.go
- plugins/inputs/execd/execd_test.go
- testutil/capturelog.go
Enable more differentiated logging in external plugins by allowing to provide logging indicators and reflecting those levels in the actual logging on Telegraf side. The PR is backward compatible if no indicator is provided.
resolves #9487
> feat(inputs.execd): Allow to provide logging prefixes on stderr

- .circleci/config.yml
- .golangci.yml
- Makefile
- `golangci-lint` bumped to `v1.61.0`
- Matching the configuration file to the example from https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml.
> chore(deps): Bump golangci-lint from v1.60.3 to v1.61.0

- plugins/outputs/application_insights/application_insights_test.go
- plugins/outputs/application_insights/transmitter.go
- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/azure_monitor/azure_monitor.go
- plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/outputs/cloudwatch/cloudwatch.go
- plugins/outputs/cratedb/cratedb.go
- plugins/outputs/datadog/datadog.go
- plugins/outputs/exec/exec.go
- plugins/outputs/exec/exec_test.go
- plugins/outputs/graylog/graylog.go
- plugins/outputs/librato/librato.go
- plugins/outputs/mqtt/topic_name_generator.go
- plugins/outputs/parquet/parquet.go
- plugins/outputs/postgresql/sqltemplate/template.go
- plugins/outputs/postgresql/table_manager.go
- plugins/outputs/prometheus_client/v1/collector.go
- plugins/outputs/prometheus_client/v2/collector.go
- plugins/outputs/riemann/riemann.go
- plugins/outputs/signalfx/signalfx.go
- plugins/outputs/stackdriver/stackdriver.go
- plugins/outputs/syslog/syslog_mapper.go
- plugins/outputs/timestream/timestream_test.go
- plugins/outputs/zabbix/autoregister_test.go
- plugins/outputs/zabbix/zabbix_test.go
- plugins/parsers/avro/schema_registry.go
- plugins/parsers/influx/escape.go
- plugins/parsers/influx/handler.go
- plugins/parsers/json/json_flattener.go
Address findings for [revive:enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) in `plugins/outputs` and `plugins/parsers`
As we agreed here https://github.com/influxdata/telegraf/issues/15811, we will fix the errors found by the following configuration:
```
- name: enforce-repeated-arg-type-style
arguments: ["short"]
```
After all findings of this type in whole project are handled, we can enable `revive:enforce-repeated-arg-type-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/outputs` and `plugins/parsers`

- cmd/telegraf/printer.go
- Aligns the plugin deprecation messages with the plugin description.
- Skips the printing of `http_listener` input as that would result in having sample config printed for `inputs.influxdb_listener` twice, once with a very confusing deprecation message.
```diff
-#  ## DEPRECATED: The "aerospike" plugin is deprecated in version 1.30.0 and will be removed in 1.40.0, use 'inputs.prometheus' with the Aerospike Prometheus Exporter instead.
+# ## DEPRECATED: The "aerospike" plugin is deprecated in version 1.30.0 and will be removed in 1.40.0, use 'inputs.prometheus' with the Aerospike Prometheus Exporter instead.
```
> chore(cmd): Align plugin deprecation messages

- plugins/inputs/activemq/activemq.go
- plugins/inputs/activemq/activemq_test.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription_test.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_test.go
- plugins/inputs/dcos/client.go
- plugins/inputs/dcos/client_test.go
- plugins/inputs/dcos/creds.go
- plugins/inputs/dcos/dcos.go
- plugins/inputs/dcos/dcos_test.go
- plugins/inputs/graylog/graylog.go
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/kubernetes/kubernetes_metrics.go
- plugins/inputs/logstash/logstash.go
- plugins/inputs/logstash/logstash_test.go
- plugins/inputs/mailchimp/chimp_api.go
- plugins/inputs/mailchimp/mailchimp.go
- plugins/inputs/mailchimp/mailchimp_test.go
- plugins/inputs/mongodb/mongodb_data.go
- plugins/inputs/mongodb/mongodb_data_test.go
- plugins/inputs/mongodb/mongodb_server.go
- plugins/inputs/mongodb/mongostat.go
- plugins/inputs/mongodb/mongostat_test.go
- plugins/inputs/monit/monit.go
Address following findings for [revive:max-public-structs](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-public-structs) in `plugins/inputs/[a-g]*`:
```
plugins/inputs/activemq/activemq.go:2:1                                revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription.go:1:1     revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/dcos/client.go:1:1                                      revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/graylog/graylog.go:2:1                                  revive  max-public-structs: you have exceeded the …
```
> chore: Fix linter findings for `revive:max-public-structs` in `plugins/inputs/[a-n]*`

- plugins/inputs/openweathermap/openweathermap.go
- plugins/inputs/phpfpm/fcgi.go
- plugins/inputs/phpfpm/fcgi_client.go
- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/ping/ping_notwindows.go
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/proxmox_test.go
- plugins/inputs/redis/redis.go
- plugins/inputs/redis_sentinel/redis_sentinel.go
- plugins/inputs/redis_sentinel/redis_sentinel_test.go
- plugins/inputs/sflow/sflow.go
- plugins/inputs/smart/smart.go
- plugins/inputs/smartctl/smartctl_device.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
- plugins/inputs/socketstat/socketstat.go
- plugins/inputs/sqlserver/connectionstring.go
- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/statsd/datadog.go
- plugins/inputs/statsd/statsd.go
- plugins/inputs/sysstat/sysstat.go
- plugins/inputs/system/mock_PS.go
- plugins/inputs/system/ps.go
- plugins/inputs/vsphere/client.go
- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/tscache.go
- plugins/inputs/vsphere/vsan.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go
- plugins/inputs/webhooks/github/github_webhooks_test.go
- plugins/inputs/webhooks/papertrail/papertrail_test.go
Address findings for [revive:enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) in `plugins/inputs/[o-z]*`
As we agreed here https://github.com/influxdata/telegraf/issues/15811, we will fix the errors found by the following configuration:
```
- name: enforce-repeated-arg-type-style
arguments: ["short"]
```
After all findings of this type in whole project are handled, we can enable `revive:enforce-repeated-arg-type-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[o-z]*`

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
This PR allows to use secret-store secrets for the `username`, `password` and `bearer_token_string` settings.
resolves #15855
> feat(inputs.prometheus): Allow to use secrets for credentials

- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/hugepages/hugepages.go
- plugins/inputs/infiniband/infiniband_linux.go
- plugins/inputs/influxdb_listener/influxdb_listener_test.go
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go
- plugins/inputs/intel_pmt/intel_pmt.go
- plugins/inputs/intel_pmt/intel_pmt_test.go
- plugins/inputs/intel_pmt/xml_parser.go
- plugins/inputs/intel_pmu/config.go
- plugins/inputs/intel_pmu/intel_pmu.go
- plugins/inputs/intel_pmu/intel_pmu_test.go
- plugins/inputs/intel_pmu/resolver.go
- plugins/inputs/intel_powerstat/intel_powerstat.go
- plugins/inputs/intel_rdt/intel_rdt.go
- plugins/inputs/ipmi_sensor/ipmi_sensor.go
- plugins/inputs/jenkins/client.go
- plugins/inputs/knx_listener/knx_listener_test.go
- plugins/inputs/kube_inventory/client.go
- plugins/inputs/leofs/leofs_test.go
- plugins/inputs/mcrouter/mcrouter.go
- plugins/inputs/mongodb/mongodb_server.go
- plugins/inputs/mongodb/mongostat.go
- plugins/inputs/mqtt_consumer/topic_parser.go
- plugins/inputs/mysql/mysql.go
- plugins/inputs/nfsclient/nfsclient.go
- plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go
- plugins/inputs/nsd/nsd.go
Address findings for [revive:enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) in `plugins/inputs/[h-n]*`
As we agreed here https://github.com/influxdata/telegraf/issues/15811, we will fix the errors found by the following configuration:
```
- name: enforce-repeated-arg-type-style
arguments: ["short"]
```
After all findings of this type in whole project are handled, we can enable `revive:enforce-repeated-arg-type-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[h-n]*`

- plugins/inputs/aerospike/aerospike.go
- plugins/inputs/aerospike/aerospike_test.go
- plugins/inputs/aliyuncms/aliyuncms.go
- plugins/inputs/azure_monitor/azure_monitor.go
- plugins/inputs/azure_monitor/azure_monitor_test.go
- plugins/inputs/beanstalkd/beanstalkd_test.go
- plugins/inputs/bond/bond.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
- plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go
- plugins/inputs/couchbase/couchbase.go
- plugins/inputs/cpu/cpu_test.go
- plugins/inputs/dcos/client.go
- plugins/inputs/directory_monitor/directory_monitor.go
- plugins/inputs/dns_query/dns_query.go
- plugins/inputs/docker/docker.go
- plugins/inputs/docker/stats_helpers.go
- plugins/inputs/dovecot/dovecot.go
- plugins/inputs/dpdk/dpdk_utils.go
- plugins/inputs/ecs/ecs.go
- plugins/inputs/elasticsearch_query/aggregation_parser.go
- plugins/inputs/elasticsearch_query/aggregation_query.go
- plugins/inputs/exec/exec_test.go
- plugins/inputs/execd/shim/shim_test.go
- plugins/inputs/fibaro/hc2/parser.go
- plugins/inputs/fibaro/hc3/parser.go
- plugins/inputs/filecount/filecount_test.go
- plugins/inputs/github/github.go
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/google_cloud_storage/google_cloud_storage_test.go
- plugins/inputs/graylog/graylog.go
Address findings for [revive:enforce-repeated-arg-type-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style) in `plugins/inputs/[a-g]*`
As we agreed here https://github.com/influxdata/telegraf/issues/15811, we will fix the errors found by the following configuration:
```
- name: enforce-repeated-arg-type-style
arguments: ["short"]
```
After all findings of this type in whole project are handled, we can enable `revive:enforce-repeated-arg-type-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[a-g]*`

- testutil/metric.go
One of my tests failed, but it was because the comparison function for test cmp opts didn't work properly
resolves #15885
> test(testutil): Fix value comparison

- plugins/inputs/nginx_plus/nginx_plus.go
- plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
- plugins/inputs/nginx_plus_api/nginx_plus_api_types.go
- plugins/inputs/nomad/nomad.go
- plugins/inputs/nomad/nomad_metrics.go
- plugins/inputs/nsq/nsq.go
- plugins/inputs/nvidia_smi/schema_v11/types.go
- plugins/inputs/opensearch_query/aggregation.response.go
- plugins/inputs/opensearch_query/opensearch_query.go
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/structs.go
- plugins/inputs/rabbitmq/rabbitmq.go
- plugins/inputs/redfish/redfish.go
- plugins/inputs/rethinkdb/rethinkdb_data.go
- plugins/inputs/rethinkdb/rethinkdb_data_test.go
- plugins/inputs/sflow/decoder_test.go
- plugins/inputs/sflow/metricencoder.go
- plugins/inputs/sflow/packetdecoder.go
- plugins/inputs/sflow/packetdecoder_test.go
- plugins/inputs/sflow/sflow.go
- plugins/inputs/sflow/types.go
- plugins/inputs/sflow/types_test.go
- plugins/inputs/solr/api.go
- plugins/inputs/solr/solr.go
- plugins/inputs/solr/types.go
- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/stackdriver/stackdriver_test.go
Address following findings for [revive:max-public-structs](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-public-structs) in `plugins/inputs/[n-s]*`:
```
plugins/inputs/nginx_plus/nginx_plus.go:2:1                            revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/nginx_plus_api/nginx_plus_api_types.go:1:1              revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/nomad/nomad_metrics.go:1:1                              revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/nsq/nsq.go:24:1                                         revive  max-public-structs: you have exceeded the …
```
> chore: Fix linter findings for revive:max-public-structs in plugins/inputs/[n-s]*

- plugins/inputs/tomcat/tomcat.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go
- plugins/inputs/webhooks/github/github_webhooks.go
- plugins/inputs/webhooks/github/github_webhooks_models.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks_events.go
- plugins/inputs/win_eventlog/event.go
- plugins/inputs/win_perf_counters/pdh.go
- plugins/inputs/win_perf_counters/pdh_386.go
- plugins/inputs/win_perf_counters/pdh_amd64.go
- plugins/inputs/win_perf_counters/pdh_arm64.go
- plugins/inputs/win_perf_counters/performance_query.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_test.go
- plugins/inputs/win_services/win_services.go
- plugins/inputs/win_services/win_services_integration_test.go
- plugins/inputs/xtremio/xtremio.go
- plugins/inputs/xtremio/xtremio_types.go
- plugins/inputs/zipkin/codec/codec.go
- plugins/inputs/zipkin/codec/codec_test.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/prometheus_client/v1/collector.go
- plugins/outputs/sensu/sensu.go
- plugins/outputs/sensu/sensu_test.go
- plugins/parsers/json_v2/parser.go
- plugins/parsers/wavefront/element.go
- plugins/parsers/wavefront/parser.go
- plugins/serializers/prometheus/collection.go
Address following findings for [revive:max-public-structs](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-public-structs) in `plugins/inputs/[t-z]*` and rest:
```
plugins/inputs/tomcat/tomcat.go:2:1                                    revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go:1:1  revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/webhooks/github/github_webhooks_models.go:1:1           revive  max-public-structs: you have exceeded the maximum number of public struct declarations
plugins/inputs/webhooks/rollbar/rollbar_webhooks_events.go:1:1         revive  max-public-structs: you have …
```
> chore: Fix linter findings for revive:max-public-structs in plugins/inputs/[t-z]* and rest

- plugins/outputs/instrumental/instrumental_test.go
- plugins/parsers/influx/influx_upstream/parser_test.go
- plugins/parsers/influx/parser_test.go
- plugins/processors/ifname/ifname_test.go
- plugins/processors/reverse_dns/rdnscache_test.go
This is only the first part of a larger effort to address the findings identified by `testifylint: go-require`: https://github.com/influxdata/telegraf/issues/15535
In this PR, I’m focusing on parser/processors tests and `instrumental_test.go`. While fixing the parser/processors tests is quite straightforward, it seems that the approach to testing the simulation of the TCP Server's response in a separate goroutine requires discussion – because there are quite a few such tests in Telegraf’s test code, and it would be great to have a consistent approach in future PRs.
```
plugins/outputs/instrumental/instrumental_test.go:92:3        testifylint …
```
> chore(linters): Fix findings found by `testifylint`: `go-require` for`instrumental` and parsers/processors

- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
- plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
- plugins/outputs/cratedb/cratedb.go
- plugins/outputs/elasticsearch/elasticsearch.go
- plugins/outputs/graphite/graphite_test.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/iotdb/iotdb_test.go
- plugins/outputs/mongodb/mongodb.go
- plugins/outputs/newrelic/newrelic.go
- plugins/outputs/postgresql/postgresql.go
- plugins/outputs/socket_writer/socket_writer.go
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
- plugins/outputs/syslog/syslog_mapper.go
- plugins/outputs/timestream/timestream_test.go
Address findings for [revive:comment-spacings](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#comment-spacings) in:
```
- plugins/outputs/...
```
It is only part of the bigger job (for issue: https://github.com/influxdata/telegraf/issues/15806).
After all findings of this type in whole project are handled, we can enable `revive:comment-spacings` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:comment-spacings` (part 3)

- plugins/common/http/config.go
The HTTP client created by httpconfig loses Timeout configuration when oauth is enabled. More information on issue #15899 
This is the fix with the least moving parts I could come up with.  
For the future it's probably advisable to have oauth config return a properly wrapped client instead of a new client; or having a mechanism to keep the configuration of the original client.
resolves #15899
> fix(common.http): Keep timeout after creating oauth client

- go.mod
- go.sum
OK, fixing this https://github.com/influxdata/telegraf/issues/13853
Specifically https://github.com/influxdata/telegraf/issues/13853#issuecomment-2269938413
There are a few issues:
1) the library [kinesis-consumer](https://github.com/harlow/kinesis-consumer) seem to be abandoned :(
2) recently (and it coincided with the switch to AWS SDK v2) 2 bugs were introduced into the library: https://github.com/harlow/kinesis-consumer/issues/158 and https://github.com/harlow/kinesis-consumer/issues/152
Here are the PRs https://github.com/harlow/kinesis-consumer/pull/159 (from Jun 12 2024, not reviewed, not accepted) and https://github.com/harlow/kinesis-consumer/pull/161 (from 16 Sept 2024)
Solution:
Unfortunately, I don't know how to handle the case with unmaintained library.
For now I made a …
> chore(deps): Bump github.com/harlow/kinesis-consumer from v0.3.6-0.20240606153816-553e2392fdf3 to v0.3.6-0.20240916192723-43900507c911

- CHANGELOG.md
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
This PR NACKs messages that cannot be parsed or processed otherwise, keeping the rejection in delivery failure cases. Messages are not requeued in both cases. Furthermore, a small notice is added to the README on how the marking works.
resolves #15741
> fix(inputs.amqp_consumer): NACKing messages on non-delivery related errors

- .golangci.yml
> chore(linters): Enable `comment-spacings` rule for revive

- plugins/inputs/consul/consul.go
- plugins/inputs/consul/consul_test.go
In order to align all plugins, the config checking and initialisation should happen in Init.
> fix(inputs.consul): Move config checking to Init method

- plugins/parsers/avro/schema_registry.go
If you have a large number of topics, you will eventually get in a place where telegraf crashes on startup by trying to read and write the schema map at the same time.
This fixes that issue by protecting read and write access to the schema map with a mutex.
resolves #15920
> fix(parsers.avro): Add mutex to cache access

- plugins/processors/all/batch.go
- plugins/processors/batch/README.md
- plugins/processors/batch/batch.go
- plugins/processors/batch/batch_test.go
- plugins/processors/batch/sample.conf
This new processor can distribute metrics across batches by adding a tag indicating what batch number it is in. This makes it possible to distribute the load of a high number of metrics across multiple instances of the same output plugin.
resolves #15621
resolves #11707
> feat(processors.batch): Add batch processor

- config/deprecation.go
- config/deprecation_test.go
Some plugin options do not have a removal version set causing the log message being malformed.
> Option "option" of plugin "test" deprecated since version 1.23.0 and will be removed in : please check
> Option "option" of plugin "test" deprecated since version 1.23.0 and will be removed in 2.0.0: please check
> fix(config): Correctly print removal version info

- plugins/inputs/vsphere/vsan.go
- plugins/inputs/vsphere/vsphere_test.go
Some VSAN metrics e.g. "vsan-esa-disk-layer" and "vsan-esa-disk-scsifw" are missing "hostname" and "devicename" tags.
Fixes: https://github.com/influxdata/telegraf/issues/15938
> fix(inputs.vsphere): Add tags to VSAN ESA disks

- internal/snmp/field.go
- internal/snmp/testdata/gosmi/server
- internal/snmp/testdata/gosmi/tableMib
- internal/snmp/translator.go
- internal/snmp/translator_gosmi.go
- internal/snmp/translator_gosmi_test.go
- internal/snmp/translator_netsnmp.go
- plugins/inputs/snmp/README.md
- plugins/inputs/snmp/snmp_test.go
- plugins/processors/snmp_lookup/README.md
- plugins/processors/snmp_lookup/sample.conf
Add option to format the returned value from SNMP according to the [textual convention](https://www.rfc-editor.org/rfc/rfc2579) from the MIB, for example the `DateAndTime`. The return type for this field will then be `string`.
> feat(inputs.snmp): Add displayhint conversion

- agent/agent.go
- models/running_output.go
- plugins/inputs/cloud_pubsub_push/cloud_pubsub_push_test.go
This PR makes sure that an output plugin will really select a metric for outputting, before copying it. This improvement had a big impact on runtime/gc time in real world performance. After this change the amount of gc time went down from 55% of the CPU time to 25%. 
In our real world case every output plugin was only interested in a subset of the metric and there was no overlap between the subsets. This means that (x-1)/x% of all the copied metrics were immediately discarded, where x is the number of outputs.
resolves #15882
> feat(outputs): Only copy metric if its not filtered out

- plugins/outputs/remotefile/README.md
- plugins/outputs/remotefile/remotefile.go
- plugins/outputs/remotefile/sample.conf
Remove the `trace` setting in favor of the new Trace log-level.
> chore(outputs.remotefile): Deprecate trace option

- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
Fixes the alignment of `dn` tags with their corresponding fields for telemetry paths on NXOS where `query-target=subtree`. 
resolves https://github.com/influxdata/telegraf/issues/15922
> fix(inputs.cisco_telemetry_mdt): Handle NXOS DME subtree telemetry format

- plugins/common/socket/socket_test.go
Avoid flaky mem-leak test for sockets.
> test(common.socket): Increase margin for memleak test to avoid flaky tests

- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/testdata/postgres/expected.sql
The Postgres integration test fails due to a different set of options being dumped compared to the reference. Fix the issue by removing all `SET` statements from the comparison as we are only interested in the data.
> test(outputs.sql): Fix failing integration test by excluding options

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
Allow to set the startup error behavior for the plugin
> feat(inputs.kafka_consumer): Implement startup error behavior options

- plugins/inputs/diskio/README.md
- plugins/inputs/diskio/diskio.go
- plugins/inputs/diskio/diskio_test.go
In practical scenarios, it may be necessary to check the values for disk I/O wait, I/O util, and I/O svctm. 
Therefore, I would like to add these three metrics.
> feat(inputs.diskio): Add field io await and util

- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
- plugins/inputs/nvidia_smi/sample.conf
There are some cases where the nvidia-smi plugin might be found in PATH and executable, but upon running it might always return a non-zero exit code. For various reasons, in the environment I work in, this might be expected. It's thus disruptive for system logs to be polluted with infinite error messages. It's preferable in this situation to check if nvidia-smi returns a good result on plugin startup, and if not, allow the error to be bubbled up and handled according to `startup_error_behavior`.
resolves #15915
> feat(inputs.nvidia-smi): Add `probe_on_startup` option

- plugins/processors/aws_ec2/ec2.go
Currently, tags added by the AWS EC2 processor with "metadata" contain a leading slash. This PR fixes this issue and avoids a panic when running Telegraf with ` --test`.
resolves #15906
> fix(processors.aws_ec2): Remove leading slash and cancel worker only if it exists

- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
> fix(inputs.influxdb_v2_listener): Fix concurrent read/write dict

- plugins/inputs/postgresql/postgresql_test.go
Fixing `inputs/postgresql` integration tests (example of fail: https://app.circleci.com/pipelines/github/influxdata/telegraf/22959/workflows/69cf611d-5609-4131-80c1-0c3c3d96c07c/jobs/357709)
The plugin by default queries two statistics tables: `pg_stat_bgwriter` and `pg_stat_database`. 
Some time ago, `buffers_backend` and `buffers_backend_fsync` were removed from the `pg_stat_bgwriter` table: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=74604a37f;ds=sidebyside
And some columns from this table were moved to the `pg_stat_checkpointer` table, and their names were changed: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=96f052613f35d07d001c8dd2f284ca8d95f82d1b;ds=sidebyside
In this PR, I'm removing the check for whether values from columns that no …
> test(inputs.postgresql): Fixing integration test

- models/buffer_disk.go
- models/buffer_suite_test.go
Fixes an issue where the disk buffer would not always flush if the buffer was emptied entirely by a metric batch
resolves #15868
> fix(agent): Fix buffer not flushing if all metrics are written

- plugins/inputs/mock/README.md
- plugins/inputs/mock/mock.go
- plugins/inputs/mock/sample.conf
Add a phase to the sine mock, so multiple signals can be mocked which are slightly out of phase.
resolves #
> feat(inputs.mock): Add sine phase

- plugins/common/proxy/socks5_test.go
- plugins/common/shim/goshim_test.go
- plugins/common/shim/input_test.go
- plugins/common/shim/output_test.go
- plugins/common/shim/processor_test.go
- plugins/inputs/apcupsd/apcupsd_test.go
- plugins/inputs/chrony/chrony_test.go
- plugins/inputs/dovecot/dovecot_test.go
- plugins/inputs/dpdk/dpdk_test.go
- plugins/inputs/execd/shim/shim_posix_test.go
- plugins/inputs/execd/shim/shim_test.go
- plugins/inputs/gnmi/gnmi_test.go
- plugins/inputs/hddtemp/go-hddtemp/hddtemp_test.go
- plugins/inputs/intel_dlb/intel_dlb_test.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/net_response/net_response_test.go
- plugins/inputs/radius/radius_test.go
- plugins/inputs/statsd/statsd_test.go
- plugins/inputs/teamspeak/teamspeak_test.go
- plugins/inputs/x509_cert/x509_cert_test.go
This is only the first part of a larger effort to address the findings identified by `testifylint: go-require`: https://github.com/influxdata/telegraf/issues/15535
In this PR, I’m focusing on `plugins/common` and `plugins/inputs`.
```
plugins/common/proxy/socks5_test.go:35:14                   testifylint  go-require: require must only be used in the goroutine running the test function
plugins/common/shim/goshim_test.go:54:3                     testifylint  go-require: require must only be used in the goroutine running the test function
plugins/common/shim/input_test.go:51:3                      testifylint  go-require: require must only be …
```
> chore(linters): Fix findings found by `testifylint`: `go-require` for `plugins/common` and `plugins/inputs`

- config/config.go
- docs/CONFIGURATION.md
- models/running_input.go
- models/running_input_test.go
Adds the option to set the timestamp to when gathering started/ended
Discussed in #15891
> feat(inputs): Add option to choose the metric time source

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update go to v1.23.2. Still requires the CI to be built and pushed, which is why this is a draft PR still.
resolves #15977
> chore: Update go to v1.23.2

- plugins/outputs/file/file_test.go
- plugins/outputs/graphite/graphite_test.go
- plugins/outputs/graylog/graylog_test_linux.go
- plugins/outputs/opentelemetry/opentelemetry_test.go
- plugins/outputs/postgresql/postgresql_bench_test.go
- plugins/outputs/postgresql/postgresql_test.go
- plugins/outputs/postgresql/table_manager_test.go
- plugins/outputs/postgresql/table_source_test.go
This is only the first part of a larger effort to address the findings identified by `testifylint: go-require`: https://github.com/influxdata/telegraf/issues/15535
In this PR, I’m focusing on `plugins/outputs`.
```
plugins/outputs/file/file_test.go:269:3                     testifylint  go-require: require must only be used in the goroutine running the test function
plugins/outputs/graphite/graphite_test.go:83:3              testifylint  go-require: require must only be used in the goroutine running the test function
plugins/outputs/graphite/graphite_test.go:87:3              testifylint  go-require: require must only be used in the …
```
> chore(linters): Fix findings found by `testifylint`: `go-require` for `plugins/outputs`

- plugins/common/socket/datagram.go
- plugins/common/socket/socket.go
- plugins/common/socket/socket_test.go
- plugins/common/socket/stream.go
- plugins/inputs/socket_listener/socket_listener.go
- plugins/inputs/syslog/syslog.go
Because #15891 causes processing to take place asynchronously, the timestamps might be late by tens of milliseconds. This PR registers the time right after the buffer is read and passes it on to the processing function.
resolves
> feat(inputs.socket_listener): Use reception time as timestamp

- config/config.go
- parser.go
- plugins/outputs/remotefile/README.md
- plugins/outputs/remotefile/remotefile.go
- plugins/outputs/remotefile/remotefile_test.go
- plugins/outputs/remotefile/sample.conf
- serializer.go
Some serializers require a new instance per output stream such as CSV. This PR adds the framework to pass a creator function to plugins if they need it and converts the remotefile output to the new code.
resolves #15912
> fix(outputs.remotefile): Create a new serializer instance per output file

- plugins/inputs/ceph/ceph.go
- plugins/inputs/chrony/chrony.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
- plugins/inputs/clickhouse/clickhouse.go
- plugins/inputs/cloud_pubsub/cloud_pubsub.go
- plugins/inputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/inputs/cloud_pubsub/subscription_stub.go
- plugins/inputs/cloud_pubsub_push/cloud_pubsub_push.go
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
- plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams.go
- plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go
- plugins/inputs/conntrack/conntrack.go
- plugins/inputs/conntrack/conntrack_notlinux.go
- plugins/inputs/consul/consul.go
- plugins/inputs/consul/consul_test.go
- plugins/inputs/consul_agent/consul_agent.go
- plugins/inputs/consul_agent/consul_structs.go
- plugins/inputs/couchbase/couchbase.go
- plugins/inputs/couchbase/couchbase_data.go
- plugins/inputs/couchbase/couchbase_test.go
- plugins/inputs/couchdb/couchdb.go
- plugins/inputs/cpu/cpu.go
- plugins/inputs/cpu/cpu_test.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/c*`.
As part of this effort for files from `plugins/inputs/c*`, the following actions were taken:
- All remaining exported types were given comments in the appropriate form – this does not apply to exported methods that implement "known" plugin interfaces (`Gather|Init|Start|Stop|SampleConfig|Parse|Add|Apply|Serialize|SerializeBatch|SetParser`).
It is only part of the bigger job (for issue: …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/c*`

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/conntrack/conntrack_test.go
- plugins/inputs/cpu/cpu.go
- plugins/inputs/cpu/cpu_test.go
- plugins/inputs/disk/disk.go
- plugins/inputs/disk/disk_test.go
- plugins/inputs/diskio/diskio.go
- plugins/inputs/diskio/diskio_test.go
- plugins/inputs/intel_powerstat/intel_powerstat.go
- plugins/inputs/mem/mem_test.go
- plugins/inputs/net/net_test.go
- plugins/inputs/netstat/netstat_test.go
- plugins/inputs/procstat/filter.go
- plugins/inputs/procstat/native_finder.go
- plugins/inputs/procstat/os_linux.go
- plugins/inputs/procstat/os_others.go
- plugins/inputs/procstat/os_windows.go
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/procstat/service_finders.go
- plugins/inputs/swap/swap_test.go
- plugins/inputs/system/mock_PS.go
- plugins/inputs/system/ps.go
- plugins/inputs/system/system.go
- plugins/inputs/system/system_test.go
- plugins/inputs/temp/temp_notlinux.go
- plugins/inputs/temp/temp_test.go
Telegraf depends on [gopsutil](https://github.com/shirou/gopsutil) to retrieve system related metrics. However, the v3 version is no longer maintained, while the v4 version has new fixes, improves and better platform coverages.
This PR upgrades gopsutil from v3 to v4.
I have tested these plugins using gopsutil and haven't seen any issue from this upgrade so far.
Note: the only [breaking changes](https://github.com/shirou/gopsutil/releases/tag/v4.24.5) from v3 to v4 that affects this repo is,  `host/SensorsTemperatures()` moved to in the new `sensors` package. This PR makes the corresponding change to the input.temp plugin to use the new package to retrieve the tempature by calling `sesors.SensorsTemperatures()` instead
resolves #16017
> chore(deps): Bump upgrade github.com/shirou/gopsutil from v3.24.4 to v4.24.9

- plugins/outputs/mqtt/topic_name_generator.go
Simple minor improvement allow to use sprig functions inside topic name templates
> feat(outputs.mqtt): Add sprig functions for topic name generator

- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
- go.mod
- go.sum
Adds a new option, `--watch-interval`, which when used with `--watch-config poll` changes the default polling rate from 250ms to a user supplied value.
resolves #15793
> feat(agent): Add --watch-interval option for polling config changes

- docs/CONFIGURATION.md
- docs/specs/tsd-005-output-buffer-strategy.md
- plugins/outputs/azure_monitor/README.md
As discussed in https://github.com/influxdata/telegraf/issues/15908 , clarifying the behavior of output buffer behavior when it fills up in general, fixing incorrect specs wording and adding related useful note to docs of outpus.azure_monitor.
Hopefully the wording is clear enough?
Also just noticed in the specs: "Telegraf will not make any attempt to limit the size on disk taken by these files beyond cleaning up WAL files for metrics that have successfully been flushed to their output source."
Perhaps the last word should be destination instead of source ?
https://github.com/influxdata/telegraf/issues/15908
> docs(outputs): Clarify buffer limits behavior and fix spec wording

- plugins/inputs/opcua/README.md
- plugins/inputs/opcua/read_client.go
- plugins/inputs/opcua/sample.conf
In cases where a session becomes invalid (e.g. due to the server not respecting the session timeout) we should retry the read after some time to allow the client to reactivate the session. This is done using the newly introduced `read_retry_timeout` and `read_retry_count` settings.
resolves #15998
> fix(inputs.opcua): Allow to retry reads on invalid sessions

- internal/snmp/field.go
- internal/snmp/field_test.go
Support byte arrays of unfixed size (1, 3, 5, 6, 7) to be converted to int.
resolves #15963
> feat(inputs.snmp): Convert uneven bytes to int

- docs/CONFIGURATION.md
- models/buffer.go
- models/buffer_disk.go
- models/buffer_disk_test.go
- models/buffer_mem_test.go
- models/buffer_suite_test.go
- models/running_output.go
Includes the alias (if set) in the file path for the WAL file to avoid plugins named the same sharing a WAL file and causing race conditions
resolves #15876
> fix(agent): Use a unique WAL file for plugin instances of the same type

- plugins/inputs/deprecations.go
This PR sets removal versions to **v1.35.0** for the old `cisco_telemetry_gnmi`, `http_listener` and `KNXListener` input plugins. All of those plugins have long be replaced or renamed.
> chore(inputs): Add removal version for old plugins

- plugins/inputs/haproxy/haproxy.go
- plugins/inputs/haproxy/haproxy_test.go
- plugins/inputs/hddtemp/go-hddtemp/hddtemp.go
- plugins/inputs/hddtemp/hddtemp.go
- plugins/inputs/hddtemp/hddtemp_test.go
- plugins/inputs/http/http.go
- plugins/inputs/http/http_test.go
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/http_response/http_response.go
- plugins/inputs/hugepages/hugepages.go
- plugins/inputs/hugepages/hugepages_notlinux.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/h*`.
As part of this effort for files from `plugins/inputs/h*`, the following actions were taken:
It is only part of the bigger work (for issue: …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/h*`

- plugins/inputs/p4runtime/p4runtime_test.go
- plugins/inputs/ping/ping.go
- plugins/inputs/postgresql/postgresql_test.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
- plugins/inputs/procstat/pgrep.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/sflow/decoder_test.go
- plugins/inputs/sflow/metricencoder.go
- plugins/inputs/sflow/packetdecoder.go
- plugins/inputs/smart/smart.go
- plugins/inputs/smart/smart_test.go
- plugins/inputs/snmp/snmp_test.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
- plugins/inputs/sqlserver/sqlserver_test.go
- plugins/inputs/stackdriver/stackdriver.go
- plugins/inputs/stackdriver/stackdriver_test.go
- plugins/inputs/statsd/statsd_test.go
- plugins/inputs/supervisor/supervisor_test.go
- plugins/inputs/sysstat/sysstat.go
- plugins/inputs/system/system_test.go
- plugins/inputs/varnish/varnish.go
- plugins/inputs/vsphere/client.go
- plugins/inputs/vsphere/vsan.go
- plugins/inputs/vsphere/vsphere_test.go
- plugins/inputs/wireguard/wireguard.go
- plugins/inputs/zfs/zfs_linux_test.go
- plugins/inputs/zipkin/codec/codec_test.go
- plugins/inputs/zipkin/codec/thrift/thrift_test.go
- plugins/inputs/zipkin/convert_test.go
- plugins/inputs/zipkin/handler_test.go
Address findings for [revive:enforce-slice-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-slice-style) in `plugins/inputs/[p-z]*`.
As we agreed here https://github.com/influxdata/telegraf/issues/15812, we will fix the errors found by the following configuration:
```
- name: enforce-slice-style
arguments: ["make"]
```
It is only part of the bigger work.
After all findings of this type in whole project are handled, we can enable `revive:enforce-slice-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-slice-style` in `plugins/inputs/[p-z]*`

- plugins/inputs/github/github.go
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/gnmi_test.go
- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/path.go
- plugins/inputs/gnmi/tag_store.go
- plugins/inputs/gnmi/update_fields.go
- plugins/inputs/google_cloud_storage/google_cloud_storage.go
- plugins/inputs/graylog/graylog.go
- plugins/inputs/graylog/graylog_test.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/g*`.
As part of this effort for files from `plugins/inputs/g*`, the following actions were taken:
It is only part of the bigger work (for issue: …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/g*`

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/configuration_metric.go
- plugins/inputs/modbus/configuration_request.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/sample_general_begin.conf
- plugins/inputs/modbus/testcases/duplicate_fields_different_registers/init.err
- plugins/inputs/modbus/testcases/duplicate_fields_different_registers/telegraf.conf
- plugins/inputs/modbus/testcases/metric_style_issue_16031/expected.out
- plugins/inputs/modbus/testcases/metric_style_issue_16031/telegraf.conf
Currently, each output of a request has the register-type added as a tag, this prevents grouping across register types. However such a grouping across register types might be helpful especially for the metric configuration-style.
This PR adds a `exclude_register_type_tag` option which is `false` by default to keep the current behavior. However, for the `request` and `metric` configuration-style this allows to group request outputs across register-types by setting it to `true`.
resolves #16031
> feat(inputs.modbus): Allow grouping across register types

- plugins/inputs/kafka_consumer/kafka_consumer.go
PR fixes a potential deadlock that most often could occur when `plugin.Stop()` was called immediately after `plugin.Start()` - this situation was most likely to happen during the execution of unit tests.
I also removed `ticker`, which was never initialized. It was likely a leftover from some functionality that no longer exists.
In the `Stop()` method, `k.topicLock.Lock()` was called along with `defer k.topicLock.Unlock()`. 
This caused `k.topicLock` to remain locked until the `Stop()` method finished executing. 
At the very end of the `Stop()` method, `k.wg.Wait()` was waiting for all goroutines to complete. 
Meanwhile, in the `Start()` method, a goroutine was started, which got stuck at `k.topicLock.Lock()` because it was waiting for `k.topicLock` to be unlocked (which would only happen …
> fix(inputs.kafka_consumer): Fix deadlock

- README.md
- plugins/outputs/cloudwatch/README.md
- plugins/outputs/cloudwatch/sample.conf
- plugins/outputs/cloudwatch_logs/README.md
- plugins/outputs/cloudwatch_logs/sample.conf
- plugins/outputs/logzio/README.md
- plugins/outputs/opentelemetry/README.md
- plugins/outputs/postgresql/README.md
- plugins/outputs/postgresql/sample.conf
- plugins/outputs/timestream/README.md
- plugins/outputs/timestream/sample.conf
- plugins/outputs/wavefront/README.md
- plugins/outputs/wavefront/sample.conf
This fixes the READMEs in outputs to adhere to a line-length of 80 in preparation of enabling the [MD013 rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md) for checking the line-length in markdownlint.
> chore(outputs): Fix line-length in READMEs

- plugins/inputs/activemq/activemq_test.go
- plugins/inputs/apache/apache_test.go
- plugins/inputs/aurora/aurora_test.go
- plugins/inputs/beat/beat_test.go
- plugins/inputs/clickhouse/clickhouse_test.go
- plugins/inputs/consul_agent/consul_agent_test.go
- plugins/inputs/couchbase/couchbase_test.go
- plugins/inputs/couchdb/couchdb_test.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_test.go
- plugins/inputs/fibaro/fibaro_test.go
- plugins/inputs/fireboard/fireboard_test.go
- plugins/inputs/fluentd/fluentd_test.go
- plugins/inputs/google_cloud_storage/google_cloud_storage_test.go
- plugins/inputs/haproxy/haproxy_test.go
- plugins/inputs/http/http_test.go
- plugins/inputs/http_response/http_response_test.go
- plugins/inputs/icinga2/icinga2_test.go
- plugins/inputs/influxdb/influxdb_test.go
- plugins/inputs/jolokia2_agent/jolokia2_agent_test.go
- plugins/inputs/jolokia2_proxy/jolokia2_proxy_test.go
- plugins/inputs/kapacitor/kapacitor_test.go
- plugins/inputs/kubernetes/kubernetes_test.go
- plugins/inputs/logstash/logstash_test.go
- plugins/inputs/mailchimp/mailchimp_test.go
- plugins/inputs/marklogic/marklogic_test.go
- plugins/inputs/monit/monit_test.go
This is only part of a larger effort to address the findings identified by `testifylint: go-require`: https://github.com/influxdata/telegraf/issues/15535
In this PR, I’m focusing on fixing findings in `http-handlers` for `plugins/inputs/[a-m]`.
```
plugins/inputs/activemq/activemq_test.go:153:4                                testifylint  go-require: do not use require in http handlers
plugins/inputs/activemq/activemq_test.go:157:4                                testifylint  go-require: do not use require in http handlers
plugins/inputs/activemq/activemq_test.go:161:4                                testifylint  go-require: do not use require …
```
> chore(linters): Fix findings found by `testifylint`: `go-require` for handlers for `plugins/inputs/[a-m]`

- .golangci.yml
- config/config.go
- internal/snmp/table.go
- internal/snmp/translator_gosmi.go
- internal/templating/matcher.go
- models/buffer.go
- models/running_input.go
- plugins/inputs/win_eventlog/util.go
- plugins/inputs/win_eventlog/win_eventlog.go
- plugins/inputs/win_wmi/method.go
- plugins/inputs/win_wmi/query.go
- selfstat/selfstat.go
- testutil/accumulator.go
- tools/custom_builder/config.go
- tools/license_checker/main.go
Address last findings for [revive:enforce-map-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-map-style) and enable this rule.
As we agreed here https://github.com/influxdata/telegraf/issues/15810 and here https://github.com/influxdata/telegraf/pull/15981, we findings found by the following configuration were addressed:
```
- name: enforce-map-style
arguments: ["make"]
exclude: [ "TEST" ]
```
resolves #15810
> chore: Enable `revive:enforce-map-style` rule

- plugins/inputs/jenkins/client.go
- plugins/inputs/jenkins/jenkins.go
- plugins/inputs/jenkins/jenkins_test.go
- plugins/inputs/jolokia2_agent/jolokia2_agent.go
- plugins/inputs/jolokia2_agent/jolokia2_agent_test.go
- plugins/inputs/jolokia2_proxy/jolokia2_proxy.go
- plugins/inputs/jolokia2_proxy/jolokia2_proxy_test.go
- plugins/inputs/jti_openconfig_telemetry/collection.go
- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/j*`.
As part of this effort for files from `plugins/inputs/j*`, the following actions were taken:
It is only part of the bigger work (for issue: …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/j*`

- plugins/outputs/wavefront/sample.conf
Fix `make docs` (lack of space in `sample.conf` for `wavefront`)
Problem introduced in https://github.com/influxdata/telegraf/pull/16079
> chore: Fix `make docs` (lack of space in `sample.conf` for `wavefront`)

- plugins/aggregators/basicstats/README.md
- plugins/aggregators/derivative/README.md
- plugins/aggregators/final/README.md
- plugins/aggregators/histogram/README.md
- plugins/aggregators/merge/README.md
- plugins/aggregators/minmax/README.md
- plugins/aggregators/quantile/README.md
- plugins/aggregators/starlark/README.md
- plugins/aggregators/valuecounter/README.md
- plugins/outputs/wavefront/README.md
This PR adds some metadata to the aggreagtor plugins like the version this plugin was introduced and the supported operating systems. Furthermore, the PR unifies the plugin descriptions a bit and uses [Github Markdown alerts](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for notes and other important information.
> [!NOTE]
> This is part of a bigger effort to automatically generate (parts) of our [documentation website](https://docs.influxdata.com/telegraf) for making the GitHub page the primary source of thruth.
> docs(aggregators): Add plugin metadata and update description

- plugins/common/socket/stream.go
- plugins/inputs/socket_listener/socket_listener_test.go
The current socket implementation allows to specify a read-buffer-size used when receiving data. However, when splitting the received message, the scanner currently uses the default scanner buffer size of 64KiB.
This PR makes sure the scanner buffer matches the read-buffer-size if the latter is larger than the default and adds a unit-test for the socket listener.
resolves #16082
> fix(common.socket): Make sure the scanner buffer matches the read-buffer size

- config/config.go
- logger/logger.go
When using the old `logtarget` setting with `eventlog` we cannot detect if the `logformat` was set because it is already initialized with the `text` default in the agent-config. This PR moves the default handling to later in order to not error if the new `logformat` was not set.
resolves #16100
> fix(logger): Avoid setting the log-format default too early

- plugins/inputs/modbus/configuration_request_test.go
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
- plugins/inputs/modbus/testcases/duplicate_fields_same_slave_and_request/init.err
Add the configured `device` name or `controller` to error messages to identify the related plugin instances if multiple modbus plugins are used.
resolves #16112
> chore(inputs.modbus): Add device or controller information to error messages

- plugins/inputs/ntpq/ntpq.go
This PR avoids scanning empty lines as this causes a panic in `processLine`. Furthermore, we need to make sure the command always contains the `-p` option to get a sensible output from the `ntpq` command.
resolves #16090
> fix(inputs.ntpq): Avoid panic on empty lines and make sure -p is present

- models/buffer.go
- models/buffer_disk.go
- models/buffer_disk_test.go
- models/buffer_mem.go
- models/buffer_mem_test.go
- models/buffer_suite_test.go
- models/filter_test.go
- models/running_aggregator_test.go
- models/running_input_test.go
- models/running_output.go
- models/running_output_test.go
- models/running_processor_test.go
This PR cleans the `models` tests a bit in preparation of submitting the partial-write-error implementation. No functional changes...
> test(models): Cleanup tests, unexport stuff and unify naming in tests

- docs/specs/tsd-008-partial-write-error-handling.md
Add specification for handling partial-write errors on outputs, defining the behavior and error content
related to #11942 
related to #14802
related to #15908 
related to #15742
> docs(specs): Add specification for partial-write errors

- internal/snmp/translator_gosmi.go
Check if the returned `Node` actually has a `Type` object.
resolves #16153
> fix(inputs.snmp): Fix crash when trying to format fields from unknown OIDs

- plugins/common/jolokia2/client.go
- plugins/common/jolokia2/gatherer.go
- plugins/common/jolokia2/gatherer_test.go
- plugins/common/jolokia2/metric.go
- plugins/common/opcua/input/input_client_test.go
- plugins/common/opcua/opcua_util.go
- plugins/common/shim/config.go
- plugins/common/starlark/starlark.go
- plugins/common/tls/utils.go
- plugins/inputs/aliyuncms/aliyuncms.go
- plugins/inputs/aliyuncms/aliyuncms_test.go
- plugins/inputs/amd_rocm_smi/amd_rocm_smi.go
- plugins/inputs/azure_monitor/azure_monitor_test.go
- plugins/inputs/beanstalkd/beanstalkd_test.go
- plugins/inputs/ceph/ceph.go
- plugins/inputs/clickhouse/clickhouse_test.go
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
- plugins/inputs/couchbase/couchbase.go
- plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription.go
- plugins/inputs/dcos/client.go
- plugins/inputs/dcos/client_test.go
- plugins/inputs/dcos/dcos_test.go
- plugins/inputs/dmcache/dmcache_linux.go
- plugins/inputs/dmcache/dmcache_linux_test.go
- plugins/inputs/docker/docker.go
- plugins/inputs/docker/docker_test.go
- plugins/inputs/docker/docker_testdata.go
- plugins/inputs/dpdk/dpdk_test.go
Address findings for [revive:enforce-slice-style](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-slice-style) in `plugins/inputs/[a-d]*` and `plugins/common`.
As we agreed here https://github.com/influxdata/telegraf/issues/15812, we will fix the errors found by the following configuration:
```
- name: enforce-slice-style
arguments: ["make"]
```
It is only part of the bigger work.
After all findings of this type in whole project are handled, we can enable `revive:enforce-slice-style` rule in `golangci-lint`.
> chore: Fix linter findings for `revive:enforce-slice-style` in `plugins/inputs/[a-d]*` and `plugins/common`

- plugins/parsers/prometheus/parser.go
The prometheus parser tries to infer the data-format from HTTP header's `Content-Type` and will return a "unknown" format if this header does not exist but continues with the `text` format. This PR skips the format warning and inference if no headers are passed to the parser and continues with the `text` format as this is probably what we want.
resolves #16157
> chore(parsers.prometheus): Do not warn about unknown format without headers

- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
- plugins/inputs/nvidia_smi/sample.conf
Reverts influxdata/telegraf#15916 per https://github.com/influxdata/telegraf/pull/16052#pullrequestreview-2419010902
> feat(inputs.nvidia-smi): REVERT -- Add `probe_on_startup` option

- .circleci/config.yml
- .golangci.yml
- Makefile
- config/config_test.go
- plugins/common/parallel/parallel_test.go
- plugins/inputs/aliyuncms/aliyuncms_test.go
- plugins/inputs/dcos/dcos_test.go
- plugins/inputs/intel_rdt/intel_rdt_test.go
- plugins/inputs/internal/internal_test.go
- plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
- plugins/inputs/vsphere/vsphere_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/outputs/cloudwatch/cloudwatch_test.go
- plugins/parsers/dropwizard/parser_test.go
- plugins/processors/starlark/starlark_test.go
- `golangci-lint` bumped to `v1.62.0`
- Matching the configuration file to the example from https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml.
- `revive:max-public-structs` disabled for now because of following isue: https://github.com/mgechev/revive/issues/1103
- we should re-enable it when issues is fixed, new version of `revive` is released and incorporated into new `golangci-lint` release
- Not recommended method of installing `golangci-lint` (from Sources) replaced for CircleCI. 
- For now, I dind't change installation method for `lint-install` in `Makefile` - developers with Windows most likely will not have `curl` installed
- https://golangci-lint.run/welcome/install/#install-from-sources
- ![image](https://github.com/user-attachments/assets/e2171396-3a55 …
> chore(deps): Bump golangci-lint from v1.61.0 to v1.62.0

- agent/agent.go
- docs/specs/tsd-003-state-persistence.md
- plugins/common/starlark/starlark.go
- plugins/inputs/tail/tail.go
- plugins/inputs/tail/tail_test.go
- plugins/processors/dedup/dedup_test.go
- plugins/processors/starlark/starlark.go
- plugins/processors/starlark/starlark_test.go
PR #15170 changed the startup sequence of stateful plugins from `Init -> SetState` to `SetState -> Init` and in turn broke all stateful users (`inputs.tail`, `inputs.docker_log`, `inputs.win_eventlog` and `processors.dedup`) to make starlark state-persistence work.
As a code sequence of `Init -> SetState` is the expected behavior and what works for all previous users, this PR restores the old order and fixes `common.starlark` to also work with this sequencing. The PR furthermore adds unit-tests where possible to make sure the sequence works. Last but not least, the PR updates the spec and also defines the shutdown order to be `Close/Stop -> GetState`.
resolves #16037
> fix(agent): Restore setup order of stateful plugins to Init() then SetState()

- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/amqp_consumer.go
- plugins/inputs/amqp_consumer/sample.conf
Allow specification of queue arguments
resolves #16140
> feat(inputs.amqp_consumer): Allow specification of queue arguments

- plugins/common/socket/datagram.go
- plugins/common/socket/socket.go
- plugins/inputs/socket_listener/socket_listener_test.go
Currently, the datagram read buffer size is fixed at 64 KB, which is leading
to data loss when receiving large datagrams (metrics) over Unix Domain Sockets (unixgram).
This fix ensures that the buffer size matches read-buffer-size
configuration, preventing truncation of incoming data.
resolves #16118
> fix(common.socket): Use read buffer size config setting as a datagram reader buffer size.

- plugins/inputs/snmp_trap/README.md
- plugins/inputs/snmp_trap/sample.conf
- plugins/inputs/snmp_trap/snmp_trap.go
Removes the "unused" deprecation from the timeout field as it is still used
resolves #16137
> fix(inputs.snmp_trap): Remove timeout deprecation

- logger/handler.go
Telegraf provides the function [RedirectLogging(w io.Writer)](https://github.com/influxdata/telegraf/blob/master/logger/logger.go#L285C1-L285C34) which allows the user to optionally redirect the log to a customized sink by wrapping the [instance.impl](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L47) as a [redirectLogger](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L111). In this case, when the user tries to close this sink by calling [logger.CloseLogging()](https://github.com/influxdata/telegraf/blob/master/logger/logger.go#L289) func (which internally calls [handler.close()](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L103)), the sink closing will not take effect because redirectLogger is not an io.Closer, while …
> fix(logging): Add Close() func for redirectLogger

- agent/agent.go
- config/types.go
- plugins/inputs/ipmi_sensor/ipmi_sensor_test.go
- plugins/inputs/sensors/sensors_test.go
fix some function names in comment
resolves #
> chore: Fix function names in comments

- plugins/inputs/smart/smart.go
- plugins/inputs/smart/smart_test.go
Adding the S.M.A.R.T. values `Power_On_Hours` and `Power_Cycle_Count` helps to identify when it is time to replace a disk.
> feat(inputs.smart): Add Power on Hours and Cycle Count

- plugins/inputs/procstat/procstat.go
With the "new" style plugin filters, if multiple filters were used, the list of running processes was being reset on each filter iteration instead of globally. This commit fixes this by setting the running pid map outside the filter iteration. The cpu usage percentage calculation needs multiple passes of gather to calculate the difference so recreating the proc on each iteration meant it never got past the first pass.
* #16256
> fix(inputs.procstat): Handle running processes correctly across multiple filters

- internal/errors.go
- models/buffer.go
- models/buffer_disk.go
- models/buffer_disk_test.go
- models/buffer_mem.go
- models/buffer_mem_test.go
- models/buffer_suite_test.go
- models/running_output.go
- models/running_output_test.go
This PR implements specification [TSD-008](https://github.com/influxdata/telegraf/blob/master/docs/specs/tsd-008-partial-write-error-handling.md) for partial write errors.
related to #11942 
related to #14802 
related to #15908
> feat(outputs): Implement partial write errors

- logger/handler.go
This PR removes the extra spaces in logging when [redirectLogger](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L111) is used.
- 3 spaces between the timestamp and log level
- 3 or 4 spaces between the log level and log messages
- 2 spaces between `prefix` and `attrMsg`
Example log contents:
The fix includes 3 aspects:
1. Based on fmt.Println func's definition,  [spaces are always added between operands](https://pkg.go.dev/fmt#Fprintln). Because of this, adding `" "` among `ts.In(time.UTC).Format(time.RFC3339)` , `level.Indicator()` and `prefix + attrMsg` will cause extra spaces to be generated (3 spaces rather than 1 space). This PR removes the `" "`  among them.
2. When `prefix` is not empty, a space is added behind `]`:
At the same time, another space is added in …
> fix(logging): Clean up extra empty spaces when redirectLogger is used

- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/read_client.go
- plugins/inputs/opcua_listener/opcua_listener.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
- plugins/inputs/opcua_listener/subscribe_client.go
- plugins/inputs/openldap/openldap.go
- plugins/inputs/openntpd/openntpd.go
- plugins/inputs/openntpd/openntpd_test.go
- plugins/inputs/opensearch_query/aggregation.bucket.go
- plugins/inputs/opensearch_query/aggregation.go
- plugins/inputs/opensearch_query/aggregation.metric.go
- plugins/inputs/opensearch_query/aggregation.response.go
- plugins/inputs/opensearch_query/opensearch_query.go
- plugins/inputs/opensearch_query/opensearch_query_test.go
- plugins/inputs/opensearch_query/query.go
- plugins/inputs/opensmtpd/opensmtpd.go
- plugins/inputs/opensmtpd/opensmtpd_test.go
- plugins/inputs/openstack/openstack.go
- plugins/inputs/opentelemetry/opentelemetry.go
- plugins/inputs/opentelemetry/opentelemetry_test.go
- plugins/inputs/openweathermap/openweathermap.go
- plugins/inputs/openweathermap/types.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/o*`.
As part of this effort for files from `plugins/inputs/o*`, the following actions were taken:
It is only part of the bigger work (for issue: …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/o*`

- cmd/telegraf/agent.conf
- cmd/telegraf/telegraf.go
- config/config.go
- docs/CONFIGURATION.md
- logger/logger.go
- logger/structured_logger.go
- logger/structured_logger_test.go
This PR adds a config option which controls the message key used for structured logs, which currently defaults to the `slog.MessageKey` value of "msg".
This is particularly useful for changing the key from `msg` to `message`, to allow automatic log parsing into certain log processing pipelines (without having to use another tool like fluentbit).
resolves #16241
> feat(logging): Allow overriding message key for structured logging

- internal/errors.go
- models/running_output_test.go
- plugins/common/ratelimiter/config.go
- plugins/common/ratelimiter/limiters.go
- plugins/common/ratelimiter/limiters_test.go
- plugins/common/ratelimiter/serializers.go
- plugins/common/ratelimiter/serializers_test.go
This PR adds the basic infrastructure to add rate-limiting to output plugins. Currently, the only rate-limiting scheme supported is a fixed-size in fixed-time-window scheme. Furthermore, a serializer is provided that iteratively adds metrics to the serialized content. Both implementations might need to be extended in the future based on demand.
related to #14802
> feat(outputs): Add rate-limiting infrastructure

- plugins/common/ratelimiter/config.go
- plugins/common/ratelimiter/limiters_test.go
- plugins/outputs/influxdb_v2/README.md
- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/influxdb_v2.go
- plugins/outputs/influxdb_v2/influxdb_v2_test.go
- plugins/outputs/influxdb_v2/sample.conf
This PR adds the ability to limit the output rate to InfluxDBv2 instances. Currently only a _fixed_ window rate-limit for the amount of _uncompressed_ data is supported.
resolves #14802
> feat(outputs.influxdb_v2): Add rate limit implementation

- logger/handler.go
This PR fixes a small regression issue I introduced in my previous PR #16255 which adds the `prefix + attrMsg` to the log message twice by mistake. 
The are added to the log message in [line 127](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L127) so it should not be added again in [line 125](https://github.com/influxdata/telegraf/blob/master/logger/handler.go#L125).
This PR removes the duplicated one.
resolves #16273
> fix(logging): Fix deplicated prefix+attrMsg in log message when redirectLogger is used

- plugins/outputs/remotefile/remotefile.go
- plugins/outputs/remotefile/remotefile_test.go
When used with tracking metrics the plugin produced an error if the template references any metric properties. This PR fixes the issue by unwrapping the metric.
resolves #16045
> fix(outputs.remotefile): Handle tracking metrics correctly

- plugins/parsers/avro/parser.go
- plugins/parsers/avro/testcases/union-nullable-tag/expected.out
- plugins/parsers/avro/testcases/union-nullable-tag/message.json
- plugins/parsers/avro/testcases/union-nullable-tag/telegraf.conf
Flatten any fields specified in `avro_tags` before trying to convert their values to strings.
Without flattening, any union fields included in `avro_tags` do not actually get converted into Influx tags. This warning is logged:
```2024-12-06T19:43:12Z W! [parsers.avro::file] Could not convert map[string:some_value] to string for tag "some_union_in_a_tag": type "map[string]interface {}" unsupported```
- [x ] No AI generated code was used in this PR
resolves #16271
> feat(parsers.avro): Allow union fields to be specified as tags

- plugins/inputs/kinesis_consumer/encoding.go
- plugins/inputs/kinesis_consumer/kinesis_consumer.go
- plugins/inputs/kinesis_consumer/kinesis_consumer_test.go
- plugins/inputs/kinesis_consumer/logging.go
- plugins/inputs/kinesis_consumer/noop_store.go
Cleanup code and tests. No functional changes.
> chore(inputs.kinesis_consumer): Cleanup code

- .golangci.yml
- plugins/serializers/json/json_test.go
- plugins/serializers/nowmetric/nowmetric_test.go
resolves https://github.com/influxdata/telegraf/issues/16183
resolves https://github.com/influxdata/telegraf/issues/16184
resolves https://github.com/influxdata/telegraf/issues/16185
> test(linters): Enable `testifylint`: `contains`, `encoded-compare` and `regexp`

- go.mod
- plugins/inputs/systemd_units/README.md
- plugins/inputs/systemd_units/systemd_units_linux.go
- plugins/inputs/systemd_units/systemd_units_test.go
Add timestamp when a unit entered the current state.
resolves #15944
> feat(inputs.systemd_units): Add active_enter_timestamp_us field

- agent/agent.go
Currently, the telegraf agent does initialize the processors in the processor stage after the aggregators even if `skip_processors_after_aggregators` is set to `true`. While the processors are not executed, initializing them is confusing and unnecessary.
This PR skips the initialization of the second processor stage if the user intends to skip them anyway.
resolves #16143
> fix(agent): Skip initialization of second processor state if requested

- CHANGELOG.md
- agent/agent.go
- config/config.go
Prepare the transition to skipping the second and unexpected stage of processors (after aggregators) by default. This PR **does not** change the default yet but adds a warning if the flag is not explicitly set to give people some head-time to figure out what they want.
> chore(agent): Add warning about changing default for 'skip_processors_after_aggregators'

- plugins/processors/unpivot/unpivot.go
- plugins/processors/unpivot/unpivot_test.go
This PR cleans up the plugin code and fixes naming of unit tests. As a side effect the PR improves performance by about 10%
```
goos: linux
goarch: amd64
pkg: github.com/influxdata/telegraf/plugins/processors/unpivot
cpu: AMD Ryzen 7 3700X 8-Core Processor   
```
| benchmark | before | after | improvement |
|--- | --- | --- | --- |
| BenchmarkAsTag-16 | 4561 ns/op |  4011 ns/op | **1.137x** |
| BenchmarkAsMetric-16 | 3598 ns/op |  3001 ns/op | **1.199x** |
> chore(processors.unpivot): Cleanup code and improve performance

- plugins/inputs/docker/docker.go
- plugins/inputs/docker/docker_test.go
- plugins/inputs/docker/docker_testdata.go
Gather info about [swarm jobs](https://github.com/moby/moby/commit/30d9fe30b1c1bf52f15a41e0b106a1542a167e04) like for normal swarm services and don't flood logs with errors about "unsupported replica mode"
relevant test configs
telegraf.conf
```toml
[[outputs.file]]
files = ["stdout"]
[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
gather_services = true
```
compose.yml
```yaml
services:
long:
image: alpine
command: sleep 20
deploy:
mode: global-job
short:
image: hello-world
deploy:
mode: replicated-job
replicas: 1
daemon:
image: jmalloc/echo-server
deploy:
mode: replicated
replicas: 1
```
output sample
```
docker_swarm,host=testst.int,service_id=mp50lo68vqgkory4e26ts8f9d,service_mode=global_job,service_name=jobs_long tasks_running=0i 1733841760000000000 …
```
> feat(inputs.docker): Support swarm jobs

- plugins/parsers/openmetrics/README.md
Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.
> docs(parsers.openmetrics): Update link to specification

- plugins/inputs/ipset/README.md
- plugins/inputs/ipset/ipset.go
- plugins/inputs/ipset/ipset_entries.go
- plugins/inputs/ipset/ipset_entries_test.go
- plugins/inputs/ipset/sample.conf
Some automatic blacklist systems (like e.g. FireHOL) are feeding known malicious IP addresses regularly into ipsets to be blocked by firewalls (e.g. iptables/nftables). It would be useful to be able to track the number of entries of such ipsets over time.
As entries can use CIDR notation to target a range of IPs (e.g. 10.12.4.0/8) with a single ipset entry, it is also useful to see the number of actualy IPs affected by one ipset.
resolves #16103
> feat(inputs.ipset): Add metric for number of entries and individual IPs

- plugins/inputs/syslog/testcases/rfc3164_best_effort_udp/expected.out
- plugins/inputs/syslog/testcases/rfc3164_strict_udp/expected.out
Timestamp for RFC3164 hardcoding 2024 in the timestamp expected output
resolves #
> chore(inputs.syslog): Fix testcase timestamp hardcoding 2024

- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/http_test.go
In #16147, the http header code for the http request was refactored, which led to a changing of the order of header application.
In v1.32.2:
1. "Hard-coded" headers (`Authorization`, `User-Agent`) were added to the headers
2. User-specified headers (config `http_headers`) were added, overwriting the "hard-coded" headers if manually specified
In v1.32.3+:
1. User-specified headers (config `http_headers`) were added to the headers
2. "Hard-coded" headers (`Authorization`, `User-Agent`) were added, overwriting the user-specified headers
In short, if an `Authorization` or `User-Agent` header was specified via the configuration `http_headers` in v1.32.3+, it would be overwritten by the default user agent and the secret store token. This PR reverts this change to be like v1.32.2 and older. …
> fix(outputs.influxdb_v2): Allow overriding auth and agent headers

- plugins/inputs/intel_powerstat/intel_powerstat.go
Telegraf fails when parsing RemovalIn value from DeprecationInfo. It is defined as  "1.35.0;"  but should be  "1.35.0".
resolves #16376
> fix(inputs.intel_powerstat): Fix option removal version

- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/influxdb_v2.go
- plugins/outputs/influxdb_v2/influxdb_v2_test.go
This PR fixes a panic for cases where the server returns a non-retryable status-code. In the course of investigating the matter unit-tests have been added to verify the correct handling of status-codes returned by the server unveiling some more corner-cases handled incorrectly. This PR also fixes those issues and simplifies code in doing so.
resolves #16350 
resolves #16386
> fix(outputs.influxdb_v2): Fix panic and API error handling

- .circleci/config.yml
- .golangci.yml
- Makefile
- plugins/inputs/prometheus/prometheus.go
- `golangci-lint` bumped to `v1.63.4`
- Matching the configuration file to the example from https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml.
- New findings addressed:
```
plugins/inputs/prometheus/prometheus.go:500:3  nolintlint  directive `//nolint:bodyclose // False positive (because of if-else) - body will be closed in `defer`` is unused for linter "bodyclose"
plugins/inputs/prometheus/prometheus.go:504:3  nolintlint  directive `//nolint:bodyclose // False positive (because of if-else) - body will be closed in `defer`` is unused for linter "bodyclose"
```
> chore(deps): Bump golangci-lint from v1.62.2 to v1.63.4

- plugins/inputs/sql/README.md
- plugins/inputs/sql/sample.conf
For some reason telegraf was not working for sql input until i added `tcp(...)` parenthesis to dsn.
resolves #
> docs(inputs.sql): Add protocol to DSN

- plugins/inputs/proxmox/README.md
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/proxmox_test.go
- plugins/inputs/proxmox/sample.conf
- plugins/inputs/proxmox/structs.go
> feat(inputs.proxmox): Allow to add VM-id and status as tag

- go.mod
- go.sum
Fixes building telegraf on OpenBSD
resolves #16368
> chore(deps): Bump github.com/shirou/gopsutil/v4 from v4.24.10 to v4.24.12

- plugins/inputs/tacacs/tacacs.go
- plugins/inputs/tail/multiline.go
- plugins/inputs/tail/multiline_test.go
- plugins/inputs/tail/tail.go
- plugins/inputs/tail/tail_solaris.go
- plugins/inputs/tail/tail_test.go
- plugins/inputs/teamspeak/teamspeak.go
- plugins/inputs/temp/temp_linux.go
- plugins/inputs/tengine/tengine.go
- plugins/inputs/tomcat/tomcat.go
- plugins/inputs/trig/trig.go
- plugins/inputs/twemproxy/twemproxy.go
- plugins/inputs/unbound/unbound.go
- plugins/inputs/unbound/unbound_test.go
- plugins/inputs/upsd/upsd.go
- plugins/inputs/upsd/upsd_test.go
- plugins/inputs/uwsgi/uwsgi.go
- plugins/inputs/vault/vault.go
- plugins/inputs/vault/vault_metrics.go
- plugins/inputs/vsphere/client.go
- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/finder.go
- plugins/inputs/vsphere/selfhealth.go
- plugins/inputs/vsphere/throttled_exec.go
- plugins/inputs/vsphere/tscache.go
- plugins/inputs/vsphere/vsan.go
- plugins/inputs/vsphere/vsphere.go
- plugins/inputs/vsphere/vsphere_test.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/[t-v]*`.
As part of this effort for files from `plugins/inputs/[t-v]*`, the following actions were taken:
It is only part of the bigger work (for …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/[t-v]*`

- agent/agent.go
- models/running_input.go
- models/running_input_test.go
- plugin.go
This PR adds support in `RunningInput` and the `Agent` to call an input plugin's `Probe` method if it exists and if the plugin has been configured for probing.
- Spec: #16052
- #15915
- #16028
- #16305
> feat(agent): Add support for input probing

- plugins/inputs/statsd/statsd.go
- plugins/inputs/statsd/statsd_test.go
Summary:
Later in this stack of diffs, I add a field named `MaxConnections` to `Statsd` because it controls the max number of connections for all listener types, not just TCP listeners. That creates a naming collision with the existing field named `MaxConnections`, which is an internal stat tracker. This diff eliminates that name collision by encapsulating all of `Statsd`'s internal stat trackers in a struct.
Test Plan:
Existing unit tests pass.
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/influxdata/telegraf/pull/16419).
* #16421
* #16420
* __->__ #16419
> chore(inputs.statsd): Refactor internal stats into their own struct

- plugins/inputs/webhooks/artifactory/artifactory_webhook.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_mock_json_test.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go
- plugins/inputs/webhooks/filestack/filestack_webhooks.go
- plugins/inputs/webhooks/filestack/filestack_webhooks_events.go
- plugins/inputs/webhooks/filestack/filestack_webhooks_test.go
- plugins/inputs/webhooks/github/github_webhooks.go
- plugins/inputs/webhooks/github/github_webhooks_mock_json_test.go
- plugins/inputs/webhooks/github/github_webhooks_models.go
- plugins/inputs/webhooks/github/github_webhooks_test.go
- plugins/inputs/webhooks/mandrill/mandrill_webhooks.go
- plugins/inputs/webhooks/mandrill/mandrill_webhooks_events.go
- plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go
- plugins/inputs/webhooks/papertrail/papertrail_test.go
- plugins/inputs/webhooks/papertrail/papertrail_webhooks.go
- plugins/inputs/webhooks/papertrail/papertrail_webhooks_models.go
- plugins/inputs/webhooks/particle/particle_webhooks.go
- plugins/inputs/webhooks/particle/particle_webhooks_test.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks_events.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks_events_json_test.go
- plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go
- plugins/inputs/webhooks/webhooks.go
- plugins/inputs/webhooks/webhooks_test.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/webhooks`.
As part of this effort for files from `plugins/inputs/webhooks`, the following actions were taken:
It is only part of the bigger work …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/webhooks/*`

- models/running_input_test.go
Consolidate the probing into the already existing `mockInput` implementation. As a side-effect, this PR fixes the linter issue existing in current master...
> test(models): Consolidate mock input implementations

- plugins/inputs/win_eventlog/event.go
- plugins/inputs/win_eventlog/syscall_windows.go
- plugins/inputs/win_eventlog/util.go
- plugins/inputs/win_eventlog/util_test.go
- plugins/inputs/win_eventlog/win_eventlog.go
- plugins/inputs/win_eventlog/win_eventlog_notwindows.go
- plugins/inputs/win_eventlog/win_eventlog_test.go
- plugins/inputs/win_eventlog/zsyscall_windows.go
- plugins/inputs/win_perf_counters/pdh.go
- plugins/inputs/win_perf_counters/pdh_386.go
- plugins/inputs/win_perf_counters/pdh_amd64.go
- plugins/inputs/win_perf_counters/pdh_arm64.go
- plugins/inputs/win_perf_counters/performance_query.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
- plugins/inputs/win_perf_counters/win_perf_counters_notwindows.go
- plugins/inputs/win_perf_counters/win_perf_counters_test.go
- plugins/inputs/win_services/win_services.go
- plugins/inputs/win_services/win_services_integration_test.go
- plugins/inputs/win_services/win_services_notwindows.go
- plugins/inputs/win_services/win_services_test.go
- plugins/inputs/win_wmi/method.go
- plugins/inputs/win_wmi/query.go
- plugins/inputs/win_wmi/win_wmi.go
- plugins/inputs/win_wmi/win_wmi_notwindows.go
- plugins/inputs/win_wmi/win_wmi_test.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/win*`.
As part of this effort for files from `plugins/inputs/win*`, the following actions were taken:
It is only part of the bigger work (for …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/win*`

- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
This PR implements [tsd-009](https://github.com/influxdata/telegraf/blob/master/docs/specs/tsd-009-probe-on-startup.md) for the `inputs.nvidia_smi` plugin. This is achieved by running nvidia-smi once and checking the return code for a successful run.
- https://github.com/influxdata/telegraf/issues/15915
- https://github.com/influxdata/telegraf/issues/16028
> feat(inputs.nvidia_smi): Implement probing

- plugins/processors/filter/README.md
There's an error in the example configuration, which causes Telegraf 1.33 to fail with the error
```
unmarshalling failed: line 73: cannot unmarshal TOML string into []string
```
resolves #16433
> docs(processors.filter): Correct tag specification in rule example

- plugins/inputs/dovecot/README.md
- plugins/inputs/dovecot/dovecot_test.go
- testutil/container.go
Dovecot version 2.4 and newer do not contain the old-statistics plugin anymore and therefore the plugin stops working.
This PR adds a comment to the README documenting this limitation. It also fixes the integration test by pinning the image to the latest 2.3 version of Dovecot. Additionally, the PR adds an information on the container including the image digest so we can easily identify which image is used.
> docs(inputs.dovecot): Document plugin not working for version 2.4+

- scripts/init.sh
Prevent Telegraf from spawning a stray dbus-session process when started by sysvinit
resolves #13635
> fix(service): Set address to prevent orphaned dbus-session processes

- plugins/outputs/azure_monitor/README.md
- plugins/outputs/azure_monitor/azure_monitor.go
- plugins/outputs/azure_monitor/azure_monitor_test.go
- plugins/outputs/azure_monitor/sample.conf
- plugins/outputs/azure_monitor/types.go
The Azure Monitor service has limitations on the time-range of accepted metrics. Metrics older than 30 minutes and more than 4 minutes into the future (or 20 min in the past and 5 min in the future according to documentation) are not accepted and the service responds with a `400` HTTP error code. The current code propagates this error up into the model and the model code then assumes it must reschedule the batch or metrics due to a retryable error. Usually metrics are filtered according to those limits but due to latency during transmission etc. the error might still be triggered.
This PR handles the `400` HTTP error code as a non-retryable error and fixes other non-retryable errors paths on the way.
It furthermore introduces two new configuration settings to better control the accepted …
> fix(outputs.azure_monitor): Prevent infinite send loop for outdated metrics

- cmd/telegraf/cmd_config.go
Check for the option not being set and issue a warning just as we do for normal runs...
resolves #16399
> fix(agent): Avoid panic by checking for skip_processors_after_aggregators

- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/testdata/clickhouse/enable_stdout_log.xml
The Docker image `yandex/clickhouse-server` that has been used for the integration test hasn't been updated in 3 years. ClickHouse has moved to the Docker image that is called `clickhouse`.
This uses the new image for the integration test.
The log messages have changed, so that is taken into account when waiting for the test container to spin up. Technically waiting for the open port would be enough but for good measure we also wait for a corresponding log output. To get the log output, a config file is included.
resolves #16461
> chore(outputs.sql): Update ClickHouse Docker image for integration test

- go.mod
Works around an issue with negative and oversize x509 certificate serial numbers to restore behavior from before Go 1.23. Long term I am communicating with the Go team to see if there is a better solution
Related to #16309
> fix(agent): Set `godebug x509negativeserial=1` as a workaround

- plugins/outputs/mqtt/README.md
- plugins/outputs/mqtt/homie.go
This is to make the homie `topic_name` consistent with the normal mqtt `topic_name` templating.
> feat(outputs.mqtt): Add sprig for topic name generator for homie layout

- plugins/processors/template/README.md
- plugins/processors/template/template.go
- plugins/processors/template/template_test.go
This enables the use of sprig functions in the template processor
> feat(processors.template): Add sprig function for templates

- plugins/inputs/gnmi/README.md
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/sample.conf
- plugins/inputs/gnmi/sample.conf.in
Adds support for gNMI depth extension to control the depth of the recursion when the server evaluates a group of paths. 
resolves #16432
> feat(inputs.gnmi): Add support for "depth" extension

- plugins/inputs/proxmox/README.md
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/sample.conf
Currently, Telegraf errors out if no search domain is configured for the proxmox node. However, the search domain is only used for outputting the FQDN for the node (and VM). This PR prevents Telegraf from erroring out at the cost of not getting the FQDN of the node.
resolves #16475
> fix(inputs.proxmox): Allow search domain to be empty

- internal/internal.go
- internal/internal_test.go
Fixes plural acronyms being split up into "separate words" for snake case. Example:
- `SnakeIDGoogle` gets split into `snake_id_google`
- `ConsumedLCUs` would get split into `consumed_lc_us`, since it assumes that `Us` is the "next word
Now will return `consumed_lcus`, having a special case for acronyms like `LCUs` (ending in 's')
resolves #16496
> fix(internal): Fix plural acronyms in SnakeCase function

- logger/event_logger.go
- logger/event_logger_test.go
- logger/logger.go
- logger/logger_test.go
- logger/structured_logger.go
- logger/structured_logger_test.go
- logger/text_logger.go
- logger/text_logger_test.go
This PR makes closing of the logging infrastructure more robust by
- not closing `stderr` in structured-logging
- avoid returning an error in closing already files
- avoid closing already closed EventLog handles
and fixes the unit tests by 
- removing prefix EventLog fixing integration tests on Windows
- close logging everywhere we setup logging before to make sure all files are closed
- use `t.TempDir` everywhere to make sure we clean up
- close files created with `os.CreateTemp` to not leave open files behind
replaces #16459
> fix(logging): Handle closing correctly and fix tests

- plugins/processors/execd/execd.go
- plugins/processors/execd/execd_test.go
This PR fixes the type assertion for detecting if we should use a streaming-parser or not by taking into account that a parser might be wrapped into a `*models.RunningParser`. Additionally, the PR adds a unit-test to check for long lines returned by the executable after cleaning up a bit. 
resolves #15927
> fix(processors.execd): Detect line-protocol parser correctly

- cmd/telegraf/telegraf.go
When watching remote (http) configuration files we do issue a `HEAD` request to find out if the config changed. However, this request is currently missing the authentication header and therefore those requests fail if the endpoint requires authentication.
This PR adds the authentication header if a token is specified and also sends the _Telegraf_ user agent in the request.
resolves #16545
> fix(agent): Add authorization and user-agent when watching remote configs

- go.mod
- go.sum
This PR bumps the upstream library to include a fix avoiding the panic seen in #16527 and in general fixes parsing of Unix socket attributes.
resolves #16527
> chore(deps): Bump github.com/vishvananda/netlink from 1.3.0 to 1.3.1-0.20250221194427-0af32151e72b

- plugins/outputs/prometheus_client/README.md
- plugins/outputs/prometheus_client/prometheus_client.go
- plugins/outputs/prometheus_client/sample.conf
Allow simple setting of custom headers in prometheus_client's HTTP response, in this case to meet security requirements, but also just as a generally useful feature.
resolves #16565
> feat(outputs.prometheus_client): Allow adding custom headers

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/sample.conf
- plugins/outputs/prometheus_client/prometheus_client_test.go
- plugins/outputs/prometheus_client/prometheus_client_v1_test.go
Add unit tests to ensure we deliver a valid `Content-Type` header when being scraped.
resolves #16259
> test(outputs.prometheus_client): Add tests for content-type header

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
The SQL output plugin automatically creates the required table in the target database. For this it uses a default create table template that currently has the value `CREATE TABLE {TABLE}({COLUMNS})` where `{TABLE}` is the metric name and `{COLUMNS}` is a list of column name/type pairs. The plugin has a setting `table_template` to override this template.
ClickHouse requires that in a CREATE TABLE statement a primary key or a sort key is given, thus the default template above does not work with the ClickHouse database.
There is [a section](https://github.com/influxdata/telegraf/blob/51cddd9c94a476604401f48800865e6830d4f7e7/plugins/outputs/sql/README.md#clickhouse) about ClickHouse-specific configuration in the README, but it doesn't mention a mandatory `table_template`.
The integration test …
> chore(outputs.sql): Adapt default templates for ClickHouse

- plugins/inputs/vsphere/endpoint.go
Includes the vcenter name in error logging when an accumulator error is added 
resolves #16567
> chore(inputs.vsphere): Improve metric collection error logging

- plugins/serializers/prometheus/convert.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
With PR #16453  we bumped the prometheus package which in turn changed the validation scheme for metric-names and labels to only being UTF-8 conform. However, while changing the label validation scheme back to "legacy" the metric name validation was not. This PR fixes the metric name validation and reverts the check to "legacy". This PR is also relevant for the `prometheusremotewrite` serializer as it reuses the sanitization code.
resolves #16550
> fix(serializers.prometheus): Use legacy validation for metric name

- plugins/outputs/opensearch/opensearch.go
We are performing an incorrect check when verifying the existence of an `opensearchutil.BulkIndexer`, leading to the creation of multiple instances. This excessive instantiation results in a memory leak.
resolves #16295
> fix(outputs.opensearch): Use correct pipeline name while creating bulk-indexers

- plugins/outputs/nats/nats.go
The NATS output plugin use the NATS Core publisher both for Core and Jetstream. This can be problematic when publishing many messages to a Jetsteam, you do not have `pack` and can overload the server. This PR change publisher to use Jetstream publisher insted of Core when publishing to Jetstream. 
resolves #16571
> feat(outputs.nats): Use Jetstream publisher when using Jetstream

- plugins/inputs/net/net.go
When running in containerized environments existing interface checks fail for cases where `procfs` is not mounted in `/proc` because the `net.Interfaces()` function will perform a syscall not taking the `HOST_PROC` environment variable into account. Therefore, this PR will _disable_ the checks in cases where the `HOST_PROC` environment variable is set.
resolves #16564
> fix(inputs.net): Skip checks in containerized environments

- plugins/inputs/exec/exec.go
- plugins/inputs/exec/exec_test.go
- plugins/inputs/exec/run_notwindows.go
- plugins/inputs/exec/run_windows.go
Allow to get the full, untruncated error messages from stderr in debug (and trace) mode.
resolves #15784
> feat(inputs.exec): Allow to get untruncated errors in debug mode

- plugins/inputs/mongodb/mongodb_server.go
This removes a check being always true as the `result` variable is always set some lines above.
> chore(inputs.mongodb): Remove superfluous check

- plugins/inputs/cloudwatch/README.md
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
- plugins/inputs/cloudwatch/sample.conf
- plugins/inputs/cloudwatch/utils.go
This PR reworks the cloudwatch plugin to support wildcards for the namespaces configuration option.
resolves #16208
> feat(inputs.cloudwatch): Allow wildcards for namespaces

- docs/CONFIGURATION.md
- plugins/aggregators/merge/README.md
- plugins/aggregators/merge/sample.conf
Adds the default settings for period, delay and grace to the aggregator plugin readme. Additionally, the merge aggregator sample config is extended with an explanation and the default setting for period, delay and grace.
resolves #16181
> docs(aggregators): Document default settings for period, delay and grace

- docs/LICENSE_OF_DEPENDENCIES.md
- tools/license_checker/data/whitelist
This PR fixes the link to the `https://github.com/pavlo-v-chernykh/keystore-go` license and whitelists the `github.com/segmentio/asm` package for versions `<=v1.2.0` as the latest master has a license change to `MIT-0` but released versions are still `MIT`.
> chore(licenses): Fix link and whitelist package

- plugins/inputs/sql/sql.go
- plugins/inputs/sql/sql_test.go
- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
- testutil/testutil.go
This PR uncomments mandatory entries in the configuration,  cleans up initialization in the code a bit and moves the `Init` function to the right spot. Furthermore, the PR unifies random password generation for tests which should not use the `crypto/rand` package to prevent draining the entropy pool as this might kill CI pipelines.
related to #16621
> chore(sql): Cleanup code

- go.mod
- go.sum
> chore(deps): Bump golang.org/x/oauth2 from 0.26.0 to 0.28.0

- .github/workflows/readme-linter.yml
This PR bumps the changed-file-detection action to a new version and hash-tags this version to avoid issues with manipulated tags.
resolves #16649
> chore(deps): Bump tj-actions/changed-files from v45 to v46.0.1

- plugins/inputs/tail/tail.go
- plugins/inputs/tail/tail_test.go
Ensure consistency between documentation and actual options in the code.
resolves #16642
> fix(inputs.tail): Use correct initial_read_offset persistent offset naming in the code

- config/plugin_printer.go
Keep one entry per file for multiple instances of plugins, ensuring the table is shorter and condensed. Also fix empty table printing when plugins(like processors, aggregators) are not loaded.
resolves #16637
> fix(agent): Condense plugin source information table when multiple plugins in same file

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
- plugins/outputs/sql/testdata/mariadb_no_timestamp/expected_metric_one.sql
- plugins/outputs/sql/testdata/mariadb_no_timestamp/expected_metric_three.sql
- plugins/outputs/sql/testdata/mariadb_no_timestamp/expected_metric_two.sql
- plugins/outputs/sql/testdata/mariadb_no_timestamp/initdb/script.sql
This PR allows to set the timestamp column to empty to not insert the timestamp column.
resolves #16621 
based on #16624
superseeds #16623
> fix(outputs.sql): Allow to disable timestamp column

- tools/package_incus_test/main.go
This bumps the fedora image for the nightly smoke test as Fedora 39 is no longer available as an Incus image.
> test: Update fedora image for nightly test

- cmd/telegraf/telegraf_posix.go
On BSDs (OpenBSD/FreeBSD/NetBSD/Dragonfly/Others?), telegraf had a bug in its detection of the lockable memory:
the respective value of the resource constant **`RLIMIT_MEMLOCK`**,  used as `getrlimit(2)` parameter, deviates from the Linux one.
resolves #16681
> fix(secrets): Make "insufficient lockable memory" warning work on BSDs

- plugins/processors/enum/README.md
- plugins/processors/enum/enum.go
- plugins/processors/enum/enum_test.go
- plugins/processors/enum/sample.conf
Adds a new `fields` option to the enum processor, deprecating the old `field` option. Allows mapping multiple fields with one enum mapping when a glob does not work
resolves #10892
> feat(processors.enum): Allow mapping to be applied to multiple fields

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
Automate table updates, when the table does not contain a field
Currently, updates to the Table are left to the administrator and whenever a field is not present (in the table), the entire Telegraf flush is discarded, losing data in the process.
The new approach exposes two templates, one to update a table and another on to query a table for it's columns.
To avoid unnecessary (and expensive) requests, we cache the table columns and update it, whenever there is a cache miss from a field.
N/A
> feat(outputs.sql): Add option to automate table schema updates

- plugins/processors/defaults/README.md
- plugins/processors/defaults/defaults.go
- plugins/processors/defaults/defaults_test.go
- plugins/processors/defaults/sample.conf
This allows the defaults processor to set tags as well as fields. It applies the same logic as the field defaults. so if the tag is missing, or its value is a empty string or a string with just spaces, it will be replaced with the default provided
> feat(processors.defaults): Add support for specifying default tags

- .github/dependabot.yml
Increases the dependabot open PRs limit from 10 to 25 to try and catch up on our backlog of dependency updates gradually
resolves #
> chore: Increase dependabot open PRs limit to 25

- plugins/outputs/influxdb_v2/influxdb_v2_test.go
This PR adds benchmarking functions to the InfluxDBv2 output plugin for assessing the pure write throughput not taking network latency or server operations into account.
> test(outputs.influxdb_v2): Add benchmarks

- plugins/inputs/whois/testcases/invalid_domain/expected.err
- plugins/inputs/whois/testcases/invalid_domain/telegraf.conf
- plugins/inputs/whois/testcases/valid_idn_domain/expected.out
- plugins/inputs/whois/testcases/valid_idn_domain/input_münchen.de.txt
- plugins/inputs/whois/testcases/valid_idn_domain/input_xn--mnchn-kva.de.txt
- plugins/inputs/whois/testcases/valid_idn_domain/telegraf.conf
- plugins/inputs/whois/whois.go
**Add IDN Support to Whois Plugin**  
Enhances domain validation for Internationalized Domain Name (IDN) support by handling punycode conversion.  
**Implementation:**  
- Validate as a standard ASCII domain first.  
- Convert non-ASCII domains to punycode with strict validation.  
- Ensure the converted domain matches ASCII or punycode patterns.  
related to: #16509
> feat(inputs.whois): Support IDN domains

- go.mod
- go.sum
> chore(deps): Bump github.com/vmware/govmomi from v0.45.1 to v0.49.0

- .github/dependabot.yml
Sets this option in the gomod package ecosystem instead of just the github actions one
resolves #
> chore: Increase dependabot PR limit for Go dependencies

- plugins/common/psutil/mock_ps.go
- plugins/common/psutil/ps.go
- plugins/inputs/conntrack/conntrack.go
- plugins/inputs/conntrack/conntrack_test.go
- plugins/inputs/cpu/cpu.go
- plugins/inputs/cpu/cpu_test.go
- plugins/inputs/disk/disk.go
- plugins/inputs/disk/disk_test.go
- plugins/inputs/diskio/diskio.go
- plugins/inputs/diskio/diskio_test.go
- plugins/inputs/mem/mem.go
- plugins/inputs/mem/mem_test.go
- plugins/inputs/net/net.go
- plugins/inputs/net/net_test.go
- plugins/inputs/netstat/netstat.go
- plugins/inputs/netstat/netstat_test.go
- plugins/inputs/swap/swap.go
- plugins/inputs/swap/swap_test.go
- plugins/inputs/system/system.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/inputs/system`.
As part of this effort for files from `plugins/inputs/system`, the following actions were taken:
- `ps.go` and `mock_PS.go` aren't part of the `system` plugin. They serve as access points to various types of system statistics for other plugins. Therefore, it seems that a better place for these files would be the `plugins/common` package, where I have moved them and properly documented the exported types and functions.
- All remaining exported types were given comments in the appropriate form – this does not apply to …
> chore: Fix linter findings for `revive:exported` in `plugins/inputs/system`

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- plugins/inputs/azure_storage_queue/README.md
- plugins/inputs/azure_storage_queue/azure_storage_queue.go
- plugins/inputs/azure_storage_queue/azure_storage_queue_test.go
- plugins/inputs/azure_storage_queue/sample.conf
This switches the plugin from the unmaintained `github.com/Azure/azure-storage-queue-go` module to the upstream, maintained version without functional changes.
> chore(inputs.azure_storage_queue): Switch to maintained library

- plugins/outputs/influxdb/influxdb_test.go
This PR adds benchmarking functions to the InfluxDBv1 output plugin for assessing the pure write throughput not taking network latency or server operations into account.
> test(outputs.influxdb): Add benchmarks

- plugins/outputs/health/README.md
- plugins/outputs/health/health.go
- plugins/outputs/health/health_test.go
- plugins/outputs/health/sample.conf
This adds a new check to the `health` output plugin that can detect moments when no metrics are flowing through `telegraf`. For example, when impacted by issues like https://github.com/influxdata/telegraf/issues/16070
This is disabled by default, and can be enabled using the new configuration options:
```
[[outputs.health]]
service_address = "http://:8080"
max_time_between_metrics = "1s"
unhealthy_if_metrics_are_delayed = true
```
Besides the included unittests, this change was validated running `telegraf` with the following configuration:
```
[[inputs.internal]]
interval = "20s"
[[outputs.health]]
service_address = "http://:8080"
max_time_between_metrics = "1s"
unhealthy_if_metrics_are_delayed = true
```
And querying the health status using: 
```
while true; do curl -X GET …
```
> feat(outputs.health): Add max time between metrics check

- plugins/outputs/nats/README.md
- plugins/outputs/nats/nats.go
- plugins/outputs/nats/nats_test.go
- plugins/outputs/nats/sample.conf
- plugins/outputs/nats/testcases/js-async-pub.conf
Solves #16581 by adding option to use async jetstream publish.  "Make" up for loose of performance when changing to sync jetstream publisher vs core. 
resolves #16581
based on #16570
> feat(outputs.nats): Allow asynchronous publishing for Jetstream

- plugins/inputs/win_wmi/method.go
Replace the hard-coded left-over when calling the given method. Thanks @skartikey for spotting this!
related to #16699
> fix(inputs.win_wmi): Replace hard-coded class-name with correct config setting

- plugins/inputs/win_wmi/method.go
This PR is part of the attempt to fix the issues seen in #16179. While I'm not able to reproduce the issues, it seems like restricting the threading model for calling the COM object to a serialized chain for each thread helps. So this PR constraint the threading model in this way.
related to #16179
> fix(inputs.win_wmi): Restrict threading model to APARTMENTTHREADED

- plugins/inputs/cloudwatch/cloudwatch.go
This change ensures safe handling when only one of StatisticInclude or StatisticExclude is non-nil, preventing a nil pointer dereference that was causing a panic.
Background
The bug stemmed from not accounting for all possible nil combinations of these two pointers. The existing if condition only handled the case where both were nil, but the else block did not properly handle scenarios where only one was set. This fix explicitly checks each pointer before dereferencing.
resolves #16779
> fix(inputs.cloudwatch): Handle metric includes/excludes correctly to prevent panic

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/common/kafka/sasl.go
- plugins/common/kafka/sasl_aws_iam_msk.go
- plugins/common/kafka/sasl_oauth_file.go
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
Allow authentication using AWS IAM with MSK as SASL token provider.
> feat(common.kafka): Add AWS-MSK-IAM SASL authentication

- plugins/outputs/influxdb_v2/README.md
- plugins/outputs/influxdb_v2/sample.conf
> docs(outputs.influxdb_v2): Use correct unit for rate_limit example

- plugins/outputs/quix/quix.go
New Quix Cloud managed broker don't require certificate and current Quix plugin implementation will fail in such a scenario.
resolves #16856
> fix(outputs.quix): Allow empty certificate for new cloud managed instances

- models/buffer_disk.go
- models/buffer_disk_test.go
- models/buffer_suite_test.go
The disk buffer grows and never shrinks, as documented [here](https://github.com/influxdata/telegraf/issues/16696).
resolves #16314
resolves #16500
resolves #16615
resolves #16696
> fix(agent): Correctly truncate the disk buffer

- .golangci.yml
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_util.go
- plugins/inputs/docker_log/docker_log.go
- plugins/inputs/eventhub_consumer/eventhub_consumer.go
- plugins/inputs/kube_inventory/daemonset.go
- plugins/inputs/kube_inventory/endpoint.go
- plugins/inputs/kube_inventory/ingress.go
- plugins/inputs/kube_inventory/pod.go
- plugins/inputs/kube_inventory/service.go
- plugins/inputs/mongodb/mongodb.go
- plugins/inputs/mongodb/mongodb_data.go
- plugins/inputs/mongodb/mongodb_server.go
- plugins/inputs/mongodb/mongostat.go
- plugins/inputs/rabbitmq/rabbitmq.go
- plugins/inputs/ras/ras.go
- plugins/inputs/ras/ras_test.go
- plugins/inputs/ravendb/ravendb.go
- plugins/inputs/vsphere/endpoint.go
- plugins/outputs/timestream/timestream_test.go
- plugins/parsers/grok/parser.go
- plugins/parsers/prometheusremotewrite/parser.go
In this PR I configure `revive:var-naming` rule in the following way:
```
- name: var-naming
arguments:
- [ "ID", "DB", "TS" ] # DenyList
```
to force UPPER_CASE convention for `ID`, `DB`, `TS` in names.
Thanks to that, we achieve the same behaviour as for [staticcheck](https://staticcheck.dev/) -> [ST1003](https://staticcheck.dev/docs/checks/#ST1003) (so it can stay disabled).
Following findings were addressed:
```
plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_util.go:841:29  revive      var-naming: method initDb should be initDB
plugins/inputs/docker_log/docker_log.go:372:6                      revive      var-naming: var lastTs should be lastTS
plugins/inputs/eventhub_consumer/eventhub_consumer.go:41:2         revive      var-naming: struct field EnqueuedTimeAsTs should be …
```
> chore(linters): Configure `revive:var-naming` and fix its findings

- plugins/inputs/lustre2/lustre2.go
From Lustre2.16 some stats files (e.g. /proc/fs/lustre/mdt/*/job_stats) can be completely empty, whereas in previous versions there were always at least some characters at the beginning of the file (e.g. "job_stats: ") 
`getLustreProcStats` generates an "index out of range" crash when trying to "figure out if the data should be tagged with job_id" if the file is completely empty.
This fix enables to skip empty files as there is nothing to report anyway.
- [x ] No AI generated code was used in this PR
resolves #16631
> fix(inputs.lustre2): getLustreProcStats skips empty files

- cmd/telegraf/telegraf.go
- plugins/common/adx/adx.go
- plugins/inputs/fluentd/fluentd.go
- plugins/inputs/ipset/ipset.go
- plugins/inputs/opensearch_query/aggregation.response.go
- plugins/inputs/vsphere/endpoint.go
- plugins/outputs/graphite/graphite.go
- plugins/outputs/signalfx/signalfx_test.go
- plugins/parsers/xpath/parser.go
- tools/license_checker/whitelist.go
In this PR, I address findings for: `staticcheck->QF1001` - Apply De Morgan’s law.  
However, as agreed in https://github.com/influxdata/telegraf/issues/16826, I am not enabling this rule.
resolves #16826
> chore(linter): Address findings for `staticcheck->QF1001` - Apply De Morgan’s law

- plugins/common/ratelimiter/serializers.go
We want to reduce the number of allocations so never shrink the buffer but only grow it.
in preparation of #16741
> fix(common.ratelimiter): Only grow the buffer but never shrink

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Updates go to 1.24.2. Also adjusts the go downloads website url to the new one.
I'm still having issues with publishing the CI container to quay, so that has not been done yet
resolves #16728
> chore: Update go to 1.24.2

- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/azuretoken.go
- plugins/inputs/sqlserver/sample.conf
- plugins/inputs/sqlserver/sqlserver.go
This pull request migrates the authentication mechanism from the deprecated **Azure Active Directory Authentication Library (ADAL)** to the modern **Microsoft Authentication Library (MSAL)**.
Microsoft has officially deprecated ADAL, and while existing applications will continue to function, **no further security fixes or updates will be provided**. To ensure continued security and compatibility with Azure services, it's essential to use MSAL going forward.
- 📢 [Microsoft’s announcement on ADAL deprecation](https://learn.microsoft.com/en-us/entra/msal/)
- 📘 [MSAL Migration Guide](https://learn.microsoft.com/en-us/entra/identity-platform/msal-migration)
> chore(inputs.sqlserver): Migrate Azure AD Authentication from ADAL to MSAL

- plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
Be able to output prom native histogram when necessary fields are present.
resolves #16120
> feat(serializer.prometheusremotewrite): Allow sending native histograms

- docs/includes/startup_error_behavior.md
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/s7comm/README.md
- plugins/outputs/cratedb/README.md
- plugins/outputs/kafka/README.md
- plugins/outputs/postgresql/README.md
- plugins/outputs/syslog/README.md
The docs should make more explicit mention of the probe config option for `startup_error_behavior`. This adds mention of it in the `docs/includes/startup_error_behavior.md`.
I'm looking for thoughts/opinions on the right way to do this. If exposing this in the plugin documentation for plugins that don't actually support probing is inappropriate, I'm happy to rethink this PR.
NOTE: The `inputs.nvidia_smi` plugin does not include the `docs/includes/startup_error_behavior.md` file, which is perhaps a historic leftover. Should We modify this to include the doc and make explicit mention of the fact that this plugin supports probing?
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nvidia_smi/README.md#startup-error-behavior-options
resolves #16858
> docs: Document `probe` as an option for the startup-error-behavior

- .golangci.yml
- config/config.go
- config/config_test.go
- plugins/inputs/burrow/burrow_test.go
- plugins/inputs/cgroup/cgroup_linux.go
- plugins/inputs/monit/monit_test.go
- plugins/inputs/phpfpm/fcgi_client.go
- plugins/inputs/redfish/redfish_test.go
- plugins/outputs/bigquery/bigquery.go
- plugins/outputs/sumologic/sumologic_test.go
- plugins/serializers/prometheus/convert.go
- tools/update_goversion/main.go
Fixes following findings:
```
config/config.go:664:10                            staticcheck  ST1005: error strings should not end with punctuation or newlines
config/config.go:702:13                            staticcheck  ST1005: error strings should not end with punctuation or newlines
config/config.go:727:13                            staticcheck  ST1005: error strings should not end with punctuation or newlines
config/config.go:747:13                            staticcheck  ST1005: error strings should not end with punctuation or newlines
config/config.go:771:13                            staticcheck  ST1005: error strings should not end with punctuation or newlines
config/config.go:792:13                            staticcheck  ST1005: error strings should not end with punctuation …
```
> chore(linters): Enable `ST1005`, `ST1013`, `ST1016`, `ST1017`, `QF1002` checks for `staticcheck`

- plugins/processors/all/cumulative_sum.go
- plugins/processors/cumulative_sum/README.md
- plugins/processors/cumulative_sum/cumulative_sum.go
- plugins/processors/cumulative_sum/cumulative_sum_test.go
- plugins/processors/cumulative_sum/sample.conf
We collect metrics from a large amount of mobile devices and scrape aggregated data with Prometheus. We don't have [a monotonic increasing](https://prometheus.io/docs/concepts/metric_types/#counter) without cumulative effect (like for histogram aggregator). Sum is reset based on period settings, which prevents us from building graphs with different time intervals.
This MR add a new config property to allow accumulate data for a long period of time even between resets.
resolves [#16591](https://github.com/influxdata/telegraf/issues/16591)
> feat(processors.cumulative_sum): Add plugin

- plugins/inputs/win_eventlog/README.md
- plugins/inputs/win_eventlog/sample.conf
- plugins/inputs/win_eventlog/win_eventlog.go
- plugins/inputs/win_eventlog/zsyscall_windows.go
This PR allows to handle arbitrarily large events but introduces a `event_size_limit` to prevent denial-of-service situations when _really_ large events occur. Furthermore, now an error message is logged if the message is too large so that there is at least a trace in the logs.
resolves #16381
> fix(inputs.win_eventlog): Handle large events to avoid they get dropped silently

- plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
- testutil/capturelog.go
Current log level for dropped series are now error. It's better to adjust it to warning since there are much more severe errors that can happen and dropped series are very noisy. This make it possible to example adjust log_level to error while incorrect metrics is fixed to stop logs from all the spam. 
resolves #16864
> chore(serializers.prometheusremotewrite): Changed log level for dropped series to warning

- go.mod
- go.sum
Fixes loong64 builds
resolves #
> chore(deps): Bump github.com/creack/goselect from 0.1.2 to 0.1.3

- go.mod
- go.sum
- plugins/inputs/azure_storage_queue/azure_storage_queue_test.go
- plugins/outputs/event_hubs/event_hubs_test.go
This PR switches the Azure integration tests to the new maintained `azure` testcontainer module.
> chore(deps): Switch to maintained azure testcontainer module

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/http_service_discovery.go
- plugins/inputs/prometheus/http_service_discovery_test.go
- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/sample.conf
- plugins/inputs/prometheus/testcases/service_discovery/http-services.json
- plugins/inputs/prometheus/testcases/service_discovery/telegraf.conf
This is a basic implementation to support HTTP service discovery. There are many use cases where something like this could be useful such as when hosts change and a developer might need to write their own http service discovery service. I tested this with a basic implementation of http service discovery I wrote here https://github.com/djbarajas/http-prometheus-sd/tree/main.
resolves https://github.com/influxdata/telegraf/issues/16695.
> feat(inputs.prometheus): Add HTTP service discovery support

- go.mod
- go.sum
Needed for the Go update in #17005 for darwin-amd64 builds to compile properly.
resolves #
> chore(deps): Bump github.com/ebitengine/purego from 0.8.2 to 0.8.3

- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
- plugins/inputs/cloudwatch/utils.go
PR #16337 changed the dimension filtering and by doing so accidentally changed the filter behavior to accept all "unconfigured" dimensions. This however, leads to the artifact that users are no longer able to exclude dimension to e.g. query data accumulated over availability zones.
This PR restores the pre-v1.34.0 behavior and will only accept metrics that match _all_ configured dimensions i.e. excluding metrics with dimensions not configured by the user.
resolves #17001
> fix(inputs.cloudwatch): Restore filtering to match all dimensions

- plugins/inputs/opcua/opcua_test.go
This is a type mismatch issue, where the consecutiveErrors field in the OpcUA struct is defined as a uint64, but in the test it's being compared to an int value.
resolves #17014
> fix(inputs.opcua): Fix type mismatch in unit test

- plugins/inputs/p4runtime/README.md
- plugins/inputs/passenger/README.md
- plugins/inputs/pf/README.md
- plugins/inputs/pgbouncer/README.md
- plugins/inputs/phpfpm/README.md
- plugins/inputs/ping/README.md
- plugins/inputs/postfix/README.md
- plugins/inputs/postgresql/README.md
- plugins/inputs/postgresql_extensible/README.md
- plugins/inputs/powerdns/README.md
- plugins/inputs/powerdns_recursor/README.md
- plugins/inputs/processes/README.md
- plugins/inputs/procstat/README.md
- plugins/inputs/prometheus/README.md
- plugins/inputs/proxmox/README.md
- plugins/inputs/puppetagent/README.md
This PR adds some metadata to the input plugins starting with o like the version this plugin was introduced, labels and the supported operating systems. Furthermore, the PR unifies the plugin descriptions a bit and uses [Github Markdown alerts](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for notes and other important information.
> docs(inputs): Add plugin metadata and update description for p*

- testutil/tls.go
Simplified readCertificate function - Replaced the two-step process of os.Open() + io.ReadAll() with a single os.ReadFile() call. This eliminates the need to explicitly open and manage the file handle, reducing overhead.
resolves #
> test(testutil): Simplify certificate reading

- .golangci.yml
- plugins/aggregators/basicstats/basicstats.go
- plugins/aggregators/basicstats/basicstats_test.go
- plugins/aggregators/derivative/derivative.go
- plugins/aggregators/derivative/derivative_test.go
- plugins/aggregators/final/final.go
- plugins/aggregators/final/final_test.go
- plugins/aggregators/histogram/histogram.go
- plugins/aggregators/histogram/histogram_test.go
- plugins/aggregators/minmax/minmax.go
- plugins/aggregators/minmax/minmax_test.go
- plugins/aggregators/quantile/algorithms.go
- plugins/aggregators/quantile/quantile.go
- plugins/aggregators/registry.go
- plugins/aggregators/starlark/starlark.go
- plugins/aggregators/valuecounter/valuecounter.go
- plugins/aggregators/valuecounter/valuecounter_test.go
Address findings for [revive:exported ](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported ) in `plugins/aggregators`.
As part of this effort for files from `plugins/aggregators`, the following actions were taken:
- All remaining exported types were given comments in the appropriate form – this does not apply to exported methods that implement "known" plugin interfaces (`Init |SampleConfig |Gather |Start |Stop |GetState |SetState |SetParser |SetParserFunc |SetTranslator |Probe |Add |Push |Reset `).
It is only part of the bigger work …
> chore: Fix linter findings for `revive:exported` in `plugins/aggregators`

- testutil/testutil.go
- testutil/testutil_test.go
Moved localhost to const - Eliminates runtime memory allocation
Made charset a const - Avoids creating the string slice on every function call
Eliminated slice allocation in Mock functions - Direct return of slice literal instead of make + append
Removed nil check in TestMetric - Since this is test code, the panic would happen anyway on nil dereference
Simplified inline tag creation - Direct map literal instead of separate variable
Optimized WithinDefaultDelta - Single comparison instead of two separate if conditions
Used early returns in GetLocalHost - Reduces nesting and potential allocations
Cleaned up OnlyTags filter - Inline function definition for slightly better performance
resolves #
> test(testutil): Improve performance and code quality

- migrations/all/inputs_cisco_telemetry_gnmi.go
- migrations/inputs_cisco_telemetry_gnmi/migration.go
- migrations/inputs_cisco_telemetry_gnmi/migration_test.go
- migrations/inputs_cisco_telemetry_gnmi/testcases/deprecated_alias/expected.conf
- migrations/inputs_cisco_telemetry_gnmi/testcases/deprecated_alias/telegraf.conf
- plugins/inputs/gnmi/gnmi.go
Replace the following plugin alias and provide a migration
```
inputs.cisco_telemetry_gnmi              ERROR since 1.15.0 removal in 1.35.0 has been renamed to 'gnmi'
```
resolves #16944
> feat(migrations): Add migration for inputs.cisco_telemetry_gnmi

- migrations/all/outputs_amqp.go
- migrations/outputs_amqp/migration.go
- migrations/outputs_amqp/migration_test.go
- migrations/outputs_amqp/testcases/minimal/expected.conf
- migrations/outputs_amqp/testcases/minimal/telegraf.conf
- migrations/utils.go
- plugins/outputs/amqp/amqp.go
- plugins/outputs/amqp/amqp_test.go
Removes the deprecated options `database`, `retention_policy`, `url`, and `precision`, providing migrations for these fields
resolves #16936
> feat(migrations): Add migration for outputs.amqp

- plugins/inputs/amqp_consumer/amqp_consumer.go
Mirrored classic queues are deprecated in RabbitMQ 4.0.x and are removed in 4.1.x, leaving quorum queues as the only option for clustering.  In order for the amqp_consumer plugin to create or read from a quorum queue it needs to have the following (string) queue argument:
```
queue_arguments = {"x-queue-type" = "quorum"}
```
This is not currently possible as the queue arguments functionality was coded to only accept int values.
This PR will enable both int and string values to be passed in queue_arguments. 
resolves [17120](https://github.com/influxdata/telegraf/issues/17120)
resolves [6591](https://github.com/influxdata/telegraf/issues/6591)
> feat(inputs.amqp_consumer): Allow string values in queue arguments

- config/config.go
- docs/specs/tsd-005-output-buffer-strategy.md
- models/buffer.go
- models/buffer_disk_test.go
- models/buffer_suite_test.go
- models/running_output.go
Clarifies the option name without breaking existing configurations. Also took the time to clean up the strategy checking code to avoid hardcoding the option names in multiple places
resolves #
> chore(agent): Add "disk_write_through" alias to disk buffer strategy config

- migrations/all/inputs_consul.go
- migrations/inputs_consul/migration.go
- migrations/inputs_consul/migration_test.go
- migrations/inputs_consul/testcases/deprecated_centre_existing/expected.conf
- migrations/inputs_consul/testcases/deprecated_centre_existing/telegraf.conf
- migrations/inputs_consul/testcases/deprecated_datacentre/expected.conf
- migrations/inputs_consul/testcases/deprecated_datacentre/telegraf.conf
- plugins/inputs/consul/consul.go
This PR migrates the `datacentre` option of the plugin and removes the deprecated option.
resolves #16915
> feat(migrations): Add option migration for inputs.consul

- migrations/all/inputs_filecount.go
- migrations/inputs_filecount/migration.go
- migrations/inputs_filecount/migration_test.go
- migrations/inputs_filecount/testcases/deprecated_directory/expected.conf
- migrations/inputs_filecount/testcases/deprecated_directory/telegraf.conf
- migrations/inputs_filecount/testcases/deprecated_directory_duplicate/expected.conf
- migrations/inputs_filecount/testcases/deprecated_directory_duplicate/telegraf.conf
- migrations/inputs_filecount/testcases/deprecated_directory_existing/expected.conf
- migrations/inputs_filecount/testcases/deprecated_directory_existing/telegraf.conf
- plugins/inputs/filecount/filecount.go
This PR migrates the `directory` option of the plugin and removes the deprecated option.
resolves #16918
> feat(migrations): Add option migration for inputs.filecount

- migrations/all/inputs_http.go
- migrations/inputs_http/migration.go
- migrations/inputs_http/migration_test.go
- migrations/inputs_http/testcases/deprecated_bearer_token/expected.conf
- migrations/inputs_http/testcases/deprecated_bearer_token/telegraf.conf
- migrations/inputs_http/testcases/deprecated_bearer_token_existing/expected.conf
- migrations/inputs_http/testcases/deprecated_bearer_token_existing/telegraf.conf
- plugins/inputs/http/http.go
This PR migrates the `bearer_token` option of the plugin and removes the deprecated option.
resolves #16920
> feat(migrations): Add option migration for inputs.http

- migrations/all/inputs_http_response.go
- migrations/inputs_http_response/migration.go
- migrations/inputs_http_response/migration_test.go
- migrations/inputs_http_response/testcases/deprecated_address/expected.conf
- migrations/inputs_http_response/testcases/deprecated_address/telegraf.conf
- migrations/inputs_http_response/testcases/deprecated_address_duplicate/expected.conf
- migrations/inputs_http_response/testcases/deprecated_address_duplicate/telegraf.conf
- migrations/inputs_http_response/testcases/deprecated_address_existing/expected.conf
- migrations/inputs_http_response/testcases/deprecated_address_existing/telegraf.conf
- plugins/inputs/http_response/http_response.go
This PR migrates the `address` option of the plugin and removes the deprecated option.
resolves #16922
> feat(migrations): Add option migration for inputs.http_response

- migrations/all/inputs_internet_speed.go
- migrations/inputs_internet_speed/migration.go
- migrations/inputs_internet_speed/migration_test.go
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download/expected.conf
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download/telegraf.conf
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_existing/expected.conf
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_existing/telegraf.conf
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_false/expected.conf
- migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_false/telegraf.conf
- plugins/inputs/internet_speed/internet_speed.go
This PR migrates the `enable_file_download` option of the plugin and removes the deprecated option.
resolves #16925
> feat(migrations): Add option migration for inputs.internet_speed

- migrations/all/inputs_influxdb_listener.go
- migrations/inputs_influxdb_listener/migration.go
- migrations/inputs_influxdb_listener/migration_test.go
- migrations/inputs_influxdb_listener/testcases/deprecated_max_line_size/expected.conf
- migrations/inputs_influxdb_listener/testcases/deprecated_max_line_size/telegraf.conf
- plugins/inputs/influxdb_listener/influxdb_listener.go
```
inputs.influxdb_listener/max_line_size   ERROR since 1.14.0 removal in 1.35.0 parser now handles lines of unlimited length and option is ignored
```
resolves #16924
> feat(migrations): Add migration for inputs.influxdb_listener

- migrations/all/inputs_cloudwatch.go
- migrations/inputs_cloudwatch/migration.go
- migrations/inputs_cloudwatch/migration_test.go
- migrations/inputs_cloudwatch/testcases/multiple_cloudwatch_instances/expected.conf
- migrations/inputs_cloudwatch/testcases/multiple_cloudwatch_instances/telegraf.conf
- migrations/inputs_cloudwatch/testcases/namespace_duplicate_in_namespaces/expected.conf
- migrations/inputs_cloudwatch/testcases/namespace_duplicate_in_namespaces/telegraf.conf
- migrations/inputs_cloudwatch/testcases/namespace_merge_with_namespaces/expected.conf
- migrations/inputs_cloudwatch/testcases/namespace_merge_with_namespaces/telegraf.conf
- migrations/inputs_cloudwatch/testcases/namespace_to_namespaces/expected.conf
- migrations/inputs_cloudwatch/testcases/namespace_to_namespaces/telegraf.conf
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
```
inputs.cloudwatch/namespace              ERROR since 1.25.0 removal in 1.35.0 use 'namespaces' instead
```
resolves #16914
> feat(migrations): Add migration for inputs.cloudwatch

- migrations/all/inputs_vsphere.go
- migrations/inputs_vsphere/migration.go
- migrations/inputs_vsphere/migration_test.go
- migrations/inputs_vsphere/testcases/deprecated_force_discover_on_init/expected.conf
- migrations/inputs_vsphere/testcases/deprecated_force_discover_on_init/telegraf.conf
- plugins/inputs/vsphere/vsphere.go
- plugins/inputs/vsphere/vsphere_test.go
This PR migrates the `force_discover_on_init` option of the plugin and removes the deprecated option.
resolves #16935
> feat(migrations): Add option migration for inputs.vsphere

- migrations/all/inputs_icinga2.go
- migrations/inputs_icinga2/migration.go
- migrations/inputs_icinga2/migration_test.go
- migrations/inputs_icinga2/testcases/deprecated_object_type/expected.conf
- migrations/inputs_icinga2/testcases/deprecated_object_type/telegraf.conf
- migrations/inputs_icinga2/testcases/deprecated_object_type_duplicate/expected.conf
- migrations/inputs_icinga2/testcases/deprecated_object_type_duplicate/telegraf.conf
- migrations/inputs_icinga2/testcases/deprecated_object_type_existing/expected.conf
- migrations/inputs_icinga2/testcases/deprecated_object_type_existing/telegraf.conf
- plugins/inputs/icinga2/icinga2.go
- plugins/inputs/icinga2/icinga2_test.go
This PR migrates the `object_type` option of the plugin and removes the deprecated option.
resolves #16923
> feat(migrations): Add option migration for inputs.icinga2

- migrations/all/general_common_tls.go
- migrations/general_common_tls/migration.go
- migrations/general_common_tls/migration_test.go
- migrations/general_common_tls/testcases/deprecated_ssl/expected.conf
- migrations/general_common_tls/testcases/deprecated_ssl/telegraf.conf
- migrations/inputs_openldap/testcases/mixed_config/expected.conf
- migrations/inputs_openldap/testcases/mixed_config/telegraf.conf
- plugins/common/tls/config.go
- plugins/common/tls/config_test.go
This PR migrates the common TLS options for all plugins using them. The PR also removes the deprecated options.
resolves #16947
> feat(migrations): Add migration for common.tls ssl options

- migrations/all/inputs_ntpq.go
- migrations/inputs_ntpq/migration.go
- migrations/inputs_ntpq/migration_test.go
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup/expected.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup/telegraf.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_duplicate/expected.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_duplicate/telegraf.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_existing/expected.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_existing/telegraf.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_true/expected.conf
- migrations/inputs_ntpq/testcases/deprecated_dns_lookup_true/telegraf.conf
- plugins/inputs/ntpq/ntpq.go
This PR migrates the `dns_lookup` option of the plugin and removes the deprecated option.
resolves #16929
> feat(migrations): Add option migration for inputs.ntpq

- migrations/all/inputs_http_listener_v2.go
- migrations/inputs_http_listener_v2/migration.go
- migrations/inputs_http_listener_v2/migration_test.go
- migrations/inputs_http_listener_v2/testcases/deprecated_path/expected.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_path/telegraf.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_path_duplicate/expected.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_path_duplicate/telegraf.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_path_existing/expected.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_path_existing/telegraf.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_port/expected.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_port/telegraf.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_port_existing/expected.conf
- migrations/inputs_http_listener_v2/testcases/deprecated_port_existing/telegraf.conf
- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
This PR migrates the `path` and `port` options of the plugin and removes the deprecated options.
resolves #16921
> feat(migrations): Add option migration for inputs.http_listener_v2

- migrations/all/inputs_kube_inventory.go
- migrations/inputs_kube_inventory/migration.go
- migrations/inputs_kube_inventory/migration_test.go
- migrations/inputs_kube_inventory/testcases/bearer_token_string_only/expected.conf
- migrations/inputs_kube_inventory/testcases/bearer_token_string_only/telegraf.conf
- migrations/inputs_kube_inventory/testcases/mixed_tokens/expected.conf
- migrations/inputs_kube_inventory/testcases/mixed_tokens/telegraf.conf
- plugins/inputs/kube_inventory/client.go
- plugins/inputs/kube_inventory/client_test.go
- plugins/inputs/kube_inventory/kube_inventory.go
```
inputs.kube_inventory/bearer_token_string ERROR since 1.24.0 removal in 1.35.0 use 'BearerToken' with a file instead
```
resolves #16926
> feat(migrations): Add migration for inputs.kube_inventory

- migrations/all/inputs_statsd.go
- migrations/inputs_statsd/migration.go
- migrations/inputs_statsd/migration_test.go
- migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags/expected.conf
- migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags/telegraf.conf
- migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags_false/expected.conf
- migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags_false/telegraf.conf
- migrations/inputs_statsd/testcases/deprecated_udp_packet_size/expected.conf
- migrations/inputs_statsd/testcases/deprecated_udp_packet_size/telegraf.conf
- plugins/inputs/statsd/statsd.go
This PR migrates the `parse_data_dog_tags` option of the plugin and removes the deprecated option including the ignored `udp_packet_size` option.
resolves #16934
> feat(migrations): Add option migration for inputs.statsd

- migrations/all/inputs_kubernetes.go
- migrations/inputs_kubernetes/migration.go
- migrations/inputs_kubernetes/migration_test.go
- migrations/inputs_kubernetes/testcases/bearer_token_string_only/expected.conf
- migrations/inputs_kubernetes/testcases/bearer_token_string_only/telegraf.conf
- migrations/inputs_kubernetes/testcases/default_case/expected.conf
- migrations/inputs_kubernetes/testcases/default_case/telegraf.conf
- migrations/inputs_kubernetes/testcases/mixed_tokens/expected.conf
- migrations/inputs_kubernetes/testcases/mixed_tokens/telegraf.conf
- plugins/inputs/kubernetes/kubernetes.go
```
inputs.kubernetes/bearer_token_string    ERROR since 1.24.0 removal in 1.35.0 use 'BearerToken' with a file instead
```
resolves #16927
> feat(migrations): Add migration for inputs.kubernetes

- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua/read_client.go
This issue was raised in [this comment](https://github.com/influxdata/telegraf/pull/16854#issuecomment-2902052562) following our recent work on [handling session invalidation between gather cycles](https://github.com/influxdata/telegraf/pull/16854).
Users with long polling intervals (>1 minute) experience alternating success/failure patterns due to OPC UA session timeouts. The current implementation prevents setting `reconnect_error_threshold = 0` because it forces zero values to default to 1, making it impossible to achieve proactive reconnection behavior.
With long polling intervals, OPC UA sessions often become stale between reads, leading to this cycle:
1. First read fails (stale session detected)
2. Reconnection is forced for next cycle  
3. Second read succeeds (fresh session)
4. …
> feat(inputs.opcua): Allow forcing reconnection on every gather cycle

- cmd/telegraf/main.go
- cmd/telegraf/telegraf.go
This PR implements a debounce mechanism for configuration file watching that batches multiple file changes into a single reload operation.
- **Added `--watch-debounce-interval` CLI flag** to configure the debounce duration (default: 0s for backward compatibility)
- **Implemented timer-based debouncing** in `watchLocalConfig()` function that:
- Starts a timer when the first file change is detected
- Resets the timer if additional changes occur during the wait period  
- Only triggers reload (`SIGHUP`) after the timer expires without interruption
- **Enhanced state tracking** with `reloadPending` flag to prevent unnecessary operations
- **Applied debouncing to all file events**: Modified, Deleted, Truncated, and Created
- **Proper resource cleanup** with timer management in all exit paths
- …
> feat(agent): Add debounce for watch events

- migrations/all/inputs_elasticsearch.go
- migrations/inputs_elasticsearch/migration.go
- migrations/inputs_elasticsearch/migration_test.go
- migrations/inputs_elasticsearch/testcases/http_timeout_to_timeout/expected.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_to_timeout/telegraf.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_auth/expected.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_auth/telegraf.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_existing_timeout/expected.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_existing_timeout/telegraf.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_tls/expected.conf
- migrations/inputs_elasticsearch/testcases/http_timeout_with_tls/telegraf.conf
- migrations/inputs_elasticsearch/testcases/multiple_elasticsearch_instances/expected.conf
- migrations/inputs_elasticsearch/testcases/multiple_elasticsearch_instances/telegraf.conf
- plugins/inputs/elasticsearch/elasticsearch.go
```
inputs.elasticsearch/http_timeout        ERROR since 1.29.0 removal in 1.35.0 use 'timeout' instead
```
resolves #16917
> feat(migrations): Add migration for inputs.elasticsearch

- migrations/all/outputs_remotefile.go
- migrations/outputs_remotefile/migration.go
- migrations/outputs_remotefile/migration_test.go
- migrations/outputs_remotefile/testcases/simple/expected.conf
- migrations/outputs_remotefile/testcases/simple/telegraf.conf
- plugins/outputs/remotefile/remotefile.go
Adds an option migration from `trace` to `log_level`
resolves #16941
> feat(migrations): Add option migration for outputs.remotefile

- plugins/inputs/win_wmi/method.go
This PR attempts to fix the issues seen in #16179. While I'm not able to reproduce the issues, it seems like restricting the threading model for calling the COM object more to a serialized chain for each thread. Furthermore, the PR adds error prefixes to better localize the error and makes error handling more strict. Additionally, the PR frees the `property` resource properly which could otherwise lead to a memory leak.
based on #16781 
resolves #16179
> fix(inputs.win_wmi): Free resources to avoid leaks

- plugins/inputs/lvm/README.md
- plugins/inputs/lvm/lvm.go
- plugins/inputs/lvm/lvm_test.go
Add the `sync_percent` field, which is useful to monitor the progress of lvm raid scrubbing.
resolves #17023
> feat(inputs.lvm): Add sync_percent for lvm_logical_vol

- plugins/inputs/opcua/opcua_test.go
The original test was assuming a default threshold of 2, but our new implementation uses a default of 1. By explicitly setting the threshold to 2 in this test, it will behave as expected and properly test the multi-error scenario.
This way:
1. `TestReconnectErrorThresholdDefaultIntegration` tests the default behaviour (threshold = 1)
2. `TestConsecutiveSessionErrorRecoveryIntegration` tests multi-error scenarios (threshold = 2)
3. `TestReconnectErrorThresholdThreeIntegration` tests the threshold = 3 case
> fix(inputs.opcua): Fix integration test for consecutive session error

- plugins/inputs/snmp_trap/snmp_trap_test.go
This PR fixes the flaky test when checking for an expected error message by waiting for the log-line to be picked up by the logger.
> test(inputs.snmp_trap): Fix flaky test by waiting for the log message to appear

- models/buffer_disk.go
- models/buffer_disk_test.go
This PR fixes an issue occurring when fully emptying a disk-buffers and then adding new metrics. In case of an empty disk-buffer we need to keep one metric around due to restrictions in the upstream library. We do so but mask the remaining entry so it is not sent again. However, when adding more metrics (after the buffer was filled and is fully empty again) we truncate the first entry in the file **but do not reset the mask**, effectively masking the first new added metric.
This leads to loosing the first new metric every time the buffer was completely drained.
This PR correctly resets the mask if a metric was added to an empty buffer, improves readability and adds a unit-test for this case.
related to #16981
> fix(disk-buffer): Correctly reset the mask after adding to an empty buffer

- plugins/inputs/ntpq/ntpq.go
- plugins/inputs/ntpq/testcases/pool_when_headers_as_data/expected.err
- plugins/inputs/ntpq/testcases/pool_when_headers_as_data/expected.out
- plugins/inputs/ntpq/testcases/pool_when_headers_as_data/input.txt
- plugins/inputs/ntpq/testcases/pool_when_headers_as_data/telegraf.conf
The ntpq input plugin was failing to parse output when NTP pool configurations were used, resulting in cryptic parsing errors like:
```
E! [inputs.ntpq] Error in plugin: parsing "when" (when) as duration failed: strconv.ParseInt: parsing "when": invalid syntax
```
This occurred when `ntpq -pn` output contained pool entries that caused field misalignment, where column header names appeared as data values instead of actual field values.
The issue was caused by **field misalignment** in ntpq output where:
1. The parser correctly detected column headers: `["remote", "refid", "st", "t", "when", "poll", "reach", "delay", "offset", "jitter"]`
2. But malformed data lines contained literal column names as values: `["remote", "refid", "st", "t", "when", "poll", "reach", "delay", "offset", …
> fix(inputs.ntpq): Fix ntpq field misalignment parsing errors

- plugins/outputs/nats/README.md
- plugins/outputs/nats/nats.go
- plugins/outputs/nats/nats_test.go
- plugins/outputs/nats/sample.conf
Provides a new param that stops Telegraf from trying to alter a stream that is centrally managed on the nats cluster. This should be backwards compatible with existing configurations and functionality.
https://github.com/influxdata/telegraf/issues/17072
resolves #17072
> feat(output.nats): Allow disabling stream creation for externally managed streams

- metric/deserialize.go
- metric/tracking.go
- models/buffer_disk_test.go
The current code tries to cleanup the tracking information cache during deserialization. That is, if the refcount of the metric is _one_ on deserialization the tracking information is removed from the cache. However, if that metric cannot be sent it is pushed back into (or rather left in) the buffer but now the required tracking information is gone. In turn the metric is skipped due to missing tracking information and the input is potentially never notified.
This PR moves the cache cleanup into the refcount decrementation function and only removes the entry if notifications are sent, i.e. if the refcount reaches zero.
resolves #16981
> fix(disk-buffer): Expire metric tracking information in the right place

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sample.conf
- plugins/outputs/sql/sql.go
- plugins/outputs/sql/sql_test.go
- plugins/outputs/sql/sqlite_test.go
The current approach to writing, issues an INSERT query for every metric in the buffer, which while working, leaves room for improvement.
This commit modifies the Write behavior as follows:
- Sort the metrics fields/tags (to ensure greater cache-hit ratio)
- Add Prepared statements option
This option caches multiple metrics, so they are issued as a single query.
The results depends on the metrics buffer, the metric cardinality, the output server configuration, etc.
That being said, in micro-benchmarks and production deployment, we've seen 10-100x improvement in write performance.
Due to a priority shift, the previous PR (#16725) has been closed, this one continues with the suggestion to use a hash in order to cache INSERT query template.
In this PR, we're using XXHash (indirect …
> feat(outputs.sql): Allow sending batches of metrics in transactions

- plugins/outputs/nats/nats.go
With introducing asynchronous publishing in Jetstream (PR #16582) the Jetstream config was initialized unconditionally. However, this breaks checks that assume the structure is only non-nil if the user actually wants NATS to be used with Jetstreams.
This PR avoids initializing the structure unconditionally in `init` and instead handles the default timeout otherwise.
resolves #17290
> fix(outputs.nats): Avoid initializing Jetstream unconditionally

- testutil/container.go
This PR optimizes Docker container operations in the testutil package to improve performance, particularly in environments with many Docker images or when processing multiple containers.
- Before: `ImageList()` - retrieves ALL Docker images, then searches linearly
- After: `ImageInspect()` - directly inspects the specific image by ID
- Performance: O(1) vs O(n) operation - 90%+ improvement when many images exist
resolves #
> test(testutil): Performance and code quality improvements on container

- metric.go
- metric/metric.go
- models/buffer.go
- models/running_aggregator.go
- models/running_input.go
- models/running_output.go
- models/running_output_test.go
- models/running_processor.go
- plugins/inputs/internal/README.md
- plugins/inputs/internal/internal.go
- plugins/inputs/internal/internal_test.go
- plugins/inputs/internal/sample.conf
- selfstat/selfstat.go
The `inputs.internal` plugin allows to collect statistics about plugins and Telegraf in general. For plugins, these statistics are collected per **plugin type** currently, i.e. if you do have multiple instances of input plugin `A` the statistics are accumulated over all plugins of type `A`. To get individual metrics you currently need to define an `alias` per instance.
This PR changes the plugin models to emit the statistics per plugin instance using the unique `id` of plugins. In the internal input plugin this PR adds a flag to output metrics on a per **plugin instance** basis. By default the metrics are emitted accumulated over the same plugin **type** to be backward compatible.
resolves #15769
> feat(inputs.internal): Allow to collect statistics per plugin instance

- plugins/inputs/internal/internal.go
While reviewing another PR, I noticed this and took the opportunity to improve it.
Replaced three separate `strings.ReplaceAll()` calls with a single `strings.NewReplacer()`, reducing the number of string operations from four to two per call. This simplifies the code and improves efficiency slightly.
> chore(inputs.internal): Replace multiple string operations with single replacer

- docs/specs/tsd-010-labels-and-selectors.md
Provides a spec for Plugin enable and disablement using labels and selectors.
resolves NA
related #16704
> docs(specs): Labels and Selectors for Plugin Enablement

- plugins/inputs/ntpq/README.md
- plugins/inputs/ntpq/sample.conf
removed deprecated option `dns_lookup` from docs
resolves #
> docs(inputs.ntpq): Remove deprecated option

- plugins/inputs/gnmi/handler.go
- plugins/inputs/gnmi/testcases/issue_17412/expected.out
- plugins/inputs/gnmi/testcases/issue_17412/responses.json
- plugins/inputs/gnmi/testcases/issue_17412/telegraf.conf
Telegraf crashes when empty update is received with delete event
resolves #17412
> fix(inputs.gnmi): handle empty updates in gnmi notification response

- go.mod
- go.sum
- plugins/inputs/cloud_pubsub/README.md
- plugins/inputs/cloud_pubsub/cloud_pubsub.go
- plugins/inputs/cloud_pubsub/sample.conf
- plugins/inputs/cloud_pubsub/subscription_gcp.go
- plugins/outputs/cloud_pubsub/README.md
- plugins/outputs/cloud_pubsub/cloud_pubsub.go
- plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
- plugins/outputs/cloud_pubsub/sample.conf
- plugins/outputs/cloud_pubsub/topic_gcp.go
- plugins/outputs/cloud_pubsub/topic_stubbed.go
Migrates from the v1 to v2 of this library, following the [migration guide](https://github.com/googleapis/google-cloud-go/blob/main/pubsub/MIGRATING.md)
Related: #17403, which deprecated the v1 of the library
resolves #
> chore(deps): Migrate from cloud.google.com/go/pubsub to v2

- internal/snmp/config.go
- internal/snmp/wrapper.go
- plugins/inputs/snmp/snmp.go
To debug snmp/gosnmp problems, it's handy to enable verbose logging also in gosnmp.
Remark: You can completely remove the logging code from telegraf using the golang build tag "gosnmp_nodebug".
resolves #17364
> feat(plugins.snmp): Allow debug logging in gosnmp

- cmd/telegraf/main.go
Because:
- PR https://github.com/influxdata/telegraf/pull/7474 enabled processors and aggregators in test mode
- The current help message for the `--test` CLI flag does not reflect that
This PR updates the help output  of the `--test` CLI flag to state processors and aggregators are run as well
resolves #17450
> fix(agent): Update help message for CLI flag --test

- go.mod
- go.sum
Fixes the `collectd.org` dependency no longer working due to the certificate of `collectd.org` expiring
resolves #
> chore(deps): Fix collectd dependency not resolving

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- .golangci.yml
- Makefile
- go.mod
- plugins/outputs/instrumental/instrumental.go
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
- Updates Go to 1.25.0
- Updates golangci-lint to 2.4.0 (necessary with Go upgrade)
- Ignores a new package name linter warning
- Fixes a new go vet warning related to ipv6 addresses
resolves #
> chore: Update to Go 1.25.0

- docs/specs/tsd-011-internal-plugin-statistics.md
This specification defines a way for plugins to report plugin-internal statistics for gathering
by the `inputs.internal` plugin.
related to #4889 
related to #6965 
related to #17275 
related to #17277
> docs(specs): Add specification for collecting plugin-internal statistics

- plugins/inputs/s7comm/s7comm.go
- plugins/inputs/s7comm/s7comm_test.go
Fix String 'extra' parameter
Config:
```toml
fields = [
{name="Line_1", address="DB68.S28.19"},
{name="Line_2", address="DB68.S50.19"},
{name="Line_3", address="DB68.S72.19"},
{name="Line_4", address="DB68.S94.19"},
{name="Line_5", address="DB68.S116.19"},
{name="Line_6", address="DB68.S138.19"},
{name="Line_7", address="DB68.S160.19"},
]
```
Test run:
```
./telegraf.exe --config ./TEST.conf --test --print-plugin-config-source
2025-08-31T08:12:04Z I! Loading config: ./TEST.conf
2025-08-31T08:12:04Z I! Starting Telegraf unknown (customized) brought to you by InfluxData the makers of InfluxDB
2025-08-31T08:12:04Z I! Available plugins: 1 inputs, 0 aggregators, 0 processors, 1 parsers, 1 outputs, 0 secret-stores
2025-08-31T08:12:04Z I! Loaded inputs: s7comm
+--------+------------+
| NAME   | …
```
> fix(inputs.s7comm): Use correct value for string length with 'extra' parameter

- plugins/inputs/diskio/diskio.go
- plugins/inputs/diskio/diskio_test.go
Fixes counter wraparound issue in diskio plugin that was causing io_util, io_svctm, and io_await metrics to occasionally produce massive values in the trillions instead of expected decimal values.
**Root cause**: Lines calculating deltas like `deltaIOTime := float64(io.IoTime - lastValue.IoTime)` don't account for counter wraparound scenarios.
**Before (with bug)**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=2847391847382.3,io_await=9847382947.2,io_svctm=8472947.1 
```
**After (during wraparound detection):**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=0.0,io_await=0.0,io_svctm=0.0
```
**After (normal operation resumes):**
```
diskio,name=sda reads=1234,writes=5678,read_bytes=987654,io_time=12345,io_util=15.2,io_ …
```
> fix(inputs.diskio): Handle counter wrapping in io fields

- go.mod
- go.sum
- plugins/inputs/chrony/chrony.go
Updated `go.mod` to latest [facebook/time](https://github.com/facebook/time/commit/87bed4b54021f847a0f3b60bcedd1fc013aea9f6) (includes my upstream fix).
This introduced a type change (`ReplyNTPSourceName.Name` → string), causing compilation errors.
PR updates:
1. Bump dependency to latest version
2. Fix code to handle string type (`[]byte(sourceName.Name)`, remove redundant `string()` casts)
Chrony plugin now builds and all tests pass.
resolves #17453
> chore(deps): Bump github.com/facebook/time to latest

- models/running_output.go
- models/running_output_test.go
When output plugins (such as `outputs.influxdb_v2`) return partial-write errors additional writes might be triggered if the buffer contains more than batch-size metrics. However, those plugins _might_ return partial-write errors for cases where no metric was written successfully, e.g. if a server is not reachable, to cover cases with serialization errors etc.
This PR updates the retrigger logic to require at least **one** metric to be written successfully to enable retriggering. If no metric was accepted by the output retriggering is disabled until the next flush-interval.
resolves #17415
resolves #17378
> fix(outputs): Retrigger batch-available-events only if at least one metric was written successfully

- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb/http_test.go
- plugins/outputs/influxdb/influxdb.go
- plugins/outputs/influxdb/influxdb_test.go
- plugins/outputs/influxdb/udp.go
- plugins/outputs/influxdb/udp_test.go
This PR adds an internal statistic about the number of metric `bytes_written` . This statistic can be collected using the `internal` input plugin.
based on #17554 
resolves #4889
> feat(outputs.influxdb): Add internal statistics for written bytes

- plugins/outputs/influxdb/http_test.go
- plugins/outputs/influxdb/influxdb.go
- plugins/outputs/influxdb/influxdb_test.go
Fixes crash on init when using the influxdb v1 output plugin
resolves #17603
> fix(outputs.influxdb): Fix crash on init

- plugins/processors/execd/execd.go
This PR adds the same og prefixing functionality which inputs.execd has.
resolves #17569
> feat(processors.execd): Add log prefixing

- plugins/inputs/rabbitmq/README.md
- plugins/inputs/rabbitmq/rabbitmq.go
- plugins/inputs/rabbitmq/rabbitmq_test.go
- plugins/inputs/rabbitmq/sample.conf
- plugins/inputs/rabbitmq/testdata/set1/overview.json
- plugins/inputs/rabbitmq/testdata/set1/queues.json
- plugins/inputs/rabbitmq/testdata/set2/overview.json
- plugins/inputs/rabbitmq/testdata/set2/queues.json
Add type tag to queue to be able to differentiate queues by type 
resolves #17632
> feat(inputs.rabbitmq): Add type tag to queues

- go.mod
- go.sum
This PR removes the temporary `collectd.org` dependency replacement as packages can be downloaded from `collectd.org` again with the certificate being valid.
> chore(deps): Remove collectd replacement

- plugins/parsers/collectd/README.md
- plugins/parsers/grok/README.md
- plugins/parsers/json_v2/README.md
- plugins/parsers/prometheusremotewrite/README.md
- plugins/parsers/wavefront/README.md
This fixes the line-length violations in the READMEs of the parser plugins.
> docs(parsers): Fix line-length in READMEs

- plugins/secretstores/systemd/systemd.go
Systemd versions might contain a dash separator in the version instead of dots. This PR fixes parsing such versions by accounting for dash-separators.
resolves #17734
> fix(secretstores.systemd): Handle dash version separator correctly

- config/config.go
Remove deprecated options `flush_buffer_when_full` and `utc` which were stated to be removed in 1.35.0
> feat(config): Remove deprecated options

- plugins/inputs/zookeeper/README.md
- plugins/inputs/zookeeper/sample.conf
- plugins/inputs/zookeeper/sample.conf.in
- plugins/inputs/zookeeper/zookeeper.go
- plugins/inputs/zookeeper/zookeeper_test.go
Remove `enable_ssl` option which was stated to be removed in 1.35.0.
Meanwhile also deprecate `enable_tls` to use `tls_enable` instead.
> feat(inputs.zookeeper): Remove deprecated option

- plugins/common/opcua/input/input_client.go
- plugins/common/opcua/input/input_client_test.go
- plugins/inputs/opcua/opcua_test.go
- plugins/inputs/opcua_listener/opcua_listener_test.go
Removes the `data_type`, `description` and `tags` options which were stated to be removed in 1.35.0.
> feat(inputs.opcua): Remove deprecated options

- plugins/inputs/win_perf_counters/README.md
- plugins/inputs/win_perf_counters/win_perf_counters.go
Remove `PreVistaSupport` option which was stated to be removed in 1.35.0.
> feat(inputs.win_perf_counters): Remove deprecated options

- plugins/inputs/file/file_test.go
- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
- Adds mutex protection to CSV parser state to enable thread-safe, concurrent usage.
- Resolves potential race conditions when multiple goroutines parse CSV data simultaneously.
- Includes comprehensive concurrency tests to verify thread safety.
resolves #17506
> fix(parsers.csv): Support concurrent usage
