influxdata/telegraf

accumulator.go

This fixes a race condition in the redis plugin where accumulator functions are called from a goroutine. This should allow plugins to use the accumulator concurrently without any issues in the future.

protect accumulator values with a mutex

---

plugins/postgresql/postgresql.go
plugins/redis/redis.go

This is basically done by adding `host` to the metric tags

Fixed: differentiate stats gathered from multiple servers/instances

---

plugins/redis/redis.go
plugins/redis/redis_test.go

These changes allow for someone to collect stats from Redis that has AUTH configured. In order to accomplish this, I changed the logic to accept a URI (i.e. `redis://x:password@localhost`).

convert Redis to use URI, support Redis AUTH

---

plugins/memcached/memcached.go
plugins/memcached/memcached_test.go

Hello guys
Here is my memcached plugin.
It sends the main metrics:
* get_hits
* get_misses
* evictions
* usage of memory (basically it is bytes / limit_maxbytes)
Thank you

Memcached plugin

---

plugins/all/all.go
plugins/kafka_consumer/kafka_consumer.go
plugins/kafka_consumer/kafka_consumer_integration_test.go
plugins/kafka_consumer/kafka_consumer_test.go

Kafka plugin polls a specified Kafka topic and adds messages to InfluxDB. The plugin assumes messages in the topic are JSON objects with 'measurement', 'tags', 'time', & 'values' keys. [Consumer Group](https://github.com/wvanbergen/kafka) is used to talk to the Kafka cluster so multiple instances of telegraf can read from the same topic in parallel.
Running the test requires running Zookeeper & Kafka. The [spotify/kafka](https://registry.hub.docker.com/u/spotify/kafka/) docker container works pretty well for this.
@evanphx 
\cc @marc-barry

Adds Kafka Plugin

---

plugins/rethinkdb/rethinkdb.go
plugins/rethinkdb/rethinkdb_data.go
plugins/rethinkdb/rethinkdb_data_test.go
plugins/rethinkdb/rethinkdb_server.go
plugins/rethinkdb/rethinkdb_server_test.go
plugins/rethinkdb/rethinkdb_test.go

This is a new PR for adding RethinkDB as a plugin due to some branch issues I had locally.

add RethinkDB plugin

---

plugins/system/disk.go

This is a fix for the following error seen in telegraf.log and a corresponding 400 response from influxdb:
2015/07/03 07:00:38 Error in plugins: unable to parse 'io_reads,host=test_host,name=md0,serial= value=1072': missing tag value
Influxdb 0.9.1 now rejects writes with empty tag values. This patch skips tags with no values. A disk serial number does not exist for many devices including md raid arrays and VMs. Other plugins may also want to check for empty tags.
This is my very first golang patch. Please feel free to fix if this is not the best way to do this.

skip disk tags with no value

---

CHANGELOG.md

use influxdb/telegraf instead of influxdb/influxdb in changelog

---

scripts/init.sh

A recent change (120218f) causes the packages to use the telegraf directories instead of the influxdb directories.  The init.sh script is still using the influxdb directories, however causing the packaged service to not start.

update init.sh to use telegraf directories

---

plugins/all/all.go
plugins/rabbitmq/rabbitmq.go
plugins/rabbitmq/rabbitmq_test.go

Collects queue, message, and node statistics from one or many RabbitMQ servers using the management plugin API.
I'm not the most seasoned Go developer, so some parts may not be idiomatic :smiley: I'm open to suggestions on making it better.

Add simple RabbitMQ plugin

---

plugins/redis/redis.go
plugins/redis/redis_test.go

Fix redis : change ending call with "\r\n"

---

agent.go
config.go

I've been doing some testing with Telegraf and noticed that when there is a connection / network problem (towards InfluxDB), Telegraf would hang 15 minutes before the connection actually times out (without collecting metrics!).
This adds a ``timeout`` parameter to the config that will be passed to to the InfluxDB client:
http://godoc.org/github.com/influxdb/influxdb/client#Config
Side note: how is this handles when plugins are taking a long time to collect stats / or are there any plans to avoid that a long running plugin will block the collection of stats?

Add connection timeout configuration for InfluxDB.

---

README.md
etc/config.sample.toml
plugins/all/all.go
plugins/mongodb/mongodb.go
plugins/mongodb/mongodb_data.go
plugins/mongodb/mongodb_data_test.go
plugins/mongodb/mongodb_server.go
plugins/mongodb/mongodb_server_test.go
plugins/mongodb/mongodb_test.go
plugins/mongodb/mongostat.go
testutil/accumulator.go

This PR contains a few additional changes along with a MongoDB plugin:
- `testutil.Accumulator` was using a `Value` and `Values` field and was using a specific one depending on whether the operation was `Add` vs `AddValuesWithTime`, this was causing tests that used `AddValuesWithTime` to not function properly so I removed `Value` and reworked how the `Add` function worked to be more inline with the actual `Accumulator` implementation.
- I copied over [stat_types.go](https://github.com/mongodb/mongo-tools/blob/master/mongostat/stat_types.go) from MongoDB Inc's [mongo-tools](https://github.com/mongodb/mongo-tools) project but removed any code that was requiring another dependency in that project as well as removed any unused code. That project is licensed under Apache V2 so I made note of …

add MongoDB plugin

---

plugins/all/all.go

According to the guidelines:
> To be available within Telegraf itself, plugins must add themselves to the github.com/influxdb/telegraf/plugins/all/all.go file.

Add rethinkdb plugin to all.go

---

Makefile
README.md
circle.yml
docker-compose.yml
plugins/kafka_consumer/kafka_consumer_integration_test.go
plugins/memcached/memcached_test.go
plugins/mysql/mysql_test.go
plugins/postgresql/postgresql_test.go
plugins/redis/redis_test.go
testutil/testutil.go
testutil/testutil_test.go

This PR adds docker container services to telegraf so complex services can be tested in a local environment. 
In addition I've also fixed some tests issues I found on the road while implementing this. 
I've tried to add CI (circle) to the project but due to a bug in Go I was having some issues and decided to postpone it. You can read more about this in this commit: 63552282d70eb1e802812132ffce4c8bf4041d58

Container services

---

testutil/testutil.go
testutil/testutil_test.go

Based on google hangout with Marcos Nils

Fix GetLocalHost testutil function for mac users (boot2docker)

---

package.sh

I thought it would be nice to have a default log rotation set up, in case people forget to set it up.

Add log rotation to /etc/logrotate.d for deb and rpm packages

---

plugins/all/all.go
plugins/lustre2/lustre2.go
plugins/lustre2/lustre2_test.go
testutil/accumulator.go

Lustre is a high performance cluster filesystem (http://lustre.org), used in HPC environments. Usefully, it makes data available in /proc, so here is a plugin to read those /proc files.
Lustre 2.x stores them in a different location to Lustre 1.x, hence the versioned plugin information. The configuration file allows those locations to be overridden for future proofing, and to make testing easier. 
One modification that may be necessary until cross-measurement mathematics is enabled is to store read_bytes and read_calls (and write_*) in the same measurement to get mean bytes per call metrics.

Lustre2 plugin

---

plugins/all/all.go
plugins/disque/disque.go
plugins/disque/disque_test.go

This adds a plugin to collect metrics from Disque. Disque uses the same protocol as Redis, so it's pretty much a clone of the Redis plugin with a few different metrics.

Add Disque plugin

---

plugins/all/all.go
plugins/haproxy/haproxy.go
plugins/haproxy/haproxy_test.go

Request HAProxy stats in CSV format and parse only below value:
```
QCUR:
SCUR:
SMAX:
BIN:
BOUT:
RATE:
RATE_MAX:
STOT:
HRSP_1xx:
HRSP_2xx:
HRSP_3xx:
HRSP_4xx:
EREQ:
ERESP:
ECON:
REQ_RATE:
REQ_RATE_MAX:
REQ_TOT
```
Metric name is column name in CSV file as above to avoid confusion and keep it in-sync with HAProxy column. Proxy name and backend, service are passed as tag. Example(when run in test mode)
```
> [host="lb.haproxy.com" proxy="be_forbidden" sv="BACKEND"] haproxy_rate value=0
> [host="lb.haproxy.com" proxy="stats" sv="FRONTEND"] haproxy_scur value=1
> [host="lb.haproxy.com" proxy="stats" sv="FRONTEND"] haproxy_smax value=1
> [host="lb.haproxy.com" proxy="stats" sv="FRONTEND"] haproxy_stot value=2
> [host="lb.haproxy.com" proxy="stats" sv="FRONTEND"] haproxy_bin value=58504
> …
```

HAProxy plugin

---

plugins/all/all.go
plugins/exec/exec.go
plugins/exec/exec_test.go

Adds an `exec` plugin suggested in #24. The plugin reads flattened metrics from one or more commands that output JSON to stdout.
Collaborated with @jpalay

Add exec plugin

---

plugins/all/all.go
plugins/leofs/leofs.go
plugins/leofs/leofs_test.go

This adds a plugin to collect metrics from [LeoFS](https://github.com/leo-project/leofs). 
As LeoFS disclose metrics via SNMP, I have used [snmpwalk](http://www.net-snmp.org/docs/man/snmpwalk.html) for making it easy to implement.

Add LeoFS plugin

---

etc/logrotate.d/telegraf
package.sh

Take 2. The .deb file installs /etc/logrotate.d/telegraf.  I don't have a RedHat based system to test on, but the rpm definitely has the file in it, I've tested with `rpm2cpio telegraf*rpm | cpio -idmv`.

Log rotation configuration for rpm/deb

---

.gitignore
agent.go
cmd/telegraf/telegraf.go
config.go
etc/config.sample.toml
outputs/all/all.go
outputs/influxdb/influxdb.go
outputs/registry.go
testdata/influx.toml

This is sort of a phase one to create an `outputs` configuration in order to send metrics to more than InfluxDB and begins to address https://github.com/influxdb/telegraf/issues/38.
I'd love some feedback here!

Initial implementation for multiple outputs

---

CHANGELOG.md
agent.go
agent_test.go
cmd/telegraf/telegraf.go
testdata/telegraf-agent.toml

Hello,
I just add a new option to filter plugins to enable at startup.
In the future, we will have a lot of plugins into all.go and into config.toml.
A solution would be to have many differents config files.
Another one could be to use this option to filter the plugins.
```telegraf --config telegraf.toml -filter mysql:redis```
Maybe I am wrong but If I want to use the same config file and activate only one plugin, the filter option could be nice. Else I must duplicate config file and delete other plugin to disable them.
The config file share common configuration so it is nice to avoid to duplicate it.
Thanks for reading this PR.
Nicolas

New option to filter the plugins to run at startup

---

.gitignore
CHANGELOG.md
agent.go
cmd/telegraf/telegraf.go
config.go
etc/config.sample.toml
outputs/all/all.go
outputs/influxdb/influxdb.go
outputs/registry.go
testdata/influx.toml
testdata/telegraf-agent.toml

\cc @jipperinbham @pauldix @toddboom 
This PR supports Telegraf outputting data to multiple locations beyond just InfluxDB. This is a breaking change that requires some changes to the .toml Telegraf configuration file, basically users will need to change their `influxdb` entry from this:
```
[influxdb]
url = "http://localhost:8086"
database = "telegraf"
```
to this
```
[outputs]
[outputs.influxdb]
url = "http://localhost:8086"
database = "telegraf"
```
You can find more details in @jipperinbham's original PR here: https://github.com/influxdb/telegraf/pull/107

Merge of PR #107, Allow Telegraf to output data to multiple locations beyond InfluxDB, such as Riemann or Kafka

---

README.md
package.sh

Update the README to reflect that, as well as some changes to the packaging script, which will now require that the builder tags and pushes tag to the repo before running. It will auto-get the version number from `git describe --always --tags`
/cc @beckettsean @gunnaraasen notifying you guys because I changed the 0.1.4 .deb and .rpm packages that are on Amazon S3. This means that users of Influx 0.9.2 can now have the more recent Telegraf plugins and multi-output features, and will need to update their config files accordingly (see README)

Telegraf version 0.1.4 is now compatible with the "new" config files & InfluxDB 0.9.2

---

plugins/system/ps/disk/disk_windows.go

A long way from an automated build and package, but at least 'go build' works on Windows now - tested on Windows 10.

Get disk usage stats working on windows

---

CHANGELOG.md
package.sh

/cc @beckettsean @gunnaraasen how do we feel about distributing linux binaries of telegraf? I was thinking that this might be good for people who want to try out telegraf without installing a .deb or .rpm which also installs an init service on the server.
Also nice for people who just want to manage the service themselves

package.sh: upload raw binaries to S3

---

CHANGELOG.md
agent.go
cmd/telegraf/telegraf.go
config.go

Closes #159
Closes #162
/cc @pauldix second precision writes
/cc @beckettsean write data in UTC by default, provide option for local

Write data in UTC by default and use 's' precision

---

plugins/rabbitmq/rabbitmq.go
plugins/system/ps/net/net_darwin.go

Fixes #183 
@rvrignaud Adding a configuration tag for the rabbitmq server, as well as adding in the URL tag, let me know if this does it

Add a server name tag to the RabbitMQ server list

---

scripts/package.sh

The test to see which version of `useradd` is installed uses 'bashisms' that fail on Ubuntu due to the fact that `/bin/sh` is symlinked to Dash, causing the telegraf account to be created without the `--system` option ever being passed.
This change amends the syntax so that it's POSIX-compatible and more portable as a result.  Fixes #231.

Fix conditional test against useradd so it's compatible with Dash

---

CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md
accumulator.go
agent.go
agent_test.go
config.go
outputs/amqp/amqp.go
outputs/amqp/amqp_test.go
outputs/datadog/datadog.go
outputs/datadog/datadog_test.go
outputs/influxdb/influxdb.go
outputs/kafka/kafka.go
outputs/kafka/kafka_test.go
outputs/mqtt/mqtt.go
outputs/opentsdb/opentsdb.go
outputs/opentsdb/opentsdb_test.go
outputs/registry.go
plugins/exec/exec.go
plugins/kafka_consumer/kafka_consumer.go
plugins/kafka_consumer/kafka_consumer_integration_test.go
plugins/mongodb/mongodb_data.go
plugins/registry.go
plugins/zookeeper/zookeeper_test.go
testutil/accumulator.go
testutil/testutil.go

Utilizing new client and overhauling Accumulator interface

---

agent.go
config.go
etc/config.sample.toml

Add support for retrying output writes, using independent threads

---

agent.go
config.go

This will provide the ability to specify multiple outputs for a single
type of output.
In essence, allowing this:
```
[outputs]
[[outputs.influxdb]]
urls = ["udp://localhost:8089"]
database = "udp-telegraf"
[[outputs.influxdb]]
urls = ["http://myhost:8086"]
database = "telegraf"
[[outputs.kafka]]
brokers = ["192.168.99.100:9092"]
topic = "telegraf"
```
closes #335

Allow users to specify outputs as lists

---

CHANGELOG.md
agent.go
config.go
config_test.go
testdata/subconfig/monitor_grafana.conf
testdata/subconfig/monitor_influxdb.conf
testdata/subconfig/procstat.conf

@gotyaoi, I believe this is a change that you made for supporting directories. Can you explain why slices get appended but all other data structures get replaced here? If there isn't a strong reason to keep it I'd rather it just have a consistent behavior for all data types
I'm having an issue now where we're getting all slices doubled from the config to structs

Dont append to slices in mergeStruct

---

CHANGELOG.md
README.md
config_test.go
outputs/influxdb/influxdb.go
plugins/kafka_consumer/kafka_consumer.go
plugins/kafka_consumer/kafka_consumer_integration_test.go
plugins/kafka_consumer/kafka_consumer_test.go
plugins/statsd/statsd.go
testdata/single_plugin.toml
testdata/subconfig/memcached.conf
testdata/telegraf-agent.toml

@panda87, this is a work in progress, any feedback appreciated

Kafka plugin refactor

---

accumulator.go
plugins/prometheus/prometheus.go

fixes #389 
@rvignaud this will fix the error messages and panic that you were seeing, it will simply skip measurements that have NaN fields.

Skip measurements with NaN fields

---

CHANGELOG.md
plugins/system/disk.go

io plugin, add an 'unknown' tag when the serial number can't be found

---

plugins/memcached/memcached.go
plugins/memcached/memcached_test.go

And unit test it using a sample response string. This will make it
easier to see what other metrics are available to the plugin for adding
future metrics.

memcached plugin. Break out metric parsing into it's own func

---

plugins/system/system.go

Convert uptime to float64 for backwards compatability.

---

CHANGELOG.md
plugins/system/mock_PS.go
plugins/system/net.go
plugins/system/ps.go
plugins/system/system_test.go

This add the system wide network protocol stats to the `net` plugin.
Uses a new method in `gopsutil` see https://github.com/shirou/gopsutil/pull/109
Basically exposes all the data in `/proc/net/snmp` as
`net_PROTOCOL_COLNAME`
for example:
Excerpt from /proc/net/snmp
```
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 67688650 3723361 58108572 124599763 58108572 0 0 318767
```
adds measurement `net_udp_rcvbuferrors` with value 58108572 etc.

Add protocol stats to the network plugin

---

.gitignore
CONFIGURATION.md
build.py
scripts/init.sh
scripts/post-install.sh
scripts/pre-install.sh
scripts/telegraf.service

Restructured the package's filesystem hierarchy:
- Binaries are now located at `/usr/bin/`
- Configuration is now located at `/etc/telegraf`
In addition:
- Added a `build.py` script to mirror InfluxDB and Kapacitor.
- A few fixes and updates to the `init.sh` script
- Minor update to the `telegraf.service` unit file to correct usage of variable
- Added a `post-install.sh` and `pre-install.sh` to handle upgrades and other housekeeping

WIP - Package Updates

---

plugins/inputs/exec/README.md

also mentioned name_override and name_prefix on top of name_suffix

interval options should have string value

---

CHANGELOG.md
agent.go
internal/config/config.go

Collection interval random jittering

---

agent.go
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go
plugins/inputs/procstat/spec_processor.go

Include CPU usage percent with procstat data

---

plugins/inputs/statsd/statsd.go

statsd: If parsing a value to int fails, try to float and cast to int

---

Godeps
internal/config/config.go

We are unifying the way that we handle configuration across the products
into the influxdata/config package. This provides the same API as
naoina/toml that was used previously, but provides some additional
features such as support for documenting generated TOML configs as well
as support for handling default options. This replaces all usage of
naoina/toml with influxdata/config.

Change configuration package to influxdata/config

---

CHANGELOG.md
agent.go

Fix some inputs panic will lead to the telegraf exit

---

plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go

Include all tag values in graphite output

---

CHANGELOG.md
plugins/inputs/exec/README.md
plugins/inputs/exec/exec.go
plugins/inputs/exec/exec_test.go

Allow exec plugin to parse line-protocol

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

ping plugin: use -W for linux, -t for bsd/darwin

---

CHANGELOG.md
CONFIGURATION.md
etc/telegraf.conf
internal/config/config.go
internal/config/testdata/telegraf-agent.toml

closes #662 
This is to workaround the following issue with the naoina toml parser: https://github.com/naoina/toml/issues/18

Change [tags] to [global_tags] to deal with toml bug

---

CHANGELOG.md
plugins/outputs/riemann/riemann.go

* Customizable 'separator' option instead of hard-coded '_'
* String values are sent as "State" instead of "Metric", preventing
Riemann from rejecting them
* Riemann service name is set to an (ugly) combination of input name &
(sorted) tags' values...this allows connecting different events for
the same input together on the Riemann side
closes #642

Updated Riemann output:

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

I made this optional by adding config option.  Updated test data to give sensible percentages.

Add calculated cpu and memory percentages to docker input (via config option)

---

CHANGELOG.md
Godeps
README.md
plugins/inputs/EXAMPLE_README.md
plugins/inputs/all/all.go
plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
plugins/inputs/nats_consumer/README.md
plugins/outputs/mqtt/mqtt.go
plugins/parsers/graphite/parser.go
plugins/parsers/influx/parser.go
plugins/parsers/json/parser.go
plugins/parsers/registry.go

[WIP] MQTT Consumer Input plugin

---

plugins/outputs/file/file_test.go

Add Serializer plugins, and 'file' output plugin

---

agent/agent.go
etc/telegraf.conf
input.go
internal/config/config.go
internal/models/running_output.go
plugins/inputs/github_webhooks/github_webhooks.go
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/kafka_consumer/kafka_consumer_integration_test.go
plugins/inputs/kafka_consumer/kafka_consumer_test.go
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
plugins/inputs/nats_consumer/nats_consumer.go
plugins/inputs/nats_consumer/nats_consumer_test.go
plugins/inputs/statsd/statsd.go
testutil/accumulator.go

Flush based on buffer size rather than time

---

plugins/inputs/system/cpu.go
plugins/outputs/file/file.go

Also if outputs.file is empty, write to stdout
closes #720

Provide default args: percpu=true and totalcpu=true for cpu plugin

---

Makefile
etc/telegraf.conf
plugins/outputs/influxdb/influxdb.go

default to 5s instead, since even if it times out we will cache the
points and move on
closes #685

InfluxDB output should not default to 'no timeout' for http writes

---

CHANGELOG.md
README.md
scripts/build.py

closes #752
closes #750
@rossmcdonald

Fix deb and rpm packages

---

plugins/inputs/all/all.go
plugins/inputs/udp_listener/README.md
plugins/inputs/udp_listener/udp_listener.go
plugins/inputs/udp_listener/udp_listener_test.go

@lexmag and I added the UDP line-protocol service input discussed in #481. The PR fully implements the UDP service input but is still lacking tests and a README; we're working on both but we would like some feedback on the current implementation :).

Add generic UDP line-protocol service input

---

CHANGELOG.md
scripts/build.py
scripts/post-install.sh

Some major changes to the `build.py` build script, including:
- breaking ARM platforms out as different architectures (fixes https://github.com/influxdata/telegraf/issues/708)
- improves debug output
- removes `pkgarch` and `goarm` build arguments
- moves nightly versioning to use a `<version>~n<epoch>` over `<version>.n<epoch>`
- removes zip as a packaging target due to FPM's poor support of zip
- merges most changes from the InfluxDB and Kapacitor build scripts (more information [here](https://github.com/influxdata/influxdb/pull/5596))
- added a permissions check to the post-install script (fixes https://github.com/influxdata/telegraf/issues/713)

Build Updates

---

plugins/inputs/phpfpm/child.go
plugins/inputs/phpfpm/fcgi.go
plugins/inputs/phpfpm/fcgi_client.go
plugins/inputs/phpfpm/fcgi_test.go
plugins/inputs/phpfpm/phpfpm.go

closes #816 
@kureikain can you take a look at this? I'm breaking these out into separate files, and the main change I'm making is to remove this defer close line completely: https://github.com/influxdata/telegraf/compare/cs816?expand=1#diff-20598882a40d49d97234c692fcab8696L304
I don't quite understand how that could work, Why would you want to close the connection after every request? Was that intentional?

Break out fcgi code into orig Go files, don't close after request

---

CHANGELOG.md
README.md
etc/telegraf.conf
plugins/inputs/system/KERNEL_README.md
plugins/inputs/system/kernel.go
plugins/inputs/system/kernel_test.go

Add a "kernel" plugin for /proc/stat statistics

---

CHANGELOG.md
plugins/inputs/EXAMPLE_README.md
plugins/inputs/all/all.go
plugins/inputs/ntpq/README.md
plugins/inputs/ntpq/ntpq.go
plugins/inputs/ntpq/ntpq_test.go
plugins/inputs/ntpq/ntpq_windows.go

Input plugin for running ntp queries

---

CHANGELOG.md
plugins/inputs/httpjson/httpjson.go
plugins/inputs/httpjson/httpjson_test.go

Fix bug with httpjson client pointer receiver

---

plugins/outputs/librato/librato.go

When attempting to send metrics from `rabbitmq` input, the `@` character which is part of the `node_name` tag causes an issue. This seemed like the _simplest_ fix but am open to other ways.

replace @ character with - for librato

---

plugins/outputs/librato/librato.go
plugins/serializers/graphite/graphite.go

Because graphite has certain restrictions on what characters can be in the metric name (i.e. `/`, `@`, ` `), the graphite serializer should be responsible for substituting those characters with good alternatives.

sanitize known issue characters from graphite tag name

---

CHANGELOG.md
plugins/inputs/statsd/statsd.go
plugins/inputs/statsd/statsd_test.go

Deprecate statsd convert_names option, expose separator

---

CHANGELOG.md
docs/CONFIGURATION.md
etc/telegraf.conf
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/single_plugin_env_vars.toml

config: parse environment variables in the config file

---

CHANGELOG.md
plugins/inputs/system/processes.go
plugins/inputs/system/processes_test.go

processes plugin: fix case where there are spaces in cmd name

---

CHANGELOG.md
docs/DATA_FORMATS_OUTPUT.md
etc/telegraf.conf
internal/config/config.go
plugins/outputs/graphite/README.md
plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go
plugins/outputs/librato/librato.go
plugins/outputs/librato/librato_test.go
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go
plugins/serializers/registry.go

closes #925
closes #879 
This is a WIP, still TODO:

Create a template system for the graphite serializer

---

CHANGELOG.md
plugins/inputs/influxdb/README.md
plugins/inputs/influxdb/influxdb.go
plugins/inputs/influxdb/influxdb_test.go

Add memstats to the influxdb input plugin

---

scripts/init.sh

Changed `nohup` fallback command to use `sudo -u` so that Telegraf doesn't run as the root user.

Init Script Update

---

CHANGELOG.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

this would make container_id a _field_
also renaming cont_name and cont_image to container_name and
container_image.
closes #1014

Remove cont_id tag from docker plugin

---

CHANGELOG.md
agent/accumulator.go
plugins/inputs/cassandra/cassandra.go
plugins/inputs/cassandra/cassandra_test.go
plugins/inputs/disque/disque.go
plugins/inputs/rethinkdb/rethinkdb_server.go
plugins/inputs/rethinkdb/rethinkdb_server_test.go

closes #1054
This affects tags in the following plugins:
- cassandra
- disque
- rethinkdb

Don't allow inputs to overwrite host tag

---

CHANGELOG.md
plugins/outputs/datadog/datadog.go

Don't replace _ with . in datadog names

---

CHANGELOG.md
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go
plugins/inputs/procstat/spec_processor.go

procstat: Add user, pidfile, pattern & exe tags

---

plugins/inputs/win_perf_counters/README.md

Network metrics are pretty important and the block adds a couple with a link to the names for more. This adds a block with a few counters to the Generic Queries examples in plugins/inputs/win_perf_counters/README.md

Added Network Interface Object block to win_perf_counters Generic Queries examples

---

CHANGELOG.md
etc/telegraf.conf
plugins/inputs/all/all.go
plugins/inputs/filestat/README.md
plugins/inputs/filestat/filestat.go
plugins/inputs/filestat/filestat_test.go
plugins/inputs/filestat/testdata/test.conf

filestat input plugin

---

CHANGELOG.md
scripts/post-install.sh

closes #1022 
WIP, need to investigate if this is the proper way to handle systemd errors

Ignore errors in systemd

---

CHANGELOG.md
plugins/inputs/phpfpm/phpfpm.go

Fix leaky tcp connections in phpfpm plugin

---

Godeps
internal/models/running_output.go
plugins/inputs/all/all.go
plugins/inputs/filestat/filestat.go
plugins/inputs/tail/README.md
plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go
plugins/inputs/tcp_listener/tcp_listener.go
plugins/inputs/udp_listener/udp_listener.go

Tail input plugin

---

CHANGELOG.md
etc/telegraf.conf
internal/buffer/buffer.go
internal/buffer/buffer_test.go
internal/config/config.go
internal/models/running_output.go
internal/models/running_output_test.go

this is a WIP, todo:
benchmarks are looking good so far, ~1.8x faster performance on Add & Write:
this PR:
```
% go test ./internal/models/... -bench=. -run=Benchmark
PASS
BenchmarkRunningOutputAddWrite-4        	10000000	       222 ns/op
```
same benchmark on master:
```
% go test ./internal/models/... -bench=. -run=Benchmark
PASS
BenchmarkRunningOutputAddWrite-4	 5000000	       395 ns/op
```

Performance refactor of running_output buffers

---

plugins/inputs/cassandra/cassandra.go

fixes #1102 
cc @subhachandrachandra can you review this? This fixes a panic that can easily happen if users don't have the exact url correct in their config, but also I'm generalizing it to include any metric that begins with org.apache.cassandra because at least one of our users has it at `.net` instead of `.metrics` (see #1102)

Cassandra: update plugin supported prefix & fix panic

---

plugins/outputs/opentsdb/opentsdb.go
plugins/outputs/opentsdb/opentsdb_test.go

Sanitize invalid opentsdb characters

---

CHANGELOG.md
cmd/telegraf/telegraf.go
docs/CONFIGURATION.md
internal/config/config.go

precedence will be:
1. --config command-line option
2. $TELEGRAF_CONFIG_PATH
3. $HOME/.telegraf/telegraf.conf
4. /etc/telegraf/telegraf.conf

Support default config paths

---

internal/internal.go
internal/internal_test.go
plugins/inputs/exec/exec.go
plugins/inputs/ipmi_sensor/command.go
plugins/inputs/leofs/leofs.go
plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go
plugins/inputs/sysstat/sysstat.go

First is to write an internal CombinedOutput and Run function with a
timeout.
Second, the following instances of command runners need to have timeouts:
plugins/inputs/ping/ping.go
125:	out, err := c.CombinedOutput()
plugins/inputs/exec/exec.go
91:	if err := cmd.Run(); err != nil {
plugins/inputs/ipmi_sensor/command.go
31:	err := cmd.Run()
plugins/inputs/sysstat/sysstat.go
194:	out, err := cmd.CombinedOutput()
plugins/inputs/leofs/leofs.go
185:	defer cmd.Wait()
plugins/inputs/sysstat/sysstat.go
282:	if err := cmd.Wait(); err != nil {
closes #1067

Implement timeouts for all exec command runners

---

CHANGELOG.md
plugins/outputs/kafka/kafka.go

Kafka output: set max_retry=3 & required_acks=-1 as defaults

---

CHANGELOG.md
plugins/inputs/exec/README.md
plugins/inputs/exec/exec.go

This reverts commit 6381efa7ced31e772b3b128f84706dbb31a070f0.
@peekeri your change breaks existing exec behavior, ie, this command has no glob match and gets ignored:
```
commands = ["/usr/bin/telegraf version"]
```

Revert "exec plugin: allow using glob pattern in command list"

---

etc/telegraf.conf
plugins/inputs/all/all.go
plugins/inputs/ceph/README.md
plugins/inputs/ceph/ceph.go
plugins/inputs/ceph/ceph_test.go

- records metrics from the output of mon and osd socket perf
dumps.

Implemented ceph storage metrics collector

---

plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/spec_processor.go

Being able to override the process_name in the procstat module is useful for daemonized perl, ruby, erlang etc. processes. This allows for manually setting process_name rather than it being set to the interpreter/VM of the process.

Procstat input plugin - functionality for overriding of process_name

---

CHANGELOG.md
agent/accumulator.go

don't overwrite host tags in plugins

---

CHANGELOG.md
Godeps
plugins/inputs/procstat/spec_processor.go
plugins/inputs/system/cpu.go
plugins/inputs/system/cpu_test.go
plugins/inputs/system/disk_test.go
plugins/inputs/system/mock_PS.go
plugins/inputs/system/net_test.go
plugins/inputs/system/ps.go
plugins/inputs/system/system.go

Update gopsutil dependency

---

CHANGELOG.md
agent/accumulator.go
agent/agent.go

currently the input interface does not have any methods for killing a
running Gather call, so there is nothing we can do but log a "FATAL
ERROR" and move on. This will at least give some visibility into the
plugin that is acting up.
Open questions:
- should the telegraf process die and exit when this happens? This might
be a better idea than leaving around the dead process.
- should the input interface have a Kill() method? I suspect not, since
most inputs wouldn't have a way of killing themselves anyways.
closes #1230

Set a timeout for calls to input.Gather

---

CHANGELOG.md
agent/agent.go
etc/telegraf.conf
internal/internal.go
plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go
plugins/inputs/net_response/README.md
plugins/inputs/net_response/net_response.go
plugins/inputs/net_response/net_response_test.go

Also changing the net_response and http_response plugins to only accept
duration strings for their timeout parameters. This is a breaking config
file change.
closes #1214

Utilize timeout in net_response plugin.

---

CHANGELOG.md
README.md
plugins/inputs/all/all.go
plugins/inputs/chrony/README.md
plugins/inputs/chrony/chrony.go
plugins/inputs/chrony/chrony_notlinux.go
plugins/inputs/chrony/chrony_test.go

Newer linux systems (RHEL7/CENTOS7) use [chrony](https://chrony.tuxfamily.org/) as ntp daemon. This PR adds support for chrony stats in addition to ntpq stats.

add chrony support

---

CHANGELOG.md
scripts/telegraf.service

There has been a change in systemd service to start telegraf which does not work anymore with the `KillMode=process` setting.
If you keep that KillMode, a stop just kills the bash, but keeps telegraf service. With that setting, it is possible to run serveral telegraf instances.
With the old setting:
```
$ systemctl start telegraf
```
you see following process:
```
/bin/sh -c /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d  >>/var/log/telegraf/telegraf.log 2>>/var/log/telegraf/telegraf.log
```
Then with:
```
$ systemctl stop telegraf
```
the service is still running.
```
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
```
Only the parent bash got killed. If you start telegraf with sytemd …

fix telegraf service

---

CHANGELOG.md
README.md
plugins/inputs/all/all.go
plugins/inputs/rollbar_webhooks/README.md
plugins/inputs/rollbar_webhooks/rollbar_webhooks.go
plugins/inputs/rollbar_webhooks/rollbar_webhooks_events.go
plugins/inputs/rollbar_webhooks/rollbar_webhooks_events_json_test.go
plugins/inputs/rollbar_webhooks/rollbar_webhooks_test.go

---
[Rollbar](https://rollbar.com) is an error tracking service. You can setup webhooks to be notified on several events like when a new error occurs or when you deploy your application.
This plugin allow to collect these events. It's highly inspired from the `github_webhooks` inputs plugin service.
All webhook events are not implemented, but it shouldn't be difficult to add more.

Add input plugin for rollbar service.

---

CHANGELOG.md
internal/config/aws/credentials.go
plugins/inputs/cloudwatch/README.md
plugins/inputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/README.md
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/kinesis/README.md
plugins/outputs/kinesis/kinesis.go

Rebased & retargeted version of https://github.com/influxdata/telegraf/pull/1155

Consolidate AWS credentials, Cloudwatch dimension wilcards

---

CHANGELOG.md
plugins/inputs/system/kernel.go

kernel: use strconv.ParseInt instead of strconv.Atoi

---

CHANGELOG.md
plugins/inputs/influxdb/influxdb.go

influxdb input: Use non-panicking type assertion

---

CHANGELOG.md
scripts/telegraf.service

PR #1252 works well for stopping Telegraf, but reloading cause Telegraf to exit:
```
$ dpkg -l telegraf 
ii  telegraf       0.13.1~a8334c3-0
$ ps waux|grep telegraf
telegraf 13662  0.0  0.0   4508   756 ?        Ss   11:31   0:00 /bin/sh -c /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d  >>/var/log/telegraf/telegraf.log 2>>/var/log/telegraf/telegraf.log
telegraf 13663  0.3  0.2 227988 23380 ?        Sl   11:31   0:00 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
$ sudo systemctl reload telegraf
$ sudo systemctl status telegraf
[...]
Active: inactive (dead) since jeu. 2016-05-26 11:33:08 CEST; 3s ago
[...]
Main PID: 13662 (code=killed, signal=HUP)
$ ps waux|grep telegraf
nothing
```
This is …

Fix reloading Telegraf under systemd

---

CHANGELOG.md
plugins/inputs/system/processes.go

I've sometime the following error:
```
$ grep telegraf /var/log/syslog |grep Error
May 26 06:28:20 hostname telegraf[15844]: 2016/05/26 06:28:20 Error in input [processes]: open /proc/16683/stat: no such file or directory
May 26 07:21:30 hostname telegraf[15844]: 2016/05/26 07:21:30 Error in input [processes]: read /proc/19975/stat: no such process
May 26 09:29:40 hostname telegraf[15844]: 2016/05/26 09:29:40 Error in input [processes]: read /proc/27969/stat: no such process
May 26 09:40:40 hostname telegraf[15844]: 2016/05/26 09:40:40 Error in input [processes]: read /proc/28637/stat: no such process
```
This cause the processes plugin to skip all metrics for the affected collection round.
This PR add a second file.IsDir() during error handling, if path is no longer a directory then the …

processes: Don't return error if process exited

---

plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongostat.go

Although I am running mongo with replicas, telegrafs mongo input plugin reported:
`2016/05/26 02:32:28 Not gathering replica set status, member not in replica set`
Patching the error message showed:
`Unsupported document type for unmarshalling: bson.MongoTimestamp`
Changing optime to optimeDate fixes that.  Has been a mismatch or it was recently changed? I am using MongoDB 3.2.6.

Use optimeDate to get MongoTimestamp (mongo input plugin).

---

etc/telegraf.conf
plugins/inputs/apache/README.md
plugins/inputs/apache/apache.go

- [x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
Why? Since most users will run this plugin on the destination host, the default http://localhost/server-status?auto is just fine and will be the default if urls is not defined simplifying the telegraf configuration for those users. They just need to add [[inputs.apache]] to be done.

Made the apache input’s urls parameter optional by using a reasonable default user input

---

CHANGELOG.md
internal/limiter/limiter.go
internal/limiter/limiter_test.go
plugins/inputs/cloudwatch/cloudwatch.go

closes #1197
cc @goller It's not entirely clear to me what the API request limit is for GetMetricStatistics, but I believe it is 10 per second. Do you think you can test with this change and see how it goes for you?
other question is: why is getting limited by AWS a problem? Would it be better to rely on their limiting rather than hardcoding in a value ourselves?

Limit GetMetricStatistics to 10 per second

---

CHANGELOG.md
agent/agent.go
agent/agent_test.go
internal/config/config.go
internal/internal.go
internal/internal_test.go

use a common function between collection_jitter and flush_jitter. which
creates the same behavior between the two options.
going forward, both jitters will be random sleeps that get re-evaluated
at runtime for every interval (previously only collection_jitter did
this)
also fixes behavior so that both jitters will exit in the event of a
process exit.
closes #1296

Refactor collection_jitter and flush_jitter

---

CHANGELOG.md
Godeps
README.md
plugins/inputs/all/all.go
plugins/inputs/consul/README.md
plugins/inputs/consul/consul.go
plugins/inputs/consul/consul_test.go

This is the Input Plugin for gathering metrics on Consul's Health Checks. The data it pulls from Consul are not someone would call stats but they can be used to monitor services using Kapacitor. More appropriate stats can be already sent using StatsD reporter built-in into Consul itself.
API which is used to poll the data is [here](https://www.consul.io/docs/agent/http/health.html#health_state)

Added Consul health checks state monitoring.

---

.gitattributes

cc @daviesalex @wrigtim
this is the gitattributes change I had mentioned a couple weeks back. Should make keeping your fork up to date a bit easier. With this, git should always take care of merging the all.go files automatically.

update gitattributes for easier fork mngmnt

---

CHANGELOG.md

@sparrc  I forget to add an entry to  ChangeLOG for Graylog input plugin, sorry I miss that in the original pull request

Add graylog input pluging  entry to change log

---

CHANGELOG.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

See PR #1315 
Redis add a "database" tag on global metrics due to tags maps being passed by-reference to gatherKeyspaceLine. This PR do a copy of that map in gatherKeyspaceLine before modifying it.

Removed leaked "database" tag on redis metrics

---

scripts/build.py

Changes here:
- Adding `static_amd64` as a default target architecture (so that static builds will be available with the nightlies)
- Changes `tar` and `zip` output directory hierarchy from the first-level directory being `telegraf-<version>-<iteration>` just to `telegraf`. (fixes https://github.com/influxdata/telegraf/issues/1201)

Packaging updates

---

CHANGELOG.md
plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/parser_test.go

This should solve issue #1336 by taking the correct prometheus metrics source:
Metrics type summary should retrieve values via GetSummary while histogram should retrieve values via GetHistogram for both count and sum.

Fixed incorrect prometheus metrics source selection

---

CHANGELOG.md
accumulator.go
agent/accumulator.go
agent/accumulator_test.go
agent/agent.go
etc/telegraf.conf
internal/config/config.go
metric.go
metric_test.go
plugins/inputs/prometheus/parser.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/prometheus_client/prometheus_client_test.go
testutil/accumulator.go

Adding precision rounding to the accumulator. This means that now every
input metric will get rounded at collection, rather than at write (and
only for the influxdb output).
This feature is disabled for service inputs, because service inputs
should be in control of their own timestamps & precisions.

Add precision rounding to accumulator

---

CHANGELOG.md
plugins/outputs/graphite/graphite.go

Fix Graphite output mangling '%' character.

---

CHANGELOG.md
plugins/inputs/nginx/nginx.go
plugins/inputs/nginx/nginx_test.go

This PR fixes Nginx -plugins parsing so that Tengine works now. 
Added tests for Tengines stubb status format too (http://tengine.taobao.org/document/http_stub_status.html).

Added support for Tengine

---

CHANGELOG.md
internal/internal.go
plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go
plugins/inputs/elasticsearch/elasticsearch_test.go

- [n/a] README.md updated (if adding a new plugin)
Extremely similar implementation to the HTTP JSON module's
implementation of the same code.

Allow for TLS connections to ElasticSearch

---

CHANGELOG.md
plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/prometheus.go

Some popular tools like ETCD works with x509 certs authentication, this PR make this plugin supports that.

x509 certs authentication now supported for Prometheus input plugin

---

CHANGELOG.md
internal/models/running_output.go
plugins/serializers/graphite/graphite.go

nil metric list panic fix

---

CHANGELOG.md
plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/parser_test.go
plugins/inputs/prometheus/prometheus.go

Prometheus parser fix, parse headers properly

---

CHANGELOG.md
plugins/inputs/system/disk.go

[diskio] Set skip_serial_number = true by default to avoid high cardinality

---

etc/telegraf.conf
plugins/outputs/graphite/README.md
plugins/outputs/graphite/graphite.go

Adding multiple endpoints in the servers sections of graphite output, load balances the output points in a random way. This was not documented so there have been cases where end users assumed that all endpoints receive all metrics. This should make it clear by clarifying this behavior of the graphite output plugin.

Documentation for load balancing on graphite output servers

---

CHANGELOG.md
plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

- [V] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [V] README.md updated (if adding a new plugin)
master_last_io_seconds_ago added
role tag renamed to replication_role

Redis input enhancement

---

plugins/inputs/cgroup/README.md
plugins/inputs/cgroup/cgroup_linux.go
plugins/inputs/cgroup/cgroup_test.go

Revised commit that moves the cgroup path name away from tags and into the fields. This information is quite useful to debug jobs, processes, other things that live under the cgroup headings in distinct folders. Having the value listed as a tag drastically increases cardinality so moving it to a field allows it to remain as a a value we can query.

Moving cgroup path name to field from tag to reduce cardinality

---

scripts/post-install.sh
scripts/telegraf.service

With current telegraf, when updating package we got the following error (at least on Debian/Ubuntu):
```
Setting up telegraf (1.0.0~beta2) ...
Failed to execute operation: Too many levels of symbolic links
```
It is caused by systemctl enable telegraf:
```
Failed to execute operation: Too many levels of symbolic links
```
It seems to be due to Alias in Install section of telegraf.service. From my understanding of manpage systemd.unit, alias should only contains *additional* name.
Removing the alias (and the symlink /etc/systemd/system/telegraf.service created) fix this issue, after this PR systemctl enable telegraf show no warning. Obviously telegraf is still started on boot & could be controlled with systemctl {start|stop|status} telegraf

Remove systemd Install alias

---

plugins/inputs/zookeeper/README.md
plugins/inputs/zookeeper/zookeeper.go

This change will send the state of Zookeeper (leader|follower) as a tag
and not a metrics
That way it will be easier to search for filter per state

Considere Zookeeper's state as a tags

---

CHANGELOG.md
README.md
plugins/inputs/webhooks/README.md
plugins/inputs/webhooks/mandrill/README.md
plugins/inputs/webhooks/mandrill/mandrill_webhooks.go
plugins/inputs/webhooks/mandrill/mandrill_webhooks_events.go
plugins/inputs/webhooks/mandrill/mandrill_webhooks_events_json_test.go
plugins/inputs/webhooks/mandrill/mandrill_webhooks_test.go
plugins/inputs/webhooks/webhooks.go

This add a new mandrill webhooks to store send, bounce, click, open events.

Webhooks plugin: add mandrill

---

CHANGELOG.md
plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go
plugins/inputs/logparser/logparser.go
plugins/inputs/logparser/logparser_test.go
plugins/inputs/tail/tail.go

closes #1436
This also fixes the bad behavior of waiting until runtime to return log
parsing pattern compile errors when a pattern was simply unfound.

Internally name all patterns for log parsing flexibility

---

CHANGELOG.md
plugins/inputs/rabbitmq/rabbitmq.go

This adds initial support for using self-signed certs. It will default to false to preserve existing functionality but can be set to `true` if desired. It also adds godoc strings where need to prevent my linter from going haywire.
There are still outstanding golint issues that could be resolved. I will leave it up to the maintainers if this should be done. I would refactor it just to make the linter pass but the code that's present is more readable so I am leaving it in place.
The code changes here are functionality identical to `curl -k` for reference.
At some point it would be nice to have this folded into agent as this is implemented in several plugins already and could be written in a standard manner for all plugins to use.

Add support for self-signed certs to RabbitMQ input plugin

---

CHANGELOG.md
plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongodb_server_test.go
plugins/inputs/mongodb/mongostat.go

I'm adding stats per DB (configurable by gather_db_stats parameter) obtained with db.stats()
And stored in a different measurement called mongodb_db_stats because storing all these data in the same one ends up a big mess with null values everywhere.
Useful to see how each DB grow by size, indexes, number of collections, etc.

MongoDB input plugin: Adding per DB stats

---

CHANGELOG.md
plugins/inputs/nstat/nstat.go

nstat: fix nstat setting path for snmp6

---

CHANGELOG.md
plugins/inputs/redis/redis.go

In PR #1480 a extra "tcp://" was added in default configuration. It was due to a OR instead of AND used in [if test](https://github.com/influxdata/telegraf/blob/d54b169d6798e160a4ecfd5061e568fc4d3c8a88/plugins/inputs/redis/redis.go#L102).
It result in:
```
$ ./build/telegraf -input-filter redis -output-filter influxdb -sample-config > sample.conf
$ ./build/telegraf -config sample.conf -test
* Plugin: redis, Collection 1
2016/07/19 15:50:06 Errors encountered: [Unable to connect to redis server 'tcp:': dial tcp: lookup tcp on 127.0.1.1:53: no such host]
```

Fix Redis url, an extra "tcp://" was added

---

CHANGELOG.md
plugins/inputs/jolokia/jolokia.go

fixes #1481
DISCLAIMER: I don't know anything about Go. This ain't pretty, but it works on my machines. Feel free to throw this PR away if you can think of a better way to do this and/or know how to write tests.
After two days on the brink of insanity trying to come to terms with Go's type system, I have found the underlying issue for #1481. It's pretty simple actually.
The bug occurs when more than one multi-dimensional attribute is requested:
```
[[inputs.jolokia.metrics]]
name = "heap_memory_usage"
mbean  = "java.lang:type=Memory"
attribute = "HeapMemoryUsage,NonHeapMemoryUsage"
```
This leads to `out` being structured like this, which is not handled properly:
```json
{
"value": {
"HeapMemoryUsage": {
"max": 1,
[...]
},
"NonHeapMemoryUsage": {
"max": 1,
[...]
}
}
}
```
The extra level …

jolokia: handle multiple multi-dimensional attributes

---

CHANGELOG.md
plugins/inputs/win_perf_counters/win_perf_counters.go
plugins/outputs/prometheus_client/prometheus_client.go

1. in prometheus client, do not check for invalid characters anymore,
because we are already replacing all invalid characters with regex
anyways.
2. in win_perf_counters, sanitize field name _and_ measurement name.
Also add '%' to the list of sanitized characters, because this character
is invalid for most output plugins, and can also easily cause string
formatting issues throughout the stack.
3. All '%' will now be translated to 'Percent'
closes #1430

Prometheus client & win_perf_counters char changes

---

CHANGELOG.md
etc/telegraf.conf
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

Like cpu plugin, add two option "total" and "perdevice" to send network
and diskio metrics either per device and/or the sum of all devices.
By default, the old behavior of only per-device metrics is keep. User needs to change configuration if total is wanted.

Added option "total/perdevice" to Docker input

---

CHANGELOG.md
README.md
plugins/inputs/all/all.go
plugins/inputs/hddtemp/README.md
plugins/inputs/hddtemp/go-hddtemp/LICENSE
plugins/inputs/hddtemp/go-hddtemp/hddtemp.go
plugins/inputs/hddtemp/go-hddtemp/hddtemp_test.go
plugins/inputs/hddtemp/hddtemp.go
plugins/inputs/hddtemp/hddtemp_nocompile.go

Here's a basic implementation for getting temperature data from disks using hddtemp

Implement support for fetching hddtemp data

---

CHANGELOG.md
Godeps

I submitted a patch upstream to gopsutil to fix some diskio time issues on FreeBSD: shirou/gopsutil#232
The issue was that the `read_time` and `write_time` metrics on Linux were reported in milliseconds, but on FreeBSD they were in seconds. The `io_time` metric was also missing entirely. The upstream PR fixed both these issues.
While the `io_time` might be considered a feature, the inconsistent time units between Linux & FreeBSD I would consider a bug, and so I have classified this as a bug fix in the CHANGELOG.
This is all the upstream changes that will be pulled in: https://github.com/shirou/gopsutil/compare/586bb697f3ec9f8ec08ffefe18f521a64534037c...ee66bc560c366dd33b9a4046ba0b644caba46bed

update gopsutil for FreeBSD disk time metrics

---

internal/config/config.go

Fix output config typo.

---

accumulator.go
agent/accumulator.go
agent/accumulator_test.go
agent/agent.go
testutil/accumulator.go

This adds an `AddError()` method to the accumulator. Ref #1446
As opposed to the original POC in #1446, I instead just implemented it so that `AddError()` immediately writes out to the log instead of sending it into a `chan` just so that a goroutine could then write it out to the log. This approach is much simpler.
I also added an `errCount` to the accumulator which will increment each time an error is generated. This was done for 2 reasons:
1. So that the `Test()` function could tell if any errors were generated during the run. 
2. To pave the way for #1348.  
It would be very useful to know when a plugin starts throwing errors. You could then write a kapacitor alert to trigger when such starts happening.
Haven't updated CHANGELOG since the code in this PR is unused, and thus there is no …

add AddError method to accumulator

---

plugins/inputs/ping/ping_windows.go
plugins/inputs/ping/ping_windows_test.go

Ping windows

---

CHANGELOG.md

As agreed in https://github.com/influxdata/telegraf/pull/1466

Fixing changelog, MongoDB stats per db feature not release in 1.0beta3

---

CHANGELOG.md
scripts/post-remove.sh

Added support for Amazon Linux distribution in post remove scripts

---

CONTRIBUTING.md

This PR depends on https://github.com/influxdata/kapacitor/pull/780 getting merged. I would love some feedback on the language or other places we could make this call to action.

Add call to action for plugin contribuitors to write tickscripts

---

scripts/build.py

telegraf can't be cross-compiled for darwin, it has C dependencies and
thus many of the system plugins won't work.
cc @rossmcdonald

Disable darwin builds

---

CHANGELOG.md
Godeps
plugins/inputs/procstat/spec_processor.go

gopsutil, fix /proc/pid/io naming issue

---

CHANGELOG.md
plugins/inputs/postgresql_extensible/postgresql_extensible.go

Fixes #1600 
I also did some code cleanup on the nearby code so that it better follows golang coding standards (type switching & less nesting).

Fix postgres extensible text

---

plugins/inputs/ping/README.md
plugins/inputs/ping/ping_windows.go
plugins/inputs/ping/ping_windows_test.go

- [x ] README.md updated (if adding a new plugin)
- Add readme.md ( with describing ping for windows )
- Fix problem with lost percentage compute. Add additional metric 'percent_reply_loss' ( described in readme.md ). Test case handled in TestUnreachablePingGather
- Fixes in previous unit tests

Fix problem with metrics when ping return Destination net unreachable ( windows )

---

etc/telegraf.conf
plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/influxdb.go

Fix typo of 'quorom' to 'quorum' when specifying InfluxDB write consistency

---

CHANGELOG.md
Godeps_windows
Makefile

Partial solution for issue #1619.  Unfortunately, I can't fix the `gdm` issue, because I don't know which revisions of the missing packages to use.

Defines GOOS and GOARCH for windows builds

---

CHANGELOG.md
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go

also sanitize the names at a higher scope for better clarity
closes #1637

Sanitize graphite characters in field names

---

CHANGELOG.md
Godeps
README.md
plugins/inputs/all/all.go
plugins/inputs/snmp/README.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go
plugins/inputs/snmp/testdata/snmpd.conf
plugins/inputs/snmp/testdata/test.mib

This is a proposal for an alternate SNMP plugin.
I wrote this because of issues like #1371, #808 & #1361
I also found the configuration of the existing SNMP plugin to be overly complex & confusing.
This new plugin has:
* A vastly simpler config
* Supports SNMP tables properly (#1371 & #808)
* Supports converting strings to numeric types (#1361 & #1151)
* Supports adding tags using SNMP values (#997)
* Supports SNMP v1 (#1163) & v3 (#856)
* Does not require an external file (`snmptranslate_file`)
* Should also fix #1043 & #961 
SNMP data:
```
.1.2.3.0.0.1.0 octet_str "foo"
.1.2.3.0.0.1.1 octet_str "bar"
.1.2.3.0.0.102 octet_str "bad"
.1.2.3.0.0.2.0 uinteger 1
.1.2.3.0.0.2.1 uinteger 2
.1.2.3.0.0.3.0 octet_str "0.123"
.1.2.3.0.0.3.1 octet_str "0.456"
.1.2.3.0.0.3.2 octet_str "9.999" …
```

Alternate SNMP plugin

---

CHANGELOG.md
plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go

Make elasticsearch timeout configurable

---

plugins/inputs/mesos/README.md
plugins/inputs/mesos/mesos.go
plugins/inputs/mesos/mesos_test.go

Removing unneeded statistics prefix for task's metric,
Adding framework id tags into each task's metric,
Adding state (leader/follower) tags to master's metric,
Make sure the slave's metrics are tags with slave

Some improvment in mesos input plugin,

---

CHANGELOG.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

This makes sure that all redis metrics are present without having to use a hard-coded list of what metrics to pull in.
Fixes #1685 
I did opt for skipping some stuff, such as most of the "server" section, with the exception of 2 metrics. Most of the fields in this section aren't metrics, but server info. Also skipped any "*_human" field since each has a more accurate field available.
For the fields that were being renamed, I kept the renaming behavior.
I also added a `rdb_last_save_time_elapsed` metric which is calculated using `rdb_last_save_time`, which is an absolute timestamp, and the current time.
Influxdb doesn't support `select time - rdb_last_save_time`, so without this, there's no way to tell how long ago the last save was.

add missing redis metrics

---

plugins/inputs/cloudwatch/README.md
plugins/inputs/cloudwatch/cloudwatch.go
plugins/inputs/cloudwatch/cloudwatch_test.go

Move CloudWatch rate limit to config

---

CHANGELOG.md
plugins/inputs/mysql/mysql.go

We discovered that certain mysql booleans were only being written to our influxdb and cloudwatch outputs when they were true. This makes graphing difficult in grafana and alarms impossible in cloudwatch.
Looking at the code in `parseValue()`: In the case of `"Yes"` or `"ON"` the function returns `value=1, ok=true`, and in the case of `"No"` or `"OFF"` it returns `value=0, ok=false`. When `ok` is `false`, telegraf drops the field and doesn't report it. This appears to be a simple bug (which has been there since the `parseValue()` code was first committed).
This PR changes `ok` to `true` for false values so that they get written to the metrics outputs instead of dropped.

Fix MySQL plugin not sending 0 value fields

---

plugins/serializers/graphite/graphite.go

This is a quick, and potentially _dirty_ fix that accounts for parenthesis in metric names, which are **especially** prevalent in the windows performance counters plugin and also in the sqlserver plugin.
From grafana these metrics are unable to be queried because of the parens.
Thoughts?  Concerns?
Thanks,
Phil

sanitize parenthesis for graphite output

---

plugins/outputs/nats/nats.go

@pires I mistakenly hit "merge" a bit too early on this. I wanted the NATS ssl config to look exactly like the other ssl configurations. If you look through the `-sample-config` you can see that there are many other plugins using this format. Can you review this and let me know what you think?

Refactor NATS ssl config

---

CHANGELOG.md
README.md
plugins/inputs/all/all.go
plugins/inputs/http_listener/README.md
plugins/inputs/http_listener/http_listener.go
plugins/inputs/http_listener/http_listener_test.go
plugins/inputs/http_listener/stoppableListener/LICENSE
plugins/inputs/http_listener/stoppableListener/listener.go

Bagelswitch master

---

cmd/telegraf/telegraf.go

Update Telegraf's version output to match InfluxDB and Kapacitor version output. Mostly this adds the branch and commit hash to the output.

Add commit to Telegraf version string

---

CHANGELOG.md
plugins/inputs/statsd/statsd.go

```
BenchmarkParse-4                                      50000         35152 ns/op
BenchmarkParseWithTemplate-4                          30000         45953 ns/op
BenchmarkParseWithTemplateAndFilter-4                 30000         50166 ns/op
BenchmarkParseWith2TemplatesAndFilter-4               20000         64277 ns/op
BenchmarkParseWith2Templates3TagsAndFilter-4          20000         81050 ns/op
```
```
BenchmarkParse-4                               	  100000	     20525 ns/op
BenchmarkParseWithTemplate-4                   	  100000	     20438 ns/op
BenchmarkParseWithTemplateAndFilter-4          	  100000	     20692 ns/op
BenchmarkParseWith2TemplatesAndFilter-4        	  100000	     20724 ns/op
BenchmarkParseWith2Templates3TagsAndFilter-4   	  100000	     22354 ns/op
```

speed up statsd parser

---

CHANGELOG.md
plugins/parsers/json/parser.go

According to the go documentation the JSON deserializer only produces these
base types in output:
- string
- bool
- float64
- nil
With this patch bool, float64 and nil values get converted to a string when
their field key is specified in tag_keys. Previously the field was simply
discarded.

Allow numeric and non-string values for tag_keys.

---

plugins/inputs/statsd/statsd.go

I got this error when forgetting to set allow_pending_message on 1.0.0 version.
```
2016/09/19 00:14:36 ERROR: statsd message queue full. We have dropped 1 messages so far. You may want to increase allowed_pending_messages in the config
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x621709 pc=0x621709]
goroutine 21 [running]:
panic(0x12cefe0, 0xc82000a060)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).udpListen(0xc8200cc0d0, 0x0, 0x0)
/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/statsd/statsd.go:298 +0x7d9
created by github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).Start
/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/statsd/s …
```

Fix crash when allow pending messgae wasn't set

---

CHANGELOG.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

max-repetitions = 10 is the default of net-snmp utils according to
http://net-snmp.sourceforge.net/docs/man/snmpbulkwalk.html
retries = 3 is the default of gosnmp:
https://godoc.org/github.com/soniah/gosnmp#pkg-variables
Could deal with some parts of the performance issues reported
by #1665

Default SNMP parameter changes

---

CHANGELOG.md
internal/config/config.go

Load config directory using filepath.Walk

---

cmd/telegraf/telegraf.go

This resolves the issue of installing the Windows service from Anisble #1760

Windows -service flags from non-interactive session

---

Godeps
plugins/inputs/snmp/snmp.go

Previous fix (#1848) for #1835 didn't catch all empty string cases. There's another caused by a bug in the gosnmp lib. So this updates the lib. In fact this was probably the original issue reported in #1835, and while #1848 fixed some potential issues, they weren't the actual problem reported.

update to latest gosnmp

---

plugins/inputs/snmp/snmp.go

Since the influxdb models marshaller panics on byte slices (when not a valid line-protocol value), we should throw an error instead of passing through the value unchanged.
I didn't update the changelog or anything as this isn't really a bug fix or enhancement. Unless people have misconfigured telegraf, there should be no behavior change.
closes #1852

snmp: return error on unknown conversion type

---

plugins/inputs/rabbitmq/rabbitmq.go

Adds `idle_since` as requested in #1811. That's about it.

Add idle_since to emitted metrics

---

CHANGELOG.md
plugins/inputs/logparser/grok/grok_test.go
plugins/inputs/logparser/grok/influx_patterns.go
plugins/inputs/logparser/grok/patterns/influx-patterns

logparser: allow numbers in ident & auth parameters

---

CHANGELOG.md
docs/DATA_FORMATS_INPUT.md
plugins/parsers/graphite/parser.go
plugins/parsers/graphite/parser_test.go

Previously, the graphite parser would simply overwrite any template that
had an identical filter to a previous template. This included the empty
filter.
This change automatically creates a "*." filter for any template
specified with an empty filter. This allows users to specify only a
template, and Telegraf will auto-match based on the most specific
template.
closes #1731

graphite parser, handle multiple templates empty filter

---

CHANGELOG.md
plugins/inputs/all/all.go
plugins/inputs/kubernetes/README.md
plugins/inputs/kubernetes/kubernetes.go
plugins/inputs/kubernetes/kubernetes_metrics.go
plugins/inputs/kubernetes/kubernetes_test.go

feat(kubernetes): Add kubernetes input plugin

---

CHANGELOG.md
circle.yml
internal/internal.go
internal/internal_test.go
scripts/circle-test.sh

`internal.Duration` unmarshaler will cause Telegraf to panic if you pass it something like `1` in `telegraf.toml`.

Fix panic in internal.Duration UnmarshalTOML

---

plugins/inputs/procstat/README.md

Fix typo from 'Proctstas' to 'Procstat' in procstat plugin's README

---

plugins/inputs/kubernetes/kubernetes.go

fix(kubernetes): Only initialize RoundTripper once

---

CHANGELOG.md
plugins/inputs/nats_consumer/nats_consumer.go
plugins/outputs/nats/nats.go

Fix NATS plug-ins reconnection logic

---

CHANGELOG.md
plugins/inputs/tcp_listener/tcp_listener.go
plugins/inputs/udp_listener/udp_listener.go

udp_listener & tcp_listener set default values

---

plugins/inputs/chrony/chrony.go
plugins/inputs/chrony/chrony_test.go

fix leap_status value in chrony input plugin

---

CHANGELOG.md
logger/logger.go
logger/logger_test.go

Use rfc3339 timestamps in telegraf log output

---

plugins/inputs/cloudwatch/README.md
plugins/inputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch.go

Also don't use named returns in fetchNamespaceMetrics since it's
non-standard for the rest of the codebase.

Fix up AWS plugin docs so they don't use single quotes.

---

plugins/inputs/udp_listener/udp_listener.go

Adding a config option to allow users to set the ReadBuffer for UDP sockets when created. This is intentionally separate from the OS settings which you may not want to make global for one socket call. If the user doesn't specify the setting, it defaults to the OS definition; otherwise it's set to udp_buffer_size.
NOTE: golint is blowing up with alerts for underscores, happy to change these if you'd like.
NOTE_2: @wrigtim contributed too!

Add udp_buffer_size option to udp_listener

---

CHANGELOG.md
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go
testutil/accumulator.go

This implements the solution we discussed in #1775

Cache and expire metrics for prometheus output

---

CHANGELOG.md
docs/DATA_FORMATS_INPUT.md
plugins/inputs/httpjson/README.md
plugins/inputs/httpjson/httpjson_test.go
plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go

- [ X ] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [ X ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ X ] README.md updated (if adding a new plugin)

Add support to parse JSON array (JSON Parser and HTTPJson)

---

CHANGELOG.md
plugins/parsers/value/parser.go
plugins/parsers/value/parser_test.go

Some producers (such as the paho embedded c mqtt client) add a null
character "\x00" to the end of a message.  The Value parser fails on
any message from such a producer.

Trim null characters in Value data format

---

etc/telegraf_windows.conf
plugins/inputs/win_perf_counters/README.md

Similar to unix load, Windows' `Processor Queue Length` indicates how many threads are ready in the processor queue, but not currently able to use the processor.  It is different than unix load in that it is an instantaneous measurement and needs to be tracked over time.
Monitoring this counter is especially important on machines with SQL Server as it is used to help tune the *lightweight threading* option (fibers).

Update win_pref_counter to include Processor Queue Length in examples.

---

CHANGELOG.md
Godeps
docs/LICENSE_OF_DEPENDENCIES.md
plugins/inputs/exec/exec.go

The old gonuts fork has no License and has not seen any commits
differing from the original project, while the original has seen some
activity, even if low.
Having no license is a problem for distributors, as by default, such
projects are undistributable.

Switch to github.com/kballard/go-shellquote

---

CHANGELOG.md

The changelog for #1965 ended up in the wrong version (1.1.0). Moved it up to 1.2.0

Fix changelog for json parser.

---

CHANGELOG.md
plugins/inputs/system/cpu.go
plugins/inputs/system/cpu_test.go

- [✔] CHANGELOG.md updated (we recommend not updating this until the PR has been approved by a maintainer)
- [✔] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [✖] README.md updated (if adding a new plugin)
On linux, the user and nice cpu time counters include the respective guest and guest_nice counters. This results in improper calculation of percentages.
Please see: 
https://github.com/torvalds/linux/blob/447976e/kernel/sched/cputime.c#L169
https://lists.linuxfoundation.org/pipermail/virtualization/2009-August/013459.html
https://github.com/giampaolo/psutil/pull/940

Fix improper calculation of CPU percentages

---

scripts/build.py

RPM for armhf are using the wrong architecture name. Fedora/CentOS (and OpenSuse also) does not use "armhf" like Debian/Ubuntu. They use "armv6hl" or "armv7hl".
This PR fix the name for armhf and use armv6hl for RPM.
This PR only fix names for armhf:
* For armel, name should probably be an armv5-something, but I don't known the "-something"
* For arm64, I didn't searched and I think currently it's build as armv7hl (32-bits). From my understanding, for 64-bits, GOARCH should be arm64 and GOARM seems unused. Since I don't have any arm64 I can't test.
Issue with current armhf:
```
Error: package telegraf-dev-1.armhf is not installable
(try to add '--allowerasing' to command line to replace conflicting packages)
package telegraf-dev-1.armhf is intended for a different architecture
```
With …

Fix RPM architecture for armhf

---

CHANGELOG.md
README.md
agent/accumulator.go
agent/accumulator_test.go
agent/agent.go
internal/buffer/buffer.go
internal/buffer/buffer_test.go
internal/config/config.go
internal/models/makemetric.go
internal/models/running_aggregator.go
internal/models/running_input.go
internal/models/running_input_test.go
internal/models/running_output.go
internal/models/running_output_test.go
plugins/inputs/all/all.go
plugins/inputs/http_listener/http_listener.go
plugins/inputs/internal/README.md
plugins/inputs/internal/internal.go
plugins/inputs/internal/internal_test.go
plugins/inputs/tcp_listener/tcp_listener.go
plugins/inputs/udp_listener/udp_listener.go
selfstat/selfstat.go
selfstat/selfstat_test.go
selfstat/stat.go
selfstat/timingStat.go
testutil/accumulator.go

Implement telegraf collecting stats on itself

---

CHANGELOG.md
metric.go
metric/metric.go
metric/metric_benchmark_test.go
metric/metric_test.go

Support a telegraf.Metric.Split function

---

CHANGELOG.md
internal/models/running_aggregator.go
plugins/inputs/logparser/README.md

Check if metric is nil before calling SetAggregate

---

CHANGELOG.md
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/spec_processor.go

Can turn pid into tag instead of field

---

plugins/outputs/opentsdb/opentsdb.go
plugins/outputs/opentsdb/opentsdb_http.go

Output openTSDB HTTPS with basic auth

---

plugins/inputs/rabbitmq/rabbitmq.go
plugins/inputs/rabbitmq/rabbitmq_test.go

This would help us track the "state" of connections, which can be used to [identify bottlenecks](http://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/) in the infrastructure.

Rabbitmq plugin: connection-related metrics.

---

CHANGELOG.md
plugins/outputs/graylog/README.md
plugins/outputs/graylog/graylog.go

Graylog output should set short_message field

---

CHANGELOG.md
plugins/inputs/hddtemp/README.md
plugins/inputs/hddtemp/go-hddtemp/hddtemp.go
plugins/inputs/hddtemp/go-hddtemp/hddtemp_test.go
plugins/inputs/hddtemp/hddtemp.go
plugins/inputs/hddtemp/hddtemp_test.go

Also added unit tests which was missing in hddtemp plugin.
this should resolve #1904 
Im not sure how to handle data migration? Perhaps a config entry to handle the new format which defaults to the old?

Change hddtemp to always put temperature in value field

---

plugins/inputs/rabbitmq/rabbitmq.go
plugins/inputs/rabbitmq/rabbitmq_test.go

Reverts influxdata/telegraf#1908
reverting this change because of https://github.com/influxdata/telegraf/issues/2168
fixes #2168

Revert "Rabbitmq plugin: connection-related metrics."

---

plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

Fixed for parsing docker image name / image version to account for the case of a custom docker repo which uses a non-standard port, for example `mycompany.net:4443/someimage:sometag`

fixes #1987 custom docker repos with non-standard port

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

Jitter for Input plugin Ping

---

CHANGELOG.md
plugins/inputs/influxdb/influxdb.go
plugins/inputs/influxdb/influxdb_test.go

Add field for last GC pause time

---

plugins/inputs/jolokia/README.md
plugins/inputs/jolokia/jolokia.go

If one is using the suggested Jolokia plugin configuration, the following will cause the plugin to fail:
```
context = "/jolokia"
```
The server requires a trailing slash (i.e. `http://127.0.0.1:8778/jolokia/`). This change adds a slash to the end of the context parameter if it is not present.

Add trailing slash to jolokia context

---

plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

The e.g. section did not have the "servers = " portion included but did have "db_" included. This confused me as I tried to use the mysql inputs plugin. I changed the look of the examples to include "servers =" and removed the "db_" so the examples now look like:
```servers = ["user:passwd@tcp(127.0.0.1:3306)/?tls=false"]```
```servers = ["user@tcp(127.0.0.1:3306)/?tls=false"]```
As opposed to the examples that had me confused which looked like:
```db_user:passwd@tcp(127.0.0.1:3306)/?tls=false```
```db_user@tcp(127.0.0.1:3306)/?tls=false```

Update MySQL Readme to clarify connection string examples.

---

CHANGELOG.md
plugins/inputs/logparser/grok/grok_test.go
plugins/inputs/logparser/grok/influx_patterns.go

deals partially with #1973
see also https://github.com/vjeantet/grok/issues/17

Fix & unit test logparser CLF pattern with IPv6

---

CHANGELOG.md
plugins/inputs/statsd/statsd.go

this basically reverts #887
at some point we might want to do some special handling of reloading
plugins and keeping their state intact, but that will need to be done at
a higher level, and in a way that is thread-safe for multiple input
plugins of the same type.
Unfortunately this is a rather large feature that will not have a quick
fix available for it.
fixes #1975
fixes #2102

Do not create a global statsd "previous instance"

---

plugins/inputs/system/ps.go

This loop is assigning a value to p then creating a pointer to it, as the value of p is switched for each loop iteration the result is all the pointers point to the last item.
This results in the value of the "device" in the disks plugin being the same as the last partition device. see https://github.com/Versent/telegraf/blob/fix_disk_by_value_loop/plugins/inputs/system/disk.go#L57

Fix for loop over value array range issue.

---

CHANGELOG.md
plugins/inputs/docker/docker.go

Check type of each blkio metric

---

plugins/inputs/cassandra/cassandra.go

Hi everyone,
I would like to update the cassandra plugin, why ?
Because if you are retrieving 50 metrics every 10 seconds, it cause a lot of logs for the service ( ie : journald ) 
- I think it is not usefull for performances (write into log). 
- It does not remove errors from being seen.

Remove print call in cassandra plugin

---

plugins/inputs/ceph/README.md
plugins/inputs/ceph/ceph.go

This fixes the sample config for the ceph input plugin (source code & readme). Sample stated that, using default values, the plugin would gather cluster stats, whereas default config has that option disabled.

Ceph: sample config should reflect actual defaults

---

CHANGELOG.md
plugins/inputs/snmp/snmp.go

Ensures proper context on all SNMP error messages.
Closes #1814

ensure proper context on snmp error messages

---

plugins/outputs/librato/librato.go

These errors are delightful, but I'd rather avoid them:
```
Error parsing /etc/telegraf/telegraf.conf, line 2: field corresponding to `api_user' is not defined in `*librato.Librato'
```

Fix for broken librato output

---

Godeps
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/kafka_consumer/kafka_consumer_test.go

This fixes an issue with kafka_consumer input plugin that broke due to a [change](https://github.com/wvanbergen/kafka/commit/45aaec2261212048bd6a66d91597e253119fbc7e) in [wvanbergen/kafka](https://github.com/wvanbergen/kafka).

Fixes change in Kafka consumer input plugin

---

CHANGELOG.md
plugins/inputs/jolokia/jolokia.go
plugins/inputs/jolokia/jolokia_test.go

This allows changing the delimiter jolokia uses for concatenating metric names & attribute keys. It is very common for an attribute key to contain an underscore, thus using an underscore as the delimiter makes the field names rather ambiguous.
Personally I use a dot (`.`) as my delimiter, as it is very rare to see a dot in an attribute key, but I've been doing so by explicitly specifying each attribute as a separate `[inputs.jolokia.metric]`.

allow changing jolokia delimiter

---

plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

Added userstats to mysql input plugin

---

plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

Add more metrics from INFORMATION_SCHEMA.INNODB_METRICS. As other extended metrics of MySQL this is enalbed or not using gather_innodb_metrics option.

Added more InnoDB metric to MySQL plugin

---

CHANGELOG.md
agent/agent.go

doing this unblocks incoming metrics while waiting for a flush to take
place.
we have to create a semaphore so that we can
'skip' flushes that try to run while a flush is already running.
closes #2262

Run scheduled flushes in background

---

CHANGELOG.md
plugins/outputs/influxdb/influxdb.go

If we write a batch of points and get a "field type conflict" error
message in return, we should drop the entire batch of points because
this indicates that one or more points have a type that doesnt match the
database.
These errors will never go away on their own, and InfluxDB will
successfully write the points that dont have a conflict.
closes #2245

influxdb output: treat field type conflicts as a successful write

---

scripts/build.py

closes #1346
closes #2218
with this PR the next release will include 32-bit binaries for Windows and FreeBSD

32-bit binary for windows and freebsd

---

CHANGELOG.md
Godeps
plugins/inputs/postgresql/README.md
plugins/inputs/postgresql/connect.go
plugins/inputs/postgresql/postgresql.go
plugins/inputs/postgresql/postgresql_test.go
plugins/inputs/postgresql_extensible/postgresql_extensible.go
plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
testutil/accumulator.go

previous pr/discussion: #1617 
currently lib/pq doesn't handle name, oid types, and I suspect other builtin postgersql types consistently making adding custom queries for some tables difficult.
It is doubtful pq will change the current output of these types to be friendlier to the end user as the maintainer is pretty hardline about not changing behaviour, even when its for the better.
switching to pgx allows support for all the currently ignored columns except stats_reset, and that is a problem with writing output not the db driver. it likely could be fixed in a follow up pr.
copied the ParseURL from lib/pq as it was a dependency whose logic I didn't wish to change, but at the same time didn't want a dependency on the driver just for that function.

switch postgresql drivers to support more column types out of the box.

---

etc/telegraf_windows.conf

Add more metrics in default Windows configuration. I trying to retrieve same metrics as a default Unix configuration.
* Processor: % DPC Time: seems to match softirq
* Memory: At least on Windows 7, the sum of the three Standby Cache match what task manager call "Cached"
* % User time is removed from LogicalDisk. It does not exists on Windows 7 and I suspect a copy/paste from Processor
Other entry should be clear enough. Tested this configuration on a Windows 7 (localized in French, so #2261 included) with FailOnMissing=true. Worked and all metrics were present.

Added more Windows metrics

---

CHANGELOG.md
plugins/inputs/win_perf_counters/win_perf_counters.go

Another fix for #1730. This PR allows default configuration (with English names, like "Processor") to work on non-English Windows.
It re-add PreVistaSupport (as it use PdhAddEnglishCounter which existing only since Vista). It removes the validation using PdhValidatePath that only support localized names.
A validation is added by calling PdhCollectQueryData during configuration. This give fewer information than PdhValidatePath, it only say if the query exist or not. We no longer know if it was the object, instance or counter that does not exists.

Improve win_perf_counters on non English systems

---

plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go

We were having problems with telegraf talking to
carbon-relay-ng using the graphite output. When
the carbon-relay-ng server restarted the connection
the telegraf side would go into CLOSE_WAIT but telegraf
would continue to send statistics through the connection.
Reading around it seems you need to a read from the connection
and see a EOF error. We've implemented this and added a test
that replicates roughly the error we were having.
Pair: @whpearson @joshmyers

Fix problem with graphite talking to closed connections

---

CHANGELOG.md
plugins/inputs/consul/README.md
plugins/inputs/consul/consul.go
plugins/inputs/consul/consul_test.go

Add numerical representation of Consul health check state.

---

CHANGELOG.md
metric/metric.go
metric/parse_test.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
plugins/parsers/influx/parser_test.go

metric: Fix negative number handling

---

CHANGELOG.md
cmd/telegraf/telegraf.go

When installing a Windows service, the "-config" option is kept. But "-config-directory" was not kept.
The PR handle "-config-directory" the same way as "-config" and keep the value used when installing the service and when running the service.

Keep -config-directory when running as Windows service

---

CHANGELOG.md
plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

When hitting a HTTP health_check it will return a valid HTTP status but will have an "healthy" or "un-healthy" message in the response. I've extended http_response to allow to specify a substring to search for in the HTTP response and return a metric of 1 if found, 0 if not. This would allow the metric to be passed or be pulled by monitoring.

http_response : Add in support for looking for substring in response

---

plugins/inputs/iptables/README.md
plugins/inputs/iptables/iptables.go

This PR adds IPtables lock support to the input plugin, related to https://github.com/influxdata/telegraf/issues/2144

Add lock option to the IPtables input plugin

---

plugins/inputs/kubernetes/kubernetes_metrics.go
plugins/inputs/kubernetes/kubernetes_test.go

Fixes #2287 - can't deserialise null `startTime` in Kubernetes responses for stopped pods.
Added a test which covers this scenario.
I can't see any usages of `PodMetrics.StartTime`, which I would normally also want to check for regressions from making `StartTime` a pointer. Please let me know if there's something else I should test.

Kubernetes input: Handle null startTime for stopped pods

---

CHANGELOG.md
plugins/inputs/ceph/README.md
plugins/inputs/ceph/ceph.go
plugins/inputs/ceph/ceph_test.go

This PR changes the layout of fields used for the `ceph_pgmap_state` metric according to what was proposed in issue #2224 
Test for the corresponding code has been added and the code for `decodeStatusPgmapState()` simplified.

Ceph: represent pgmap states using tags

---

CHANGELOG.md
cmd/telegraf/telegraf.go

Fix telegraf swallowing panics in --test mode

---

CHANGELOG.md
README.md
plugins/inputs/all/all.go
plugins/inputs/socket_listener/socket_listener.go
plugins/inputs/socket_listener/socket_listener_test.go
plugins/outputs/all/all.go
plugins/outputs/socket_writer/socket_writer.go
plugins/outputs/socket_writer/socket_writer_test.go
testutil/accumulator.go

This adds support for a generic socket writer & listener.
The original intent was to add support for unix domain sockets. But it was trivial to write generic plugins that can handle all protocols. Thus the functionality of the `socket_listener` duplicates `tcp_listener` and `udp_listener`.
However in the case of `tcp_listener`, there is a critical difference in that the plugin will not ever drop a metric (such as if the buffer fills up). TCP is meant to be a reliable protocol, thus it should be up to the sender whether data gets dropped.
Another slight difference in the `socket_listener` is that instead of having 2 layers of buffering, an application chan buffer and a socket buffer, it only has a socket buffer. Config parameters have been provided for adjusting the size of the socket …

add socket listener & writer

---

plugins/outputs/influxdb/influxdb.go

HI,
I tested the HEAD version of telegraf, and I could not connect to my influxdb server because the authentification was not set since #2251.
This should fix the issue.

Fix setting the username and the password to the influxdb output.

---

README.md

The docker engine-api package we use needs golang 1.7+, see:
https://github.com/docker/engine-api/pull/382#issuecomment-244512952
So telegraf won't compile without 1.7

README: update golang requirement to 1.7

---

CHANGELOG.md
internal/models/running_output.go

Increment buffer_size as soon as the metric is incremented

---

README.md

Commit 54c9a385d introduced a requirement on Go version 1.8, updating the
README.md accordingly.

Updated readme, now requires Go 1.8

---

CHANGELOG.md
plugins/inputs/logparser/grok/grok_test.go
plugins/inputs/logparser/logparser.go

log error message when invalid regex pattern is used

---

CHANGELOG.md
internal/config/config.go

Handle nil os.FileInfo in filepath.Walk

---

CHANGELOG.md
plugins/inputs/ping/ping_windows.go
plugins/inputs/ping/ping_windows_test.go

closes #1433
this is going to require a note in the changelog release notes, because it will break current users of only the windows plugin.

Fix type conflict on windows ping plugin

---

etc/telegraf_windows.conf

Tweak formatting of `LogicalDisk` counter array to have one entry per
line.

Disk counter array newline

---

CHANGELOG.md
plugins/inputs/iptables/README.md
plugins/inputs/iptables/iptables.go

During issue #2215 it was highlighted that the current behavior where
rules without a comment are ignored is confusing for several users.
This commit improves the documentation and adds a NOTE to the sample
config to clarify the behavior for new users.
Fixes #2215

Iptables input: document better the ignored rules behavior

---

CHANGELOG.md
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go
plugins/inputs/procstat/spec_processor.go

Reverts influxdata/telegraf#2206

Revert "Procstat: don't cache PIDs"

---

CHANGELOG.md
plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/ipmi_sensor/ipmi_test.go

Currently "path" is not exported, giving this error when users try to
override the variable via telegraf.conf as per the sample config:
`field corresponding to `path' is not defined in `*ipmi_sensor.Ipmi'`
Exporting the variable solves the problem.
Config:
```ini
[[inputs.ipmi_sensor]]
path = "/usr/local/bin/ipmitool_sdr_f"
```
Before:
```
$ sudo telegraf -test
2017/03/06 17:09:12 I! Using config file: /etc/telegraf/telegraf.conf
2017/03/06 17:09:12 E! Error parsing /etc/telegraf/telegraf.conf, line 50: field corresponding to `path' is not defined in `*ipmi_sensor.Ipmi'
```
After:
```
$ sudo telegraf -test
2017/03/06 17:17:15 I! Using config file: /etc/telegraf/telegraf.conf
[...]
* Plugin: inputs.ipmi_sensor, Collection 1
> ipmi_sensor,unit=degrees_f,host=filesrv.rob86.net,name=cpu_temp …
```

Exporting Ipmi.Path to be set by config.

---

CHANGELOG.md
metric/parse.go
plugins/inputs/exec/exec_test.go

Related to my issue #2448, I propose to hide warning if empty content should be passed especially with input.exec plugin

Remove warning if parse empty content

---

plugins/inputs/postgresql/README.md
plugins/inputs/postgresql/postgresql.go

Add configuration docs to PostgreSQL input plugin README (mostly from the source code) though I've not included the configuration example that seems to use all he connections on the database[1].
[1] https://github.com/influxdata/telegraf/issues/2410

Add configuration docs to Postgresql input plugin

---

CHANGELOG.md
plugins/inputs/system/PROCESSES_README.md
plugins/inputs/system/processes.go

Following https://github.com/torvalds/linux/blob/master/fs/proc/array.c#L126 telegraf plugin should handle DEAD state process and possibility to see it (http://unix.stackexchange.com/questions/126101/possible-to-see-dead-proccesses) specially in Docker context, the X state should be handle (I think this should be process like zombies but if you consider another metrics is necessary I can add it to interface)

DEAD (X) State Process

---

CHANGELOG.md
plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go

Add support for new SSL configuration to mongodb

---

CHANGELOG.md
plugins/inputs/cloudwatch/README.md
plugins/inputs/cloudwatch/cloudwatch.go
plugins/inputs/cloudwatch/cloudwatch_test.go

Follow up of: https://github.com/influxdata/telegraf/issues/2298
New documentation: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
Rate limit is used for the `GetMetricStatistics` endpoint.

Update default value for Cloudwatch rate limit

---

CHANGELOG.md
plugins/serializers/registry.go

return error on unsupported serializer data format

---

plugins/inputs/cloudwatch/cloudwatch_test.go
plugins/inputs/http_listener/http_listener_test.go
plugins/inputs/http_response/http_response_test.go
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/kafka_consumer/kafka_consumer_test.go
plugins/inputs/logparser/logparser_test.go
plugins/inputs/mongodb/mongodb_server_test.go
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
plugins/inputs/nats_consumer/nats_consumer.go
plugins/inputs/nats_consumer/nats_consumer_test.go
plugins/inputs/socket_listener/socket_listener_test.go
plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go
plugins/inputs/tcp_listener/tcp_listener_test.go
plugins/inputs/udp_listener/udp_listener.go
plugins/inputs/udp_listener/udp_listener_test.go
plugins/outputs/graphite/graphite_test.go
plugins/outputs/influxdb/client/udp_test.go
plugins/outputs/instrumental/instrumental_test.go
testutil/accumulator.go

This removes `time.Sleep()` from the majority of the tests. This should alleviate the racyness that causes the CircleCI tests to randomly fail. It also makes the affected tests significantly faster.
The few tests where `time.Sleep()` wasn't removed generally one of 2 cases. Either doing so would have made the code very complex, or I don't have the ability to test the change.
Fixes #2382

remove sleep from tests

---

CHANGELOG.md
plugins/inputs/snmp/README.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

Closes #1948 
Closes #2291 
Closes #2537

snmp: support table indexes as tags

---

CHANGELOG.md
plugins/outputs/riemann/README.md
plugins/outputs/riemann/riemann.go

Add write timeout to Riemann output

---

plugins/inputs/memcached/memcached.go
plugins/inputs/memcached/memcached_test.go

@theonajim noticed I duplicated evictions in https://github.com/influxdata/telegraf/pull/412
This fixes that.
- [ x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ x ] README.md updated (if adding a new plugin)

Removed duplicate evictions metric

---

CHANGELOG.md
plugins/inputs/prometheus/prometheus.go
plugins/inputs/prometheus/prometheus_test.go
testutil/accumulator.go

This change exposes the parsed timestamp from the input metric when available, defaulting to current time when not provided.

fix timestamp parsing on prometheus plugin

---

testutil/accumulator.go

Noticed this in a test result for #2587: https://circleci.com/gh/influxdata/telegraf/6432?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
What happens is that the accumulator has 2 metrics in it, `Wait(3)` is called and grabs a lock. Then another goroutine adds a metric, increments the atomic counter, and blocks waiting for the lock. The first goroutine, which is still running, gets to the point in the code where it checks the atomic counter, sees `3`, and returns, releasing the lock. This frees up the second goroutine, but it doesn't get scheduled on the CPU yet. The caller of `Wait(3)` then tries to access the 3rd metric, but the second goroutine didn't get a chance to add it yet.

fix race in testutil Accumulator.Wait()

---

docs/DATA_FORMATS_OUTPUT.md
internal/config/config.go
plugins/serializers/json/json.go
plugins/serializers/registry.go

Resolves #2124
The changes in this pull request add a new `json_timestamp_units` parameter to the Telegraf agent configuration, giving users the ability to define the which units should be used when reporting back the timestamps associated with a given metric when that metric is output as JSON.  Currently, the Telegraf agent simply returns a timestamp for those metrics in seconds when the metrics are output in JSON format (regardless of the precision that was used in generating the timestamp itself), while the same timestamps are returned in nanoseconds for if those metrics are output in the InfluxDB format.  Specifically, this pull request changes the Telegraf configuration file and the JSON serializer as follows in order to enable reporting of the timestamps associated with JSON …

Adds a new json_timestamp_units configuration parameter

---

CHANGELOG.md
README.md
plugins/inputs/system/LINUX_SYSCTL_FS_README.md
plugins/inputs/system/linux_sysctl_fs.go
plugins/inputs/system/linux_sysctl_fs_test.go

add support for linux sysctl fs metrics

---

CHANGELOG.md
plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/fake_client.go

The default in the docker input is to add all labels as tags.  This created a couple problems for us:
1.  Using OpenTSDB as the backend, only 8 tags are allowed.  If you combine this with AWS ECS, you run out of tags very quickly.
2.  Not all of the labels are useful, but some are.
This addresses the ability to both disable label's being added as tags (default is to add them) and optionally only select specific labels to add.

Docker: optionally add labels as tags

---

plugins/inputs/socket_listener/socket_listener.go
plugins/inputs/socket_listener/socket_listener_test.go
plugins/outputs/socket_writer/socket_writer_test.go

Includes 2 fixes for the `socket_listener`:
1. On unix* sockets, unlink the file before start and after stop.  
This is the critical fix. When writing, I forgot about this step :-(
2. Suppress "use of closed network connection" error on shutdown.  
On shutdown, we kill off the listener & reader goroutines by just shutting down the sockets they're using. But this was causing them to log the result as an error.
No change log entry since the plugin isn't in a released version yet.

socket_listener: clean up unix socket file on start & stop

---

CHANGELOG.md
Godeps
plugins/inputs/postgresql/connect.go
plugins/inputs/postgresql/postgresql.go
plugins/inputs/postgresql_extensible/postgresql_extensible.go

fixes #2410
the connection leak caused by how pgx manages connection pools and how telegraf connects to generate the sql.DB connection. We needed to close the pool in addition to the db connection.
I've patched pgx to handle both DSN and URI based connection strings natively. this fixes the issue.

fix postgresql connection leak

---

CHANGELOG.md
plugins/inputs/ipmi_sensor/connection.go
plugins/inputs/ipmi_sensor/connection_test.go

ipmi_sensor: allow @ symbol in password

---

CHANGELOG.md
plugins/inputs/all/all.go
plugins/inputs/dmcache/README.md
plugins/inputs/dmcache/dmcache.go
plugins/inputs/dmcache/dmcache_linux.go
plugins/inputs/dmcache/dmcache_notlinux.go
plugins/inputs/dmcache/dmcache_test.go

Add dmcache input plugin

---

CHANGELOG.md
plugins/inputs/snmp/snmp.go

set default measurement name on snmp input

---

CHANGELOG.md
Godeps
Makefile
plugins/inputs/system/disk.go
plugins/inputs/system/mock_PS.go
plugins/inputs/system/ps.go

Addresses the diskio slowdown discussed in #2197

Use name filter for IOCounters in diskio

---

CHANGELOG.md
plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/kafka_consumer/kafka_consumer_test.go

Add max_message_len in kafka_consumer input

---

docs/DATA_FORMATS_INPUT.md

This is just a small fix for the documentation, as it's wrongly showing how to pass command line options to nagios NRPE checks you want to execute.

Nagios plugin documentation fix

---

plugins/outputs/opentsdb/opentsdb_http.go

Minor fix for Content-Type header, there was a misspelling

Fixed content-type header in output plugin OpenTSDB

---

plugins/inputs/interrupts/README.md
plugins/inputs/interrupts/interrupts.go
plugins/inputs/interrupts/interrupts_test.go

@danielnelson Sorry for the noise and this extra PR, but I was making some updates to the interrupts plugin's code before I noticed you merged in the previous one (thanks btw!). I think this refactor cleans up the code rather nicely if you'd like to take a look and merge it in, of course it isn't urgent. Feel free to close the PR if you don't think it's necessary. thanks again!

Refactor interrupts plugin code

---

CHANGELOG.md
etc/telegraf.conf
plugins/inputs/webhooks/github/README.md
plugins/inputs/webhooks/github/github_webhooks.go
plugins/inputs/webhooks/github/github_webhooks_test.go
plugins/inputs/webhooks/webhooks.go

Fix #1661  
I added the check of the signature to github webhooks. If no secret is set in the config file, no check is performed (make it backward compatible).

GitHub webhooks: check signature

---

CHANGELOG.md
plugins/inputs/jolokia/jolokia.go
plugins/inputs/jolokia/jolokia_test.go

This adjusts the jolokia input to use bulk requests. This significantly increases the performance of it.
In my specific use case, I have a deployment where it takes ~10.4 seconds to gather all the requested jolokia metrics. With this change it now takes ~0.04 seconds (260x faster).
There is one behavioral change as a result of this PR. If the configuration has a syntatically invalid mbean name, instead of just failing to gather that one metric, all metrics will fail. This is because if jolokia can't parse the request, it fails the entire request. Missing mbeans/attributes still behave the way they previously have, in that an error for that specific metric will be logged, but all others will be gathered.
You can find details on this here: https://github.com/rhuss/jolokia/issues/124
Closes …

change jolokia input to use bulk requests

---

CHANGELOG.md
plugins/inputs/ipmi_sensor/ipmi.go

I noticed ipmi_sensor always returns the same struct instance.  This prevents having separate ipmi_sensor plugins active with different configs.

Fix ipmi_sensor config is shared between all plugin instances

---

plugins/inputs/win_perf_counters/pdh.go
plugins/inputs/win_perf_counters/win_perf_counters.go

The change uses WinAPI call FormatMessage() to format errors reported by pdh.dll in human-readable format.
With the change user gets error messages, which make more sense:
Invalid query: '\.NET CLR Memory(xxx)\Large Object Heap size'. Error: No data to return.
The "No data to return" is the error message "deciphered" from error code by FormatMessage.
I wonder if we should also add an "else" branch on win_perf_counters.go:296 and report errors there?
- [ X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

win_perf_counters: Format errors reported by pdh.dll in human-readable format

---

CHANGELOG.md
plugins/inputs/socket_listener/README.md
plugins/inputs/socket_listener/socket_listener.go
plugins/outputs/socket_writer/README.md
plugins/outputs/socket_writer/socket_writer.go

Closes #2635 
Unfortunately I cannot think of any way to add unit tests here. There's no ability to query a socket for its current keep-alive setting. The only way to trigger a socket shut down due to keep-alive is to kill a host, or sever the network. And the only way to observe a keep-alive probe is a packet capture.
**{rock}** (us) **{hard place}**

add keep-alive support to socket_listener & socket_writer

---

CHANGELOG.md
plugins/outputs/amqp/README.md
plugins/outputs/amqp/amqp.go

Outputs must never block on write, or it will hang all outputs and eventually inputs as well.
fixes #2603

Fix amqp output block on write if disconnected

---

CHANGELOG.md
plugins/inputs/haproxy/README.md
plugins/inputs/haproxy/haproxy.go

In my company, we use haproxy as an ssl endpoint with internal certificate authority.
So I've added TLS configuration in the haproxy input plugin to allow configuration of the `ssl_ca`.

Added SSL configuration for input haproxy

---

CHANGELOG.md
plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go

I've updated the output kafka plugin to add the two options 
```
sasl_username = "kafka"
sasl_password = "secret"
```
In the plugin congiguration to allow sending metrics into kafka with SASL authentication.

Added SASL options for ouput kafka plugin

---

CHANGELOG.md
circle.yml

Use go 1.8.1 for CI and Release builds

---

plugins/outputs/influxdb/influxdb.go

If the database creation fails on Connect for authorization failure, don't report anything.
Sadly needed to do `strings.Contains` to detect this error.  I think we should start using https://github.com/pkg/errors to append context.
If the user is also not authorized to write to the database you get:
```
E! InfluxDB Output Error: Response Error: Status Code [403], expected [204], ["xyzzy" user is not authorized to write to database "foobar2"]
E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```
And if the database does not exist at all:
```
E! InfluxDB Output Error: Response Error: Status Code [404], expected [204], [database not found: "foobar3"]
E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```
closes …

Don't log error creating database on connect

---

plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/logparser.go
plugins/inputs/logparser/logparser_test.go

With this fix Telegraf will not start if the pattern is not valid.  This is a hard failure since the configuration is invalid.  This was a regression during the 1.3 dev cycle.
Here is the how the errors look, not crazy about the multiline logging, I'll probably change it in the near future.
If you have an undefined pattern:
```
2017-05-02T21:06:49Z E! Service for input inputs.logparser failed to start, exiting
no pattern found for %{FOOBAR}
```
If there are no patterns which are not the empty string:
```
2017-05-02T21:06:41Z E! Service for input inputs.logparser failed to start, exiting
pattern required
```
fixes #2742

Return an error if no valid patterns.

---

CHANGELOG.md
plugins/inputs/sqlserver/sqlserver.go

This PR fixes a problem with the sqlserver input where database properties are not returned by Telegraf when SQL Server has been installed with a case sensitive default collation type. This issue is covered in #2725

Fixed sqlserver input to work with case sensitive server collation.

---

CHANGELOG.md
scripts/telegraf.service

Fixes: https://github.com/influxdata/telegraf/issues/2717
````
[root@<hostname> ~]# systemctl status telegraf -l
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
Active: inactive (dead) since Tue 2017-04-25 10:33:40 EDT; 14min ago
Docs: https://github.com/influxdata/telegraf
Main PID: 7857 (code=killed, signal=PIPE)
````
This occurs when we restart `systemd-journald`, which cause a crash/stop of telegraph seen as a STDPIPE
See: https://bugs.freedesktop.org/show_bug.cgi?id=84923#c9
With affected services like Consul: https://github.com/hashicorp/consul/issues/1688
and Prometheus: https://github.com/voxpupuli/puppet-prometheus/pull/3/files

Systemd does not see all shutdowns as failures

---

CHANGELOG.md
plugins/inputs/influxdb/README.md
plugins/inputs/influxdb/influxdb.go

This adds initial support for using self-signed certs. It will default to `false` to preserve existing functionality but can be set to `true` if desired.
This PR solves issue https://github.com/influxdata/telegraf/issues/1274

Add support for self-signed certs to InfluxDB input plugin

---

CHANGELOG.md
plugins/inputs/apache/apache.go
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go
plugins/inputs/prometheus/prometheus.go
testutil/accumulator.go

Reuse transport in input plugins

---

plugins/outputs/influxdb/client/udp.go
plugins/outputs/influxdb/influxdb.go

Without this fix, metric streams would send data blindly up to the max size of the `UDPPayload` buffer without processing newline and/or timestamps. This would result in malformed packets being processed at the DB entry point causing either partial writes or complete failed points.
The patch here splits the measurements up to a max size of the `UDPPayload` value with enough room to add both the newline and timestamp information. This results in more packets being sent, but ensures the payload will be properly formatted for receipt at the DB entry point.

split metrics based on UDPPayload size

---

plugins/outputs/influxdb/influxdb.go

Only split metrics if there is an udp output

---

plugins/inputs/system/processes.go

Handle process termination during read from /proc

---

CHANGELOG.md
plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/fake_client.go

Add Docker container environment variables as tags. Only whitelisted #2580
PR for the above issue.

Add Docker container environment variables as tags. Only whitelisted #2580

---

plugins/inputs/win_perf_counters/win_perf_counters.go

Fixes #1137 
The root of the problem for #1137 is that all items are maintained in a global map, but the map is only populated by one config file. Once one config file is parsed, then a flag is set and the plugin will not populate items from any other config.
~~To fix this, I've removed the flag that checks if a config file has been parsed. Instead, the check for duplicates is done within the `AddItem` function. An item is considered a duplicate if it has the same `query`, `objectName`, `counter`, and `instance`.~~
To fix this, I've removed the global map and instead store items in the main plugin struct.
I've also cleaned up a couple other aspects of this plugin:
- Removed a local `metrics` variable
- In the code, this variable was being populated as if it was going to be used for …

Fix multiple plugin loading in win_perf_counters

---

CHANGELOG.md
plugins/inputs/ipmi_sensor/README.md
plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/ipmi_sensor/ipmi_test.go

Add timeout option to IPMI sensor input plugin

---

plugins/inputs/procstat/README.md

This is needed for specific procstat metrics

Enhance the documentation with telegraf process run as root 

---

plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/influxdb/influxdb_test.go

Fix influxdb quoting

---

plugins/inputs/mysql/mysql.go

MySQL input plugin - log a warning when failing to parse field values

---

plugins/inputs/mongodb/mongostat.go

Upgraded to telegraf 1.3, mongo input is generating panics in our environment:
panic: interface conversion: interface {} is nil, not bool
goroutine 238 [running]:
github.com/influxdata/telegraf/plugins/inputs/mongodb.NewStatLine(0xed0b6827e, 0xc5670ba, 0x1bea540, 0xc4204700f0, 0xc42
03024a0, 0xc420b95668, 0xc4201746c0, 0xed0b68288, 0x568a97d, 0x1bea540, ...)
/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongostat.go:567 +0x1bb2
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*Server).gatherData(0xc420175000, 0x1b01540, 0xc420174f40, 0x4060
01, 0x0, 0x0)
/home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/mongodb/mongodb_server.go:107 +0xd
0f
github.com/influxdata/telegraf/plugins/inputs/mongodb.(*MongoDB).gatherServer …

Check for nil on mongo input, fix for panic.

---

plugins/outputs/influxdb/influxdb.go
plugins/outputs/influxdb/influxdb_test.go

fixes #2862 
fixes #2854 (75% sure)

Fix length calculation of split metric buffer

---

plugins/inputs/logparser/README.md
plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go
plugins/inputs/logparser/grok/influx_patterns.go
plugins/inputs/logparser/logparser.go
plugins/inputs/logparser/logparser_test.go

adding timezone support to logparser timestamps

---

plugins/inputs/ping/ping_windows.go
plugins/inputs/ping/ping_windows_test.go

Fix problem with crash when using sample output configuration on Windows platform
**…line 617: ping.Ping.Timeout: `float64' is not any types of int"**
Timeout variable was set as integer and should be float. Broken after refactoring code to float variables some time ago. 
- [x ] Associated README.md updated.
- [x ] Has appropriate unit tests.

Fix timeout option in Windows ping input sample configuration

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

Fix for https://github.com/influxdata/telegraf/issues/2784 & https://github.com/influxdata/telegraf/issues/2624.
Does return measurement data even if no http connection can be established.
This is based on pull request https://github.com/influxdata/telegraf/pull/2813, as it depends on the fixes.

Add result_type field for http_response input

---

metric/metric.go
metric/metric_test.go

Additional fix for #2862.
Metrics needing one extra byte to fit the output buffer would not be split, so we would emit lines without a line ending.  Metrics which overflowed by exactly one field length would be split one field too late, causing truncated fields.

Fix metric splitting edge cases

---

CHANGELOG.md
plugins/inputs/nginx/README.md
plugins/inputs/nginx/nginx.go

This PR adds support for an optional SSL/TLS config in the nginx input plugin.

Add SSL/TLS support to nginx input plugin

---

CHANGELOG.md
Godeps
Makefile
docs/LICENSE_OF_DEPENDENCIES.md
etc/telegraf.conf
internal/config/testdata/telegraf-agent.toml
plugins/inputs/all/all.go
plugins/inputs/kafka_consumer_legacy/README.md
plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy.go
plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go
plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_test.go

This PR allow the kafka_consumer input plugin to connect directly to kafka brokers using the new kafka consumer offset management.
Here is an example of configuraiton
```
[[inputs.kafka_consumer]]
brokers = ["localhost:9092"]
topics = ["telegraf"]
consumer_group = "telegraf_metrics_consumers"
offset = "oldest"
data_format = "influx"
```
Note : the old Zookeeper Connection type is no more supported.
Related Issue : #1312

Add Kafka 0.9+ consumer support

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

Add wildcard inclusion/exclusion support to container names

---

plugins/inputs/leofs/leofs.go
plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go

This was broken by changes in go 1.8 to url.Parse.  This change allows
the string but prompts the user to move to the correct url string.
Fixes #2888

Fix support for mongodb urls without scheme

---

Godeps

Update aws-sdk-go dependency to latest release.

---

CHANGELOG.md
plugins/inputs/ping/ping_test.go

I noticed that the Linux ping pluging was missing values for min and max. Wanted to capture that data since we already have it in the ping output.

added linux/darwin min/max ping values to match windows plugin

---

plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

It is not allowed for labels to differ within a metric, this patch
ensures that they are consistent within a single Write operation.
However, it does not address cases where the label varies across calls
to Write.
#2822

Ensure prometheus metrics have same set of labels

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/influxdb.go

As in issue #1588 
Influxdb output plugin does not works with http proxy.
This patch solve the issue.

HTTP Proxy in influxdb output plugin

---

plugins/inputs/logparser/logparser.go
plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go

Parsing dos line ending delimited line protocol is still illegal in most
cases.
fixes #2915

Allow dos line endings in tail and logparser.

---

etc/telegraf.conf
plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

https://github.com/influxdata/telegraf/issues/2916 cc @danielnelson

Mysql input plugin: Add ability to specify custom SSL certificates

---

metric/parse.go
metric/parse_test.go

Fix bug parsing default timestamps with precision set

---

Godeps
etc/telegraf.conf
plugins/inputs/rethinkdb/rethinkdb.go
plugins/inputs/rethinkdb/rethinkdb_server.go
plugins/inputs/rethinkdb/rethinkdb_test.go

Fix rethinkdb plugin to work with actual database and actual authorization protocol

---

plugins/inputs/elasticsearch/elasticsearch.go

This introduces a fix for #2893. With this change, ES collection is skipped for the interval rather than telegraf crashing due to panic.

Fix panic in elasticsearch input plugin

---

Makefile
cmd/telegraf/telegraf.go

closes #2942 
On this branch
```
$ telegraf --version
Telegraf v1.4.0~pre8f2d9233 (git: fix-version 8f2d9233)
```
Release should look something like:
```
Telegraf v1.4.0 (git: release-1.4 8f2d9233)
```

Use git sha1 as version if not tagged

---

CHANGELOG.md
etc/telegraf.conf
plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go

According to https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers we have to use that port table to avoid collisions. That PR fixes previous incompatibility with that table.

Change default prometheus_client port

---

plugins/outputs/prometheus_client/prometheus_client.go

I encounter this issue when I have a telegraf instance A already bind prometheus metric endpoint to  port 9216, while another telegraf instance B trying to bind port 9216 after that didn't show any clue its binding failed.
What makes it more confusing is that my visiting metrics endpoint at port 9216 still shows results. I didn't realize there's an old instance A there.
I think output error message from serve and listen method should be a help to this issue.

display error message if  serve prometheus metric output failed

---

README.md

I noticed it was missing, so I thought I'd add in real quick.

Add link to Graylog input to README.md

---

metric/metric.go
metric/metric_test.go

Line protocol does not require or allow escaping of backslash, the only
requirement for a byte to be escaped is if it is an escapable char and
preceeded immediately by a slash.
closes #3001

Fix error handling escaped field strings

---

internal/models/makemetric.go
internal/models/running_input_test.go
metric/metric.go
metric/metric_test.go

It is not possible to encode a measurement, tag, or field whose last
character is a backslash due to it being an unescapable character.
Because the tight coupling between line protocol and the internal metric
model, prevent metrics like this from being created.
Measurements with a trailing slash are not allowed and the point will be
dropped.  Tags and fields with a trailing a slash will be dropped from
the point.
closes #3004

Do not allow metrics with trailing slashes

---

internal/models/running_output.go

Prevent Write from being called concurrently

---

agent/agent.go
internal/models/running_processor.go

Looping the metrics back through the same channel could result in a
deadlock, by using a new channel and locking the processor we can ensure
that all stages can make continual progress.
closes #2914

Prevent possible deadlock when using aggregators

---

plugins/inputs/all/all.go
plugins/inputs/fluentd/README.md
plugins/inputs/fluentd/fluentd.go
plugins/inputs/fluentd/fluentd_test.go

Plugin is scraping metrics from JSON endpoint exposed by in_monitor plugin.
I've used custom function to parse JSON output due to output incoherency.
Please review and share your thoughts.
Thanks!

Add fluentd input plugin

---

plugins/inputs/net_response/README.md
plugins/inputs/net_response/net_response.go
plugins/inputs/net_response/net_response_test.go

This PR adds a newly proposed field called `result_type` (inspired by the [http_response](https://github.com/influxdata/telegraf/pull/2814) input plugin) which indicates whether a collection was either successful or failed. This should be useful for alerting purposes, and also will fix #2794. In an effort to be consistent it also removes the `string_match` boolean field and replaces it with a `string_mismatch` result type (this is a breaking change, not sure if we should keep this for backward compatibility or not).
**Proposed result types**:
- **result_type (string)** # `success`, `timeout`, `connection_failed`, `read_failed`, `string_mismatch`
```
* Plugin: inputs.net_response, Collection 1
> net_response,server=influxdata.com,port=8080,protocol=tcp,host=localhost result_type="timeout" …
```

Add result_type field to net_response input plugin

---

agent/agent.go
plugins/inputs/ntpq/ntpq.go
plugins/inputs/ntpq/ntpq_test.go

Add regular expression to tackle a problem #2386 
Change:
- Add regular expression to remove unwanted string
- Create Unit Test for this case

Fix issue #2386

---

internal/models/filter.go
internal/models/filter_test.go

Fix issue #2860 
- Add logic for case where tagpass and tagdrop were defined.
- Add Unit Test to cover this use case

fix issue #2860

---

docs/CONFIGURATION.md
internal/models/filter.go
internal/models/filter_test.go

This MR is the result of #2860 discussion/issue.
- Adjust logic in functions responsible for passing metrics (should Field/Name/Tags Pass) in order to be able to process them correctly in case where pass and drop are defined together.
- Change documentation to reflect this change
- Create additional Unit Tests to cover `shouldFieldPass` and `shouldNamePass`.
- Small refactor

fix logic in tags/names/fields filtering

---

Godeps
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
testutil/accumulator.go

This patch fixes #2964 
It take cares of the OnlineCPUs info that is returned by recent docker daemons (and which is set to number of CPU by the client if the daemon does not return it).
It updates the docker client to 17.03.2-ce.
I have added an assertion test method to check that telegraf does not added tagged metrics for offline cpu.
The cpu usage percentage calculation takes also cares of the online cpus.

Online cpus

---

internal/globpath/globpath.go
internal/globpath/globpath_test.go

This prevents a pattern with no wildcards from matching in case
permissions is denied.
closes #3037

Don't match pattern on any error

---

plugins/inputs/dns_query/README.md
plugins/inputs/dns_query/dns_query.go

Add explicit network control option to dns_query

---

agent/agent.go
internal/models/running_aggregator.go
internal/models/running_aggregator_test.go

Fixes issue where metrics collected immediately after startup would not
be aggregated.

Start first aggregator period at startup time

---

plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

Add redis_version field to redis input

---

Godeps
plugins/inputs/docker/README.md
plugins/inputs/docker/client.go
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

Add tls options to docker input

---

docs/WINDOWS_SERVICE.md

Troubleshooting  error #1067  "failed to start service"
When installing as service, always double check to specify full path of the config file:  --config C:\"Program Files"\Telegraf\telegraf.conf
Otherwise windows service will fail to start

WINDOWS_SERVICE.md

---

plugins/inputs/couchbase/README.md
plugins/inputs/couchbase/couchbase.go
plugins/inputs/couchbase/couchbase_test.go

Fix issue #1680
- In `cluster` tag, use information provided by CouchDB API instead of getting it from telegraf server configuration where user is able to provide credentials.
- Adjust Unit Tests to new values.

Sanitize password from couchbase metric #1680

---

CHANGELOG.md
etc/telegraf.conf
plugins/aggregators/all/all.go
plugins/aggregators/histogram/README.md
plugins/aggregators/histogram/histogram.go
plugins/aggregators/histogram/histogram_test.go

The ability of collecting metrics for histogram was added.

The histogram aggregator plugin  was added.

---

plugins/inputs/zipkin/cmd/thrift_serialize/thrift_serialize.go
plugins/inputs/zipkin/testdata/json/distributed_trace_sample.json

Addresses comment https://github.com/influxdata/telegraf/pull/3080#discussion_r130700933

Zipkin thrift cli tool refactor

---

plugins/inputs/logparser/logparser.go
plugins/inputs/logparser/logparser_test.go

Useful when using glob patterns to select multiple files.
#2150

Add path tag to logparser containing path of logfile

---

plugins/inputs/all/all.go
plugins/inputs/salesforce/README.md
plugins/inputs/salesforce/salesforce.go
plugins/inputs/salesforce/salesforce_test.go

Gather metrics about limits and usage for a Salesforce organisation.

add salesforce input plugin

---

plugins/inputs/varnish/README.md
plugins/inputs/varnish/varnish.go
plugins/inputs/varnish/varnish_test.go

##
Varnishstat requires read access to the underlying varnish libs at /var/lib/varnish. Since some users don't run telegraf as root we either need to setfacls on this directory or enable sudo to execute this command (default is false).
Looking back in history a bit, it seems sudo is the preferred method:
https://www.varnish-cache.org/lists/pipermail/varnish-misc/2011-November/021426.html
sudo = false
```
$ telegraf --config /etc/telegraf/telegraf.conf --input-filter varnish --test
* Plugin: inputs.varnish, Collection 1
2017-08-07T18:33:17Z E! error gathering metrics: error running varnishstat: Command timed out.
```
sudo = true
```
$ telegraf --config /etc/telegraf/telegraf.conf --input-filter varnish --test
* Plugin: inputs.varnish, Collection 1
> varnish,section=MAIN …
```

Adding Varnish sudo rules for unprivileged users

---

plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Converge to typed value in prometheus output

---

CHANGELOG.md
plugins/inputs/system/DISK_README.md
plugins/inputs/system/disk.go

add weighted_io_time to diskio input

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/client/http_test.go
plugins/outputs/influxdb/influxdb.go

An approach for fixing #2802. Adds an optional parameter `gzip` (default: `false`), which if enabled, will compress the payload of each HTTP request sent to InfluxDB using GZIP.
While testing I was able to get on average 67% space savings when comparing the content length of the compressed vs. uncompressed payloads using the default sample `telegraf.conf` with no input filters.

Add influxdb gzip support

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

If the ping executable returns with exit status 1, don't report an error yet and try to parse output.  If the exit status is not 1 return without trying to parse, this is a change from the current behavior.
Here are some output examples:
```
[[inputs.ping]]
urls = ["timeout.example.org", "8.8.8.8"]
count = 1
```
```
$ ./telegraf --test
> ping,url=8.8.8.8 packets_transmitted=1i,packets_received=1i,percent_packet_loss=0,minimum_response_ms=14.791,average_response_ms=14.791,maximum_response_ms=14.791 1502758914000000000
> ping,url=timeout.example.org packets_transmitted=1i,packets_received=0i,percent_packet_loss=100 1502758915000000000
```
```
$ PATH= ./telegraf --test
2017-08-15T01:02:07Z E! Error in plugin [inputs.ping]: exec: "ping": executable file not found in $PATH
2017-08-15T01:02:07Z …
```

Remove log message on ping timeout

---

plugins/inputs/tomcat/README.md
plugins/inputs/tomcat/tomcat.go
plugins/inputs/tomcat/tomcat_test.go

adding tomcat plugin

---

plugins/inputs/rabbitmq/README.md
plugins/inputs/rabbitmq/rabbitmq.go

@phemmer I don't see a Connections parameter, but this documents the queue parameter.
closes #2165

Add queues to rabbitmq documentation

---

etc/telegraf.conf
plugins/aggregators/histogram/README.md
plugins/aggregators/histogram/histogram.go

It has been pointed out that the terminology of the histogram aggregator does not match the terms we use in other plugins, and since this plugin has not been released yet I have adjusted `metric_name` and `metric_field` to `measurement_name` and `field`.
While I was in there I updated the documentation to better fit with example readme.
@vlamug If you have time can you double check my work?  If not, be aware of the name change in the 1.4 release.

Rename histogram options and update documentation

---

metric/escape.go
metric/metric.go
metric/metric_test.go
metric/reader_test.go

Escape backslash within a string field

---

plugins/inputs/ntpq/ntpq.go
plugins/inputs/ntpq/ntpq_test.go

- added test cases for SHM remotes;
- slightly changed the fix for #2386 to improve and fix the parsing of SHM remotes.

Fixed #3162 fix parsing of SHM remotes

---

plugins/inputs/zfs/zfs_freebsd.go
plugins/inputs/zfs/zfs_freebsd_test.go

`zpool list -Hp` will report:
```
temp2   -       -       -       -       -       -       -       UNAVAIL -
zroot   110595407872    53253271552     57342136320     -       16% 48      1.00x   ONLINE  -
```
Before this parsing will fail trying to convert - to Int.
Signed-off-by: Rickard von Essen <rickard.von.essen@gmail.com>

zfs: Don't fail parsing of zpool stats if pool health is UNAVAIL on FreeBSD

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/client/http_test.go
plugins/outputs/influxdb/influxdb.go

Allows users to add meta-data to metric payloads via HTTP headers that may be useful to intermediary/gateway services. These services may perform interesting routing, throttling, tracing, auth functions.

HTTP headers can be added to InfluxDB output

---

plugins/outputs/kinesis/README.md
plugins/outputs/kinesis/kinesis.go
plugins/outputs/kinesis/kinesis_test.go

cleanup and adding support for sharding based on metric name

---

plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

Added CloudWatch metric constraint validation for float64 numbers. The constraints are detailed here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html. Added relevant links in comments for those otherwise magic numbers.
Also added positive and negative tests for these boundaries.
This change should fix influxdata/telegraf#2523
Signed-off-by: Jeff Nickoloff <jeff@allingeek.com>

Added CloudWatch metric constraint validation

---

docs/DATA_FORMATS_OUTPUT.md
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go

Hi there. 
I try to use telegraf with graphite. Right now I see some problems, because some fields values are non-numeric and graphite didn't support that. 
I didn't sure that I want to change that, because of https://github.com/influxdata/telegraf/pull/1015#issuecomment-211090770. 
Graphite format supports only numeric values. So, maybe we can skip strings?

Skip non-numerical values in graphite format

---

plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go
plugins/outputs/kafka/kafka_test.go

Add ability to the Kafka output plugin to send data to different topics, based on the metric name or tags
This addresses #3177

Add Kafka output plugin topic_suffix option

---

plugins/inputs/system/DISK_README.md
plugins/inputs/system/disk.go
plugins/inputs/system/disk_test.go

This patch just adds the mount options to the disk metrics. This is useful for alerting, for example, when a partition gets remounted as read only due an error.
- [*] Signed [CLA](https://influxdata.com/community/cla/).
- [*] Associated README.md updated.
- [*] Has appropriate unit tests.

Include mount options in disk metrics

---

plugins/outputs/amon/amon.go
plugins/outputs/datadog/datadog.go
plugins/outputs/influxdb/client/http.go
plugins/outputs/librato/librato.go

Add support for the normal proxy environment variables to all of the output plugins.
closes #1588

Add support for standard proxy env vars in outputs.

---

plugins/inputs/http_listener/README.md
plugins/inputs/http_listener/http_listener.go
plugins/inputs/http_listener/http_listener_test.go

This enhancement allows a user to enable TLS for the endpoint by providing certificate and private key files. They can use private PKI by specifying a list of certificate authority file names. Mutual TLS authentication can be enabled by providing a list of allowed client CA certificate files.
Signed-off-by: Jeff Nickoloff <jeff@allingeek.com>

TLS and MTLS enhancements to HTTPListener input plugin

---

plugins/inputs/webhooks/webhooks.go

Change HTTP listener by removing `ListenAndServe()` method and implementing `Close() net.Listen()` methods.
Change error reporting, by disabling adding it in case when `http.ErrServerClosed` occurred.

Fix address already in use with webhooks input during reload 

---

plugins/inputs/logparser/README.md
plugins/inputs/logparser/logparser.go
plugins/inputs/tail/README.md
plugins/inputs/tail/tail.go

Add the ability to use polling to watch for file changes to tail and logparser.
The default is still to use inotify, but I may change this depending on reliability feedback, as there are a number of bugs open with inotify as well as it being supported on non-linux platforms.
supersedes #2858
closes #2981 
related #2965, #2847

Add polling method to logparser and tail inputs

---

plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go

Add connection_timeout option that is corresponding with the same option in MQTT library.
Add connect() function in order to provide reconnect functionality and to remove requirement for initial connection to be available when telegraf starts.

Fix MQTT input exits if Broker is not available on startup 

---

plugins/inputs/kubernetes/kubernetes.go

Add timeout option for kubernets

---

etc/telegraf.conf
plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/client/http_test.go
plugins/outputs/influxdb/influxdb.go

Fixes issues:
- #2568
- #2750 
Duplicate of PR #2751, attempts to address https://github.com/influxdata/telegraf/pull/2751#issuecomment-306721832

Respect path prefix in influx output uri

---

plugins/outputs/opentsdb/opentsdb.go
plugins/outputs/opentsdb/opentsdb_test.go

Whitelist allowed char classes for opentsdb output.

---

plugins/inputs/statsd/statsd.go

Correctly categorizes StatsD counter and gauge metric types.

Fix StatsD counter and gauge metric types

---

plugins/inputs/iptables/iptables.go
plugins/inputs/iptables/iptables_test.go

closes #3229 
This was a regression caused by #3060, For the fix, I brought back a modified version of the valuesRe that was removed in that pull request.

Fix skipped line with empty target in iptables

---

plugins/inputs/sqlserver/sqlserver.go

When running the performance counter query against SQL Server 2016 SP1-CU2, you will see PK errors when inserting the performance counters into the temp table. The performance counter DMV contains duplicate entries which are not handled by the query. Adding `DISTINCT` to the queries retrieving the results will resolve this issue.
I also tried setting the PK on the temp tables to ignore duplicate keys, but the distinct was marginally cheaper on my system, and likely more backwards compatible.

Fixed a bug in the performance counter query

---

plugins/inputs/statsd/README.md
plugins/inputs/statsd/running_stats.go
plugins/inputs/statsd/statsd.go
plugins/inputs/statsd/statsd_test.go

Adds support to calculate StatsD timing sums as requested by #2823.

Calculate StatsD timing metric type sum

---

plugins/inputs/statsd/running_stats.go
plugins/inputs/statsd/running_stats_test.go

Fixes an index out of range panic when calculating p100. The following line evaluates to the length of the array when n = 100.
```Go
i := int(float64(len(rs.perc)) * float64(n) / float64(100))
```
I've updated the existing tests to check p0 and p100 boundary conditions.

Fix StatsD p100 calculation

---

CHANGELOG.md
Godeps
plugins/inputs/procstat/README.md
plugins/inputs/procstat/process.go
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go

This adds resource limits to the procstat input plugin.
closes #2617

add process resource limits to procstat input

---

plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Make the metrics path configurable but /metrics by default. Using a non
default value can be useful when used in k8s pods with multiple containers
that have non standard prometheus metric paths.
Some apps already use /metrics for something else.
- [*] Signed [CLA](https://influxdata.com/community/cla/).
- [*] Associated README.md updated.
- [*] Has appropriate unit tests.

Configurable metrics endpoint for prometheus output

---

plugins/inputs/statsd/statsd.go
plugins/inputs/statsd/statsd_test.go

I noticed we have a TCP Benchmark but not one for UDP, which would be useful for #3254 so I added one based on the existing test.  When running this I found that the plugin can deadlock on shutdown if there are messages pending on the input channel.
cc @agnivade

Unlock Statsd when stopping to prevent deadlock

---

plugins/inputs/prometheus/prometheus.go
plugins/inputs/prometheus/prometheus_test.go

Follow-up PR for https://github.com/influxdata/telegraf/pull/3236
- for `kubernetes_services` URLs, the `url` tag will have the value of the original service URL (as you already have the `address` tag created)
- for `url` URLs, the `url` tag will have the URL value

Prometheus plugin: Tagging original URL in case of Kubernetes services

---

plugins/inputs/statsd/statsd.go
plugins/inputs/statsd/statsd_test.go

- Instead of allocating a byte slice everytime we get a message,
we can use a sync.Pool to keep those buffers and reuse them.
~- [ ] Has appropriate unit tests.~

improve statsd plugin by using a byte buffer pool

---

plugins/inputs/postgresql_extensible/postgresql_extensible.go
plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
testutil/accumulator.go

adds unit tests covering the issue in #2052 
basically comes down to example given in the issue is that postgresql treats 
`SELECT 10.0 AS myvalue` as being numeric and not a float and then the driver we're using treats that as a string. nothing needs to be done in telegraf to fix the issue its driver related. followup will be to work with the driver maintainer to see about a resolution. in the meantime if the user wants it to be emitted as a float they can alter the query to `SELECT 10.0::float AS myvalue`

[postgresql_extensible] additional tests.

---

Godeps
etc/telegraf.conf
plugins/inputs/nsq_consumer/README.md
plugins/inputs/nsq_consumer/nsq_consumer.go
plugins/inputs/nsq_consumer/nsq_consumer_test.go

This PR adds support for NSQLookupd in `nsq_consumer`.
Why:
Existing solution where `nsq_consumer` reads only from a single NSQD server limits ability to take advantages from distributed nature of NSQ.
NSQ godocs suggest to use `nsqlookupd` as a prefered method for connection (https://godoc.org/github.com/nsqio/go-nsq#Consumer.ConnectToNSQD):
> It is recommended to use ConnectToNSQLookupd so that topics are discovered automatically. This method is useful when you want to connect to a single, local, instance.
`nsqlookupd` is the daemon that manages topology information. Clients query nsqlookupd to discover nsqd producers for a specific topic and nsqd nodes broadcasts topic and channel information.
With `nsqLookupd` support `nsq_consumer` will detect all avaiable nsqd producers and connects …

NSQLookupd support for nsq_consumer

---

plugins/inputs/httpjson/httpjson.go
plugins/inputs/httpjson/httpjson_test.go

Fix parsing of JSON with a UTF8 BOM in httpjson

---

plugins/inputs/all/all.go
plugins/inputs/jolokia2/README.md
plugins/inputs/jolokia2/client.go
plugins/inputs/jolokia2/client_test.go
plugins/inputs/jolokia2/examples/java.conf
plugins/inputs/jolokia2/examples/kafka.conf
plugins/inputs/jolokia2/gatherer.go
plugins/inputs/jolokia2/gatherer_test.go
plugins/inputs/jolokia2/jolokia.go
plugins/inputs/jolokia2/jolokia_agent.go
plugins/inputs/jolokia2/jolokia_proxy.go
plugins/inputs/jolokia2/jolokia_test.go
plugins/inputs/jolokia2/metric.go
plugins/inputs/jolokia2/point_builder.go

This PR is an attempt to deprecate the initial Jolokia input plugin. The shortcomings of the initial Jolokia plugin include:
- inability to extract more than one measurement from a single input
- inability to capture tags from mbean names [#2014](https://github.com/influxdata/telegraf/issues/2014)
I'll gladly add other target "shortcomings" should they come up and be in scope. 
Taking inspiration from the `win_perf_counters` input, the core change here is to tie measurements to mbeans, rather than folding all mbean requests to a single "jolokia" measurement.
Feedback is welcome.
*I'm available for discussion on the gophers #influxdb channel as @dylanmei.*
Checkout `quay.io/nordstrom/telegraf:latest` to test-drive this.

Redesign the Jolokia input plugin (as Jolokia2)

---

plugins/inputs/webhooks/rollbar/README.md
plugins/inputs/webhooks/rollbar/rollbar_webhooks.go
plugins/inputs/webhooks/rollbar/rollbar_webhooks_events.go
plugins/inputs/webhooks/rollbar/rollbar_webhooks_events_json_test.go
plugins/inputs/webhooks/rollbar/rollbar_webhooks_test.go

Rollbar added a new event triggered on each occurrences. 
Tested in production, my number of occurrences matche the ones from rollbar ;)

Add support for the new occurrence webhook event from rollbar

---

plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go

Fix format of connection_timeout in mqtt_consumer

---

plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongostat.go

MongoDB input plugin: Add extra wired tiger cache metrics

---

plugins/outputs/wavefront/wavefront.go
plugins/outputs/wavefront/wavefront_test.go

Need to have a newline character at end of each metric sent to wavefront-proxy to work on all platforms properly.

Add newline to each metric for Wavefront output

---

plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go
plugins/inputs/elasticsearch/elasticsearch_test.go
plugins/inputs/elasticsearch/testdata_test.go

We found that the plugin generates a lot of data and also makes Elasticsearch work quite hard to generate the data (in some cases not necessary, if you are not interested in all the data).
New configurability:
- ability to get base cluster health information without querying for indices health
```toml
cluster_health = false
```

elasticsearch input: ability to get base cluster health information without querying for indices health

---

plugins/inputs/system/cpu.go
plugins/inputs/system/cpu_test.go

Fix panic in cpu input if number of cpus changes

---

plugins/outputs/influxdb/client/client.go
plugins/outputs/influxdb/client/http.go
plugins/outputs/influxdb/client/http_test.go
plugins/outputs/influxdb/client/udp.go
plugins/outputs/influxdb/client/udp_test.go
plugins/outputs/influxdb/influxdb.go

Remove the Content-Length header from all POSTs to InfluxDB.
With the current metrics.Reader the content length cannot be determined without buffering the full request body.  Our choice to fix this issue then are:
- Replace metrics.Reader with a static length serializer regardless of buffer size.
- Buffer the full request to get the actual size.
- Remove the Content-Length header and use chunked transfer encoding.
The later was the quickest and least risk, so I went with that for now.  In the future, I think we should replace the metrics.Reader with a more appropriate abstraction, as it doesn't allow for the line based structure of line protocol very well.
closes #2854

Use chunked transfer encoding in InfluxDB output

---

plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go
plugins/inputs/elasticsearch/elasticsearch_test.go
plugins/inputs/elasticsearch/testdata_test.go

We found that the plugin generates a lot of data and also makes Elasticsearch work quite hard to generate the data (in some cases not necessary, if you are not interested in all the data).
New configurability:
- ability to get individual node stats
Example configuration to just get only JVM information:
```yaml
[[inputs.elasticsearch]]
servers = ["http://elasticsearch-host:9200"]
local = false
cluster_health = false
indices_health = false
cluster_stats = true
individual_stats = ["jvm"]
```

elasticsearch input: ability to get individual node stats

---

plugins/aggregators/all/all.go
plugins/aggregators/basicstats/README.md
plugins/aggregators/basicstats/basicstats.go
plugins/aggregators/basicstats/basicstats_test.go

The BasicStats aggregator plugin give us count,max,min,mean,s2(variance), stdev for a set of values,
emitting the aggregate every `period` seconds.
```toml
[[aggregators.basicstats]]
period = "30s"
drop_original = false
```
- measurement1
- field1_count
- field1_max
- field1_min
- field1_mean
- field1_s2 (variance)
- field1_stdev (standar deviation)
No tags are applied by this aggregator.
```
$ telegraf --config telegraf.conf --quiet
system,host=tars load1=1 1475583980000000000
system,host=tars load1=1 1475583990000000000
system,host=tars load1_count=2,load1_max=1,load1_min=1,load1_mean=1,load1_s2=0,load1_stdev=0 1475584010000000000
system,host=tars load1=1 1475584020000000000
system,host=tars load1=3 1475584030000000000
system,host=tars …
```

Added new basicstats aggregator

---

plugins/inputs/system/DISK_README.md

I got the documented equation wrong for calculating the average queue depth. I based it off [the equation in iostat](https://github.com/sysstat/sysstat/blob/33557c3db463ac6efb337a67dd5f099609d62b30/iostat.c#L1042:L1044), but the iostat `/1000` was for the time unit conversion. For us this is handled by the `derivative(..., 1ms)`.
Demonstration of the correct equation:
```
Linux 3.10.0-514.21.2.el7.x86_64 (fll2gdbs10stg) 	10/12/17 	_x86_64_	(2 CPU)
...
10/12/17 17:08:32
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     4.47 1479.13   12.33 756996.80   117.33  1015.26     9.39    6.30    6.34    1.26   0.65  96.96
10/12/17 17:08:47
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s …
```

fix documented equation for diskio average queue depth

---

plugins/outputs/cloudwatch/README.md
plugins/outputs/cloudwatch/cloudwatch.go

Fixes #3319. Use STS to validate the provided credentials work, rather than `ListMetricData` which requires a separate permission, and document the required permission.
I'm not sure about unit tests since none exist using mock AWS, but I did some manual testing.
I made a test IAM user with only `cloudwatch:PutMetricData` permission, policy:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"cloudwatch:PutMetricData"
],
"Resource": [
"*"
]
}
]
}
```
I then used its access key as environment variables locally and ran telegraf in this environment, with this config:
```ini
[agent]
debug = "true"
[[outputs.cloudwatch]]
region = "eu-west-1"
namespace = "InfluxData/Telegraf"
[[inputs.cpu]]
```
I then successfully saw data flushed when running telegraf like so:
```
$ …
```

Improved Cloudwatch output plugin Connect()

---

plugins/inputs/statsd/README.md
plugins/inputs/statsd/statsd.go

Enable the ability to specify IPv4/6 expilcitly when listening on UDP

---

CHANGELOG.md
plugins/inputs/system/cpu.go
plugins/inputs/system/cpu_test.go

This fix an issue when a Linux system is suspended, after resuming, Telegraf no longer send CPU metrics and log:
```
oct. 16 11:09:12 xps-pierref telegraf[8363]: 2017-10-16T09:09:12Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
oct. 16 11:09:22 xps-pierref telegraf[8363]: 2017-10-16T09:09:22Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
[...]
```
This occur after a suspend, because /proc/stat counter decrease ! [1]
On previous Telegraf version this issue did not occured  because it updated lastStats and complained only ONCE. PR #3306 [changed this behavior](https://github.com/influxdata/telegraf/pull/3306/files#diff-ad280c07b9dc22406895aad96d9b41e7L95).
This PR restore the old …

Fix CPU system plugin that get stuck after suspend

---

scripts/telegraf.service

With the brackets you cannot add more than 1 flag to the ExecStart command. Flags that require arguments will not work.
The following addition to /etc/default/telegraf gives a "flag provided but not defined" ERROR and the service fails to start. Removing the brackets from $TELEGRAF_OPTS fixes this.
#/etc/default/telegraf
TELEGRAF_OPTS=-pidfile /var/run/telegraf/telegraf.pid
log: flag provided but not defined: -pidfile /var/run/telegraf/telegraf.pid
https://www.freedesktop.org/software/systemd/man/systemd.service.html
"Use "${FOO}" as part of a word, or as a word of its own, on the command line, in which case it will be replaced by the value of the environment variable including all whitespace it contains, resulting in a single argument. Use "$FOO" as a separate word on the command line, …

telegraf.service remove curly brackets on $TELEGRAF_OPTS

---

plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/prometheus.go
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

This is an alternative pull request to #3337, I added the setting of metric types in the prometheus input, and use that in the prometheus output to adjust the output format.  I think this will have less potential for side effects.
I also included @jdoupe suggestion to use the promhttp package, as well as adding his configurable disabling of the built in collectors.  It would be nicer to disable them by default, since outputs shouldn't really create metrics, but for now they default on.
I added the `ErrorHandling: promhttp.ContinueOnError` option which seems to prevents conflict if the help message is different.  This will reduce the visibility of errors, but it seems it may be necessary.  In the long term I would like to add metadata support to our metrics struct, so that help info can be …

Fix prometheus passthrough for existing value types

---

plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Use labels in prometheus output for string fields

---

plugins/inputs/logparser/README.md
plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go

Add support for converting a unix time with decimal portion to a timestamp to the ts-epoch modifier.
closes #1912

Add support for decimal timestamps to ts-epoch modifier

---

plugins/inputs/consul/consul.go
plugins/inputs/consul/consul_test.go

Consul input plugin has been fixed to set ACL token in API client config so that it will be included into API requests as `X-Consul-Token` header.
Closes #3375

Fix token usage in consul input plugin (#3375)

---

plugins/inputs/tomcat/tomcat.go
plugins/inputs/tomcat/tomcat_test.go

If the connector name cannot be unquoted, use the raw value

---

plugins/inputs/system/disk.go
plugins/inputs/system/disk_linux.go

This pull request is currently for testing only, it **might** fix the crash reported in #3373, #3299.

Use golang.org/x/sys/unix instead of syscall in diskio

---

accumulator.go
agent/accumulator.go
metric.go
plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/prometheus.go
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go
testutil/accumulator.go

UPDATE: After the merge of #3351, this PR now only addresses the handling of history and summary types.
---
This contains a couple fixes for the prometheus_client output.
- The prometheus.http module is deprecated.  Updated to use prometheus/promhttp.
- The plugin renamed metrics by appending field names, even when that didn't make sense.
For example, when using the prometheus input plugin, field names of "counter" and "gauge" were created (instead of just "value"), and then the metrics would have "counter" and "gauge" appended to them on the output.
- When the prometheus input was used, the histogram and summary types were not handled gracefully.  For …

Fix prom client output

---

plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

Adds concurrent collection for each agent, each agent is still gathered sequentially.
I changed the connection cache to hold connections by index, in case the agent list contains multiples of the same destination.
#1665

Gather concurrently from snmp agents

---

plugins/inputs/varnish/varnish.go
plugins/inputs/varnish/varnish_test.go

This change add a new configuration option to allow probing of
namespaced varnish instances, usually reached using the '-n' switch on
the varnish cli.

Add instance option to varnish plugin

---

plugins/outputs/elasticsearch/README.md
plugins/outputs/elasticsearch/elasticsearch.go

Add support for SSL settings to ElasticSearch output plugin

---

plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go

This is the same fix as #3173 but contains backwards compatibility for host:port servers.

Use explicit schemas in mqtt_consumer input

---

agent/agent.go
internal/config/config.go
metric/parse.go
metric/reader_test.go
plugins/inputs/cloudwatch/cloudwatch.go
plugins/inputs/couchbase/couchbase.go
plugins/inputs/dns_query/dns_query.go
plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/iptables/iptables_test.go
plugins/inputs/mesos/mesos.go
plugins/inputs/minecraft/internal/rcon/rcon.go
plugins/inputs/minecraft/minecraft.go
plugins/inputs/minecraft/rcon.go
plugins/inputs/phpfpm/fcgi_client.go
plugins/inputs/phpfpm/phpfpm_test.go
plugins/inputs/ping/ping_windows.go
plugins/inputs/powerdns/powerdns_test.go
plugins/inputs/statsd/statsd.go
plugins/inputs/sysstat/sysstat.go
plugins/inputs/system/cpu_test.go
plugins/inputs/win_perf_counters/pdh.go
plugins/inputs/win_perf_counters/win_perf_counters.go
plugins/outputs/graphite/graphite.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/opentsdb/opentsdb_test.go
plugins/outputs/riemann_legacy/riemann.go

This was fixed running the `misspell` linter in fix mode using `gometalinter`. The exact command I ran was :
```
gometalinter --vendor --disable-all -E misspell --linter='misspell:misspell -w {path}:^(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$' ./...
```
Plus some typo were fixed by hand on top of it.
I reviewed the diff, no code is affected (just some error logs).

Fix typos in comments across repository

---

CHANGELOG.md
appveyor.yml
circle.yml

Updates both CircleCI and AppVeyor configs to Go 1.9.2.

Update CI configs to Go 1.9.2

---

plugins/inputs/procstat/README.md
plugins/inputs/procstat/procstat.go

This adds the ability to identify the process to monitor by asking systemd for the PID. It uses the "Main PID" value you can see in `systemctl status`. In the event that the "children" parameter is `true`, it grabs all the PIDs within the Cgroup that systemd creates for the service.
I didn't want to add the "children" parameter to just systemd, so I also added it to the existing process matching stuff. Though it is a little heavy as it calls `pgrep` recursively until it reaches the end of the chain.
Closes #3439

add systemd unit pid matching to procstat

---

CHANGELOG.md
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go

Whitelist allowed char classes for graphite output

---

plugins/inputs/webhooks/README.md
plugins/inputs/webhooks/particle/README.md
plugins/inputs/webhooks/particle/particle_webhooks.go
plugins/inputs/webhooks/particle/particle_webhooks_test.go
plugins/inputs/webhooks/webhooks.go
plugins/inputs/webhooks/webhooks_test.go

A Webhook Plugin for the Partricle.io platform

Add Particle Webhook Plugin

---

plugins/inputs/sqlserver/sqlserver.go

Using SUM() results in multi-second latency measurements when multiple files are used for a database - which is typical for tempdb.  Using MAX() gives a more meaningful measurement.   AVG() can be used as well but will hide problems when one of the db files encounters a problem.  Example:
File0: 30ms
File1: 40ms
File2: 50ms
File3: 60ms
File4: 70ms
File5: 80ms
File6: 90ms
SUM (currently what is reported) results in 420 ms latency, MAX (current proposal) in 90ms and AVG in 60ms

 use MAX() instead of SUM() for latency measurements

---

plugins/outputs/elasticsearch/README.md
plugins/outputs/elasticsearch/elasticsearch.go
plugins/outputs/elasticsearch/elasticsearch_test.go

Add week number to Elasticsearch output 

---

README.md
etc/telegraf.conf
plugins/inputs/all/all.go
plugins/inputs/unbound/README.md
plugins/inputs/unbound/unbound.go
plugins/inputs/unbound/unbound_test.go
plugins/inputs/unbound/unbound_windows.go

This plugin gathers stats from Unbound - a validating, recursive, and caching DNS resolver (https://www.unbound.net/)

Add unbound input plugin

---

README.md
etc/telegraf.conf
plugins/inputs/all/all.go
plugins/inputs/opensmtpd/README.md
plugins/inputs/opensmtpd/opensmtpd.go
plugins/inputs/opensmtpd/opensmtpd_test.go

This plugin gathers stats from [OpenSMTPD - a FREE implementation of the server-side SMTP protocol](https://www.opensmtpd.org/).

Input plugin opensmtpd

---

plugins/inputs/snmp/snmp.go

Fix snmp tools output parsing when they contain Windows eols

---

plugins/inputs/mysql/mysql.go

When you set `interval_slow` (to a positive value), MySQL plugin starts gathering the global variables.
What is expected (in accordance with the README.md): The gathering of variables occurs at a slower pace than the regular telegraf data collection interval. And the pace would be the value `interval_slow` (+ an eventual jitter of 1 telegraf interval).
What is actually happening: The plugin collects the global variable at every single data collection interval.
The fix is not to call the gathering when it was done less than `interval_slow` duration ago.
Note:
- I've signed the CLA
- I did not change the README.md. This pull request is to make the code behave as advertised in the README.md.
- I don't know how to produce a unit test that validates the timing. I've checked by looking at the …

MySQL plugin should not collect global variables at each telegraf data collection interval

---

plugins/inputs/jolokia2/gatherer.go
plugins/inputs/jolokia2/jolokia_test.go
plugins/inputs/jolokia2/metric.go

Addressing issue #3435 the Jolokia2 plugin can match mbeans with object name properties that are coming back in a different order than specified in the toml config.
For example, it shouldn't matter if a metric mbean was declared as
```
[[inputs.jolokia2_agent.metric]]
mbean = "Catalina:host=localhost,context=*,type=Manager"
```
or as 
```
[[inputs.jolokia2_agent.metric]]
mbean = "Catalina:type=Manager,host=localhost,context=*"
```
This update will greatly reduce confusion when working with the plugin.

Jolokia2 handles unordered mbean object name properties

---

scripts/build.py

RPM package was missing `shadow-utils` dependence.
Fix: #3447

RPM missing dependencie fix

---

scripts/post-install.sh

From man page:
```
deb-systemd-invoke is a Debian-specific helper script which asks
/usr/sbin/policy-rc.d before performing a systemctl call.
deb-systemd-invoke is intended to be used from maintscripts to start
systemd unit files. It is specifically NOT intended to be used
interactively by users. Instead, users should run systemd and use
systemctl, or not bother about the systemd enabled state in case they
are not running systemd.
```
This PR replace regular `systemctl` with `deb-systemd-invoke`.
Fix: #3448

deb-systemd-invoke restart

---

plugins/inputs/system/MEM_README.md
plugins/inputs/system/memory.go
plugins/inputs/system/memory_test.go

Add slab to mem plugin

---

plugins/inputs/postfix/postfix.go
plugins/inputs/postfix/postfix_test.go
plugins/inputs/postfix/stat_ctim.go
plugins/inputs/postfix/stat_ctimespec.go
plugins/inputs/postfix/stat_none.go

Fixes #3521 
Unfortunately ctime is not supported on all platforms, but I think the only such platform is windows, which doesn't support postfix anyway. However there are 2 different methods of getting ctime among the unix platforms, so I had to add conditional build tags to the different methods. You also cannot manually set a file's ctime, so we can't test it very well :-/

fix postfix plugin age to use ctime, not mtime

---

Godeps
plugins/inputs/system/NET_README.md
plugins/inputs/system/net.go

An approach for fixing #1073.
Adds support for specifying [golang glob](https://github.com/gobwas/glob)-style patterns.
**Example**
```
[[inputs.net]]
interfaces = ["en*", "utun[0-1]", "lo0"]
```
```
$ ./telegraf --input-filter net --config telegraf.conf --test
* Plugin: inputs.net, Collection 1
> net,interface=lo0,host=mac bytes_sent=103240327i,packets_sent=227866i,drop_in=0i,drop_out=0i,bytes_recv=103240327i,packets_recv=227866i,err_in=0i,err_out=0i 1503126134000000000
> net,interface=en0,host=macbook packets_sent=13568823i,packets_recv=23715254i,err_in=0i,err_out=0i,drop_out=3193i,bytes_sent=2411560838i,bytes_recv=30527805468i,drop_in=0i 1503126134000000000
> net,interface=en1,host=macbook bytes_sent=0i,drop_out=0i,bytes_recv=0i,packets_sent=0i,packets_recv=0i,err_in=0i,err_out=0i,drop_ …
```

Add support for glob patterns in net input plugin

---

plugins/inputs/all/all.go
plugins/inputs/pf/README.md
plugins/inputs/pf/pf.go
plugins/inputs/pf/pf_nocompile.go
plugins/inputs/pf/pf_test.go

Add input plugin for OpenBSD/FreeBSD pf

---

plugins/inputs/postfix/stat_none.go
plugins/outputs/amqp/README.md
plugins/outputs/amqp/amqp.go

Add option to amqp output to publish persistent messages

---

docs/FAQ.md
plugins/inputs/system/DISK_README.md
plugins/inputs/system/disk_test.go
plugins/inputs/system/ps.go

Based on #2812, but only filters partitions if there is a conflict between the filesystem and the `HOST_MOUNT_PREFIX`, i.e.: `/mnt/foo` vs `/hostfs/mnt/foo`.
closes #1544
closes #2811
closes #3483

Docker host mount prefix

---

plugins/outputs/wavefront/wavefront.go

If an error is returned from an output plugins Connect function, the Agent will connect once and if it fails again the agent will exit.  This behavior should probably be altered in the Output interface, so that the Connect function becomes an initialization function.  I'm planning to add an initialization function in #272 and will then revisit if the Connect function should then be removed.
In the meantime, we can log the error and return nil.  This plugin will attempt reconnect on every Write.
cc @puckpuck 
closes #3545

Log connect error only in wavefront output

---

plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go
plugins/inputs/elasticsearch/testdata_test.go

Add status_code field mapping when reporting health status.

Add health status mapping from string to int.

---

plugins/inputs/smart/README.md
plugins/inputs/smart/smart.go
plugins/inputs/smart/smart_test.go

To be consistent with diskio and /proc entries
cc @rickard-von-essen
closes #3541

Use device name instead of abs path for devices tag

---

plugins/inputs/system/PROCESSES_README.md
plugins/inputs/system/processes.go

`I` is a Linux process state: https://github.com/torvalds/linux/blob/master/fs/proc/array.c#L135
This is a fairly recent change but causes lots of Telegraf log noise with 4.x kernels.
I'll do the rest of the paperwork for the PR if the underlying idea is acceptable.

Support I (idle) process state on procfs+Linux

---

plugins/outputs/prometheus_client/prometheus_client.go

Fix separation of multiple prometheus_client outputs

---

plugins/inputs/system/SYSTEM_README.md
plugins/inputs/system/system.go

Prometheus doesn't support string fields, let's split system_uptime and system_uptime_format.
Issue #3577

Add system_uptime_format as Field, not as Counter

---

plugins/inputs/redis/README.md

Add `master_link_status` and `master_link_down_since_seconds` to the replication measurements for Redis. These measurements are provided by the plugin, but not included in the README.

Update README with missing Redis measurements

---

plugins/outputs/cloudwatch/cloudwatch.go

This method is reported to not work with IAM Instance Profiles, and we
do not want to make any calls that would require additional permissions.
closes #3474

Remove AWS credential check from cloudwatch output

---

plugins/aggregators/basicstats/README.md
plugins/aggregators/basicstats/basicstats.go
plugins/aggregators/basicstats/basicstats_test.go

Basic implementation of configuring which stats are pushed from basicstats aggregator (https://github.com/influxdata/telegraf/issues/3413)

Configurable basicstats

---

plugins/inputs/rabbitmq/README.md
plugins/inputs/rabbitmq/rabbitmq.go

As discussed in #3586. `messages_delivered_get` represents the grand total of messages delivered since the node's startup.

Add messages_delivered_get to rabbitmq_overview

---

plugins/inputs/postfix/README.md

Add information about how to set postfix permissions

---

plugins/outputs/cloudwatch/cloudwatch.go

Re-add the check removed in #3583, but this time using the right API call that doesn't require any additional permissions. Fixes #3474.
I tested this by running telegraf locally with my personal credentials, and also running `$ aws sts get-caller-identity` on an EC2 instance that had an IAM Role/instance profile with zero permissions.
- -[ ] Associated README.md updated.-

Re-add AWS credential check from cloudwatch output

---

plugins/inputs/system/MEM_README.md
plugins/inputs/system/memory.go
plugins/inputs/system/memory_test.go

closes #3628
Ideally this patch would not report wired on systems that do not have this field, however I think this is an acceptable change since we are already reporting active and inactive.

Add wired field to mem input

---

plugins/inputs/rabbitmq/rabbitmq.go

The json output has apparently never been parsed correctly.

Fix deliver_get in RabbitMQ

---

plugins/inputs/rabbitmq/README.md
plugins/inputs/rabbitmq/rabbitmq.go
plugins/inputs/rabbitmq/rabbitmq_test.go

Add RabbitMQ exchanges

---

internal/config/config.go

Escape environment variables during config toml parsing

---

plugins/inputs/system/KERNEL_README.md
plugins/inputs/system/kernel.go
plugins/inputs/system/kernel_test.go

Monitor available entropy

---

CHANGELOG.md
plugins/inputs/ipmi_sensor/README.md
plugins/inputs/ipmi_sensor/connection.go
plugins/inputs/ipmi_sensor/connection_test.go
plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/ipmi_sensor/ipmi_test.go

Based on #2397 by @Stefan-Code 
closes #2284

added user privilege level setting to IPMI sensors

---

.gitignore
Godeps
README.md
docs/DATA_FORMATS_INPUT.md
internal/config/config.go
internal/templating/engine.go
internal/templating/matcher.go
internal/templating/node.go
internal/templating/template.go
plugins/parsers/dropwizard/parser.go
plugins/parsers/dropwizard/parser_test.go
plugins/parsers/graphite/parser.go
plugins/parsers/graphite/parser_test.go
plugins/parsers/registry.go

Add support for dropwizard format

---

plugins/inputs/http_listener/http_listener_test.go
plugins/inputs/statsd/statsd_test.go
plugins/inputs/tcp_listener/tcp_listener_test.go

Update to have all test listeners listen only on localhost to prevent macOSX firewall prompts to "allow incoming connections" on the listeners.
This is per https://medium.com/@leeprovoost/suppressing-accept-incoming-network-connections-warnings-on-osx-7665b33927ca

Have all test listeners listen only on localhost

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_testdata.go

This is a continuation of #3493
I fixed the tests to pass by adding mock data to the container inspect data that is being referenced.
Let me know if anything else is required.

Docker healthcheck (cont. of #3493)

---

plugins/parsers/graphite/parser.go

Updates the Graphite parser to ignore empty lines in incoming Graphite plaintext.
Currently, empty lines result in an error and Telegraf fails to parse the incoming packet.

Ignore empty lines in Graphite plaintext

---

plugins/inputs/solr/solr.go
plugins/inputs/solr/solr_test.go

(**n/a**)
Fixes Issue: https://github.com/influxdata/telegraf/issues/3604

Fix index out of bounds exception on solr input plugin

---

Godeps
plugins/inputs/redis/redis.go

No functionality changes, this is only to improve error handling and future extensibility of this plugin.

Refactor redis input to use go-redis

---

plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go

If writing to Graphite would fail the plugin would reconnect, but not retry to send the metrics until the next interval. In a situation when the connection would break before the next interval the metrics would never reach the Graphite server. Obviously this is a network issue which but Telegraf should handle these kind of situations better.
This patch retries to send the metrics one time immediately after reconnecting.

outputs.graphite: Retry sending metrics immediately after reconnect

---

agent/agent.go
internal/models/running_aggregator.go
internal/models/running_aggregator_test.go

By the time the aggregator.run() was called about 600ms already passed since setting now which was skewing up the aggregation intervals and skipping metrics.

aggregator: move time.now into the aggregator

---

plugins/outputs/mqtt/mqtt.go

By limiting the amount of time we will wait for message to be sent, we avoid deadlock in the mqtt output.
closes #3697

Limit wait time for writes in mqtt output

---

agent/agent.go

I think this will fix the deadlock when using an aggregator.
closes #3629

Avoid loop creation in second processor pass

---

CHANGELOG.md
cmd/telegraf/telegraf.go

- [N/A] README.md updated (if adding a new plugin)
Allow windows service to run as console application

Allow running as console application on Windows

---

plugins/inputs/postgresql_extensible/README.md

I had some issues understanding what the tagvalue-Option in the postgresql_extensible-Plugin does, especially as the README suggest that it is just a list of Tags added literally to the result-Row:
> the tagvalue field is used to define custom tags (separated by comas)
Neither does the README have an example on how the tagvalue can be used in conjunction with `GROUP BY` to add multiple result-rows to one measurement.
This PR extends the README wiith both, a more detailed explanation and such an example.

postgresql_extensible / extend README explaining the tagvalue Option

---

plugins/inputs/rabbitmq/README.md
plugins/inputs/rabbitmq/rabbitmq.go
plugins/inputs/rabbitmq/rabbitmq_test.go

- Add `running` field to the `rabbitmq_node` measurement directly mapped to the `running` flag from the output of `/api/nodes`
- Add `clustering_listeners` to the `rabbitmq_overview` measurement as the total count of listeners of protocol `clustering` from the output of `/api/overview`
- Add `amqp_listeners` to the `rabbitmq_overview` measurement as the total count of listeners of protocol `amqp` from the output of `/api/overview`

Add RabbitMQ cluster and running nodes count and running node status

---

Godeps
docs/LICENSE_OF_DEPENDENCIES.md
plugins/inputs/all/all.go
plugins/inputs/nats/README.md
plugins/inputs/nats/nats.go
plugins/inputs/nats/nats_test.go

This plugin gathers metrics a [NATS](https://nats.io/) server monitoring endpoint. Currently, only the `/varz` endpoint is used. See https://nats.io/documentation/server/gnatsd-monitoring/ for more information.
Note that this is a continuation of #3186. The original author isn't working on that PR any more.

NATS Monitoring Input Plugin

---

plugins/inputs/rabbitmq/README.md
plugins/inputs/rabbitmq/rabbitmq.go
plugins/inputs/rabbitmq/rabbitmq_test.go

Make rabbitmq_queue gathering be configurable

---

plugins/inputs/ping/README.md
plugins/inputs/ping/ping.go

Fixes issue https://github.com/influxdata/telegraf/issues/3721.
Linux supports defining the source address or source interface with paramter **I**.
FreeBSD and Darwin do only support specifying the source address and also use a different parameter **S** to set it: see [manpage](https://www.freebsd.org/cgi/man.cgi?ping(8)). 
This commit adds cases to support pings from a defined source address on other operating systems than Linux. Source interface is linux only.

ping plugin: Add cases to interface parameter

---

plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

Exclude master_replid from redis input

---

plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go

Hello community,
this commit adds support for TLS transport encryption and http basic_auth for authentication in prometheus_client output plugin.
Configurations:
Prometheus:
```
- job_name: 'ssl_test'
scheme: 'https'
tls_config:
#insecure_skip_verify: true
basic_auth:
username: 'Foo'
password: 'Bar'
static_configs:
- targets: ['localhost:9200']`
```
Telegraf configuration:
```
[[outputs.prometheus_client]]
listen = ":9200"
tls_cert = "test.crt"
tls_key = "test.key"
basic_username = "Foo"
basic_password = "Bar"
path = "/metrics"
expiration_interval = "60s"
```
Greetings,
Philipp

prometheus_client plugin: Add transport encryption via TLS and authentication via http basic_auth

---

plugins/outputs/wavefront/README.md
plugins/outputs/wavefront/wavefront.go

default sample config and readme recommended the wrong point tag to be used for source within wavefront when SNMP input plugin is used.

fix issue with SNMP source config default is incorrect

---

plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/prometheus.go
plugins/inputs/prometheus/prometheus_test.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Remove user data from URL before setting URL tag to prevent information disclosure.
See https://github.com/influxdata/telegraf/issues/3739.
Also run gofmt and turn variables with name *url* to uppercase to prevent overwrite of *net/url* package. Now it is more clear wheter the variable or package is used.

prometheus input: Remove credentials from URL before setting url tag

---

plugins/inputs/openldap/README.md
plugins/inputs/openldap/openldap.go
plugins/inputs/openldap/openldap_test.go

I noticed that this plugin wasn't including a bunch of metrics, specifically the monitoredObject entries. This PR includes those entries with numerical values for monitoredInfo.
It also changes up the field names so they sort more naturally. I know this was discussed on the original PR, and in retrospect and after using this plugin, reversing the names based on their distinguished names will make them easier to work with. This will be a breaking change for anyone already using this plugin, but I believe it will be worth it.
(please let me know if we'd rather make this two PRs so the additional metrics can be included in a release sooner on account of the breaking change)

openldap: Include more metrics, change up field names

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_windows.go

Input ping plugin now supports a response time of 0.
Fix issue #3503

Fixes #3503 -- Ping can return a response time of 0

---

plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go

I added the following new counters to the performance counter query:
- SQLServer:Resource Pool Stats
- Active memory grant amount (KB)
- Disk Read Bytes/sec
- Disk Read IO Throttled/sec
- Disk Read IO/sec
- Disk Write Bytes/sec
- Disk Write IO Throttled/sec
- Disk Write IO/sec
- Used memory (KB)
- SQLServer:User Settable
- All
- SQLServer:SQL Errors
- All
- SQLServer:Databases\Backup/Restore Throughput/sec
- SQLServer:Memory Manager\Target Server Memory (KB)
- SQLServer:Memory Manager\Total Server Memory (KB)
This was based on feedback from my previous pull request and internal feedback. I also removed the 'c_type' tag from the performance counter query and add documentation to the readme about which counters need delta calculations and which dont.

Added additional SQL Server performance counters

---

etc/telegraf.conf
plugins/inputs/statsd/README.md
plugins/inputs/statsd/statsd.go

Similar implementation to the socket listener input plugin and its [original pull request](https://github.com/influxdata/telegraf/pull/2697). Found this was really necessary to keep the server connections clean, because you can't rely on clients always being able to close them (FIN), specially if you are running Telegraf behind a load balancer. Default behaviour is still false, so that it doesn't disrupt existing setups. 
Same as the pull request 2697, unit tests for this are hard to accomplish ("There's no ability to query a socket for its current keep-alive setting") but you can observe the behaviour using packet capturing.

Add keep alive support to the TCP mode of statsd

---

plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

#3350 introduced a change where all string fields are turned to labels. However in certain cases where string value changes, it introduces a new metric due to the change in label value.
Hence this will provide an option to disable as well as enable only for certain string values. The default behavior doesn't change with this commit.

Providing option to disable labels in prometheus output for string fields

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongostat.go

Adds total stats for a shard connection pool exposed via the
`shardConnPoolStats` database command.

Add shard server stats to the mongoDB input plugin

---

README.md
plugins/inputs/unbound/README.md
plugins/inputs/unbound/unbound.go
plugins/inputs/unbound/unbound_test.go

This allows unbound plugin to connect to other servers

Add server option to unbound plugin

---

plugins/outputs/datadog/datadog.go
plugins/outputs/datadog/datadog_test.go

Boolean metric values from plugins converted to float for datadog output. For example `health_ok` in
[smart](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/smart/smart.go#L234) plugin.
Added more verbose error logging to make it easier to debug, sample error output
```
2018-02-18T17:14:41Z I! unable to build Metric for smart_device due to error 'unable to extract value from Fields health_ok error undeterminable type', skipping
```

Convert boolean metric values to float. More verbose message when failing to build a metric

---

plugins/outputs/mqtt/mqtt.go

This functionality currently has race conditions that can result in the
output deadlocking.
#3697

Disable keepalive in mqtt output.

---

plugins/inputs/solr/README.md
plugins/inputs/solr/solr.go
plugins/inputs/solr/solr_test.go
plugins/inputs/solr/testdata3_test.go

Fixes https://github.com/influxdata/telegraf/issues/3681

Add Solr 3 compatibility

---

plugins/aggregators/basicstats/README.md
plugins/aggregators/basicstats/basicstats.go
plugins/aggregators/basicstats/basicstats_test.go

Implements #3467.  `sum` is not included by default to maintain backwards compatibility.

Add sum stat to basicstats aggregator

---

plugins/inputs/snmp/README.md

This PR is fixing the type of the `inherit_tags` option in one of the examples. It must be `[]string` and not `string`.

Fixing snmp input doc

---

etc/telegraf.conf

I think this qualifies as a de minimus documentation fix. Hope you enjoy it

Add link to full fail2ban plugin docs

---

CONTRIBUTING.md

Hello!
As I'm reading the Contribution section, I've seen that there was a [link](https://github.com/influxdata/telegraf/blob/master/CONTRIBUTING.md#input-plugin-guidelines) to the `telegraf.Input` interface, but not to the `telegraf.ServiceInput` interface.
This PR will add the link below to the `telegraf.ServiceInput` interface: https://godoc.org/github.com/influxdata/telegraf#ServiceInput
I'm looking forward to receiving your feedback
Thank you!

[Docs] Add link to ServiceInput interface

---

plugins/inputs/http_response/http_response.go

Feature/http response configurable proxy #3374

---

plugins/inputs/sqlserver/sqlserver.go

different collations fix

---

plugins/inputs/passenger/passenger.go
plugins/inputs/passenger/passenger_test.go

fix uptime metric in passenger input plugin

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

This merge request aims to solve #3803 #3802 and #3801. These issues pertain mainly some bugs in the http_response input plugin and making the metrics that it generates Prometheus friendly
Work in progress, do not merge

Http response fixes

---

plugins/inputs/system/NET_README.md
plugins/inputs/system/net.go
plugins/inputs/system/net_test.go

Added config flag to system net (inputs.net) to ignore collection of protocol stats.
Provides feature requested in #3879

added config flag to skip collection of network protocol metrics

---

plugins/inputs/exec/exec.go

If the command failed with a non-zero exit status there might be an error
message on stderr. Append the first line to the error message to ease the
search for its cause.
/cc @danielnelson

exec: Print first line of stderr in case of error (#3851)

---

plugins/outputs/wavefront/wavefront.go

Before this change, debugging telegraf with Wavefront is very difficult due to the high volume of debug log entries.

remove very noisy debug output

---

plugins/inputs/kapacitor/README.md
plugins/inputs/kapacitor/kapacitor.go

Add TLS support to kapacitor input

---

etc/telegraf.conf
plugins/inputs/http_listener/README.md
plugins/inputs/http_listener/http_listener.go
plugins/inputs/http_listener/http_listener_test.go

Does what it says on the tin. Needed it for a specific use case, and saw no reason for it to not be there, so here we are.

add HTTP basic auth support to the http_listener input plugin

---

Makefile
metric/metric.go
metric/uint_support.go
plugins/parsers/influx/escape.go
plugins/parsers/influx/handler.go
plugins/parsers/influx/machine.go
plugins/parsers/influx/machine.go.rl
plugins/parsers/influx/machine_test.go
plugins/parsers/influx/parser.go
plugins/parsers/influx/parser_test.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go

Didn't see an appropriate README to update. 
Pull adds uint64 support for InfluxDB line protocols (in and out), and to telegraf/metric.  telegraf metric uint64 support is gated behind a build flag until infludata/influxdb mainline uint64 is generally available to ensure behavior is consistent with how telegraf has behaved in the past.  
That will likely be a breaking change in the future unless the API for AddField and convertField are extended so the caller can specify whether or not uint64 storage and, by extension output, is desired.

uint64 support

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

Add filters for container state to docker input

---

CHANGELOG.md
plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go
plugins/inputs/mysql/v1/mysql.go

This attempts to smooth over migration with the metric type changes to the mysql input for existing users of the plugin and especially those with many Telegraf instances and supporting code.
By default, metrics will remain in the old format and must be opted into by setting `metric_version = 2`.  An in depth migration recommendation is included in the mysql/README.md.
@skord Would be great if you could review the code.
@oplehto I hope this provides a reasonable upgrade path, though it won't be fully painless, please let me know if this will work for you.
closes #3858

Add metric_version option to mysql input

---

plugins/outputs/influxdb/http.go

Fixing https://github.com/influxdata/telegraf/issues/3975, where the influxdb output plugin now longer formats valid write/query urls for https scheme.

Fixing https urls in Influxdb Output Plugin

---

Godeps

Update gonsmp, in particular to pull in a fix for the Cisco ASA 5515.
closes #3655

Update gosnmp rev

---

plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Fix conversion of unsigned ints in prometheus output

---

scripts/init.sh

This keeps the format of this file the same between systemd and
sysvinit.

Export all vars defined in /etc/default/telegraf

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongostat.go

Hello!
Here is new metric named oplog_timediff.
References:
https://www.mongodb.com/blog/post/replica-set-health-is-more-than-just-replication
https://github.com/DataDog/integrations-core/blob/master/mongo/datadog_checks/mongo/mongo.py#L972

Add repl_oplog_window_s metric to mongodb input

---

plugins/parsers/influx/machine.go
plugins/parsers/influx/machine.go.rl
plugins/parsers/influx/machine_test.go
plugins/serializers/influx/escape.go
plugins/serializers/influx/influx_test.go

Fix newline escaping in line protocol

---

internal/config/config.go
internal/config/testdata/subconfig/..4984_10_04_08_28_06.119/invalid-config.conf

When config dir is mounted from configmap, filepath.Walk() find the same
.conf file twice as 20-acme.conf is a link to
..data/20-acme.conf for example.
This patch skips all folder names starting with '..' which is pretty
uncommon and mainly used by Kubernetes mounts.

Prevent loading config twice in K8S

---

plugins/inputs/system/memory.go

Closes #3835 
Memory metrics were incorrectly assigned to Counter instead of Gauge metric types.

Update mem values to gauge

---

plugins/inputs/snmp/README.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

Adds an oid_strip_index_components option to the snmp input to allow for stripping variable trailing OID sub-indexes (e.g. CISCO-IETF-ISIS-MIB L2 circuits)

Snmp strip components

---

plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go

Fix graphite serialization of unsigned ints

---

plugins/inputs/system/SYSTEM_README.md
plugins/inputs/system/system.go

Report available fields if utmp is unreadable

---

Godeps
plugins/parsers/registry.go
plugins/parsers/syslog/parser.go

---
This PR introduces a parser plugin for syslog [RFC5424](https://tools.ietf.org/html/rfc5424)-compliant messages.
A syslog message is in the form.
`<priority>value timestamp hostname appname procid msgid structureddata message`
The [parser](https://github.com/influxdata/go-syslog) extracts info (also partially) from a syslog message organizing them in a struct containing:
- timestamp
- facility, severity (tags)
- hostname, appname (tags)
- msgid, message (fields)
- structured data id (fields)
- structured data parameters (fields)
This plugin does not provide at the moment any capability to distinguish structured data parameters that have to be stored as tags from others that have to be stored as fields.
This would be a neat feature to write advacend queries against the extracted data. …

RFC 5424 syslog parser

---

Godeps

Fixes #4037 
Instead of the latest commit I'm picking the gopsutils commit just after current one used in telegraf, to avoid adding unrelated changes

Update gopsutils to fix #4037

---

plugins/parsers/influx/parser_test.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go

Fix ints being capped at 32-bits on 32-bit archs

---

plugins/inputs/unbound/unbound.go

Unfortunately I dont see anything in the unbound change log to support this claim, but the code doesnt work anymore

Since unbound 1.7 the `-s` argument must come first

---

plugins/parsers/influx/machine.go
plugins/parsers/influx/machine.go.rl
plugins/parsers/influx/machine_test.go

Fix handling of floats with multiple leading zeroes

---

plugins/inputs/docker/README.md
plugins/inputs/docker/client.go
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/docker_testdata.go
testutil/accumulator.go

Add docker input server version

---

plugins/inputs/sysstat/sysstat.go

Added new config parameter for sysstat plugin, sadc_interval, to force
the gather interval of the sadc command.
This is useful when we have configured jitter in the agent, because
jitter breaks the measurement of the interval used in sadc.
Example:
- agent with interval=10, jitter=5
- sysstat is started in t=0 and runs sadc with interval=1
- next execution of sysstat is in t=14 (interval + some jitter)
- sysstat plugin set the value of "s.interval" to 14s
- sadc is run with interval=13 (s.interval - parseInterval)
- sysstat plugin is killed because is taking longer that collection
interval

New parameter to force the interval of gather for sysstat

---

plugins/inputs/jolokia2/examples/cassandra.conf

The modifications are important as after working with the old version, it's better to add the prefix of the metrics name.
Here an example with the output of the deprecated cassandra plugin:
```
cassandraThreadPools,cassandra_host=localhost,dc=dc1,env=prod,host=my_hostname.com,mname=MaxPoolSize,path=transport,rack=rack1,scope=Native-Transport-Requests MaxPoolSize_Value=256 1524670394000000000
```
Here the same output with the current version of the cassandra.conf of jolokia2:
```
cassandra_ThreadPools,dc=dc1,env=prod,host=my_hostname.com,jolokia_agent_url=http://localhost:8778/jolokia,name=MaxPoolSize,path=transport,rack=rack1,scope=Native-Transport-Requests Value=256 1524670394000000000
```
As you can see the value name `MaxPoolSize_Value` has been renamed to `Value` only
With the version …

[jolokia2] [cassandra] Metrics values should have same names than old cassandra plugin

---

plugins/inputs/win_perf_counters/win_perf_counters.go

Fix win_perf_counters to collect counters per instance

---

plugins/inputs/all/all.go
plugins/inputs/mcrouter/README.md
plugins/inputs/mcrouter/mcrouter.go
plugins/inputs/mcrouter/mcrouter_test.go

McRouter is a smart proxy for Memcached
https://github.com/facebook/mcrouter
Code is based on the memcached input plugin

Add input plugin for McRouter

---

plugins/outputs/datadog/datadog.go
plugins/outputs/datadog/datadog_test.go

Fix handling of uint64 in datadog output

---

scripts/build.py

Error in build WITHOUT --platform parameter (from macosx/darwin)
```
[INFO] check_prereqs: Checking for dependencies...
Traceback (most recent call last):
File "./scripts/build.py", line 922, in <module>
sys.exit(main(args))
File "./scripts/build.py", line 697, in main
logging.error("Invalid build platform: {}".format(target_platform))
NameError: global name 'target_platform' is not defined
```
After fix:
```
[INFO] check_prereqs: Checking for dependencies...
[ERROR] main: Invalid build platform: darwin
```

Fix platform not supported error

---

docs/DATA_FORMATS_OUTPUT.md
plugins/outputs/influxdb/udp_test.go
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go
plugins/serializers/json/json.go
plugins/serializers/json/json_test.go
plugins/serializers/registry.go

Add SerializeBatch method to the Serializer interface

---

plugins/processors/all/all.go
plugins/processors/topk/README.md
plugins/processors/topk/test_sets.go
plugins/processors/topk/topk.go
plugins/processors/topk/topk_test.go

The pluging uses:
- Selectors to pick the metrics that will be filtered
- A group by clause to group the metrics based on metric names and tags
- A list of fields
- An aggregator function to agreggate each field of the grouped metrics
- Once the aggregations for each group are calculated, the plugin orders the groups by each aggregation and returns all the metrics of each group in the top k spots
PR #3691 closed in favor of this one, as I mangled the branch through a rebase

TopK processor: Add topk processor plugin code

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongostat.go

Fixes: #3480
```
$ GOCACHE=off go test -v -tags=integration ./...
=== RUN   TestAddNonReplStats
--- PASS: TestAddNonReplStats (0.00s)
=== RUN   TestAddReplStats
--- PASS: TestAddReplStats (0.00s)
=== RUN   TestAddWiredTigerStats
--- PASS: TestAddWiredTigerStats (0.00s)
=== RUN   TestAddShardStats
--- PASS: TestAddShardStats (0.00s)
=== RUN   TestAddShardHostStats
--- PASS: TestAddShardHostStats (0.00s)
=== RUN   TestStateTag
--- PASS: TestStateTag (0.00s)
=== RUN   TestGetDefaultTags
--- PASS: TestGetDefaultTags (0.00s)
=== RUN   TestAddDefaultStats
--- PASS: TestAddDefaultStats (0.01s)
PASS
ok      github.com/influxdata/telegraf/plugins/inputs/mongodb   0.012s
```
```
$ ./telegraf --config ~/tele-conf --test
> mongodb,host=foo,hostname=127.0.0.1:27017 …
```

MongoDB: Add cursor Metrics

---

plugins/inputs/dns_query/README.md
plugins/inputs/dns_query/dns_query.go

Adds `result` tag and `result_code` field for results: success, timeout, error.  If the result is not success, the `query_time_ms` field will be omitted.
closes #2548

Don't report 0ms on timeout in dns_query

---

docker-compose.yml
plugins/outputs/cratedb/cratedb.go
plugins/outputs/cratedb/cratedb_test.go

Since 1.6, fields can be int64, uint64, float64, bool, string.
For uint64 values too large to store in CrateDB, we save as the maximum int64 value.
@felixge Can you review?
closes: #4110

Add uint support to cratedb output

---

plugins/inputs/nvidia_smi/nvidia_smi.go
plugins/inputs/nvidia_smi/nvidia_smi_test.go

I do have some concern that the nvidia-smi tool may localize this message, but I don't want to get overly aggressive is skipping unknown data.
closes: #4120
cc @jackzampolin

Skip fields that report "not supported" in nvidia-smi

---

plugins/inputs/net_response/README.md
plugins/inputs/net_response/net_response.go
plugins/inputs/net_response/net_response_test.go

Deprecating result_type as a field value in favor of result_text as a tag value.
Adding a field value called result_code which is an int in the fields.
Updating tests to reflect changes.
Adding new tests to test other sections of the code.
Updating the README.me file to reflect the changes.

Update net response

---

plugins/inputs/jolokia2/jolokia_agent.go
plugins/inputs/jolokia2/jolokia_proxy.go

Using internal.Duration is required in order to specify the timeout as a duration string.
```
[[inputs.jolokia2_agent]]
name_override = "howdy"
urls = ["http://debian-stretch-tomcat:8080/jolokia"]
response_timeout = "5s"
[[inputs.jolokia2_agent.metric]]
name  = "java_runtime"
mbean = "java.lang:type=Runtime"
paths = ["Uptime"]
```
```
E! Error parsing /home/dbn/.telegraf/telegraf.d/input.jolokia2.conf, line 12: jolokia2.JolokiaAgent.ResponseTimeout: `string' type is not assignable to `time.Duration' type
```

Use internal.Duration for jolokia timeouts

---

metric.go
metric/metric.go
plugins/parsers/dropwizard/parser.go
plugins/parsers/dropwizard/parser_test.go
plugins/parsers/influx/machine.go
plugins/parsers/influx/machine.go.rl
plugins/parsers/influx/machine_test.go
plugins/parsers/influx/parser.go
plugins/parsers/influx/parser_test.go
plugins/parsers/registry.go

If the dropwizard parser cannot convert the metric name into a valid line protocol series then we will accept the name as is.
This adds a way to parse only the `<measurement>,<tagset>` portion of line protocol and uses it to create new metrics instead of serializing the entire dropwizard metric to line protocol.  Anything that would require escaping to be valid cannot be converted, because escaping it fully would prevent tags from being extracted.

Fix dropwizard parsing error for metrics that need escaped

---

plugins/inputs/aerospike/README.md
plugins/inputs/aerospike/aerospike.go

Add support for TLS and username/password auth to aerospike input

---

plugins/inputs/logparser/README.md
plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go

Previously it was impossible to parse syslog timestamps without the date being reported as year 0, due to the year not being specified.
This pull request adds the special timestamp format: `ts-syslog` that will set the year after parsing to the current year.  `%{SYSLOGTIMESTAMP:timestamp:ts-syslog}`
closes  #3379

Add special syslog timestamp parser that uses current year

---

cmd/telegraf/telegraf.go
internal/config/config.go

Print the enabled aggregator and processor plugins on startup

---

etc/telegraf.conf
plugins/outputs/amqp/README.md
plugins/outputs/amqp/amqp.go

#2797
* Add routing_key config option
* routing_tag, if defined and exists, can still override routing_key in the case where the latter is being used as a default value

Add ability to specify routing_key in amqp output

---

etc/telegraf.conf
plugins/inputs/amqp_consumer/README.md
plugins/inputs/amqp_consumer/amqp_consumer.go

#3785 
* New configuration option exchange_passive, defaults to false

 AMQP Consumer - Allow turning on exchange passive mode

---

agent/agent.go
internal/models/running_aggregator.go

The order of loading service plugins caused metrics not being aggregated during startup. This was seen when using the logparser plugin and having it start from the beginning of the file. I run into it while testing: https://github.com/influxdata/telegraf/pull/3523 . 
Also prints a debug message when skipping metrics.

Don't skip metrics during startup in aggregate phase

---

Godeps
plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go

SSL/TLS support is added to make Redis input working with services like:
- AWS Elasticache with encryption in-transit feature turned on (https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)
- Redis with stunnel (https://redislabs.com/redis-enterprise-documentation/administering/security/client-connections/)
- Redis with native SSL support (antirez/redis#4855).

Add SSL/TLS support to Redis input

---

etc/telegraf.conf
etc/telegraf_windows.conf
plugins/inputs/system/DISK_README.md
plugins/inputs/system/disk.go

Add more FS type to default ignore list.
* overlay: Used by Docker for overlay2 (and probably overlay). This filesystem is backed by another local directory, disk usage/free/total will be the same as backing filesystem.
* aufs: Used by Docker for aufs. Like overlay this is backed by a local filesystem
* squashfs: Used by snap. This is a read-only filesystem backed by a local file.
For all those filesystem, since the backing store is a local directory/file, the space used will be seen in the metrics of this filesystem.

Ignore more boring filesystems from disk plugin

---

Godeps
internal/tls/config.go
plugins/inputs/openldap/README.md
plugins/inputs/openldap/openldap.go
plugins/inputs/openldap/openldap_test.go

Fix TLS and SSL config option parsing

---

plugins/outputs/wavefront/wavefront.go

Wavefront Proxy will block metrics that have empty tags.  This PR will remove the tag from the output instead. Some output plugins now emit empty tags (prometheus, mysql).

Wavefront output: remove empty tags 

---

plugins/inputs/solr/README.md
plugins/inputs/solr/solr.go
plugins/inputs/solr/solr_test.go
plugins/inputs/solr/testdata7_test.go

Simple fix to maintain compatibility with solr3.5-6.x while adding compat. for solr 7.x  cache hits (#3665)

Fix solr plugin for Solr 7 (Fixes #3665)

---

cmd/telegraf/telegraf.go

Treat sigterm as a clean shutdown signal

---

plugins/inputs/burrow/README.md
plugins/inputs/burrow/burrow.go
plugins/inputs/burrow/burrow_test.go
plugins/inputs/burrow/testdata/v3_kafka_clustername1_consumer_group1_lag.json

Update for Burrow Input plugin. Added "owner" tag, which allows identify which consumer is owns partition. Primary goal is to be able to track Kafka RangeAssignor job.

Burrow: add owner tag on partitions

---

plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go

Allow for Tags on non base level JSON format

---

.circleci/config.yml
README.md

The CircleCI docker images we are using have been removed for this version of Go, and the 1.8 release is no longer supported upstream.

Drop CI support for Go 1.8

---

plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/docker_testdata.go

Currently the docker input plugin does not provide the running status of the docker . It does provide health status of the docker but that is only retrieved if the docker application supports it . This enhancement extends the plugin to give out the running status of the docker which is taken from the Docker Container Inspect API.

Telegraph Docker Input Plugin : per docker running status support

---

plugins/inputs/logparser/README.md
plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go

Add support for comma in timestamp format

---

CHANGELOG.md
plugins/inputs/postfix/postfix.go
plugins/inputs/postfix/postfix_test.go

Adjusts the postfix input plugin to recursively walk the queue directories instead of expecting a certain depth/structure.
Fixes #4135

fix postfix input handling multi-level queues

---

plugins/inputs/tail/tail.go

- [v] Signed [CLA](https://influxdata.com/community/cla/).
- [v] Associated README.md updated.
- [v] Has appropriate unit tests.
Added filename tag for tail input plugin.
This information is needed when the case telegraf captures log from multiple files in the directory structure and there's a need to identify source.

Added filename tag to tail input plugin.

---

plugins/inputs/logparser/grok/grok.go
plugins/inputs/logparser/grok/grok_test.go

Fix syslog timestamp parsing with single digit day of month

---

plugins/inputs/win_perf_counters/README.md
plugins/inputs/win_perf_counters/kernel32.go
plugins/inputs/win_perf_counters/pdh.go
plugins/inputs/win_perf_counters/performance_query.go
plugins/inputs/win_perf_counters/win_perf_counters.go
plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
plugins/inputs/win_perf_counters/win_perf_counters_test.go

Trying to fix #4250: added possibility to use timestamp from performance counters

Use counter time in win perf counters

---

plugins/aggregators/basicstats/basicstats.go
plugins/aggregators/basicstats/basicstats_test.go
plugins/aggregators/minmax/minmax.go
plugins/aggregators/minmax/minmax_test.go

These aggregators were not working with other numbers type not being
float64 or int64.
Telegraf uses externals libs that could use other types.

Fix minmax and basicstats aggregators to use all number types

---

plugins/inputs/fibaro/README.md
plugins/inputs/fibaro/fibaro.go
plugins/inputs/fibaro/fibaro_test.go

This PR implement features requested here:
- https://github.com/influxdata/telegraf/issues/4273
- https://github.com/influxdata/telegraf/issues/4274

add consumption, add device id as tag, modify documentation and tests

---

etc/telegraf.conf
plugins/outputs/opentsdb/opentsdb.go
plugins/outputs/opentsdb/opentsdb_http.go
plugins/outputs/opentsdb/opentsdb_test.go

This PR updates the OpenTSDB to allow for the path to be configured when using the HTTP client. Currently there is no way for telegraf to send data to OpenTSDB servers behind a reverse proxy with non default routes.

Add http path configuration for OpenTSDB plugin

---

plugins/inputs/system/DISKIO_README.md

diskio utilization and queue length should be positive, not negative.

Fix diskio utilization and queue length issue.

---

plugins/processors/all/all.go
plugins/processors/enum/README.md
plugins/processors/enum/enum.go
plugins/processors/enum/enum_test.go

This processor allows substitution of field values of string or bool type with
numeric values. It can be used, e.g. to map status codes such as "red", "amber"
and "green" to values such as 0, 1, 2. Multiple fields can be configured, each
with its own mapping table.

Add Enum Processor

---

plugins/inputs/procstat/process.go
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go

This adds the username of the user running a process as a tag to the `procstat` plugin.
Resolves #4378

Add process' user as a tag

---

plugins/inputs/zookeeper/dev/docker-compose.yml
plugins/inputs/zookeeper/dev/telegraf.conf
plugins/inputs/zookeeper/zookeeper.go

Use 'localhost' as default 'server' tag

---

plugins/processors/regex/regex.go
plugins/processors/regex/regex_test.go

Fixed behavior when pattern doesn't match:
a) if no `result_key` specified => plugin doesn't alter existing tag/field
b) if `result_key` specified => plugin doesn't create tag/field with `result_key` name (resolves #4374)
```toml
[agent]
interval="1s"
flush_interval="1s"
[[inputs.exec]]
timeout = "1s"
data_format = "influx"
commands = [
"echo 'deal,computer_name=hosta message=\"stuff\" 1530654676316265790'",
"echo 'deal,computer_name=hostb message=\"stuff\" 1530654676316265790'",
]
[[processors.regex]]
[[processors.regex.tags]]
key = "computer_name"
pattern = "^(.*?)a$"
replacement = "${1}"
result_key = "server_name"
[[processors.regex.tags]]
key = "computer_name"
pattern = "^(.*?)b$"
replacement = "${1}"
result_key = "server_name"
[[outputs.file]]
files = ["stdout"]
```
``` …
```

Regex: don't emit empty tags and fields when pattern doesn't match and result_key specified

---

docs/DATA_FORMATS_INPUT.md
internal/config/config.go
plugins/parsers/collectd/parser.go
plugins/parsers/collectd/parser_test.go
plugins/parsers/registry.go

add parse_multivalue config to collectd parser

---

agent/agent.go

It is possible for `(RunningOutput).AddMetric` to be called concurrently when
using aggregator plugins, which can cause a deadlock in buffer.go:
```
goroutine 146 [chan receive, 3202 minutes]:
github.com/influxdata/telegraf/internal/buffer.(*Buffer).Add(0xc42008d4f0, 0xc4203c2e90, 0x1, 0x1)
src/github.com/influxdata/telegraf/internal/buffer/buffer.go:50 +0x115
github.com/influxdata/telegraf/internal/models.(*RunningOutput).AddMetric(0xc4201ac500, 0x16702a0, 0xc420a6ac40)
src/github.com/influxdata/telegraf/internal/models/running_output.go:116 +0xb3
github.com/influxdata/telegraf/agent.(*Agent).flusher.func1(0xc420bf7cb0, 0xc4200b4300, 0xc4201f29c0, 0xc4201820c8)
src/github.com/influxdata/telegraf/agent/agent.go:284 +0x28d
created by github.com/influxdata/telegraf/agent.(*Agent).flusher …
```

Fix potential deadlock by not calling AddMetric concurrently

---

plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go

The team running the Kafka I was using required that I set the client id for reads and writes.  For reference, the default client id is "sarama"
I ran "make lint" and "make test", the latter showed failures for unrelated files. (outputs/socket_writer, outputs/influxdb, inputs/syslog, inputs/socket_listener, inputs/ping, inputs/http_response, inputs/fluentd)

Expose kafka client id

---

plugins/outputs/http/http.go

Telegraf will panic if the `http` output's `url` was an incorrect/unparseable [format](https://golang.org/pkg/net/url/#URL). This returns the error, allowing the user to know and correct the url.
Resolves #4389

Return error if NewRequest fails

---

plugins/inputs/syslog/syslog.go

This change reads from a syslog client in a separate step from the log parsing. This allows fewer errors in telegraf's logs about exceeding read timeouts. This should also limit the amount of reconnecting syslog clients must do when streaming logs to telegraf.
Previously, the syslog plugin would immediately start reading from a connection and if data was not immediately provided (or a connection was made and closed), `found EOF, expecting a MSGLEN` would be printed to telgraf's log.
By reading the data on the connection in a separate step, we are able to handle connection issues separately from parsing issues, thus resulting in less of them. This will also allow for syslog client connections to stay alive longer.
Resolves #4335

Improve syslog connection handling

---

plugins/outputs/cloudwatch/cloudwatch.go

Improve cloudwatch output performance (#4317)

---

Gopkg.lock
Gopkg.toml

This is currently the most recent version without the memory leak issue.

Downgrade max aerospike client version to 1.27.0

---

plugins/inputs/docker/dev/telegraf.conf
plugins/inputs/exec/dev/telegraf.conf
plugins/inputs/procstat/dev/telegraf.conf

Add at least a `dev/telegraf.conf` file for input plugins:
Refers to #4367

Add dev telegraf.conf for input pluigns

---

plugins/inputs/snmp/snmp.go

As used in Cisco VPN's, eg: http://oidref.com/1.3.6.1.4.1.9.9.171.1.3.2.1.4
The relevant fields are of course garbled without this.
- [ X ] Signed [CLA](https://influxdata.com/community/cla/).
- [ U ] Associated README.md updated.
- [ U ] Has appropriate unit tests.

Add IPSIpAddress syntax to ipaddr conversion in snmp plugin

---

README.md
plugins/inputs/all/all.go
plugins/inputs/filecount/README.md
plugins/inputs/filecount/filecount.go
plugins/inputs/filecount/filecount_test.go
plugins/inputs/filecount/testdata/qux

This pull request introduces a new input plugin named `filecount`. The `filecount` plugin counts files in a directory that match certain criteria (e.g. "name", "size", "mtime" etc.).
While `filecount` is modeled after the [collectd filecount plugin](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_filecount), the two plugins do not share any code.

Add filecount input plugin

---

internal/config/aws/credentials.go
plugins/inputs/cloudwatch/README.md
plugins/inputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/kinesis/kinesis.go

Add support for configuring an AWS endpoint_url

---

plugins/outputs/kafka/kafka.go

Send all messages before waiting for results in kafka output

---

plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go

Add support for lz4 compression to kafka output

---

etc/telegraf.conf
plugins/inputs/ipmi_sensor/README.md
plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/ipmi_sensor/ipmi_test.go

Ipmi.v2.schema

---

plugins/inputs/syslog/README.md
plugins/inputs/syslog/rfc5426_test.go
plugins/inputs/syslog/syslog.go

Preserve leading whitespace commonly used for indention when logging stack traces.
Also fixed the documentation for the default read timeout.

Keep leading whitespace for messages in syslog input
