influxdata/telegraf

plugins/inputs/interrupts/interrupts.go
plugins/inputs/interrupts/interrupts_test.go

Skip bad entries on interrupt input

---

internal/models/running_output.go

Resolves #4501
Using telegraf 1.7.2 with the following config to export kube-scheduler metrics:
```
[[outputs.prometheus_client]]
listen = "0.0.0.0:9273"
expiration_interval = "60s"
[outputs.prometheus_client.tagpass]
_OUTPUT = ["prometheus"]
[[inputs.prometheus]]
urls = ["http://127.0.0.1:10251/metrics"]
[inputs.prometheus.tags]
_OUTPUT = "prometheus"
```
Histograms in http://127.0.0.1:9273/metrics look like:
```
...
scheduler_scheduling_algorithm_latency_microseconds_16000{_OUTPUT="prometheus",host="xxx",url="http://127.0.0.1:10251/metrics"} 0
scheduler_scheduling_algorithm_latency_microseconds_1_024e_06{_OUTPUT="prometheus",host="xxx",url="http://127.0.0.1:10251/metrics"} 0
...
```
With the tagpass filter removed from `outputs.prometheus_client`, the output preserved the metric type: …

Preserve metric type when using filters in output plugins

---

plugins/outputs/cloudwatch/README.md
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

Fix #4318 
Add `enable_statistic_values` flag. If true, this plugin would try to parse required statistic fields and send StatisticSet to Cloudwatch.

Support StatisticValues in cloudwatch output plugin (#4318)

---

etc/telegraf.conf
plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go

Sometimes you want to protect the exported /metrics path from the prometheus_client.
It was already possible to secure it with a password.
This patch adds the option to allow only defined CIDR ranges to access the /metrics.

Add ip restriction for the prometheus_client output

---

README.md
docker-compose.yml
plugins/inputs/all/all.go
plugins/inputs/pgbouncer/README.md
plugins/inputs/pgbouncer/pgbouncer.go
plugins/inputs/pgbouncer/pgbouncer_test.go
plugins/inputs/postgresql/postgresql.go
plugins/inputs/postgresql/postgresql_test.go
plugins/inputs/postgresql/service.go
plugins/inputs/postgresql_extensible/postgresql_extensible.go
plugins/inputs/postgresql_extensible/postgresql_extensible_test.go

This requires an update on jackc/pgx to support a specific feature (v3.1.0 was chosen)
This PR will fix #3253 and normalize the pgbouncer component properly
You will find a grafana output example below

Add pgbouncer input plugin

---

plugins/inputs/zfs/zfs_freebsd.go
plugins/inputs/zfs/zfs_freebsd_test.go

Use explicit zpool properties to fix parse error on FreeBSD 11.2

---

plugins/outputs/influxdb/influxdb.go

closes #3794 
Here is the message before (which is now even worse than in the original issue):
```
2018-08-03T00:45:30Z E! Failed to connect to output influxdb, retrying in 15s, error was 'error parsing url [<nil>]: parse "http://localhost:8086": first path segment in URL cannot contain colon'
```
Here is the message now:
```
2018-08-03T00:44:46Z E! Failed to connect to output influxdb, retrying in 15s, error was 'error parsing url ["\"http://localhost:8086\""]: parse "http://localhost:8086": first path segment in URL cannot contain colon'
```

Fix error message if URL is unparseable in influxdb output

---

cmd/telegraf/telegraf.go

Prevents setting the branch version to the last major release, and as a bonus we no longer need to set this variable on release:
```
$ go build -ldflags "-X main.version=1.8.0 -X main.commit=fa08656a -X main.branch=default-version" ./cmd/telegraf
$ ./telegraf version
Telegraf 1.8.0 (git: default-version fa08656a)
```
```
$ go build -ldflags " -X main.commit=fa08656a -X main.branch=default-version" ./cmd/telegraf
$ ./telegraf version
Telegraf unknown (git: default-version fa08656a)
```
```
$ go build ./cmd/telegraf
$ ./telegraf version
Telegraf unknown
```
closes #4516

Set version to unknown if not set

---

README.md
plugins/inputs/activemq/README.md
plugins/inputs/activemq/activemq.go
plugins/inputs/activemq/activemq_test.go
plugins/inputs/all/all.go

Add ActiveMQ input plugin

---

plugins/outputs/kafka/kafka.go

Add Message Max bytes configuration

---

plugins/inputs/powerdns/powerdns_test.go

As it was noted in https://github.com/influxdata/telegraf/pull/4545 not to use crypto/rand in a test. Lets fix the source where I got it :)
Also fix a small function naming mismatch.

Minor fixes in powerdns_test

---

plugins/outputs/influxdb/udp.go
plugins/outputs/influxdb/udp_test.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go
plugins/serializers/influx/reader.go

Additionally display the series, measurement_name + tagset, if a serialization error occurs.

Continue with batch if a metric is unserializable in InfluxDB UDP output

---

internal/buffer/buffer.go
internal/buffer/buffer_test.go

- [x ] Has appropriate unit tests.
Benchmark results for internal/buffer
```
Before:
$ go test -run='^$' -bench=.   -benchmem -race
goos: darwin
goarch: amd64
pkg: github.com/influxdata/telegraf/internal/buffer
BenchmarkBufferBatch5Add-8                   	  200000	      5454 ns/op	       2 B/op	       0 allocs/op
BenchmarkBufferBigInfrequentBatchCatchup-8   	 1000000	      1065 ns/op	       1 B/op	       0 allocs/op
BenchmarkBufferOftenBatch-8                  	 1000000	      1892 ns/op	      16 B/op	       0 allocs/op
BenchmarkBufferAlmostBatch-8                 	 1000000	      1543 ns/op	      14 B/op	       0 allocs/op
BenchmarkBufferSlowBatch-8                   	 1000000	      1381 ns/op	       1 B/op	       0 allocs/op …
```

Performance tweaks for internal/buffer

---

plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go
plugins/outputs/kafka/kafka_test.go

closes #4573 
- [] Has appropriate unit tests.

Add support for static and random routing keys in kafka output

---

plugins/inputs/burrow/README.md
plugins/inputs/burrow/burrow.go
plugins/inputs/burrow/burrow_test.go

The value returned in `burrow_group.offset` field was the highest offset of any partition, rather than the sum of all partition offsets.  Note that the partition offset is still available from the `burrow_partition` metric if needed, this PR just fixes the `burrow_group` calculation to provide a better indication of total offset for the group.
- [*] Signed [CLA](https://influxdata.com/community/cla/).
- [*] Associated README.md updated.
- [*] Has appropriate unit tests.

Fix burrow_group.offset calculation for Burrow plugin

---

plugins/inputs/all/all.go
plugins/inputs/kibana/README.md
plugins/inputs/kibana/kibana.go
plugins/inputs/kibana/kibana_test.go
plugins/inputs/kibana/testdata_test.go

Implements #4576
I tried to keep it simple and only collecting the metrics related to Kibana itself.

Add Kibana input plugin 

---

plugins/inputs/statsd/README.md
plugins/inputs/statsd/statsd.go

Add read_buffer_size option to statsd input

---

plugins/inputs/syslog/syslog.go

On UDP sockets we shouldn't use the timeout due to the connection-less nature of the socket.
related: #4593

Remove timeout deadline for udp syslog input.

---

plugins/outputs/http/http.go
plugins/outputs/http/http_test.go

Fix sending of basic auth credentials in http output

---

plugins/parsers/grok/parser.go
plugins/parsers/grok/parser_test.go

Logparser divide by zero

---

plugins/outputs/application_insights/README.md
plugins/outputs/application_insights/application_insights.go

Found small miss spelling from application insights example config.
- [  ] Has appropriate unit tests.
/cc @karolz-ms

Corrected application insights example config

---

plugins/inputs/amqp_consumer/README.md
plugins/inputs/amqp_consumer/amqp_consumer.go

- [+] Signed [CLA](https://influxdata.com/community/cla/).
- [+] Associated README.md updated.
- [-] Has appropriate unit tests.
Added a Queue Durability property to amqp_consumer input plugin.
The amqp_consumer input plugin always creates at RabbitMQ server a queue with durable 'true',
that meas RabbitMQ is saving messages to disk in the queue util they are consumed. Sometimes it is needed to avoid impact of disk I/O and set the queue 'not durable'. It is easy to do in plugin configuration file.
Please review the code if it can be merged.

add queue_durability property to amqp_consumer input

---

docs/DATA_FORMATS_INPUT.md
plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go

closes: #4607
..., corresponding test and doc updated.
If parsing a Unix epoch timestamp, e.g. 1536092344000, "json_time_format" config must be set to "Unix"; corresponding JSON value must be in milliseconds and unquoted.

Added Unix epoch timestamp support for JSON parser

---

plugins/inputs/all/all.go
plugins/inputs/system/mock_PS.go
plugins/inputs/system/ps.go
plugins/inputs/temp/README.md
plugins/inputs/temp/temp.go
plugins/inputs/temp/temp_test.go

This `temp` inputs plugin implement #4400 . Use `gopsutil`  to collect virtual machine temperature.

Add temp inputs plugin for collect temperature

---

plugins/inputs/haproxy/haproxy.go

Resolves #4509 
Formerly users who enabled auth on their haproxy servers were required to set the username/password in the url. Now it is added separately. Older config styles (`https://user:pass@host/haproxy?stats`) won't break and won't print login info in logs on bad connections.

Add options for basic auth to haproxy input

---

plugins/inputs/redis/redis.go

Resolves #4663 
Resolves #2786

Add means to specify server password for redis input

---

docs/DATA_FORMATS_OUTPUT.md
internal/config/config.go
plugins/serializers/registry.go
plugins/serializers/splunkmetric/README.md
plugins/serializers/splunkmetric/splunkmetric.go
plugins/serializers/splunkmetric/splunkmetric_test.go

This serializer properly formats the metrics data according to the Splunk metrics JSON specification, it can be used with any output that supports serializers, including file or HTTP. I decided that just formatting the data according to the Splunk spec was a better investment than managing the whole output pipeline. Now you can use telegraf without requiring a HEC (by using a file output), or you can use the well tested and maintained HTTP output and just set the extra headers required by the HEC.
Please see the docs in README.md

Splunk Metrics serializer

---

plugins/inputs/cloudwatch/cloudwatch.go
plugins/inputs/cloudwatch/cloudwatch_test.go

Fixes #4643 
For consideration, please review

Align metrics windows to gather interval for cloudwatch input

---

plugins/processors/enum/README.md
plugins/processors/enum/enum.go
plugins/processors/enum/enum_test.go
plugins/processors/rename/README.md
plugins/processors/rename/rename.go
plugins/processors/rename/rename_test.go

Based on #4616, this pull request switches the enum and rename to use the operation style subtables.
The primary reason for this is free up the `field`/`fields` options and make the various processors configs a bit more uniform.  There is no change in functionality.
cc @goldibex @KarstenSchnitter

Use operation subtables in enum and rename processors

---

plugins/inputs/win_services/README.md
plugins/inputs/win_services/win_services.go
plugins/inputs/win_services/win_services_integration_test.go

This is a mitigation for #4522, reduce the log level to debug when a service cannot be opened due to permissions issues.  This allows Telegraf to be ran with reduce privileges without spamming the log.

Log access denied opening a service at debug level

---

Gopkg.lock
Gopkg.toml
plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go

closes #4222 
closes #4597
- Altered database IO stats to include stats on a per-file basis
- Added a few new perf counters including `Background Writer pages/sec` which tracks indirect checkpoints
- Refactored some queries to be compatible with Azure Managed Instances
- Changed to the `denisenkom` SQL package, prior to the change this plugin would not work properly with managed instances
- Some perf counters now grab data per database instead of just for the "_Total" counter instance
- Moved some newer wait types into a proper category
- Added a few new wait types to the list of types to ignore
- Now filtering for wait types that have accumulated some …

Updates to SQL Server Plugin, better Azure Managed Instance support + more

---

plugins/inputs/vsphere/client.go

The plugin was calling an unsupported View.Destroy method which caused errors to be logged to the vCenter log. Removed the call, as any open views would be destroyed by the subsequent call to Logout anyway.

Fixed minor bug that caused error messages in vCenter log

---

etc/telegraf.conf
plugins/inputs/iptables/README.md
plugins/inputs/iptables/iptables.go

Allow alternate binaries for "iptables" input plugin.

---

plugins/inputs/ceph/ceph.go
plugins/inputs/ceph/ceph_test.go

With a new found mastery of Go it was time to revisit this plugin and
make the code more idiomatic.  The main thrust is to unmarshal directly
into data structures rather than using type assertions which makes the
code far more readable.  I've also added additional protections in the
form of extended testing.
- [/] Signed [CLA](https://influxdata.com/community/cla/).
- [/] Associated README.md updated.
- [/] Has appropriate unit tests.

Cleanup Ceph Input Plugin

---

plugins/inputs/docker/README.md

This updates the docker input plugin readme with a section about setting permissions for telegraf to access the docker daemon socket. This should address some of the confusion about why the docker input plugin does not work out of the box ([as seen here](https://github.com/influxdata/telegraf/issues/1074#issuecomment-213040280)).
There should probably be a note about security considerations with the current method. That could be a link to [this page](https://docs.docker.com/install/linux/linux-postinstall/#use-a-different-storage-engine) or [this page](https://docs.docker.com/engine/security/https/) on the Docker docs.
A better solution would be showing a way to give telegraf read-only permissions to the socket. Any suggestions on the "right" way to do that would be appreciated.

Add readme note about docker socket permissions

---

plugins/inputs/openldap/README.md

I think it's relevant to specify it's the OpenLDAP slapd _monitoring_ backend; I didn't hover over or click on the link and thought I needed a special telegraf monitoring backend.

Clarify monitoring backend provenance

---

plugins/inputs/sqlserver/sqlserver.go

Physical machine is 16 characters long rather than 15 characters.  Changed definition of @sys_info table. Also, worth noting for future a Virtual Box VM in Linux shows up as a Physical Machine.

String or Binary data will be truncated

---

plugins/inputs/temp/README.md
plugins/inputs/temp/temp.go

This plugin notably does not yet support FreeBSD or Darwin.  Mention the current platform support and provide a more specific error message if a "not implemented error" is returned from gopsutil.

Clarify platform support for temp input

---

plugins/aggregators/basicstats/basicstats.go

Use FieldList in basicstats to improve performance

---

plugins/inputs/x509_cert/x509_cert.go

x509_cert plugin was creating TLS connection without specifying a
server name for handshake. If there are multiple certificates on the
same host, the first one is received, resulting insecure host warning.
ServerName in tls.Config turns Server Name Indication (SNI) on for the
handshake, which allows virtual hosts on the same server.

Add hostname to TLS config for SNI support

---

plugins/inputs/vsphere/endpoint.go

This is a fix for #4764 
If a network error is encountered while querying for metric metadata, it is possible to get a panic due to a typo in endpoint.go (Unlock instead of Lock). 
https://github.com/influxdata/telegraf/blob/af0ef55c0281af67fe2db52d8c700fa8f636010e/plugins/inputs/vsphere/endpoint.go#L660-666

Fixed #4764 (Panic when error during call to GetAvailableMetrics)

---

plugins/inputs/vsphere/endpoint.go

- [ X ] Signed [CLA](https://influxdata.com/community/cla/).
- [ X ] Associated README.md updated.
- [ X ] Has appropriate unit tests.
Resolved #4768: Added UUID to VMs. 
BIOS UUIDs are needed to correlate metrics from inside the VM to metrics gathered from vSphere. They were originally not included and users raised this as an issue. This PR addresses that issue and adds code to emit BIOS UUIDs when available.

Resolved #4768: Added UUID to VMs

---

plugins/inputs/http_listener/http_listener.go

Unify http_listener error response with influxdb

---

plugins/inputs/vsphere/client.go
plugins/inputs/vsphere/endpoint.go

closes #4783 
When collecting non-realtime metrics, there's a risk of getting null metrics or incorrect metrics if the clock on the collector node is ahead of vCenter by just a very modest amount. 
Fixed it by getting "current time" from the vCenter server instead of the local clock.

Fixed issue 4783 (Non-realtime samples missing)

---

internal/config/config.go
plugins/inputs/logparser/logparser.go
plugins/parsers/registry.go

Fix case of timezone/grok_timezone options.

---

plugins/inputs/procstat/README.md
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/win_service_notwindows.go
plugins/inputs/procstat/win_service_windows.go

This PR implement #4209. Add `win_service` option to lookup the specified service process pid.

Procstat plugin add win_service option to lookup the specified service process pid

---

plugins/inputs/filecount/filecount.go
plugins/inputs/filecount/filecount_test.go

Per-directory file counts in the Filecount plugin

---

plugins/outputs/datadog/datadog.go
plugins/outputs/datadog/datadog_test.go

- [Y ] Signed [CLA](https://influxdata.com/community/cla/).
- [ NA] Associated README.md updated.
- [ NA] Has appropriate unit tests.
@danielnelson This PR addresses the feedback in #4699.  I replaced the use of `Metric.Fields` with `Metric.FieldList` and reduced how often `Metric.Tags` is called (it didn't look like using `TagList` made sense)
Since the changes were internal, I left the existing tests as is.

#4699 Improve how the datadog plugin uses Metric.Fields and Metric.Tags

---

internal/internal.go
internal/internal_test.go
plugins/outputs/http/README.md
plugins/outputs/http/http.go
plugins/outputs/http/http_test.go
plugins/outputs/influxdb/http.go
plugins/outputs/influxdb_v2/http.go

Implement HTTP Output Compression

---

plugins/inputs/net/NET_README.md

The README for the 'net' plugin had a link formatted as `(text)[url]`, but the correct markdown syntax is `[text](url)`.

Fix formatting in net plugin docs

---

cmd/telegraf/telegraf.go
internal/internal.go
internal/internal_test.go

- [ Y] Signed [CLA](https://influxdata.com/community/cla/).
- [ NA] Associated README.md updated.
- [ Y] Has appropriate unit tests.
@danielnelson This PR exposes the agent version in the _internal_ module per our conversation in #3911 
I decided to separate this in to two PRs, one to expose the version and then one to use it, in case there is back and forth on how the version is initially exposed.

Issue #3911: Expose telegraf agent version in internal module

---

plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/http_internal_test.go

Updating write url to match changes made in influxdata/platform commit [1a2f606](https://github.com/influxdata/platform/commit/1a2f606533672fa94be5ade1b8a22f862c2fdf52) (Convert everything to /api/v2)

Update write path to match updated v2 API

---

Dockerfile
Dockerfile.alpine
docker/entrypoint.sh

The images in influxdata-docker are meant to be built by downloading
official releases. Sometimes, it is useful to build directly from source
when you need an unofficial release. These images are meant to be used
then using multi-stage builds so that it can build from source and then
copy the results to images that match the official counterpart.

Add a Dockerfile that matches influxdata-docker to build images from source

---

plugins/inputs/vsphere/client.go
plugins/inputs/vsphere/endpoint.go
plugins/inputs/vsphere/vsphere_test.go

Fixed issue #4830 (SOAP timeout not honored). Added timeouts to contexts passed down to govmomi.

Implemented timeouts

---

plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go

It appears that the `/container/:id/stats` does not contain a name field on older docker version, seen in docker engine 1.12.6.

Use container name from list if no name in container stats

---

plugins/inputs/aerospike/aerospike.go
plugins/inputs/aerospike/aerospike_test.go

Add support for uint fields in aerospike input

---

plugins/inputs/filecount/filecount.go

Prevent panic if fileinfo is nil

---

internal/globpath/globpath.go
internal/globpath/globpath_test.go

When you have a super-meta in your expression (`**`), globpath was trying every files descendant of a root directory which was defined as « truncate path at the last / before the first star ». In cases such as `/path/**` or `/some/where/*/**`, it was OK.
But for path like `/some/*/path/*with/stars*/and/elements**` it was not optimal : it recursed through all directories under '/some', while it's only necessary to recurse through directories under `Glob("/some/*/path/*with/stars*/and/elements*")`.
This new version of globpath defines 'roots' (files and directories) as the filepath.Glob (« truncate between the 2 stars of the first `**` occurence »), and then calls filepath.Walk from these roots.
Simple tests (using 'time' on unix), where telegraf contains telegraf source code, and calling …

Optimization for globpath (root elements for recursion)

---

plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go

Reworks the connection lifetime for the mqtt_consumer plugin.  For now I have this marked for 1.9.0 but if we can get some help testing we can consider it for 1.8.x.
closes #4594 
closes #4580
closes #4731
Based on #4814

Rework mqtt_consumer connect/reconnect

---

plugins/inputs/logparser/logparser.go

Don't pass empty measurement name to AddFields

---

plugins/inputs/mongodb/mongodb_server.go

Lower authorization errors to debug level in mongodb input

---

plugins/inputs/ping/README.md
plugins/inputs/ping/ping.go

Resolves #4772 
Since the original issue was added in 1.7.4 (PR 4550), does it need backported to the 1.7 line too?

On host not available, set result_code accordingly

---

plugins/inputs/x509_cert/README.md
plugins/inputs/x509_cert/dev/telegraf.conf
plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

- When no tls params are in config, tlsCfg will be nil
- fix setting hostname in tlsCfg it will contain the port number and never correctly match server certs
- Add a test that shows that it now works
- Fix readme as port number is required in soruces
Its currently possible to workaround the crash by adding `insecure_skip_verify = true` to the conf

Fix segfault in x509_cert

---

plugins/inputs/swap/README.md

Especially for the fields in & out it was pretty unclear what they contain as the usual values from `vmstat` returns the number of pages but here we get bytes.

Add more detailed description for swap fields

---

Gopkg.lock
Gopkg.toml
plugins/outputs/kinesis/kinesis.go

Updates the plugin's stream discovery to use DescribeStreamSummary[1]
in favor of ListStreams[2]. The API switch has the following benefits.
* **Faster Startup** - Previously, the configured stream had to be compared
against all available streams (possibly paginating the results) to check
its existence. Now it just calls a single API.
* **Improved Security** - Previously, the AWS IAM credentials had to have
read access to list all available streams. Now the AWS IAM credentials
can restrict operations to a specific Kinesis stream ARN.
* **Improve API Limits** - Per the AWS documentation, DescribeStreamSummary[1]
has a limit of 20 transactions per second while ListStreams[2] has a limit
of 5 transaction per second.
[1] https://docs.aws.amazon.com/kinesis/latest/APIReference/API_DescribeStrea …

Improve AWS Kinesis IAM Security

---

.circleci/config.yml
Makefile
appveyor.yml
scripts/ci-1.10.docker

Updates CI image and config to latest Go 1.10.4 release.

Update CI to Go 1.10.4

---

plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

If there is a certificate chain in input source, all certificates are
returned with the same source tag. Subject of the certificate is added
to use all certs in the chain as an input.

Add certificate subject as a tag

---

.circleci/config.yml
Makefile
scripts/ci-1.11.docker

Add Go 1.11 CI support

---

plugins/inputs/nsq/nsq.go
plugins/inputs/nsq/nsq_test.go

Add support for TLS configuration in NSQ input to reach HTTPS nsqd endpoints

---

Gopkg.lock
Gopkg.toml
plugins/inputs/all/all.go
plugins/inputs/ipvs/README.md
plugins/inputs/ipvs/ipvs.go
plugins/inputs/ipvs/ipvs_notlinux.go

IPVS input plugin

---

plugins/outputs/kinesis/README.md
plugins/outputs/kinesis/kinesis.go
plugins/outputs/kinesis/kinesis_test.go

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
Resolves #4894

Set defaults on kinesis output partition key when tag does not exist.

---

plugins/inputs/ipmi_sensor/ipmi.go
plugins/inputs/ipmi_sensor/ipmi_test.go
plugins/inputs/wireless/wireless_test.go

Handle panic when ipmi_sensor input gets bad input

---

plugins/inputs/jolokia2/examples/zookeeper.conf
plugins/inputs/jolokia2/jolokia_test.go
plugins/inputs/jolokia2/point_builder.go

Don't add unserializable fields

---

plugins/inputs/postgresql_extensible/postgresql_extensible.go

Fixes https://github.com/influxdata/telegraf/issues/3864
Idea from @robinsmidsrod
https://github.com/influxdata/telegraf/issues/3864#issuecomment-380828664
No need for README update.
Unsure how to emulate PG version in unit tests

postgresql_extensible: fix DB version check for version 10+

---

plugins/inputs/vsphere/endpoint.go

Resolving issue #4855 by adding a human readable tag named ```dsname``` to all datasource instances in VMs and hosts. This should NOT increase cardinality, since it has a 1:1 relationship to ```lun```. We decided to keep the original ```lun``` tag for backward compatibility.

Implemented LUN to datasource translation

---

plugins/outputs/influxdb_v2/http.go

Resolves #4947 
Now, instead of `EOF` the description will contain the response status:
`E! [outputs.influxdb_v2] Failed to write metric: 403 Forbidden`

Add a better default error description

---

plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/prometheus.go
plugins/inputs/prometheus/prometheus_test.go

Allow connecting to prometheus via socket

---

internal/config/config.go

closes #4489
Only permits HTTPS with a valid certificate.

Add support for fetching config over https

---

testutil/accumulator.go

Simple fix in the `testutil.Accumulator` `AddFields` method - `fieldsCopy` should be used instead of `fields` which can be mutated outside of the method. Also made a change to return earlier to avoid an extra iteration of `tags`.

Use fieldsCopy in testutil.Accumulator AddFields

---

agent/agent.go
cmd/telegraf/telegraf.go

Resolves #3454
Currently, the cpu, mongodb, and procstat input plugins run twice so as to collect `cpu_usage`, this change will only print the second collection that includes it as a field.

Only print final collection when runing --test

---

cmd/telegraf/telegraf.go
plugins/inputs/wireless/wireless.go
plugins/inputs/wireless/wireless_linux.go
plugins/inputs/wireless/wireless_nonlinux.go

Log once on startup if the wireless plugin is not supported on the platform.
Pros
+ plugin is still a non-service plugin on all platforms
+ logging happens once
+ linux code doesn't need to worry about logging
+ plugin config still must be valid
+ fixes annoying timestamp format difference when Telegraf starts
Cons
- Tests can be ran only on linux
- Not crazy about the order of logging
- Telegraf still runs even if no plugins are supported
- Plugin still logged as loaded
Some of these issues can be resolved after config loading work.
Here is the logging output:
```
2018-11-13T23:32:39Z I! Starting Telegraf
2018-11-13T23:32:39Z I! Using config file: /home/dbn/.telegraf/telegraf.conf
2018-11-13T23:32:39Z W! [inputs.wireless] Current platform is not supported
2018-11-13T23:32:39Z I! Loaded …
```

Log warning when wireless plugin is used on unsupported platform

---

CHANGELOG.md
etc/telegraf.conf
plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go

Add option to gather Elasticsearch cluster stats from all node (default is old behavior, stats are only gathered from master).
Also documented the fact that gathering only from master node only works if local = true.
Slightly changed behavior when local=false and cluster_stats=true. Previous behavior was undetermined (it gather cluster stats only if the last node is the master node. The order was based on the order of a map which is probably not fixed). New behavior is the documented one: if local = false, we gather from all node.

Allow for force gathering ES cluster stats

---

plugins/serializers/splunkmetric/splunkmetric.go
plugins/serializers/splunkmetric/splunkmetric_test.go

Strings are still dropped, bools are set to 1 for true and 0 for false
closes: #5006
- [n/a] Associated README.md updated.

Refactor value verification to manage bools.

---

plugins/inputs/mongodb/mongostat.go

The MongoDB plugin currently showing the connection information, example:
```
./telegraf --config telegraf.conf --test
2018-11-27T20:32:59Z I! Starting Telegraf
> mongodb,host=muraritele-01-154333202752 commands_per_sec=8i,connections_available=0i,connections_current=0i,deletes_per_sec=0i,flushes_per_sec=0i,getmores_per_sec=0i,inserts_per_sec=0i,queries_per_sec=2i,resident_megabytes=49i,updates_per_sec=0i,vsize_megabytes=307i 1543350780000000000
> mongodb_db_stats,db_name=admin,host=muraritele-01-154333202752 avg_obj_size=310.7,collections=3i,data_size=3107i,index_size=81920i,indexes=4i,num_extents=0i,objects=10i,ok=1i,storage_size=65536i,type="db_stat" 1543350780000000000
> mongodb_db_stats,db_name=local,host=muraritele-01-154333202752 …
```

Fix input plugin MongoDB server connection info

---

plugins/parsers/csv/README.md
plugins/parsers/csv/parser.go
plugins/parsers/csv/parser_test.go

For now the csv parser does not handle unix timestamp like `1257894000` as csv_timestamp_format in the csv as timestamp.
So to fix that if csv_timestamp_format = Unix, we assume that the timestamp is an epoch ms format.
```golang
metricTime = time.Unix(timeUnixValue, 0)
```
I have also added unit tests, and no others unit test were broken.
=== RUN   TestBasicCSV
--- PASS: TestBasicCSV (0.00s)
=== RUN   TestHeaderConcatenationCSV
--- PASS: TestHeaderConcatenationCSV (0.00s)
=== RUN   TestHeaderOverride
--- PASS: TestHeaderOverride (0.00s)
=== RUN   TestTimestamp
--- PASS: TestTimestamp (0.00s)
=== RUN   TestTimestampError
--- PASS: TestTimestampError …

Plugins parsers csv unix timestamp

---

plugins/inputs/graylog/graylog.go

X-Requested-By is needed by Graylog in order to respond API requests. It adds URL's hostname as requested-by parameter.
Resolves #5010

Graylog Input X-Requested-By added.

---

docs/CONFIGURATION.md

This example shows how to use tagdrop to filter based on windows network interface names. Related to this discussion: https://github.com/influxdata/telegraf/pull/5018#issuecomment-442243175

Add tagdrop example for inputs.win_perf_counters

---

plugins/inputs/interrupts/README.md
plugins/inputs/interrupts/interrupts.go
plugins/inputs/interrupts/interrupts_test.go

Switch CPU from field to tag in Interrupts input plugin (#4999)

---

plugins/inputs/ping/ping.go

Under version `Telegraf 1.9.0` the ping plugin throws the following error under FreeBSD 11.2:
```
2018-12-05T13:42:50Z E! [inputs.ping]: Error in plugin: host 1.1.1.1: ping: illegal option -- w
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize] [-g sweepminsize]
[-h sweepincrsize] [-i wait] [-l preload] [-M mask | time] [-m ttl]
[-P policy] [-p pattern] [-S src_addr] [-s packetsize] [-t timeout]
[-W waittime] [-z tos] host
ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait] [-l preload]
[-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
[-s packetsize] [-T ttl] [-t timeout] [-W waittime]
[-z tos] mcast-group, exit status 64
```
This fixes that and changes the flag to `-W` which was probably intended in that use-case.

Fixed ping plugin under bsd variants. 

---

plugins/parsers/wavefront/element.go
plugins/parsers/wavefront/parser_test.go
plugins/parsers/wavefront/scanner.go
plugins/parsers/wavefront/token.go

In response to issue #5114 .
With this patch, Telegraf accepts and forwards delta metrics correctly using a Wavefront format listener.

stop Wavefront parser rejecting delta metrics

---

plugins/inputs/varnish/varnish.go

With a large amount of VCLs loaded, varnishstat can take slightly longer to run. This is not a complete fi, but should suffice in 98% of cases.
See https://github.com/varnishcache/varnish-cache/issues/2712#issuecomment-445864700 for some background.

Increase varnishstat time allotment.

---

agent/accumulator.go
plugins/inputs/procstat/README.md
plugins/inputs/procstat/procstat.go

This field indicates the number of processes that were actually found, as opposed to pid_count which tells you how many pids were found and may not be what you are after with some query methods.
closes #5043

Add running field to procstat_lookup

---

plugins/inputs/http/README.md
plugins/inputs/http/http.go
plugins/inputs/http/http_test.go

Add support for sending a request body to http input

---

plugins/inputs/diskio/README.md
plugins/inputs/diskio/diskio_linux.go
plugins/inputs/diskio/diskio_linux_test.go

Partial fix for https://github.com/influxdata/telegraf/issues/3663. The diskio plugin claims to grab udev properties when specified, but can't actually grab all of them due to the way it is written. One property it didn't grab is "DEVLINKS." Our company, Skytap, has a business need for using diskio to tag with DEVLINKS, and it was only a few lines of code to add that capability.

Include DEVLINKS in available diskio udev properties

---

plugins/outputs/azure_monitor/azure_monitor.go

Fix translate empty tag values

---

plugins/processors/converter/README.md

Rename "ParseServerConfigGeneration" in example config to match "ParentServerConfigGeneration" as used in example diff.

Fix Converter Processor Example

---

plugins/inputs/prometheus/prometheus.go

Run stop logic only if required

---

internal/globpath/globpath.go
internal/globpath/globpath_test.go
plugins/inputs/file/file.go
plugins/inputs/filestat/filestat.go
plugins/inputs/logparser/logparser.go
plugins/inputs/tail/tail.go

Hello,
This PR adds 2 simple optimizations to globpath internal library :
- returns file names rather than fileInfo (-> prevents us stat-ing found files, as fileInfo is most of the times discarded by the caller)
- replaces filepath.walk with godirwalk library. The latter is more efficient (less `stat` calls).
I used `unsorted : true` option of godirwalk. It changes the order of recursion (the option name is quite explicit), and thus the order of the results provided by telegraf plugins. As there is no contract about the order of results with telegraf users, i don't consider this move as a breaking change. But this (small) optimization could be reverted if you disagree with that point.
While it is an optimization on the paper, results are not striking. Simple `time` results with and …

Optimization : globpath using godirwalk

---

plugins/inputs/couchdb/README.md
plugins/inputs/couchdb/couchdb.go

Add support for basic auth in couchdb input

---

plugins/inputs/win_perf_counters/win_perf_counters.go
plugins/inputs/win_perf_counters/win_perf_counters_test.go

Add PDH_NO_DATA to known counter error codes

---

agent/agent.go
scripts/init.sh

It often takes Telegraf a while to do a clean shutdown, as it attempts to write the metric buffer before stopping, which led to a few issues.
This line signals the process and returns success if signaled, this almost always works and so the pidfile is removed.  If Telegraf has not shutdown this will remove the pidfile before Telegraf can do so.  Since the script then exits stop it is possible that Telegraf will be restarted before the running Telegraf exits.  The new pidfile will then be removed by the closing Telegraf, which means any future attempts to stop Telegraf will not be able to find the process to signal it.
```
killproc -p $pidfile SIGTERM && /bin/rm -rf $pidfile
```
With this change the pidfile is removed only if Telegraf exits.  The script will wait for Telegraf to exit, you …

Signal telegraf process until it exits

---

agent/accumulator_test.go
metric/tracking.go

If an empty array of tracking metrics is added to the accumulator, just mark it as immediately delivered and send delivery notification.  This avoids potential errors and avoids the input needing to check for empty groups.
closes #5170

Deliver empty metric tracking group immediately

---

plugins/aggregators/valuecounter/README.md
plugins/aggregators/valuecounter/valuecounter.go
plugins/aggregators/valuecounter/valuecounter_test.go

Allow floats in valuecounter aggregator.

---

plugins/processors/strings/strings.go
plugins/processors/strings/strings_test.go

Solves issue brought up discussing use of strings processor to replace localized names.
closes #4906

Fix usage of loop variable in function closure

---

plugins/inputs/ceph/README.md
plugins/inputs/ceph/ceph.go
plugins/inputs/ceph/ceph_test.go

[inputs.ceph] added the read and write op per second fields

---

plugins/inputs/net_response/net_response.go

Previously, `net_response` was limiting udp connections to localhost as the return address was always `127.0.0.1`

Allow non local udp connections in net_response

---

plugins/parsers/registry.go

Fix toml option names in parser processor

---

Gopkg.toml

This gets rid of some error messages in the log caused by a (benign) race condition in the sdk.

Changed to wavefront-sdk-go 0.9.1

---

plugins/inputs/docker/docker.go

Docker input to error on bad endpoint

---

plugins/inputs/http_response/README.md

Adding undocumented response_string_match field and making it clear which result_code 4xx and 5xx errors will trigger.

http_response plugin docs

---

plugins/inputs/sqlserver/sqlserver.go

- when using the money type,  large values can cause arithmetic overflow
exceptions
- use decimal(19,4) in favor of money
- fixes '[inputs.sqlserver]: Error in plugin: mssql: Arithmetic overflow
error converting expression to data type money.

sqlserver: fix type overflow in perf counter query

---

internal/models/buffer.go
internal/models/buffer_test.go
internal/models/running_output_test.go
testutil/metric.go

Use lifo order in metric buffer

---

plugins/inputs/prometheus/kubernetes.go
plugins/inputs/prometheus/kubernetes_test.go
plugins/inputs/prometheus/prometheus.go

Stop collecting from deleted pods
Resolves #5281

Collect from newly discovered/launched pods

---

Gopkg.lock
Gopkg.toml
plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go

This change passes the metrics collection time to prometheus.
Prior to this change, prometheus can see one sample as two different samples, which generates dips/spikes on the charts.
For example:
- prometheus scrape interval = 7 sec;
- collection interval = 5 sec;
- expression: `irate(system_uptime[30s])`

Keep input timestamp for prometheus metrics

---

plugins/inputs/couchbase/README.md
plugins/inputs/couchbase/couchbase.go

Resolves #5215
```toml
[[inputs.couchbase]]
servers = ["http://user:password@localhost:8091/"]
```
Before:
```
couchbase_node,cluster=http://localhost:8091/,hostname=172.17.0.2:8091 memory_free=7703277568,memory_total=16558182400 1547829563000000000
couchbase_bucket,bucket=beer-sample,cluster=http://user:password@localhost:8091/ disk_used=21662943,data_used=9325087,mem_used=28408920,quota_percent_used=27.09285736083984,ops_per_sec=0,disk_fetches=0,item_count=7303 1547829563000000000
```
After:
```
couchbase_node,cluster=http://localhost:8091/,hostname=172.17.0.2:8091 memory_free=7705575424,memory_total=16558182400 1547829754000000000
couchbase_bucket,bucket=beer-sample,cluster=http://localhost:8091/ quota_percent_used=27.09285736083984,ops_per_sec=0,disk_fetches=0,item_count=7303,disk_used …
```

Remove credentials from cluster tag in couchbase input

---

internal/models/buffer.go
internal/models/buffer_test.go
internal/models/running_output.go

Update the internal_write buffer_size metric immediately when a metric is added and after a successful write.  Includes a fix for metric buffer changes on master that can cause a panic.
closes #5298

Update the buffer_size internal metric after writes

---

internal/config/config.go

Resolves #5334
Turns out `skip_rows` and `skip_columns` were never getting set in the csv parser.
Tested with:
```toml
[[inputs.exec]]
timeout = "1s"
command = "echo -en 'version=13.0\ndate,instance,Incoming Requests,Outgoing Requests,Incoming Answers 2xxx,Outgoing Answers 2xxx,Incoming Answers UTD,Outgoing Answers UTD,Incoming Answers Redirect,Outgoing Answers Redirect,Incoming Answers Other,Outgoing Answers Other,Retransmit Requests,Rejected Requests Filtering,Rejected Requests In-gress Filtering,Rejected Requests Other,Timeout Requests,Discarded Answers\n2018-01-23-12:04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\n'"
data_format = "csv"
csv_skip_rows = 1
csv_header_row_count = 1
csv_delimiter = ","
csv_trim_space = true
csv_tag_columns = ["instance"]
csv_timestamp_column = "date" …
```

Set skip rows and columns in csv parser

---

etc/telegraf.conf
plugins/inputs/consul/README.md
plugins/inputs/consul/consul.go

Fix Consul "datacenter" typo

---

plugins/inputs/influxdb_listener/http_listener.go

Adding ability to disable authentication on ping route.  Load balancers like AWS's ALBs don't support basic auth.

Removing auth from /ping route

---

README.md
docs/DATA_FORMATS_OUTPUT.md
plugins/serializers/carbon2/README.md
plugins/serializers/carbon2/carbon2.go
plugins/serializers/carbon2/carbon2_test.go
plugins/serializers/registry.go

This PR addresses issue #5344 by adding a Carbon2 serializer.  Carbon2 is a metrics format supported by multiple applications and vendors.  Implementing it as a serializer would allow it to integrate with the existing output plugin ecosystem as well as integrate with any additional vendors who want to add support for the Carbon2 format.

Add carbon2 serializer

---

testutil/accumulator.go

Improved the testutil accumulator's `AssertDoesNotContainsTaggedFields` method to allow testing for specific fields that don't have a set of tags (tags that may exist in the same measurement under different fields). Otherwise such a test within the same measurement type isn't possible (checking that the same set of tags exists on some fields but not others).
I think the method as is would have been more accurately named `AssertDoesNotContainsTags` since it is mainly testing for tags. If it's better to instead create a `AssertDoesNotContainsTags` method with the original logic, and `AssertDoesNotContainsTaggedFields` with the changes below, I am happy to make that change!

Improve testutil AssertDoesNotContainsTaggedFields

---

scripts/build.py

Add mipsle package

---

plugins/outputs/cloud_pubsub/README.md
plugins/outputs/cloud_pubsub/pubsub.go

updated the default config (and the README) for the output plugin: the output plugin publishes to a topic, it does not subscribe to a subscription. This is probably a copy/paste error from the input plugin.
- [n/a ] Has appropriate unit tests.

replaced subscription with topic in the pubsub output plugin

---

internal/internal.go
plugins/parsers/csv/parser.go
plugins/parsers/json/parser.go

Resolves #5310
If the internal package isn't a good place to locate the `ParseTimestamp` function, it can be moved.

Unify time parsing in json/csv parsers

---

plugins/outputs/stackdriver/README.md
plugins/outputs/stackdriver/stackdriver.go
plugins/outputs/stackdriver/stackdriver_test.go

This change attempts to mitigate #5364 by sorting the batch, but doesn't solve the issue.  Remaining issues are documented in the README and some errors are ignored, resulting in some points being dropped, but attempting to keep the output from becoming stuck.
related #5364

Stackdriver sort order

---

scripts/post-install.sh
scripts/post-remove.sh

Amazon Linux 2 uses systemd. This PR adds support for Amazon Linux 2 in the Telegraf `post-install.sh` and `post-remove.sh` scripts.
closes #5117

Use Systemd for Amazon Linux 2

---

plugins/outputs/stackdriver/README.md
plugins/outputs/stackdriver/stackdriver.go
plugins/outputs/stackdriver/stackdriver_test.go

This is a follow-up on #5389 and depends on it. Adds functionality to customize resource labels for Stackdriver metrics. Resource types apart from `global` have required labels, so this is necessary to make #5389 useful.

Stackdriver output config resourcetype labels

---

plugins/inputs/influxdb_listener/http_listener.go

Provides the ability to sort/search for errors that relate to the input being oversized.

Change log level of buffer too small error

---

plugins/inputs/sqlserver/sqlserver.go

- sets deadlock priority to the lowest possible value
- this will tell sqlserver to force this spid to be the deadlock victim (which is ok) in case of a deadlock with a running query that is running at normal deadlock priority.
- we don't want telegraf metrics to be interrupting other
operational queries on the database instance
- resolves #4988

[inputs.sqlserver]: set deadlock priority low

---

plugins/outputs/mqtt/README.md
plugins/outputs/mqtt/mqtt.go

----
Not unit-testable. Behavior confirmed to be correct in-house on the following configuration:
* FreeBSD 11-STABLE
* Mosquitto 1.5.3
* `mosquitto.conf`:
```txt
persistence true
autosave_interval 5
autosave_on_changes true
log_dest syslog
log_type warning
persistence_location /data/mosquitto/
persistent_client_expiration 1w
bind_address 127.0.0.1
port 1300
```
* `telegraf.conf`:
```toml
[global_tags]
[agent]
interval = "60s"
round_interval = true
metric_batch_size = 100
metric_buffer_limit = 10000
collection_jitter = "500ms"
flush_interval = "10s"
flush_jitter = "10s"
precision = ""
quiet = true
hostname = ""
omit_hostname = false
[[outputs.mqtt]]
servers = ["localhost:1300"]
client_id = "telegraf-out"
qos = 2
batch = true
retain = true
topic_prefix = "telegraf"
[[inputs.cpu]] …
```

Add retain flag to mqtt output to let brokers/servers cache measurements

---

plugins/inputs/nstat/README.md
plugins/inputs/nstat/nstat.go

Silently ignore missing `/proc/stat/snmp6` directory
Resolves #5403

Check if SNMP6 directory exists (#5403)

---

plugins/inputs/dns_query/README.md
plugins/inputs/dns_query/dns_query.go

Resolves #5276 
From what I see it's always been creating a metric with the result and result_code, but I've enhanced the logging to give more information:
```
2019-02-12T15:41:12Z E! [inputs.dns_query]: Error in plugin: Invalid answer (NXDOMAIN) from 127.0.0.1 after A query for definitelynotreal.com
dns_query,domain=definitelynotreal.com,record_type=A,result=error,server=127.0.0.1 result_code=2i 1549986072000000000
dns_query,domain=google.com,record_type=A,result=success,server=127.0.0.1 result_code=0i,query_time_ms=0.440704 1549986072000000000
```

Enhance error log when dns query isn't successful

---

plugins/outputs/influxdb/udp.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go

Fixes #5438 
- Set MaxLineBytes correctly
- Split the data to utilize as much of the datagram as possible (even with MaxLineBytes set correctly each metric that did not fit into the first datagram was split up separately)
- Split the byte slice from serializer to separate UDP datagrams if there are multiple lines

Fix InfluxDB UDP line splitting (#5438)

---

plugins/outputs/stackdriver/stackdriver.go
plugins/outputs/stackdriver/stackdriver_test.go

This is a first attempt at #5404. This is not yet perfect, as it just does an iteration over the metrics/fields, adding TimeSeries until adding the next one would mean a duplicate, in which case it sends off the batch so far and then proceeds with a new request.
This should still be an improvement over the current situation (it is not yet properly tested in practice, though)

Aggregate multiple Stackdriver TimeSeries in requests

---

plugins/outputs/azure_monitor/README.md
plugins/outputs/azure_monitor/azure_monitor.go

Azure sovereign cloud environments do not conform to the `<region>.monitoring.azure.com` endpoint address.  This proposed change looks to allow for an override of the endpoint URL so that metrics can be pushed to the appropriate URL and Azure Monitor.
Attempts to address #5452 and this is my first PR to this project.  Before I continue further, I'd like to get some insight/feedback on this approach and if it seems reasonable, will continue by building out the necessary unit tests (e.g. endpoint_override = "testymctesturl.testing")? 
Comments and insights appreciated (_also, I'm not a go programmer by any means, but wanted to contribute this_)

Support Azure Sovereign Environments with EndpointOverride argument

---

plugins/parsers/wavefront/element.go
plugins/parsers/wavefront/parser_test.go

Values with negative exponents were being rejected. This patch allows values of the form `1.0E-05` to pass through.  Unit tests added accordingly.

Wavefront Parser: accept values with a negative exponent

---

plugins/inputs/snmp/snmp.go

Just some verbose logging to help debug issues executing subprocesses, only visible when running with `--debug`.
related: #4896

Add command logging to snmp input at debug level

---

plugins/inputs/socket_listener/socket_listener.go
plugins/inputs/socket_listener/socket_listener_test.go

related #5371
related #5448
```
2019-02-20T03:46:38Z I! [inputs.socket_listener] Listening on tcp://0.0.0.0:8095
2019-02-20T03:46:38Z I! [inputs.socket_listener] Listening on udp://0.0.0.0:8094
```

Log the protocol and address that socket_listener is listening on.

---

internal/config/config.go
internal/internal.go
internal/internal_test.go
plugins/parsers/json/README.md
plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go
plugins/parsers/registry.go

Support configuring a default timezone in JSON parser

---

plugins/inputs/ceph/README.md
plugins/inputs/ceph/ceph.go
plugins/inputs/ceph/ceph_test.go

Resolves #5277 
Resolves #3387 by gathering health metrics
Likely that 3431 is close-able
Has anyone tried using the telegraf plugin built into ceph starting in mimic? http://docs.ceph.com/docs/mimic/mgr/telegraf/

Add alternative fieldnames for ceph input

---

internal/config/config.go
plugins/parsers/grok/README.md
plugins/parsers/grok/parser.go
plugins/parsers/registry.go

Resolves #5394 by adding `disable_time_mod` option to grok parser.

Add option to disable timestamp adjustment in grok parser

---

plugins/outputs/stackdriver/stackdriver.go

@danielnelson Apologies for the succession of incomplete fixes - the current `master` can encounter off-by-one-errors writing > 200 timeseries per request because the loop was broken too late. This adrdesses that - has been running the past 3 days with decent loads without any issues. Good news is compared to before the bucket-batching we are seeing over an order of magnitude of reduction in requests.

Move capacity check for stackdriver output plugin

---

internal/config/config.go

Remove 'inputs.' prefix when logging loaded inputs

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/http.go
plugins/outputs/influxdb/http_test.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/influxdb/influxdb_test.go
plugins/outputs/influxdb/udp.go
plugins/outputs/influxdb/udp_test.go
plugins/outputs/influxdb_v2/README.md
plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/http_internal_test.go
plugins/outputs/influxdb_v2/influxdb.go

Influxdb output database routing tag

---

logger/logger.go
logger/logger_test.go

Problem:
When log file didn't exist the agent used to create a file without `O_APPEND` mode. This led to the file growing indefinitely, because the writes ignored the truncated file (by the current `logrotate` settings) and did not update the fd offset.
When you write to the offset bigger than the current file size, the file is expanded by the OS (at least Linux), the gap is filled with `\0`.
Note:
This behavior doesn't apply when the log file has already been created before Telegraf starts. The file opened in the proper append mode then.
Fix:
Always open in `O_APPEND` mode.

Open log file in append mode.

---

internal/models/running_aggregator.go
metric/metric.go

When passing a metric into an aggregator remove the tracking info and don't count it towards the metric refcount.
While it would be possible to track the metric in the aggregator, there are a few issues:
- The throughput would be limited to `max_undelivered / aggregator period`, since nothing would be delivered until the aggregator period ends.
- If the metric was not delivered, it is unlikely it can be aggregated again anyway, since we do not support aggregating metrics with timestamps in the past.  Reprocessing the metric would produce only the original metric, so its not helpful to hold off on marking it delivered.
closes #5325

Ignore tracking for metrics added to aggregator

---

internal/models/buffer.go
internal/models/buffer_test.go

Fix panic when rejecting empty batch

---

plugins/parsers/grok/parser.go
plugins/parsers/grok/parser_test.go
plugins/parsers/registry.go

Allow grok to produce metrics with no fields

---

plugins/inputs/cloud_pubsub/README.md
plugins/inputs/cloud_pubsub/pubsub.go
plugins/inputs/cloud_pubsub/pubsub_test.go
plugins/outputs/cloud_pubsub/README.md
plugins/outputs/cloud_pubsub/pubsub.go
plugins/outputs/cloud_pubsub/pubsub_test.go
plugins/outputs/cloud_pubsub/topic_stubbed.go

- [x ] Has appropriate unit tests.
This enables several GCP services that can and only output base64-encoded JSON to PubSub (and thus input into Telegraf/TICK). Enabled base-64 encoded for output of metrics just because symmetry is nice and it's suggested that PubSub wants base64-encoded data no matter what.

Base64-encoding/decoding parameters for Google Cloud PubSub plugins

---

plugins/inputs/socket_listener/socket_listener.go

Return error creating tls config

---

plugins/inputs/webhooks/README.md
plugins/inputs/webhooks/filestack/README.md
plugins/inputs/webhooks/mandrill/README.md
plugins/inputs/webhooks/particle/README.md
plugins/inputs/webhooks/rollbar/README.md
plugins/inputs/webhooks/webhooks.go

Add configuration example and links to supported webhook sites.
It appears the individual webhook readmes were all based off of the same example. I don't quite believe that every supported webhook has the same methods of adding a webhook endpoint.

Fix links and add config to webhook readme

---

plugins/inputs/ping/README.md
plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

Feature request [5537](https://github.com/influxdata/telegraf/issues/5537)

Input Plugin: Adding TTL field for Ping plugin 

---

plugins/inputs/vsphere/endpoint.go
plugins/inputs/vsphere/finder.go
plugins/inputs/vsphere/vsphere.go

TL;DR version:
In version 1.10, we changed the data type of all samples to floating point. This caused problems when sending data to existing InfluxDB databases. The ```use_int_samples``` forces the plugin to send int samples for everything except percentages.
Long version:
Under certain conditions, such as high load, vCenter can significantly delay sample delivery. When this happens, the plugin will see empty samples for the current time period. To solve this, we have to look back a certain number of sample periods to catch delayed data. Unfortunately, that data can come in at different time series granularity, so we apply a normalization process implemented in Endpoint.alignMetrics. This process consists of dividing the raw time series into buckets according to the desired sample …

[inputs.vsphere] Introduce use_int_samples to obtain backwards compatibility

---

plugins/parsers/csv/parser.go

If an empty column is present in parsed csv data, a `recordFields` is
set to the key of "". If no `MeasurementColumn` is defined, this empty
value was being used as the measurement name. By only setting the
measurementName if the value is not empty, we avoid this error.
Since an empty column is a valid column, skip values must account for
them.
Resolves #5530

Use valid measurement names in csv parser

---

Gopkg.lock
appveyor.yml

Most of the errors I am seeing on Appveyor are caused by not being able to clone the golang.org/x repos.  The hosting for these repos does not appear to be very reliable, so this switches to the github.com mirrors.
Also cache the dep/sources directory unless the Gopkg.lock changes.
Might pull this over to release-1.10 if we continue to have problems there.

Improve stability of appveyor builds

---

agent/agent.go

If a Telegraf is asked to stop (SIGTERM, SIGINT) while it is aligning an
aggregator, ``internal.SleepContext`` will fail and the goroutine will
return without closing the ``aggregations`` channel getting stuck
forever in ``for metric := range aggregations``
Sample config file to test the problem:
```
[global_tags]
[agent]
interval = "60s"
debug = true
[[aggregators.basicstats]]
period = "1800s"
[[inputs.mem]]
[[outputs.file]]
files = [ "stdout" ]
```
Run telegraf:
```
telegraf -config telegraf.conf
```
Kill it before 60s:
```
pkill telegraf
```
It won't finish.
Here [telegraf.log](https://github.com/influxdata/telegraf/files/2988434/telegraf.log) is the log of the execution mixed with the ``kill -ABRT`` used to check the status of goroutines.
``goroutine 58 (agent.runAggregators)`` is the …

Fix deadlock when Telegraf is aligning aggregators

---

agent/agent.go
internal/models/running_output.go
plugins/outputs/file/file.go

- Always use OpenFile, this way the file is always opened in append mode.
- Fix err handling, err was incorrectly shadowed
- Changed agent so that close errors are reported per plugin (eg `[outputs.file]`)

Fix open error handling in file output

---

plugins/parsers/grok/influx_patterns.go
plugins/parsers/grok/parser.go
plugins/parsers/grok/parser_test.go

This change is not backwards compatible, the workaround for old patterns relying on this trimming is:
`%{QS} -> "%{DATA}"`
closes #4998

Remove string trimming from grok parser

---

scripts/build.py

With this change the `/etc/telegraf`, `/etc/telegraf/telegraf.d`, and `/var/log/telegraf` directories will be removed with the package.  
Following standard rpm behavior the directories are not removed if they contain new files. As before, if the `/etc/telegraf/telegraf.conf` file has been modified it will be renamed and saved as `/etc/telegraf/telegraf.conf.rpmsave`.

Add owned directories to rpm package

---

plugins/inputs/diskio/diskio_linux.go

The current implementation assure that the major and the minor are
coded on one byte. But they are not:
```
brw-rw----  1 root disk    252, 290 Feb 25 11:36 dm-290
```
290 as minor in this example is over 1 byte.
So after wondering why all my devices iops weren't correctly stored,
I found out that several points were added for some disks. For `dm-290`
it was overriding `252:34`, instead of getting udev stats for `252:290`.
The solution is here:
https://sites.uclouvain.be/SystInfo/usr/include/sys/sysmacros.h.html
The implementation is directly taken from this, fixing my bug.

[inputs/diskio] Fix how major and minor identifiers of block devices are read.

---

plugins/inputs/exec/exec.go
plugins/inputs/exec/exec_test.go
plugins/parsers/nagios/parser.go
plugins/parsers/nagios/parser_test.go

Example Nagios check output:
```
DISK OK - free space: / 3326 MB (56%); | /=2643MB;5948;5958;0;5968
/ 15272 MB (77%);
/boot 68 MB (69%);
/home 69357 MB (27%);
/var/log 819 MB (84%); | /boot=68MB;88;93;0;98
/home=69357MB;253404;253409;0;253414
/var/log=818MB;970;975;0;980
```
Old behavior:
```
nagios_state,host=localhost state=0i 1552677172000000000
nagios,host=localhost,perfdata=/,unit=MB critical_gt=5958,critical_lt=0,max=5968,min=0,value=2643,warning_gt=5948,warning_lt=0 1552677172000000000
nagios,host=localhost,perfdata=/boot,unit=MB critical_gt=93,critical_lt=0,max=98,min=0,value=68,warning_gt=88,warning_lt=0 1552677172000000000
```
**New** behavior:
```
nagios,host=localhost,perfdata=/,unit=MB critical_gt=5958,critical_lt=0,max=5968,min=0,value=2643,warning_gt=5948,warning_lt=0 …
```

Fix nagios parser to parse all perfdata and report info message.

---

agent/agent.go
docker-compose.yml

Aggregators' `drop_original = true` doesn't work well with `*_consumer` inputs' `max_undelivered_messages`. (mentioned by me at https://github.com/influxdata/telegraf/issues/5595#issuecomment-476546850)
`*_consumer` inputs are using `AddTrackingMetricGroup` to find out whether metrics get delivered (either `Accept` or `Drop`, `Reject` won't count). However, when `drop_original = true`, metrics are dropped without calling `metric.Drop()`. As a result, inputs lost track of metrics, consider dropped metrics undelivered, and `max_undelivered_messages` is reached rather quickly. Eventually, `*_consumer` inputs stop consuming new messages.

Fix aggregator metric drop

---

plugins/inputs/statsd/statsd.go

Don't return from the Start method until plugin is listening, this ensures that we know when the plugin can receive data and also when it is safe to call the Close method.
With great resolve I skipped fixing the off style log messages.
closes #5618

Listen before leaving start in statsd

---

plugins/inputs/filecount/filecount.go

Not just a Windows bug, previously we would panic on paths without a `/`, and it was possible to not detect the top directory if it was aliased with a different path.
closes #5621

Fix basedir check and parent dir extraction in filecount input

---

cmd/telegraf/telegraf.go

If neither --console or --service is added to the command line, run as a service only in a non-interactive shell.  This is always a little scary to change, but currently Telegraf refuses to exit when running --test unless you also specify --console.

Exit after running --test without requiring --console

---

accumulator.go
agent/accumulator.go
agent/accumulator_test.go
agent/agent.go
agent/agent_test.go
internal/internal.go
internal/internal_test.go
internal/models/running_aggregator.go
internal/models/running_aggregator_test.go
testutil/accumulator.go

Fix aggregator window and shutdown of multiple aggregators

---

docs/CONFIGURATION.md
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/single_plugin_env_vars.toml

Both styles will work, but in the docs I'm only recommend the ${} syntax since it gives you one less thing to worry about.
closes #5646

Add support for ${} env vars in configuration file

---

plugins/aggregators/histogram/README.md
plugins/aggregators/histogram/histogram.go
plugins/aggregators/histogram/histogram_test.go

For some use cases it is desireable for the histogram buckets to be reset between operations. 
A good example is collecting data from processes using the PID as a tag where the cardinality may become very high and series can become "stale". With the current implementation, series for already dead processes will still continue to be reported on. 
This functionality could be further improved by adding a reset interval and per-subconfig reset options but I expect that for most use cases just having everything reset on flush is a simple and effective solution. 
@vlamug It would be good to hear your thoughts on this

[aggregators/histogram] Add option to reset buckets on flush

---

Gopkg.lock
Gopkg.toml
plugins/inputs/prometheus/kubernetes.go

Resolves https://github.com/influxdata/telegraf/issues/5642

Use github.com/ghodss/yaml to parse k8s config (#5642)

---

plugins/outputs/wavefront/README.md
plugins/outputs/wavefront/wavefront.go
plugins/outputs/wavefront/wavefront_test.go

Allow Wavefront output to accept / and ,

---

docker-compose.yml

This is what is configured in the connection string within cratedb_test.go

Expose CrateDB on Host Port 6543

---

Gopkg.lock
Gopkg.toml
plugins/inputs/all/all.go
plugins/inputs/github/README.md
plugins/inputs/github/github.go
plugins/inputs/github/github_test.go

Input Plugin: GitHub

---

plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go

Signed-off-by: Robert Sullivan <rsullivan@pivotal.io>

Allow colons in metric names in prometheus_client output

---

docs/DATA_FORMATS_OUTPUT.md
internal/config/config.go
plugins/serializers/registry.go
plugins/serializers/wavefront/README.md
plugins/serializers/wavefront/wavefront.go
plugins/serializers/wavefront/wavefront_test.go

Adds serializer support for Wavefront data format.  Has support for a limited number of settings from the equivalent output plugin.  Settings have a `wavefront_` prefix on them to ensure they will not collide with other settings.
Since serializer settings are still part of internal config, this did require a few changes to some internal packages.

add wavefront serializer plugin

---

plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/kubernetes.go
plugins/inputs/prometheus/prometheus.go

Allow prometheus to operate as a namespaced pod with namespace level permissions. This addresses https://github.com/influxdata/telegraf/issues/5306
- [√] Signed [CLA](https://influxdata.com/community/cla/).
- [√] Associated README.md updated.
- [√] Has appropriate unit tests.

Add optional namespace restriction to prometheus input plugin

---

plugins/inputs/system/README.md
plugins/inputs/system/system.go

Deprecate uptime_format field in system input

---

plugins/inputs/procstat/README.md
plugins/inputs/procstat/process.go
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go

adding cmdline procstat

---

plugins/inputs/influxdb_listener/http_listener.go

Resolves #4935 
This enables the ping endpoint to be compatible with Google Kubernetes
Cloud healthchecks.
See commit: https://github.com/influxdata/influxdb/commit/76fe3f081cad524b2a995612a84ab332d130322b

Change ping endpoint to match influxdb

---

scripts/build.py
scripts/post-install.sh

This change sets the ownership of directories on package generation with fpm instead that in post-install to make `rmp -i` pass.
For more details, see: https://github.com/influxdata/EAR/issues/716

fix(package): make rpm verify pass after installation

---

plugins/inputs/phpfpm/README.md
plugins/inputs/phpfpm/phpfpm.go

Enhance HTTP connection options for phpfpm input plugin

---

docs/CONFIGURATION.md
etc/telegraf.conf
etc/telegraf_windows.conf
internal/config/config.go
plugins/inputs/vsphere/vsphere_test.go

This corrects an out of date description of how the metric buffers work.

Fix docs for metric buffer limit to reflect current behavior

---

scripts/init.sh

In the case that a stale pidfile is found, refuse to start until it has been dealt with by the system administrator.
closes #5730

Don't start telegraf when stale pidfile found

---

README.md

Add **Try in Browser** section in README with the link to the [Telegraf playground](https://rootnroll.com/d/telegraf/) to try it out right in the browser.
https://rootnroll.com is a standalone service for running cli playgrounds.
Source files used to create the Poetry playground: https://github.com/rootnroll/library/tree/master/telegraf/
Automated build of the docker image: https://hub.docker.com/r/rootnroll/demo-telegraf/

Update README: add link to Telegraf playground to try it in browser

---

plugins/inputs/net/net.go

On nodes where there are hundreds of interfaces net plugin can take a very long time to finish.
On my test env for 700 interfaces it takes over 6 seconds to gather stats. With this patch it takes only 0.1 second.

Speed up getting interfaces stats

---

README.md
etc/telegraf.conf
plugins/inputs/all/all.go
plugins/inputs/powerdns_recursor/README.md
plugins/inputs/powerdns_recursor/powerdns_recursor.go
plugins/inputs/powerdns_recursor/powerdns_recursor_test.go

Added a PowerDNS Recursor input plugin.
The PowerDNS plugin does not work for the recursor, as it as some differences.
Not only the command to get the stats is different, but also the socket type (datagram socket for the recursor).
As I also had to add some additional options, it looks better to me to have it in a separate plugin.
Please review the code if it can be merged. If things need to get changed, let me know!
I also get a strange error on make test ... so might need some assistance there!

Add PowerDNS Recursor input plugin

---

plugins/parsers/wavefront/parser.go

The Wavefront parser had some statefulness to it making it panic when receiving heavy traffic from multiple sources. Solved it by moving stateful objects to a separate struct and using a sync.Pool to make sure they are reused but never shared across goroutines.

Fixed race condition in the Wavefront parser

---

plugins/inputs/socket_listener/README.md
plugins/inputs/socket_listener/socket_listener.go

Continuation of the work on #3996.
Renamed the option to socket_mode to match the name in pdns_recursor and only set the mode if set in the configuration file so by default we honor the umask.
closes #3239

Set socket permissions for unix domain sockets

---

scripts/build.py

The Makefile already requires dep to be in the $PATH, which should
include $GOPATH/bin. This change helps in case dep was not compiled
from source but maybe installed from distro packages.

No longer requires dep to be in $GOPATH/bin

---

plugins/inputs/procstat/procstat.go

This PR relates to #5746. When you provide a `pid_file` that exists, has a (int32) number in it of a non-existing process, it will report the process as running right from the start of the agent:
```
> procstat_lookup,host=Kita.local,pid_finder=pgrep,pidfile=/tmp/process.pid,result=success pid_count=1i,result_code=0i,running=1i 1556141065000000000
```
A process is marked running if the [procs map has at least one item](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/procstat.go#L137):
```golang
"running":     len(procs),
```
This map is build/filled by [updateProcesses](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/procstat.go#L284):
```golang
info, ok := prevInfo[pid]
if ok {
procs[pid] = info
}
...
proc, err := p.createProcess(pid) …
```

Check if a process is running using it's name

---

scripts/post-install.sh
scripts/pre-install.sh

fix(package): create telegraf user before install

---

Gopkg.lock
Gopkg.toml

Will return to a tagged release when available, need >3.3.0
closes #5455

Use non-release revision of pgx for pgbouncer fix

---

cmd/telegraf/telegraf.go
internal/usage_windows.go

Add --service-display-name option for use with Windows service

---

plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/influxdb.go

Buffer metrics from failed writes in influxdb2 output if token is invalid

---

cmd/telegraf/telegraf.go
docs/CONFIGURATION.md
internal/config/config.go
internal/rotate/file_writer.go
internal/rotate/file_writer_test.go
logger/logger.go
logger/logger_test.go

Concerns #3393
I took the code from #5547 as a basis and did the following:
- created a reusable rotation-aware file writer
- added additional rotation features (maxsize, maxarchives)
- wrote unit tests. 
This PR uses the new file writer for logging purposes only, but it can be easily plugged in the output file plugin.

Log rotation

---

plugins/inputs/lustre2/lustre2.go
plugins/inputs/lustre2/lustre2_test.go

The current Lustre input plugin will only report jobstats for one job per storage target. This can be tested by running the included tests with the current version of the input plugin. 
With this fix all jobs active on each storage target are recorded.

Fixed an issue in the lustre input polgin with the jobstats only being reporeted for one job per storage target

---

plugins/inputs/ntpq/ntpq.go
plugins/inputs/ntpq/ntpq_test.go

Fix for report of lines with missing refid:
```
+10.0.0.1 16 u 1048 1024 376 15.384 -0.538 0.943
```
I believe this is the actual cause of #1634 based on the error message, which is why I'm removing the test case created for that issue.  The panic from that issue would also no longer occur due to other changes to the plugin since then.

Skip lines with missing refid and other fields

---

internal/internal.go
plugins/parsers/csv/parser.go
plugins/parsers/csv/parser_test.go

Fix parse of unix timestamp with more than ns precision

---

plugins/inputs/interrupts/interrupts.go
plugins/inputs/interrupts/interrupts_test.go

Resolves #5836
Should we also change the case of the newly added cpu as tag to uppercase to match?

Revert field name case in interrupts input

---

docs/LICENSE_OF_DEPENDENCIES.md
etc/telegraf.conf
plugins/inputs/statsd/README.md
plugins/inputs/statsd/datadog.go
plugins/inputs/statsd/datadog_test.go
plugins/inputs/statsd/running_stats.go
plugins/inputs/statsd/statsd.go
plugins/inputs/statsd/statsd_test.go

closes https://github.com/influxdata/telegraf/issues/5224
This adds Datadog events to the Statsd input plugin.

Statsd datadog

---

plugins/inputs/diskio/diskio.go
plugins/inputs/diskio/diskio_linux_test.go

Diskio plugin: make devices glob also match devlinks

---

internal/templating/template.go
internal/templating/template_test.go

Using the length of the slice returned by strings.Split() to count the number of separators in a string is incredibly wasteful and makes for expensive sort operations.  This commit fixes that.
```sh
$ benchcmp base.txt new.txt
benchmark                    old ns/op     new ns/op     delta
BenchmarkTemplateLess-16     180           12.5          -93.06%
benchmark                    old allocs     new allocs     delta
BenchmarkTemplateLess-16     2              0              -100.00%
benchmark                    old bytes     new bytes     delta
BenchmarkTemplateLess-16     192           0             -100.00%
```
N/A
A benchmark was added to identify …

templating: fix templateSpecs.Less()

---

plugins/processors/enum/README.md
plugins/processors/enum/enum.go
plugins/processors/enum/enum_test.go

Support tags in enum processor

---

plugins/outputs/azure_monitor/azure_monitor.go

Use alternate resource-id for virtual machine scale sets.
closes #5819

Fix resource id in virtual machine scale sets with azure_monitor output

---

internal/content_coding.go
internal/content_coding_test.go
plugins/inputs/amqp_consumer/README.md
plugins/inputs/amqp_consumer/amqp_consumer.go
plugins/outputs/amqp/README.md
plugins/outputs/amqp/amqp.go
plugins/outputs/amqp/client.go

Add support for gzip compression to amqp input and output

---

plugins/inputs/amqp_consumer/README.md
plugins/inputs/amqp_consumer/amqp_consumer.go
plugins/outputs/amqp/README.md
plugins/outputs/amqp/amqp.go
plugins/outputs/amqp/client.go

Support passive queue declaration in amqp_consumer

---

plugins/inputs/neptune_apex/README.md
plugins/inputs/neptune_apex/neptune_apex.go
plugins/inputs/neptune_apex/neptune_apex_test.go

closes #5883
- [✓ ] Signed [CLA](https://influxdata.com/community/cla/).
- [✓ ] Associated README.md updated.
- [✓ ] Has appropriate unit tests.

Fixes #5883 Omits power_failed and power_restored when the Apex provides invalid timestamps. Eg: "none"

---

plugins/inputs/sqlserver/sqlserver.go

Moved the  ```defer conn.Close()``` to before ```conn.Ping``` to ensure the connection is cleaned up if Ping fails.
Fixes https://github.com/influxdata/telegraf/issues/3485

Move defered closing of connection

---

plugins/outputs/stackdriver/stackdriver.go

Can you advice on what tests and doc updates you'd like for this change?

Set user agent in all Stackdriver requests

---

plugins/inputs/postfix/README.md

When you did set the u:telegraf:rX acl, the telegraf user has only r-x permissions on the maildrop folder.
Now when the telegraf user wants to send an email, it calls postdrop (which has root:postdrop and 2555/-r-xr-sr-x permissions).
This means that postdrop accesses the maildrop folder with telegraf:postdrop user:group.
Now the user acl is matched, and write access is denied. So telegraf user cannot send any email!
The workaround is to set g:telegraf:rX permissions.
Now when postdrop sends an email, it will match the unix permissions for the postdrop group (which is -wx), and mail will work.
When telegraf postfix plugin accesses the folders, it uses telegraf:telegraf, and matches the g:telegraf:rX permission acl :)
So both things work!

Adjust Postfix docs to have proper setfacl command

---

plugins/inputs/vsphere/endpoint.go

LUN IDs were not correctly mapped to datastore names. The mapping code was using an obsolete mapping table that is no longer populated. Removed the obsolete table and changed to code to using the new version of the mapping table instead.
This fixes issue #5881

Fixed datastore name mapping issue

---

plugins/inputs/smart/smart.go

Remove logs from every `gather` call.

Remove verbose debug logs from smart input

---

plugins/outputs/amqp/amqp.go
plugins/outputs/cloud_pubsub/pubsub.go
plugins/outputs/file/file.go
plugins/outputs/instrumental/instrumental.go
plugins/outputs/kafka/kafka.go
plugins/outputs/kinesis/kinesis.go
plugins/outputs/mqtt/mqtt.go
plugins/outputs/nats/nats.go
plugins/outputs/nsq/nsq.go
plugins/outputs/socket_writer/socket_writer.go
plugins/serializers/influx/influx.go
plugins/serializers/influx/reader.go
plugins/serializers/registry.go

When using the `Serialize()` function to serialize metrics one at a time, sometimes a single metric cannot be serialized.  This if often because the particular Serializer does not support a feature of telegraf.Metric, in the case this PR is addressing the `influx` serializer does not support `+Inf` floats.
I considered having the serializer `return nil, nil`, but decided against it because this would require users to check both the error and the buffer before writing the metric.  Another option would be to return a sentinel error value that could be used to ignore, I think this may be a good method but I opted to not introduce any new types at this time.
closes #5858

Ignore errors serializing metrics

---

internal/config/config.go
plugins/outputs/file/README.md
plugins/outputs/file/file.go

Added support for the reamining file rotations options available to the agent, and aligned the option naming.
related: #5547

Add support for remaining file rotation options

---

plugins/inputs/hddtemp/README.md
plugins/inputs/hddtemp/hddtemp.go
plugins/inputs/hddtemp/hddtemp_test.go

Add source tag to hddtemp plugin

---

plugins/serializers/wavefront/wavefront.go
plugins/serializers/wavefront/wavefront_test.go

This PR improves the performance and memory consumption of the Wavefront serializer by roughly 30%.
```
benchmark                 old ns/op     new ns/op     delta
BenchmarkSerialize-16     1168          778           -33.39%
benchmark                 old allocs     new allocs     delta
BenchmarkSerialize-16     16             8              -50.00%
benchmark                 old bytes     new bytes     delta
BenchmarkSerialize-16     1116          800           -28.32%
```

wavefront/serializer: improve performance by ~30%

---

plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go

Fixes #5983.
Passing configured subscriptions paths through the same parser as incoming paths when creating aliases. This should make sure they match up.

Omit keys when creating measurement names for GNMI telemetry

---

plugins/outputs/http/README.md
plugins/outputs/http/http.go

Default URL matches the http_listener_v2 input.

Add default url for http output

---

plugins/inputs/procstat/procstat.go

Attempt at fixing #5300. Not sure if using an OR statement or writing a separate if was a better practice. Since both check for valid PIDs I used an OR statement.
Also I tested this on golang and know almost nothing of GO, so there might be better ways to write this.

Fix pid_count with systemd_unit in procstat_lookup

---

agent/agent.go
cmd/telegraf/telegraf.go
internal/usage.go
internal/usage_windows.go

Some plugins use the Start/Stop functions for setup/teardown but are still polling based inputs at heart.  With this change you won't have to choose to between having `--test` support and using these functions.
I Added a new option, `--test-wait`, which is the number of seconds to pause after running Gather.  The default is 0 and so Telegraf exits immediately.  This can be set higher to, for example, run socket_listener for a few minutes.
Call flow is:
- Start
- Gather
- Wait
- Stop
This pull request does have some important limitations.  The Gather function is only called once instead of on an interval.  Service inputs that use the Gather function, such as statsd, may not behave normally.  In the statsd case it will not emit any metrics.
When using `--test` with a queue consumer, …

Run ServiceInputs during test mode; add --test-wait option

---

plugins/processors/all/all.go
plugins/processors/date/README.md
plugins/processors/date/date.go
plugins/processors/date/date_test.go

Adds Date Processor Plugin

---

plugins/parsers/graphite/parser.go

The commit reduces the amount of memory used by `GraphiteParser.Parse()` by 80% and increases performance by 30%.  Honestly, this would be more efficient if we stepped through `buf` line-by-line but this improvement is good enough to justify a PR.
```
benchmark             old ns/op     new ns/op     delta
BenchmarkParse-16     1825          1235          -32.33%
benchmark             old allocs     new allocs     delta
BenchmarkParse-16     24             20             -16.67%
benchmark             old bytes     new bytes     delta
BenchmarkParse-16     5200          896           -82.77%
```
Also, this codebase and in particular anything on the statsd …

graphite: reduce the memory used by GraphiteParser.Parse() by ~80%

---

agent/agent.go
docs/AGGREGATORS.md
docs/INPUTS.md
docs/OUTPUTS.md
docs/PROCESSORS.md
input.go
internal/models/running_aggregator.go
internal/models/running_input.go
internal/models/running_output.go
internal/models/running_processor.go
plugins/inputs/http/http.go
plugins/inputs/http/http_test.go

Add call to optional Init function for all plugins

---

plugins/processors/regex/README.md
plugins/processors/regex/regex.go
plugins/processors/regex/regex_test.go

This change allows to mix values from different tags.
When regexp is used to transform a tag, if value `append` is set to
`true` and we the `result_key` tag already exists, replacement value
will be appended to the end of the current tag value.
Example use case, set `host` tag with the values of tags `clustername` and `dcname`:
Input:
```
vsphere_cluster_vmop,clustername=somecluster,dcname=mydc,host=xxxx numPoweron_latest=27i 1557967800000000000
```
Processor config:
```
[[processors.regex]]
[[processors.regex.tags]]
key = "clustername"
pattern = "^(.*)"
replacement = "${1}"
result_key = "host"
[[processors.regex.tags]]
key = "dcname"
pattern = "^(.*)"
replacement = "_${1}"
result_key = "host"
append = true
```
Output:
```
vsphere_cluster_vmop,clustername=somecluster,dcname=mydc,host=somec …
```

Allow regexp processor to mix different tags

---

metric/metric.go
plugins/processors/all/all.go
plugins/processors/pivot/README.md
plugins/processors/pivot/pivot.go
plugins/processors/pivot/pivot_test.go
plugins/processors/unpivot/README.md
plugins/processors/unpivot/unpivot.go
plugins/processors/unpivot/unpivot_test.go

Adds two processors, one for "pivot" and one for "unpivot".  Ideally, we would also have an aggregator for combining pivoted metrics into a single line.
closes #5629

Add pivot and unpivot processors

---

plugins/inputs/phpfpm/phpfpm.go
plugins/inputs/phpfpm/phpfpm_test.go

"start since" was missing from the exported php-fpm metrics.
Lets have it added :)

Add starttime to php-fpm metrics

---

plugins/inputs/elasticsearch/elasticsearch.go
plugins/inputs/elasticsearch/elasticsearch_test.go
plugins/inputs/elasticsearch/testdata_test.go

Add missing metric in ElasticSearch

---

plugins/inputs/all/all.go
plugins/inputs/docker_log/README.md
plugins/inputs/docker_log/client.go
plugins/inputs/docker_log/docker_logs.go

Resolves #1483 
This PR introduces a telegraf plugin to get docker logs . Sample output : 
`
docker_log,containerId=168c940a98b4317de15e336140bf6caae009c1ea948226d7fac84c839ccf6e6d,containerName=loving_leavitt,host=prash-laptop log=" root@168c940a98b4:/# ls\r\n" 1538210547000000000
docker_log,containerId=168c940a98b4317de15e336140bf6caae009c1ea948226d7fac84c839ccf6e6d,containerName=loving_leavitt,host=prash-laptop log=" bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var\r\n" 1538210547000000000
docker_log,containerId=168c940a98b4317de15e336140bf6caae009c1ea948226d7fac84c839ccf6e6d,containerName=loving_leavitt,host=prash-laptop log=" root@168c940a98b4:/# pwd\r\n /\r\n" 1538210552000000000
`
The plugin is a Telegraf service input plugin …

Docker log plugin

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

This is an attempt to implement the `interface` field in the `http_response` input plugin.
The `interface` field can be populated with an interface name such as `eth0`. A local address associated with the network interface will be derived and used for dialing.
Resolves: https://github.com/influxdata/telegraf/issues/5856

Add support for interface field in http_response input plugin

---

plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go

Closes #5807
Currently, this plugin tries a set of hardcoded paths.  Not all paths are enabled in a standard NGINX configuration.
This PR skips any API resource paths that do not exist.
However, the correct way would be to get the paths from NGINX itself at /api, /api/4, etc rather than have a set
of hardcoded paths.

fix(inputs/nginx_plus_api): swallow 404 error reporting

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/docker_testdata.go

:wave:
This change introduces the `uptime_ns` field for the `docker_container_status` metric. This was a little low hanging fruit I thought I could take a stab at for a first contribution. As it was requested a long time ago, I imagine it might not even be desired anymore.
Resolves https://github.com/influxdata/telegraf/issues/3184

Container Uptime in Docker Input Plugin

---

plugins/inputs/docker/docker.go
plugins/inputs/docker/errors.go

Closes #2233 
Each client interaction with the Docker server may have a timeout.  Rather than return `context.DeadlineExceeded` as the error, this translates into a more clear error message.
I fixed up various linter problems as well as make the error messages more consistent.

feat(inputs/docker): add better user-facing errors for API timeouts

---

plugins/inputs/pgbouncer/pgbouncer.go

This column is not available in pgbouncer 1.5
closes #5999

Fix panic if pool_mode column does not exist

---

plugins/inputs/sysstat/sysstat.go
plugins/inputs/sysstat/sysstat_test.go

Fix double pct replacement in sysstat input

---

etc/telegraf.conf
plugins/inputs/jti_openconfig_telemetry/README.md
plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go

Adding TLS mutual auth supoort to jti_openconfig_telemetry plugin

---

plugins/inputs/ping/ping.go

-s is packet size, -S is source.

inputs.ping Wrong ping flag on BSD

---

docker-compose.yml
plugins/outputs/elasticsearch/README.md
plugins/outputs/elasticsearch/elasticsearch.go

This PR adapts the index template to work on versions 6.x and 7.x while still supporting 5.x
Also it removes the mapping type on ES 7.x as mapping types are deprecated. Telegraf still sets the mapping type to "metrics" to keep backwards compatibility on previous ES versions.
Tested manually on versions 5.6, 6.0, 6.8 and 7.2
closes #5780
closes #4268

Elasticsearch output - Add support up to ES 7.x

---

plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/prometheus.go

Add basic auth to prometheus input plugin

---

plugins/inputs/bind/bind_test.go
plugins/inputs/bind/json_stats.go
plugins/inputs/bind/xml_stats_v2.go
plugins/inputs/bind/xml_stats_v3.go

Use int64 for fields in bind plugin

---

internal/globpath/globpath.go
internal/globpath/globpath_test.go

Fixes no metrics produced when forward slash is used in the config file for the path in Windows.

Fix path separator matching in filecount input

---

plugins/inputs/logparser/logparser.go
plugins/inputs/tail/tail.go

This is discussed further on https://github.com/influxdata/tail/pull/6.  In short, over time the Cleanup call has been broken and shouldn't be used since it decrements the reference count unconditionally.
closes: #3573
https://github.com/hpcloud/tail/issues/153

Remove tail cleanup call to avoid double decrement

---

plugins/inputs/activemq/README.md
plugins/inputs/activemq/activemq.go
plugins/inputs/activemq/activemq_test.go

Needed to provide a way to select between `http` and `https`.  While I was tempted to go with an `enable_tls = true` option, I instead went for a new `url` option that combines the scheme, host and port.  This is more similar to how we handle other HTTP inputs.
I will have to do some minor changes to apply this to the release branch, since it uses the new Init function.
closes #6076

Fix https support in activemq input.

---

plugins/inputs/nvidia_smi/README.md
plugins/inputs/nvidia_smi/nvidia_smi.go
plugins/inputs/nvidia_smi/nvidia_smi_test.go

Very sad to see this issue from nvidia-smi. Without this fix all of the stats from this plugin fail to be written out and a continuous stream of this log is written until the memory clock value is <= the stock value: `2019-07-05T09:04:30Z E! [inputs.nvidia_smi]: Error in plugin: strconv.ParseInt: parsing "[Unknown Error]": invalid syntax`

Handle edge case where we're unable to get data due to limitations of nvidia-smi

---

plugins/outputs/kafka/kafka.go

This is a little messier than I would like, we can't be specific about if these messages come from the input or the output as sarama has only a single global logger.
related: #6072

Emit sarama library log messages at debug level

---

plugins/inputs/logparser/logparser.go
plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go

* Fixes #3522 - Not able to read rotated log file without missing lines
* ~Fixes #3573 - logparser/tail plugin stop after reload (removes unnecessary tailer.Cleanup() calls)~
I did not write a unit test for this, but I did test externally:
```toml
[agent]
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "600ms"
flush_jitter = "0s"
precision = ""
debug = false
quiet = false
logfile = ""
hostname = ""
omit_hostname = true
[global_tags]
[[outputs.file]]
files = ["stdout"]
data_format = "influx"
[[inputs.tail]]
files = ["/spare/local/tmp/mymetrics.out"]
from_beginning = false
watch_method = "notify"
data_format = "influx"
```
```bash
#!/bin/bash
counter=1
until [ $counter -gt 150 ]; do
if [ $counter -eq 75 ]; …
```

[tail/logparser] resume from last known offset when reloading

---

plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go

As is the SQL Plugin doesn't lend itself to Azure SQL Database.
- ServerName is a logical construct on Azure SQL Database, added Database name to all collectors to be able to filter
- Added Resource governance collection for Managed instance and Azure SQL Database collected if the AzureDB flag is enabled in telegraf.conf
- Added waitstats collection against sys.dm_db_wait_stats if the it is Azure SQL DB instead of server level waits.
- Will Publish grafana reports specific to Azure SQL DB separately.

Adding/fixing support for Azure SQL Database (singleton database)

---

.gitignore
plugins/inputs/smart/smart.go
plugins/inputs/smart/smart_test.go

This PR attempts to deliver most of https://github.com/influxdata/telegraf/issues/6041
Currently this PR supports:
Outstanding Questions:
1. Documentation for smart attributes seem to be a little elusive to me. Can anyone point me in the direction of the attributes id's for all the above attributes. Perhaps you know @coccobill1 ?
2. `Critical Warning` appears to be a bit flag printed as a hex value. I have struggled to find decent documentation around the meaning of all these attributes. Maybe someone can point me in the best direction of better docs. I have this https://www.intel.com/content/dam/support/us/en/documents/solid-state-drives/Intel_SSD_Smart_Attrib_for_PCIe.pdf for example.
Given we know the definitive meaning (and that there is one) for what each flag means, do we have any …

Smart Input Plugin Extra Attributes

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/docker_testdata.go

Closes https://github.com/influxdata/telegraf/issues/5758
This adds a new measurement `docker_thin_pool` with the field `minimum_free_space` measured in bytes.

Docker Input Plugin Measure Thin Pool Minimum Free Space

---

plugins/inputs/sqlserver/sqlserver.go

As part of [https://github.com/influxdata/telegraf/pull/6111](url) ,  had added resource governance related info, and had not tested with SQL Managed instance with a  public endpoint. This is a minor change Required to match up server names later in dashboard. Also golang SQL driver was throwing an error for MI  worked around it by aliasing the columns.

@@servername change otherwise breaks MI with public endpoint

---

plugins/inputs/elasticsearch/README.md
plugins/inputs/elasticsearch/elasticsearch.go

Add basic auth support to elasticsearch input

---

Gopkg.lock

This allows the new multipath syntax.
closes #6097

Compile with gjson 1.3.0

---

plugins/parsers/json/README.md
plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go
plugins/parsers/registry.go

Support string field glob matching in json parser

---

plugins/inputs/statsd/datadog_test.go
plugins/inputs/statsd/statsd.go

Fixes the folllowing panic that is caused by sending a Datadog event to the StatsD input
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1747ff7]
goroutine 12 [running]:
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).parseEventMessage(0xc0001b8380, 0xbf434fd5f15bd546, 0xd7be3d60, 0x4554680, 0xc000286380, 0x3a, 0xc00
04b8060, 0x9, 0x1, 0x0)
/go/src/github.com/influxdata/telegraf/plugins/inputs/statsd/datadog.go:136 +0x10a7
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).parser(0xc0001b8380, 0x2695778, 0xc0001b8408)
/go/src/github.com/influxdata/telegraf/plugins/inputs/statsd/statsd.go:502 +0x2fd
github.com/influxdata/telegraf/plugins/inputs/statsd.(*Statsd).Start.func4( …
```

Fix Statsd input panic when processing DataDog events

---

plugins/inputs/lustre2/lustre2.go
plugins/inputs/lustre2/lustre2_test.go

This closes https://github.com/influxdata/telegraf/issues/6107
PR contains a test definition to capture the regression scenario and an associated fix.
Oustanding question:
Was there a desire to parse these new `ost_jobstat` and `mds_jobstat` fields also? Do we need to support those field names as aliases?

Fix lustre2 input plugin config parse regression

---

internal/templating/engine_test.go
internal/templating/node.go

Closes: https://github.com/influxdata/telegraf/issues/5894
This fixes an issue within templating rules used by line formats like the graphite format. The templating rules do not exhaustively explore all matches. The moment a match is found at any level, if the search fails to match the filters children it will bail out and return a nil template (which gets replace by teh caller with a default template).
Instead the template should return to the previous successful match and check to see if a wildcard exists which can also be explored.

Fix templating patterns wildcard matching

---

plugins/processors/strings/README.md
plugins/processors/strings/strings.go
plugins/processors/strings/strings_test.go

Resolves #5928 
This enables the string processor to work on tag and field keys with the config additions of `tag_key` and `field_key`.
**Config**
```toml
[[processors.strings]]
[[processors.strings.lowercase]]
tag_key = "URI-Stem"
[[processors.strings.replace]]
tag_key = "uri-stem"
old = "-"
new = "_"
```
**Input**
```
iis_log,URI-Stem=/API/HealthCheck http_version=1.1 1519652321000000000
```
**Output**
```
iis_log,uri_stem=/API/HealthCheck,URI-Stem=/API/HealthCheck http_version=1.1 1519652321000000000
```
Try it here:
<ul>
<li><details><summary>linux/</summary><ul>
<li><details><summary>amd64</summary><ul>
<li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf">telegraf</a></li>
<li><a href="https://36784-33258973-gh.circle-artifacts.com/0/build/linux/am …

Add support for field/tag keys to strings processor

---

plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go

Pull request to satisfy this - [https://github.com/influxdata/telegraf/issues/6140 ]
Added support to collect requests and important fields to identify blocking.

Adding support for collecting SQL Requests to identify  blocking

---

plugins/inputs/x509_cert/README.md
plugins/inputs/x509_cert/dev/telegraf.conf
plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

Resolves #4877 
This always sets `insecure_skip_verify` as it verifies the cert once it's been collected/parsed.
To verify a self-signed cert (remote endpoint or file), set the `tls_ca` to the self-signing ca, or the self-signed cert itself for validation to be successful.
Alternate to #6139

Add certificate verification status to x509_cert input

---

plugins/inputs/docker_log/docker_log.go

Closes: https://github.com/influxdata/telegraf/issues/6146
This is required in order for the docker_logs input plugin to be treated as a service input. Rather than just a regular input. This ensures that Stop is called and that the input channel within the accumulator is not closed before all the logs calls have exited and have stopped sending on the it.

Add Start() function to DockerLogs input plugin

---

plugins/inputs/github/README.md
plugins/inputs/github/github.go
plugins/inputs/github/github_test.go

This adds networks, subscribers, and watchers as fields.
According to [github's api docs](https://developer.github.com/v3/repos/#list-organization-repositories), forks_count is indeed different than network_count.

Add networks, subscribers, and watchers to github input

---

plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

Percentage values would get interpreted incorrectly as tags because they
did not pass the int/float conversion.

redis input: fix percentage value parsing

---

cmd/telegraf/telegraf.go
internal/usage.go

Original patch written by sparrc, brought up to date by timidger.
Original from 92d8a2e5ea2846a34ba8c90a67606b9708aa5eb0 message follows:
support for the Go 1.8 shared object feature of loading external
plugins.
this support relies on the developer defining a `Plugin` symbol in their
.so file that is a telegraf plugin interface.
So instead of the plugin developer "Adding" their own plugin to the
telegraf registry, telegraf loads the .so, looks up the Plugin symbol,
and then adds it if it finds it.
The name of the plugin is determined by telegraf, and is namespaced
based on the filename and path.
see #1717
Since this adding a new capability to inject plugins I wasn't sure where to document this or how to test this. So looking for feed back on how to do those things :smile:

Load external .so plugins, fixes #1717

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/http.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/influxdb_v2/README.md
plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/influxdb.go

 Add ability to exclude db/bucket tag from influxdb outputs

---

plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go

This is a requirement of using sarama's consumer groups in #6172.
We could add a switch that could fallback to the old sarama-cluster code to avoid this, but I want to see what kind of feedback we get.
closes #6136

Require Kafka 0.10.2.0 or later in kafka_consumer

---

etc/telegraf.conf
plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongostat.go

This PR add Mongodb input plugin per collection stats gathering.
It will discover collection in each database.
You can specify the databases you want to gather collection stats by setting the `col_stats_db` option.
```
```
New metrics per collections are :
mongodb_col_stats
- tags:
- hostname
- collection
- db_name
- fields:
- size (integer)
- avg_obj_size (integer)
- storage_size (integer)
- total_index_size (integer)
- ok (integer)
- count (integer)
- type (tring)
Related Issue : https://github.com/influxdata/telegraf/issues/5496

Gather per collections stats in mongodb input plugin

---

docs/CONFIGURATION.md
internal/config/config.go
internal/models/running_aggregator.go
internal/models/running_aggregator_test.go

This addresses a use-case when it's expected that some metrics will be late for aggregation (i.e. outside of the aggregation period) and `delay` doesn't allow to account for these. For example when timestamped metrics are submitted by an application using the _http_listener_ input and they're more than a full period late.
Setting the `grace` parameter allows these metrics to still be passed to the aggregator plugin for a certain duration.

Grace period for metrics late for aggregation

---

plugins/processors/strings/README.md
plugins/processors/strings/strings.go
plugins/processors/strings/strings_test.go

closes: https://github.com/influxdata/telegraf/issues/5877

adding left string function

---

plugins/inputs/github/README.md
plugins/inputs/github/github.go
plugins/inputs/github/github_test.go

https://github.com/influxdata/telegraf/issues/6162

Add support for Enterprise repos in Github plugin

---

plugins/inputs/nats_consumer/README.md
plugins/inputs/nats_consumer/nats_consumer.go

Basic changes to add missing TLS & credentials options for NATS. Mutual TLS is supported too.

Added TLS & credentials configuration for NATS_consumer input plugin

---

plugins/inputs/kubernetes/kubernetes.go
plugins/inputs/kubernetes/kubernetes_test.go

Fixed misspelled field name `logsfs_available_bytes`

logsfs available bytes fix

---

plugins/outputs/datadog/datadog.go
plugins/outputs/datadog/datadog_test.go

Skip floats that are NaN or Inf in Datadog output.

---

plugins/inputs/system/README.md
plugins/inputs/system/system.go

runtime.NumCPU() return the number of logical CPUs at the startup of the
process, https://golang.org/pkg/runtime/#NumCPU.
gopsutil return the current number of CPUs, giving the correct number
when CPU hot un/plug are being done.
closes #5451

Get the number of logcal CPUs dynamically

---

plugins/inputs/internal/README.md
plugins/inputs/internal/internal.go
plugins/inputs/internal/internal_test.go

Collecting telegraf version is useful to find outdated agents and match
behavioural changes with version changes.
closes #5958

Add telegraf and go version to the internal input plugin

---

plugins/outputs/elasticsearch/README.md

I added futher explaination for which role you need to add if you wish to use a service account inside your Elasticsearch cluster.
Maybe there is a better way to explaine this, and there is maybe some typo errors.

Update Elaticsearch Output Plugin README.md

---

plugins/inputs/smart/README.md
plugins/inputs/smart/smart.go
plugins/inputs/smart/smart_test.go

Fix for https://github.com/influxdata/telegraf/issues/6240.
This change makes the SMART timeout a configuration parameter, and bumps the default value from 5s to 30s.
- Previous behavior: measurements are dropped when the HDD is under heavy load.
- Current behavior: measurements are delayed (5-10s on my system) but not dropped.

Made the SMART timeout a parameter, and set the default to 30s

---

plugins/inputs/procstat/process.go
plugins/inputs/procstat/procstat.go
plugins/inputs/procstat/procstat_test.go

I needed it and [gopsutils](https://github.com/shirou/gopsutil/blob/master/process/process.go#L222-L241) already provides it.

Add memory_usage (percent) field to procstat input plugin

---

README.md
scripts/build.py

Closes #4801
This will build a darwin tar.gz package for macOS.  This allows people an easy way to download
releases from github directly.

feat(scripts): add darwin (macOS) builds to the release

---

Gopkg.lock

This version primarily contains authentication fixes.

Update github.com/go-sql-driver/mysql to 1.4.1

---

plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go

Use new-ish SessionPresent function to determine if we need to resubscribe and add routes so that persisted messages can be delivered.
closes #6232

Fix persistent session in mqtt_consumer.

---

agent/agent.go

A couple notes:
1. I added a separate `--test-status` option to `telegraf` to implement this. I did this to maintain backwards compatibility in case anyone is depending on the current behavior of always returning 0.
2. The exec plugin was always returning no error. I fixed this plugin since we are using it. It is possible other plugins are also not correctly returning any errors.
closes: #6278

Fix issue #6278

---

plugins/inputs/influxdb_listener/README.md
plugins/inputs/influxdb_listener/http_listener.go
plugins/inputs/influxdb_listener/http_listener_test.go

Updating to allow the users to keep the database that gets sent in the query string. See issue #6253
Adding a test for the code change
Adding new configuration to the README.
Adding toml tags to make it like the rest of the plugins.

Allow influxdb_listener to keep the database name from the query string if supplied

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

Added content_length metric to http_responce input plugin according to feature request #6037 
closes #6037

Add content_length metric to http_response input plugin (#6037)

---

plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

Capture and parse the cmdstat timings from `INFO ALL` command

---

plugins/inputs/mqtt_consumer/README.md
plugins/inputs/mqtt_consumer/mqtt_consumer.go
plugins/inputs/mqtt_consumer/mqtt_consumer_test.go

Add a new option `topic_tag` to the mqtt_consumer input.  When unset the default is `topic` in order to preserve backwards compatibility, when set to `""` no topic tag is added, otherwise the value is used for the topic tag.  This is the basic pattern I would like to use for all inputs with parsers and want to add metadata.
In 2.0 we should change the default to not add the topic tag.  We don't have a mechanism for changing the defaults yet, this is something that needs a plan.
closes: #6262

Add topic_tag option to mqtt_consumer

---

etc/telegraf_windows.conf
plugins/inputs/win_perf_counters/win_perf_counters.go

Remove extra percent from win_perf_counters sample config and have it
mirror the config provided in the Windows package.
closes #5823

Update win_perf_counters sample config

---

plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go

This is a quick fix for parsing multiple metrics on the first line of a file without breaking the special csv behavior.  #6160 will fix this in a better way, but needs changes around performance and reporting errors during construction first.
closes #6138

Fix parsing multiple metrics on the first line of tailed file

---

.gitignore
plugins/inputs/all/all.go
plugins/inputs/logstash/README.md
plugins/inputs/logstash/logstash.go
plugins/inputs/logstash/logstash_test.go
plugins/inputs/logstash/samples_logstash5.go
plugins/inputs/logstash/samples_logstash6.go

Add the input plugin to fetch metrics from the Logstash HTTP endpoints.
Both version 5 and 6 are supported.
Fetching process, jvm, events and plugins metrics.
Original developer:
* https://github.com/lkmcs/telegraf
Contributors:
* https://github.com/arkady-emelyanov/telegraf
* https://github.com/dmitryilyin/telegraf

Add Logstash input plugin (both version 5 and 6 support)

---

plugins/inputs/nginx_plus/nginx_plus.go
plugins/inputs/nginx_plus_api/nginx_plus_api.go
plugins/inputs/nginx_vts/nginx_vts.go

Add TLS support to nginx_plus, nginx_plus_api and nginx_vts

---

Gopkg.lock
plugins/inputs/all/all.go
plugins/inputs/marklogic/README.md
plugins/inputs/marklogic/marklogic.go
plugins/inputs/marklogic/marklogic_test.go

- [] Signed [CLA](https://influxdata.com/community/cla/).
This is a new input plugin for monitoring the Marklogic Databases using their Management API. The plugin requires the "Digest Authentication" as that is the default method for MarklogicDB.
[TAGS]
"ml_hostname"
"id"
[FIELDS]
"online"                          
"total_cpu_stat_user"               
"total_cpu_stat_system"           
"memory_process_size"             
"memory_process_rss"
"memory_system_total"
"memory_system_free":                 
"num_cores"
"total_load"                        
"data_dir_space"
"query_read_bytes"
"query_read_load"                    
"http_server_receive_bytes"
"http_server_send_bytes":             
Go-Libraray for Digest Auth Support:
xinsnake/go-http-digest-auth-client
Marklogic Documentation …

Marklogic Input Plugin

---

plugins/inputs/iptables/iptables.go

Split out -w argument in iptables input

---

cmd/telegraf/telegraf.go
docs/CONFIGURATION.md
docs/WINDOWS_SERVICE.md
internal/config/config.go
logger/event_logger.go
logger/event_logger_test.go
logger/logger.go
logger/logger_test.go

In startup phase where there is not logging set yet, reports errors to OS event source (event viewer on windows). Helps debugging #4235

Telegraf startup error reporting improvement

---

Gopkg.lock
Gopkg.toml

The newer sarama library uses CGO for it's zstd compression.  Telegraf does not support enabling zstd compression currently, so it is safe to remove.  This avoids the build requiring GLIBC_2.14, but we may want to make further changes to the build to avoid linking newer symbol versions.
Changes against sarama 1.23.1: https://github.com/influxdata/sarama/commit/b12709e6ca29240128c89fe0b30b6a76be42b457
closes #6344

Switch to fork of sarama without zstd dependency

---

plugins/inputs/kafka_consumer/kafka_consumer.go

Fix could not mark message delivered error in kafka_consumer

---

plugins/inputs/icinga2/icinga2.go
plugins/inputs/icinga2/icinga2_test.go

Parse state into a float64 and then convert to and int later, to support numbers with a decimal component in the response body.  It is unknown if icinga ever returns a number without a decimal but this will work in either case.
closes #6331

Convert check state to an integer

---

plugins/inputs/filecount/filecount.go
plugins/inputs/filecount/filecount_test.go

Paths returned during the walk have had filepath.Clean applied to them, so we need to create a glob that will match these cleaned paths.
closes #6329

Fix filecount for paths with trailing slash

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go
plugins/inputs/mongodb/mongodb_server.go
plugins/inputs/mongodb/mongostat.go

In addition to fixing the `gather_col_stats` option, this sets the default list of collection stat databases to the documented value.  This avoids errors reading the collections in the admin database that the documented role does not have permission to read.
closes #6362

Skip collection stats when disabled

---

plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

Since we were not using the sigil error in CheckRedirect, an error was set and the response body closed.  However since redirects don't return from the error condition, there were follow on errors later reading the response body.  With the `http.ErrUseLastResponse` error we can simplify this a bit and the response body will not be closed.
Removed test used knowledge of the prior behavior to inject a read error, this method will no longer work and will require larger refactoring to reintroduce the case.
close #6366

Fix error reading closed response body on redirect

---

plugins/outputs/influxdb_v2/http.go

Return error rather than set a zero "retry after" value

---

internal/internal.go
internal/internal_test.go
plugins/parsers/csv/parser.go
plugins/parsers/json/parser.go

Fix detection of layout timestamps

---

plugins/inputs/kube_inventory/README.md
plugins/inputs/kubernetes/README.md

Our [tick-charts](https://github.com/influxdata/tick-charts) repository is not maintained. It has been decided that we should adopt the upstream Helm Stable repositories and support them as much as we can.
[Internal Issue](https://github.com/influxdata/devrel-team/issues/30)

Recommend Installing TICK Stack with Helm Stable Charts

---

cmd/telegraf/telegraf.go
internal/goplugin/noplugin.go
internal/goplugin/plugin.go

It has come to my attention that the Go plugin support added in #6024 had an unexpected and hefty cost in terms of binary size, to the tune of about 19MB.
Despite this feature been released in 1.12, I propose we add a build flag and disable it on official Telegraf builds.  Based on my testing of this feature, it is quite difficult to get plugins working without building the plugin and Telegraf together on the same host, and the extra binary size is just too much for a feature that will be rarely used.
To build with Go plugin support add `-tags goplugin` to the build command:
```
go build -tags goplugin -ldflags "-w -s -X main.commit=9e3f918d -X main.branch=HEAD" ./cmd/telegraf
```

Require goplugin build flag to enable go plugin support

---

plugins/parsers/grok/parser.go
plugins/parsers/grok/parser_test.go

Allow alternate base when grok parsing ints.

---

plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go

This addresses three issues in the GNMI plugin:
- Measurement names (aliases) are correctly generated for replies where the origin field is empty even though the request contained a non-empty origin. (This may fix https://github.com/influxdata/telegraf/issues/6391 but I cannot verify it for this platform, however it addresses the same issue with a device of a different platform I have access to).
- It prevents Telegraf from crashing when a field has no value or one of a deprecated type.
- It skips path elements with empty names instead of adding additional '/' to fields.

GNMI: Improve platform compatibility and corner case handling

---

plugins/outputs/exec/exec.go

Solves #6445
When the exec output serialises the metrics it does it one by one and writes it to the buffer. Error checking is done on the serialising but not the writing into the buffer. So there is no reason to not use the batch serialiser.
When developing against the output exec I expected the output to follow the rules of the data format that I specified. For my use case I am using JSON and expected a list of metrics but was unfortunately greeted with a multiple lines of single metrics, making it extremely difficult to render the metrics again.
Sample of bad output:
```json
{"fields":{"bytes_recv":0,"bytes_sent":0,"drop_in":0,"drop_out":0,"err_in":0,"err_out":0,"packets_recv":0,"packets_sent":0},"name":"net","tags":{"host":"pickle","interface":"br-0ac7079a5349"},"timestamp":156941841700 …
```

Change the Exec output to use BatchSerialize()

---

plugins/aggregators/all/all.go
plugins/aggregators/merge/README.md
plugins/aggregators/merge/merge.go
plugins/aggregators/merge/merge_test.go

This plugin merges single field metrics into the fewest number of lines possible.
```diff
- cpu,host=localhost usage_time=42 1567562620000000000
- cpu,host=localhost idle_time=42 1567562620000000000
+ cpu,host=localhost idle_time=42,usage_time=42 1567562620000000000
```

Add merge aggregator

---

plugins/inputs/smart/smart.go

Smartctl output for HGST disk drives for serial number does not capitalise second word (number). 
```
Serial number:        0SY4UP5A
```
Therefore in order to make this regex match different vendors it should be case insensitive.

Add case insensitivity to serial numer matching

---

plugins/inputs/sqlserver/sqlserver.go

This change will add some previously removed "Batch Response Statistics" back, and also add a few more metrics around Availability Group performance.

More metrics for SQL Server plugin

---

internal/config/config.go

Adding an `Authorization: Token <token>` header causes 404 errors with GitHub when using the raw content URI.
This fix only adds the header when the token is available, allowing for public configs to be loaded correctly.
You can test this with:
`telegraf --config https://raw.githubusercontent.com/influxdata/telegraf/master/etc/telegraf.conf`
To see the HTTP behaviour without Telegraf:
Returns 404:
`curl -X GET -H "Authorization: Token ABC" -H "Accept: application/toml" -I https://raw.githubusercontent.com/influxdata/telegraf/master/etc/telegraf.conf`
Returns 200
curl -X GET -H "Accept: application/toml" -I https://raw.githubusercontent.com/influxdata/telegraf/master/etc/telegraf.conf

fix(config): allow remote config with no auth

---

.github/workflows/main.yml

This installs and configures a github action which looks up our CLA spreadsheet using the PR authors github username. It ensures the username is present. If it is not, it fails the action.

Install and configure CLAsee

---

plugins/inputs/mysql/mysql.go
plugins/inputs/mysql/mysql_test.go
plugins/inputs/sqlserver/sqlserver.go
plugins/inputs/sqlserver/sqlserver_test.go

The current implementations of mysql and sqlserver input plugins don't support running multiple times with different configurations because they use shared package level vars
I've just revised the package level var's to either declare them as const's or move them into the instance struct.  Also added tests, both integration and unit, that correspond to those changes.

Remove shared package level vars from sqlserver and mysql input plugins

---

plugins/outputs/influxdb/http.go
plugins/outputs/influxdb/http_test.go
plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/http_test.go

Fix database routing on retry with exclude_database_tag

---

internal/config/config_test.go
plugins/inputs/exec/exec.go
plugins/inputs/exec/exec_test.go

Fix logger initialization in exec input

---

plugins/inputs/docker/README.md
plugins/inputs/docker/docker.go
plugins/inputs/docker/docker_test.go
plugins/inputs/docker_log/README.md
plugins/inputs/docker_log/docker_log.go
plugins/inputs/docker_log/docker_log_test.go

Solves #6472
I'm not 100% sure of the config value name `container_id_as_hostname`, I'm happy to take some guidance on this.
This PR allows the user to set a config value to tag all measurements gathered by this plugin with the container_id, stripped down to the common hostname value.
It sets this in the `host` tag which telegraf expects to be set and will set itself if its not already set. This allows for backwards comparability with the current behaviour.

Containers can now be identified by the container ID

---

plugins/processors/enum/README.md
plugins/processors/enum/enum_test.go

Clarify behaviour of enum processor without default or defined mapping

---

plugins/processors/clone/README.md
plugins/processors/clone/clone.go
plugins/processors/clone/clone_test.go

Add an option to keep the original metric and modify the a copy of the
metric.
This allows "multiplexing" of metrics, having one input, generate
metrics for multiple hosts.
Example:
```
[[inputs.kernel]]
[[processors.override]]
clone = true
[processors.override.tags]
host = "virtualHost"
```

Clone processor

---

plugins/inputs/zookeeper/README.md

They dont seem to use "trunk" anymore, changed to "current"

Fix doc-link

---

etc/telegraf.conf
plugins/inputs/http/README.md
plugins/inputs/http/http.go
plugins/inputs/http/http_test.go

Fixes https://github.com/influxdata/telegraf/issues/6538

HTTP input plugin: Supporting custom success codes

---

plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

The sample config now shows the default values.  I added new defaults for the perf events since the existing defaults were not usable and the plugin required them to be set.
```
```
closes #6444

Show default settings in mysql sample config

---

Gopkg.lock
plugins/common/logrus/hook.go
plugins/inputs/ipvs/ipvs.go

Improve ipvs input error strings

---

.circleci/config.yml
Makefile
appveyor.yml
scripts/ci-1.12.docker
scripts/ci-1.13.docker

Note: Telegraf 1.12.4 will be with 1.12.12.

Build with Go 1.13.3 and 1.12.12

---

Gopkg.lock
Gopkg.toml

Version 1.10 of godirwalk are reported to support Solaris.  However, this isn't sufficient to support a Solaris, changes still need to be made to the docker, docker_logs, and ecs plugins.
related: #407

Update godirwalk version

---

Gopkg.lock
plugins/inputs/ping/ping.go

There was a bug when using raw socket mode with `method = "native"` on the ping input plugin where responses would be processed for the wrong host. This has been rectified upstream and the library updated in telegraf.
Better matching in `result_code` has also been implemented in telegraf between `exec` and `native` methods.
Resolves #6521

Ensure metrics generated are correct in ping plugin using "native"

---

plugins/inputs/powerdns/README.md
plugins/inputs/powerdns_recursor/powerdns_recursor.go
plugins/inputs/powerdns_recursor/powerdns_recursor_test.go

Fix powerdns_recursor socket_mode option

---

plugins/parsers/json/README.md
plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go
plugins/parsers/registry.go

feat(parser/json): continue parsing JSON after invalid object in array, with an option of strict to enforce validity of all objects

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

In the last change, sending to a channel was overlooked, causing all
ping errors and packet sent count to be ignored.
Resolves #6576

Fix incorrect results in ping plugin

---

plugins/inputs/sqlserver/sqlserver.go

Added some missing REPLACE(@@SERVERNAME,'\\',':') which caused inconsistency in the value of the tag [sql_instance]

Fixed an inconsistency in the value of the tag sql_instance

---

plugins/inputs/kube_inventory/README.md
plugins/inputs/kube_inventory/kube_state.go
plugins/inputs/kubernetes/README.md
plugins/inputs/kubernetes/kubernetes.go

Due to Kubernetes RBAC policies, it's extremely rare and unlikely that
anyone will run these plugins outside of the cluster. With that in-mind,
we should use as many defaults as possible to remove configuration.
All pods within Kubernetes have a ServiceAccount token mounted in to this
location, which shouldn't need to be repeated each time.

Add BearerToken Defaults for Kubernetes Plugins

---

Gopkg.lock
Gopkg.toml
plugins/inputs/snmp/README.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

While SNMP is usually done over UDP, it is possible to transport it using TCP. This is specified in RFC 3430 and should be used when transferring lots of data.
This PR adds support for SNMP over TCP to telegraf. The heavy lifting is done by the gosnmp library. Therefore it was only necessary to set the transport protocol for the agents, that should be gathered via TCP. To use it, you have to configure an agent like this:
```toml
[[inputs.snmp]]
agents = [ "tcp://1.2.3.4" ]
```
~The notation of prefixing with `tcp:` has been taken from net-snmp which uses it for their command line tools like snmpbulkwalk.~

Support for SNMP over TCP

---

Gopkg.lock
Gopkg.toml
plugins/inputs/all/all.go
plugins/inputs/ethtool/README.md
plugins/inputs/ethtool/ethtool.go
plugins/inputs/ethtool/ethtool_linux.go
plugins/inputs/ethtool/ethtool_nonlinux.go
plugins/inputs/ethtool/ethtool_test.go

Resolves #5864
Added new input plugin that will support pulling of data from
ethernet devices via ethtool

Ethtool Input Plugin (#5864)

---

plugins/inputs/openweathermap/README.md
plugins/inputs/openweathermap/openweathermap.go
plugins/inputs/openweathermap/openweathermap_test.go

The OpenWeatherMap API doesn't reliably return "3h" rain values,
so we examine the response for "1h" (preferred) or "3h" values as it
seems to depend on the particular weather station used which value will
be returned (see
https://openweathermap.desk.com/customer/en/portal/questions/17663899-rain-1h-3h-are-mutually-exclusive-?new=17663899).
Closes #6583

Use 1h or 3h rain values as appropriate

---

logger/logger.go

Having `logfile` unset is not an error, and is in fact the default value.  This is a unreleased log message that was added in #4291

Skip logging when logfile is unset

---

plugins/inputs/mysql/mysql.go
plugins/inputs/mysql/v2/convert.go
plugins/inputs/mysql/v2/convert_test.go

Add the ability to have per field conversion functions for the global status and global variables queries.  These queries both return tables of the form:
```
+----------------+---------------+------+-----+---------+-------+
| Field          | Type          | Null | Key | Default | Extra |
+----------------+---------------+------+-----+---------+-------+
| VARIABLE_NAME  | varchar(64)   | NO   |     |         |       |
| VARIABLE_VALUE | varchar(2048) | NO   |     |         |       |
+----------------+---------------+------+-----+---------+-------+
```
closes #5529
closes #6646

Fix known mysql type conversion issues

---

plugins/inputs/jenkins/README.md
plugins/inputs/jenkins/jenkins.go
plugins/inputs/jenkins/jenkins_test.go

Fix metric creation when node is offline in jenkins input

---

agent/agent.go
docs/CONFIGURATION.md
internal/config/config.go
internal/models/running_output.go

This supports setting unique flush intervals per output plugin.
See [#6569](https://github.com/influxdata/telegraf/issues/6569)

Handle per-plugin flush jitter, fixes #6569

---

internal/internal.go
internal/internal_test.go
plugins/inputs/http/http.go
plugins/outputs/http/http.go
plugins/outputs/influxdb/http.go
plugins/outputs/influxdb/influxdb.go
plugins/outputs/influxdb_v2/http.go
plugins/outputs/influxdb_v2/influxdb.go

Fix influxdb output serialization on connection closed

---

plugins/inputs/file/README.md
plugins/inputs/file/file.go
plugins/inputs/file/file_test.go

This PR adds the ability to create and name a tag containing the filename of the file parsed using the file input plugin.  Leaving this option blank will cause the tag not to be generated.
Resolves #6644.

Add a nameable file tag to file input plugin

---

Gopkg.lock
Gopkg.toml

The Telegraf agent fails to connect to Azure_Monitor using environment variables AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_SECRET. This issue seems to have been fixed by this [commit](https://github.com/Azure/go-autorest/commit/880eb0e2aca291c40538ddef66e5914fb1cc1d7f), however the agent is currently using the package "github.com/Azure/go-autorest" version `10.12.0`. This PR is to change the version definition on `Gopkg.toml` file to `^13.0.0`. I have successfully tested the new agent on a Azure VM with the aforementioned variables set.
Co-authored-by: @billglover

Upgrading Azure/go-autorest version to ^13.0.0

---

plugins/inputs/nats/nats.go
plugins/inputs/nats/nats_freebsd.go
plugins/inputs/nats/nats_test.go

Build the nats input on freebsd when cgo is enabled

---

agent/accumulator.go
plugins/inputs/cloudwatch/cloudwatch.go

Revert change to log all plugin errors at debug level, only report the "no metrics found" error from the cloudwatch plugin at debug level.
follow-up to #6630
closes #6666

Log no metrics found at debug level in cloudwatch input

---

plugins/inputs/docker_log/docker_log.go

Use nanosecond precision in docker_log input

---

internal/config/config.go
plugins/serializers/registry.go
plugins/serializers/splunkmetric/README.md
plugins/serializers/splunkmetric/splunkmetric.go
plugins/serializers/splunkmetric/splunkmetric_test.go

Adds support for Splunk 8.0's multi metric format.

Add Splunk MultiMetric support

---

plugins/inputs/influxdb/README.md
plugins/inputs/influxdb/influxdb.go
plugins/inputs/influxdb/influxdb_test.go

Add support for sending HTTP Basic Auth in influxdb input

---

plugins/inputs/socket_listener/README.md
plugins/inputs/socket_listener/socket_listener.go
plugins/inputs/socket_listener/socket_listener_test.go

Add compression support to socket_listener

---

plugins/outputs/cloudwatch/README.md
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

Add StorageResolution config to CloudWatch output

---

plugins/outputs/cloudwatch/README.md
plugins/outputs/cloudwatch/cloudwatch.go

Fixes README.md and example config from cloudwatch output as notified in https://github.com/influxdata/telegraf/pull/6689#discussion_r349610227

Fix cloudwatch output README.md and improve example config description

---

plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

Allow to load multiple certificates from the same file with the x509 input
- [] Associated README.md updated. (Not needed)

Allow multiple certificates on same file for x509 input

---

etc/telegraf.conf
plugins/inputs/x509_cert/README.md
plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

Fixes https://github.com/influxdata/telegraf/issues/6685

Add additional tags for x509 Input Plugin

---

plugins/inputs/vsphere/METRICS.md

Currently there is no easy way of finding the units metrics are stored as; added an explanation and link in the METRICS.md file to the VMWare vCenter Converter API Reference which lists all the metrics, as well as the units those metrics are stored as.
This resolves #6709

Added link to VMWare vCenter Converter API Reference

---

Gopkg.lock
docs/DATA_FORMATS_OUTPUT.md
internal/http.go
plugins/inputs/file/file.go
plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/prometheus.go
plugins/outputs/file/README.md
plugins/outputs/file/file.go
plugins/outputs/prometheus_client/README.md
plugins/outputs/prometheus_client/prometheus_client.go
plugins/outputs/prometheus_client/prometheus_client_test.go
plugins/outputs/prometheus_client/v1/collector.go
plugins/outputs/prometheus_client/v2/collector.go
plugins/serializers/prometheus/README.md
plugins/serializers/prometheus/collection.go
plugins/serializers/prometheus/collection_test.go
plugins/serializers/prometheus/convert.go
plugins/serializers/prometheus/prometheus.go
plugins/serializers/prometheus/prometheus_test.go
plugins/serializers/registry.go

Add a prometheus serializer, with support for round tripping `metric_version=2` of the `prometheus` input.
related #4414 
Use this serializer in the Prometheus output when `metric_version=2`.  Formally deprecate metric_version = 1 in both the input and the output plugin.
closes #4415
Add `use_batch_format` support to the file output, similar to support in the amqp and kafka outputs.  This is a move away from the `Serialize` function towards the `SerializeBatch` function in the Serializer interface, which allows for more efficient writing and writing multiple metrics to a destination.  In regards to the prometheus serializer, the batch format is required in order to group metric families and to write histogram and summary types correctly.  
There is a known bug introduced in this pull …

Add prometheus serializer and use it in prometheus output

---

Gopkg.lock
Gopkg.toml
etc/telegraf.conf
plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go

Exposed the balance strategy configuration as in https://github.com/Shopify/sarama/blob/master/balance_strategy.go.
Fixes #6687.

kafka_consumer: expose partition assignment strategy configuration (#6687)

---

plugins/inputs/influxdb_listener/influxdb_listener_test.go
testutil/accumulator.go

Here are some benchmarks for the influxdb listener.  I'm hoping these can be guides for performance if there are refactors to do in the plugin.

perf(inputs/influxdb_listener): benchmark serving writes

---

plugins/inputs/filecount/README.md
plugins/inputs/filecount/filecount.go
plugins/inputs/filecount/filecount_test.go

plugins/input: filecount: Support resolution of symlinks in directory tree

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongostat.go

MongoDB doc: [serverstatus.uptimeMillis](https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.uptimeMillis)

Add MongoDB uptime_ms

---

plugins/inputs/mongodb/mongodb_server.go

Restore debug logging of authentication errors when reading the oplog first added in #4869.
closes #6684

Log mongodb oplog auth errors at debug level

---

plugins/inputs/ping/ping.go

Continue after error.  Also fix tag name regression `url` -> `ip`. 
Compare against 1.11:
https://github.com/influxdata/telegraf/blob/747b136466cfe31084ef0ec5fc24ffb2aabba8c9/plugins/inputs/ping/ping.go#L111-L120
closes #6690

Fix ping skips remaining hosts after dns lookup error

---

plugins/inputs/prometheus/prometheus.go

Add `*/*;q=0.1` to the accept header of the prometheus input.  This is for greater compatibility with the prometheus scaper:
https://github.com/prometheus/prometheus/blob/1fa5a75a3a066778de5a78305141ed0dcb791cc3/scrape/scrape.go#L518
closes #6523

Accept any media type in the prometheus input

---

plugins/processors/strings/README.md
plugins/processors/strings/strings.go
plugins/processors/strings/strings_test.go

This is an updated version of #4698.  It adds support for the "standard base64 encoding" and not the "alternate base64 encoding" aka url encoded base64.  If the string is not base64 encoded or does not contain encoded utf-8 data, the unmodified string is passed through without warning, consistent with the other operations of the plugin.
closes #4697

Add base64decode operation to string processor

---

plugins/outputs/kafka/kafka.go

Set message timestamp to the metric time in kafka output

---

docs/FAQ.md

I found there are five environment variables(HostProc、HostSys、HostEtc、HostVar and HostRun) in gopsutil  which are used by telegraf referencing from https://github.com/shirou/gopsutil/blob/5335e3fd506df4cb63de0a8239c7461d23063be6/internal/common/common.go

update telegraf supported environment variables

---

.circleci/config.yml
CHANGELOG.md
Makefile
appveyor.yml
scripts/ci-1.12.docker
scripts/ci-1.13.docker

Fix issue on Darwin where binary fails to run with "developer cannot be verified" error.

Build packages with Go 1.13.5

---

Gopkg.lock
Gopkg.toml

This change is being made to reduce confusion around if Telegraf is affected by https://github.com/satori/go.uuid/issues/73.  Neither Telegraf 1.12 or 1.13 are affected by this issue, I have not investigated earlier versions.
Telegraf dropped this library as a direct dependency in 1.13, moving to gofrs.  In Telegraf 1.12, we do use the affected library, but only for random partitioning in the kinesis and kafka outputs where randomness is not a security issue.
This library still exists as a transitive dependency for the Microsoft Application Insights output plugin.  However, they have worked around this bug in their library and we have had the fix since Telegraf 1.8: https://github.com/microsoft/ApplicationInsights-Go/blob/master/appinsights/uuid.go#L14-L21
At first glance it may also …

Override github.com/satori/go.uuid revision for transitive deps

---

plugins/outputs/influxdb/influxdb.go

Use the effective database name instead of the name from the configuration file.  These are only different when using the default "telegraf" database.

Use actual database name in db creation failed log

---

plugins/outputs/prometheus_client/prometheus_client_v1_test.go
plugins/outputs/prometheus_client/v1/collector.go
plugins/serializers/prometheus/prometheus_test.go

Replace `:` with `_` in label names when using `metric_version = 1`.  Version 2 already did this correctly.
closes #6757

Replace colon chars in prometheus output labels with metric_version=1

---

plugins/inputs/snmp_trap/README.md
plugins/inputs/snmp_trap/snmp_trap.go

add documentation to SNMP trap plugin about listening on port < 1024

---

plugins/parsers/csv/parser.go
plugins/parsers/csv/parser_test.go

When TrimSpace is used and Delimeter is a space, it trips up the CSV reader otherwise.
Visual representation of now-supported format:
```
first   second   third   fourth
abcdefgh        0       2    false
abcdef      3.3       4     true
f        0       2    false
```

csv: TrimLeadingSpace when TrimSpace is on

---

plugins/inputs/mysql/README.md
plugins/inputs/mysql/mysql.go

This PR addresses Issue #6789 
There should be a config value that allows for enabling/disabling collection of MySQL Global Variables.
- Readme: Added line for boolean config for collecting global vars
- mysql.go: added line to retrieve  config value
- mysql.go: added logic to either collect or not collect vars based on config

MySQL - Option for collecting global variables

---

plugins/inputs/snmp_trap/snmp_trap.go

I tested this with a coldStart trap from net-snmp.  ColdStart is packet.GenericTrap == 0.

Fix off by one bug in snmp trap v1 generic trap field

---

plugins/inputs/haproxy/README.md

Added missing HTTP basic auth credentials for HAProxy stats endpoint in README.md for HAProxy input plugin
- [x ] Associated README.md updated.

Added missing HTTP basic auth credentials for stats endpoint

---

plugins/inputs/kubernetes/README.md
plugins/inputs/kubernetes/kubernetes.go
plugins/inputs/kubernetes/kubernetes_podlist.go
plugins/inputs/kubernetes/kubernetes_pods.go
plugins/inputs/kubernetes/kubernetes_test.go

By calling the Endpoint `/pods` i added a function that collects the Labels of all Pods and adds them to their tags.

Kubernetes input plugin PodLabels

---

cmd/telegraf/telegraf.go

With tens of ouputs of plugins, and hundreds of input plugins, I struggled to easily read the needed plugin, so I though about sorting them alphabetically.
It can be useful to every user, instead of using grep to look for the needed plugin.

Sort alphabetically plugin lists

---

plugins/inputs/snmp_trap/snmp_trap.go
plugins/inputs/snmp_trap/snmp_trap_test.go

Also add a test for v1 generic trap and fix a bug in v1 generic trap where generic oid was missing its leading period.

Convert snmp_trap_test.go to table test

---

etc/telegraf.conf
plugins/inputs/unbound/README.md
plugins/inputs/unbound/unbound.go
plugins/inputs/unbound/unbound_test.go

This PR exposes the [-c cfgfile option of unbound-control](https://linux.die.net/man/8/unbound-control) allowing Telegraf users to monitor non-default unbound setups.
Unbounds default location `/etc/unbound/unbound.conf` is set as Telegraf default.

unbound: expose unbound-control config file option

---

internal/config/config.go

New 1.13 prometheus serializer includes configuration fields that are not included in the serializer configs.  Adding these parameters enable telegraf to prometheus http push gateway to work.
closes #6823
- [n/a] Associated README.md updated.
- [n/a] Has appropriate unit tests.

Config fields for prometheus serializer missing at serializer config

---

plugins/inputs/mqtt_consumer/mqtt_consumer.go

If messages from a previous connection are delivered after a new connection is established, there would be too many messages in flight which would overflow the delivery channel.  We need to reuse the send semaphore on reconnection, so that it has the same lifetime as the accumulator delivery channel.
closes #6694

Fix panic on connection loss with undelivered messages

---

plugins/inputs/sqlserver/sqlserver.go

With reference to issue #6679, this will convert the binary data to strings, in order to make them more meaningful once stored.
The involved fields are:
- query_hash
- query_plan_hash
The question about turning them from fields to tags is still open

Input Sqlserver -binary hash converted to string

---

plugins/inputs/diskio/diskio_linux.go

[Input: Diskio] Invalid diskinfo cache if the device Mtim has changed

---

plugins/inputs/suricata/suricata_test.go

This pull request is meant to improve the reliability and output of the suricata inputs unit tests to help track down some intermittent failures in the test suite.

Improve suricata input unit test debugging

---

plugins/common/kafka/sasl.go
plugins/inputs/kafka_consumer/README.md
plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/inputs/kafka_consumer/kafka_consumer_test.go
plugins/inputs/zookeeper/README.md
plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go

Add manual control of SASL version for testing.  Before merging this support should also be added to the output.
related #6342

Add kafka SASL version control to kafka_consumer

---

Gopkg.lock
Gopkg.toml

This fixes a step that happens during static initialization where the library detects the init system.  Since we use this library only for Windows service and event log support, I would separately like to split the library out of the build for other platforms.
closes #6846

Update github.com/kardianos/service to 1.0.0

---

plugins/inputs/rabbitmq/rabbitmq.go

Report rabbitmq_node measurement and return on gather error

---

plugins/aggregators/merge/README.md
plugins/aggregators/merge/merge.go

Update merge aggregator config file in README.md with `drop_original = true`. This type of aggregator would want to default to true.

Update merge aggregator config file in README.md

---

plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go
plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go

Use last path element as field key if path fully specified

---

plugins/inputs/sqlserver/sqlserver.go

Added RBPEX IO statistics as part of DatabaseIO collector
Added space on disk for each file for https://github.com/influxdata/telegraf/pull/6711 as part of DatabaseIO collector. Also added space used only for Azure SQL DB ( gathering on MI/on-prem requires switching DB context to each DB and is expensive
Calculated DB Name instead of GUID in physical_db_name for specific perfmon countners for MI/ Azure SQL DB to address https://github.com/influxdata/telegraf/issues/6570
Changed query to convert resource stats to floats/measurements instead of prior strings to address https://github.com/influxdata/telegraf/issues/6397. Changed the measurement to sqlserver_azure_db_resource_stats
Change to address Case sensitive collation : https://github.com/influxdata/telegraf/issues/6867
closes #6711 …

Adding RBPEX stats collection, DBName for perfmon, proper type for resource stats

---

CHANGELOG.md
plugins/outputs/warp10/README.md
plugins/outputs/warp10/warp10.go
plugins/outputs/warp10/warp10_test.go

Update documentation to latest style.
Clamp unsigned integers to largest int64, as required by Warp10.
Use metric timestamp instead of send time as timestamp.

Update Warp10 docs and uint64 and timestamp handling

---

plugins/inputs/jenkins/README.md
plugins/inputs/jenkins/jenkins.go
plugins/inputs/jenkins/jenkins_test.go

-> Earlier "url.Parse" function was called "N Nodes" and "J Jobs" times which is now reduced to just  2 calls by creating separate function for URL parsing and source, port split.
-> Added missing source and port tags in jenkins_job metrics

Added source and port tags in jenkins_job metrics

---

plugins/inputs/vsphere/endpoint.go
plugins/inputs/vsphere/finder.go

Fixes issue #6883. 
The original intention was that custom attribute should be collected for all resource types. However, only collection for VMs was working. This PR fixes that.
Maintainers: Is there a chance we can get this one into 1.13.1?

[inputs.vsphere] Added custom attributes for all resource types

---

CHANGELOG.md
plugins/processors/date/README.md
plugins/processors/date/date.go
plugins/processors/date/date_test.go

Add date offset option to date processor

---

plugins/inputs/vsphere/endpoint.go
plugins/inputs/vsphere/vsphere.go

The ```force_discovery_on_init``` flag was causing problems and setting it to false no longer has any desirable effects due to the way discovery is implemented.
The flag is now deprecated and setting it to ```false``` will print a warning and will be ignored.
closes #6860

[inputs.vsphere] Deprecated force_discovery_on_init flag

---

plugins/inputs/smart/smart.go

Changed logic to allow recording of device fields without having to set attributes flag to true. With attributes set to false, if the metric is classified as an attribute it is not recorded. This occurs even is the metric is not a vendor attribute. Left it like this to keep the system compatible with users who are expecting the current structure. Validated with 'go test' and by building telegraf and monitoring inputs into local influxdb.
closes #6619

Record Device Fields Regardless of Attribute Flag

---

plugins/inputs/ntpq/README.md

when I first see commnet for dns_lookup, I don't understand the meaning of set the -n ntpq flag

change comment for config dns_lookup

---

internal/config/config.go
internal/config/config_test.go
plugins/parsers/json/README.md

Hook up json_strict option with default of true

---

plugins/outputs/graylog/README.md
plugins/outputs/graylog/graylog.go

closes #6683
```toml
[[outputs.graylog]]
servers = ["127.0.0.1:12201"]
```

Allow a user defined field to be used as the graylog short_message

---

plugins/inputs/x509_cert/README.md
plugins/inputs/x509_cert/x509_cert.go

Closes #6809.
As it's my first contrib to this project:

Add server_name override for x509_cert plugin

---

plugins/inputs/statsd/statsd.go

Add additional counters for statsd in udp mode.
closes: #6779

Add udp internal metrics for the statsd input

---

plugins/inputs/kibana/README.md
plugins/inputs/kibana/kibana.go
plugins/inputs/kibana/kibana_test.go
plugins/inputs/kibana/testdata_test6_3.go
plugins/inputs/kibana/testdata_test6_5.go

Kibana Input Plugin: added compatibility for all 6.X.X versions

---

metric/tracking.go
metric/tracking_test.go

There is a small chance the newTrackingID() function in tracking.go
will return the same id to multiple simultaneous callers.
The function must return the value returned by atomic.AddUint64()
to be safe.

Fix duplicate TrackingIDs returned

---

internal/models/running_aggregator_test.go
plugins/inputs/vsphere/vsphere_test.go
testutil/accumulator.go

Fix atomic usage in tests

---

plugins/outputs/prometheus_client/v2/collector.go

Ensures that expired metrics are removed even when no new data is sent
to the output.
closes #6973

Expire metrics on query in addition to on add.

---

plugins/processors/strings/README.md
plugins/processors/strings/strings.go
plugins/processors/strings/strings_test.go

- Title (https://golang.org/pkg/strings/#Title) function support all unicode letters.
- BUG: The rule Title uses for word boundaries does not handle Unicode punctuation properly, that should not effect much with use-case of Title rule in telegraf.

 processor/strings: add support for `title` convertor

---

plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go

This intermittent error appears to be an error calling net.Listen, with a follow on error later in the test causing the panic.  It is unknown why the Listen call failed.
To address, change tests to listen on an available port instead of a hardcoded port to avoid conflicts, and use require to stop the test after the first error.
```
--- FAIL: TestTCPDialoutOverflow (0.00s)
cisco_telemetry_mdt_test.go:390: 
Error Trace:	cisco_telemetry_mdt_test.go:390
Error:      	Expected nil, but got: &net.OpError{Op:"listen", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc00014db30), Err:(*os.SyscallError)(0xc00000fba0)}
Test:       	TestTCPDialoutOverflow
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil …
```

Use require in cisco mdt tests to avoid follow on errors

---

plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/prometheus_test.go

Parse NaN values from summary types with prometheus `metric_version = 2`.  Missing data in the output was caused by not having any quantile values.
Note that line protocol does not support NaN values, so these won't appear when when using `--test`.
closes #6988

Parse NaN values from summary types in prometheus input

---

plugins/inputs/modbus/modbus.go
plugins/inputs/modbus/modbus_test.go

this solve the next 2 issues that [@serrj-sv](https://github.com/serrj-sv) reported
- [improve float conversion](https://github.com/influxdata/telegraf/pull/6154#issuecomment-583509623)
- [if host associated with input plugin is down it prevents telegraf service from starting](https://github.com/influxdata/telegraf/pull/6154#issuecomment-583538364)

Fix float conversion and Connection issue

---

plugins/inputs/openldap/openldap.go

Update the OpenLDAP plugin to be able to utilize the new information about the database state available in OpenLDAP 2.4.49 and later

issue#6992 - Add support for MDB database information

---

plugins/inputs/pgbouncer/pgbouncer.go
plugins/inputs/postgresql/service.go

The pgbouncer input plugin was not checking for errors from the 'SHOW POOLS' query. For at least newer versions of pgbouncer, this query was failing, silently, causing none of those values to be recorded. The second issue was the cause of that query failing. For whatever reason, we need to register pgtype.NumericOID because pgbouncer is now sending data with that. See https://github.com/jackc/pgx/issues/649 for a discussion about this.

Fixes for two pgbouncer issues. 

---

plugins/inputs/jenkins/README.md
plugins/inputs/jenkins/jenkins.go
plugins/inputs/jenkins/jenkins_test.go

Added new fields for Jenkins Total and Busy executors

---

docker-compose.yml
plugins/inputs/ethtool/ethtool_test.go
plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
plugins/inputs/powerdns_recursor/powerdns_recursor_test.go
plugins/inputs/processes/processes_test.go
plugins/inputs/syslog/rfc5426_test.go

Fixes issues with failing tests on darwin for `go test -short ./...` test run.

Fixes issues with failing tests on darwin

---

plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go

Currently configuring embedded_tags for cisco_telemetry_mdt input
requires an unusual mix of - and _, i.e. one needs to specify e.g.
Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization/process_cpu/process-id
for it to work correctly. Additionally, tags created might still contain
dashes against convention.
This fix creates correctly formatted tags with underscores instead of
dashes and unifies the configuration parameter to expect either dashes
or underscores, so old configurations are still valid.

Fix dash to underscore replacement when handling embedded tags in Cisco MDT

---

plugins/inputs/sqlserver/sqlserver.go

Resolves #7059 
Fixed some filter conditions in the Performance Counters queries (both v1 and v2).
The column "object_name" has different values between default and named instance
- **Default Instance** - object_name = SQLServer:Batch Resp Statistics
- **Named Instance** - object_name = <Instancename>:Batch Resp Statistics
The fix (in its own commit) has been made also for the v1 query (the logic is exactly the same), but I have no way to test it since none of my databases gathers the affected "object_name", which are "%FileTable" and"%Backup Device".

Missing perf counters fix

---

plugins/outputs/prometheus_client/v2/collector.go
plugins/serializers/prometheus/collection.go
plugins/serializers/prometheus/collection_test.go
plugins/serializers/prometheus/prometheus.go

Use add time for prometheus expiration calculation

---

agent/accumulator.go
agent/accumulator_test.go
agent/agent.go
internal/models/log.go
internal/models/log_test.go
internal/models/running_aggregator.go
internal/models/running_input.go
internal/models/running_input_test.go
internal/models/running_output.go
internal/models/running_processor.go
plugins/inputs/cloud_pubsub_push/pubsub_push_test.go

Addresses error inconsistency raised by https://github.com/influxdata/telegraf/issues/7057

Fixes inconsistency with input error counting

---

plugins/inputs/prometheus/parser.go

avoid the chance to have different timestamp during iteration of each
metric for one http.Response
This PR, fix an issue we discover. some time during the iteration of metrics, the timestamp change to pass to the next second and our metrics aren't align.
This only applied if TimestampMs is not provided in the prometheus metrics

Input prometheus, use the same timestamp per call if no time is provided

---

plugins/serializers/influx/reader_test.go

```
BenchmarkReader-4            186           6372130 ns/op            7984 B/op         13 allocs/op
```

Add basic benchmark for influx serializer reader

---

README.md
plugins/inputs/all/all.go
plugins/inputs/execd/README.md
plugins/inputs/execd/examples/count.go
plugins/inputs/execd/examples/count.rb
plugins/inputs/execd/examples/count.sh
plugins/inputs/execd/execd.go
plugins/inputs/execd/execd_unix.go
plugins/inputs/execd/execd_win.go

The execd input plugin spawns a long running process and parses its output to gather metrics. The process can be signaled in different ways on each interval.
This can be used to avoid spawning processes on each interval as with the exec plugin or with external programs that report metrics by themselves e.g. in irregular intervals (events). Processes are restarted after termination with a one second pause.
The overhead is minimal for both sides as only `stdout`, `stderr`, and `stdin` or signals are used. Some example daemons in bash, go, and ruby are included.
---
This is my first time writing Go at all. Feel free to comment or change things. I only have this running on linux, but cross compilation to windows works. I have no idea how to unit test this unfortunately.

Add an exec daemon plugin

---

plugins/inputs/phpfpm/README.md
plugins/inputs/phpfpm/phpfpm.go
plugins/inputs/phpfpm/phpfpm_test.go

This PR allows glob patterns to be used in the `unixsocket` configuration. This is useful in environments where FPM pools are managed dynamically, so that the configuration file doesn't have to be edited every time a pool is created or deleted.

Allow globs in FPM unix socket paths

---

plugins/aggregators/histogram/README.md
plugins/aggregators/histogram/histogram.go
plugins/aggregators/histogram/histogram_test.go

Histogram aggregator: Enable non-cumulative stats

---

go.mod
go.sum
plugins/inputs/prometheus/README.md
plugins/inputs/prometheus/kubernetes.go
plugins/inputs/prometheus/kubernetes_test.go
plugins/inputs/prometheus/prometheus.go

- [ y] Signed [CLA](https://influxdata.com/community/cla/).
- [ y] Associated README.md updated.
- [ y] Has appropriate unit tests.
Fixes #6950

add functionality to scrape pods per kubernetes node

---

plugins/processors/converter/README.md
plugins/processors/converter/converter.go
plugins/processors/converter/converter_test.go

Add support for converting tag or field to measurement in converter processor

---

internal/rotate/file_writer.go
internal/rotate/file_writer_test.go

Fix file rotation mechanism. (#6776)

logging: Fix file rotation mechanism.

---

plugins/inputs/kafka_consumer/kafka_consumer.go
plugins/outputs/kafka/README.md
plugins/outputs/kafka/kafka.go
plugins/outputs/kafka/kafka_test.go

Add topic tag options to kafka output

---

internal/models/buffer.go
internal/models/running_output_test.go

Fix a issue where the internal metrics were split over two lines unnecessarily due to the alias tag being set to the empty string.
1.13.4
```
> internal_write,host=loaner,output=kafka,version=unknown errors=0i,metrics_filtered=0i,write_time_ns=0i 1583447470000000000
> internal_write,host=loaner,output=kafka,version=unknown buffer_limit=10000000i,buffer_size=0i,metrics_added=0i,metrics_dropped=0i,metrics_written=0i 1583447470000000000
```
With change
```
internal_write,host=loaner,output=file,version=unknown buffer_limit=10000000i,buffer_size=0i,errors=0i,metrics_added=0i,metrics_dropped=0i,metrics_filtered=0i,metrics_written=0i,write_time_ns=0i 1583447704000000000
```

Fix internal metrics for output split into multiple lines

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb/http.go
plugins/outputs/influxdb/http_test.go
plugins/outputs/influxdb/influxdb.go

Add support for setting retention policy using tag

---

docs/CONFIGURATION.md
internal/config/config.go
internal/models/running_output.go
internal/models/running_output_test.go

This PR adds the ability to apply name_* modifiers to measurement names in output plugins. It closes the issue #7033.

Allow using name_* modificators for output plugins

---

plugins/inputs/sqlserver/sqlserver.go

- [] Has appropriate unit tests.
Datababase IO changes
Today on Azure SQL DB there was a bug where left outer join from virtual file stats and database_files was only on file_id. Tempdb was exposed on virtual file stats, but not in Database files. On Azure SQL DB have to use tempdb.sys.database_files. In addition each Azure SQL DB has its own tempdb so needed to add Database_id/File ID to be able to distinguish so that reporting can be done by Logical Server + Azure DB + database_id.  If you just looked at tempdb for a logical server would get multiple tempdb's belonging to different Azure SQL DB's as the logical server construct is just that a placeholder logical server not actual physical server.
Also corrected bug introduced …

Adding Database IO Tempdb per Azure DB collection, Fixing PerfmonV2 collection for on-prem

---

etc/telegraf.conf
plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go
plugins/inputs/sqlserver/sqlserver_test.go

Add option for explicitly including queries in sqlserver input plugin.

---

plugins/inputs/phpfpm/phpfpm_test.go

I'm seeing this test fail locally due to differences in how the url is quoted. Possibly an issue specific to go 1.14.

fix broken test on mac

---

plugins/inputs/influxdb_listener/influxdb_listener.go
plugins/inputs/influxdb_listener/influxdb_listener_test.go

Set x-influxdb-version and content-type headers on ping URL as expected by clients.
closes #7104

Set headers on influxdb_listener ping URL

---

go.mod
go.sum

Update to the latest gopsutil

---

plugins/inputs/cisco_telemetry_gnmi/README.md
plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go

This uses the GNMI library native ToScalar function to convert GNMI TypedValues to scalar Go values.
Also adds an updated note on tested device platforms.
Fixes #7167

Fix GNMI TypedValue to scalar value conversion and update supported platforms

---

docs/LICENSE_OF_DEPENDENCIES.md
go.mod
plugins/inputs/prometheus/prometheus.go

Importing these libraries starts a goroutine at init time.  The removal of the checks will push a startup time error to a runtime error.
```
goroutine 8 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x454f3c0)
/home/dbn/src/influx/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
/home/dbn/src/influx/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6
```
related #6969

Remove init checks for valid label and field selectors

---

Makefile

The /dev/null device on Windows is a virtual file named "nul" not "nil".
This fix works under both cmd.exe and Powershell.
Not applicable:

Fix 'nil' file created by Makefile on Windows

---

plugins/inputs/ping/ping.go
plugins/inputs/ping/ping_test.go

This includes dns lookup in ping deadline. The deadline context is used for performing dns lookups, thus a ping collection will fail if the dealine times out during a lookup
Fixes #5059

Apply ping deadline to dns lookup

---

scripts/check-deps.sh

This scripts output was confusing, this change adds some directions for how to handle errors.
Example output:
```
$ ./scripts/check-deps.sh
--- /tmp/tmp.NnRf7xH9bB/LICENSE_OF_DEPENDENCIES.md      2020-03-27 11:45:01.273020284 -0700
+++ /tmp/tmp.NnRf7xH9bB/HEAD    2020-03-27 11:45:01.272020301 -0700
@@ -67 +66,0 @@
-github.com/gorilla/context
The docs/LICENSE_OF_DEPENDENCIES.md file does not contain the expected entries.
Lines prefixed with '+' should be added to LICENSE_OF_DEPENDENCIES.md and '-'
lines should be removed.
Include a link to the appropriate licenses for any additions.
```

Add docs for how to handle errors in check-deps script

---

plugins/inputs/tail/README.md
plugins/inputs/tail/tail.go
plugins/inputs/tail/tail_test.go

This avoids the input reading too far ahead and filling the metric buffer.  Particularly useful when doing a batch import with `from_beginning = true`.

Add limit to number of undelivered lines to read ahead in tail

---

plugins/inputs/modbus/README.md
plugins/inputs/modbus/modbus.go

With this PR it is possibile to specify an (optional) _measurement_ property per register definition to group those registers as fields of the specified measurement. In case the _measurement_ property is missing _modbus_ is used for the measurement name just as before.
The reasoning behind this is that some devices have restrictions for the number of simultaneous connections. When reading multiple metrics (e.g. voltage, current, work, power) from one device, assigning each them to different measurements would take multiple instances of the modbus plugin, each with a `name_override`. Thus these multiple instances will concurrently connect to device potentially exceeding the number of maximum allowed connections.
With the PR applied, one modbus plugin can read all required registers from …

[inputs/modbus] Add possibility to specify measurement per register

---

internal/config/config.go
plugins/outputs/graphite/README.md
plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go
plugins/outputs/instrumental/instrumental.go
plugins/serializers/graphite/README.md
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go
plugins/serializers/registry.go

```
[[outputs.graphite]]
...
template = "host.tags.measurement.field"
```
```
[[outputs.graphite]]
...
templates = [
"cpu tags.measurement.host.field",
"disk* measurement.field",
"host.measurement.tags.field"
]
```
closes #7135

Support multiple templates for graphite serializers

---

plugins/inputs/kapacitor/README.md

- Update ReadMe to include `kapacitor_alert` and `kapacitor_cluster` measurements. 
@danielnelson, I've incorporated all edits from @nathanielc.
Thanks guys!

kapacitor_alert and kapacitor_cluster measurements

---

etc/telegraf.conf
scripts/build.py
scripts/post-install.sh

This PR fixes https://github.com/influxdata/telegraf/issues/4966, by changing the way `telegraf.conf` is packaged and deployed:
- `telegraf.conf` is now packaged as `telegraf.conf.sample`. This will make package managers compare over the `.sample` file instead of the `.conf` one, making it more user friendly since `/etc/telegraf.conf` is usually configured by the user
- If no `/etc/telegraf/telegraf.conf` is present on the target system (typical case of a fresh install), the post installation step will copy `/etc/telegraf/telegraf.conf.sample` to `/etc/telegraf/telegraf.conf` to have an initial working configuration
Notes:
* There is a non related first commit with some changes to `build.py` file, based on PEP-8 recommendations
* I have tested this with `linux/amd64` `rpm/deb` packages, I …

Deploy telegraf configuration as a "non config" file

---

plugins/processors/template/template_metric.go
plugins/processors/template/template_test.go

Fix Name field in template processor

---

plugins/inputs/http/README.md
plugins/inputs/http/http.go

Associated Feature Request #7303

Adds the ability to read an authorization token from a file

---

plugins/inputs/fibaro/README.md
plugins/inputs/fibaro/fibaro.go
plugins/inputs/fibaro/fibaro_test.go

This simply adds battery level scraping for battery operated devices, in order to be able to alert when a battery runs out of juice.

Fibaro input: for battery operated devices, add battery level scraping

---

agent/agent.go
agent/agent_notwindows.go
agent/agent_windows.go
cmd/telegraf/telegraf.go
cmd/telegraf/telegraf_notwindows.go
cmd/telegraf/telegraf_windows.go
docs/OUTPUTS.md
internal/usage.go
internal/usage_windows.go

Closes https://github.com/influxdata/telegraf/issues/5120

add support for SIGUSR1 to trigger flush

---

go.mod
go.sum

AWS GO SDK released support for AWS Metadata service v2 
as SDK enhancement from [Release](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v12538-2019-11-19)
The current AWS SDK version used in cloud watch output plugin
has to updated to version >= 1.25.38 to have support for IMDSV2
More info on AWS Instance metadata service [info](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)
closes #7371

Fix #7371 aws cloudwatch cannot write metrics if imdsv1 is disabled

---

plugins/inputs/modbus/README.md
plugins/inputs/modbus/modbus.go
plugins/inputs/modbus/modbus_test.go

Currently, when the slave device is busy, e.g. because it already serves a request of another client, we get an error and the measurement is lost for the gathering interval. This potentially leads to many lost measurements for very busy devices.
With this PR you can specify the number of retry attempts (and a wait time) to be performed if the device is busy. This achives a higher probability to get a measurement on busy devices for each query interval.

[inputs/modbus] Implement retry when slave is busy

---

plugins/inputs/sqlserver/sqlserver.go

closes #7241
added the missing RTRIM on the column that becomes the tag "instance" in the perf counters query

SQL Server - Fix - Perf Counter missing RTRIM

---

plugins/inputs/cloudwatch/cloudwatch.go

Use new higher limit for cloudwatch GetMetricData

---

plugins/inputs/iptables/iptables.go
plugins/inputs/iptables/iptables_test.go

This is very handy to find all rules going to a certain target, for
example DROP.

iptables input plugin: Extract target as a tag for each rule

---

plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

`strconv.Atoi` produces a 32 bit and truncates larger inputs. Switch this to `strconv.ParseInt` to get an int64, matching the other conversions. Add a unit test. No changes to README.md needed.

Fix string to int64 conversion for SNMP input

---

plugins/serializers/json/json.go
plugins/serializers/json/json_test.go

With this change it is possible to have a metric with no encodeable fields.  I debated having the serializer skip the metric and potentially return an empty buffer, this would be similar to what the influx serializer does, but decided against it in this case.  With line protocol, it isn't possible to write a line without fields, but with JSON it is still possible to write the remaining data and guarantees that something will be written.  Since this data format is often used for debugging I think this will be the best behavior.
closes #7388

Ignore fields with NaN or Inf floats in the JSON serializer

---

plugins/inputs/kapacitor/README.md
plugins/inputs/kapacitor/kapacitor.go
plugins/inputs/kapacitor/kapacitor_test.go

Fix typo in name of gc_cpu_fraction field

---

plugins/parsers/influx/machine.go
plugins/parsers/influx/machine.go.rl
plugins/parsers/influx/machine_test.go
plugins/parsers/influx/parser.go
plugins/parsers/influx/parser_test.go

In addition to the CR/FF change, this fixes a panic/inf loop if you call Next() on the parser after a io.Reader error.
closes #7406

Allow CR and FF inside of string fields and fix parser panic

---

plugins/parsers/json/parser.go
plugins/parsers/json/parser_test.go

I am new to this, so please let me know if this is not appropriate.
My data is sent as a single JSON packet but the resulting measurements generated from the JSON array all had different timestamps.  This made it difficult to work with the data.  Because all objects in the JSON array arrive at the same time they should have the same timestamp.  With the same timestamp the data has the correlation that it should.

plugins/parsers/json: Use same timestamp for all objects in arrays

---

plugins/outputs/socket_writer/README.md
plugins/outputs/socket_writer/socket_writer.go
plugins/outputs/socket_writer/socket_writer_test.go

Add `ContentEncoder` to `socket_writer` output plugin for packet-based connections (UDP, unixgram).
Implements [Feature 7354 - Add ContentEncoder to socket_writer output plugin for UDP connections](https://github.com/influxdata/telegraf/issues/7354)

Feature 7354 - Add ContentEncoder to socket_writer output plugin for packet-based connections

---

README.md
plugins/processors/all/all.go
plugins/processors/filepath/README.md
plugins/processors/filepath/filepath.go
plugins/processors/filepath/filepath_test.go
plugins/processors/filepath/filepath_test_helpers.go
plugins/processors/filepath/filepath_windows_test.go

Signed-off-by: Andres Alvarez <1671935+kir4h@users.noreply.github.com>
This PR resolves #7342, adding a new processor plugin to include some path operations that are available through the `filepath` golang package.
First time dealing with a processor and did some refactors on the way, so any feedback is more than welcome.
closes #7342

Add filepath processor plugin

---

internal/content_coding.go
internal/content_coding_test.go
plugins/inputs/socket_listener/socket_listener.go
plugins/inputs/socket_listener/socket_listener_test.go

Fix gzip support in socket_listener with tcp sockets

---

plugins/inputs/sqlserver/sqlserver.go

Since this new measurement has not been released yet, there should be no problem in renaming to better match the query name in the configuration file, but also makes it more meaningful, in fact a volume does not always correspond to a disk.
- the configuration query name is "VolumeSpace"
- the current measurement name is "sqlserver_disk_space"
- the new name is "sqlserver_volume_space"

SqlServer - rename measurement "sqlserver_disk_space" to "sqlserver_volume_space"

---

plugins/serializers/splunkmetric/README.md

This PR updated documentation about HEC JSON format limitation and possible workaround for it.
See https://github.com/influxdata/telegraf/issues/7456. I also been able to find regular questions about it in the tracker.

Add information about HEC JSON format limitations

---

agent/agent.go
agent/tick.go
agent/tick_test.go
docs/LICENSE_OF_DEPENDENCIES.md
go.mod
go.sum
internal/internal.go

Fix several drift issues when using `round_interval` and use a rolling ticker for doing the full write flush.  In the future I would like to rework the output to only do full flushes after `flush_interval` seconds has elapsed without a batch write.  This will reduce unneeded calls to write but can be done separately.
It is possible that we will want to use the "RollingTicker" for inputs as well, since it would give you the best collection spread.  However, making the switch when using jitter requires changing the configuration in order to maintain the same collection pace, so I haven't switched in this pull request.
closes #5937
closes #5335
closes #4232
closes #4652

Rework plugin tickers to prevent drift and spread write ticks

---

plugins/inputs/sqlserver/README.md
plugins/inputs/sqlserver/sqlserver.go
plugins/inputs/sqlserver/sqlserver_test.go

Closes #7269
This PR adds a new measurement called "sqlserver_cpu" with the following structure:
| measurement | sql_instance | sqlserver_process_cpu | system_idle_cpu | other_process_cpu |
| ------ | ------ | ------ | ------ | ------ |
| sqlserver_cpu | QDLP03:SQL2019 | 0 | 95 | 5 |
It reads the CPU data from the ring buffer, therefore it allows to get CPU data from any version of SQL Server (including express and standard).
In the source, the data are updated once every minute.
As of now, it works only on the On-prem version of SQL Server (from SQL 2008 to 2019) but I'm looking to make it work also on Azure SQL DB and managed Instance. (maybe using sys.dm_db_resource_stats or sys.server_resource_stats)

Sql server - ring buffer cpu v2

---

plugins/processors/date/README.md
plugins/processors/date/date.go
plugins/processors/date/date_test.go

Pull Request for Issue https://github.com/influxdata/telegraf/issues/7449
* Adds field_key to settings
* Checks one of `field_key` or `tag_key` set, errors if both or neither
* Adds sentinel values to `date_format` for output to integer field:
* `unix`, `unix_ms`, `unix_us`, `unix_ns`
* Unit tests added with coverage of added lines, and README updated

Add field output to date processor and integer output formats

---

plugins/processors/enum/README.md
plugins/processors/enum/enum.go
plugins/processors/enum/enum_test.go

[processors] Add integer support to `processors.enum`

---

plugins/processors/dedup/dedup.go
plugins/processors/dedup/dedup_test.go

Handle multiple metrics with the same timestamp in dedup plugin

---

plugins/outputs/wavefront/README.md
plugins/outputs/wavefront/wavefront.go
plugins/outputs/wavefront/wavefront_test.go

Fixes issue #7447 
The total length of tag key + tag value isn't allowed to exceed 254 characters when sending metrics to Wavefront. By default, these metrics are discarded by wavefront. The new ```truncate_tags``` flag in the configuration file causes the Wavefront output to truncate the tag value so that the length of the key + value never exceeds 254. If the tag key is longer than 254 characters, the metric point is dropped and a warning is logged.
The ```truncate_tags``` flag is turned off by default to ensure backwards compatibility.

[output.wavefront] Added truncate_tags setting

---

plugins/inputs/ping/README.md

Fix typo in the `ping` input plugin docs

Fix Typo In Ping Input Plugin Docs

---

plugins/inputs/sqlserver/sqlserver.go

On Elastic pools, sys.dm_os_perfmon_counters has counters for all databases represented by GUIDS. To resolve the GUID to a DB name have to join with sys.databases
However sys.database only has a row for the current database and not all databases and hence the instance_name for those rows would be NULL and insert would fail with
"Cannot insert the value NULL error"
Fix is to resolve DB name for the current database, leave the GUID for perfmon counters of other databases.
closes #7325

Fix for perfmon instance_name for #7325

---

config/config.go
etc/telegraf.conf
plugins/outputs/graphite/README.md
plugins/outputs/graphite/graphite.go
plugins/outputs/graphite/graphite_test.go
plugins/outputs/instrumental/instrumental.go
plugins/serializers/graphite/README.md
plugins/serializers/graphite/graphite.go
plugins/serializers/graphite/graphite_test.go
plugins/serializers/registry.go

Fix #7539
Add character selection to separating the metric name and field for graphite tag metrics.

add character selection to separating the metric name and field for graphite tag

---

plugins/inputs/mongodb/README.md
plugins/inputs/mongodb/mongodb.go
plugins/inputs/mongodb/mongodb_server.go

It can be expensive to compute these metrics. In particular, when
retrieving the amount of jumbo chunks, an index is not being used and
consequently the query triggers an expensive COLLSCAN. For big
databases, this query has negative impact on the cluster performance.
I left the default value of `gather_cluster_status` to `true` so as not to break
the current behavior.

Optionally gather mongodb cluster status

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

fixes https://github.com/influxdata/telegraf/issues/7403

7403 - Allow to collect HTTP Headers thanks to http_response

---

plugins/parsers/influx/parser.go
plugins/parsers/influx/parser_test.go

Error message before this PR:
```
2020-05-21T22:54:10Z E! [inputs.file] Error in plugin: metric parse error: expected field at 45:1543: "remote_status,platform=some,env=prd,dst=clf code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,ok=1i,code=200i,o …
```

make sure parse error includes offending text

---

agent/agent.go
cmd/telegraf/telegraf.go
internal/usage.go
internal/usage_windows.go
models/running_output.go
plugins/outputs/file/file.go

This PR contains several changes over #7408:
- Resolved conflicts on #7408 due to ticker changes.
- Fixed buffering issues by running full pipeline.
- Added special handling for cpu/mongodb/procstat to mirror `--test` behavior.
- Allowed using `--once` with the `--test-wait` flag.
- Renamed cli option to `--once` (let me know if you think this is to terse)
- Updated usage message
- Combined with `--test`, which now runs processors and aggregators at last.
There are several behavior changes compared to current behavior:
- `--test` now runs all inputs, previously stopped on first failure.  Exit code is based on agent internal/selfstats.
- `--test` mode now runs all inputs concurrently, this means that output lines will generally be mixed.
closes #6190
closes #7408
closes #7415

Add support for once mode; run processors and aggregators during test.

---

plugins/inputs/execd/shim/goshim.go
plugins/inputs/execd/shim/shim_test.go
plugins/inputs/execd/shim/testdata/plugin.conf

Enable `shim` to interpret environment variables by changing `config.parseConfig` to public.

Add support for env variables to shim config

---

scripts/post-install.sh
scripts/post-remove.sh

Since the pre/post install scripts check for distribution names, a lot of perfectly valid distributions are left out just because they are not "ubuntu", "debian" or "redhat". This PR simply adds a check for Solus to (un)install the systemd file.

Add support for Solus distribution

---

plugins/inputs/snmp_trap/README.md
plugins/inputs/snmp_trap/snmp_trap.go
plugins/inputs/snmp_trap/snmp_trap_test.go

In V3 traps, the trap sender sends a context name and engine ID.  Before this change, telegraf's snmp_trap input passed a context name and engine ID to Gosnmp.  Gosnmp doesn't use these when receiving traps, only when sending, so this change removed them.  The input now also adds tags for the context name and engine ID that we receive in the trap.
Also clean up variable naming in tests.

Add tags to snmp_trap input for context name and engine ID

---

agent/agent.go
aggregator.go
config/config.go
config/config_test.go
go.mod
input.go
models/running_processor.go
models/running_processor_test.go
output.go
plugin.go
plugins/processors/registry.go
plugins/processors/streamingprocessor.go
processor.go

add support for streaming processors

---

plugins/inputs/icinga2/README.md
plugins/inputs/icinga2/icinga2.go
plugins/inputs/icinga2/icinga2_test.go

The plugin uses the icinga2 server name, but does not provide the actual host the check is running on.
This fixes that by adding a new field called `server`, where `server` is the icinga2 server and `source` is hostname of the service or host object that icinga2 performing the checks on.
closes #7004

Fix source field for icinga2 plugin (#7004)

---

go.mod
go.sum
plugins/inputs/procstat/native_finder.go
plugins/inputs/procstat/native_finder_notwindows.go
plugins/inputs/procstat/native_finder_test.go
plugins/inputs/procstat/native_finder_windows.go

Update to github.com/shirou/gopsutil v2.20.5

---

config/config.go
plugins/parsers/csv/README.md
plugins/parsers/csv/parser.go
plugins/parsers/csv/parser_test.go
plugins/parsers/registry.go

example:
- csv_timezone = "Asia/Jakarta"
closes: #7618

Add timezone configuration to csv data format

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

7595 - Be able to add the body's content as field with http_response

---

plugins/inputs/execd/shim/goshim.go
plugins/inputs/execd/shim/shim_posix_test.go
plugins/inputs/execd/shim/shim_test.go

pre-patch was seeing this fail about 1 in 50. 
now passes 10000 test runs with no failures.

Flaky shim test

---

agent/tick_test.go
go.mod
go.sum

Fix for test failure:
```
--- FAIL: TestAlignedTicker (0.04s)
tick_test.go:44: 
Error Trace:	tick_test.go:44
Error:      	Not equal: 
expected: []time.Time{time.Time{wall:0x0, ext:62135596810, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596820, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596830, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596840, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596850, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596860, loc:(*time.Location)(nil)}}
actual  : []time.Time{time.Time{wall:0x0, ext:62135596810, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596820, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596830, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:62135596840, …
```

Fix race issue in tick_test.go

---

plugins/outputs/influxdb/README.md
plugins/outputs/influxdb_v2/README.md
plugins/serializers/influx/README.md
plugins/serializers/influx/influx.go
plugins/serializers/influx/influx_test.go

Currently a tag key or value with a trailing backslash will produce an error like:
```
E! [outputs.influxdb] When writing to [http://localhost:8086]: received error unable to parse 'mem,host=loaner,path=C:\ free=3166146560i 1591645472000000000': invalid tag format; discarding points
```
With this change the trailing slashes are stripped.  Other methods were considered include using a space or a replacement char such as` _`.  I decided not to use a space since it might cause confusion when writing queries by hand and in the cli.  I decided against underscore because due to how ugly it is.
I know ideally we would have some form of https://github.com/influxdata/influxdb/issues/6037, but I believe this needs to be worked out separately from a fix for the current line protocol.
closes #7558

Remove trailing backslash from tag keys/values

---

models/running_processor_test.go
plugins/inputs/http_response/README.md
plugins/processors/streamingprocessor.go

7692 - The processors are no more initialized

---

plugins/inputs/procstat/native_finder.go
plugins/inputs/procstat/native_finder_notwindows.go
plugins/inputs/procstat/native_finder_windows.go

darwin:
before
```
$ go test -short ./plugins/inputs/procstat/... -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/influxdata/telegraf/plugins/inputs/procstat
BenchmarkPattern-12        	       1	1600582288 ns/op	 5874216 B/op	   48391 allocs/op
BenchmarkFullPattern-12    	       1	3620761444 ns/op	11612472 B/op	   86876 allocs/op
PASS
ok  	github.com/influxdata/telegraf/plugins/inputs/procstat	5.450s
```
after
```
$ go test -short ./plugins/inputs/procstat/... -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/influxdata/telegraf/plugins/inputs/procstat
BenchmarkPattern-12        	      57	  25058656 ns/op	  309886 B/op	    2991 allocs/op
BenchmarkFullPattern-12    	       1	1798469106 ns/op	 6176720 B/op	   41895 allocs/op
PASS
ok …
```

procstat speed improvement

---

plugins/inputs/kube_inventory/README.md
plugins/inputs/kube_inventory/pod.go
plugins/inputs/kube_inventory/pod_test.go

Add state reason, which can eventually deprecated `terminated_reason`, to pod_container metrics; as well as a tag to represent the readiness of the container.

feat: add additional tags/fields to pod metrics

---

plugins/inputs/sqlserver/sqlserver.go

This PR just removes the removal of trailing backslashes from the query itself.
Now that #7558 has been closed, this kind of logic is not needed inside the query itself.

Sql Server iputn - removed trailing backslash trim

---

plugins/outputs/prometheus_client/README.md
plugins/serializers/prometheus/README.md

Document that string fields do not produce prometheus metrics

---

plugins/inputs/ping/ping_notwindows.go

BSD-derived ping's use exit code 2 for timeout, not 1

fix ping exit code handling on non-Linux

---

internal/exec.go
plugins/inputs/sensors/sensors.go

Amdgpu drivers produces an output that cannot be handled by sensors:
root@qt5222:~# sensors -A -u
amdgpu-pci-0300
vddgfx:
ERROR: Can't get value of subfeature in0_input: Can't read
vddnb:
ERROR: Can't get value of subfeature in1_input: Can't read
edge:
temp1_input: 40.000
temp1_crit: 80.000
temp1_crit_hyst: 0.000
00000400100-mdio-4
temp1:
temp1_input: 59.000
temp1_crit: 100.000
temp1_max_alarm: 0.000
This results in an invalid parsing of its ouput. Eg:
> sensors,chip=ERROR:\ Can't\ get\ value\ of\ subfeature\ in0_input:\ Can't\ read,feature=isl_curr_soc,host=qt5222,serial=${SERIAL_NUMBER} curr_input=1.6 1592920794000000000
The invalid parsing is due to the different buffer size of stdout and
stderr. Which results on stderr output out of sync with stdout.
Since we do not need the output of …

sensors: Handle error sentences from sensors

---

plugins/inputs/sqlserver/sqlserver.go

Counter type enables understanding of how to visualize a performance counter as there are different types of counters. Without which you have to have knowledge of what type each counter is.
Adding perfmon counter type to  description at https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.performancecountertype?view=dotnet-plat-ext-3.1

Add counter type to perfmon collector

---

plugins/inputs/smart/smart.go
plugins/inputs/smart/smart_test.go

This PR adds additional nvme specific attributes to smart plugin.
The attributes are verified with [NVMe Specification 1.4](https://nvmexpress.org/wp-content/uploads/NVM-Express-1_4-2019.06.10-Ratified.pdf) and tested with Crucial MP510.
There is no mention of specific attributes in smart README file.

Add missing nvme attributes to smart plugin

---

plugins/inputs/sqlserver/sqlserver.go

The sql_server_properties measure had a few incorrect values for Azure SQL DB
a. Number of DB's online/offline/suspect is irrelevant for a single DB and was counting master had incorrect values of 2
b. Space usage (Max/unallocated) was also set to NULL prior
c. Given all the 3 parts of this collector required adhoc queries, eliminated the unnecessarily table variable to simplify query

Fix incorrect Azure SQL DB server properties

---

plugins/inputs/snmp_trap/snmp_trap_test.go

Clean up race detected by 'go test -race' in snmp_trap input plugin

Fix SNMP trap test race

---

plugins/inputs/kafka_consumer/kafka_consumer_test.go

Data race when assigning to `err` variable.
related: #7729

Fix data race in kafka_consumer_test.go

---

plugins/inputs/suricata/suricata_test.go

Relates to issue #7729 - fixes data race in input plugin suricata tests'.
```
go test -short -race ./plugins/inputs/suricata/...
```
Before:
```log
==================
WARNING: DATA RACE
Write at 0x00c0000b4020 by goroutine 18:
github.com/influxdata/telegraf/plugins/inputs/suricata.TestSuricata()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/inputs/suricata/suricata_test.go:77 +0x68d
testing.tRunner()
/usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:991 +0x1eb
Previous read at 0x00c0000b4020 by goroutine 20:
github.com/influxdata/telegraf/plugins/inputs/suricata.(*Suricata).handleServerConnection()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/inputs/suricata/suricata.go:116 +0x6e
Goroutine 18 (running) created at:
testing.(*T).Run() …
```

Fix data race in plugins/inputs/suricata/suricata_test.go

---

plugins/inputs/x509_cert/x509_cert.go
plugins/inputs/x509_cert/x509_cert_test.go

Allow any key usage type on x509 certificate

---

plugins/outputs/prometheus_client/prometheus_client_v2_test.go
plugins/serializers/prometheus/collection.go
plugins/serializers/prometheus/prometheus_test.go

I don't remember why I disallowed this originally, but it doesn't seem to be a requirement to have quantiles for a summary or buckets for a histogram.
closes: #7705

Allow histograms with no buckets and summary without quantiles

---

agent/agent.go
config/config.go
docs/CONFIGURATION.md
models/running_input.go
models/running_output.go

Allow overriding the agent precision and collection jitter on a per-plugin basis.  Unlike the agent precision, this setting is applied to service inputs as well.
It is possible to shoot yourself in the foot with this, care will need to be taken to avoid have event-style metrics merged in the database.  See linked issues for use-cases.
closes #3634
closes #1589
closes #5853

Allow overriding the collection_jitter and precision per input

---

plugins/inputs/tail/tail_test.go

Relates to issue #7729 - fixes data race in input plugin tail tests'.
```
go test -short -race ./plugins/inputs/tail/... 
```
Before:
```
2020/07/02 21:54:28 D! [] Tail added for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/961769049"
2020/07/02 21:54:28 D! [] Tail removed for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/961769049"
2020/07/02 21:54:28 D! [] Tail added for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/918683620"
2020/07/02 21:54:28 D! [] Recording offset 61 for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/918683620"
2020/07/02 21:54:28 D! [] Tail removed for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/918683620"
2020/07/02 21:54:28 D! [] Tail added for "/var/folders/lh/yzgq0xxj1kbc5cbchsjzps_40000gn/T/134852083"
==================
WARNING: DATA …
```

Fix data race in plugins/inputs/tail/tail_test.go

---

plugins/outputs/cloud_pubsub/pubsub_test.go
plugins/outputs/cloud_pubsub/topic_stubbed.go

Relates to issue #7729 - fixes data race in output plugin cloud_pubsub tests'.
```
go test -short -race ./plugins/outputs/cloud_pubsub/...
```
Before:
```
WARNING: DATA RACE
Read at 0x00c00041a078 by goroutine 16:
github.com/influxdata/telegraf/plugins/outputs/cloud_pubsub.TestPubSub_WriteMultiple()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/outputs/cloud_pubsub/pubsub_test.go:76 +0x3d1
testing.tRunner()
/usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:991 +0x1eb
Previous write at 0x00c00041a078 by goroutine 19:
github.com/influxdata/telegraf/plugins/outputs/cloud_pubsub.(*stubTopic).sendBundle.func1()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/outputs/cloud_pubsub/topic_stubbed.go:176 +0x3f4
google.golang.org/api/support/bundler.(*Bundler).handle() …
```

Fix data race in plugin output cloud_pubsub tests

---

plugins/inputs/ecs/README.md
plugins/inputs/ecs/client.go
plugins/inputs/ecs/client_test.go
plugins/inputs/ecs/ecs.go
plugins/inputs/ecs/ecs_test.go

Justification: v2 `metadata and Docker stats are available to tasks that use the awsvpc network mode ...` only [v2]. v3 metadata is available regardless of the network mode and provides the same statistics as the v2 metadata.
[v2] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html

inputs.ecs: add v3 metadata support.

---

internal/snmp/config.go
internal/snmp/wrapper.go
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go
plugins/processors/all/all.go
plugins/processors/ifname/README.md
plugins/processors/ifname/cache.go
plugins/processors/ifname/cache_test.go
plugins/processors/ifname/ifname.go
plugins/processors/ifname/ifname_test.go

Add ifname processor plugin

---

plugins/inputs/nginx_sts/README.md
plugins/inputs/redfish/README.md
plugins/outputs/execd/README.md
plugins/outputs/newrelic/README.md
plugins/processors/defaults/README.md
plugins/processors/execd/README.md
plugins/processors/filepath/README.md
plugins/processors/ifname/README.md
plugins/processors/port_name/README.md
plugins/processors/reverse_dns/README.md
plugins/processors/starlark/README.md

Add minimum version for new plugins

---

plugins/inputs/cloud_pubsub/README.md

Small typo in the documentation for the cloud_pubsub input plugin

documentation: typo cloud_pubsub plugin

---

etc/telegraf.conf
plugins/outputs/cloud_pubsub/README.md
plugins/outputs/cloud_pubsub/pubsub.go

Small typo in the documentation for the cloud_pubsub output plugin.

documentation: typo outputs cloud_pubsub

---

plugins/inputs/tail/tail_test.go

This is an attempt to fix the intermittent test case:
```
2020/07/10 15:10:08 D! [] Tail added for "/var/folders/pt/0xykrh9j62g34sc7znh47kbc0000gn/T/643693879"
2020/07/10 15:10:08 E! [] Malformed log line in "/var/folders/pt/0xykrh9j62g34sc7znh47kbc0000gn/T/643693879": ["cpu mytag= foo usage_idle= 100"]: metric parse error: expected field at 1:11: "cpu mytag= foo usage_idle= 100"
--- FAIL: TestTailBadLine (0.00s)
tail_test.go:54: 
Error Trace:	tail_test.go:54
Error:      	"2020/07/10 15:10:08 D! [] Tail removed for "/var/folders/pt/0xykrh9j62g34sc7znh47kbc0000gn/T/643693879"
" does not contain "Malformed log line"
Test:       	TestTailBadLine
FAIL
FAIL	github.com/influxdata/telegraf/plugins/inputs/tail	0.252s
```

Close file to ensure it has been flushed

---

CHANGELOG.md
models/buffer.go
models/buffer_test.go
models/running_output_test.go

As requested in https://github.com/influxdata/telegraf/issues/5633#issuecomment-655687905, here the PR :)
closes #5633

Send metrics in FIFO order

---

plugins/processors/ifname/README.md
plugins/processors/ifname/cache.go
plugins/processors/ifname/cache_test.go
plugins/processors/ifname/ifname.go
plugins/processors/ifname/ifname_test.go
plugins/processors/ifname/ttl_cache.go
plugins/processors/ifname/ttl_cache_test.go

Also refetch interfaces when interface number is missing

ifname processor: expire old cached entries

---

agent/agent.go

Initialize aggregation processors

---

plugins/inputs/suricata/README.md

https://github.com/influxdata/telegraf/issues/7843

Update README.md with FreeBSD necessary tuning

---

internal/internal_test.go
plugins/inputs/bind/bind_test.go
plugins/inputs/cassandra/cassandra_test.go
plugins/inputs/cloudwatch/cloudwatch_test.go
plugins/inputs/filecount/filesystem_helpers_test.go
plugins/inputs/github/github_test.go
plugins/inputs/gnmi/gnmi_test.go
plugins/inputs/jolokia/jolokia_test.go
plugins/inputs/statsd/datadog_test.go
plugins/inputs/syslog/rfc5426_test.go
plugins/parsers/collectd/parser_test.go
plugins/parsers/grok/parser_test.go

[NoError](https://godoc.org/github.com/stretchr/testify/require#NoError) is for asserting no error was return
[Error](https://godoc.org/github.com/stretchr/testify/require#Error) is for asserting an error was returned
```golang
return Fail(t, fmt.Sprintf("Received unexpected error:\n%+v", err), msgAndArgs...)
```
```golang
return Fail(t, "An error is expected but got nil.", msgAndArgs...)
```
When these fail their message explicitly calls out that we were or were not expecting an error. This communicates the intent of the assertion.

prefer testify error funcs over nil checks

---

plugins/inputs/execd/README.md
plugins/inputs/execd/execd.go
plugins/outputs/execd/README.md
plugins/outputs/execd/execd.go
plugins/processors/execd/README.md
plugins/processors/execd/execd.go

Addresses some of the concerns raised in https://github.com/influxdata/telegraf/issues/7859. Clarify docs and warn users if the plugin appears to be used in an unintended way.

clarify docs and add warning if execd is misconfigured

---

config/types.go
plugins/inputs/execd/execd.go
plugins/inputs/execd/execd_test.go

resolves https://github.com/influxdata/telegraf/issues/7858

fix issue with execd restart_delay being ignored

---

plugins/inputs/gnmi/gnmi.go

Should fix the intermittent test failure.
#Required for all PRs:

Recv next message after send returns EOF in gnmi input

---

models/log.go
models/running_aggregator.go
models/running_input.go
models/running_output.go
models/running_processor.go
plugins/common/shim/config.go
plugins/common/shim/input.go
plugins/common/shim/logger.go
plugins/common/shim/output.go
plugins/common/shim/processor.go
plugins/inputs/execd/shim/goshim.go

- warn on loading default config
- move stdin reader to a goroutine so it doesn't block forever on local ctrl-c shutdown
- add shim logger interface that writes to stderr by default to work well with the shim environment.
- set `Log telegraf.Logger` if it's defined on plugins before calling plugin.Init() to avoid panics from plugins that expect to use it.
- add deprecation warning about using old shim.

shim logger improvements

---

Makefile

This fixes an issue with the 1.15.0 builds of the rpm and deb packages for non-amd64 platforms which have the arch set incorrectly and cannot be installed.

Fix arch name in deb/rpm builds

---

plugins/inputs/mongodb/mongodb_data.go
plugins/inputs/mongodb/mongodb_data_test.go
plugins/inputs/mongodb/mongostat.go

Added new metric "pages written from cache" for MongoDB
Below is the test result
mongodb,host=my-system,hostname=127.0.0.1:27017 active_reads=1i,active_writes=0i,aggregate_command_failed=0i,aggregate_command_total=0i,assert_msg=0i,assert_regular=0i,assert_rollovers=0i,assert_user=8i,assert_warning=0i,available_reads=127i,available_writes=128i,commands=74i,commands_per_sec=12i,connections_available=203i,connections_current=1i,connections_total_created=1i,count_command_failed=0i,count_command_total=1i,cursor_no_timeout=0i,cursor_no_timeout_count=0i,cursor_pinned=0i,cursor_pinned_count=0i,cursor_timed_out=0i,cursor_timed_out_count=0i,cursor_total=0i,cursor_total_count=0i,delete_command_failed=0i,delete_command_total=0i,deletes=0i,deletes_per_sec=0i,distinct_command_failed=0i,distinct_command_ …

MongoDB: Added new metric "pages written from cache"

---

plugins/common/encoding/decoder.go
plugins/common/encoding/decoder_reader.go
plugins/inputs/tail/tail_test.go

The Reader from x/text stops reading after the first io.EOF error is returned, preventing further tailing of the file when new lines are appended.  This PR is based on #7886 and adds a unit test of the EOF condition.
closes #7880

Fix tail following on EOF

---

plugins/outputs/opentsdb/opentsdb.go

When in prometheus metrics we have a value with NaN or Inf, Telegraf cannot to send metrics in TSDB and write the error in stdout:
```
2020-07-28T08:42:32Z E! [agent] Error writing to outputs.opentsdb: Metric serialization error json: unsupported value: NaN
```
I fixed this error like in json serializer: https://github.com/influxdata/telegraf/blob/master/plugins/serializers/json/json.go#L61

Fix for opentsdb output-plugin for NaN and Inf in float64 value

---

EXTERNAL_PLUGINS.md

This documentation update points to a simple execd shim that can
poll AWS Alarms at given time intervals.
Closes #7931 
Required for all PRs:

Support for AWS Cloudwatch Alarms #7931

---

plugins/inputs/sqlserver/sqlserver.go

closes #6978
Added a new counter 'Lock Timeouts (timeout > 0)/sec' to the sqlserver_performance measurement.

SQL Server - added new counter - Lock Timeouts (timeout > 0)/sec

---

.gitignore

this PR adds the mac `.DS_Store` files to the `.gitignore` file

chore: extend gitignore to ignore .DS_Store

---

plugins/processors/starlark/README.md
plugins/processors/starlark/testdata/pivot.star

add pivot example for starlark processor

---

plugins/outputs/application_insights/README.md
plugins/outputs/application_insights/application_insights.go
plugins/outputs/application_insights/transmitter.go

Added the ability to set the endpoint url in the configuration file

---

config/config.go

Fixes #7839 
This can also be done by directly generating the map and passing that to the `PluginNameCounts` method, let me know if this is more appropriate.

Cleanup duplicates in loaded plugins list

---

plugins/processors/starlark/testdata/number_logic.star
plugins/processors/starlark/testdata/ratio.star
plugins/processors/starlark/testdata/rename.star
plugins/processors/starlark/testdata/scale.star

sorry for all the commits, was doing it through the github ui 😸

add example input/outputs to starlark examples

---

plugins/inputs/ping/ping_notwindows.go
plugins/inputs/ping/ping_test.go

FreeBSD has separate ping binaries for IPv4 and IPv6, `ping(8)` and `ping6(8)`.
Both have differently named options (or sometimes even with the same name but different function...),
and differently formatted outputs.
When using the `exec` method, the ping plugin, searches for a `ttl=` string to get the remaining TTL of the echo response, however `ping6` has a different output format and returns the TTL as `hlim=<integer>`. Thus the plugin throws this error:
```
E! [inputs.ping] Error in plugin: Fatal error processing ping output: 2a09::
```
Furthermore the ping plugin isn't aware of the different command options and always tries to use the arguments for the IPv4 `ping` command, which fails:
```
E! [inputs.ping] Error in plugin: host 2a09::: ping6: Non-recoverable failure in name …
```

Fix Ping Input plugin for FreeBSD's ping6

---

plugins/processors/starlark/README.md
plugins/processors/starlark/starlark_test.go
plugins/processors/starlark/testdata/number_logic.star
plugins/processors/starlark/testdata/pivot.star
plugins/processors/starlark/testdata/ratio.star
plugins/processors/starlark/testdata/rename.star
plugins/processors/starlark/testdata/scale.star
plugins/processors/starlark/testdata/value_filter.star

We can vastly improve the quality of the starlark examples by executing them, along with their documentation standards, as tests.
Using `Example Input:` and `Example Output:` as section header markers, we can parse the subsequent metrics out and use them as inputs to test the Starlark function, comparing the processed metrics to the example output, and failing if it does not match.
Example docs standards + function:
```python
#
#
renames = {
'lower': 'min',
'upper': 'max',
}
def apply(metric):
for k, v in metric.tags.items():
if k in renames:
metric.tags[renames[k]] = v
metric.tags.pop(k)
for k, v in metric.fields.items():
if k in renames:
metric.fields[renames[k]] = v
metric.fields.pop(k)
return metric
```
also the multi-line string format works, too:
```python
'''
In this example we …
```

improve the quality of starlark docs by executing them as tests

---

plugins/inputs/eventhub_consumer/eventhub_consumer.go

The existing conversion produces a vet check (which is enabled by default starting with 1.15) when running `go test` in 1.15 as per https://golang.org/doc/go1.15#vet.
```
$ make test
go test -short -race ./...
?       github.com/influxdata/telegraf  [no test files]
plugins/inputs/eventhub_consumer/eventhub_consumer.go:379:40: conversion from int16 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
...
```

Fix string to int conversion in eventhub consumer

---

plugins/processors/ifname/ifname.go

This allows for debugging why metrics are not processed. (like in #8012)
I'm only not sure about the used severity.

Add addTag debugg in ifname plugin

---

docker-compose.yml
plugins/inputs/aerospike/README.md
plugins/inputs/aerospike/aerospike.go
plugins/inputs/aerospike/aerospike_test.go

refactored to allow non integration tests
fix tests to work with aerospike 4.9.0.11

Add set, and histogram reporting to aerospike telegraf plugin

---

Makefile
scripts/alpine.docker
scripts/stretch.docker

Looks like `make go-install` should probably not have been removed, as it was still in use. Likely daniel thought that it was not relevant to the new makefile setup, which focuses on creating our package builds, however the docker file also expects to be able to call into it so it doesn't have to manage env variables. This is likely a reasonable assumption, and not realistic to expect only one consumer of the `Makefile`, so I've added the function back in.

fix docker build. update dockerfiles to Go 1.14

---

plugins/common/shim/goshim.go
plugins/common/shim/goshim_test.go
plugins/common/shim/input.go
plugins/common/shim/output.go
plugins/common/shim/processor.go

Fixes issue in shim around use of .AddError. accumulator hadn't properly set up a logger to use.

fix bug in shim logger affecting AddError

---

Makefile
plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go

All recent PRs get the following CI error 
```
go vet $(go list ./... | grep -v ./plugins/parsers/influx)
plugins\inputs\win_perf_counters\win_perf_counters_integration_test.go:188:69: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
plugins\inputs\win_perf_counters\win_perf_counters_integration_test.go:192:75: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
plugins\inputs\win_perf_counters\win_perf_counters_integration_test.go:236:74: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
plugins\inputs\win_perf_counters\win_perf_counters_integration_test.go:241:75: conversion from int to string yields a …
```

Fix CI AppVeyor 'make check' errors for go 1.15 on windows

---

go.mod
go.sum

Additionally to the version bump of gopsutils we need to update
golang.org/x/sys as gopsutils strongly depends on this package.
We have to exactly use the sys-version (that exact commit) as
directly afterwards a variable (SYS__SYSCALL) is removed which
breaks gopsutils 2.20.7 (which is the latest release currently).
This superseeds [PR #7988](https://github.com/influxdata/telegraf/pull/7988) and is related to [PR #8047](https://github.com/influxdata/telegraf/pull/8047).

Update gopsutils to v.2.20.7

---

Makefile

`COMMIT` doesn't seem to be defined anywhere which causes:
```
docker build -f scripts/stretch.docker -t "telegraf:" .
invalid argument "telegraf:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [docker-image] Error 125
```
whereas `commit` is defined in https://github.com/influxdata/telegraf/blob/master/Makefile#L10

Fix docker-image make target

---

etc/telegraf.conf
plugins/outputs/elasticsearch/README.md
plugins/outputs/elasticsearch/elasticsearch.go

This PR solves #7891 
ID has been computed as hash computed with sha256(concat(timestamp,measurement,series-hash)),enables resend or update data avoiding ES duplicated documents.
Tested with several loads with the same data and no duplicated documents have been generated.
Hope this PR could help everybody.

added force_document_id option to ES output enable resend data avoiding duplicated ES documents, fix #7891

---

plugins/inputs/snmp/README.md

Based on [Daniel's comment](https://community.influxdata.com/t/telegraf-snmp-select-oids/4965) on community.influxdata.com, update `snmp` input plugin documentation to clarify how to select columns from a table.

inputs/snmp: document partial table collection

---

EXTERNAL_PLUGINS.md

I would like to add a link to a new [external input plugin](https://github.com/BattleBas/octoprint-telegraf-plugin) I created to gather data from the [OctoPrint](https://octoprint.org/) API.
At the moment it gathers 3d printing state (operational, printing, etc.) and tool temperature (hotend, bed). The information looks great in InfluxDB 2.0 cloud dashboards, I look forward to add more info.
The [documentation](https://github.com/influxdata/telegraf/blob/master/plugins/common/shim/README.md#Congratulations) recommended I make a pull request to include new plugins and I thought that was a good idea.
Cheers!

Update doc to add new external plugin: OctoPrint

---

plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go

Following this discussion https://github.com/influxdata/telegraf/pull/7828#issuecomment-692747173, that can be great if this come with 1.16 
All credits for @magichair, I only revert the commit who remove the ready route
Thanks!

Adding ready route to inputs.influxdb_v2_listener

---

plugins/inputs/sqlserver/sqlqueriesV2.go

Added more performance counters to SqlServer input plugin

---

models/log.go
models/running_aggregator.go
models/running_input.go
models/running_output.go
models/running_processor.go
models/running_processor_test.go
plugins/processors/streamingprocessor.go

resolves the underlying issues in https://github.com/influxdata/telegraf/issues/8173

fix panic on streaming processers using logging

---

plugins/inputs/snmp_trap/README.md
plugins/inputs/snmp_trap/snmp_trap.go
plugins/inputs/snmp_trap/snmp_trap_test.go

If the community string is available, add it as a tag.  This will allow use of tagpass to drop traps that don't have the expected community string.
closes #8182

SNMP Trap community string tag

---

go.mod
go.sum
plugins/processors/starlark/starlark.go
plugins/processors/starlark/testdata/json.star

eg
```python
#
#
load("json", "encode", "decode", "indent")
def apply(metric):
j = decode(metric.fields.get('value'))
metric.fields.pop('value')
metric.tags["label"] = j.get("label")
metric.fields["count"] = j.get("count")
return metric
```

 add json parsing support to starlark

---

go.mod
go.sum
plugins/inputs/redis/README.md
plugins/inputs/redis/redis.go
plugins/inputs/redis/redis_test.go

This PR is an attempt to pull additional metrics on redis from arbitrary commands. The logic in this PR accounts for types (`string`, `integer`, and `float`), and we could add more types.
Issue addressed: https://github.com/influxdata/idpe/issues/8711
Community issue Addressed: https://github.com/influxdata/telegraf/issues/1027

feat: add functionality to get values from redis commands

---

docs/LICENSE_OF_DEPENDENCIES.md
go.mod
go.sum
plugins/inputs/docker/docker_test.go
plugins/inputs/docker/docker_testdata.go
plugins/inputs/github/github.go
plugins/inputs/github/github_test.go

This PR solves: https://github.com/influxdata/telegraf/issues/7981
`moby`, `etcd`, `github` packages bumped to the newest versions - should solve problems with found vulnerabilities in Telegraf binary

Fix vulnerabilities found in BDBA scan

---

plugins/parsers/influx/parser.go
plugins/parsers/influx/parser_test.go

A line ends at `\n` or `\r\n`, but not `\r` on its own. The ParseError.Error
logic was assuming that any carriage return terminates the line.
This caused a crash when the buffer is big, there's a single `\r` character and the
error offset was after that, because it assumed that the offset is always before
the end of the current line (a reasonable assumption as long as the line-termination
logic agrees between the Error method and the parsing code).
This bug found by running `go-fuzz`.

fix: plugins/parsers/influx: avoid ParseError.Error panic

---

go.mod
go.sum

This gopsutil update addresses a performance regression where getting stats for a process would read many files to check whether the program is running under virtualization.  In telegraf this would happen for every process running on the system on every collection interval causing excessive cpu usage.  The update changes gopsutil to only check for virtualization once.  See shirou/gopsutil#942
closes #7811
closes #7884
closes #7883

Update gopsutil: fix procstat performance regression

---

plugins/outputs/sumologic/sumologic_test.go
plugins/serializers/carbon2/carbon2.go
plugins/serializers/carbon2/carbon2_test.go

When `carbon2_format` is unspecified or is specified as empty string there's a missing `fallthrough` which makes carbon2 serializer not produce metric names at all (noop case in `switch`).
This PR addresses that and adds a handful of tests for that case.

Fix carbon2 serializer not falling through to field separate when carbon2_format field is unset

---

docs/CONFIGURATION.md
plugins/inputs/influxdb_v2_listener/README.md
plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
plugins/outputs/influxdb_v2/README.md
plugins/outputs/influxdb_v2/influxdb.go
plugins/outputs/influxdb_v2/influxdb_test.go

Addresses https://github.com/influxdata/telegraf/issues/8080.
hold off on merging until InfluxDB OSS is released with the port change.

change influxdb port 9999 to 8086

---

plugins/serializers/carbon2/carbon2.go
plugins/serializers/carbon2/carbon2_test.go

To align with other serializers e.g. prometheus, this PR addresses the way carbon2 serializer serializes `bool`s.
Instead of `false` and `true` it should output `0` and `1` respectively. Some systems do not accept string formatted `bool`s and return errors.

Fix bool serialization when using carbon2

---

plugins/inputs/jenkins/jenkins.go
plugins/inputs/jenkins/jenkins_test.go

Multiple escaping occurs on Jenkins URLs at certain folder depth

---

plugins/common/encoding/decoder_reader.go
plugins/inputs/bcache/bcache.go
plugins/inputs/github/github.go
plugins/inputs/graylog/graylog.go
plugins/inputs/haproxy/haproxy.go
plugins/inputs/ipmi_sensor/connection.go
plugins/inputs/jolokia/jolokia.go
plugins/inputs/jolokia2/client.go
plugins/inputs/kibana/kibana.go
plugins/inputs/mcrouter/mcrouter.go
plugins/inputs/net_response/net_response.go
plugins/inputs/openldap/openldap.go
plugins/inputs/phpfpm/phpfpm.go
plugins/inputs/phpfpm/phpfpm_test.go
plugins/inputs/processes/processes_notwindows.go
plugins/inputs/procstat/native_finder.go
plugins/inputs/procstat/pgrep.go
plugins/inputs/procstat/procstat.go
plugins/inputs/prometheus/parser.go
plugins/inputs/prometheus/prometheus.go
plugins/inputs/proxmox/proxmox.go
plugins/inputs/rethinkdb/rethinkdb_server.go
plugins/inputs/smart/smart.go
plugins/inputs/snmp_legacy/snmp_legacy.go
plugins/outputs/influxdb/http.go
plugins/outputs/kafka/kafka.go
plugins/outputs/warp10/warp10.go

Fixed almost all bugs found by LGTM analysis platform: https://lgtm.com/projects/g/influxdata/telegraf
What is LGTM: https://lgtm.com/help/lgtm/about-lgtm
@ssoroka Have you considered adding LGTM to Telegraf repo and enable automated code review?

Fixed almost all bugs found by LGTM analysis platform

---

plugins/inputs/snmp/README.md
plugins/inputs/snmp/snmp.go
plugins/inputs/snmp/snmp_test.go

The agent hostname is hardcoded in agent_host tag. Expose this as a variable and make it configurable in order to avoid extra processing later on.
In reply to feature request https://github.com/influxdata/telegraf/issues/8060

Add agent host tag configuration option

---

plugins/inputs/http_response/README.md
plugins/inputs/http_response/http_response.go
plugins/inputs/http_response/http_response_test.go

I've added the possibility to match on the status code instead of only the response body, can be useful if your service return a 204. 
I'm not fully satisfied because actually we can only check the body OR the status code (not both). Technically isn't difficult to be able to do both, but that require some decisions about the `result` value, if only one of these fail the value is pretty obvious but in case both check fail, do we need to create another value (`response_mismatch`?) or set the field to `response_status_code_mismatch` or `response_string_mismatch`
Thanks!

http_response: status_code match

---

Makefile
scripts/check-dynamic-glibc-versions.sh

This version check makes sure that telegraf on linux platforms doesn't dynamically link to a glibc that is too new.  Requiring a new glibc would cause telegraf to fail to run on older supported linux distributions.  The version it compares against is configurable in the makefile and set to 2.17 which is what RHEL 7 provides.
The check runs as part of the makefile's packages target which already runs during CI, so this will run on every PR.
CI for this PR is failing intentionally to show that it works.

Add glibc version check for linux builds

---

plugins/processors/port_name/README.md
plugins/processors/port_name/port_name.go
plugins/processors/port_name/port_name_test.go

Improve functionality of the `port_name` plugin by:
- allowing source to be provided as a field (not only as a tag)
- output will be provided as a field if input was a field as well
- additional tag/field can be provided to specify the protocol (tcp/udp)
Documentation and tests are updated accordingly.

Add support for fields and protocol lookups in port_name.

---

config/config_test.go
plugins/outputs/azure_monitor/azure_monitor.go

Fix using empty string as the namespace prefix in azure_monitor output plugin

---

etc/telegraf.conf
plugins/outputs/sumologic/README.md
plugins/outputs/sumologic/sumologic.go

After deciding to use `config.Size` in https://github.com/influxdata/telegraf/commit/e9dcade0a85701a645f11ecd11a1463b4ecc4d7f I've noticed that it uses `ParseStrictBytes` from https://github.com/alecthomas/units/blob/b9c82cb/bytes.go#L77-L85 which doesn't understand underscores in numbers.
This PR addresses that by changing what's in the sample config not to confuse users.

Sumo Logic output plugin: fix unparsable config.Size from sample config

---

plugins/inputs/ras/ras.go
plugins/inputs/ras/ras_test.go

Database driver doesn't close file handler properly when `db.Close()` is called. 
This may lead to `too many open files` for Telegraf process (returned by OS).
In this fix `sql.Open()` is called once in `Start()` and `db.Close()` is also called only once in `Stop()`.
This is also optimization (open DB just once, not in every `Gather()`) and following along guide from comment for `func (db *DB) Close() error` in `sql.go`:
> // It is rare to Close a DB, as the DB handle is meant to be
> // long-lived and shared between many goroutines.
The same approach was introduced in `inputs/postgresql` plugin.

RAS plugin - fix for too many open files handlers

---

plugins/inputs/ras/README.md
plugins/inputs/ras/ras.go
plugins/inputs/ras/ras_notlinux.go
plugins/inputs/ras/ras_test.go

Solves: https://github.com/influxdata/telegraf/issues/8311
RAS plugin runs only for Linux `386`, `amd64`, `arm` and `arm64` platforms. This PR reflects that and corrects build tags.

Disable RAS input plugin on specific Linux architectures: mips64, mips64le, ppc64le, riscv64 (#8317)

---

plugins/inputs/sqlserver/azuresqlqueries.go
plugins/inputs/sqlserver/sqlserverqueries.go

Closes #8252
adds a new tag with the readable value of the SQL Server Version. (in addition to the already existing numeric version number)
The tag will be added for On-prem and Azure Managed Instance

SQL Server - server_properties added sql_version_desc

---

plugins/inputs/sqlserver/sqlserverqueries.go

This PR removes some synthetic performance counters from the sqlserver_performance_counters measurement.
We believe that those counters were added to create unavailable counters on older editions of SQL Server, as of now, some of those counters already exist even in SQL 2008. In any case, we don't really want to fetch performance counters that do not exist.
- affects only the latest version of the queries
- affect only the on-prem query, for Azure those synthetic counter never existed
- The query has been simplified

SQL Server - PerformanceCounters - removed synthetic counters

---

plugins/inputs/ras/ras_test.go

On some systems /tmp/test.db happens to exist which
makes this test fail.

fix plugins/input/ras test
