- docs/FAQ.md
- plugins/inputs/sqlserver/README.md
> Add cardinality tips to FAQ and sqlserver input

- CHANGELOG.md
- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
> skip all blocks except certificates, closes #6890

- plugins/inputs/snmp/snmp.go
- plugins/inputs/snmp/snmp_test.go
> Support URL agent address form with udp in snmp input

- plugins/outputs/kafka/kafka.go
> Do not add invalid timestamps to kafka messages

- plugins/inputs/exec/README.md
> Document workaround for truncated powershell scripts

- plugins/inputs/mongodb/README.md
- plugins/inputs/mongodb/mongodb_data.go
- plugins/inputs/mongodb/mongodb_data_test.go
> Add rs name tag branch

- plugins/inputs/monit/monit.go
- plugins/inputs/monit/monit_test.go
> Change monit Testcase

- go.mod
- go.sum
> Update to github.com/safchain/ethtool@latest

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/kafka.go
> Document the behavior of an unset routing key

- plugins/inputs/chrony/chrony.go
> Search for chronyc only when chrony input plugin is enabled

- internal/models/running_output.go
- plugins/inputs/ecs/client.go
- plugins/inputs/ecs/client_test.go
- plugins/inputs/fibaro/fibaro.go
- plugins/inputs/haproxy/haproxy.go
- plugins/inputs/kibana/kibana.go
- plugins/inputs/logstash/logstash.go
- plugins/inputs/mailchimp/chimp_api.go
- plugins/inputs/nginx_upstream_check/nginx_upstream_check.go
- plugins/inputs/nsq_consumer/nsq_consumer_test.go
- plugins/inputs/salesforce/salesforce.go
Related to https://github.com/influxdata/telegraf/issues/6623
> resolves issues where failed api calls lead to obscure errors

- plugins/inputs/net_response/net_response.go
> Remove duplicate loop in net_response plugin

- .circleci/config.yml
> CI Mac build

- .circleci/config.yml
- Makefile
- appveyor.yml
- scripts/ci-1.12.docker
- scripts/ci-1.13.docker
> Use Go 1.13.8 to build official packages

- plugins/inputs/snmp/README.md
- Changed the float(X) description to correct the spelling of effectively
> Fixed a spelling error in the SNMP field example

- plugins/inputs/salesforce/README.md
> fix(salesforce): fix typo in readme

- etc/telegraf.conf
- plugins/inputs/pgbouncer/README.md
- plugins/inputs/postgresql/README.md
- plugins/inputs/postgresql_extensible/README.md
> Document port specification in postgres input plugins.

- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/modbus_test.go
> modbus to support scaling int32 and float32-ieee

- plugins/inputs/postgresql/postgresql.go
> fix inputs.postgresql panic in posgres 12

- plugins/inputs/EXAMPLE_README.md
Add minimum versions for plugins in README
> Add versioning to example readme

- go.mod
- go.sum
- plugins/processors/all/all.go
- plugins/processors/geo/README.md
- plugins/processors/geo/geo.go
- plugins/processors/geo/geo_test.go
This PR contains simple processor plugin that add a tag containing S2 Cell ID token required for `experimental/geo` Flux package (https://github.com/influxdata/flux/pull/2565). It uses Google S2 library (https://s2geometry.io/).
> feat: geo processor plugin

- go.mod
- go.sum
> fix issue with ping input in windows. Closes #7088

- scripts/alpine.docker
- scripts/stretch.docker
> update docker files for go modules. Closes #7170

- CONTRIBUTING.md
> Remove dep from contribution guidelines

- plugins/inputs/jenkins/jenkins.go
- plugins/inputs/jenkins/jenkins_test.go
> Fix encoding of job names in jenkins input plugin.

- plugins/inputs/sqlserver/sqlserver.go
Peformance Fix for #7236 
Resolves #7236
> FIX: Perfmon collector adding OPTION RECOMPILE for perf reasons

- plugins/inputs/postfix/README.md
> Update permission docs on postfix input

- metric.go
> Improve documentation for the Metric interface

- plugins/inputs/sflow/README.md
> fix(sflow): add series cardinality to readme

- plugins/outputs/influxdb/README.md
- plugins/outputs/influxdb/influxdb.go
> Fix error in docs about exclude_retention_policy_tag

- plugins/inputs/phpfpm/phpfpm.go
Sorry no tests, plugin needs major refactor.
closes #7262
> Fix status path when using globs in phpfpm

- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb/http_test.go
> Fix exclude database and retention policy tags is shared

- internal/internal_test.go
- plugins/inputs/solr/solr.go
- plugins/outputs/http/http.go
- plugins/outputs/http/http_test.go
- plugins/outputs/influxdb/http.go
- plugins/outputs/influxdb/http_test.go
- plugins/outputs/influxdb_v2/http.go
> Update the product token for the user agent in more locations

- plugins/inputs/influxdb_listener/README.md
- plugins/inputs/influxdb_listener/influxdb_listener.go
- plugins/inputs/influxdb_listener/influxdb_listener_test.go
> Add option to save retention policy as tag in influxdb_listener

- plugins/outputs/azure_monitor/azure_monitor.go
> Fix dimension limit on azure_monitor output

- plugins/inputs/nvidia_smi/README.md
Updated for Windows users. Clarified toml edits and location of nvidia-smi.exe on Win10
> Update nvidia-smi README for Windows users

- plugins/inputs/file/README.md
- plugins/inputs/file/file.go
- plugins/inputs/tail/tail.go
> Document distinction between file and tail inputs

- CHANGELOG.md
> Update filepath processor link

- plugins/serializers/splunkmetric/README.md
- plugins/serializers/splunkmetric/splunkmetric.go
- plugins/serializers/splunkmetric/splunkmetric_test.go
> Remove debug fields from spunkmetric serializer

- plugins/inputs/execd/execd.go
- plugins/inputs/execd/execd_test.go
Closes https://github.com/influxdata/telegraf/issues/7461
> fix issue with execd-multiline influx line protocol

- plugins/outputs/datadog/README.md
- plugins/outputs/datadog/datadog.go
> Update datadog output documentation

- cmd/telegraf/telegraf_windows.go
Minor, but it's been bugging me.
> Fix typo in Windows service description

- CONTRIBUTING.md
- README.md
> Update docs for execd plugins

- plugins/inputs/ipmi_sensor/ipmi.go
- plugins/inputs/ipmi_sensor/ipmi_test.go
> Fix negative value parsing in impi_sensor input

- go.mod
- go.sum
https://github.com/benbjohnson/clock/pull/22
> Use updated clock package to resolve test failures

- plugins/inputs/influxdb/README.md
- plugins/inputs/influxdb/influxdb.go
- plugins/inputs/influxdb/influxdb_test.go
- plugins/inputs/kapacitor/README.md
> Fix the typo in `gcc_pu_fraction` to `gc_cpu_fraction`.

- internal/internal_test.go
> fix go version check

- plugins/inputs/tail/tail_test.go
- plugins/parsers/csv/README.md
- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
> Exclude `csv_timestamp_column` and `csv_measurement_column` from fields.

- plugins/inputs/http_response/http_response.go
- plugins/inputs/http_response/http_response_test.go
> 7592 - Segmentation violation on connection failed

- plugins/inputs/diskio/README.md
> Fix typo in queue depth example of diskio plugin

- plugins/parsers/influx/machine.go
- plugins/parsers/influx/machine.go.rl
- plugins/parsers/influx/parser_test.go
resolves https://github.com/influxdata/telegraf/issues/7617
> fix issue with stream parser blocking when data is in buffer

- docs/CONFIGURATION.md
> link to glob pattern docs

- plugins/inputs/cisco_telemetry_gnmi/README.md
Update gNMI plugin readme to note vendor agnostic and supportive on multiple platforms.
> Update gNMI plugin readme

- plugins/outputs/mqtt/README.md
readme.md update: added missing 'batch' parameter
> add 'batch' to optional parameters

- plugins/parsers/json/README.md
> Link to GJSON playground in json parser documentation

- plugins/inputs/stackdriver/stackdriver_test.go
Relates to issue #7729 - fixes data race in input plugin stackdriver tests'.
```
go test -short -race ./plugins/inputs/stackdriver/...
```
Before:
```
==================
WARNING: DATA RACE
Read at 0x00c0000db128 by goroutine 15:
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*MockStackdriverClient).ListTimeSeries()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/inputs/stackdriver/stackdriver_test.go:46 +0x18b
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).gatherTimeSeries()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/inputs/stackdriver/stackdriver.go:595 +0xce
github.com/influxdata/telegraf/plugins/inputs/stackdriver.(*Stackdriver).Gather.func1()
/Users/jakubwarczarek/Documents/my/telegraf/plugins/inputs/stackdriver/stackdriver.go:310 …
```
> Fix data race in plugins/inputs/stackdriver/stackdriver_test.go

- config/config.go
> Return on toml parse errors instead of logging

- go.mod
- plugins/processors/all/all.go
- plugins/processors/reverse_dns/README.md
- plugins/processors/reverse_dns/parallel/ordered.go
- plugins/processors/reverse_dns/parallel/parallel.go
- plugins/processors/reverse_dns/parallel/parallel_test.go
- plugins/processors/reverse_dns/parallel/unordered.go
- plugins/processors/reverse_dns/rdnscache.go
- plugins/processors/reverse_dns/rdnscache_test.go
- plugins/processors/reverse_dns/reversedns.go
- plugins/processors/reverse_dns/reversedns_test.go
Resolves https://github.com/influxdata/telegraf/issues/7245
> reverse dns lookup processor

- plugins/inputs/elasticsearch/README.md
> inputs/elasticsearch: Fix typo in docs

- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/phpfpm/phpfpm_test.go
> Fix data race in phpfpm initializing http client

- plugins/inputs/kibana/kibana.go
- plugins/inputs/kibana/testdata_test6_5.go
> kibana: Change int64 to float64 in uptime fields

- config/config.go
> Set user agent when requesting http config

- .circleci/config.yml
> switch mac tests to Go 1.14

- docs/PROCESSORS.md
for discussing/editing updates to docs about streaming processors.
> streaming processors docs update

- plugins/inputs/execd/README.md
> Fix inputs.execd readme links

- testutil/accumulator.go
https://circleci.com/gh/influxdata/telegraf/59437
> Fix test race in kafka_consumer

- CHANGELOG.md
> small typo fix to 1.15 changelog

- plugins/inputs/execd/shim/README.md
- ~Associated README.md updated.~
- ~Has appropriate unit tests.~
> Fix markdown syntax

- Makefile
> Fix darwin package build flags

- plugins/common/shim/config.go
- plugins/common/shim/config_test.go
- plugins/common/shim/input_test.go
> fix bug with loading plugins in shim with no config

- plugins/inputs/tail/tail_test.go
> Set log output before starting plugin

- EXTERNAL_PLUGINS.md
I have created a new external plugin.
- ~~Has appropriate unit tests.~~
> Add github.com/inabagumi/youtube-telegraf-plugin to list of external plugins

- plugins/inputs/redfish/README.md
> update redfish docs with link

- agent/agent.go
- agent/tick.go
> Log after interval has elapsed; skip short intervals

- scripts/release.sh
Print some information used to generate https://portal.influxdata.com/downloads/ on release.
> Print configuration for downloads page

- docs/FAQ.md
> Update docker FAQ

- plugins/processors/defaults/README.md
> fix defaults readme typos

- plugins/inputs/cgroup/README.md
- plugins/inputs/cgroup/cgroup.go
> fixed cgroups docu

- plugins/inputs/jolokia2/gatherer.go
related to https://github.com/influxdata/telegraf/issues/7812
> jolokia: add some error message context

- scripts/rpm/post-install.sh
resolves https://github.com/influxdata/telegraf/issues/7905
> fixes issue with rpm /var/log/telegraf permissions

- plugins/outputs/newrelic/README.md
> Fixed title on New Relic README.md

- plugins/inputs/http_response/README.md
- plugins/inputs/http_response/http_response.go
http_response input plugin README.md was not in sync with updated features.
Updated README file to keep it in sync
#7942
> Updated http_response input plugin README.md

- plugins/inputs/ipmi_sensor/README.md
Old link went to obsolete repo.
> fix(ipmi): update link in readme

- plugins/inputs/puppetagent/README.md
fixes broken link in puppet readme
> fix(puppet): update broken link

- plugins/inputs/clickhouse/README.md
- plugins/inputs/clickhouse/clickhouse.go
- plugins/inputs/clickhouse/clickhouse_test.go
- plugins/inputs/clickhouse/dev/docker-compose.yml
- plugins/inputs/clickhouse/dev/part_log.xml
- plugins/inputs/clickhouse/dev/telegraf.conf
- plugins/inputs/clickhouse/dev/telegraf_ssl.conf
- plugins/inputs/clickhouse/dev/test_dictionary.xml
- plugins/inputs/clickhouse/dev/text_log.xml
- plugins/inputs/clickhouse/dev/zookeeper.xml
add additional set of metrics, unit test and update README.md for following ClickHouse tables:
- system.zookeeper 
- system.detached_parts
- system.dictionaries  
- system.replication_queue  
- system.mutations  
- system.disks  
- system.processes  
- system.text_log
> add additional metrics to clickhouse input plugin

- go.mod
- plugins/inputs/all/all.go
- plugins/inputs/proxmox/README.md
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/proxmox_test.go
- plugins/inputs/proxmox/structs.go
> Proxmox plugin

- plugins/inputs/internal/README.md
- plugins/inputs/proxmox/README.md
- Added Telegraf to the title of the internal plugin readme
- added toml annotation to new proxmox readme config section
> fix(readmes): updates to internal and proxmox readmes

- plugins/inputs/http_listener_v2/http_listener_v2.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- testutil/log.go
resolves https://github.com/influxdata/telegraf/issues/7907
> http_listener_v2: make http header tags case insensitive

- agent/agent.go
resolves https://github.com/influxdata/telegraf/issues/7998
> fix minor agent race condition around error messages

- docs/CONFIGURATION.md
Fixed some fo the formatting in configuration.md from some of @alsargent's additions
> Fix configuration.md formatting

- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/vsphere_test.go
- plugins/outputs/wavefront/wavefront.go
* Fixed issue #7878 (clustername missing)
* Fixed an issue causing clustername to be missing if data collection is turned off for clusters (unrelated to #7878)
* Added tests to make sure this doesn't happen again.
> Fixed issue 7878 (vSphere missing clustername)

- CONTRIBUTING.md
- docs/EXTERNAL_PLUGINS.md
update documentation for external plugins
> Create external plugins doc file and update contributing guide

- EXTERNAL_PLUGINS.md
- docs/EXTERNAL_PLUGINS.md
> add guidelines run to external plugins with execd

- docs/CONFIGURATION.md
> add tagpass/tagdrop order note in docs

- plugins/inputs/opcua/README.md
> update opcua readme

- docs/EXTERNAL_PLUGINS.md
> Fix external plugin docs links

- plugins/inputs/all/all.go
- plugins/inputs/nsd/README.md
- plugins/inputs/nsd/nsd.go
- plugins/inputs/nsd/nsd_test.go
> add nsd input plugin

- plugins/inputs/kubernetes/kubernetes.go
> [fix] add missing error check for HTTP req failure

- CHANGELOG.md
> update 1.16 changelog with new plugins

- CHANGELOG.md
@noramullen says Bug Fixes is two words
> Fix bug fix typo in changelog

- docs/EXTERNAL_PLUGINS.md
Link to example main.go for external plugin was leading to a 404, updated the path to what looks like the correct example.
> Doc update: Fix main.go shim example link

- config/config.go
> Sort plugin name lists for output (#7710)

- README.md
> add influxdata slack icon to telegraf readme

- docs/DATA_FORMATS_OUTPUT.md
Missing ServiceNow metrics in DATA_FORMATS_OUTPUT.md
> Missing ServiceNow metrics in DATA_FORMATS_OUTPUT.md

- plugins/inputs/win_eventlog/README.md
- plugins/inputs/win_eventlog/win_eventlog.go
Adds the missing toml to win_eventlog.
> fix(win_eventlog): fixing config

- etc/telegraf.conf
- plugins/outputs/sumologic/README.md
- plugins/outputs/sumologic/sumologic.go
- plugins/outputs/sumologic/sumologic_test.go
> Sumo Logic output plugin: only support HTTP POST

- plugins/inputs/ras/README.md
> fix(ras): update readme title

- plugins/inputs/exec/README.md
> fix(exec): fix typo in exec readme

- plugins/common/shim/config.go
- plugins/common/shim/config_test.go
- plugins/common/shim/testdata/processor.conf
closes https://github.com/influxdata/telegraf/issues/8272
> fix issue with loading processor config from execd

- plugins/outputs/influxdb/README.md
- plugins/outputs/influxdb/influxdb.go
resolves https://github.com/influxdata/telegraf/issues/7397
> turn gzip on by default for influxdb v1

- plugins/inputs/win_eventlog/README.md
- plugins/inputs/win_eventlog/win_eventlog.go
> Fix win_eventlog timestamps

- plugins/inputs/sqlserver/azuresqlqueries.go
Closes #8285
Added missing sorting, now the latest data should be fetched
> sqlAzureMIResourceStats - added sorting

- plugins/inputs/phpfpm/phpfpm.go
- plugins/inputs/phpfpm/phpfpm_test.go
closes https://github.com/influxdata/telegraf/issues/1906
> fix issue with phpfpm url usage

- plugins/inputs/proxmox/README.md
- plugins/inputs/proxmox/proxmox.go
- plugins/inputs/proxmox/proxmox_test.go
- plugins/inputs/proxmox/structs.go
> Fix wrong memory measurements of containers and vms

- plugins/inputs/win_perf_counters/win_perf_counters.go
> fix issue with PDH_CALC_NEGATIVE_DENOMINATOR error

- plugins/inputs/processes/processes_notwindows.go
> processes: fix issue with stat no such file/dir

- plugins/inputs/sqlserver/sqlserverqueries.go
Sorry to bother you (again) with this @ssoroka but I've noticed this just now.
looks like that the edits made with #8172 to the main file of the sqlserver on prem queries have been lost in the merge... somehow.
If I go to that or (#8172) I can see that only 2 files have been edited, and "plugins/inputs/sqlserver/sqlserverqueries.go" is not included.
Therefore I made this PR to re-add all the missing formatting and edits that had been made to that file
> SQL Server - on-prem queries refactor (again)

- plugins/inputs/sqlserver/sqlserverqueries.go
I missed two quotes in #8324, the error is only on the on-prem query.
Lately, I've been making more mistakes than usual with my PRs, sorry about that. I'll be more careful, or at least as careful as before.
> SQL Server - On-Prem ServerProperties - fix for #8324

- plugins/inputs/redis/README.md
- plugins/inputs/sqlserver/README.md
- plugins/inputs/win_perf_counters/README.md
- plugins/parsers/collectd/README.md
some typos found from https://github.com/influxdata/influxdb/pull/19751
> fix: minor typos in readmes

- docs/EXTERNAL_PLUGINS.md
> fix link in external plugins readme

- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
> Add DriverVersion and CUDA Version to output

- .circleci/config.yml
- Makefile
- scripts/alpine.docker
- scripts/buster.docker
- scripts/ci-1.15.docker
closes https://github.com/influxdata/telegraf/issues/8445
> update to go 1.15.5

- plugins/inputs/phpfpm/phpfpm.go
Closes: https://github.com/influxdata/telegraf/issues/8237
> [php-fpm] Fix possible "index out of range"

- plugins/inputs/sqlserver/azuresqlqueries.go
> Fix typo in column name

- plugins/inputs/mock_Plugin.go
Add an example of using `Init()`.
> Add initialization example to mock-plugin.

- plugins/parsers/json/README.md
Added back in https://github.com/influxdata/telegraf/pull/6400
> add boolean info to json parser readme

- plugins/inputs/influxdb/README.md
update influxdb metrics - include missing enterprise metrics.
Closes #4017
> update inputs.influxdb readme

- plugins/parsers/influx/README.md
> Fix readme link for line protocol in influx parser

- plugins/processors/topk/README.md
The docs for the topk plugin are pretty unclear. This PR aims to make them easier to read and understand.
> Fix spelling and clarify docs

- plugins/inputs/intel_powerstat/README.md
> update intel powerstat readme

- EXTERNAL_PLUGINS.md
> Open Hardware Monitor

- docs/DATA_FORMATS_INPUT.md
- docs/DATA_FORMATS_OUTPUT.md
The data formats input and outputs documents provided a link to themselves
> Remove redundant references to self

- plugins/inputs/all/all.go
- plugins/inputs/beat/README.md
- plugins/inputs/beat/beat.go
- plugins/inputs/beat/beat6_info.json
- plugins/inputs/beat/beat6_stats.json
- plugins/inputs/beat/beat_test.go
As discussed in https://github.com/influxdata/telegraf/pull/4911, combine @dmitryilyin 's filebeat and kafkabeat plugins.
> Add Beat input plugin

- plugins/serializers/prometheusremotewrite/README.md
clean up the prometheus remote write serializer readme
> update readme: prometheus remote write

- plugins/inputs/jolokia2/README.md
- plugins/inputs/jolokia2/examples/kafka-connect.conf
Hi all!
I add comprehensive example for kafka-connect to jolokia2 input plugin.
> add kafka connect example to jolokia2 input

- go.mod
- go.sum
Incorporate the fixes of the grok library. Relates to PR #8276.
> Update grok-library to v1.0.1 with dots and dash-patterns fixed.

- README.md
> update min Go version in Telegraf readme

- .circleci/config.yml
- Makefile
- scripts/alpine.docker
- scripts/buster.docker
- scripts/ci-1.15.docker
```
Updated to use 1.15.8 !
------------------------
\
\
\   ,_---~~~~~----._         
_,,_,*^____      _____``*g*\"*, 
/ __/ /'     ^.  /      \ ^@q   f 
[  @f | @))    |  | @))   l  0 _/  
\`/   \~____ / __ \_____/    \   
|           _l__l_           I   
}          [______]           I  
]            | | |            |  
]             ~ ~             |  
|                            |   
|                           |   
```
Close #8853
> Update Go to 1.15.8

- EXTERNAL_PLUGINS.md
> add SMCIPMITool input to external plugin list

- plugins/inputs/cloudwatch/README.md
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
> Add HTTP Proxy to Cloudwatch input

- plugins/outputs/all/all.go
- plugins/outputs/loki/README.md
- plugins/outputs/loki/loki.go
- plugins/outputs/loki/loki_test.go
- plugins/outputs/loki/stream.go
- plugins/outputs/loki/stream_test.go
fixes: #5939
README and unit tests will be added soon (next week)
I open this PR to get review, is my first plugin I hope doing well
Documentation about Loki endpoint: https://github.com/grafana/loki/blob/master/docs/sources/api/_index.md#user-content-post-lokiapiv1push
> plugin: output loki

- .lgtm.yml
- README.md
- plugins/inputs/github/github.go
- plugins/inputs/jolokia2/client.go
- plugins/inputs/riemann_listener/riemann_listener.go
- plugins/outputs/http/http.go
- plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
- plugins/parsers/prometheus/parser.go
Clearing alerts and warnings found by LGTM analysis platform: https://lgtm.com/projects/g/influxdata/telegraf
What is LGTM: https://lgtm.com/help/lgtm/about-lgtm
> Clearing LGTM alerts and warnings

- plugins/inputs/csgo/README.md
> chore: update csgo readme title

- plugins/inputs/beat/README.md
> fix: Beat readme title

- plugins/inputs/influxdb_v2_listener/README.md
> chore: update docs link in influxdbv2listener

- plugins/inputs/nfsclient/README.md
> NFS Client input plugin README cleanup

- plugins/outputs/kinesis/kinesis.go
- plugins/outputs/kinesis/kinesis_test.go
> Writing unit tests for Kinesis output plugin Write method

- EXTERNAL_PLUGINS.md
> feat: Adding Plex Webhooks external plugin

- .circleci/config.yml
- Makefile
- go.mod
- go.sum
- scripts/alpine.docker
- scripts/buster.docker
- scripts/ci-1.16.docker
Changelog: https://golang.org/doc/devel/release.html#go1.16.minor
> Update Go to 1.16.1

- plugins/outputs/bigquery/README.md
> update bigquery readme

- plugins/parsers/xml/README.md
> add xpath testers to xml readme

- plugins/processors/execd/README.md
> readme fix

- plugins/inputs/tail/README.md
- plugins/inputs/tail/tail.go
- plugins/inputs/tail/tail_test.go
> Add configurable option for the 'path' tag override in the Tail plugin.

- EXTERNAL_PLUGINS.md
Hi,
This a PR for adding my external Big Blue Button plugin.
CLA is already signed.
Best regards,
SLedunois
> feat: Add external Big blue button plugin

- plugins/inputs/nvidia_smi/README.md
resolves #8531
Add context on how to use nvidia plugin with a custom nvidia/cuda docker image
> Add custom docker image info to nvidia plugin

- plugins/common/shim/example/cmd/main.go
> clarify pollIntervalDisabled message

- plugins/inputs/cloudwatch/README.md
- plugins/inputs/cloudwatch/cloudwatch.go
- plugins/inputs/cloudwatch/cloudwatch_test.go
I believe this will resolve #4046
> Add Glob / Wildcard support to Cloudwatch input for 'Dimensions' configuration

- EXTERNAL_PLUGINS.md
resolves #
Add new external input plugin to get dnsmasq cache statistics.
The cache statistics are available in the DNS as answers to queries of class CHAOS and type TXT in domain bind.
> Add external dnsmasq input plugin

- .github/dependabot.yml
> Update Dependabot config: ignore all packages with *.v*

- Makefile
> Add FreeBSD GOARCH=arm, GOARM=7 to package step

- plugins/inputs/docker/README.md
There is no related issues (yet).
I added popular configuration regarding to docker-compose similiar to Kubernetes.
> Add docs for docker-compose labels in docker input

- EXTERNAL_PLUGINS.md
> Add x509_crl external plugin

- docs/AGGREGATORS.md
- docs/INPUTS.md
- docs/OUTPUTS.md
- docs/PROCESSORS.md
- docs/maintainers/PULL_REQUESTS.md
Redirect links to wiki pages to new docs pages
> Redirect former wiki links

- plugins/parsers/prometheusremotewrite/README.md
> Prometheus remote write parser readme fix path

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/prometheus.go
> chore: update prometheus input readme to match config options

- docs/developers/REVIEWS.md
Document the review steps and the procedure on inactive PRs.
> Document inactivity procedure.

- docs/maintainers/LABELS.md
- docs/maintainers/PULL_REQUESTS.md
- added labels and descriptions to maintainers/LABELS.md
- cleaned up other docs in maintainer folder
> update github maintainer docs

- EXTERNAL_PLUGINS.md
resolves #7728 
Added external input plugin for Siemens PLC using golang library [gos7](https://github.com/robinson/gos7)
First ever contribution to open source project. All advice are welcome.
> Add s7comm external input plugin

- plugins/inputs/kube_inventory/README.md
> kube_inventory: expand tls key/tls certificate documentation 

- plugins/parsers/json_v2/parser.go
- plugins/parsers/json_v2/testdata/nested_and_nonnested_tags/telegraf.conf
- plugins/parsers/json_v2/testdata/object/telegraf.conf
resolves #9394 
added a line to append tags to included keys
took tags out of included_keys in test data
> tags no longer required in included_keys

- go.mod
- go.sum
resolves internal issue
updated jwt to v1.2.2 and updated jwt-go to v3.2.3
> updated jwt to v1.2.2 and updated jwt-go to v3.2.3

- plugins/inputs/aliyuncms/README.md
- plugins/inputs/cisco_telemetry_mdt/README.md
- plugins/inputs/dpdk/README.md
- plugins/inputs/knx_listener/README.md
Some small changes to the README's based on incorporating them into the UI https://github.com/influxdata/ui/pull/1703/files
resolves #
> chore: readme updates

- go.mod
- go.sum
resolves #9396 
Forked gopsutil and removed unnecessary pointer that was causing a segfault
> updated gopsutil to use a specific commit

- README.md
> add OpenTelemetry entry

- plugins/inputs/docker/docker.go
resolves #
Fix typo in `perDeviceIncludeDeprecationWarning` Docker Input Plugin output.
Before:
`... and 'network' metrics willbe collected. ...`
After:
`... and 'network' metrics will be collected. ...`
> Fix typo in perDeviceIncludeDeprecationWarning

- plugins/inputs/influxdb_listener/README.md
> chore: fixing link in influxdb_listener plugin

- go.mod
- go.sum
Update to the latest Dynatrace metric util library
> Update the dynatrace metric utils

- plugins/outputs/dynatrace/dynatrace.go
- plugins/outputs/dynatrace/dynatrace_test.go
Fixes #9437
~~- [ ] Updated associated README.md.~~ n/a
> [output dynatrace] Initialize loggedMetrics map

- plugins/outputs/prometheus_client/prometheus_client.go
- plugins/outputs/prometheus_client/prometheus_client_v1_test.go
> Support Landing page on Prometheus landing page

- plugins/outputs/influxdb/README.md
clean up broken links in readme
> docs: clean up influxdb output readme

- README.md
> docs: Add list of 3rd party builds to the README

- plugins/inputs/jenkins/README.md
resolves -
Example output was inconsistent with the metrics overview, now it should be correct
> docs: fix jenkins plugin documentation

- plugins/inputs/trig/README.md
- plugins/inputs/twemproxy/README.md
Added missing trig and twemproxy readme
> docs: add trig and twemproxy plugin readmes

- go.mod
- go.sum
resolves #[201](https://github.com/influxdata/telegraf-internal/issues/201)
updates consul to v1.11.0
> chore: update consul to v1.11.0

- plugins/inputs/sqlserver/README.md
resolves #9758 
Just forget in previous PR to add `elastic pool` in the list of supported SQL versions for this plugin. Just one line change in the documentation.
> docs: add elastic pool in supported SQL versions (README.md)

- plugins/inputs/webhooks/README.md
- plugins/inputs/webhooks/filestack/README.md
- plugins/inputs/webhooks/github/README.md
- plugins/inputs/webhooks/mandrill/README.md
- plugins/inputs/webhooks/papertrail/README.md
- plugins/inputs/webhooks/particle/README.md
- plugins/inputs/webhooks/rollbar/README.md
- plugins/inputs/wireguard/README.md
- plugins/inputs/wireless/README.md
- plugins/inputs/x509_cert/README.md
- plugins/inputs/zipkin/README.md
- plugins/inputs/zookeeper/README.md
> chore: clean up markdown lint errors input plugins w to z

- plugins/inputs/github/README.md
- plugins/inputs/gnmi/README.md
- plugins/inputs/graylog/README.md
- plugins/inputs/haproxy/README.md
- plugins/inputs/hddtemp/README.md
- plugins/inputs/http/README.md
- plugins/inputs/http_listener_v2/README.md
- plugins/inputs/http_response/README.md
- plugins/inputs/httpjson/README.md
> markdown: resolve all markdown issues with g-h

- plugins/inputs/prometheus/kubernetes.go
> fix: check error before defer in prometheus k8s

- go.mod
- go.sum
- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/http_test.go
> fix: failing ci on master

- plugins/inputs/kibana/README.md
- plugins/inputs/kibana/kibana.go
- plugins/inputs/kibana/testdata_test6_5.go
resolves #10242
Added new field "heap_size_limit" for input.kibana plugin
> feat(input.kibana): add heap_size_limit field

- internal/snmp/translate.go
> fix: grab table columns more accurately

- agent/agent.go
This improves debugging of configuration errors for the various plugins.
> feat: Improve error logging on plugin initialization

- .circleci/config.yml
- Makefile
- scripts/ci-1.17.docker
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Release notes: https://go.dev/doc/devel/release
> chore: update Go version to 1.17.5

- plugins/inputs/dpdk/README.md
> docs: add note about dpdk and socket availability

- go.mod
- go.sum
- plugins/outputs/groundwork/README.md
- plugins/outputs/groundwork/groundwork.go
- plugins/outputs/groundwork/groundwork_test.go
> fix: Update GroundWork SDK and improve logging

- plugins/outputs/sql/README.md
- plugins/outputs/sql/sql.go
> chore: sql readme with more details on data types

- accumulator.go
- internal/choice/choice.go
- internal/globpath/globpath.go
- internal/internal.go
- metric/tracking.go
- models/buffer.go
- models/makemetric.go
- models/running_processor.go
- plugins/common/encoding/decoder_reader.go
- plugins/inputs/mysql/mysql.go
- plugins/parsers/registry.go
- plugins/serializers/json/json.go
- plugins/serializers/registry.go
> fix: multiple typos throughout project

- go.mod
- go.sum
- plugins/inputs/docker/client.go
> feat: update docker client API version

- plugins/outputs/syslog/syslog.go
- plugins/outputs/syslog/syslog_test.go
> fix: correctly set ASCII trailer for syslog output

- plugins/inputs/influxdb/README.md
Add `openConnections`.
See https://github.com/influxdata/docs-v2/issues/3653.
resolves #
> Update Enterprise cluster metrics

- plugins/inputs/syslog/README.md
> fix: add RFC3164 to RFC5424 translation to docs

- plugins/inputs/sql/README.md
> docs: Fixes for input/sql readme

- plugins/inputs/modbus/README.md
spelling / syntax corrections.
resolves #
> fix: Update README.md

- plugins/inputs/modbus/README.md
> fix: Update modbus readme

- go.mod
- go.sum
required after merging this: https://github.com/influxdata/telegraf/pull/10434
> chore: update grpc to v1.44.0

- go.mod
- go.sum
Resolves mib loading when they are dependent on RFC-1212 mib.
```
Parse module: /mibs/RFC-1212:63:33: unexpected ".." (expected ")")
2022-01-12T02:08:40Z W! [inputs.snmp] module RFC-1212 could not be loaded
```
> chore: Update gosmi

- plugins/outputs/influxdb_v2/http.go
> fix: include influxdb bucket name in error messages

- plugins/inputs/mdstat/mdstat.go
- plugins/inputs/mdstat/mdstat_test.go
> fix: mdstat when sync is less than 10%

- plugins/parsers/csv/parser.go
- plugins/parsers/csv/parser_test.go
- [N/A] Updated associated README.md.
The error msg should refer to the parameter name.
> fix: typo metadata support to csv parser

- plugins/parsers/value/README.md
> docs: add value_field_name to value processor

- plugins/outputs/wavefront/README.md
- plugins/outputs/wavefront/wavefront.go
- [X ] Updated associated README.md.
- [ X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)
Fixed README file so that it is clear to user to use url in config file for direct ingestion and to use host and port for proxy server.
> docs: Fix wavefront config file docs for using proxy server.

- EXTERNAL_PLUGINS.md
Added external input plugin for gathering FRITZ!Box router statistics using it's SOAP interface.
> feat: Add fritzbox plugin

- plugins/processors/regex/README.md
> docs: regex processor only works on strings

- plugins/inputs/mongodb/README.md
This would fail connecting to localhost with the error
unable to connect to MongoDB: "error parsing uri: must have a / before the query ?"
resolves #
> docs(inputs.mongodb): Missing slash in mongodb readme

- .circleci/config.yml
resolve: https://github.com/influxdata/telegraf/issues/10985
resolve: https://github.com/influxdata/telegraf/issues/9977
Rebase branch with master before testing and before creating the packages so that latest changes are applied.
> chore: update pull request with master when running CI

- plugins/parsers/influx/README.md
`parser_type` is actually used when reading configuration.
> fix: typo in influx line protocol parser docs

- plugins/inputs/consul_agent/consul_agent.go
resolves #
Updated Consul Header token as the previous code was not passing the Consul token correctly and was blocking Consul client metrics from being sent to Telegraf.
> fix: Update Consul Header Token

- docs/LICENSE_OF_DEPENDENCIES.md
- go.mod
- go.sum
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/gnmi_test.go
Utilize a more extensively tested xpath -> gnmi parser
> refactor(gnmi): use external xpath parser

- .github/workflows/linter.yml
- scripts/check-dynamic-glibc-versions.sh
- scripts/installgo_mac.sh
resolve: https://github.com/influxdata/telegraf/issues/9716
also bumped the version to the latest.
> chore: enable linting of shell scripts

- .github/workflows/semantic.yml
- [ N/A] Updated associated README.md.
- [ N/A] Wrote appropriate unit tests.
This change unblocks https://github.com/influxdata/k8s-idpe/issues/5723
Introduce Influxdata semantic commit and PR text checker to allow removal of semantic-pull-requests github app.
> feat: add influx semantic commits checker, checks only last commit.

- plugins/inputs/statsd/statsd.go
Fix a minor copy-and-paste error in a comment.  No changes to README or unit tests.
> docs: correct copy-and-paste of udp to tcp in comment

- plugins/outputs/socket_writer/README.md
> docs: socket_writer format link

- plugins/inputs/webhooks/README.md
- plugins/inputs/webhooks/artifactory/README.md
- plugins/inputs/webhooks/artifactory/artifactory_webhook.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_mock_json.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go
- plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go
- plugins/inputs/webhooks/webhooks.go
- plugins/inputs/webhooks/webhooks_test.go
resolves #10376
https://github.com/influxdata/telegraf/issues/10376
Added a webhook receiver to receive webhooks from Jfrog Artifactory
> feat: Artifactory Webhook Receiver

- plugins/inputs/file/file.go
> chore(inputs/file): More clear error messages

- plugins/inputs/win_perf_counters/win_perf_counters.go
Add extra logging as #9498 recommends
> fix: log instance name in skip warnings

- plugins/parsers/logfmt/README.md
- plugins/parsers/logfmt/parser.go
- plugins/parsers/logfmt/parser_test.go
- plugins/parsers/registry.go
> feat(parsers/logfmt): Add tag support

- plugins/outputs/elasticsearch/elasticsearch_test.go
> fix: elasticsearch output float handling test

- plugins/inputs/sql/sql_test.go
- plugins/outputs/sql/sql_test.go
> test: remove unecessary flag in sql input

- docker-compose.yml
> test: use supported version of elasticsearch

- plugins/inputs/burrow/burrow.go
> feat: [inputs/burrow] fill more http transport parameters

- docs/developers/REVIEWS.md
Update the docs to reflect closing scheme of bot when waiting for response.
> docs: Update review docs

- CONTRIBUTING.md
Just adding the word `love` in the CONTRIBUTING.md, sentence doesn't make sense without it.
> docs: add the missing word love :heart: 

- etc/telegraf.conf
- etc/telegraf_windows.conf
- plugins/common/shim/processor_test.go
- plugins/inputs/openstack/README.md
- plugins/inputs/openstack/sample.conf
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
resolves #
> Fix typo: recieve -> receive

- plugins/inputs/mongodb/mongodb_server.go
Gather collection status, runs list collections names, which returns all views, collections, and timeseries. Then right after we attempt to list the collection status. However, this is not a valid operation on views. This will throw an error. 
fixes: #11270
> fix: filter out views in mongodb lookup

- plugins/inputs/cloudwatch/sample.conf
- plugins/inputs/redis/sample.conf
- plugins/inputs/x509_cert/sample.conf
- plugins/outputs/datadog/sample.conf
- plugins/outputs/websocket/sample.conf
related: https://github.com/influxdata/telegraf/pull/9319
related: https://github.com/influxdata/telegraf/pull/9333
The above pull request updated some README.md's without updating the related sample.conf, because the sample.conf is a new process decided to updated it manually after the merge to make it easier for the original PR author.
> docs: Sync sample.conf for recent features

- config/agent.conf
- config/config.go
resolves #11331 
moves the default agent config into a seperate file.
> chore: move agent config into seperate file

- config/config.go
- docs/DATA_FORMATS_OUTPUT.md
- plugins/serializers/csv/README.md
- plugins/serializers/csv/csv.go
- plugins/serializers/csv/csv_test.go
- plugins/serializers/csv/testcases/basic.conf
- plugins/serializers/csv/testcases/basic.csv
- plugins/serializers/csv/testcases/header.conf
- plugins/serializers/csv/testcases/header.csv
- plugins/serializers/csv/testcases/nanoseconds.conf
- plugins/serializers/csv/testcases/nanoseconds.csv
- plugins/serializers/csv/testcases/prefix.conf
- plugins/serializers/csv/testcases/prefix.csv
- plugins/serializers/csv/testcases/rfc3339.conf
- plugins/serializers/csv/testcases/rfc3339.csv
- plugins/serializers/csv/testcases/semicolon.conf
- plugins/serializers/csv/testcases/semicolon.csv
- plugins/serializers/registry.go
resolves #10637
This PR adds a CSV serializer to output metrics in the comma-separated format.
> feat: Add CSV serializer

- plugins/inputs/file/file_test.go
- plugins/inputs/logparser/logparser.go
- plugins/inputs/logparser/logparser_test.go
- plugins/inputs/tail/tail_test.go
- plugins/parsers/all/all.go
- plugins/parsers/grok/parser.go
- plugins/parsers/registry.go
> feat: migrate grok to new parser style

- plugins/parsers/all/all.go
- plugins/parsers/prometheusremotewrite/parser.go
- plugins/parsers/registry.go
> fix: Update prometheusremotewrite parser to be a new style parser plugin

- plugins/inputs/openstack/README.md
- plugins/inputs/openstack/openstack.go
> fix: correct init volume gatherer in openstack

- scripts/mac-signing.sh
> fix: Add version number to MacOS packages

- plugins/inputs/sqlserver/README.md
> docs(inputs.sqlserver): add timeout section

- plugins/outputs/opentelemetry/opentelemetry_test.go
resolves #
Fixes opentelemetry test mock server returning:
```
rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called
```
See the deleted comment for more details
> test: fix opentelemetry test

- EXTERNAL_PLUGINS.md
Added external input plugin for gathering network statistics from Netgear switches.
> feat: Add nsdp plugin

- plugins/parsers/json_v2/parser_test.go
- plugins/parsers/wavefront/element.go
This PR fixes all remaining linter issues in `plugins/parsers`.
> fix(parsers): Linter issues

- cmd/telegraf/telegraf.go
Related to the pull request that migrated to using urfave/cli https://github.com/influxdata/telegraf/pull/11700
Originally the now named struct `Telegraf` was named `AgentManager`, I overlooked renaming the receiver argument to the methods from `a` to `t`. Not a big deal but it is more consistent and matched the other methods which I did rename.
> chore: Rename Telegraf receiver argument from a to t

- EXTERNAL_PLUGINS.md
> docs(external): add hwinfo external plugin

- .circleci/config.yml
- agent/agent.go
- config/config.go
- config/config_test.go
- docs/CUSTOMIZATION.md
- scripts/installgo_windows.sh
include link to custom builder
> docs: update customization docs

- go.mod
- go.sum
> chore: update github.com/jackc/pgx/v4 from v4.17.0 to v4.17.1

- plugins/inputs/cpu/README.md
> docs(inputs.cpu): explain macos cpu support requires cgo

- .golangci.yml
- plugins/inputs/phpfpm/fcgi.go
- plugins/inputs/zfs/zfs.go
> chore(lint): Removed deprecated varcheck linter

- plugins/inputs/opcua/README.md
Simple typing error in an example
> docs(inputs.opcua): typing error

- plugins/inputs/opcua/sample.conf
CI is failing due to an out of sync opcua plugin readme: https://app.circleci.com/pipelines/github/influxdata/telegraf/13026/workflows/6a4dd625-c415-4cc5-b870-8be61af8edd6/jobs/208203
this fixes it.
> docs: Ran `make docs`

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.19.2

- .github/workflows/golangci-lint.yml
- Makefile
> chore: Bump golangci-lint to 1.50.0

- plugins/inputs/socket_listener/socket_listener_test.go
This PR reworks the socket_listener tests to be table based in order to be more extensible later. There is no functional change.
> chore(inputs.socket_listener): Reorganize test to be table-based.

- plugins/inputs/opcua/opcua.go
- plugins/inputs/opcua/opcua_test.go
> fix(inputs.opcua): Add metric tags to node

- cmd/telegraf/main.go
- cmd/telegraf/main_test.go
- cmd/telegraf/telegraf.go
- cmd/telegraf/telegraf_windows.go
- internal/process/process.go
- internal/process/process_posix.go
- internal/process/process_windows.go
- internal/syslog/framing_test.go
- logger/event_logger_test.go
- logger/logger.go
- logger/logger_test.go
- metric/metric.go
- metric/series_grouper.go
- models/running_output_test.go
- plugins/outputs/postgresql/sqltemplate/template.go
- plugins/outputs/postgresql/table_source.go
- plugins/outputs/postgresql/utils/utils.go
- selfstat/selfstat.go
- testutil/testutil_test.go
Plus some typos etc...
```
internal/process/process.go:84:2       revive       unhandled-error: Unhandled error in call to function p.Stdin.Close
internal/process/process_posix.go:15:3 revive       unhandled-error: Unhandled error in call to function cmd.Process.Signal
internal/process/process_posix.go:20:3 revive       unhandled-error: Unhandled error in call to function cmd.Process.Kill
internal/syslog/framing_test.go:10:2   revive       unhandled-error: Unhandled error in call to function f1.UnmarshalTOML
internal/syslog/framing_test.go:14:2   revive       unhandled-error: Unhandled error in call to function f2.UnmarshalTOML
internal/syslog/framing_test.go:18:2   revive       unhandled-error: Unhandled error in call to function f3.UnmarshalTOML
internal/syslog/framing_test.go:22:2 …
```
> chore: Resolve linter issues for unhandled-error

- plugins/inputs/dovecot/dovecot_test.go
- plugins/inputs/dovecot/testdata/dovecot.conf
> test: add dovecot integration test

- plugins/inputs/mongodb/README.md
> docs(inputs.mongodb): update supported versions

- plugins/common/tls/config.go
- plugins/inputs/gnmi/gnmi.go
- plugins/inputs/gnmi/gnmi_test.go
- plugins/outputs/amqp/client.go
- plugins/outputs/socket_writer/socket_writer.go
- plugins/outputs/syslog/syslog.go
- plugins/processors/strings/strings.go
resolves https://github.com/influxdata/telegraf/issues/12043
> chore: Resolve deprecated linter issues

- plugins/aggregators/starlark/README.md
> docs: corrected typo mentioning wrong func name

- plugins/inputs/http/README.md
- plugins/inputs/http/sample.conf
> docs(inputs.http): add use system proxy config option

- plugins/inputs/mcrouter/mcrouter_test.go
> test(inputs.mcrouter): add eventually to pause for metrics

- plugins/common/shim/input.go
- plugins/common/shim/processor.go
> chore(common.shim): check err of s.writeProcessedMetrics for the linter

- plugins/parsers/xpath/parser.go
**Note:** It seems like these tags are not taken care of by the deprecation mechanism, they are just added for semantics.
> chore(parsers.xpath): Add correct deprecation tags

- plugins/inputs/directory_monitor/directory_monitor.go
> fix(inputs.directory_monitor): allow moving files across filesystems

- plugins/inputs/gnmi/gnmi.go
resolves https://github.com/influxdata/telegraf/issues/12151
> chore: Ignore usages of deprecated fields from gnmi lib

- plugins/inputs/syslog/README.md
- plugins/inputs/syslog/sample.conf
> docs(inputs.syslog): mention usage of tcp4/6

- cmd/telegraf/printer.go
resolve https://github.com/influxdata/telegraf/issues/5887
> feat!: Disable [[outputs.influxdb]] in sample config

- plugins/common/aws/credentials.go
- plugins/common/opcua/opcua_util.go
- plugins/common/shim/example/cmd/main.go
> chore: Wrap long lines in plugins/common

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
> docs(outputs.kafka): specify broker behavior

- cmd/telegraf/main.go
- cmd/telegraf/printer.go
- config/config.go
- config/config_test.go
- logger/logger.go
- plugins/serializers/influx/influx_test.go
- plugins/serializers/json/json_test.go
- plugins/serializers/nowmetric/nowmetric.go
- plugins/serializers/nowmetric/nowmetric_test.go
- plugins/serializers/registry.go
- plugins/serializers/splunkmetric/splunkmetric_test.go
- tools/package_lxd_test/container.go
> chore: Wrap long lines in other locations

- plugins/inputs/x509_cert/README.md
- plugins/inputs/x509_cert/sample.conf
resolves #12245
Add missing option documentation.
> docs(inputs.x509_cert): Add documentation for 'exclude_root_certs' option

- plugins/inputs/x509_cert/dev/telegraf.conf
- plugins/inputs/x509_cert/x509_cert.go
- plugins/inputs/x509_cert/x509_cert_test.go
This PR cleans the code of certificate checking to add new features later.
> chore(inputs.x509_cert): Cleanup code

- plugins/inputs/prometheus/kubernetes.go
> fix(inputs.prometheus): correctly default to 9102 port

- plugins/inputs/gnmi/gnmi.go
resolves #12290
This PR changes the empty-name _error_ to a _warning_, explaining where the error comes from and adds instructions to open an issue with the response in question.
> chore(inputs.gnmi): Degrade empty-name error to a warning

- plugins/inputs/sqlserver/README.md
- plugins/inputs/sqlserver/sqlqueriesV2.go
- plugins/inputs/sqlserver/sqlserverqueries.go
> feat(inputs.sqlserver): add metric available_physical_memory_kb in sqlserver_server_properties

- go.mod
- go.sum
> fix(inputs.filecount): revert library version

- plugins/common/kafka/config.go
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
This PR adds a keep-alive setting to both `inputs.kafka_consumer` as well as `outputs.kafka`.
> feat(kafka): Add keep-alive period setting for input and output.

- config/config.go
> fix(secretstores): Fix handling of 'id' and print failing secret-store

- scripts/windows-signing.ps1
Remove the need for a password as it is not needed.
> chore: update windows signing script

- plugins/inputs/logstash/logstash.go
> fix(inputs.logstash): collect opensearch specific stats

- plugins/outputs/mqtt/README.md
N/A
N/A
resolves #
Correct the topic syntax description as go template ["Actions"](https://pkg.go.dev/text/template) ends with `}}` not `]]`
> docs(outputs.mqtt): fix minor syntax typo

- README.md
> chore: update package repo GPG key

- scripts/windows-signing.ps1
This reverts commit bfb26a8af6d7146eb336c0cbe794a55315077e1e.
> Revert "chore: update windows signing script (#12524)"

- plugins/inputs/mysql/mysql.go
- plugins/inputs/mysql/mysql_test.go
resolves #12487 
This PR adds support for using secret-store(s) for the servers.
> feat(inputs.mysql): Add secret-store support

- .circleci/config.yml
- Makefile
- internal/internal_test.go
- plugins/inputs/chrony/chrony_test.go
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.20

- plugins/inputs/prometheus/README.md
- plugins/inputs/prometheus/sample.conf
Fix typo in the README
resolves #
>  fix(inputs.prometheus): Fix typo in the README

- plugins/inputs/snmp/README.md
- plugins/inputs/snmp/sample.conf
- plugins/inputs/snmp_trap/README.md
> docs(inputs.snmp): Explain different snmp backends

- plugins/inputs/procstat/README.md
> docs(inputs.procstat): add ppid field

- plugins/aggregators/starlark/README.md
- plugins/inputs/conntrack/README.md
- plugins/inputs/sflow/README.md
- plugins/inputs/upsd/README.md
- plugins/outputs/cloudwatch/README.md
- plugins/outputs/graphite/README.md
- plugins/outputs/iotdb/README.md
- plugins/serializers/graphite/README.md
Fix the remaining issues found by _markdownlinter_.
> docs: Fix remaining markdownlinter issues

- docs/METRICS.md
- plugins/inputs/amqp_consumer/README.md
- plugins/inputs/amqp_consumer/sample.conf
- plugins/inputs/cloud_pubsub/README.md
- plugins/inputs/cloud_pubsub/sample.conf
- plugins/inputs/cloud_pubsub_push/README.md
- plugins/inputs/cloud_pubsub_push/sample.conf
- plugins/inputs/eventhub_consumer/README.md
- plugins/inputs/eventhub_consumer/sample.conf
- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/sample.conf
- plugins/inputs/kinesis_consumer/README.md
- plugins/inputs/kinesis_consumer/sample.conf
- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/sample.conf
- plugins/inputs/nats_consumer/README.md
- plugins/inputs/nats_consumer/sample.conf
- plugins/inputs/nsq_consumer/README.md
- plugins/inputs/nsq_consumer/sample.conf
> docs: tracking metrics

- plugins/inputs/cloudwatch/cloudwatch.go
> fix(inputs.cloudwatch): verify endpoint is not nil

- .circleci/config.yml
- Makefile
- go.mod
- internal/internal_test.go
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
- tools/update_goversion/main.go
* Updates to go1.20.1
* Updates the tooling to correctly update the go.mod and circleci files
* Updates a test that is expecting an error message :(
> chore: update to go1.20.1

- plugins/outputs/postgresql/README.md
> docs(outputs.postgresql): update URL for sql template

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Mention `make lint` in PR template and Contributing doc
> chore: Mention make lint in PR template and Contributing doc

- plugins/inputs/disk/README.md
- plugins/inputs/disk/disk.go
> feat(inputs.disk): add label as tag

- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
resolves #12734
The underlying jsonata-go library modifies some compiled expressions (e.g. `$each`) as described in #12734. As a result, the compiled expression becomes stateful varying after each (serialize) iteration creating changing or erroneous output even for identical and valid metrics and transformations.
To prevent this, we compile the given statement in each serialization iteration removing a potential state.
> fix(serializers.json): Fix stateful transformations

- docs/FAQ.md
> docs: update the FAQ

- go.mod
- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/modbus.go
- plugins/inputs/modbus/sample_general_begin.conf
- plugins/inputs/modbus/sample_general_end.conf
resolves #12784 
This PR exposes RS485 specific configuration options.
> feat(inputs.modbus): Add RS485 specific config options

- plugins/inputs/amqp_consumer/amqp_consumer.go
resolves #12811 
Improve the handling of defaults to avoid triggering deprecation warnings by not using `URL`.
> fix(inputs.amqp_consumer): Avoid deprecations when handling defaults

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.20.2

- output.go
> docs(typo): output.go

- accumulator.go
Remove extra dot
an metric -> a metric
> docs(typo): Update accumulator.go

- agent/agent.go
> docs: update agent.go comments

- EXTERNAL_PLUGINS.md
Added an external input plugin to gather statistics from HomeKit devices.
> feat: Add homekit plugin

- docs/AGGREGATORS.md
- docs/INPUTS.md
- docs/OUTPUTS.md
- docs/PROCESSORS.md
- internal/limiter/limiter.go
- models/running_output.go
- plugins/inputs/riemann_listener/riemann_listener.go
> docs: fix various typos in comments

- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/prometheus/prometheus_test.go
> fix(inputs.prometheus): use set over add for custom headers

- plugins/inputs/kubernetes/kubernetes.go
resolves #12917
use http.Client instead of lower level RountTripper to make HTTP requests. `http.Client.Timeout` is applied to the whole request time, not just part of it.
(courtesy of https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/)
> feat(inputs.kubernetes): apply timeout for the whole HTTP request

- plugins/inputs/upsd/README.md
- plugins/inputs/upsd/sample.conf
> docs(inputs.upsd): add comment about ipv6 addresses

- plugins/inputs/all/netflow.go
resolves NA
fix typo for netflow(_from netlow_) which was preventing custom builds of telegraf containing netflow input plugin.
> fix(inputs.netflow): Use correct name in the build tag

- .circleci/config.yml
This implements remote artifact signing and uploading releases to S3.
> feat: implement remote artifact signing

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.20.3

- plugins/parsers/avro/README.md
> docs: use single quotes for multi-line literal TOML

- plugins/inputs/mysql/README.md
- plugins/inputs/mysql/sample.conf
> docs(inputs.mysql): remove duplicate settings from config

- plugins/inputs/knx_listener/README.md
👋 Adds a link to related tool to improve discoverability a bit and ease config generation for people who use KNX Telegraf Input Plugin.
> docs(inputs.knx_listener): add a link to related project to ease config generation for KNX Telegraf Input Plugin

- plugins/aggregators/basicstats/README.md
- plugins/aggregators/basicstats/basicstats.go
- plugins/aggregators/basicstats/basicstats_test.go
- plugins/aggregators/basicstats/sample.conf
> feat(aggregators.basicstats): add percentage change

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.20.4

- plugins/inputs/cloud_pubsub/cloud_pubsub.go
resolves #13236
Fixed gzip decompression error when under high load
> fix(inputs.cloud_pubsub): fix gzip decompression

- go.mod
- go.sum
With the latest version the xpath library supports the `string-join()` function.
> chore(deps): Bump github.com/antchfx/xpath to latest master

- testutil/capturelog.go
replaces #13161
required-by #13060
> feat(test): Allow to capture all messages during test

- plugins/inputs/vsphere/README.md
- plugins/inputs/vsphere/sample.conf
resolves NA
Change `skip` to `ignore` in the sample configuration. Probably missed in the PR
> fix(inputs.vsphere): specify the correct option for `disconnected_servers_behavior` in the sample conf

- internal/templating/node.go
- plugins/inputs/cloudwatch/README.md
- plugins/inputs/consul/README.md
- plugins/inputs/directory_monitor/directory_monitor_test.go
- plugins/inputs/syslog/nontransparent_test.go
- plugins/inputs/syslog/octetcounting_test.go
- plugins/parsers/json_v2/parser.go
resolves #
remove repetitive the
> fix(docs): Remove repetitive "the"

- docs/CONFIGURATION.md
> chore(docs): clarify how taginclude/tagexclude work with processors

- config/config.go
- plugins/outputs/azure_data_explorer/azure_data_explorer.go
- plugins/outputs/azure_data_explorer/azure_data_explorer_test.go
- plugins/outputs/event_hubs/event_hubs_test.go
- plugins/outputs/http/http_test.go
- plugins/outputs/stomp/stomp_test.go
- plugins/serializers/all/json.go
- plugins/serializers/json/json.go
- plugins/serializers/json/json_test.go
- plugins/serializers/registry.go
This PR migrates the json serializer to the new-style framework.
> chore(serializers.json): Migrate to new-style framework

- plugins/inputs/mysql/mysql.go
resolves #13140
Fixes a partially incorrect regex in a query used to determine whether MariaDB is a certain version.
> fix(inputs.mysql): update MariaDB Dialect regex version check

- plugins/outputs/sql/README.md
This PR makes the README of the SQL output plugin more precise in two ways:
- extends the listing of required configuration changes necessary to make the integration work
- notes explicitly that the use of certain input plugins might make it necessary to initialize the database schema manually
> docs(outputs.sql): improve the documentation

- docs/includes/secret_usage.md
- plugins/secretstores/docker/README.md
- plugins/secretstores/http/README.md
- plugins/secretstores/jose/README.md
- plugins/secretstores/os/README.md
fixes: #13328
superseeds #13370
> docs: Add generic secret store usage

- plugins/inputs/internet_speed/README.md
- plugins/inputs/internet_speed/internet_speed.go
> fix(inputs.internet_speed): add location as a field

- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
resolves https://github.com/influxdata/telegraf/issues/10920#issuecomment-1084631081
> feat(inputs.procstat): Add status field

- cmd/telegraf/main.go
> fix(secretstore.jose): skip dbus with kwallet

- plugins/inputs/ravendb/README.md
Updated metrics requirements added in [previous PR](https://github.com/influxdata/telegraf/pull/13433) `README.md`.
> docs(inputs.ravendb): Changed metrics requirements in Readme.md

- plugins/inputs/intel_baseband/README.md
ACC101 devices will not enter the production phase, so it doesn't make sense to mention them anymore.
> docs(inputs.intel_baseband): Remove ACC101 mentions from documentation

- plugins/outputs/stackdriver/README.md
- plugins/outputs/stackdriver/sample.conf
- plugins/outputs/stackdriver/stackdriver.go
> fix(outputs.stackdriver): Add tag as resource label option

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
- plugins/inputs/kafka_consumer/sample.conf
This reverts commit a13f3463eb19a5095c12d58cf24caf24cce04289.
fixes: #13615
fixes: #13595
> Revert "feat(inputs.kafka_consumer): Refresh regexp topics periodically (#13410)"

- .circleci/config.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: update to go1.20.6

- .github/workflows/govulncheck.yml
see https://github.com/marketplace/actions/golang-govulncheck-action
> chore: update to official govulncheck github action

- plugins/inputs/prometheus/kubernetes.go
> fix(inputs.prometheus): don't collect metrics from finished pods

- plugins/outputs/azure_data_explorer/README.md
- [X ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)
resolves #13676 
Updates to README documentation with the supported flavors
> docs(outputs.azure_data_explorer): Update supported Azure Data Explorer flavors

- plugins/inputs/radius/radius_test.go
superseeds #13680 
This PR fixes the radius test to use a random port for the local test.
> test(inputs.radius): Use random port for test

- plugins/inputs/jenkins/README.md
- plugins/inputs/jenkins/jenkins.go
- plugins/inputs/jenkins/jenkins_test.go
- plugins/inputs/jenkins/sample.conf
> feat(inputs.jenkins): add option for node labels as tag

- plugins/inputs/conntrack/README.md
- plugins/inputs/conntrack/sample.conf
> docs(inputs.conntrack): Explain different collection methods

- plugins/inputs/jti_openconfig_telemetry/jti_openconfig_telemetry.go
> fix(inputs.jti_openconfig_telemetry): reauthenticate connection

- docs/CONFIGURATION.md
resolves #12502
This PR adds some notes on secret-stores, especially the solution found in #12502.
> docs(config): Add notes for secret-store pitfalls

- .golangci.yml
- plugins/inputs/snmp/netsnmp.go
- plugins/processors/strings/strings_test.go
fixes: #13184
fixes: #13195
fixes: #13196
fixes: #13198
> chore: Enable additional gocritic

- .golangci.yml
- internal/rotate/file_writer.go
- plugins/common/cookie/cookie.go
- plugins/common/starlark/field_dict.go
- plugins/inputs/azure_monitor/azure_monitor_test.go
- plugins/inputs/dpdk/dpdk.go
- plugins/inputs/intel_dlb/intel_dlb.go
- plugins/inputs/intel_rdt/intel_rdt.go
- plugins/inputs/jenkins/jenkins.go
- plugins/inputs/kibana/kibana.go
- plugins/inputs/libvirt/libvirt.go
- plugins/inputs/mailchimp/chimp_api.go
- plugins/inputs/mysql/mysql.go
- plugins/inputs/opensearch_query/opensearch_query_test.go
- plugins/inputs/phpfpm/fcgi.go
- plugins/inputs/phpfpm/fcgi_client.go
- plugins/inputs/postgresql_extensible/postgresql_extensible.go
- plugins/inputs/powerdns_recursor/protocol_v3.go
- plugins/inputs/salesforce/salesforce.go
- plugins/inputs/sflow/packetdecoder.go
- plugins/inputs/statsd/statsd.go
- plugins/inputs/teamspeak/teamspeak.go
- plugins/inputs/win_eventlog/util.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/inputs/zipkin/codec/thrift/thrift.go
- plugins/outputs/sumologic/sumologic.go
- plugins/outputs/syslog/syslog.go
Also moves golanglint to run in circleci due to memory issues as a
github action.
fixes: #13201
> chore: Resolves gocritic sloppyReassign

- plugins/inputs/redis/README.md
- plugins/inputs/redis/redis.go
- plugins/inputs/redis/redis_test.go
resolves [#13717](https://github.com/influxdata/telegraf/issues/13717)
> feat(inputs.redis): support of redis 6.2 ERRORSTATS

- plugins/inputs/prometheus/prometheus.go
- plugins/inputs/vsphere/endpoint.go
From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu
> chore(inputs): Remove unnecessary nil check

- plugins/inputs/couchbase/README.md
- plugins/inputs/couchbase/couchbase.go
- plugins/inputs/couchbase/couchbase_test.go
- plugins/inputs/couchbase/sample.conf
- plugins/inputs/couchbase/testdata/settings_autofailover.json
> feat(inputs.couchbase): Add failover metrics

- plugins/inputs/sysstat/sysstat.go
> fix(inputs.sysstat): fix tmpfile fd leak

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update to go1.21.1

- plugins/inputs/sqlserver/azuresqldbqueries.go
> fix(inputs.sqlserver): Cast max_size to bigint

- plugins/inputs/redis/README.md
- plugins/inputs/redis/redis.go
- plugins/inputs/redis/sample.conf
- plugins/inputs/redis_sentinel/README.md
- plugins/inputs/redis_sentinel/redis_sentinel.go
- plugins/inputs/redis_sentinel/sample.conf
> feat(inputs.redis_sentinel): Allow username and password

- plugins/inputs/redis/redis.go
> fix(inputs.redis): Fix password typo

- Makefile
- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
> fix(packaging): Revert permission change on configs

- plugins/inputs/sql/drivers_sqlite.go
- plugins/outputs/sql/sqlite.go
- plugins/outputs/sql/sqlite_test.go
Adds additional build directives to avoid a few other arch combos
> chore: Clean up results from make check-deps

- plugins/inputs/procstat/README.md
> docs(inputs.procstat): Add docs on permissions and metric details

- plugins/processors/lookup/README.md
> docs(processors.lookup): Fix wrong word usage

- internal/exec_unix.go
- plugins/inputs/exec/exec.go
- plugins/inputs/exec/run_notwinodws.go
- plugins/inputs/exec/run_windows.go
> fix(inputs.exec): Clean up grandchildren processes

- plugins/processors/starlark/starlark_test.go
> chore(processors.starlark): Add benchmark for field-value filter

- plugins/inputs/mock/README.md
- plugins/inputs/mock/mock.go
- plugins/inputs/mock/sample.conf
> fix(inputs.mock): Plugin not aligned with documentation

- plugins/inputs/openstack/openstack.go
> fix(inputs.openstack): Handle dependencies between enabled services a available endpoints

- scripts/deb/post-install.sh
- scripts/rpm/post-install.sh
> chore: Restore log directory behavior

- plugins/processors/split/README.md
> docs(processors.split): Fix example

- plugins/outputs/influxdb/README.md
Based on https://community.influxdata.com/t/get-telegraf-to-send-to-multiple-influxdb-hosts/3957
> docs(outputs.influxdb): Add help message about multiple influxdb

- plugins/inputs/redfish/README.md
- plugins/inputs/redfish/redfish.go
- plugins/inputs/redfish/redfish_test.go
- plugins/inputs/redfish/sample.conf
> feat(inputs.redfish): Allow specifying with metrics to collect

- plugins/outputs/nebius_cloud_monitoring/nebius_cloud_monitoring.go
resolves #14134 
New endpoint works like this:
```bash
curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/vendor/folder-id
b48bnn3jtboj8vb5uv8n
```
> fix(outputs.nebius_cloud_monitoring): fx endpoint

- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/kafka_test.go
- testutil/container.go
Rework and simplify integration test to (hopefully) fix CI issues.
> test(outputs.kafka): Rework integration test to use bitnami/kafka

- plugins/parsers/json/parser_test.go
- plugins/parsers/json_v2/parser_test.go
- plugins/parsers/json_v2/testdata/benchmark/benchmark.json
- plugins/parsers/json_v2/testdata/benchmark/expected.out
- plugins/parsers/json_v2/testdata/benchmark/input.json
- plugins/parsers/json_v2/testdata/benchmark/telegraf.conf
related to #14025 
This PR adds benchmarks for all parsers both for sequential and in-parallel parsing to asses performance effects of changes.
> test(parsers): Add benchmarks

- plugins/outputs/cratedb/README.md
add missing column "day" in sql statement in readme
resolves #
> docs(outputs.cratedb): Correct required SQL table schema

- plugins/inputs/ecs/ecs.go
- plugins/inputs/ecs/ecs_test.go
> fix(inputs.ecs): Test for v4 metadata endpoint

- plugins/inputs/temp/README.md
> docs(inputs.temp): Add additional troubleshooting steps

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update to go1.21.4

- plugins/inputs/intel_powerstat/README.md
- plugins/inputs/intel_powerstat/sample.conf
> docs(inputs.intel_powerstat): Add notes about hw/sw dependencies

- plugins/inputs/ecs/client.go
> fix(inputs.ecs): Correct v4 metadata URLs

- plugins/parsers/json_v2/parser.go
> fix(parsers.json_v2): Log, avoid hidding errors

- plugins/processors/all/noop.go
- plugins/processors/noop/README.md
- plugins/processors/noop/noop.go
- plugins/processors/noop/noop_test.go
- plugins/processors/noop/sample.conf
> feat(processors.noop): Noop processor

- plugins/parsers/binary/parser_test.go
> chore(parsers.binary): Add benchmark

- plugins/parsers/avro/parser_test.go
- plugins/parsers/avro/testdata/benchmark/expected.out
> chore(parsers.avro): Add benchmark for binary format

- plugins/parsers/xpath/parser_test.go
> chore(parsers.xpath): Add benchmark for msgpack format

- .github/PULL_REQUEST_TEMPLATE.md
- .markdownlintignore
- CONTRIBUTING.md
Updates the PR template to make it much shorter, removing items that are automatically checked by the bots and tests. Make it very clear in both the guidelines and PR template that AI generated code is not accepted.
fixes #
> docs: Update PR checklist, make clear AI generated code not accepted

- migrations/inputs_procstat/migration.go
- migrations/inputs_procstat/migration_test.go
- migrations/inputs_procstat/testcases/deprecated_tagging_false/expected.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_false/telegraf.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true/expected.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true/telegraf.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true_merge/expected.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true_merge/telegraf.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true_merge_overlap/expected.conf
- migrations/inputs_procstat/testcases/deprecated_tagging_true_merge_overlap/telegraf.conf
- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/procstat/sample.conf
based-on #14329
This PR converts the boolean flags for which information to use as a tag to a string list which is more extensible,
> chore(inputs.procstat): Convert bool tagging settings to a list

- plugins/inputs/rabbitmq/rabbitmq.go
remove inputs.rabbitmq useless comment
resolves #
> chore(inputs.rabbitmq): Remove useless comment

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update go1.21.5

- .gitignore
The .uuid is create by JetBrains Gateway
resolves #
> chore: Add .uuid to gitignore

- .golangci.yml
- cmd/telegraf/main.go
- cmd/telegraf/main_test.go
- cmd/telegraf/printer.go
- plugins/inputs/disque/disque.go
- plugins/inputs/influxdb_listener/influxdb_listener.go
- plugins/inputs/intel_dlb/intel_dlb_test.go
- plugins/inputs/varnish/varnish_test.go
- plugins/parsers/csv/parser.go
- plugins/serializers/csv/csv.go
resolves https://github.com/influxdata/telegraf/issues/14406 (preferDecodeRune)
resolves https://github.com/influxdata/telegraf/issues/14407 (preferFprint)
> chore(linters): Enable `preferDecodeRune` and `preferFprint` checkers for gocritic

- .golangci.yml
- plugins/inputs/amd_rocm_smi/amd_rocm_smi.go
- plugins/inputs/ecs/cgroupv2_test.go
- plugins/inputs/ecs/client.go
- plugins/inputs/ecs/client_test.go
- plugins/inputs/ecs/ecs.go
- plugins/inputs/ecs/ecs_test.go
- plugins/inputs/ecs/stats.go
- plugins/inputs/ecs/stats_test.go
- plugins/inputs/ecs/types.go
- plugins/inputs/ecs/types_test.go
- plugins/inputs/kube_inventory/daemonset.go
- plugins/inputs/kube_inventory/daemonset_test.go
- plugins/inputs/kube_inventory/deployment.go
- plugins/inputs/kube_inventory/deployment_test.go
- plugins/inputs/kube_inventory/node.go
- plugins/inputs/kube_inventory/node_test.go
- plugins/inputs/kube_inventory/persistentvolume.go
- plugins/inputs/kube_inventory/persistentvolume_test.go
- plugins/inputs/kube_inventory/pod.go
- plugins/inputs/kube_inventory/pod_test.go
- plugins/inputs/kube_inventory/service.go
- plugins/inputs/kube_inventory/service_test.go
- plugins/inputs/kube_inventory/statefulset.go
- plugins/inputs/kube_inventory/statefulset_test.go
- plugins/inputs/kubernetes/kubernetes.go
- plugins/inputs/nvidia_smi/schema_v11/parser.go
- plugins/inputs/nvidia_smi/schema_v12/parser.go
- plugins/inputs/vsphere/endpoint.go
- plugins/inputs/vsphere/vsphere_test.go
resolves https://github.com/influxdata/telegraf/issues/14411 (rangeValCopy)
resolves https://github.com/influxdata/telegraf/issues/14404 (hugeParams)
> chore(linters): Enable `rangeValCopy` and `hugeParams` checkers for gocritic

- .circleci/config.yml
Removing all caching before holiday.
> chore: Remove all CircleCI caching

- .github/workflows/govulncheck.yml
- .github/workflows/linter.yml
- .github/workflows/milestones.yml
- .github/workflows/readme-linter.yml
This PR bumps workflow actions in GitHub actions to their latest versions.
> chore(CI): Bump GitHub workflows to latest version

- plugins/inputs/snmp/README.md
- plugins/inputs/snmp/sample.conf
- plugins/inputs/snmp/snmp.go
Provide some additional information about the change for users after user feedback was seen in #14111.
> docs(inputs.snmp): Clarify the deprecation of agent tag setting

- docs/TOML.md
Adds a new TOML specific doc page to explain some common confusions around TOML.
> docs: Add notes about TOML

- plugins/aggregators/derivative/README.md
- plugins/inputs/http_response/README.md
Found after updating markdownlint to v0.39.0
> docs: Resolve table column count lint issues

- plugins/serializers/all/binary.go
- plugins/serializers/binary/README.md
- plugins/serializers/binary/binary.go
- plugins/serializers/binary/binary_test.go
- plugins/serializers/binary/entry.go
- plugins/serializers/binary/entry_test.go
- plugins/serializers/binary/type_conversions.go
Adds binary serializer plugin to let user communicate with e.g. raw tcp clients or writing binary messages to a file
resolves #14473
> feat(serializers): Add binary serializer

- plugins/inputs/chrony/README.md
- plugins/inputs/chrony/chrony.go
- plugins/inputs/chrony/chrony_test.go
- plugins/inputs/chrony/sample.conf
This PR allows to collect more metrics about chronyd than just the "tracking data".
resolves #2798
> feat(inputs.chrony): Allow to collect more data

- config/secret.go
- config/secret_test.go
Secret-references can only contain letters, digits and underscores, however some users might accidentally use dashes or other invalid character. Currently those invalid references are currently just silently ignored.
This PR logs a warning for any setting similar to a secret but containing invalid characters.
resolves #14662
> chore(secrets): Warn on settings looking like secrets but use invalid characters

- plugins/processors/clone/clone.go
- plugins/processors/clone/clone_test.go
Add unit-tests to the processor
resolves #14709
> test(processors.clone): Add unit-test for tracking metrics

- plugins/processors/regex/regex_test.go
> test(processors.regex): Add unit-test for tracking metrics

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- Makefile
- README.md
- go.mod
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
- testutil/tls.go
Update to go1.22.0
resolves #14705
resolves #12684
> chore: Update to go1.22.0

- plugins/processors/dedup/dedup_test.go
> test(processors.dedup): Add unit-test for tracking metrics

- plugins/processors/filter/filter_test.go
> test(processors.filter): Add unit-test for tracking metrics

- plugins/outputs/mqtt/mqtt.go
Currently, the MQTT output drops all metrics if an error occurred while publishing. This PR will keep the metrics and retry in case the publishing times out, which is the case if the remote server is down.
resolves #14750
> fix(outputs.mqtt): Retry metrics for server timeout

- plugins/processors/ifname/ifname_test.go
> test(processors.ifname): Add unit-test for tracking metrics

- plugins/processors/noise/noise_test.go
> test(processors.noise): Add unit-test for tracking metrics

- plugins/processors/pivot/pivot_test.go
> test(processors.pivot): Add unit-test for tracking metrics

- plugins/processors/scale/scale_test.go
> test(processors.scale): Add unit-test for tracking metrics

- plugins/processors/s2geo/s2geo_test.go
> test(processors.s2geo): Add unit-test for tracking metrics

- plugins/processors/rename/rename_test.go
> test(processors.rename): Add unit-tests for tracking metrics

- plugins/processors/topk/topk.go
- plugins/processors/topk/topk_test.go
> test(processors.topk): Add unit-test for tracking metrics

- plugins/processors/split/split_test.go
> test(processors.split): Add unit-tests for tracking metrics

- plugins/inputs/amd_rocm_smi/README.md
- plugins/inputs/amd_rocm_smi/amd_rocm_smi.go
- plugins/inputs/amd_rocm_smi/amd_rocm_smi_test.go
- plugins/inputs/amd_rocm_smi/sample.conf
Similarly to NVIDIA in #14680 completes the 2nd part of the #14603 issue for AMDGPU.
resolves #14603
> feat(inputs.amd_rocm_smi): Add startup_error_behavior config option

- config/config_test.go
- config/testdata/single_plugin_with_comment_in_array.toml
Add test for correctly handling comments in arrays.
resolves #10534
> test(config): Add unit-test for comments in arrays

- plugins/inputs/modbus/README.md
- plugins/inputs/modbus/sample_metric.conf
Remove extra comma.
fixes: #14878
> docs(inputs.modbus): Remove extra comma

- docs/specs/README.md
- docs/specs/overview.md
- docs/specs/template.md
Introduces the spec background and process for Telegraf.
> docs: Introduce spec overview and template

- docs/specs/tsd-001-deprecation.md
Publish internal specification for the deprecation framework and deprecation procedure in Telegraf.
> docs(spec): Add specification for deprecations

- CHANGELOG.md
Add an "important changes" note about the plugin option removal to the changelog.
resolves #13375
> docs(Changelog): Add note about removed deprecated plugin options

- .circleci/config.yml
- .github/workflows/govulncheck.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update to go1.22.1

- plugins/inputs/prometheus/kubernetes.go
The current implementation lists namespaces for later filtering PODs based on those namespaces. This is done unconditionally whether or not the user specified a filter at all. However, listing namespaces requires permissions to do so.
This PR only lists the namespaces in case a filtering on namespaces is actually requested!
resolves #13876
> fix(inputs.prometheus): List namespaces only when filtering by namespace

- plugins/inputs/win_wmi/win_wmi_test.go
Cleanup unit-test code.
related to #14942
> chore(inputs.win_wmi): Cleanup unit-tests

- .github/workflows/govulncheck.yml
Update the timeout as we seem to be consistently hitting it.
> chore: Update govulncheck timeout

- docs/PARSING_DATA.md
Intro to parsing metrics docs.
> docs: Add how to parse guide

- plugins/inputs/nvidia_smi/nvidia_smi_test.go
- plugins/inputs/nvidia_smi/schema_v12/parser.go
- plugins/inputs/nvidia_smi/schema_v12/types.go
- plugins/inputs/nvidia_smi/testdata/rtx-3080-v12.xml
Produce a new metric based on nvidia_smi process data.
fixes: #5546
> fix(inputs.nvidia_smi): Add process info metrics

- docs/CONFIGURATION.md
Clarify example description to avoid tagpass and tagdrop behavior misinterpretations.
resolves #14990
> docs(config): Clarify metric-routing example

- docs/includes/startup_error_behavior.md
- plugins/outputs/kafka/README.md
- tools/readme_config_includer/generator.go
Document the newly available options for the output plugin.
> docs(outputs.kafka): Document startup error behavior options

- go.mod
- go.sum
Update sarama dependency to pick up some new fixes around throttling.
> chore(deps): Bump github.com/IBM/sarama from v1.42.2 to v1.43.1

- plugins/inputs/win_services/README.md
- plugins/inputs/win_services/sample.conf
Update comments to in readme/sample config to also specify case-insensitve.
> docs(inputs.win_services): Specify case-insensitive naming

- plugins/inputs/x509_cert/README.md
The change explains the meaning of `expiry` field and how it can be used
resolves #15097
> docs(inputs.x509_cert): Explain expiry field

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Upgrade Go to 1.22.2

- plugins/inputs/postgresql/postgresql_test.go
This adds a unit-test trying to reproduce the issue described in #8586 on no reconnect if the server is not available. However, the plugin works as expected...
resolves #8586
> test(inputs.postgresql): Add unit-test for #8586

- agent/README.md
> docs(agent): Add README

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/sample.conf
Adds metadata options to docs, this was not added to the output in #https://github.com/influxdata/telegraf/pull/12111 only the input.
fixes: #15181
> docs(outputs.kafka): Add metadata options to docs

- models/running_input.go
- plugins/inputs/nvidia_smi/README.md
- plugins/inputs/nvidia_smi/nvidia_smi.go
- plugins/inputs/nvidia_smi/nvidia_smi_test.go
- plugins/inputs/nvidia_smi/sample.conf
Use the common implementation of startup-retry-behavior implementation.
> chore(inputs.nvidia_smi): Consolidate startup_retry_behavior to model implementation

- docs/README.md
Update the docs README with links to all pages.
> docs: Update docs readme with all links

- docs/RELEASES.md
Adds a formal page to the docs around releases.
> docs: Add releases documentation

- plugins/inputs/postgresql/README.md
Document permissions required for postgres input.
fixes: #15296
> docs(inputs.postgresql): Add permissions section

- plugins/inputs/mqtt_consumer/README.md
- plugins/inputs/mqtt_consumer/sample.conf
This is causing confusion and was brought up on the community forums.
> docs(inputs.mqtt_consumer): Update topic parsing types naming

- plugins/inputs/procstat/README.md
- plugins/inputs/procstat/process.go
- plugins/inputs/procstat/procstat.go
- plugins/inputs/procstat/procstat_test.go
- plugins/inputs/procstat/sample.conf
Add a config setting to list the properties the plugin should collect. By default all current features are collected to provide backward compatibility.
resolves #15295
> feat(inputs.procstat): Add option to select properties to collect

- plugins/inputs/kubernetes/README.md
> docs(inputs.kubernetes): Add link to generating bearer token to explore API

- README.md
After review with a friend we thought adding links to the various plugins mentioned would be helpful. Changed one other link's capitalization and format to match others as well.
> docs(readme): Add links to plugins

- docs/AGGREGATORS_AND_PROCESSORS.md
- docs/CONFIGURATION.md
Clean up the aggregator/processor doc page.
> docs: Update aggregator and processor docs

- docs/DOCKER.md
Rather than link to upstream, provide many more details, many from the install guide, as well.
> docs: Update docker page

- docs/INPUTS.md
Please check the `### External Services` section, which is new.
fixes: #12202
> docs(inputs): Clean up, add note about external connections

- docs/AGGREGATORS.md
Clean up docs, update links, clean example.
> docs(aggregators): Clean up aggregator docs

- docs/PROCESSORS.md
Clean up, re-order the sections, update links.
> docs(processors): Clean up

- docs/README.md
- docs/SECRETSTORES.md
Adds secret store doc page similar to other plugin types.
> docs(secretstores): Add docs for creating

- docs/SUPPORTED_PLATFORMS.md
Remove "current" versions and simplify the page.
> docs: Update supported platforms docs

- docs/EXTERNAL_PLUGINS.md
Cleans up the markdown, limits to 80 chars, reorganizes the text.
> docs: Update external plugin docs

- plugins/inputs/kafka_consumer/README.md
- plugins/inputs/kafka_consumer/kafka_consumer.go
- plugins/inputs/kafka_consumer/sample.conf
Introduce new option to change behavior of bootstrap servers. 
fixes: #15367
> feat(inputs.kafka_consumer): Add resolve canonical bootstrap server option

- internal/snmp/testdata/gosmi/tableMib
- plugins/common/shim/README.md
This PR fixes a few typos I spotted in the project.
> docs: Fix typos

- cmd/telegraf/cmd_plugins.go
- docs/CUSTOMIZATION.md
- plugins/parsers/deprecations.go
- plugins/serializers/deprecations.go
> feat(cli): List available parsers and serializers

- plugins/outputs/datadog/README.md
- plugins/outputs/datadog/sample.conf
Specify only v1 API support.
fixes: #15419
> docs(outputs.datadog): Specify API v1 support

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore(deps): Bump go from v1.22.3 to v1.22.4

- tools/package_incus_test/main.go
> test(incus): Update image list

- .golangci.yml
- internal/content_coding_test.go
- internal/internal_test.go
- internal/snmp/field.go
- plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go
- plugins/inputs/docker_log/docker_log_test.go
- plugins/inputs/http_listener_v2/http_listener_v2_test.go
- plugins/inputs/influxdb_listener/influxdb_listener_test.go
- plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go
- plugins/inputs/nsd/nsd_test.go
- plugins/inputs/openntpd/openntpd_test.go
- plugins/inputs/opensmtpd/opensmtpd_test.go
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/unbound/unbound_test.go
- plugins/inputs/varnish/varnish_test.go
- plugins/inputs/win_perf_counters/win_perf_counters.go
- plugins/outputs/sql/sql_test.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
- tools/readme_config_includer/generator.go
> test(lint): Enable mirror

- .golangci.yml
> test(lint): Enable badSyncOnceFunc

- .golangci.yml
- plugins/common/cookie/cookie_test.go
- plugins/inputs/intel_pmu/reader.go
- plugins/inputs/neptune_apex/neptune_apex_test.go
- plugins/inputs/x509_cert/x509_cert_test.go
- plugins/parsers/csv/parser.go
- plugins/parsers/graphite/config.go
- plugins/parsers/json/json_flattener.go
- plugins/processors/strings/strings.go
- tools/config_includer/generator.go
> test(linters): Enable copyloopvar

- plugins/inputs/netflow/sflow_v5.go
This PR adds the missing fields for sFlow extended gateway packets.
resolves #15430
> feat(inputs.netflow): Add more fields for sFlow extended gateway packets

- docs/CONFIGURATION.md
feat: Improve Modifier Explanation
MINOR: Enhanced the explanation of how the Modifier works for better clarity.
For newcomers, the impact of using modifiers on the data might not be clear. This update aims to clarify that aspect.
resolves #
> docs: Further clarify modifiers

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update to Go v1.22.5

- plugins/outputs/remotefile/remotefile.go
> fix(outputs.remotefile): Resolve linter not checking error

- cmd/telegraf/main.go
- plugins/inputs/tail/README.md
- plugins/inputs/tail/sample.conf
Clarify the differences and when one is used over the other.
> docs: Clarify poll vs notify

- go.mod
Move the non-indirect imports up.
> chore: Clean up go.mod

- cmd/telegraf/telegraf.go
To help out when testing adding and deleting config files it is helpful to know what actually was added or deleted. This adds the filename to the various messages.
> chore(agent): Print config filename in messages for clarity

- plugins/inputs/hddtemp/README.md
> docs(inputs.hddtemp): Document hddtemp removal and alternatives

- plugins/inputs/nats/README.md
Fixed link to nats monitoring .
resolves #15711
> docs(inputs.nats): Update NATS monitoring URL

- plugins/inputs/netflow/README.md
Add subsection on metrics tagging.
resolves #15676
> docs(inputs.netflow): Add note on how to tag metrics

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore(deps): Bump Go from v1.22.5 to v1.22.6

- plugins/inputs/pgbouncer/pgbouncer_test.go
The following PR updates the PgBouncer container inside test case.
> test(inputs.pgbouncer): Update container version

- plugins/inputs/chrony/README.md
- plugins/inputs/chrony/sample.conf
I spent way to long trying to figure out why it couldn't connect to the socket even after testing as the telegraf user that chronyc could use the socket.
Just a small documentation update.
resolves #15762
> docs(inputs.chrony): Update schema to unixgram

- .golangci.yml
> chore(linters): Enable `optimize-operands-order` rule for revive

- .golangci.yml
resolves #15799
resolves #15800
resolves #15801
resolves #15802
> chore(linters): Enable G405, G406, G506 and G507 rules for gosec

- metric/metric.go
Performance. For measurements with large amounts of fields, this starts having an impact.
resolves #15888
> perf(agent): Reduce complexity of creating new metrics to 'O(N_fields)'

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update to latest go version.
resolves #15875
> chore: Update go to v1.23.1

- .golangci.yml
> chore(linters): Enable `max-public-structs` rule for revive

- plugins/inputs/modbus/modbus.go
Add some more details on request grouping.
> chore(inputs.modbus): Add more debug information for request grouping

- cmd/telegraf/cmd_win_service.go
> chore(agent): Fix typo in service install command

- plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
- plugins/inputs/kafka_consumer/kafka_consumer_test.go
Fixing test compilation for the "old" code that was merged into `master` after merging this PR: https://github.com/influxdata/telegraf/pull/15836
> test(compilation): Fixing test compilation

- .golangci.yml
- plugins/common/shim/goshim_test.go
- plugins/common/shim/input_test.go
- plugins/inputs/execd/shim/shim_test.go
More info: https://stackoverflow.com/questions/64355668/data-race-within-go-function-with-named-return-values
resolves #15809
> chore(linters): Enable `datarace` rule for revive

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update go to v1.23.3

- .github/workflows/semantic.yml
As we squash-merge commits we only keep the PR title in the master branch. Therefore it is not necessary to check the commit messages.
> chore(actions): Only check PR title for semantic commit message

- plugins/serializers/json/README.md
Change "json_tansformation" to "json_transformation"
resolves #16243
> docs(serializers.json): Fix typo

- plugins/inputs/vsphere/README.md
- plugins/inputs/vsphere/finder.go
Adds CPU temperature from the numeric sensor info as an optional metric field
resolves #11162
> feat(inputs.vsphere): Add cpu temperature field

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update go to v1.23.4

- docs/FAQ.md
- docs/RELEASES.md
Update the link to the release calendar.
> chore: Update link to release calendar

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
> chore: Update go to v1.23.5

- go.mod
- go.sum
- plugins/serializers/prometheus/convert.go
- plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
Adapt code to changes in the package.
related to #16445
> chore(deps): Bump github.com/prometheus/common from 0.61.0 to 0.62.0

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- .golangci.yml
- Makefile
- config/config_test.go
- go.mod
- plugins/inputs/beanstalkd/beanstalkd.go
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update go version to latest
resolves #16487
> chore: Update go to v1.24.0

- plugins/aggregators/basicstats/README.md
- plugins/aggregators/derivative/README.md
- plugins/aggregators/final/README.md
- plugins/aggregators/histogram/README.md
- plugins/aggregators/merge/README.md
- plugins/aggregators/minmax/README.md
- plugins/aggregators/quantile/README.md
- plugins/aggregators/starlark/README.md
- plugins/aggregators/valuecounter/README.md
- plugins/inputs/dpdk/README.md
- plugins/inputs/ethtool/README.md
- plugins/inputs/example/README.md
- plugins/inputs/fail2ban/README.md
- plugins/inputs/influxdb/README.md
- plugins/inputs/influxdb_listener/README.md
- plugins/inputs/influxdb_v2_listener/README.md
- plugins/outputs/amon/README.md
- plugins/outputs/event_hubs/README.md
- plugins/outputs/graylog/README.md
- plugins/outputs/socket_writer/README.md
Add missing tags and unify existing ones.
> docs: Fix issues for existing metadata

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Update go version to latest.
resolves #16590
> chore: Update go to v1.24.1

- plugins/outputs/influxdb_v2/http.go
- plugins/outputs/influxdb_v2/influxdb_v2_test.go
> fix(outputs.influxdb_v2): Use dynamic token secret

- plugins/inputs/fritzbox/fritzbox.go
- plugins/inputs/fritzbox/fritzbox_test.go
Fix linter issues after this new plugin merged
resolves #
> chore(inputs.fritzbox): Fix linter issues

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
- .github/ISSUE_TEMPLATE/SUPPORT.yml
I noticed a couple tiny issues in our issue templates, so went ahead and updated them
resolves #
> chore: Fix issues in issue templates

- plugins/outputs/http/http.go
This PR makes response errors detected as "non-retryable" _also_ include a sample of the response body in the error log.
resolves #16596
> feat(outputs.http): Include body sample in non-retryable error logs

- tools/readme_linter/assert.go
- tools/readme_linter/main.go
- tools/readme_linter/rules.go
This PR adds a check for the plugin metadata required for document generation.
> chore(tools): Add metadata check to README linter

- plugins/inputs/snmp_trap/snmp_trap_test.go
Cleanup the test code without any functional changes.
related to #16222
> chore(inputs.snmp_trap): Cleanup testing

- plugins/parsers/json_v2/README.md
Updated readme file for json v2 input parser
> docs(parsers.json_v2): Fix wording

- plugins/inputs/snmp_trap/logger.go
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
This PR cleans the SNMP trap code in preparation of fixing #16222.
related to #16222
> chore(inputs.snmp_trap): Cleanup code

- plugins/common/ratelimiter/limiters.go
Allow to reserve and release memory for sharing the rate between multiple (potentially failing) go-routines.
in preparation of #16741
> feat(common.ratelimiter): Implement means to reserve memory for concurrent use

- go.mod
- go.sum
- plugins/inputs/snmp_trap/snmp_trap.go
- plugins/inputs/snmp_trap/snmp_trap_test.go
Bump upstream library to fix authentication for v3 traps. Also add some unit-tests to prevent future regressions.
based on #16810
resolves #16222
> chore(deps): Bump github.com/gosmnp/gosnmp from 1.39.0 to 1.40.0

- docs/WINDOWS_SERVICE.md
Fill the missed symbol \
resolves #
> docs: fill the missed symbol \ in WINDOWS_SERVICE.md

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Updates go to 1.24.3
resolves #16979
> chore: Update go to 1.24.3

- testutil/metric.go
Simplified loops and reduced redundant checks in lessFunc.
Optimized slice handling with preallocation and copy() in metric diff functions.
Removed unnecessary variable assignments for cleaner returns.
Avoided repeated method calls by caching results.
Preallocated map capacities for better performance.
resolves #
> test(testutil): Performance and code quality improvements on metric

- config/migration.go
This PR fixes an issues with migrations where a general migration is run before a plugin migration to e.g. migrate an option common to many plugins. The issue arises due to a missing update to the internal TOML table not being updated before passing it to the following migrations. The PR updates the TOML table of the internal struct before passing it on and also switches the order to first update general options and individual plugins afterwards.
> fix(migrations): Update table content for general plugin migrations

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Updates Go to 1.24.4
resolves #17164
> chore: Update go to 1.24.4

- plugins/common/socket/socket_test.go
Fix flaky test by waiting for the closed connection to be registered by the stream socket implementation.
> test(common.socket): Fix flaky test

- testutil/file.go
This optimization transforms:
```go
// Expensive: Allocate + Copy + Compare
strings.HasPrefix(string(line), "#")
```
Into:
```go
// Cheap: Just Compare
line[0] == '#'
```
So this small optimization gets multiplied by every line in every file we process.
resolves #
> test(testutil): Performance and code quality improvements on file

- plugins/inputs/cpu/README.md
- plugins/inputs/docker/README.md
- plugins/inputs/docker/sample.conf
- plugins/inputs/docker_log/README.md
- plugins/inputs/dovecot/README.md
This PR syncs the website docs' texts back to Github.
> docs: Improve wording

- plugins/processors/snmp_lookup/lookup_test.go
- plugins/processors/snmp_lookup/store.go
When stopping the SNMP lookup processor deferred tasks might still be active. Those tasks will try to issue an SNMP lookup after the minimum time between updates has passed. However, as the plugin was stopped the pool is also stopped and won't accept any new tasks to be enqueued. This in turn leads to a panic.
This PR makes sure to stop all deferred update timers and, as a safety guard, will make sure that tasks are not submitted to a stopped pool.
resolves #17289
> fix(processors.snmp_lookup): Avoid re-enqueing updates after plugin stopped

- plugins/outputs/stackdriver/stackdriver_test.go
> test(outputs.stackdriver): Cleanup tests

- .github/workflows/milestones.yml
Update the milestone action to the [latest version](https://github.com/srebhan/label-milestone-action/releases/tag/v1.0.2) 
resolves #17343
> chore(CI): Update milestone action

- plugins/inputs/vsphere/README.md
removed deprecated option `force_discover_on_init` from docs
resolves #
> docs(inputs.vsphere): Remove deprecated option

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Updates Go to 1.24.5
resolves #17313
> chore: Update Go to 1.24.5

- plugins/outputs/microsoft_fabric/README.md
- plugins/outputs/microsoft_fabric/sample.conf
> docs(outputs.microsoft_fabric): Changes as per Fabric

- plugins/outputs/kafka/README.md
- plugins/outputs/kafka/kafka.go
- plugins/outputs/kafka/kafka_test.go
- plugins/outputs/kafka/sample.conf
This PR cleans-up the code of the Kafka output plugin in preparation of adding internal statistics.
> chore(outputs.kafka): Cleanup code

- selfstat/collector.go
- selfstat/selfstat.go
- selfstat/stat.go
- selfstat/timingStat.go
Add functions to efficiently cleanup registered stats.
related to #17277 
related to #17548
> chore(selfstat): Add functions to unregister stats

- .circleci/config.yml
- .github/workflows/readme-linter.yml
- Makefile
- scripts/ci.docker
- scripts/installgo_linux.sh
- scripts/installgo_mac.sh
- scripts/installgo_windows.sh
Updates Go to 1.25.1
resolves #17565
> chore: Update Go to 1.25.1

- plugins/inputs/syslog/syslog_test.go
This PR fixes a race condition in syslog tests where an error is expected but no metric. E.g.
```
=== FAIL: plugins/inputs/syslog TestCases/rfc5424_strict_toolong_appname (0.00s)
2025-09-05T07:47:44Z I! Loading config: testcases/rfc5424_strict_toolong_appname/telegraf.conf
2025-09-05T07:47:44Z I! [inputs.syslog] Listening on udp://127.0.0.1:57226
syslog_test.go:278: 
Error Trace:    /go/src/github.com/influxdata/telegraf/plugins/inputs/syslog/syslog_test.go:278
Error:          Should NOT be empty, but was []
Test:           TestCases/rfc5424_strict_toolong_appname
=== FAIL: plugins/inputs/syslog TestCases/rfc5424_strict_udp_min_incomplete (0.00s)
2025-09-05T07:47:45Z I! Loading config: testcases/rfc5424_strict_udp_min_incomplete/telegraf.conf
2025-09-05T07:47:45Z I! [inputs.syslog] …
```
> test(inputs.syslog): Fix race condition in test for expected errors

- plugins/common/shim/README.md
- plugins/inputs/opentelemetry/README.md
- plugins/inputs/rabbitmq/README.md
Fix remaining violations in existing plugins.
> docs(plugins): Fix remaining line-length in plugin READMEs
