influxdata/telegraf

plugins/inputs/gnmi/README.md, plugins/inputs/gnmi/gnmi.go
This PR adds support for `bytes` encoding for the gNMI messages as per [2.3.2 of gNMI specification](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#232-bytes).
The code [already had a support for `bytes`](https://github.com/influxdata/telegraf/blob/effe112473a6bd8991ef8c12e293353c92f1d538/plugins/inputs/gnmi/gnmi.go#L337-L338) encoded values, it [was just not allowed](https://github.com/influxdata/telegraf/blob/effe112473a6bd8991ef8c12e293353c92f1d538/plugins/inputs/gnmi/gnmi.go#L182) to specify this encoding in the appropriate check before.
The only changes made to the plugin were to allow to specify `bytes` as the `encoding`.
Config file:
```toml
[[inputs.gnmi]]
addresses = ["r1:14946"]
username = "admin"
password = "nokia"
encoding = "bytes"
redial = …
```
=> Support for bytes encoding for "gnmi" input plugin

README.md, plugins/outputs/all/all.go, plugins/outputs/yandex_cloud_monitoring/README.md, plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go, plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring_test.go
=> #8295 Initial Yandex.Cloud monitoring

plugins/outputs/wavefront/README.md, plugins/outputs/wavefront/wavefront.go
Addresses an issue mentioned in #7409 concerning the "double buffering" done by the Wavefront SDK. The SDK is designed to send metrics asynchronously in order to minimize the delay experienced by a caller. This behavior is not ideal when used with Telegraf, since Telegraf will assume the connection to Wavefront can accept data very quickly. When the internal buffer in the Wavefront SDK overflows, it will drop metrics. Meanwhile, Telegraf will still think the metrics are flowing at a very high rate and will keep flooding the SDK. 
To avoid extensive redesign of the SDK, this PR adds a flag, ```immediate_flush``` that flushes the internal SDK buffers after each batch. This will ensure that the buffer never fills with more records than the batch size and also has the side effect of providing …
=> [output.wavefront] Introduced "immediate_flush" flag

config/config.go, config/config_test.go
Ideas behind this change: 
- reduce duplication by providing standard methods for parsing field types.
- allow reusing fields by not deleting them
- delay unused field errors by instead adding them to a list and removing it if it's later processed
- reduce repetitious error handling by collecting errors on the config
- provide our own toml.Config settings that allows us to capture missingField errors and handle them ourselves.
=> shorten config

plugins/inputs/redfish/redfish.go
When using the redfish plugin against an HPE iLO4 host it fails parsing the responses. This is due to a backwards compatibility in iLO4 to before the standardization of field naming in embedded links. Setting the optional `OData-Version` on request headers signals the server to reply in a redfish 1.0 conformant format (https://hewlettpackard.github.io/ilo-rest-api-docs/ilo4/#redfish-1-0-conformance). This will not change the responses from already compliant hosts (tested against iDRAC)  
Fixes #8093
=> Add OData-Version header to requests

plugins/inputs/smart/smart.go, plugins/inputs/smart/smart_test.go
It was wrongly assumed that device names from config should be validated. This PR removes this validation (added in 1.16.0).
Moreover, issues found by `golint` were addressed.
This should fix: https://github.com/influxdata/telegraf/issues/8313
=> Fix SMART plugin to recognize all devices from config

plugins/inputs/systemd_units/README.md, plugins/inputs/systemd_units/systemd_units_linux.go
This addresses #7990. Tested on Arch Linux running v246 and Debian Buster running v241
=> systemd_units: add --plain to command invocation (#7990)

plugins/inputs/proxmox/README.md, plugins/inputs/proxmox/proxmox.go, plugins/inputs/proxmox/proxmox_test.go, plugins/inputs/proxmox/structs.go
- Ignore QEMU templates
- Fix logger calls (`Error` -> `Errorf`)
- Changed confusing error `node_name not found` to `search domain is not set`
- Fix creator to return a pointer to new struct on every call (now it uses the same struct every time, which results in gathering only the last input of proxmox in the configuration)
- Updated README.md to acknowledge the default value of `node_name`
=> proxmox: ignore QEMU templates and iron out a few bugs

plugins/parsers/csv/parser.go
Alternative to PR #6324 also fixing all other plugins (e.g. `tail`). This resolves [issue #6318](https://github.com/influxdata/telegraf/issues/6318) in my setup.
=> Fix parsing of multiple files with different headers (#6318).

plugins/processors/starlark/README.md, plugins/processors/starlark/builtins.go, plugins/processors/starlark/starlark.go, plugins/processors/starlark/starlark_test.go
Fix for https://github.com/influxdata/telegraf/issues/8354
There is no way to manage error returned in the apply function.
* Adds a new built-in function called `catch` based on the function of the same name of [`starlarktest`](https://github.com/google/starlark-go/blob/master/starlarktest/starlarktest.go#L79-L88)
* Adds a new test to ensure that it works as expected
* Adds a new sub section of **Common Questions** into the `README.md` to describe how to use it
=> Allow to manage errors that occur in the apply function

plugins/outputs/wavefront/wavefront.go
Currently we assume all wavefront send errors are retryable, and when an
error happens during Write function we will reject the buffer and keep
retrying the next tick. This means that when an actually non-retryable
error happens, we'll just keep getting the same error on every tick, and
never flush the buffer.
One such error we encountered is "empty metric name" error.
Add isRetryable function to detect non-retryable errors, and make it
default to assume that all errors are retryable (so it matches the
current behavior), but make it possible to mark certain errors as
non-retryable.
Currently only handled that "empty metric name" error as non-retryable.
A support ticket has been filed against wavefront to provide a canonical
way to distinguish between retryable and non-retryable errors. …
=> Wavefront output should distinguish between retryable and non-retryable errors

plugins/outputs/wavefront/wavefront.go
Adds debug level logging for metric data that is not retryable. fixes #8405
=> add non-retryable debug logging

plugins/processors/starlark/README.md, plugins/processors/starlark/logging.go, plugins/processors/starlark/starlark.go, plugins/processors/starlark/starlark_test.go, plugins/processors/starlark/testdata/logging.star
Fix for #8402
Logging primitives to tie into the Telegraf logger are missing
* Adds a new module to manage all the logging primitives
* Uses a static logger to log the message as there is no easy way to use the current one
=> Support logging in starlark

config/config.go
resolves https://github.com/influxdata/telegraf/issues/8417
=> fix config issue with tags

plugins/processors/starlark/README.md, plugins/processors/starlark/starlark_test.go, plugins/processors/starlark/testdata/multiple_metrics.star, plugins/processors/starlark/testdata/multiple_metrics_with_json.star
Fix for #8371
It seems to be unclear for end-users to return several metrics from the Starlark processor
* Adds a new Starlark script to show how to return several metrics thanks to [a list of metrics](https://docs.bazel.build/versions/master/skylark/lib/list.html)
* Adds the corresponding unit test that proves that it works as expected
* Refers the new Starlark script from the `README.md`
=> Show how to return several metrics with the Starlark processor

plugins/parsers/csv/parser.go, plugins/parsers/csv/parser_test.go
**Root Cause Analysis:**
Within the csv parser, the field name for the `csv_timestamp_column` is, initially, converted from a `string` into an `int`. This causes the field name (for example: `202011131605`) to be interpreted as a Unix format (instead of the Go reference time `200601021504`).
**The Fix:**
- Prevent implicit type conversion on the timestamp column, so that `parseTimestamp` can correctly parse the time as unix or UTC
- Added a unit test to verify `TimestampFormat:   "200601021504"`
closes #7288
=> Keep field name for csv timestamp column (don't implicitly convert)

plugins/processors/starlark/README.md, plugins/processors/starlark/starlark_test.go, plugins/processors/starlark/testdata/fail.star
Fix for #8403 
It seems to be unclear for end-users to return a custom error with the Starlark processor
* Adds a new Starlark script to show how to return a custom error thanks to the function [fail](https://docs.bazel.build/versions/master/skylark/lib/globals.html#fail)
* Adds the corresponding unit test that proves that it works as expected
* Refers the new Starlark script from the `README.md`
=> Show how to return a custom error with the Starlark processor

plugins/aggregators/basicstats/README.md, plugins/aggregators/basicstats/basicstats.go, plugins/aggregators/basicstats/basicstats_test.go
Added `rate`, `non_negative_rate` and `interval` calculations to the basicstats aggregator.
=> Add rate and interval to the basicstats aggregator plugin

plugins/common/kafka/config.go, plugins/inputs/kafka_consumer/README.md, plugins/inputs/kafka_consumer/kafka_consumer.go, plugins/inputs/kafka_consumer/kafka_consumer_test.go, plugins/outputs/kafka/README.md, plugins/outputs/kafka/kafka.go, plugins/outputs/kafka/kafka_test.go
=> Enable kafka zstd compression and idempotent writes

plugins/outputs/nats/README.md, plugins/outputs/nats/nats.go, plugins/outputs/nats/nats_test.go
Added `name` parameter to the NATS output plugin. The connection name simplifies monitoring, debugging and reporting. 
See: https://docs.nats.io/developing-with-nats/connecting/name
=> Added "name" parameter to NATS output plugin

plugins/processors/starlark/README.md, plugins/processors/starlark/starlark_test.go, plugins/processors/starlark/testdata/drop_fields_with_unexpected_type.star, plugins/processors/starlark/testdata/drop_string_fields.star
Starlark example for dropping fields of metrics by the value type. This is a suitable replacement for PR #3763.
=> Starlark example dropbytype

go.mod, go.sum
1. Most importantly, this version runs on Dragonfly BSD, which might
be an issue that potential users would care about.
2. Re-issues syscall request after EINTR.
More resiliant on Go v1.14 and above, where syscall is more likely
to return syscall.EINTR.
Also, alongside the place where it would instead call
golang.org/x/sys/unix, but it is commented out, I include the
equivalent code for checking for unix.EINTR, to make it less likely
that I forget to change the EINTR check if I ever convert it to use
golang.org/x/sys/unix rather than syscall.
3. Performance improvements for unix and Windows.
NOTE: While updated godirwalk package now runs on Dragonfly BSD, I did not test whether the remainder of telegraf also runs on Dragonfly BSD, so I did not add Dragonfly BSD to the README.md file.
NOTE …
=> update godirwalk to v1.16.1 (dragonfly support)

plugins/inputs/zfs/README.md, plugins/inputs/zfs/zfs.go, plugins/inputs/zfs/zfs_freebsd.go, plugins/inputs/zfs/zfs_freebsd_test.go
=> Add dataset metrics to zfs input

plugins/inputs/procstat/README.md
Newer versions of Telegraf for Windows do not appear to support using WMI query patterns as values for the "pattern" option. Regular expressions appear to be the only patterns now supported.
=> Removed outdated information about Windows support

plugins/inputs/gnmi/gnmi.go, plugins/inputs/gnmi/gnmi_test.go
Added logging of the SubscribeResonse_Error response types to fix #8482
=> Log SubscribeResponse_Error message and code

Makefile, README.md, scripts/release.sh
=> add support for linux/ppc64le

go.mod, go.sum, plugins/parsers/grok/parser_test.go
related: #4003
Currently grok package seems no longer maintained, the latest commit merged the support for field names containing '-' and '.', maybe we can update to this commit.
=> Update grok package to support for field names containing '-' and '.'

plugins/inputs/opcua/README.md, plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go
Remove unneeded node settings (data_type and description).
Add the concept of a node group.  Groups have default settings for all nodes in the group.  They also are able to override the plugin's metric name so multiple metric names can be used in a single plugin instance.
Remove the name tag which wasn't useful because it duplicated the OPC UA value's field name.
Expose stats to telegraf internal plugin.
=> Add node groups to opcua input plugin

plugins/inputs/sqlserver/sqlserver.go
This column is used to distinguish between outputs of queries that have the same value in column [measurement], such as sqlAzureDBResourceStats and sqlAzureMIResourceStats.
=> Add column measurement_db_type to output of all queries

plugins/inputs/bind/README.md, plugins/inputs/bind/bind.go, plugins/inputs/bind/bind_test.go, plugins/inputs/bind/json_stats.go, plugins/inputs/bind/xml_stats_v2.go, plugins/inputs/bind/xml_stats_v3.go
closes #8443 
**The Fix:**
- Created `Init()` function with configurable timeout param
=> Add configurable timeout to bind input plugin http call

plugins/inputs/http_response/http_response.go, plugins/inputs/http_response/http_response_test.go
Fixed network test by adding a mock client for failing test coming back with connection failure instead of dns failure
=> fixed network test 

plugins/inputs/statsd/README.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
The new config value will establish how long any metric can sit in the gauges/counters/timings/sets without being updated / received. When the Max TTL elapses, the metric will stop being reported until it was received again.
closes #8348
=> Add configurable Max TTL duration for statsd input plugin entries

plugins/processors/execd/execd.go, plugins/processors/execd/execd_test.go
=> Adding support for new lines in influx line protocol fields.

.circleci/config.yml
The current circleci mac executor has an old homebrew which provides golang 1.13.6.  This is used in CI macdeps and test-go-darwin.  Homebrew itself can provide a newer golang but updating it takes a few minutes each CI run.
This PR switches to a newer circleci executor and updates the cache key to avoid reusing the cache from the previous executor.  (see https://circleci.com/docs/2.0/caching/#managing-caches)  The newer executor has an updated homebrew that provides golang 1.15.3 without updating.
#8391 and #8496 depend on updated golang during CI
=> Update circleci mac golang version

plugins/inputs/kube_inventory/README.md
The field values for kubernetes_pod_container has a few name mismatches with what's in code.
=> Fix kube_inventory readme

plugins/inputs/snmp/README.md, plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go
=> Add support to convert snmp hex strings to integers

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
=> Fix #7344: Add percentiles to the ping plugin

plugins/inputs/jenkins/README.md, plugins/inputs/jenkins/jenkins.go, plugins/inputs/jenkins/jenkins_test.go
This PR adds `number` field to `jenkins_job` measurement. It allows eg. to create links to specific builds in dashboards.
Example output (`telegraf --config telegraf.conf --input-filter jenkins --test`):
```
2020-08-26T14:42:29Z I! Starting Telegraf 
> jenkins,host=jenkins.bonitoo4influxdata.com,port=8443,source=localhost busy_executors=2i,total_executors=8i 1598452951000000000
...
> jenkins_job,host=jenkins.bonitoo4influxdata.com,name=deploy-tickstack-eprise-partial,port=8443,result=SUCCESS,source=localhost duration=108962i,number=1091i,result_code=0i 1598450671000000000
```
=> feat(plugins/input/jenkins): add build number field to jenkins_job measurement

plugins/inputs/vsphere/endpoint.go
Due to a spelling error in an if-statement, the code to resolve names of datacenters was called even when the name was known. This also caused a somewhat misleading debug message to be shown.
=> Fixed minor issue in datacenter name lookup code

plugins/inputs/kube_inventory/README.md, plugins/inputs/kube_inventory/node.go, plugins/inputs/kube_inventory/node_test.go
The Allocatable cpu value returned from Kubernetes can have a milli suffix, which gets parsed as 0 when stored in allocatable_cpu_cores.
This change updates the metric to be millicpus to prevent truncation of decimals.
=> Update string parsing of allocatable cpu cores in kube_inventory

plugins/inputs/github/README.md, plugins/inputs/github/github.go
This adds the possibility to query the number of "open" and "closed" pull-requests from a GitHub repository. We hide this behind a new `additional_fields` option to limit the effect to the rate-limit as two new queries are necessary for the new fields.
=> [inputs.github] Add query of pull-request statistics

plugins/inputs/aerospike/aerospike.go, plugins/inputs/aerospike/aerospike_test.go
converted to integer if all digits
=> fix edge case in aerospike plugin where an expected hex string was

plugins/inputs/kube_inventory/README.md, plugins/inputs/kube_inventory/pod.go, plugins/inputs/kube_inventory/pod_test.go
Also added Pod Phase and Pod Reason fields
Should also fix #8347
=> Fixing issue with missing metrics when pod has only pending containers

plugins/parsers/graphite/README.md, plugins/parsers/graphite/parser.go, plugins/parsers/graphite/parser_test.go
=> Graphite tags parser

plugins/inputs/socket_listener/socket_listener.go
Socket_listener cause Telegraf crash when receiving invalid data if `NewStreamContentDecoder` returning error. `decoder` is nil at that time that cause `scnr.Scan` to dereference null pointer.
```
E! [inputs.socket_listener] Read error: %vunexpected EOF
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5951da]
goroutine 25 [running]:
bufio.(*Scanner).Scan(0xc000669ec0, 0xbfed4a168ea3030f)
/usr/local/go/src/bufio/scan.go:214 +0x7a
[global_tags]
github.com/influxdata/telegraf/plugins/inputs/socket_listener.(*streamSocketListener).read(0xc0005c4800, 0x33d9d80, 0xc000010008)
/go/src/github.com/influxdata/telegraf/plugins/inputs/socket_listener/socket_listener.go:124 +0x1ae …
```
=> fix crash when socket_listener receiving invalid data

plugins/inputs/win_services/README.md, plugins/inputs/win_services/win_services.go, plugins/inputs/win_services/win_services_integration_test.go, plugins/inputs/win_services/win_services_test.go
This pull request addresses the issue  #3673
Updated the "Windows Services" plugin to allow glob patterns in the input config for including services.
I based the changes on the Docker plugin which also allows glob pattern matching.
Tested the changes locally and uploaded some information:
```
[[inputs.win_services]]
service_names = [
"Win*",
]
```
=> Added Glob pattern matching for "Windows Services" plugin

plugins/inputs/mqtt_consumer/mqtt_consumer.go, plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
closes https://github.com/influxdata/telegraf/issues/7581
=> fix issue with mqtt concurrent map write

plugins/inputs/ping/ping.go
potentially resolves https://github.com/influxdata/telegraf/issues/8501
=> fix potential issue with race condition

plugins/inputs/suricata/suricata_test.go, testutil/accumulator.go
Changed the acc to wait for 2 as its receiving an empty metric and appears to be counting that empty metric against the wait count
=> Fixed race condition on TestThreadStats

plugins/processors/enum/README.md, plugins/processors/enum/enum.go, plugins/processors/enum/enum_test.go
Resolve #7184 by allowing globs (wildcards) in config for tags/fields in enum processor.
With the CPU input plugin loaded and the enum processor configured as below, the output will have the associated mapped number included under the destination tag "glob_test".
```
[[processors.enum]]
[[processors.enum.mapping]]
tag = "*"
dest = "glob_test"
[processors.enum.mapping.value_mappings]
cpu2 = 2
cpu3 = 3
```
=> Allow globs (wildcards) in config for tags/fields in enum processor

plugins/outputs/influxdb/http.go
This is in attempts to track down where the `EOF` error is coming from when sending to an `influxdb_listener` configured telegraf via `outputs.influxdb`
=> Add more verbose errors to influxdb output

plugins/inputs/elasticsearch/README.md, plugins/inputs/elasticsearch/elasticsearch.go, plugins/inputs/elasticsearch/elasticsearch_test.go, plugins/inputs/elasticsearch/testdata_test.go
Add configurable number of 'most recent' date-stamped indices to gather in the Elasticsearch input plugin, and allow wildcards to account for date-suffixed index names. Configuring '3' for num_most_recent_indices will only gather the 3 latest indices, based on the date or number they end with. Finding the date or number is dependent on the targeted indices being configured with wildcards at the end of their 'base' names.
closes #8517
=> Add configurable number of 'most recent' date-stamped indices to gather in Elasticsearch input

plugins/inputs/ipmi_sensor/README.md, plugins/inputs/ipmi_sensor/connection.go, plugins/inputs/ipmi_sensor/connection_test.go, plugins/inputs/ipmi_sensor/ipmi.go, plugins/inputs/ipmi_sensor/ipmi_test.go
=> Add hex_key parameter for IPMI input plugin connection

plugins/inputs/http_listener_v2/http_listener_v2.go, plugins/inputs/http_listener_v2/http_listener_v2_test.go
In cases where the http_listener_v2 plugin config is invalid, when the agent attempts to cleanup by stopping all the inputs, the Stop method here panics as it tries to call listener.Stop() when no listener has been set. This also masks the error message returned from the Start method.
```
> telegraf --test
2020-10-27T12:21:45Z I! Starting Telegraf 1.16.0
2020-10-27T12:21:45Z I! Using config file: /etc/telegraf/telegraf.conf
...
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1245130]
goroutine 45 [running]:
github.com/influxdata/telegraf/plugins/inputs/http_listener_v2.(*HTTPListenerV2).Stop(0xc00043e000)
/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener_v2/http_listener_v2.go:178 …
```
=> [http_listener_v2] Stop() succeeds even if fails to start

plugins/inputs/snmp_trap/snmp_trap.go
add OID value and source information into the error log and make it easier for troubleshooting
before:
```
2020-11-24T06:04:55Z E! [inputs.snmp_trap] Error resolving OID: exit status 2
```
after:
```
2020-11-24T06:04:55Z E! [inputs.snmp_trap] Error resolving OID, oid=.1.3.6.1.4.1.9.9.41, source=10.1.1.2.: exit status 2
```
#8535
=> improve the error log message for snmp trap

plugins/inputs/jenkins/README.md, plugins/inputs/jenkins/jenkins.go, plugins/inputs/jenkins/jenkins_test.go
=> Add support for an inclusive job list in Jenkins plugin

internal/snmp/wrapper.go, plugins/inputs/snmp/README.md, plugins/inputs/snmp/snmp_test.go
Closes #8530: Extended the internal snmp wrapper to support AES192, AES192C, AES256, and AES256C.  Updated the example configuration with the new privProtocols.  Added the warning that those protocols are only supported if you have the appropriate tooling on your system.  Added test to ensure all 4 new privProtocols could be selected and properly encrypt the priv password.
=> Extended SNMPv3 Polling privProtocol Support

docs/TLS.md, plugins/common/tls/config.go, plugins/common/tls/config_test.go, plugins/inputs/http_response/README.md, plugins/inputs/http_response/http_response.go, plugins/inputs/http_response/http_response_test.go, plugins/inputs/x509_cert/README.md, plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
This PR adds a new configration field `sni_server_name` that allows specifying the server name that'll be sent in the ClientHello when telegraf makes an HTTP request to TLS servers. This allows checking against load balancers responding to specific hostnames that otherwise wouldn't resolve to their addresses, or other more complex TLS configurations.
Fixes #7598.
=> common/tls: Allow specifying SNI hostnames

docs/CONFIGURATION.md
[Per the v2 output readme](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb_v2/README.md) and trial/error the fields aren't arrays, and "org" is actually "organization".
=> update influxdb_v2 config documentation in main

plugins/outputs/http/README.md, plugins/outputs/http/http.go
This PR resolves the issue when Telegraf stays in front of Load Balancer.
Some servers has hardcoded IdleTimeut which is higher then 15 seconds (default Telegrafs keep-alive timeout). In this case Telegraf creates keep-alive connection and it is never closed because of reuse.
As a result, balancing does not work.
=> outputs/http: add option to control idle connection timeout

EXTERNAL_PLUGINS.md
- add Open Hardware Monitor as external plugin
- alphabetize plugins
Closes #4596
=> add Open Hardware Monitor as external plugin

plugins/inputs/kibana/README.md, plugins/inputs/kibana/test_environment/basic_kibana_telegraf.conf, plugins/inputs/kibana/test_environment/docker-compose.yml, plugins/inputs/kibana/test_environment/run_test_env.sh
To help diagnose the issue #7588, this pull request adds a test environment for the Kibana input plugin. Created a docker-compose.yml file that defines the basic components needed to use the plugin. I was able to get the expected output and wasn't able to recreate the reported issue.
The verification steps are manual, having to read the logs and attach to the container to inspect the Telegraf output file. In future pull requests, integration tests should be made to automate this. Hopefully this change will set the foundation for such tests.
=> Provide test environment for kibana input plugin

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum, internal/snmp/wrapper.go, plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go
No need to update README.md or unit tests, since functionality has not been changed.
The update of gosnmp library to version 1.28.0 for usage in input snmp plugin should fix the issue described in #3788.
Closes #3788
=> Input SNMP plugin - upgrade gosnmp library to version 1.29.0

metric/series_grouper.go, metric/series_grouper_test.go, plugins/aggregators/merge/merge.go, plugins/aggregators/merge/merge_test.go
This introduces some optimizations for use with the aggregators.merge plugin. In my current usage of telegraf, it's heavily bottle-necking on this plugin.
----
The previous implementation of `SeriesGrouper` required breaking a metric object apart into its constituents, converting tags and keys into unoptimized maps, only to have it put them back together into another metric object. This resulted in a significant performance overhead. This overhead was further compounded when the number of fields was large.
This change adds a new `AddMetric` method to `SeriesGrouper` which preserves the metric object and removes the back-and-forth conversion.
Additionlly the method used for calculating the metric's hash was switched to use `maphash`, which is optimized for this case.
----
Benchmarks …
=> Optimize SeriesGrouper & aggregators.merge

.lgtm.yml
This configuration file didn't disable the Python analysis like it was intended to. Removing and disabled automated lgtm code reviews.
=> Removing .lgtm.yml

config/config.go, plugins/parsers/csv/README.md, plugins/parsers/csv/parser.go, plugins/parsers/csv/parser_test.go, plugins/parsers/registry.go
Closes #6436 
Adds the ability to define an array of string skip values to the csv parser, such as an empty string, where the value matches the provided skip value it will skip the field entirely. Addresses the issue of ignoring missing values
=> Added ability to define skip values in csv parser

plugins/inputs/postgresql_extensible/README.md, plugins/inputs/postgresql_extensible/postgresql_extensible.go, plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
=> Add timestamp column support to postgresql_extensible

plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/procstat_test.go
=> Procstat input plugin should use the same timestamp in all metrics in the same Gather() cycle.

plugins/inputs/webhooks/particle/particle_webhooks.go, plugins/inputs/webhooks/particle/particle_webhooks_test.go
=> Use the 'measurement' json field from the particle webhook event as the measurement name, or if it's blank, use the 'name' field of the event's json.

.github/PULL_REQUEST_TEMPLATE.md
Removed the CLA checkbox now that the telegraf-tiger bot enforces the signing of the CLA.
=> Update template, remove CLA checkbox

plugins/inputs/gnmi/gnmi.go, plugins/inputs/gnmi/gnmi_test.go
=> GNMI plugin should not take off the first character of field keys when no 'alias path' exists.

cmd/telegraf/telegraf_windows.go, logger/event_logger.go, logger/event_logger_test.go, logger/logger.go
This should add support to be able to configure the following in telegraf.conf:
`logtarget = "eventlog"`
Currently it only works when running telegraf as an already-installed windows service. This should enable it to work always, as long as it's configured and running on a windows machine.
resolves #7487
=> Add Event Log support for Windows

plugins/inputs/ipmi_sensor/README.md, plugins/inputs/ipmi_sensor/ipmi.go
I had the issue that ipmi data was reported with gaps on a 30s interval on HP G10 servers (latest firmware).
The gaps where due to the ipmitool command was not always finishing within the 20s timeout. Even changeing the timeout to 30s was not always giving it enough time to respond.
ipmi-sensors from freeipmi tools which is used in some prometheus ipmi exporters is running way faster but does not provide all information I needed.
At some point I just realized there is a cache option for ipmitool. Using this option speeds the tool up by something between 3x and 6x for most of my runs so it holds the deadline given by timeout and I can record the data not even in 30s intervals but also now in 15s intervals.
In case you merge this or agree with it, I would appreciate a hacktoberfest-accepted …
=> Add setting to enable caching in ipmitool

plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
I encountered a timeout issue when using x509 cert input plugin.
This timeout issue can be reproduced by the test case in commit 9fd1066 or this configuration
```
[[inputs.x509_cert]]
sources = ["https://www.influxdata.com:443"]
timeout = "15s"
```
I fixed this issue by removing redundant code and test cases are added.
=> fix x509 cert timeout issue

plugins/inputs/lustre2/lustre2.go, plugins/inputs/lustre2/lustre2_test.go
are not separated by whitespace, which happens when numbers grow large (#7966)
=> Fix crash in lustre2 input plugin, when field name and value

plugins/inputs/zookeeper/zookeeper.go
Found zookeeper input plugin error as below:
> [inputs.zookeeper] Error in plugin: unexpected line in mntr response: "zk_avg_pull-daily-attendence-data-testByQA_read_per_namespace\t137.1803"
This PR is to improve mntr regex to match user specific keys.
=> improve mntr regex to match user specific keys.

plugins/outputs/elasticsearch/elasticsearch.go
resolves https://github.com/influxdata/telegraf/issues/7393
=> Fix issue with elasticsearch output being really noisy about some errors

docs/TEMPLATE_PATTERN.md
If you supply a template without measurement included it returns an error asking you to specify measurement. This was not currently mentioned in the templating docs.
=> Add line to template docs about measurement

plugins/outputs/influxdb_v2/http.go, plugins/outputs/influxdb_v2/http_internal_test.go
- change max wait on error to 30s
- handle more http response codes, both for future-proofing and for playing nice with gateways and proxies
- 4xx response codes now result in metrics being dropped, because server will never accept them. This prevents infinite delivery of failing metrics, blocking transmission at head of line.
- add exponential backoff as well as respecting retry-after header. Pick whichever is more up to 30s max
- include the server response code in the logs, as well as clarify if the metric was dropped.
resolves https://github.com/influxdata/telegraf/issues/8571
=> [outputs.influxdb_v2] add exponential backoff, and respect client error responses

plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
fixes #8766 
This pull request addresses the issue @NZSmartie found and reported in #8704. There was a regression due to the pr #8679 which removed a required function which led to a instant panic when using the "exec" method for inputs.ping. I added an integration unit test to cover for this case in the future that ensures `init()` is correct.
=> inputs.ping regression: Add back required "hostPinger" function for "exec" method

plugins/inputs/ping/ping.go
Fixes #6642 and Fixes #8767
This pull request adds support to set the interface in native mode using either the name or IP address. Originally only the IP address was supported. Readme is already up-to-date because it stated this was supported, but as identified in #6642 it was not.
The pull request #8679 did cause a regression relating to this were the interface could no longer be set by IP address, this is now fixed as well.
=> inputs.ping: Allow interface to be configured with both name and IP address in native mode

plugins/processors/starlark/README.md, plugins/processors/starlark/field_dict.go, plugins/processors/starlark/starlark.go, plugins/processors/starlark/starlark_test.go
Fix for #8768
We would like to be able to reuse Starlark scripts by providing somehow input parameters
* Adds a map `constants` to the configuration
* Injects the content of the constants into the `builtins` of the program
=> Allow to provide constants to a starlark script

go.mod, go.sum
~~DON'T MERGE, for testing only to create temporary artifacts to give community a chance to test changes.~~
Fix #8704
A [pull request](https://github.com/go-ping/ping/pull/130) by @ssoroka has been merged go-ping that should resolve concurrency issues with inputs.ping plugin.
=> Update go-ping to latest version

Makefile
Initial build took several minutes on my machine, and it looked like it
was hanging until I added the -x flag.
=> Increase build verbosity with go mod download -x

plugins/inputs/ping/README.md
Fix: #8778
Update README to clarify the sysctl command you need to run to enable using native ping on Linux.
=> Update README for inputs.ping with correct cmd for native ping on Linux

plugins/inputs/ping/ping.go, plugins/inputs/ping/ping_test.go
#8805
- Sort the RTTS slice before calculating the percentile, updated a unit test to verify this
- Changed inputs.ping "Deadline" config to be assigned to go-pings "Timeout"
go-ping doesn't support "timeout to wait for ping response (-W)" yet, but there is an open issue https://github.com/go-ping/ping/issues/63
=> Fix percentile calculations and assign Deadline correctly

config/config.go
=> Flush jitter output missing &

internal/snmp/wrapper.go, plugins/inputs/snmp/README.md, plugins/inputs/snmp/snmp.go
Hi, 
This PR fixes https://github.com/influxdata/telegraf/issues/7879.
I modified the Gosnmpwrapper to expose tcp{4,6} and udp{4,6} as connection-scheme and pass them to Gosnmp. 
This way, one can indirectly specify the address-family to be used for snmp-requests. 
I updated the according README-files. 
In my small test-setup everything is working as intended. 
However, I did not find a unit-test for the snmp input-plugin or the wrapper to alter, so I assume this small 4 line change can (hopefully) be reviewed by hand. 
This is my first PR on a go-project ever, so please be gentle! :)
Have a nice day.
=> Expose v4/v6-only connection-schemes through GosnmpWrapper

.circleci/config.yml, plugins/outputs/influxdb/http.go, plugins/outputs/influxdb/http_test.go
=> Validate the response from InfluxDB after writing/creating a database to avoid json parsing panics/errors

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum, plugins/inputs/mqtt_consumer/mqtt_consumer.go, plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
Closes #8722, #7648 
When there is a network interruption or anything to cause a connection failure the input would not recover without restarting Telegraf. 
Eg the following:
`E.g connection lost EOF or connection lost pingresp not received`
Would cause it to repeat loop on the messages below and not resume gathering metrics without a restart.
```
Previous collection has not completed; scheduled collection  
Collection took longer than expected; not complete after interval of 10s 
```
Upgraded to[ eclipse/paho.mqtt.golang v1.3.0](https://github.com/eclipse/paho.mqtt.golang/releases/tag/v1.3.0) which includes fixes for reconnection errors.
Moved the make of m.messages into the Init function so it is only called once rather than on every reconnect, so in the event of a reconnection error …
=> Fix reconnection issues mqtt

config/config.go, config/config_test.go
Closes #7338
Related #7349, #7662 
This is a temporary fix which we intend to improve on:
- Retries three times at 10s intervals when receiving an error on loading config from a url incase of the endpoint being down.
- Log attempts and the specific failure response codes.
- Does not use env variables or add new flags 
- Tests added to demonstrate that on the final failure it will return the error.
=> Add default retry for load config via url

plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
closes #8809
If timeout is not configured, it will be set to "5ns" when adding to inputs. This cause the timeout issue #8809. Test case for reproducing is added in commit ac4cda1.
I fix the issue by setting timeout to "0s".
=> inputs.x509_cert: Fix timeout issue 

plugins/outputs/warp10/warp10.go, plugins/outputs/warp10/warp10_test.go
Hello,
The warp10 specification requires the commas in tag values to be URL encoded as `%2C`. This PR fixes this behavior. 
I'm not very familiar with Golang, let me know if there is anything I should do better.
EDIT: Without this, Warp10 will reject the input and reply a parse error. This is the case with the current Elasticsearch input plugin for example.
=> outputs/warp10: url encode comma in tags value

etc/telegraf.conf, plugins/inputs/statsd/README.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
Thanks for the awesome work you folks do :)
This PR is my attempt to add support for the [distributions](https://docs.datadoghq.com/developers/metrics/types/?tab=distribution) metric (alternate [link](https://docs.datadoghq.com/metrics/distributions/)) to maintain compatibility with Datadog metrics. This would allow us to aggregate metrics on the server rather than on the agent (i.e. aggregate on Influx rather than on Telegraf).
I've added unit tests and tested this on my local Influx and Telegraf setup. Let me know of all the changes required 👍 
Closes #8134
=> Add support for datadog distributions metric

plugins/inputs/filestat/filestat.go, plugins/inputs/filestat/filestat_test.go
This PR attempts to fix #7315, the same problem as #6940, but without adding a config flag.
Previously, the filestat plugin would check for a file's existence, and then try to compute all sorts of things for the missing file, which failed and resulted in a log message about possible permission errors.
Now, the plugin just skips the file if it exists. If an error is encountered probing an existing file, the plugin now logs that error, too, instead of hazarding a guess at permission problems.
=> plugins/filestat: Skip missing files

plugins/processors/ifname/ifname.go
=> Fix mutex locking around ifname cache

internal/snmp/wrapper.go, plugins/inputs/snmp/README.md, plugins/inputs/snmp/snmp.go
=> Support more snmpv3 authentication protocols

plugins/inputs/modbus/modbus.go, plugins/inputs/modbus/modbus_test.go
- Fix https://github.com/influxdata/telegraf/issues/7227
if you try to read multiple consecutive addresses , modbus return error "quantity 346 must be between 1 and 125".
this happens because we have a limitation with the number of registers that we can retrieve, 125 for holding registers and Input registers and 2000 for discrete inputs and coils
=> fix: reading multiple holding registers in modbus input plugin

config/config.go
=> Display error message on badly formatted config string array (eg. namepass)

plugins/inputs/docker/docker.go
I have noticed that the docker input plugin occasionally gathers metrics for containers with a container name that does not match the configured filter. For example, I have a container named `influxdb` and have configured the docker input plugin with `container_name_include = ["influxdb"]`, but the docker input plugin sometimes produces metrics with a `container_name` tag of something like `689a5b5f3679_influxdb`.
Upon further investigation, I discovered that this happens when the metrics are gathered while docker-compose is recreating the container. When docker-compose recreates the container, it temporarily renames the original container to `{id}_{name}` before removing it.
- https://github.com/docker/compose/blob/b9249168bd280429820e2ae72c0b86006ccfc19d/compose/service.py#L610
- …
=> Use consistent container name in docker input plugin

plugins/processors/starlark/testdata/schema_sizing.star
=> Add Starlark script for outputting Line Protocol shape...for sizing

plugins/inputs/procstat/process.go, plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/procstat_test.go
=> Add PPID field to procstat input plugin

plugins/outputs/kinesis/kinesis.go, plugins/outputs/kinesis/kinesis_test.go
```
2021-03-02T21:29:01Z D! [outputs.kinesis] Wrote a 131 point batch to Kinesis in 387.624941ms.
2021-03-02T21:29:01Z D! [outputs.kinesis] Wrote batch of 131 metrics in 389.182445ms
2021-03-02T21:29:01Z D! [outputs.kinesis] Buffer fullness: 14 / 1000 metrics
```
=> Switching kinesis output plugin to use telegraf.Logger

plugins/inputs/docker/README.md, plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go, testutil/accumulator.go, testutil/testutil.go
Signed-off-by: Andres Alvarez <1671935+kir4h@users.noreply.github.com>
This PR resolves #6609 by making the `perdevice` setting for docker input plugin affect also the `cpu` resource
=> [plugins/input/docker] Make perdevice affect also cpu and add class granularity through perdevice_include/total_include 

plugins/inputs/tail/tail_test.go
'poll' mode works and is consistent, as opposed to the default fsnotify mode.
=> Get Tail tests to pass on windows

plugins/processors/starlark/README.md
Closes #8907 .  After #8447  , this common question in the Starlark Processor README.md should be updated to reflect the newly available shared state.
=> Correct Q+A about state

plugins/inputs/kube_inventory/README.md
Telegraf daemonset pod cannot contact kube-apiserver via localhost.
Should be `$HOSTIP`, and the default port is 6443.
=> kubernetes_inventory: Set $HOSTIP in default URL

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, plugins/inputs/prometheus/README.md, plugins/inputs/prometheus/kubernetes.go, plugins/inputs/prometheus/kubernetes_test.go, plugins/inputs/prometheus/prometheus.go, plugins/inputs/prometheus/prometheus_test.go
PR for the issue https://github.com/influxdata/telegraf/issues/8705.
If monitor_kubernetes_pods = true and the new monitor_kubernetes_pods_version = 2 is specified, the pod list is queried locally on the node every 60s instead of using the watch api. This allows for scalability for large clusters so the pods to scrape are distributed among the nodes, which requires telegraf to be run as a daemonset. The same annotations to choose which pods to scrape are used and the optional filtering by namespace and selectors is also the same, with this filtering done afterwards. The feature is backwards compatible and is used if and only if monitor_kubernetes_pods_version = 2 is specified in the config.
=> Prometheus [Input] plugin - Optimizing for bigger kubernetes clusters (500+ pods) when scraping thru 'monitor_kubernetes_pods'

plugins/common/kafka/config.go
Currently if idempotent_writes is set to true telegraf crashes
Idempotent_writes requires max open requests to be set to 1 (defaults to 5)
Change config to set max open requests to 1 under the hood when idempotent_writes is turned on
=> Fix max open requests to one if idempotent writes is set to true

plugins/processors/starlark/testdata/json_nested.star
=> Add Starlark parsing example of nested JSON

README.md, etc/telegraf.conf, plugins/outputs/sensu/README.md, plugins/outputs/sensu/sensu.go
Per request from @sjwang90, fix the plugin name for sensu to match the directory name.
=> Fix output name to match directory name for sensu output plugin

scripts/release.sh
This is needed because the new notarized Mac artifact is in DMG format.
=> Include DMG files when syncing release artifacts to AWS

.circleci/config.yml, .github/workflows/golangci-lint.yml
Golangci-lint project provides a github action: https://github.com/golangci/golangci-lint-action
This pr adds a config to enable the github action (replacing circle-ci), this should be faster with caching enabled and not having to download the golangci-lint binary each time.
=> Move golangci-lint from circle-ci to github actions

config/config.go, plugins/inputs/exec/exec_test.go, plugins/inputs/kafka_consumer/kafka_consumer_test.go, plugins/parsers/registry.go, plugins/parsers/value/parser.go, plugins/parsers/value/parser_test.go
=> Add value_field_name config option to customize field name when using Value parser.

.circleci/config.yml
Update cache version to avoid using old version and causing failure.
similar update: https://github.com/influxdata/telegraf/pull/8516
=> Update mac cache version number in circle-ci to avoid conflicts

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile
- Most valuable (TBD?) linters for `golangci-lint` enabled, for `revive` linter almost all rules enabled. Both linters and rules should reviewed to get list of what should stay enabled.
- `golangci-lint` bumped from `v1.37.0` to `v1.38.0`
- settings from `Makefile` moved to config file
=> Proposal of enabled linters and their settings.

plugins/outputs/nats/nats.go
The nats_output plugin never used the configured credentials file and therefore could not connect to an account-based nats system.
I modified the plugin based on the consumer plugin (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nats_consumer/nats_consumer.go)
=> nats_output: use the configured credentials file

agent/agent.go, cmd/telegraf/telegraf.go
closes #8726, closes #8185
As we know, telegraf will reload when getting a SIGHUP signal. If we go deeper into the reload loop, we can see "runAgent" is called without closing running outputs.
This will cause some issues like reload failure and connection leaking.
- Reload failure
1. Add prometheus configuration
```
[[outputs.prometheus_client]]
listen = ":9273"
path = "/metrics"
metric_version = 2
```
2. Send a SIGHUP to the process
3. We will get the "address already in use" error:
```
2021-01-28T08:47:59Z I! Starting Telegraf 
2021-01-28T08:47:59Z I! Loaded inputs: x509_cert
2021-01-28T08:47:59Z I! Loaded aggregators: 
2021-01-28T08:47:59Z I! Loaded processors: 
2021-01-28T08:47:59Z I! Loaded outputs: prometheus_client
2021-01-28T08:47:59Z I! Tags enabled: host=Zachary-MBP.local …
```
=> Close running outputs when reloading

docs/FAQ.md, plugins/inputs/dcos/README.md, plugins/inputs/kube_inventory/README.md, plugins/inputs/kubernetes/README.md, plugins/inputs/passenger/README.md, plugins/inputs/sflow/README.md
The `max-series-per-database` and `max-values-per-tag` settings are/were only used by the `inmem` index option in InfluxDB. `inmem` is going away for good in v2.0.4 (releasing late this week / early next), so the recommendations to tweak those settings aren't relevant any more.
=> chore: remove references to outdated InfluxDB settings.

plugins/inputs/teamspeak/README.md, plugins/inputs/teamspeak/teamspeak.go, plugins/inputs/teamspeak/teamspeak_test.go
Add additional field `query_clients_online` to the teamspeak input plugin.
This field is useful because the `clients_online` field already included in the plugin is a total of both end-users and server query users connected to a virtual server, so having this allows you to break down the total clients by type.
=> Teamspeak input plugin query clients

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/mongodb.go, plugins/inputs/mongodb/mongodb_data.go, plugins/inputs/mongodb/mongodb_data_test.go, plugins/inputs/mongodb/mongodb_server.go, plugins/inputs/mongodb/mongodb_server_test.go, plugins/inputs/mongodb/mongostat.go
Added information (insert, update, queries, remove etc...) about each collection in replica set.
More information in [documentation](https://docs.mongodb.com/manual/reference/command/top/)
=> Add top stat info to mongodb plugin

plugins/inputs/sflow/types.go, plugins/inputs/sflow/types_test.go
prior to calling getFields() or getTags() on them.
If a protocol header is not available, an empty map is returned.
updates: #7937
Signed-off-by: Felix Moessbauer <felix.moessbauer@siemens.com>
=> fix segfaults in sflow plugin by checking if protocol headers are set

plugins/processors/starlark/README.md, plugins/processors/starlark/testdata/iops.star
For https://github.com/influxdata/telegraf/issues/8903
Add a starlark example showing how to obtain IOPS (to aggregate, to produce max_iops).
Where the max_iops is the peak IO per second rate seen over a period (and not a maximum of means of IO "per second").
=> Add a starlark example showing how to obtain IOPS 

plugins/outputs/azure_monitor/README.md
Azure Monitor Custom Metrics is supported in All Public Cloud Regions. ref https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-custom-overview#supported-regions
I think that should update README.
Update Azure Monitor README.
I deleted "The following regions are currently known to be supported", because of already supported All Public Regions.
=> Update supported regions in azure monitor

.github/PULL_REQUEST_TEMPLATE.md
Update the PR template to encourage contributors to link the PR to the issues it resolves.  Also ask contributors to use github issues to describe why the change is needed and then summarize how the issues were resolved in the PR description.
=> Update PR template to encourage linking to issues

plugins/inputs/docker/docker.go
Fix for #8692 
Check for length of perusage array and removed unused function from code
=> Check for length of perusage array and removed unused function from code

plugins/inputs/x509_cert/README.md, plugins/inputs/x509_cert/x509_cert.go
=> Wildcard support for x509_cert files

plugins/inputs/sqlserver/sqlqueriesV2.go, plugins/inputs/sqlserver/sqlserverqueries.go
fixes #8548  
cc / @denzilribeiro @Trovalo
=> SQLServer - Fixes sqlserver_process_cpu calculation

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum, plugins/inputs/kube_inventory/kube_state.go, plugins/inputs/prometheus/kubernetes.go, plugins/inputs/prometheus/kubernetes_test.go, plugins/inputs/prometheus/prometheus.go, plugins/inputs/prometheus/prometheus_test.go
Closes #9021 
Fixing this import path to match the one used everywhere else removes the "duplicate proto" message.
Also updated protobuf library to the latest change, this didn't fix the issue but seemed like a good change to keep.
=> Replace github.com/kubernetes import with k8s.io and update protobuf to v1.5.1

plugins/processors/starlark/README.md, plugins/processors/starlark/starlark.go, plugins/processors/starlark/testdata/math.star
resolves #8985 
The math module has been added recently to the upstream project `starlark-go`, we would like to make the Starlark processor support it too
* Adds the math module in the list of external modules to load
* Adds a simple example showing how to use it
* Update the `README.md` to refer the new example
We can use math functions in the Starlark scripts executed by the Starlark Processor.
=> Add the math module to the Starlark Processor

plugins/outputs/azure_monitor/azure_monitor.go
If this error isn't handled, it seems as though the 'auth' object can end up being nil and ultimately causing a panic. 
(Hopefully) resolves #9044
=> Handle error when initializing the auth object in Azure Monitor output plugin

plugins/outputs/kafka/kafka.go
This is a fix for if Kafka doesn't connect it wont stop telegraf from starting up
=> Moved samara config out of init into connect

plugins/outputs/all/all.go, plugins/outputs/cloudwatch_logs/README.md, plugins/outputs/cloudwatch_logs/cloudwatch_logs.go, plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
The primary motivation is to fix messy log storing when using native AWS tools to deliver logs from docker containers (for example) running on EC2 (with or without kuberentes). This plugin allows to sort out logs by log streams that can be parsed from metric tag. Log streams is created automatically.
=> AWS Cloudwatch log output

plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
resolves #9054
Fixed Yandex.Cloud compute metadata url
Added debug message body logging
=> use correct compute metadata url to get folder-id

plugins/processors/ifname/ifname.go
resolves #8801
Changed the `makeTable` function to only have the required field to walk.
Improvement of `time telegraf --test` when having only a single snmp agent was from:
```
real    1m12.939s
user    0m2.196s
sys     0m0.612s
```
To 
```
real    0m1.526s
user    0m0.394s
sys     0m0.130s
```
=> Improve processor.ifname startup performance

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go
resolve #8919
As pointed out by the users in the above issue, the inputs.ping implementation was incomplete. The documentation made it seem you needed to set CAP_NET_RAW and set sysctl, while the CAP_NET_RAW solution wouldn't work without the call to SetPrivileged(true). As well when using FreeBSD you either need root or set CAP_NET_RAW in order to send ICMP packets, therefore requiring SetPrivileged(true). 
When [SetPrivileged(true)](https://github.com/go-ping/ping/blob/42a6788a51373f490c628ee52c81ef54cbe02c6c/ping.go#L313-L323) is not set the library go-ping will attempt to send a [UDP ping](https://nmap.org/book/man-host-discovery.html) which isn't as reliable as a ICMP ping. While a UDP ping doesn't require any permissions it will only work if the endpoint is configured to reply. This …
=> inputs.ping: Always SetPrivileged(true) in native mode

plugins/inputs/nfsclient/nfsclient.go, plugins/inputs/nfsclient/nfsclient_test.go
Close #9028
The values received by [mountstats](https://man7.org/linux/man-pages/man8/mountstats.8.html) were out of the range of int64, this pr updates the type to uint64. I couldn't find any definitive documentation that says this is the right type, but this [Prometheus project](https://pkg.go.dev/github.com/prometheus/procfs#MountStats) that seems to do something similar also uses uint64. I added a unit test to test for the values received by @micoq (thanks!) which were out of int64 range. 
Also removed the call to `log.Fatalf`, having it return the error instead.
=> inputs.nfsclient: use uint64, also update error handling

metric.go, metric/metric.go, metric/metric_test.go, models/running_aggregator.go
The mentioned functions are deprecated, their use was discouraged and they are not used anywhere anymore. According to a comment of @reimda in PR #8183 those functions should be removed.
=> Remove deprecated and unused SetAggregate() and IsAggregate() functions.

plugins/inputs/logstash/logstash.go, plugins/inputs/logstash/logstash_test.go, plugins/inputs/logstash/samples_logstash7.go
This PR is meant to satisfy #7629, the Logstash plugin was unable to parse some stats for 'queue' when querying pipelines, so we'll add those to the model and if the newer ones exist, use those. 
It also seems that 'events' was renamed to 'event_count' so that had to be handled as well.
=> Add support for Logstash 7 'queue' stats from the Pipelines API

plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_util.go, plugins/inputs/webhooks/github/github_webhooks_models.go, plugins/inputs/win_eventlog/util.go
Removing all calls other than in tests. Calls to metric.new have no chance of returning an error, so we can ignore it (it's a mistake that it returns an 'error', and could be refactored soon)
=> Delete log.Fatal calls and replace with error returns.

plugins/inputs/mysql/mysql.go
Add ability to handle 'binary logs' mySQL query with 3 columns, in case 3 columns are sent (MySQL 8 and greater). The third column is called 'encrypted', hence the placeholder variable name.
resolves #9063
=> Add ability to handle 'binary logs' mySQL query with 3 columns, in case 3 columns are sent (MySQL 8 and greater)

config/config.go, plugins/outputs/sumologic/sumologic_test.go, plugins/serializers/carbon2/README.md, plugins/serializers/carbon2/carbon2.go, plugins/serializers/carbon2/carbon2_test.go, plugins/serializers/registry.go
Sanitize metric name: replace problematic characters with `:`.
Fixes: https://github.com/influxdata/telegraf/issues/8974
Future PRs might introduce configuration of this feature, i.e. the character to replace with.
=> Carbon2 serializer: sanitize metric name

docker-compose.yml, plugins/inputs/opcua/opcua_client_test.go
Related to #8737
Changed remote `opcua.rocks` domain to docker container on `localhost`. The docker image is the same as the original server on opcua.rocks uses: `open62541/open62541`. See https://opcua.rocks/open62541-online-test-server/ for additional info.
=> Fix opcua integration test

etc/telegraf.conf, plugins/inputs/prometheus/README.md, plugins/inputs/prometheus/prometheus.go, plugins/outputs/prometheus_client/README.md, plugins/outputs/prometheus_client/prometheus_client.go
Remove deprecation warning as we currently support both v1 & v2 metrics with no plans to deprecate.
Lessens confusion around the ability to continue with v1 metrics if that is preferred. 
relates to #8617
=> Remove deprecation warning for v1 prom metrics

plugins/common/shim/processor.go, plugins/common/shim/processor_test.go
Whilst creating an external processor plugin, I was utilising the shim to provide the reading from stdin and writing to stdout:
````
// create the shim. This is what will run your plugins.
s := shim.New()
// Check for settings from a config toml file,
err = s.LoadConfig(configFile)
if err != nil {
fmt.Fprintf(os.Stderr, "Err loading input: %s\n", err)
os.Exit(1)
}
// run the plugin until stdin closes or we receive a termination signal
if err := s.Run(shim.PollIntervalDisabled); err != nil {
fmt.Fprintf(os.Stderr, "Err: %s\n", err)
os.Exit(1)
}
````
When running the processor plugin I was seeing that the processor was being terminated and restarted with the error message in telegraf's stderr:
````
write error: Broken pipe
````
However, when I moved the plugin away from using the shim for …
=> change to NewStreamParser to accept larger inputs from scanner

plugins/processors/enum/README.md, plugins/processors/enum/enum.go, plugins/processors/enum/enum_test.go
This adds float64 support to enum processor.
=> Support float64 in enum processor

plugins/inputs/nfsclient/nfsclient.go
resolves #9127 
Fixed an incorrect mapping inside the nfsclient plugin input.
In the `Init` function of the nfsclient plugin, `nfs3Ops` and `nfs4Ops` is prepared in a local map inside but never attached to the underlying `nfsclient` struct.
Passing an empty map to 
```go
if (version == "3" && n.nfs3Ops[first]) || (version == "4" && n.nfs4Ops[first]) {
tags["operation"] = first
if len(nline) <= len(nfsopFields) {
for i, t := range nline {
fields[nfsopFields[i]] = t
}
acc.AddFields("nfs_ops", fields, tags)
}
}
```
Result in `n.nfs3Ops[first]` or `n.nfs4Ops[first]` to be false, and this branch of the code is never reached.
=> Fix: sync nfsclient ops map in nfsclient struct

.circleci/config.yml
Updated circle-ci config to check for certain patterns in the latest commit to see if the jobs should run. Credit to this blog post for the idea: https://dev.to/acro5piano/exit-circleci-jobs-if-changed-files-do-not-match-specific-pattern-mel
=> Only run CI for certain file changes

cmd/telegraf/telegraf.go, config/config.go, docs/CONFIGURATION.md, etc/telegraf.conf, etc/telegraf_windows.conf, logger/logger.go, logger/logger_test.go
This hopefully resolves #3462.
You'd be able to enable `log_with_local_time` so that all logs will use the time of the machine it's being ran on. This will apply for all types of logs (stdout, file).
=> Config Option to Enable Logging with Local Time

plugins/processors/starlark/starlark.go, plugins/processors/starlark/starlark_test.go, plugins/processors/starlark/testdata/compare_metrics.star, plugins/processors/starlark/testdata/iops.star, plugins/processors/starlark/testdata/json_nested.star, plugins/processors/starlark/testdata/multiple_metrics.star, plugins/processors/starlark/testdata/multiple_metrics_with_json.star, plugins/processors/starlark/testdata/pivot.star, plugins/processors/starlark/testdata/rename_prometheus_remote_write.star, plugins/processors/starlark/testdata/schema_sizing.star, plugins/processors/starlark/testdata/time_set_timestamp.star, plugins/processors/starlark/testdata/value_filter.star
This adds the ability to mock the time.now() function in starlark and thus be able to create an example in which time.now() is used to set on metrics.
=> Add time.now() starlark processor example test

plugins/parsers/json/parser.go, plugins/parsers/json/parser_test.go
Telegraf expects either an object or an array of objects but nulls are valid JSON values. This commit detects if query returns a null or the document is a null to return an empty metric instead of an error.
For example, with this configuration:
test.json:
```json
{"error":null,"result":{"data":null,"items_per_page":10,"total_items":0,"total_pages":0}}
```
test.conf:
```
[[inputs.file]]
files = ["test.json"]
data_format = "json"
json_query = "result.data"
```
The query returns `null`:
```
$ cat test.json | jq ".result.data"
null
```
Latest version returns an error:
```
$ docker run -it -v $(pwd):/mnt/ -w "/mnt" --rm -e telegraf:latest telegraf -test -debug -config test.conf
2021-04-09T09:31:08Z I! Starting Telegraf 1.18.1
2021-04-09T09:31:08Z D! [agent] Initializing plugins …
```
=> Make JSON format compatible with nulls

.circleci/config.yml, Makefile
resolves #9098
Before this change, a full check suite on a PR took about 30-33 minutes. After this change, I've seen consistent results around 19 minutes. Note that the `make package` command will no longer work for generating all packages, each OS type has to be specified in an argument (such as `windows=1 make package`). This will also require an update to telegraf tiger which will be a separate PR.
=> Speed up package step by running in parallel.

plugins/processors/starlark/README.md
The library `math.star` and `time.star` were not described in the readme of the Starlark processor
=> Add time.star and math.star info to the Starlark readme lib section

CONTRIBUTING.md, docs/developers/CODE_STYLE, docs/developers/CODE_STYLE.md, docs/developers/DEPRECATION.md, docs/developers/LOGGING.md, docs/developers/METRIC_FORMAT_CHANGES.md, docs/developers/PACKAGING.md, docs/developers/PROFILING.md, docs/developers/REVIEWS.md, docs/developers/SAMPLE_CONFIG.md, docs/maintainers/CHANGELOG.md, docs/maintainers/LABELS.md, docs/maintainers/PULL_REQUESTS.md, docs/maintainers/RELEASES.md
resolves #9119
- moved wiki developer, maintainer information to `docs` folder
- linked docs folder to CONTRIBUTING.md
=> Move wiki information to docs

plugins/common/http/config.go, plugins/common/oauth/config.go, plugins/common/oauth2/config.go, plugins/inputs/http/README.md, plugins/inputs/http/http.go, plugins/inputs/http/http_test.go, plugins/outputs/http/http.go, plugins/outputs/http/http_test.go
This should add support for oauth2 authentication ability for the http input client. Be advised that this is mostly directly taken from the HTTP output plugin. Should resolve #5309
=> Add OAuth2 to HTTP input

plugins/inputs/aerospike/README.md, plugins/inputs/aerospike/aerospike.go, plugins/inputs/aerospike/aerospike_test.go, plugins/inputs/aliyuncms/aliyuncms.go, plugins/inputs/aliyuncms/aliyuncms_test.go, plugins/inputs/aliyuncms/discovery.go, plugins/inputs/amqp_consumer/README.md, plugins/inputs/amqp_consumer/amqp_consumer.go, plugins/inputs/apache/apache.go, plugins/inputs/apcupsd/apcupsd.go, plugins/inputs/apcupsd/apcupsd_test.go, plugins/inputs/beat/README.md, plugins/inputs/beat/beat.go, plugins/inputs/bind/json_stats.go, plugins/inputs/bind/xml_stats_v2.go, plugins/inputs/bind/xml_stats_v3.go, plugins/inputs/burrow/burrow_test.go
```
plugins/inputs/aerospike/aerospike.go:179:12          revive       superfluous-else: if block ends with a continue statement, so drop this else and outdent its block
plugins/inputs/aerospike/aerospike.go:208:13          revive       superfluous-else: if block ends with a continue statement, so drop this else and outdent its block
plugins/inputs/aerospike/aerospike.go:401:1           revive       argument-limit: maximum number of arguments per function exceeded; max 6 but got 7
plugins/inputs/aerospike/aerospike.go:461:1           revive       confusing-results: unnamed results of the same type may be confusing, consider using named results
plugins/inputs/aerospike/aerospike_test.go:129:10     ineffassign  ineffectual assignment to err …
```
=> Linter fixes for plugins/inputs/[ab]*

go.mod, go.sum, plugins/serializers/prometheusremotewrite/prometheusremotewrite.go, plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
relates to #9166
- upgraded to prometheus/common [v0.15.0](https://github.com/prometheus/common/releases/tag/v0.15.0) as it includes an[ update to text parsing](https://github.com/prometheus/common/pull/263) to not allow duplicate labels 
this change will mean we pass the prometheus remote write [repeated labels compliance test](https://github.com/prometheus/compliance/blob/main/remote_write/cases/labels.go#L38) which we are currently failing
- added a check to the prometheus serializer to see if the tags value is "", if it is we drop the tag
this change will mean we mass the prometheus remote write [empty labels compliance test](https://github.com/prometheus/compliance/blob/main/remote_write/cases/labels.go#L65), added a test for the above
=> Remote write compliance updates

.github/dependabot.yml
Ignoring the package `gopkg.in/djherbis/times.v1` because it is causing dependabot to throw the following error:
```
Dependabot wasn't able to update gopkg.in/djherbis/times.v1
The module path gopkg.in/djherbis/times.v1 found in your go.mod doesn't match the actual path github.com/djherbis/times found in the dependency's go.mod.
Updating the module path in your go.mod to github.com/djherbis/times should resolve this issue.
```
=> Resolve dependabot error by ignoring package

.github/dependabot.yml
Updating config to have dependabot ignore soniah/gosnmp dependency for now until the issue #9203 is resolved.
=> Ignore soniah/gosnmp dependency

plugins/inputs/cassandra/README.md, plugins/inputs/cassandra/cassandra.go, plugins/inputs/ceph/README.md, plugins/inputs/ceph/ceph.go, plugins/inputs/ceph/ceph_test.go, plugins/inputs/cgroup/README.md, plugins/inputs/cgroup/cgroup_linux.go, plugins/inputs/chrony/chrony_test.go, plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go, plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go, plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_util.go, plugins/inputs/clickhouse/clickhouse.go, plugins/inputs/clickhouse/clickhouse_test.go, plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch.go, plugins/inputs/cloudwatch/cloudwatch_test.go, plugins/inputs/couchbase/couchbase.go, plugins/inputs/couchbase/couchbase_test.go, plugins/inputs/cpu/README.md, plugins/inputs/cpu/cpu.go, plugins/inputs/cpu/cpu_test.go, plugins/inputs/csgo/README.md, plugins/inputs/csgo/csgo.go, plugins/inputs/csgo/csgo_test.go
```
plugins/inputs/cassandra/cassandra.go:150:3                           revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/inputs/cassandra/cassandra.go:159:3                           revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/inputs/cassandra/cassandra.go:77:9                            revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/inputs/ceph/ceph.go:180:9                                     revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/inputs/ceph/ceph.go:321:16 …
```
=> Linter fixes for plugins/inputs/[c]*

docs/FAQ.md
The FAQ still had a mention to look at milestones. But since we don't use those anymore, this PR cleans it up.
=> Remove outdated milestones info from FAQ

plugins/processors/strings/README.md, plugins/processors/strings/strings.go, plugins/processors/strings/strings_test.go
Adds a new option for the Strings processer to sanitize strings so that they conform to utf-8
=> Add UTF-8 sanitizer to Strings plugin

plugins/inputs/pf/README.md
Adding the "telegraf" user to the "proxy" group gives it the required permissions to read from /dev/pf.
This PR is to resolve a comment left by @reimda https://github.com/influxdata/telegraf/pull/9200#issuecomment-830457595 . With my testing of Telegraf on Freebsd ARMv7 (21.02.2-RELEASE (arm)), I found you needed to add the Telegraf user to the "Proxy" group in order to gain access to /dev/pf. I do not have sudo installed on my router, so this was the path I took to resolve the permissions issues.
As this specific step isn't suggested in the README, adding. 
resolves #
Provides another method of giving Telegraf's user the correct permissions to read from /dev/pf for pf metrics.
=> Document using group membership to allow access to /dev/pf for pf input plugin

plugins/inputs/dovecot/README.md, plugins/inputs/dovecot/dovecot.go, plugins/inputs/dovecot/dovecot_test.go
It's safer for dovecot to export metrics via a UDS instead of tcp port,
this will add support for that option.
resolves #9215 
dovecot: Add support for unix domain sockets as well
=> plugins/inputs/dovecot: Add support for unix domain sockets

go.mod, go.sum
resolves #9198
relates to #9225
CVE from scans show a need to upgrade hashicorp/consul. The module we are using is actually [hashicorp/consul/api](https://pkg.go.dev/github.com/hashicorp/consul/api?tab=versions) which I have upgraded to the latest
=> Upgrade hashicorp/consul/api to v1.8.1

plugins/inputs/kinesis_consumer/kinesis_consumer.go
resolves #8784 
Simply log error message instead of returning it which results in the malformed data to be skipped rather than repeated
=> Kinesis_consumer input plugin - fix repeating parser error

README.md
Update README.md to:
1) Include FreeBSD armv7 nightly links
2) Organize the list of nightly builds to make it easier to find what you want.
With https://github.com/influxdata/telegraf/pull/9200 recently being closed and there now being a nightly build for FreeBSD armv7, I recently went to find a new build and found it wasn't listed here. I tried the URL and found the armv7 build does exist so adding the URL makes sense.
=> Add Freebsd armv7 URL for nightly builds / organize

plugins/inputs/sqlserver/azuresqlqueries.go, plugins/inputs/sqlserver/sqlserverqueries.go
s.[login_name] tracks SQL and NT users, while [nt_user_name] tracks only NT users.
Enchantment, as of now the username is not gathered if the request comes from a SQL login, as nt_user_name tracks only NT users.
login_name tracks both SQL and NT users.
@denzilribeiro do you want me to add this also for Azure queries?
=> SQL Server - SQL Requests - added s.[login_name]

cmd/telegraf/telegraf.go, cmd/telegraf/telegraf_windows.go
This adds a feature mentioned in this issue https://github.com/influxdata/telegraf/issues/7501
The only change in functionality is that telegraf will now merge multiple "--config" and "--config-directory" flags into the config, rather than only using value of the last flag.
=> Feature: merge multiple "--config" and "--config-directory" flags

plugins/inputs/prometheus/prometheus.go
this change updates the user agent used when scraping a prometheus endpoint from the generic Go-Http-Client to Telegraf/1.18 used in other plugins (the influxdb_v2 output)
=> feat: set user agent when scraping prom metrics

plugins/inputs/ping/README.md, plugins/inputs/ping/ping.go
resolves #9222 
This patch adds an option to specify the number of data bytes to be sent.
This corresponds to the "-s" in the ping(8) command.
It is only applicable for the "native" method.
=> inputs.ping: Add an option to specify packet size

plugins/inputs/http_listener_v2/README.md
default config should _not_ be set to `data_format = "influx"` since if users are reading in influx LP they should be using the `inputs.influxdb_listener`. 
- Add note about using `inputs.influxdb_listener
- Change data format in default config to `data_format.= "json"`
=> update HTTP v2 listener readme

plugins/inputs/eventhub_consumer/README.md, plugins/inputs/eventhub_consumer/eventhub_consumer.go
This PR improves documentation (README and sample config) for eventhub_consumer input plugin:
* clarifies the usage of env vars and adds example.
* addresses issues like: #8643
=> Improve eventhub_consumer input documentation

config/config.go, config/config_test.go
resolves #9218 
Fixed an error where telegraf attempted to fetch files starting with `http:` or `https:` over HTTP/S rather than read them from the filesystem.
=> Fix reading config files starting with http:

internal/internal.go, internal/internal_test.go
I've added the code to allow for different formats in json_timestamp_parser. 
resolves #4928
=> Addresses issues in PR 4928

plugins/outputs/datadog/README.md, plugins/outputs/datadog/datadog.go
resolves #8388 
Added configuring a HTTP proxy for the DataDog output through the config file.
=> Add HTTP proxy to datadog output

.circleci/config.yml, Makefile
The recent parallel build PRs #9096 and #9172 left the circleci package-build command broken for releases, and the debian package lists incomplete. I cherry picked those two PRs to the release-1.18 branch for 1.18.2 and had to add these fixes in order for CI to complete and produce all the expected packages.
=> Parallel build fixes

.circleci/config.yml, Makefile, scripts/alpine.docker, scripts/buster.docker, scripts/ci-1.16.docker, scripts/mac_installgo.sh
Release notes: https://golang.org/doc/devel/release#go1.16
Updating the CI to use 1.16.5
=> Update Go to 1.16.5

scripts/mac_installgo.sh
Adds a SHA256 check, which will we exit the script upon failure (with `set -e`).
Also edit comments.
=> fix: Verify checksum of Go download in mac script

scripts/check-file-changes.sh, scripts/mac_installgo.sh
This pull request caused a bug in the shell script to install Go for mac: https://github.com/influxdata/telegraf/pull/9335 causing the Mac build to fail currently: https://app.circleci.com/pipelines/github/influxdata/telegraf/5226/workflows/6e336a4d-749b-42fb-83d0-3cf0ba309879/jobs/95226. This wasn't caught in the pull request due to the script `check-file-changes.sh` which didn't run the CI if a shell script changed. Also updated the `check-file-changes.sh` script to take into consideration for release branches which was another issue with the script.
@pierwill can you help verify that this change looks good?
=> Fix Mac script to install go

plugins/inputs/suricata/suricata.go, plugins/inputs/suricata/suricata_test.go, plugins/inputs/suricata/testdata/test2.json
resolves #9330
As described in #9330, the plugin didn't support array's in JSON being written by Suricata. I've updated the plugin to handle the case if an array or a string is encountered.
=> Support new Suricata JSON format which includes arrays and strings

plugins/inputs/docker/client.go, plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
This prevents error "too many open files" in most cases
resolves #9242 
Method `Close()` of official docker client just closes all idle connections and don't destroy client instance itself:
https://github.com/moby/moby/blob/17.05.x/client/client.go#L181
So it's safe to use inside telegraf input plugin
=> Closing all idle connections in docker input plugin

plugins/parsers/xml/parser.go, plugins/processors/parser/parser.go, plugins/processors/parser/parser_test.go
resolves #9282
Parsers can use the telegraf logging facility by defining a `Log` field. When using those parsers in inputs the logging facility is automatically set by telegraf after instantiation. However, in this processor the parsers are instantiated manually and setting the log facility is omitted. This in turn leads to segfault-panics for all parsers that rely on the logging facility.
This PR fixes the issue by passing its (newly added) logging facility on to the parser and in this step also gets rid of the unrecommended usage of the `log` package.
Additionally, some minor improvements like making the parser private and fixing the remaining linter issues are performed.
=> Fix segfault in processors/parser

go.mod, go.sum
resolves #9266
go-mssql v0.10.0 fixes issues with tls changes in Go 1.16 causing panic crash in windows telegraf v1.18.2, v1.18.3 sqlserver plugin
=> upgrade denisenkom go-mssql to v0.10.0

plugins/inputs/kube_inventory/client.go
resolves #9293 
Fixes a bug where `kube_inventory` would always connect to `localhost` instead of the URL specified in the plugin configuration.
=> Fix kube_inventory not connecting to specified URL

plugins/outputs/dynatrace/README.md, plugins/outputs/dynatrace/dynatrace.go, plugins/outputs/dynatrace/dynatrace_test.go
- export timestamps
- enrich dimensions with OneAgent data
- Add default dimensions feature
- Seems the readme already mentioned the associated default_dimensions feature for some reason
=> Update dynatrace output

plugins/inputs/sql/drivers_sqlite.go, plugins/outputs/sql/sqlite.go, plugins/outputs/sql/sqlite_test.go
Fix unintended pulling in of CGO by importing the sqlite SQL driver. CGO is required for some platforms when using sqlite. We simply do not support sqlite for those platforms and get rid of the CGO dependency. Fixes CI errors like
```
[...]
package github.com/influxdata/telegraf/cmd/telegraf
imports github.com/influxdata/telegraf/plugins/outputs/all
imports github.com/influxdata/telegraf/plugins/outputs/sql
imports modernc.org/sqlite
imports modernc.org/libc
imports modernc.org/libc/unistd: build constraints exclude all Go files in /go/pkg/mod/modernc.org/libc@v1.9.5/unistd
[...]
```
=> Fix import of sqlite and ignore it on all platforms that require CGO.

.golangci.yml, plugins/inputs/dcos/client.go, plugins/inputs/dcos/dcos.go, plugins/inputs/directory_monitor/directory_monitor.go, plugins/inputs/directory_monitor/directory_monitor_test.go, plugins/inputs/disk/disk.go, plugins/inputs/disk/disk_test.go, plugins/inputs/diskio/diskio.go, plugins/inputs/diskio/diskio_linux_test.go, plugins/inputs/disque/disque.go, plugins/inputs/dns_query/dns_query.go, plugins/inputs/docker/client.go, plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go, plugins/inputs/docker_log/docker_log.go, plugins/inputs/ecs/ecs.go, plugins/inputs/elasticsearch/elasticsearch.go, plugins/inputs/elasticsearch/elasticsearch_test.go, plugins/inputs/ethtool/ethtool_linux.go, plugins/inputs/ethtool/ethtool_test.go, plugins/inputs/eventhub_consumer/eventhub_consumer.go, plugins/inputs/exec/exec.go, plugins/inputs/execd/execd_test.go
```
plugins/inputs/dcos/client.go:236:57                             revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/dcos/client.go:262:23                             revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/dcos/client.go:276:52                             revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/dcos/client.go:321:25                             revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/dcos/client.go:322:2                              revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/dcos/dcos.go:355:2                                revive …
```
=> Linter fixes for plugins/inputs/[de]*

plugins/inputs/ceph/README.md
Update link to Ceph's documentation for Telegraf module. The old link resulted in a 404 error.
=> Adjust link to ceph documentation

plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
resolves #8914
resolves #9278
resolves #9384
1. commit  448eac0 tries to ensure that fileglobs are not tried for remote uris (sources starting with tcp://, udp:// or https://). This is because strings.Index(source, ":\\\\") != 1 (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/x509_cert/x509_cert.go#L70) matches almost all sources -> fileglobs are tried for remote sources.
2. commit 4e1e6f3 tries to ensure that c.tlsCfg.ServerName is reset between multiple certs/sources. Without this telegraf uses same SNI for multiple certs. Leading to telegraf requesting wrong certificates and failing validation because SNI/SAN doesn't match. (Longer discussion in: https://github.com/influxdata/telegraf/issues/8914)
=> Issue 8914 x509sni

plugins/inputs/x509_cert/x509_cert.go
When using the x509_cert plugin with `https` sources, the `source` tag should contain the specified source. However, in #6952 we messed up that tag by unintentionally changing the scheme of the source to `tcp` for `https` sources as described in #9384. The present PR fixes this issue by _not_ messing with the scheme directly.
**Please note: This PR is based on  and should be merged after #9289!**
resolves #9384
=> Fix schema mess-up for x509 with https

plugins/outputs/http/http.go
resolves #9389 
removed tls from HTTP struct since it gets imported with HTTPClientConfig
=> fixing insecure_skip_verify

plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go
resolves #8840 SNMP input can produce metrics with empty metric name
Added a check for empty oid and empty name
fixed an existing unit test to give the table a name
and added a test for a table with empty oid and empty name
=> added a check for oid and name to prevent empty metrics

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum
resolve: #7914
Updating `github.com/couchbase/goutils` to the newest version `v.0.1.0` which is using the Apache 2.0 license. Also updated the other couch-base dependencies to the latest version.
=> Update couchbase dependencies

plugins/inputs/statsd/statsd.go
I marked off the two above criteria because I don't believe this requires a README.md update and I don't think reliable unit tests will be easy to implement since `Statsd.parser()` doesn't provide negative feedback upon a parser error anymore. I'm open to other ways to solve this though! 
resolves #9422 
This fixes an issue where statsd stats would stop getting processed because malformed stats would cause the parser to return. Malformed stats should be logged but they shouldn't cause parsing to stop.
=> Don't stop parsing after statsd parsing error

plugins/inputs/dovecot/dovecot.go
resolves #9415
This PR tries to resolve the regression above.
=> Fix dovecot regression in #9415

plugins/inputs/jenkins/README.md, plugins/inputs/jenkins/jenkins.go, plugins/inputs/jenkins/jenkins_test.go
resolves #9047 
Adds the ability to explicitly include nodes for the `jenkins_node` metric. Previously, you could only exclude nodes from being collected.
Like the `job_exclude` and `job_include` filters, `node_exclude` takes precedence over `node_include` if they are both present.
=> Add include_nodes filter for jenkins

plugins/inputs/kube_inventory/endpoint.go, plugins/inputs/kube_inventory/endpoint_test.go
resolves #9450 
Fixes a segfault in `kube_inventory` due to a nil pointer dereference when an endpoint did not have a node name by checking if the pointer is not nil before dereferencing.
=> Fix segfault in kube_inventory

CONTRIBUTING.md, README.md, config/README.md, docs/developers/README.md
This includes multiple improvements:
- Add README symlinks on locations where you might expect some documentation without the need to update on multiple places.
- Add proper links to contribution of external plugins.
- Link to the list of known external plugins from the main README file.
=> Improve documentation

plugins/inputs/sqlserver/README.md, plugins/inputs/sqlserver/sqlserver.go, plugins/inputs/sqlserver/sqlserver_test.go
The sqlserver input plugin uses windows authentication (aka integrated security) when there is no username and password in the connection string.
#8822 added support for AAD authentication but only when there is no password in the connection string. Since the new check for no password happens before the previous connection logic, this causes windows authentication to be unavailable, which is a regression.
This PR adds a setting to enable AAD authentication. This allows use of windows authentication as before. It's backward compatible because the default of the new setting is the old behavior. New users who want to use AAD will to opt in to the new auth behavior by changing the setting to "AAD".
resolves #9362
=> Sqlserver input: require authentication method to be specified

plugins/parsers/json_v2/parser.go, plugins/parsers/json_v2/parser_test.go, plugins/parsers/json_v2/testdata/array_of_objects/expected.out, plugins/parsers/json_v2/testdata/array_of_objects/input.json, plugins/parsers/json_v2/testdata/array_of_objects/telegraf.conf
@sjwang90 found an issue when parsing the following JSON that would result in empty metrics:
```json
{
"features": [
{
"properties": {
"mag": 5.17
}
}
]
}
```
Config used:
```toml
[[inputs.file]]
files = ["./testdata/test/input.json"]
data_format = "json_v2"
[[inputs.file.json_v2]]
[[inputs.file.json_v2.object]]
path = "features"
```
This pull request resolves this problem by updating the part where the metrics were being discarded.
=> Fix json_v2 parser to handle nested objects in arrays properly

go.mod, go.sum, plugins/inputs/syslog/README.md, plugins/inputs/syslog/commons_test.go, plugins/inputs/syslog/rfc3164_test.go, plugins/inputs/syslog/rfc5426_test.go, plugins/inputs/syslog/syslog.go, plugins/outputs/syslog/syslog.go, plugins/outputs/syslog/syslog_mapper.go
This PR replaces `go-syslog/v2` usage with `go-syslog/v3` so that the `inputs.syslog` plugin can use the [new RFC3164 support](https://github.com/influxdata/go-syslog/pull/27). Resolves #4593 
When defining the inputs, a user will specify the `syslog_standard` option (Either "5424" *[default]* or "3164"). The `best_effort` option will also apply when "3164" is used.
I was really hoping that this would let me use telegraf direction for Cisco syslog messages, but from my understanding it seems they have some problems with current go-syslog parsing:
Format: `<PRI>SEQNUM:HOST:MONTHDAY YEARHOUR:MINUTES:SECONDS.MILLISECONDSTIMEZONE:%APPNAME-SEVERITY-MSGID:%TAGS:MESSAGE`
Example: `<187>37972: Nov 21 16:53:33.429: %LINK-3-UPDOWN: Interface GigabitEthernet0/8, changed state to down`
- Seq field …
=> Migrate syslog/v2 to syslog/v3 (adds RFC3164 support to inputs.syslog) (#4593)

plugins/inputs/sqlserver/sqlserver.go
Suppose the entered connection string in telegraf.conf is incorrect, the error logs in telegraf did not indicate the server/database that is having issues. Also it does not expose error, state and severity when certain queries fail in execution due to permission issue. This makes troubleshooting harder if a single VM is monitoring more than 1 database/server.
**Current Behavior:** 
```
Error in plugin: script AzureSQLDBPerformanceCounters failed: Login error: mssql: Login failed for user 'telegraf'
```
**Desired Behavior:** 
```
Error in plugin:Query AzureSQLDBResourceGovernance failed for server: "sample-server" and database: "sample-database" with Error: login error: mssql: Login failed for user 'telegraf'.
Error in plugin:Query AzureSQLDBResourceGovernance failed for server: …
```
=> Provide detailed message in error log for troubleshooting

plugins/common/cookie/cookie.go, plugins/common/cookie/cookie_test.go, plugins/common/http/config.go, plugins/inputs/http/README.md, plugins/inputs/http/http.go, plugins/inputs/http/http_test.go, plugins/outputs/http/README.md, plugins/outputs/http/http.go
resolves #5932
1. Added a few configuration options for `inputs.http` cookie auth: 
auth url 
body 
method
refresh interval
2. HTTP Client is updated to use a CookieJar
3. During plugin `Init()`, a initial auth is attempted and is successful, a Go routine is fired off for cookie auth renewal
=> Http plugin add cookie auth

cmd/telegraf/telegraf.go, go.mod, go.sum, internal/usage.go, internal/usage_windows.go
resolves #7187
This feature was thought to be already supported, but has now made clear that it isn't and is required for another project effort. To help get this pull request ready quicker I've taken it over to resolve merge conflicts and use the latest [influxdata/tail](https://github.com/influxdata/tail) now that the fix has been merged. This pr still needs to be tested and reviewed to make sure this is the best approach. I also didn't copy over the windows specific changes because it wasn't obvious why they were necessary, see the original pull request #8529 for more details.
Lots of kudos to @vlastahajek for the original pr and the [fix to the tail repo](https://github.com/influxdata/tail/pull/9).
=> Detect changes to config and reload telegraf (copy of pr #8529)

config/types.go, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
resolves #9441 
added a Number struct and an unmarshal that will allow for ints or floats
=> fixed percentiles not being able to be ints

plugins/inputs/prometheus/kubernetes.go
Building upon #8762, the kubelet API requires auth if `--anonymous-auth` flag is set to false for kubelet (which is the case for EKS). 
Enabling that flag is a huge security risk
Closes https://github.com/influxdata/telegraf/issues/9408 https://github.com/influxdata/telegraf/issues/9349
**Before**
```sh
$ curl -v -k "https://10.38.177.113:10250/pods"
*   Trying 10.38.177.113:10250...
* Connected to 10.38.177.113 (10.38.177.113) port 10250 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):    
* TLSv1.3 (IN), TLS handshake, …
```
=> Fix prometheus cadvisor authentication

plugins/parsers/json_v2/parser.go, plugins/parsers/json_v2/parser_test.go, plugins/parsers/json_v2/testdata/complex_nesting/expected.out, plugins/parsers/json_v2/testdata/complex_nesting/input.json, plugins/parsers/json_v2/testdata/complex_nesting/telegraf.conf, plugins/parsers/json_v2/testdata/multiple_arrays_in_object/expected.out
@sjwang90 found another valid issue with the json_v2 parser. Resolved it by simplifying how nesting is handled, for every nested array it will crate a new line protocol. Benefit is that it does now follow the documentation and the code is simpler. Also noticed that the methods can just return `[]telegraf.metric` making it easier to read.
Added a new input.json that caught this issue.
=> Fix how nesting is handled in json_v2 parser

.circleci/config.yml, Makefile, scripts/alpine.docker, scripts/buster.docker, scripts/ci-1.16.docker, scripts/mac_installgo.sh
Release notes: https://golang.org/doc/devel/release#go1.16
Updating the CI to use 1.16.6
=> Update Go to v1.16.6

plugins/inputs/kubernetes/kubernetes.go, plugins/inputs/kubernetes/kubernetes_test.go
Resolves the issue that the pod labels are missing in the metrics `kubernetes_pod_volume` & `kubernetes_pod_network`.
=> Attach the pod labels to the `kubernetes_pod_volume` & `kubernetes_pod_network` metrics.

docs/CONFIGURATION.md
Some tagging behavior is unclear in the docs.
=> [Docs] Clarify tagging behavior

plugins/inputs/prometheus/README.md, plugins/inputs/prometheus/consul.go, plugins/inputs/prometheus/kubernetes.go, plugins/inputs/prometheus/prometheus.go
This PR adds the ability to query Consul Catalog for published prometheus metric endpoints.
Tests are not my strong suit, I will add them if this PR makes sense and there are no other issues with it.
=> For Prometheus Input add ability to query Consul Service catalog

plugins/inputs/fail2ban/fail2ban_test.go, plugins/inputs/file/file_test.go, plugins/inputs/filecount/filesystem_helpers_test.go, plugins/inputs/filestat/filestat.go, plugins/inputs/filestat/filestat_test.go, plugins/inputs/fluentd/fluentd.go, plugins/inputs/fluentd/fluentd_test.go, plugins/inputs/github/github.go, plugins/inputs/gnmi/gnmi.go, plugins/inputs/gnmi/gnmi_test.go
```
plugins/inputs/fail2ban/fail2ban_test.go:106:3            revive       deep-exit: calls to os.Exit only in main() or init() functions
plugins/inputs/fail2ban/fail2ban_test.go:112:3            revive       deep-exit: calls to os.Exit only in main() or init() functions
plugins/inputs/fail2ban/fail2ban_test.go:117:4            revive       deep-exit: calls to os.Exit only in main() or init() functions
plugins/inputs/fail2ban/fail2ban_test.go:121:4            revive       deep-exit: calls to os.Exit only in main() or init() functions
plugins/inputs/fail2ban/fail2ban_test.go:125:4            revive       deep-exit: calls to os.Exit only in main() or init() functions
plugins/inputs/fail2ban/fail2ban_test.go:130:2            revive       deep-exit: calls to …
```
=> Linter fixes for plugins/inputs/[fg]*

internal/type_conversions.go
Resolves #9517 
The `ToBool` type conversion didn't check whether the value already was a boolean value (identity check). This adds the check so that bool values will be handled.
=> Fix handling bool in sql input plugin

plugins/inputs/nsq_consumer/nsq_consumer.go
resolves #9502 
As a fallout of the linter-fixes we now check return code when trying to connect to servers specified in `nsqd`. However, if this option is omitted, which is valid when using `nsqlookupd`, the server list stays empty. In turn the attempt to connect to this empty list of servers fails as can be expected. Previously (<v1.19), this error went unnoticed as the returned error was not checked.
This PR now checks if the server-list specified in `nsqd` (and for backward-compatibility `server`) is empty and omits the attempt to connect to this empty list. Furthermore, we check if at least either `nsqd` or `nsqlookupd` has entires.
=> Fix nsq_consumer regression by avoiding connection to an empty list of servers

plugins/inputs/procstat/README.md, plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/procstat_test.go
Thank you @DEvil0000 for the work on the original pull request (#7890)! I will be taking it over to help resolve merge conflicts and any other required changes.
Closing #7890 and moving forward with this new pr.
=> Update procstat to support cgroup globs & include systemd unit children (Copy of #7890)

plugins/inputs/kube_inventory/persistentvolumeclaim.go, plugins/inputs/kube_inventory/persistentvolumeclaim_test.go
as mentioned [here](https://github.com/influxdata/telegraf/pull/9456#issuecomment-876720823) and [here](https://github.com/influxdata/telegraf/issues/9537#issuecomment-885877302)
Fixes a segfault in `kube_inventory` when selector labels were not present on a persistent volume claim.
=> Prevent segfault in kube_inventory

plugins/outputs/influxdb/http_test.go, plugins/outputs/influxdb/influxdb.go
resolves #9514 
Reworked code to handle more than database not found errors so it will not say metrics are getting pushed when the database goes down. Also updated test
=> Fix metrics reported as written but not actually written 

plugins/inputs/procstat/README.md
Related to #9488, the README wasn't updated correctly and forgot to change ` systemd_all` to `include_systemd_children`.
=> Fix procstat plugin README to match sample config

plugins/inputs/phpfpm/phpfpm_test.go
The test was trying to connect to a localhost address causing failures if you have something running locally. Changed to trying to connect to a fake service.
=> Fixes phpfpm test to connect to a fake service

plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go
Resolves #8871, relates to #9523 and #9524
Properly handles nodes with a bad quality. Instead of returning the error, it is now only passed to the logger. Any following good quality nodes are no longer skipped.
=> Do not skip good quality nodes after a bad quality node is encountered

go.mod, go.sum, plugins/inputs/vsphere/README.md
resolves #9102
replaces pr #9486
Updating vsphere plugin dependency to officially support the latest version of the vsphere products.
=> Update supported vsphere version by updating vmware/govmomi to v0.26.0

go.mod, go.sum
Upgrading to the latest api release due to CVE concerns
resolves #9559
=> Upgrade hashicorp/consul/api to 1.9.1

EXTERNAL_PLUGINS.md
- [ n/a ] Wrote appropriate unit tests.
Summary: adding a link to net_irtt external plugin, as per https://github.com/influxdata/telegraf/tree/master/plugins/common/shim
=> docs: Adding links to net_irtt and dht_sensor external plugins

plugins/inputs/modbus/README.md, plugins/inputs/modbus/modbus.go
resolves #
Added support for RTU over TCP
=> feat: Modbus Rtu over tcp enhancement

plugins/processors/aws/ec2/README.md
Update awsec2 processors readme to following golang code.
=> docs: Update Processors/awsec2 readme

plugins/inputs/postgresql/service.go
resolves #9472 
Fixed a bug in `postgresql` and `postgresql_extensible` where connecting via a unix socket would fail if the full path to the socket was given rather than just the directory of the socket by stripping the socket name from the path so it was only the directory as the library adds the socket path itself. This bug appeared after updating `github.com/jackc/pgx` to v4 in #9182.
=> fix: Normalize PostgreSQL unix socket path

config/aws/credentials.go, plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch.go, plugins/inputs/cloudwatch/cloudwatch_test.go, plugins/inputs/kinesis_consumer/README.md, plugins/inputs/kinesis_consumer/kinesis_consumer.go, plugins/outputs/cloudwatch/README.md, plugins/outputs/cloudwatch/cloudwatch.go, plugins/outputs/cloudwatch_logs/README.md, plugins/outputs/cloudwatch_logs/cloudwatch_logs.go, plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go, plugins/outputs/kinesis/README.md, plugins/outputs/kinesis/kinesis.go, plugins/outputs/timestream/README.md, plugins/outputs/timestream/timestream.go
resolves #9073 
Adds support for authenticating with the AWS API using a [Web Identity Provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html) using the fields `role_arn`, `web_identity_token_file` and `role_session_name`. However, only `role_arn` and `web_identity_token_file` are required to use this authentication method as `role_session_name` will default to the current timestamp.
=> feat: Support AWS Web Identity Provider

plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go
resolves #9523 
The underlying OPCUA library seems to error out often when disconnecting sessions. In turn, with the recent linter-fixes (#8992) applied, reconnection fails due to the newly introduced error check in disconnect.
This PR changes the bailing-out with an error into logging the error only but allows to continue reconnection.
=> fix: Do not return on disconnect to avoid breaking reconnect

plugins/inputs/udp_listener/udp_listener_test.go
The udp_listener plugin will be deprecated in 2.0, these unit tests are randomly failing but aren't worth the effort to fix seeing they will be removed soon. The plugin can't be removed from master yet but this pr proposes to at least mute the tests so we don't have these flaky tests anymore.
More information about 2.0 here: https://github.com/influxdata/telegraf/issues/9478
=> fix: muting tests for udp_listener

plugins/outputs/loki/README.md, plugins/outputs/loki/loki.go, plugins/outputs/loki/loki_test.go
Related to https://github.com/influxdata/telegraf/pull/9114
Loki has very strict ordering requirements. You cannot submit a log line with a timestamp older than what already exists (for a matching label set). One way around the issue is to overwrite the timestamp using a processor, as discussed in the related PR. However this is not ideal when we want to send our logs with the timestamp of the input source, not the time telegraf processed the metric.
This PR adds an additional step in the Loki plugin to sort the ~~log data by timestamp in each log stream~~ batch of metrics by timestamp before they are serialised and written to Loki.
@Eraac - looping you in as the author of the original Loki plugin.
@loganmc10 - may be of interest to you
=> fix: sort logs by timestamp before writing to Loki

plugins/processors/aws/ec2/ec2.go, plugins/processors/aws/ec2/ec2_test.go
To help with the config-api work, the init functions should no longer be responsible with connecting to external services. Moved this change from the config-api pull request: https://github.com/influxdata/telegraf/pull/9546 because it shouldn't be a breaking change created a separate pr for it to help reduce the number of files changed in #9546
=> fix: Refactor ec2 init for config-api

plugins/inputs/opcua/opcua_client.go
- [-] Updated associated README.md.
- [-] Wrote appropriate unit tests.
resolves #9582 
If the client connection only gets closed, the next invocation of `Connect`
(via `Gather` loop) would try to invoke `CloseSession` on an already-closed
client.
It might be possible to get rid of the nil-check
```
if o.client != nil {
```
in `Connect` but further investigation is needed.
=> fix(opcua): clean client on disconnect so that connect works cleanly

plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch.go, plugins/inputs/cloudwatch/cloudwatch_test.go
resolves #8233 
Added the ability to pull metrics from multiple namespaces for the `cloudwatch` input. 
Adds the field `namespaces` to specify the namespaces to pull from. The change is backward compatible with the previous versions using the `namespace` field by appending the value of `namespace` to `namespaces`.
=> feat: Pull metrics from multiple AWS CloudWatch namespaces

plugins/outputs/cratedb/README.md, plugins/outputs/cratedb/cratedb.go, plugins/outputs/cratedb/cratedb_test.go, telegraf.conf
resolves #7026 
Fixes a bug in the `cratedb` output where records would fail to insert if any tags contained keys separated by dots by replacing all dots with underscores in the key. Also made insertion errors more explicit since CrateDB does not cause the entire insert command to fail when the one record fails in a batch.
=> fix: CrateDB replace dots in tag keys with underscores

plugins/inputs/redis/README.md, plugins/inputs/redis/redis.go
Updates the documentation for `redis` to clearly specify the allowed result types for commands and explain the format of the `command` array. Also errors when an unknown result type is specified rather than defaulting to a string.
=> docs: improve redis commands documentation

go.mod, go.sum
Resolve: #8800
Relevant information that explains the problem:
- https://groups.google.com/g/golang-nuts/c/MVtHZUtZru4
- https://github.com/aws/amazon-cloudwatch-agent/blob/master/go.mod#L33
Seems this issue only happens when GOPROXY is set to direct, I created pr to implement the workaround suggested by the above links to use the pseudo version number for wireguard.
For more information on pseudo versions you can look here: https://golang.org/doc/modules/version-numbers#tmp_1
This is also causing dependabot to fail.
=> fix: wireguard unknown revision when using GOPROXY=direct

plugins/outputs/sql/README.md, plugins/outputs/sql/sql.go, plugins/outputs/sql/sql_test.go, plugins/outputs/sql/testdata/mariadb/expected.sql, plugins/outputs/sql/testdata/postgres/expected.sql
resolves #9597 
Add `Bool` to the datatypes that can be configured and allow for bool values to be mapped to this datatype.
=> feat: add bool datatype for sql output plugin

plugins/common/cookie/cookie.go, plugins/common/cookie/cookie_test.go, plugins/common/http/config.go
The tests for `cookie.go` were failing randomly, when checking for the expected number of time it should have authenticated sometimes the number would be less then expected and throw the error `"2" is not greater than or equal to "3"` [link to example of a failing test](https://app.circleci.com/pipelines/github/influxdata/telegraf/5898/workflows/cc103580-69df-493e-8842-ca3085ce4d3a/jobs/105376).
This pr fixes the tests by removing the reliance on sleep, also closes each fake http server before the next test to avoid `socket: too many open files` error.
=> fix: flaky cookie test and failing to close fake server between tests

plugins/inputs/prometheus/kubernetes.go
Resolves #9600
- Get the pod info from the event using `event.Object.(*corev1.Pod)` so that the pod isn't an empty struct. This is the equivalent of `watcher.Next(pod)` when the previous client package was used.
- A [go routine](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/kubernetes.go#L80) is already running that keeps calling the watchPod() function whenever it returns. Right now with the watchPod() function is calling its own go routine, the function returns and watchPod is called again. This continuously creates new threads and new watchers and re-registers pods instead of having one watcher running each time. Changed back to the [previous functionality](https://github.com/influxdata/telegraf/blob/24a552b90ba06d278cbe0639290a9bee1d7791b6/plugins/inputs/ …
=> fix: issues with prometheus kubernetes pod discovery

.github/dependabot.yml
Dependabot is now working again with this merged: https://github.com/influxdata/telegraf/pull/9620 so it made some pr's with the semantic-pullrequest checker failing. To fix this we need to prefix all the commits it makes with `fix:`.
Setting was found in the documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message
=> fix: prefix dependabot commits with "fix:"

README.md, docs/DATA_FORMATS_INPUT.md
=> docs: update links

plugins/outputs/graylog/graylog.go
The graylog output plugin previously output the timestamp in whole seconds with no fractional part. This PR adds the fractionalpart. I'm not sure why it wasn't there before. The gelf format specification says it is optional but is clear that fractional seconds are allowed.
https://docs.graylog.org/en/3.3/pages/gelf.html#gelf-payload-specification
=> fix: Output timestamp with fractional seconds

plugins/inputs/mdstat/mdstat.go, plugins/inputs/mdstat/mdstat_notlinux.go, plugins/inputs/mdstat/mdstat_test.go
#9101 was merged but hadn't run against go v1.17, to fix the CI failing just ran `go fmt` so that it can add the missing updated build flags.
More information on these builds flags can be found in the pr: #9642
=> fix: run go fmt on inputs.mdstat with Go v1.17

plugins/common/cookie/cookie.go, plugins/common/cookie/cookie_test.go
The tests in `cookie_test.go` are still failing randomly ([link to circleci failed Mac build on master](https://app.circleci.com/pipelines/github/influxdata/telegraf/6062/workflows/6c41cd80-9c03-47c5-902e-85593ef791cd/jobs/107660)), I thought I had resolved this issue in this pr #9608. I believe the problem is due to a race condition, where the go-routine running the ticker loop to authenticate again isn't guaranteed to be called before checking the count.
This pr adds a `sync.WaitGroup` and a `context.Context` with cancel, to guarantee that the ticker loop has finished running before checking the count. Also moved the authentication renewal loop to a separate function so that the tests can pass ticker and then call `ticker.Close()`. Refactored the tests away from using the assert …
=> fix: race condition in cookie test

plugins/serializers/prometheus/README.md, plugins/serializers/prometheus/collection.go, plugins/serializers/prometheus/collection_test.go
resolves #8170 
Replaces #8257
#8257 partially implements a fix for #8170 but this PR expands it to also resolve the expiration issue to the Summary type.
It also updates both the Histogram and Summary `timestampMs` field when new data arrives for a particular Histogram or Summary. I talk about this problem in [this](https://github.com/influxdata/telegraf/issues/8170#issuecomment-816261054) comment on #8170. Below expands on it.
If you have configured `[[outputs.prometheus_client]]` to `export_timestamps = true` then without the updating of `timestampMs` on new data coming in you end up in a situation like below.
Say you are pushing prometheus data to telegraf. The first batch might look something like below with a timestamp of `1617722541063`
``` …
```
=> Make prometheus serializer update timestamps and expiration time as new data arrives

plugins/outputs/opentelemetry/opentelemetry.go, plugins/outputs/opentelemetry/opentelemetry_test.go
resolves issue mentioned in this [comment](https://github.com/influxdata/telegraf/pull/9228#issuecomment-892942452)
Updating the OpenTelemetry output plugin to pass `headers` configuration as metadata into grpc requests.
=> fix: outputs.opentelemetry use headers config in grpc requests

plugins/outputs/opentelemetry/opentelemetry.go, plugins/outputs/opentelemetry/opentelemetry_test.go
Following the discussion [here](https://github.com/influxdata/telegraf/pull/9228#issuecomment-892942452), the attributes setting was not being utilized in the opentelemetry output plugin. This PR fixes that by upserting the attributes configured into the resource before emitting it.
This is a followup to https://github.com/influxdata/telegraf/pull/9587
=> fix: outputs.opentelemetry use attributes setting

go.mod, go.sum, plugins/inputs/opcua/opcua_client.go
resolves #9551 
Update to the latest state of the gopcua library in the hope to fix potential timeout problems (see #9551).
=> fix: Update gopcua library to latest version

plugins/inputs/tail/tail_test.go
resolves: #8478 
similar to: https://github.com/influxdata/telegraf/pull/8927
Evidently, the watch method "poll" is more stable on Windows and has issue with fsnotify (some issues about this in the hpcloud/tail repo e.g. https://github.com/hpcloud/tail/issues/54) . I was able to re-produce the failing tail tests locally, and it was occurring in the test `TestCharacterEncoding` which didn't have the change #8927 implemented to set the watcher method to "poll" for Windows. After making this change I haven't been able to re-produce it but that doesn't guarantee anything of course, but hopefully this fixes the flaky test.
Slightly refactored the test to remove some duplicated setup.
=> fix(inputs.tail): change test default watch method to poll when Win

plugins/outputs/http/http.go
We run a multitenant system with 1000s of users and some of them use
Telegraf to push to us. The error logs they see look like this:
```
2021-09-06T06:07:34Z E! [agent] Error writing to outputs.http:
when writing to [XXX] received status code: 400
2021-09-06T06:07:34Z D! [outputs.http] Buffer fullness: 2410 / 200000
metrics
2021-09-06T06:07:34Z E! [agent] Error writing to outputs.http: when
writing to [XXX] received status code: 400
2021-09-06T06:07:44Z D! [outputs.http] Buffer fullness: 2415 / 200000
metrics
2021-09-06T06:07:44Z E! [agent] Error writing to outputs.http: when
writing to [XXXX] received status code: 400
```
Our upstream returns actionable messages that make the issue pretty
clear to our users, but those using Telegraf cannot see those messages.
I propose that users should …
=> fix: Add error message logging to outputs.http

plugins/inputs/cloudwatch/cloudwatch.go
Fix the error of InvalidParameterValue: Parameters do not match original request parameters as the current code dont use correctly the return token from aws client
Following the discussion on PR #9386  (the update to support multiple namespaces in cloudwatch input plugin ) the latest change keep the token pagination to the next namespace which result in an error of InvalidParameterValue: Parameters do not match original request parameters. This change is to fix this error.
I moved the namespace loop and the aws param initialization to be outside the loop of the pagination
=> fix: pagination error on cloudwatch plugin

plugins/inputs/bond/README.md, plugins/inputs/bond/bond.go, plugins/inputs/bond/bond_test.go
Collecting the count of slaves to a network bond makes alerting on downed slaves/etc. much easier.
=> feat: add count of bonded slaves (for easier alerting)

plugins/parsers/registry.go, plugins/parsers/xpath/parser.go, plugins/parsers/xpath/parser_test.go
related to #9756 
In case you specify a `metric_name` within a parser configuration section you will actually set a _query_ to fill the metric name. If this query references a non-existing node the code will panic as the resulting `nil` value cannot be converted to `string` (see #9756). However, this might also happen in case you try to specify a constant metric name but omit the `string('...')` around that name.
Catch the panic before it occurs and add test cases to test it works correctly.
=> fix: Fix panic for non-existing metric names

README.md, docs/NIGHTLIES.md, docs/README.md
This was discussed in a Telegraf planning meeting last week. 
This simply moves the large chunk of nightly builds off to developer documentation, to a specific page.
=> docs: Move nightly builds

.circleci/config.yml, Makefile, docs/developers/PACKAGING.md
resolve: #9261
This change reverts the behavior of `make package` to how it was before #9096 and will build all packages by default. Then to build specific packages you now need to override the variable `include_packages` with the packages you want, such as `make package include_packages="amd64.deb"`. Running `make help` will list the possible values for `include_packages`. To keep the information on what packages are associated with what architecture in the makefile new rules have been added to echo out the lists so that you can build all `amd64` packages for example like so `make package include_packages="$(make amd64)"`.
Example output of `make help`
```
Targets:
all          - download dependencies and compile telegraf binary
deps         - download dependencies
telegraf     - compile …
```
=> chore: "makefile help" output, but still support building based on arch for CI

plugins/inputs/prometheus/README.md
Existing Prometheus plugin docs for "Usage for Caddy Server" is for Caddy v1 and out of date as now Caddy no longer has a prometheus plugin and metrics are built in. 
Updating readme to include new instructions and links
=> docs: update caddy server instructions

.circleci/config.yml, Makefile
Updated the nightly workflow to be the same as the per-commit workflow so that is packages everything in parallel. Also removed `make upload-nightly` and moved the logic in the the CI config. All it was doing was an aws call which is only used in the CI process and won't be used by users so it doesn't seem appropriate to live in the makefile.
Used YAML anchors to make the nightly and per-commit workflow a little bit more DRY, but seems this is the limit with YAML. Bit more context in this stack-overflow question: https://stackoverflow.com/questions/4948933/is-there-a-way-to-alias-anchor-an-array-in-yaml
:warning: I don't know how to the test the nightly workflow without running the nightly workflow.
=> chore: update nightly workflow to match per-commit workflow

etc/telegraf.conf, plugins/outputs/graylog/README.md, plugins/outputs/graylog/graylog.go, plugins/outputs/graylog/graylog_test.go
This PR resolves #9034.
It adds support for TCP. Servers (endpoints) may now be specified as URLs with either `udp` or `tcp` scheme, eg. `"udp://127.0.0.1:12201"` or `"tcp://127.0.0.1:12201"`. For compatiblity with existing configurations, if scheme is missing (eg. `"127.0.0.1:12201"`) or is not `udp` neither `tcp`, UDP protocol is assumed.
Sample config has been changed to reflect it:
```
servers = ["udp://127.0.0.1:12201"]
```
Config option `timeout` allows to change connection dialup timeout.
Connection handling has been refactored. Although I'm not quite sure, it may be OK for UDP to have a connection created for each outgoing message, but it would not work well for TCP where network resources would get depleted quickly. Therefore connections are reused (and recreated whenever needed, …
=> feat: add graylog plugin TCP support

.circleci/config.yml
There was a mistake in the refactor in this pull request: #9781 the nightly step uploads all the artifacts and requires to wait for the package steps. The nightly job was running before them without this change.
=> fix: nightly upload requires package steps

etc/telegraf.conf, plugins/inputs/knx_listener/README.md, plugins/inputs/knx_listener/knx_listener.go
resolves #9709 
Rename `KNXListener` input plugin to `knx_listener` to follow the convention.
=> fix: Rename KNXListener to knx_listener

Makefile
On go1.17.1 make lint is failing due to some errors around a constant
overflow error. Upgrading the golang-ci package resolves this.
=> fix: update golang-ci package

plugins/inputs/opcua/README.md, plugins/inputs/opcua/opcua_client.go
=> feat: Allow user to select the source for the metric timestamp.

plugins/inputs/elasticsearch_query/aggregation_query.go
This will print out the elasticsearch query itself if debug logging is
turned on. This is incredibly helpful when trying to put together a new
query or debugging what might be going on. The output string can then be
used directly with Elasticsearch via something like:
$ curl -H 'Content-Type: application/json' -XPOST "http://localhost:9200/_search" -d'<output>'
resolves #
=> feat: add debug query output to elasticsearch_query

plugins/inputs/couchbase/README.md, plugins/inputs/couchbase/couchbase.go, plugins/inputs/couchbase/couchbase_test.go
resolves #9454 
Fixes a bug where the `couchbase` plugin would fail to retrieve bucket stats due to a self-signed certificate. Prior, only the bucket stats would fail because the couchbase library skips certificate verification by default unless a keypair and optional root certificate are provided.
=> fix: Couchbase insecure certificate validation

plugins/outputs/mqtt/README.md, plugins/outputs/mqtt/mqtt.go, plugins/outputs/mqtt/mqtt_test.go
resolves #9763
Users were getting a identifier rejected error when using the plugin with mosquitto v2.0.12
eclipse/mosquitto v2.0.12 has a [bug](https://github.com/eclipse/mosquitto/issues/2117) where you cannot set keep_alive to 0. This is now a known bug which will be fixed in the next release v2.0.13.
I've added a config option for keep_alive so that users can decide themselves what they want to set this to, and so users of v2.0.12 are still able to use this plugin.
Defaults to 0 (turning the keep alive feature off) as this has been the behavior of this plugin for the last 4 years. The library github.com/eclipse/paho.mqtt.golang we are using defaults keep_alive to 30.
Added documentation around the purpose of the config option and updated the integration test so if you are running any …
=> fix: add keep alive config option for identifier rejected error

.gitignore
As the application requires a config.toml or config.conf file it makes
sense to ignore these types of files rather than having them show up
in git status output.
While the files are technically in the toml format, we use the .conf
extension in our documentation so ignore both.
resolves #
=> fix: gitignore should ignore .toml & .conf files

plugins/inputs/procstat/procstat.go
In #9488 the way that tags were built for procstat_lookup was changed
and it was only including the pid_finder and result tags. This is not
consistent with the documentation and is a regression from how they were
previously constructed.
Because of the large change to how procstat metrics are gathered, this
will use one of the process metric's tags as a basis for the tags for
procstat_lookup.
Resolves: #9793
=> fix: procstat missing tags in procstat_lookup metric

plugins/outputs/loki/loki.go
=> fix: update toml tag to match sample config / readme

plugins/inputs/intel_rdt/intel_rdt.go
resolves #9844
when intel_rdt plugin enabled, `service stop telegraf` will timeout even when telegraf service is running as root.
This patch fixes it.
=> fix: logging in intel_rdt.go caused service stop timeout even as root (#9844)

plugins/inputs/mongodb/mongostat.go
input plugin would fail (and result in seg fault) because there was no check to see if newStat.Metrics.Repl.Network.GetMores was nil or not. Added a checking so that the assignment would happen only when newStat.Metrics.Repl.Network.GetMores is not nil.
resolves #9845
This code change will make sure to check the newStat.Metrics.Repl.Network.GetMores is not null, before performing any access to its underlying variables. This will prevent the mongodb plugin from resulting into segmentation violation that the issue #9845 reported.
```
if newStat.Metrics.Repl.Network.GetMores != nil {
returnVal.ReplNetworkGetmoresNum = newStat.Metrics.Repl.Network.GetMores.Num
returnVal.ReplNetworkGetmoresTotalMillis = newStat.Metrics.Repl.Network.GetMores.TotalMillis
}
```
=> fix: mongodb input plugin issue #9845

.github/PULL_REQUEST_TEMPLATE.md
Remove line in PR template which has been breaking the way the label bot searches for text to identify appropriate labels.
=> fix: remove line which breaks label bot functionality

plugins/inputs/intel_rdt/intel_rdt.go, plugins/inputs/intel_rdt/intel_rdt_test.go, plugins/inputs/intel_rdt/publisher.go, plugins/inputs/intel_rdt/publisher_test.go
Summary:
- Resolves #10025 timezone issue. The plugin now puts local timezone to measurements gathered from pqos tool instead of UTC by default.
- Fixed all linter issues. E.g: maximum number of return results per function exceeded.
- Added check to avoid panic on wrong csv input line format:
```	
if lenOfPIDs > len(splitCSV.coreOrPIDsValues) {
return parsedProcessMeasurement{}, errors.New("detected more pids (quoted) than actual number of pids in csv line")
}
```
=> fix: Resolve Intel RDT timezone issue

plugins/inputs/influxdb/README.md
Closes influxdata/DAR#232
Updated the metrics and descriptions returned by the InfluxDB input plugin.
=> fix: update influxdb input schema documentation

plugins/inputs/nats/nats.go, plugins/inputs/neptune_apex/neptune_apex.go, plugins/inputs/net_response/net_response.go, plugins/inputs/nginx/nginx_test.go, plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go, plugins/inputs/nginx_upstream_check/nginx_upstream_check.go, plugins/inputs/nsd/nsd.go, plugins/inputs/nsd/nsd_test.go, plugins/inputs/nsq_consumer/nsq_consumer_test.go, plugins/inputs/nstat/nstat.go, plugins/inputs/ntpq/ntpq.go, plugins/inputs/ntpq/ntpq_test.go, plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go, plugins/inputs/openldap/openldap.go, plugins/inputs/openldap/openldap_test.go, plugins/inputs/openntpd/openntpd_test.go, plugins/inputs/opensmtpd/opensmtpd_test.go, plugins/inputs/opentelemetry/opentelemetry_test.go, plugins/inputs/openweathermap/openweathermap.go
```
plugins/inputs/nats/nats.go:44:2                                    revive       import-shadowing: The name 'url' shadows an import name
plugins/inputs/neptune_apex/neptune_apex.go:248:8                   revive       unexported-naming: the symbol TimeLayout is local, its name should start with a lowercase letter
plugins/inputs/net_response/net_response.go:123:4                   revive       unexported-naming: the symbol RegEx is local, its name should start with a lowercase letter
plugins/inputs/net_response/net_response.go:189:2                   revive       unexported-naming: the symbol RegEx is local, its name should start with a lowercase letter
plugins/inputs/net_response/net_response.go:19:2                    staticcheck  SA9004: only the first …
```
=> fix: Linter fixes for plugins/inputs/[n-o]*

plugins/inputs/mailchimp/chimp_api.go, plugins/inputs/mailchimp/mailchimp.go, plugins/inputs/mailchimp/mailchimp_test.go, plugins/inputs/marklogic/marklogic.go, plugins/inputs/mcrouter/mcrouter.go, plugins/inputs/mcrouter/mcrouter_test.go, plugins/inputs/mdstat/mdstat_test.go, plugins/inputs/memcached/memcached_test.go, plugins/inputs/mesos/mesos.go, plugins/inputs/mesos/mesos_test.go, plugins/inputs/minecraft/client.go, plugins/inputs/mongodb/mongodb_data_test.go, plugins/inputs/mongodb/mongodb_server_test.go, plugins/inputs/mongodb/mongostat.go, plugins/inputs/mongodb/mongostat_test.go, plugins/inputs/monit/monit.go, plugins/inputs/monit/monit_test.go, plugins/inputs/mqtt_consumer/README.md, plugins/inputs/mqtt_consumer/mqtt_consumer.go, plugins/inputs/multifile/multifile_test.go, plugins/inputs/mysql/mysql.go, plugins/inputs/mysql/mysql_test.go
```
plugins/inputs/mailchimp/chimp_api.go:8:2           revive         imports-blacklist: should not use the following blacklisted import: "log"
plugins/inputs/marklogic/marklogic.go:166:66        revive         import-shadowing: The name 'url' shadows an import name
plugins/inputs/marklogic/marklogic.go:228:36        revive         import-shadowing: The name 'url' shadows an import name
plugins/inputs/mcrouter/mcrouter.go:149:1           revive         confusing-results: unnamed results of the same type may be confusing, consider using named results
plugins/inputs/mesos/mesos.go:25:2                  staticcheck    SA9004: only the first constant in this group has an explicit type
plugins/inputs/mesos/mesos.go:7:2                   revive …
```
=> fix: Linter fixes for plugins/inputs/m*

.circleci/config.yml
The share-artifacts job wasn't checking what files changed like the other jobs, so the bot was failing to find artifacts when it was triggered this way.
=> chore: don't trigger share-artifacts if no go files changed

plugins/processors/regex/README.md, plugins/processors/regex/regex.go, plugins/processors/regex/regex_test.go
resolves #5159
resolves #9506 
resolves #9557 
related to #6830, #6831
With this PR, the `regexp` processor is able to rename measurements, tags and fields using regular expressions. To do so, the user specifies _what_ to rename using the `key` property. Furthermore, the user has control over the behavior in case the resulting tag or field name already exists by changing the `result_key` value between `overwrite` and `keep`.
=> feat: Extend regexp processor do allow renaming of measurements, tags and fields

docs/LICENSE_OF_DEPENDENCIES.md
Markdown linter fixes for LICENSE_OF_DEPENDENCIES.md
resolves https://github.com/influxdata/telegraf/issues/10064
=> fix: Markdown linter fixes for LICENSE_OF_DEPENDENCIES.md

plugins/inputs/nvidia_smi/README.md, plugins/inputs/nvidia_smi/nvidia_smi.go
The smi path exception was thrown in Init() (previously thrown in Gather()), the purpose of this is to find the problem earlier
resolves #9979
=> fix: Set the default value correctly

plugins/inputs/modbus/configuration.go, plugins/inputs/modbus/configuration_original.go, plugins/inputs/modbus/modbus.go, plugins/inputs/modbus/modbus_openbsd.go, plugins/inputs/modbus/modbus_test.go, plugins/inputs/modbus/request.go, plugins/inputs/modbus/type_conversions.go, plugins/inputs/modbus/type_conversions16.go, plugins/inputs/modbus/type_conversions32.go, plugins/inputs/modbus/type_conversions64.go
This is the remaining plugin that is blocking builds on OpenBSD. The issue is the github.com/grid-x/serial library does not build on OpenBSD. That library is an indirect import, due to github.com/grid-x/modbus. Upgrading modbus does not help the situation as it does not pull in a newer version of the grid-x/serial.
Because this is the only one, I figured it is simpler to stop building this on openbsd until someone comes by with a better solution.
resolves #10034
=> fix: do not build modbus on openbsd

plugins/inputs/proxmox/proxmox.go, plugins/inputs/proxmox/proxmox_test.go, plugins/inputs/proxmox/structs.go
Small fix to properly parse JSON data from Proxmox >=7.0 installs.
resolves #9611
- Updated the VMStat schema to use a Number for ID.
- Changed getCurrentVMStatus and getVmConfig accordingly.
- Added case to testdata to check that both string representations and integers work in JSON.
=> fix: Proxmox input: Changed VM ID from string to int, fixes #9611

plugins/inputs/mysql/mysql.go, plugins/inputs/mysql/mysql_test.go, plugins/inputs/mysql/v1/mysql.go, plugins/inputs/mysql/v2/convert.go, plugins/inputs/mysql/v2/convert_test.go
follow-up to  #9403:
- fix #6671 by parsing the column types of slave status
- add more variables from #5055
- cleanup
=> fix: mysql: type conversion follow-up

plugins/inputs/mongodb/README.md
The markdown linter checks the entire file, not just the parts changed, so to help #10075 I resolved the remaining linter issues in the README for the plugin inputs/mongodb. Just some minor issues.
=> fix(inputs/mongodb): resolve all markdown linter issues in README.md

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/mongodb.go
Since v1.19.2 telegraf collects PRIMARY MongoDB metrics via SECONDARY servers by default. By that it means you are not able to get SECONDARY server metrics with default configuration. To fix that, `?connection=direct` should be used in conection string URL. Hopefully that README.md fix saves lot of debugging time in future for other users :))
=> fix (inputs/mongodb) readme: correct connection URI

plugins/parsers/csv/README.md
This pull request resolves some minor markdown linter issues in the parser/csv readme.
The linter complained about them in pr #10083
=> fix(parser/csv): resolve linter issues

go.mod, go.sum, plugins/common/shim/config_test.go, plugins/common/shim/testdata/special.conf
resolves #10088 
Bump up version of BurntSushi/toml to v0.4.1
Local tests: 
* `make check` and `make test` run successfully
* Starting the docker containers and running `make test-integration` runs with two failures, which locally on my machine also fail with the current master (i.e. same behavior for `BurntSushi/toml v0.3.1` and `v0.4.1`: 
* `FAIL    github.com/influxdata/telegraf/plugins/inputs/ping      10.169s`
* `FAIL    github.com/influxdata/telegraf/plugins/outputs/mongodb  65.052s `
=> fix: update BurntSushi/toml for hex config support

.github/workflows/linter.yml
The markdown linter is failing due to an issue with the latest version (v4.8.3), in the meantime updating the linter configuration to use an older version known to still work (v4.8.1).
Relevant issue: https://github.com/github/super-linter/issues/2128
=> fix: super-linter use v4.8.1, issue with latest

plugins/inputs/directory_monitor/directory_monitor.go, plugins/inputs/directory_monitor/directory_monitor_test.go, plugins/inputs/tail/tail.go, plugins/inputs/tail/tail_test.go, plugins/parsers/csv/parser.go, plugins/parsers/csv/parser_test.go
resolves #9898
resolves #9903
resolves #5338
🐛 Fixed an issue with directory monitor input plugin when data format is CSV and csv_skip_rows>0 and csv_header_row_count>=1
✅ Added new test cases that cover these scenarios
=> fix: directory monitor input plugin when data format is CSV and csv_skip_rows>0 and csv_header_row_count>=1

plugins/inputs/zfs/README.md
This pull request resolves minor linter issues in README.md for the input plugin zfs, brought up in #10099
=> fix(inputs/zfs): resolve README.md linter issues

plugins/outputs/amon/amon.go, plugins/outputs/amqp/amqp.go, plugins/outputs/amqp/client.go, plugins/outputs/application_insights/application_insights_test.go, plugins/outputs/azure_monitor/azure_monitor.go, plugins/outputs/cloud_pubsub/pubsub_test.go, plugins/outputs/cloudwatch/cloudwatch.go, plugins/outputs/cloudwatch/cloudwatch_test.go, plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go, plugins/outputs/cratedb/cratedb.go, plugins/outputs/datadog/datadog.go, plugins/outputs/datadog/datadog_test.go, plugins/outputs/elasticsearch/elasticsearch.go, plugins/outputs/elasticsearch/elasticsearch_test.go, plugins/outputs/exec/exec.go, plugins/outputs/exec/exec_test.go, plugins/outputs/execd/execd_test.go, plugins/outputs/file/file_test.go
```
plugins/outputs/amon/amon.go:145:17                                       unconvert    unnecessary conversion
plugins/outputs/amqp/amqp.go:183:3                                        revive       import-shadowing: The name 'config' shadows an import name
plugins/outputs/amqp/amqp.go:254:4                                        revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/outputs/amqp/amqp.go:255:5                                        ineffassign  ineffectual assignment to first
plugins/outputs/amqp/amqp.go:271:3                                        revive       unhandled-error: Unhandled error in call to function q.client.Close
plugins/outputs/amqp/amqp.go:318:2 …
```
=> fix: Linter fixes for plugins/outputs/[a-f]*

go.mod, go.sum, plugins/inputs/cpu/cpu.go, plugins/inputs/cpu/cpu_test.go, plugins/inputs/disk/disk.go, plugins/inputs/disk/disk_test.go, plugins/inputs/diskio/diskio_test.go, plugins/inputs/mem/memory.go, plugins/inputs/mem/memory_test.go, plugins/inputs/net/net_test.go, plugins/inputs/procstat/native_finder.go, plugins/inputs/procstat/process.go, plugins/inputs/procstat/procstat.go, plugins/inputs/procstat/procstat_test.go, plugins/inputs/swap/swap_test.go, plugins/inputs/system/mock_PS.go, plugins/inputs/system/ps.go, plugins/inputs/system/system.go, plugins/inputs/temp/temp_test.go
At the end of the month, gopsutil will drop support for version 2 [1]. This PR migrate to v3 of gopsutil.
[1]: https://github.com/shirou/gopsutil/pull/1174
=> fix: update shirou/gopsutil to v3

config/config.go
We renamed KNXListener to knx_listener a while back. We registered it under both names for backward compatibility. Since it's registered twice the sample config has two sections, one with each name.
This PR checks for the old name when printing the sample config, and skips the section in that case.
=> fix: skip knxlistener when writing the sample config

Makefile
Currently, any make command will run these three which commands because of how they are indented. It is annoying if you don't happen to have one of the items installed. This moves them back to where they actually need to be run.
resolves #
=> fix: update makefile indents to not always run which

plugins/aggregators/starlark/starlark.go
resloves: #9419 
Leftover `//nolint` comment that kept the file from being linted for `aggregator/starlark`
=> chore: remove leftover nolint comment

config/config.go, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
resolves #
- fix: #10113
reason: input plugins(statsd), parse metrics line, value has '=' parse error(return empty tag,ignore tag)
After repair: 
```
line ="uri=/service/endpoint?sampleParam={paramValue}"
parse result  key="uri", val="/service/endpoint?sampleParam\={paramValue}"
```
file: config/config.go adjust the deprecated position, some IDE can disply strikethrough, eg: goland
=> fix: input plugin statsd bug

plugins/inputs/win_services/README.md, plugins/inputs/win_services/win_services.go, plugins/inputs/win_services/win_services_test.go
resolves #8733
This pull request updates the input plugin `win_services` and adds a new configuration feature named `excluded_service_names` that will allow users to list what services to ignore. This plugin was already using the internal utility `NewIncludeExcludeFilter` which accepts an exclude list, so now it gets list from the user and passes it along.
Background info:
This duplicates and replaces the pull request: #8901, my intention is to just clean it up slightly to help get the feature merged. All the credit should go to @let-thomas thank you for working on this! I just had to run `gofmt`, match the sample config with the readme, and fix some minor markdown linter issues.
=> feat(inputs.win_services): add exclude filter

plugins/inputs/snmp_trap/README.md, plugins/inputs/snmp_trap/snmp_trap.go
`snmp_trap` was reworked to use `gosmi` for mib look up but the readme still stated `snmptranslate`. Removed the `snmptranslate` section from the readme.
Also fix default path to use the suggested path from the readme if none is specified.
=> fix: removed snmptranslate from readme and fix default path

plugins/inputs/win_perf_counters/README.md, plugins/inputs/win_perf_counters/win_perf_counters.go, plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go, plugins/inputs/win_perf_counters/win_perf_counters_test.go
Add a setting to undo the localization that windows does when expanding wildcards.
Many users of this plugin want to gather English metrics from all windows machines, even those that have non-English UI. This is possible when not using wildcards, but before this PR it was not possible when using wildcards on non-English machines because windows localizes counters in the ExpandWildCardPath call.
There are three parts to a counter: object name, counter name, and instance. Object name and counter name are well defined but instance is machine dependent.
This PR is a workaround that lets you use wildcards in the instance name without localizing metrics. It ignores the localized names returned from ExapandWildCardPath and always uses the object and counter names in the plugin config. Users of …
=> fix: Add setting to win_perf_counters input to ignore localization

Makefile
This correctly indents and fixes the various checks for binaries that are used in the Makefile. It also corrects the markdown link binary name when it is run.
=> makefile: fix indenting, use corret markdownlint binary

config/config_test.go, plugins/parsers/collectd/parser.go, plugins/parsers/collectd/parser_test.go, plugins/parsers/csv/parser_test.go, plugins/parsers/dropwizard/parser.go, plugins/parsers/dropwizard/parser_test.go, plugins/parsers/graphite/parser.go, plugins/parsers/graphite/parser_test.go, plugins/parsers/grok/parser.go, plugins/parsers/grok/parser_test.go, plugins/parsers/influx/machine_test.go, plugins/parsers/influx/parser_test.go, plugins/parsers/json/parser.go, plugins/parsers/nagios/parser.go, plugins/parsers/nagios/parser_test.go, plugins/parsers/prometheus/parser.go, plugins/parsers/prometheus/parser_test.go, plugins/parsers/prometheusremotewrite/parser_test.go, plugins/parsers/value/parser_test.go, plugins/parsers/wavefront/element.go, plugins/parsers/wavefront/parser.go, plugins/parsers/wavefront/parser_test.go, plugins/parsers/xpath/parser.go
```
plugins/parsers/collectd/parser.go:6:2            revive       imports-blacklist: should not use the following blacklisted import: "log"
plugins/parsers/collectd/parser_test.go:218:2     ineffassign  ineffectual assignment to metrics
plugins/parsers/collectd/parser_test.go:273:2     ineffassign  ineffectual assignment to metrics
plugins/parsers/csv/parser_test.go:93:5           ineffassign  ineffectual assignment to err
plugins/parsers/csv/parser_test.go:114:5          ineffassign  ineffectual assignment to err
plugins/parsers/dropwizard/parser.go:6:2          revive       imports-blacklist: should not use the following blacklisted import: "log"
plugins/parsers/graphite/parser.go:80:4           revive       import-shadowing: The name 'metric' shadows an …
```
=> fix: Linter fixes for plugins/parsers/[a-z]*

plugins/outputs/influxdb_v2/http.go, plugins/outputs/influxdb_v2/http_test.go
The 413 error occurs when the body of a request is too large. In order
to attempt to help avoid these errors, Telegraf can split the metrics
slice in half and retry the request. If there are still errors, then the
write will then fail.
Resolves: #9744
=> feat: add retry to 413 errors with InfluxDB output

plugins/outputs/prometheus_client/prometheus_client.go, plugins/outputs/prometheus_client/prometheus_client_v1_test.go, plugins/outputs/prometheus_client/prometheus_client_v2_test.go, plugins/outputs/riemann/riemann.go, plugins/outputs/riemann_legacy/riemann.go, plugins/outputs/sensu/sensu.go, plugins/outputs/signalfx/signalfx.go, plugins/outputs/signalfx/signalfx_test.go, plugins/outputs/socket_writer/socket_writer.go, plugins/outputs/socket_writer/socket_writer_test.go, plugins/outputs/stackdriver/stackdriver.go, plugins/outputs/stackdriver/stackdriver_test.go, plugins/outputs/sumologic/sumologic.go, plugins/outputs/sumologic/sumologic_test.go, plugins/outputs/syslog/syslog.go, plugins/outputs/syslog/syslog_mapper.go, plugins/outputs/syslog/syslog_mapper_test.go, plugins/outputs/syslog/syslog_test.go, plugins/outputs/timestream/timestream.go, plugins/outputs/timestream/timestream_internal_test.go, plugins/outputs/timestream/timestream_test.go, plugins/outputs/warp10/warp10.go, plugins/outputs/wavefront/wavefront.go
```
plugins/outputs/prometheus_client/prometheus_client.go:124:21          errcheck     Error return value of `registry.Register` is not checked
plugins/outputs/prometheus_client/prometheus_client.go:126:21          errcheck     Error return value of `registry.Register` is not checked
plugins/outputs/prometheus_client/prometheus_client.go:163:10          errcheck     Error return value of `w.Write` is not checked
plugins/outputs/prometheus_client/prometheus_client_v1_test.go:20:2    revive       unexported-naming: the symbol Logger is local, its name should start with a lowercase letter
plugins/outputs/prometheus_client/prometheus_client_v1_test.go:275:2   revive       unexported-naming: the symbol Logger is local, its name should start with a lowercase …
```
=> fix: Linter fixes for plugins/outputs/[p-z]*

plugins/processors/aws/ec2/ec2.go, plugins/processors/clone/clone_test.go, plugins/processors/converter/converter.go, plugins/processors/date/date_test.go, plugins/processors/dedup/dedup_test.go, plugins/processors/defaults/defaults.go, plugins/processors/defaults/defaults_test.go, plugins/processors/enum/enum_test.go, plugins/processors/execd/execd_test.go, plugins/processors/ifname/ifname.go, plugins/processors/ifname/ifname_test.go, plugins/processors/override/override_test.go, plugins/processors/rename/rename_test.go, plugins/processors/reverse_dns/rdnscache.go, plugins/processors/reverse_dns/rdnscache_test.go, plugins/processors/reverse_dns/reversedns_test.go, plugins/processors/starlark/starlark_test.go, plugins/processors/strings/strings_test.go, plugins/processors/tag_limit/tag_limit.go, plugins/processors/tag_limit/tag_limit_test.go, plugins/processors/template/template_test.go
```
plugins/processors/aws/ec2/ec2.go:31:2                   revive       struct-tag: tag on not-exported field imdsClient
plugins/processors/aws/ec2/ec2.go:32:2                   revive       confusing-naming: Field 'imdsTags' differs only by capitalization to other field in the struct type AwsEc2Processor
plugins/processors/aws/ec2/ec2.go:33:2                   revive       struct-tag: tag on not-exported field ec2Client
plugins/processors/aws/ec2/ec2.go:34:2                   revive       struct-tag: tag on not-exported field parallel
plugins/processors/aws/ec2/ec2.go:35:2                   revive       struct-tag: tag on not-exported field instanceID
plugins/processors/clone/clone_test.go:21:46             revive       import-shadowing: The name 'metric' …
```
=> fix: Linter fixes for plugins/processors/[a-z]*

plugins/outputs/graphite/graphite.go, plugins/outputs/graphite/graphite_test.go, plugins/outputs/graylog/graylog.go, plugins/outputs/graylog/graylog_test.go, plugins/outputs/health/health.go, plugins/outputs/health/health_test.go, plugins/outputs/http/http.go, plugins/outputs/http/http_test.go, plugins/outputs/influxdb/http.go, plugins/outputs/influxdb/udp.go, plugins/outputs/influxdb/udp_test.go, plugins/outputs/influxdb_v2/http.go, plugins/outputs/influxdb_v2/http_internal_test.go, plugins/outputs/influxdb_v2/http_test.go, plugins/outputs/influxdb_v2/influxdb.go, plugins/outputs/instrumental/instrumental.go, plugins/outputs/instrumental/instrumental_test.go, plugins/outputs/kafka/kafka.go, plugins/outputs/kafka/kafka_test.go, plugins/outputs/kinesis/kinesis_test.go, plugins/outputs/librato/librato.go, plugins/outputs/loki/loki.go, plugins/outputs/loki/loki_test.go, plugins/outputs/mqtt/mqtt.go, plugins/outputs/nats/nats.go, plugins/outputs/newrelic/newrelic.go, plugins/outputs/nsq/nsq.go
```
plugins/outputs/graphite/graphite.go:116:3                revive       unhandled-error: Unhandled error in call to function conn.Close
plugins/outputs/graphite/graphite.go:136:22               errcheck     Error return value of `conn.SetReadDeadline` is not checked
plugins/outputs/graphite/graphite.go:140:3                revive       unhandled-error: Unhandled error in call to function conn.Close
plugins/outputs/graphite/graphite.go:150:3                revive       unhandled-error: Unhandled error in call to function conn.Close
plugins/outputs/graphite/graphite.go:177:12               errcheck     Error return value of `g.Connect` is not checked
plugins/outputs/graphite/graphite.go:192:31               errcheck     Error return value of `` is not …
```
=> fix: Linter fixes for plugins/outputs/[g-m]*

go.mod, plugins/inputs/raindrops/raindrops.go, plugins/inputs/raindrops/raindrops_test.go, plugins/inputs/ras/ras.go, plugins/inputs/ras/ras_test.go, plugins/inputs/redfish/redfish.go, plugins/inputs/redfish/redfish_test.go, plugins/inputs/redis/redis_test.go, plugins/inputs/rethinkdb/rethinkdb_data_test.go, plugins/inputs/rethinkdb/rethinkdb_server.go, plugins/inputs/rethinkdb/rethinkdb_server_test.go, plugins/inputs/riemann_listener/riemann_listener.go, plugins/inputs/riemann_listener/riemann_listener_test.go, plugins/inputs/snmp/snmp_test.go, plugins/inputs/udp_listener/udp_listener_test.go, plugins/inputs/webhooks/filestack/filestack_webhooks.go, plugins/inputs/webhooks/github/github_webhooks.go, plugins/inputs/webhooks/github/github_webhooks_test.go, plugins/inputs/webhooks/mandrill/mandrill_webhooks.go, plugins/inputs/webhooks/papertrail/papertrail_webhooks.go, plugins/inputs/webhooks/particle/particle_webhooks.go, plugins/inputs/webhooks/rollbar/rollbar_webhooks.go, plugins/inputs/webhooks/webhooks.go
```
plugins/inputs/raindrops/raindrops.go:119:4                                ineffassign  ineffectual assignment to iterate
plugins/inputs/ras/ras.go:26:2                                             revive       struct-tag: tag on not-exported field db
plugins/inputs/ras/ras.go:28:2                                             revive       struct-tag: tag on not-exported field latestTimestamp
plugins/inputs/ras/ras.go:29:2                                             revive       struct-tag: tag on not-exported field cpuSocketCounters
plugins/inputs/ras/ras.go:30:2                                             revive       struct-tag: tag on not-exported field serverCounters
plugins/inputs/redfish/redfish.go:179:27                                   revive …
```
=> fix: Linter fixes for plugins/inputs/[p-z]* (leftovers)

plugins/serializers/carbon2/carbon2.go, plugins/serializers/carbon2/carbon2_test.go, plugins/serializers/graphite/graphite_test.go, plugins/serializers/influx/influx.go, plugins/serializers/json/json.go, plugins/serializers/json/json_test.go, plugins/serializers/msgpack/metric.go, plugins/serializers/msgpack/metric_test.go, plugins/serializers/msgpack/msgpack_test.go, plugins/serializers/nowmetric/nowmetric.go, plugins/serializers/nowmetric/nowmetric_test.go, plugins/serializers/prometheus/collection.go, plugins/serializers/prometheus/convert.go, plugins/serializers/prometheusremotewrite/prometheusremotewrite.go, plugins/serializers/registry.go, plugins/serializers/splunkmetric/splunkmetric_test.go, plugins/serializers/wavefront/wavefront.go, plugins/serializers/wavefront/wavefront_test.go
```
plugins/serializers/carbon2/carbon2.go:68:3                                revive       unhandled-error: Unhandled error in call to function batch.Write
plugins/serializers/carbon2/carbon2.go:86:4                                revive       unhandled-error: Unhandled error in call to function m.WriteString
plugins/serializers/carbon2/carbon2.go:91:4                                revive       unhandled-error: Unhandled error in call to function m.WriteString
plugins/serializers/carbon2/carbon2.go:97:4                                revive       unhandled-error: Unhandled error in call to function m.WriteString
plugins/serializers/carbon2/carbon2.go:98:4                                revive       unhandled-error: Unhandled error in call to function …
```
=> fix: Linter fixes for plugins/serializers/[a-z]*

plugins/aggregators/basicstats/basicstats.go, plugins/aggregators/basicstats/basicstats_test.go, plugins/aggregators/derivative/derivative_test.go, plugins/aggregators/histogram/histogram_test.go, plugins/aggregators/merge/merge_test.go, plugins/aggregators/quantile/algorithms.go
```
plugins/aggregators/basicstats/basicstats.go:132:5        revive    unexported-naming: the symbol M2 is local, its name should start with a lowercase letter
plugins/aggregators/derivative/derivative_test.go:43:17   errcheck  Error return value of `derivative.Init` is not checked
plugins/aggregators/derivative/derivative_test.go:69:17   errcheck  Error return value of `derivative.Init` is not checked
plugins/aggregators/derivative/derivative_test.go:91:17   errcheck  Error return value of `derivative.Init` is not checked
plugins/aggregators/derivative/derivative_test.go:133:17  errcheck  Error return value of `derivative.Init` is not checked
plugins/aggregators/derivative/derivative_test.go:166:17  errcheck  Error return value of `derivative.Init` is not …
```
=> fix: Linter fixes for plugins/aggregators/[a-z]*

plugins/common/kafka/scram_client.go, plugins/common/logrus/hook.go, plugins/common/proxy/proxy.go, plugins/common/shim/config_test.go, plugins/common/shim/goshim.go, plugins/common/shim/goshim_test.go, plugins/common/shim/input_test.go, plugins/common/shim/logger.go, plugins/common/shim/processor_test.go, plugins/common/starlark/builtins.go, plugins/common/starlark/field_dict.go, plugins/common/starlark/metric.go, plugins/common/starlark/tag_dict.go, plugins/common/tls/config_test.go, plugins/common/tls/utils.go
```
plugins/common/kafka/scram_client.go:31:2     nakedret     naked return in func `Step` with 3 lines of code
plugins/common/proxy/proxy.go:17:3            revive       import-shadowing: The name 'url' shadows an import name
plugins/common/shim/config_test.go:16:2       revive       unhandled-error: Unhandled error in call to function os.Setenv
plugins/common/shim/config_test.go:17:2       revive       unhandled-error: Unhandled error in call to function os.Setenv
plugins/common/shim/goshim.go:87:9            revive       early-return: if c {...} else {... return } can be simplified to if !c { ... return } ...
plugins/common/shim/goshim.go:105:2           gosimple     S1000: should use for range instead of for { select {} } …
```
=> fix: Linter fixes for plugins/common/[a-z]*

plugins/inputs/bind/bind_test.go, plugins/inputs/cassandra/cassandra_test.go, plugins/inputs/cloud_pubsub/pubsub_test.go, plugins/inputs/csgo/csgo_test.go, plugins/inputs/dcos/client.go, plugins/inputs/dcos/dcos.go, plugins/inputs/dns_query/dns_query_test.go, plugins/inputs/ecs/client_test.go, plugins/inputs/ethtool/ethtool_test.go, plugins/inputs/exec/exec_test.go, plugins/inputs/execd/shim/goshim_posix.go, plugins/inputs/execd/shim/shim_test.go, plugins/inputs/graylog/graylog_test.go, plugins/inputs/hddtemp/hddtemp_test.go, plugins/inputs/http_response/http_response_test.go, plugins/inputs/httpjson/httpjson_test.go, plugins/inputs/jolokia/jolokia_test.go, plugins/inputs/jolokia2/gatherer_test.go, plugins/inputs/jolokia2/jolokia_test.go, plugins/inputs/kafka_consumer/kafka_consumer.go, plugins/inputs/kafka_consumer/kafka_consumer_test.go, plugins/inputs/minecraft/internal/rcon/rcon.go, plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_util.go
```
plugins/inputs/dcos/client.go:330:19                                       staticcheck  SA1019: jwt.StandardClaims is deprecated: Use RegisteredClaims instead for a forward-compatible way to access registered claims in a struct. 
plugins/inputs/dcos/dcos.go:240:3                                          gosimple     S1017: should replace this `if` statement with an unconditional `strings.TrimPrefix`
plugins/inputs/execd/shim/goshim_posix.go:18:3                             gosimple     S1000: should use a simple channel send/receive instead of `select` with a single case
plugins/inputs/execd/shim/shim_test.go:124:2                               revive       import-shadowing: The name 'inputs' shadows an import name …
```
=> fix: Linter fixes for plugins/inputs/[a-o]* (leftovers)

plugins/inputs/sysstat/sysstat.go
These changes stop using a hard-coded filename. This would lead to
duplicate files getting created with multiple sysstat plugins
running which results in one sysstat deleting a temp file before
the second was done reading it.
resolves #
=> fix: sysstat use CreateTemp versus hard-coded filename

plugins/inputs/cloudwatch/cloudwatch.go
resolves #10027
store pointer to metric rather than pointer to range value variable
Copied from #10123:
getDataQueries iterates over all filteredMetrics and takes the address of the metric from that list to store it in the dataQueries map. However since go seems to re-use the same object for every iteration of the loop the pointer that is taken always points to the exact same memory location. Due to this the Metric field will always contain the same pointer (and therefore value) after the for loop is done. The fix is easy and I will provide it as soon as I am done with this issue: the metric struct needs to be copied once to allocate new memory, after that the address can be taken.
=> fix #10027

internal/snmp/translate.go
resolves #
added once.Do on init as it is getting called multiple times and only needs to be called once
=> fix: sync on init to run it once for safety

Makefile
PR #10200 accidentally broke the linter rule in the Makefile by reintroducing old code. This PR fixes the issue and brings back `make lint`.
=> fix: Revert unintented corruption of the Makefile from #10200.

cmd/telegraf/telegraf_windows.go
Resolves #7876, however the issue affects telegraf agent behaviour across all plugins when telegraf runs as service, not just the execd plugin.
The current telegraf service implementation does not appear to wait for the main telegraf agent loop to gracefully finish before the main thread exits. This causes an abrupt exit and plugins do not have a chance to shut down / clean up properly (ie. outputs are not flushed, inputs with external dependencies are not closed properly).
I'm submitting this PR initially as a review - I am not sure this is the right solution to cover all scenarios. However from testing, it does work as intended under ideal scenarios - the main goroutine thread is blocked until the agent thread runs to completion.
The code changes are fairly simple. When the service stop …
=> fix: windows service - graceful shutdown of telegraf

plugins/inputs/mqtt_consumer/mqtt_consumer.go, plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
resolves #10207 
Extracting tags used to require all three fields but people may not use all three fields. Now checks if it is not there and does not error. Wrote a test with the config not having fields
=> fix: mqtt topic extracting no longer requires all three fields

plugins/inputs/prometheus/README.md
resolves #10085 
Address documentation gap when running telegraf in a k8s pod (required for k8s 1.20 and higher).
=> docs: address documentation gap when running telegraf in k8s 

plugins/inputs/zfs/README.md, plugins/inputs/zfs/zfs_linux.go, plugins/inputs/zfs/zfs_linux_test.go
partially resolves #8862 
I moved to ZFS 2.1.1 the other day and noticed my pool metrics broke. After a bit of investigation I found out that things have changed significantly under the hood. I have this diff deployed to one of my servers and can show it working:
=> fix: pool detection and metrics gathering for ZFS >= 2.1.x

plugins/outputs/graylog/graylog.go, plugins/outputs/graylog/graylog_test.go
The Graylog GELF spec[1] there are a number of fields that are part of
the spec and should *not* be prefixed by a '_'. The only fields that get
the underscore per the spec are additional fields not part of the spec.
[1] https://docs.graylog.org/docs/gelf
resolves #
=> fix: ensure graylog spec fields not prefixed with '_'

go.mod, go.sum
resolves #10140
Issue resolved by updating the [gopcua/opcua](https://github.com/gopcua/opcua) library to v0.2.3. Fix confirmed using a Siemens PLC.
=> fix: Sudden close of Telegraf caused by OPC UA input plugin

plugins/inputs/smart/README.md, plugins/inputs/smart/smart.go, plugins/inputs/smart/smart_test.go
Resolves #10149.
Resolves #8684.
Resolves #9417.
This PR fixes a two issues and provides some code clean-up:
* Updated SMART plugin input parsing to support nvme-cli v1.14+ version (output format has changed). Compatibility with older versions is preserved.
* Added concurrency configuration option to plugin config: read_method -  optionally call smartctl and nvme-cli sequentially to gather disks attributes. The reason for this change can be found here: https://github.com/influxdata/telegraf/issues/8684#issuecomment-772392280
* Linter issues fixed.
=> feat: Add SMART plugin concurrency configuration option, nvme-cli v1.14+ support and lint fixes.

internal/snmp/translate.go, plugins/inputs/snmp/snmp_test.go
This PR optimizes locking for the SNMP MIBs loading. This is necessary as the current loading of those files is completely serial. With large setups with dozends or hundreds of SNMP plugins this might take long...
@Hipska will provide measurements... :-)
=> feat: Optimize locking for SNMP MIBs loading.

cmd/telegraf/telegraf.go, docs/COMMANDS_AND_FLAGS.md, internal/usage.go
resolves #10080
In the current state loaded plugin-names will only be shown when running in production mode but **not** when running with `--test` or `--once`. The same holds for the newly added deprecation information.
This PR changes the behavior to _always_ show the loaded plugins as well as the deprecation information even when running in testing mode. Furthermore, it clarifies `--test` behavior and fixes `--test-wait` documentation.
=> fix: Print loaded plugins and deprecations for once and test

plugins/inputs/all/all.go, plugins/inputs/nomad/README.md, plugins/inputs/nomad/nomad.go, plugins/inputs/nomad/nomad_metrics.go, plugins/inputs/nomad/nomad_test.go, plugins/inputs/nomad/testdata/response_key_metrics.json
Add the input for Hashicorp Nomad.
=> feat: add nomad input plugin

plugins/outputs/elasticsearch/README.md, plugins/outputs/elasticsearch/elasticsearch.go, plugins/outputs/elasticsearch/elasticsearch_test.go
based on #9221
This fixes an issue with the elasticsearch output when dealing with metrics containing `NaN` or `inf`/`-inf` values. This PR adds an option to handle fields with those values by either do nothing, dropping or replacing the fields and field-values.
The PR is based on the unit-test provided in #9221 by @adrianlzt.
=> fix: Implement NaN and inf handling for elasticsearch output

plugins/inputs/modbus/README.md, plugins/inputs/modbus/configuration_register.go, plugins/inputs/modbus/configuration_request.go, plugins/inputs/modbus/modbus.go, plugins/inputs/modbus/modbus_test.go, plugins/inputs/modbus/request.go
This PR add the possibility to add tags per request. This is helpful in cases with multiple slave-ids per plugin where you want to add information about that sub-device.
=> feat: Modbus add per-request tags

plugins/outputs/http/README.md, plugins/outputs/http/http.go, plugins/outputs/http/http_test.go
This adds support to write to Amazon Managed Service for Prometheus.
Writing to AWS Prometheus requires queries to be signed with AWS v4 signatures, this PR adds support for that.
=> feat(http): support aws prometheus

plugins/inputs/all/all.go, plugins/inputs/vault/README.md, plugins/inputs/vault/testdata/response_key_metrics.json, plugins/inputs/vault/vault.go, plugins/inputs/vault/vault_metrics.go, plugins/inputs/vault/vault_test.go
This PR adds Hashicorp Vault input plugin. It is not so much different from Nomad input plugin here:
https://github.com/influxdata/telegraf/pull/10106
There are a couple of things that differs. An authentication/authorization through a token is mandatory and some structs have different fields.
=> feat: add Vault input plugin

agent/accumulator.go, plugins/inputs/http_listener_v2/http_listener_v2.go, plugins/inputs/http_listener_v2/http_listener_v2_test.go
Fixes: https://github.com/influxdata/telegraf/issues/10125
=> fix(http_listener_v2): fix panic on close

plugins/parsers/xpath/protocolbuffer_document.go
This PR fixes cases where a protocol-buffer definition is added multiple time to the protocol-buffer registry. This can happen with multiple parser instances using the same protocol-buffer definition, as the protocol-buffer registry is global for the process. Without this fix, the parser will fail with a panic showing that the same spec already exists.
=> fix: Handle duplicate registration of protocol-buffer files gracefully.

scripts/rpm/post-remove.sh
Restart service if it is already running and upgraded via RPM. Other services do that and Fedora guidelines suggests it - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#Systemd :
```
On upgrade, a package may only restart a service if it is running; it may not start it if it is off. Also, the service may not enable itself if it is currently disabled.
```
Fixes #3516.
=> Restart service if it is already running and upgraded via RPM

Makefile
The md5 algorithm is known to be unsafe and FIPS enabled systems do not
allow its use for file manifests. The `fpm` tool used to produce rpm
and deb packages uses md5 by default. This updates the algorithm to
sha256.
Resolves: #10270
=> fix: use sha256 for RPM digest

config/config.go, plugins/serializers/registry.go, plugins/serializers/wavefront/README.md, plugins/serializers/wavefront/wavefront.go
Maintaining the default behavior for backwards compatibility, while adding the option of preserving original metric prefixes.
resolves #7913
Users who use the Wavefront serializer who don't wish to have their metric prefixes modified may configure their output plugin in a similar way as the [Wavefront Output Plugin](https://github.com/influxdata/telegraf/blob/release-1.20/plugins/outputs/wavefront/README.md#convert-path--metric-separator).
Users may set the following configuration option: `wavefront_disable_prefix_conversion = true`
Default behavior (enabled prefix/path conversion): `prod.prefix.name.metric.name`
Configurable behavior (disabled prefix/path conversion): `prod.prefix_name.metric_name`
=> feat: Add option to disable Wavefront prefix conversion

go.mod, go.sum, plugins/outputs/wavefront/wavefront.go
resolves https://github.com/influxdata/telegraf/pull/8812
1. update wavefront-sdk-go to the most recent version
2. added flushing of the sender once it encounters an error, without it what's happening is that the connection is never cleaned and the client is constantly trying to send messages via broken connection. This means if the wavefront-proxy goes down and the connection breaks (for example when container has crushed or you are simply deploying new version of it) telegraf will never again acquire new connection and resume sending, with this fix it will
=> fix: Flush wavefront output sender on error to clean up broken connections

internal/snmp/wrapper.go
resolves #7300, resolves #4683
The snmp input always doubled the number of configured retries. Since the underlaying library handles this correctly, the reconnect in telegraf code can be removed.
=> fix: inputs.snmp to respect number of retries configured

plugins/inputs/x509_cert/x509_cert_test.go
This unit test has been flaky and occasionally times out: https://app.circleci.com/pipelines/github/influxdata/telegraf/8090/workflows/c8943f70-7ba8-4ae7-84c2-888371146352/jobs/137793/tests#failed-test-0
From the panic stack trace, I think the issue is that it hangs during the client creation because its documentation does state it can hang `Connection handshake will timeout`: https://github.com/influxdata/telegraf/blob/146fff31832e74e0db31ed6405400a3b18e9ccdd/plugins/inputs/x509_cert/x509_cert.go#L128 but it isn't obvious why it hangs. It looks like it only fails in the Mac CI job so it could just be an issue with the Mac environment.
=> fix: mark TestGatherUDPCert as an integration test

config/config.go
resolves #10285
resolves #10286
Plugins using the SetParserFunc do not initialize the parsers' `Log` field properly (nor do they call `Init()`). This PR fixes the resulting panic by doing the initialization properly.
A quick search shows that `file`, `tail` and `directory_monitor` seem to be hit by this bug.
=> fix: Fix panic in parsers due to missing Log

.circleci/config.yml, scripts/mac-signing.sh
The arm64 binary failed to get signed during the release because by default Go gives an ad hoc signature to arm64 binaries because Mac requires a signed binary with arm64 otherwise all Go binaries will fail (thread about this here: https://github.com/golang/go/issues/42684). Therefore in order to overwrite the ad hoc sig with our influxdata signature we needed to provide the flag `--force` to the codesign tool. This pull requests adds the required `--force` flag and refactored the mac signing shell script. All linter issues found by shellcheck were addressed, more information is printed out for future debugging, and I updated the script to stop changing directories and instead use absolute paths to make it easier to read.
This was tested by changing the circleci config to only build and …
=> fix: mac signing issue with arm64

internal/snmp/translate.go
resolves #10300 
Checks folder info and errors is nil to avoid panic when no mibs folder is found
=> fix: panic is no mibs folder is found

internal/snmp/translate.go, plugins/inputs/snmp/snmp_test.go
resolves #10298 
Check the index before looking it up in case there is a floating :: eg. `RFC1213-MIB::` instead of `RFC1213-MIB::sysUpTime`, also added unit test. This will now error instead of panic
=> fix: check index before assignment

plugins/inputs/logparser/logparser.go
resolves #10286
The `logparser` plugins sets-up the `grok` parser manually without initializing the logger. This leads to the panic reported in #10286. This PR fixes the resulting panic by doing the initialization properly.
=> fix: Fix panic in logparser due to missing Log.

plugins/inputs/graylog/README.md, plugins/inputs/graylog/graylog.go
resolves [#10185](https://github.com/influxdata/telegraf/issues/10185)
I added timeout, but not sure if I did it correctly in regards to a default-vaule. I have not dealt with go before.
=> feat: Add timeout-setting to Graylog-plugin

.circleci/config.yml
The circle-ci job `package-sign-mac` is using an older version of xcode that will be deprecated next year, I got an email from circle-ci giving me the heads up that in the last 4 weeks we were using a soon to be deprecated version. This pull request updates the `package-sign-mac` job to use the same executor as the test mac jobs and then also update the xcode to be the latest available. More info here: https://circleci.com/docs/2.0/testing-ios/?mkt_tok=NDg1LVpNSC02MjYAAAGBeOzfiKOY9HazYFRauJhXC2JKwmQWafZS9Xg4Us_YocgMYgZElmdRcFtqqCOkYSuPh5aP7wd4wFCG5vYxooLRzF8cDV0WagYftENvIYg4G6kd
=> chore: update mac signing job to use latest xcode

plugins/inputs/snmp/snmp_test.go, plugins/processors/reverse_dns/reversedns_test.go
There are a couple of tests that get run that reach out to external
network devices. Unit tests should not depend on functional networking
or be reaching out to random servers. The DNS server is somewhat
understandable, but the SNMP server is an unknown system that is not
owned by the development team.
Fixes: #9894
=> fix: do not require networking during tests

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
I have seen or needed to request logs from a number of bug reports. I
would like to add an explicit required section for Telegraf logs in our
bug report template.
=> chore: add logs section for bug reports

.circleci/config.yml
When a new tag is created for a release, the artifacts get created by running the `release` job. This job didn't make use of the parallel packaging builds based on arch, so it was slow, this PR removes the `release` job so that when a tag is created the same parallel packaging that happens for each pull request is used instead. The signing jobs were dependent on the `release` job, I just had them only trigger when a tag is created just like the `release` job was.
=> chore:  release packaging run in parallel

cmd/telegraf/telegraf.go
When running with `--test` you see the output
```shell
2021-12-22T12:34:09Z I! Starting Telegraf 1.22.0-f239ac32
2021-12-22T12:34:09Z I! Loaded inputs: disk
2021-12-22T12:34:09Z I! Loaded aggregators: 
2021-12-22T12:34:09Z I! Loaded processors: 
2021-12-22T12:34:09Z I! W! Outputs are not used in testing mode!
```
Please note the `I! W!` for the last line. This is due to the coloring of the output including `W!` which breaks the log detection of the type. This PR fixes the issue by not coloring the `W!`.
=> fix: Fix warning output when running with --test

plugins/outputs/stackdriver/README.md, plugins/outputs/stackdriver/counter_cache.go, plugins/outputs/stackdriver/counter_cache_test.go, plugins/outputs/stackdriver/stackdriver.go, plugins/outputs/stackdriver/stackdriver_test.go
resolves #7758 
Cumulative metrics, when posted to google cloud monitoring (nee
Stackdriver), require a TimeInterval with a start time that corresponds
to the last time at which the counter/cumulative metric was reset to
zero, cannot overlap previous intervals, and cannot be more than 25
hours in the past:
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeInterval
The stackdriver output plugin had been creating StartTimes of
`Thu Jan 1 00:00:01 UTC 1970` leading to bizarre behavior: stackdriver graphs
would reflect flatlined fractional values no matter what data telegraf
was sending, and direct queries to the projects.timeSeries.list API
would initially return the last handful of posted values but then
eventually return only `{"unit": "not_a_unit"}` for the same query,
presumably …
=> fix(outputs/stackdriver): cumulative interval start times

plugins/inputs/postgresql/README.md, plugins/inputs/postgresql/postgresql.go, plugins/inputs/postgresql/service.go, plugins/inputs/postgresql_extensible/README.md, plugins/inputs/postgresql_extensible/postgresql_extensible.go
resolves #9630 
This adds an option for disabling the use of prepared statements in the `postgresql` and `postgresql_extensible` inputs. It also prevents changing the `IsPgBouncer` flag from the configuration which was previously possible.
=> feat: add option to disable prepared statements for PostgreSQL

plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go
resolves #9427
This PR adds `exclude_root_certs` configuration option(defaults to false) to  x509_cert plugin. When `exclude_root_certs` is true then x509_cert doesn't add metrics for root (and intermediate) certs.
```
[[inputs.x509_cert]]
sources = [ "https://www.influxdata.com:443" ]
exclude_root_certs = false
```
outputs:
```
> x509_cert,common_name=sni.cloudflaressl.com,country=US,host=hidden,issuer_common_name=Cloudflare\ Inc\ ECC\ CA-3,locality=San\ Francisco,organization=Cloudflare\,\ Inc.,province=California,public_key_algorithm=ECDSA,san=www.influxdata.com\,sni.cloudflaressl.com,serial_number=f0e13e9cfe14710ee2e23d4f7255351,signature_algorithm=ECDSA-SHA256,source=https://www.influxdata.com:443,verification=valid age=13523310i,enddate=1650671999i,expiry=18012688i,startdate=16191360 …
```
=> feat: add exclude_root_certs option to x509_cert plugin

internal/snmp/translate.go
resolves #10305, resolves #10304 
Thank you @Doridian for the debugging and the solution!! 
Store modules in an array of strings and then load them in as this ensures modules are loaded in the correct order. Also added better error messaging instead of the marshal: marshalPDU error.
=> fix: snmp marshal error

plugins/inputs/all/all.go, plugins/inputs/consul_metrics/README.md, plugins/inputs/consul_metrics/consul_metrics.go, plugins/inputs/consul_metrics/consul_metrics_test.go, plugins/inputs/consul_metrics/consul_structs.go, plugins/inputs/consul_metrics/testdata/response_key_metrics.json
This PR adds an input for Consul. This one differs from the base Consul present in Telegraf. This plugin grabs Consul system metrics from the Consul metrics endpoint. Maybe the older one Consul plugin could be renamed in something like "consul_services" since it gets infos of the services registered in Consul, but in the meantime I thought that this plugin could be called with a reference to metrics. 
Any comments on this are really appreciated!
=> feat: add consul metrics input plugin

.circleci/config.yml, scripts/mac-signing.sh
New release time: `25m 40s`
Tested here: [app.circleci.com/pipelines/github/influxdata/telegraf/8324/workflows/7f088f3d-670c-44fb-8821-73f097dfbc32](https://app.circleci.com/pipelines/github/influxdata/telegraf/8324/workflows/7f088f3d-670c-44fb-8821-73f097dfbc32) 
The new job package-consolidate now will contain all the artifacts for a release: [app.circleci.com/pipelines/github/influxdata/telegraf/8324/workflows/7f088f3d-670c-44fb-8821-73f097dfbc32/jobs/141206/artifacts](https://app.circleci.com/pipelines/github/influxdata/telegraf/8324/workflows/7f088f3d-670c-44fb-8821-73f097dfbc32/jobs/141206/artifacts) 
This pull requests updates the circle-ci config so that the mac and windows signing job run at the same time and only depend on the relevant packages instead of everything. This saves …
=> chore: run release signing jobs at the same time

plugins/processors/template/README.md, plugins/processors/template/template_metric.go, plugins/processors/template/template_test.go
I was surprised the template processor didn't support `{{.}}` in a usable way.
```diff
- {0xc0000565a0}
+ test1 map[tag1:value1] map[value:1] 1257894000000000000
```
In the meantime, I also added support for `{{ .FieldList }}` and `{{ .TagList }}`.
=> feat: Add more functionality to template processor

.circleci/config.yml
The test-go-1_17-386 job... does not even test on i386. If you look at
the architecture it reports as "Architecture: x86_64" during the spin up
of the environment. There is no difference in the CLI either.
=> chore: remove "i386" test job

.circleci/config.yml
The default medium executor only is 2 cores. With these 2 cores we were
always trying to split tests into 4 parallel runs as well as passing
GOFLAGS of 8.
This ensures the MacOS, Linux (docker), and Windows executors are using
systems with 4 cores and that we pass parallel values of 4.
=> chore: use 4 cores on linux systems

plugins/inputs/all/all.go, plugins/inputs/mock/README.md, plugins/inputs/mock/mock.go, plugins/inputs/mock/mock_test.go
Will generate random data based on a variety of algorithms. Options
include random, stepwise, sine-wave, and stock-like data values.
Resolves: #9749
=> feat: add mock input plugin

plugins/inputs/snmp_trap/README.md, plugins/inputs/snmp_trap/snmp_trap.go
resolves #
Timeout was deprecated in 1.20.0 as we now call `gosmi` instead of `snmptranslate` but it was not documented.
=> chore: document deprecation of timeout

plugins/parsers/csv/parser.go
The telegraf binary currently does not include any timezone data. While
this data is usually readily available in linux systems it is not
available to a go binary in Windows.
Fixes: #8756
=> fix: empty import tzdata for Windows binaries

cmd/telegraf/telegraf.go, docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum, scripts/telegraf.service
- [-] Updated associated README.md.
- [-] Wrote appropriate unit tests.
resolves #7485
Right now telegraf is not specifying Type in [Service] in its systemd service.
When starting telegraf this means that as soon as it's forked systemd
assumes it's running, even though it will stop just milliseconds after.
If Type is changed to Notify the unit will never be marked as Active
since telegraf is not telling systemd it's up.
This patch adds that support and opens up the possibility to convert the
service to a Notify type instead of Simple.
Before:
$ systemd-run --user --service-type=simple  ./telegraf --config /dev/null
Running as unit: run-rdf62c01eb6834b3fa5e96cc8c2816b87.service
$ systemd-run --user --service-type=notify  ./telegraf --config
/dev/null
Job for …
=> feat: add systemd notify support

plugins/inputs/disk/disk.go, plugins/inputs/disk/disk_test.go, plugins/inputs/disk/testdata/issue_10297/1/mountinfo, plugins/inputs/disk/testdata/success/1/mountinfo, plugins/inputs/system/ps.go
resolves #10297
This PR fixes the missing disks when trying to run telegraf from within a container.
=> fix: Fix missing disks in container

plugins/outputs/amqp/amqp.go
When writing errors, such as occasional writing timeouts, close the last connection to avoid connection leaks.
=> fix(outputs/amqp): Close the last connection when writing error to avoid connection leaks

plugins/outputs/timestream/timestream.go, plugins/outputs/timestream/timestream_test.go
=> fix: Fix batching logic with write records, introduce concurrent requests

go.mod, go.sum, plugins/outputs/elasticsearch/README.md, plugins/outputs/elasticsearch/elasticsearch.go, plugins/outputs/elasticsearch/elasticsearch_test.go
resolves #82333
Added a configuration to the Elasticsearch output to allow a bearer token to be passed along in the authorization header.
=> feat: add bearer token support to elasticsearch output

plugins/inputs/http/http.go, plugins/inputs/http/http_test.go
Even if the http body was empty, the current method will create an
io.ReadCloser and send that to the http request. This was causing a 502
error from a service. Ensuring that the empty body is actually empty
prevents the server side error message.
Add log fixture to tests to aid in debugging.
Fixes: #10386
=> fix: send actual empty http body when no body is set

plugins/common/cookie/cookie.go, plugins/common/cookie/cookie_test.go, plugins/inputs/http/README.md, plugins/inputs/http/http.go, plugins/outputs/http/README.md, plugins/outputs/http/http.go
Signed-off-by: Conor Evans <coevans@tcd.ie>
resolves #10061
=> feat: support headers for http plugin with cookie auth

plugins/inputs/opcua/README.md, plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go
resolves #8826
Added `[inputs.opcua.workarounds]` similar to the modbus plugin.
=> fix: Accept non-standard OPC UA OK status by implementing a configurable workaround

.circleci/config.yml
Possibly fix to prevent workspace attach issues on nightlies
=> fix: do not save cache on i386 builds

plugins/inputs/execd/execd.go
The Prometheus parser currently will return a text format parsing error
due to an unexpected end of input stream. This is due to there not being
a new line (e.g. \n) at the end of the string. Once added, the execd
works as expected.
Fixes: #10460
=> fix: add newline in execd for prometheus parsing

plugins/parsers/nagios/parser.go, plugins/parsers/nagios/parser_test.go
resolves #10472
The real error will now be returned by the "getExitCode" function instead of an placeholder.
With these changes all real errors message will be written to the log. Problems can be debuged properly.
=> fix(persers.nagios): nagios parser now uses real error for logging

plugins/inputs/opcua/opcua_client.go
resolves #10477
Fixed duplicate addition of fields by deleting the offending line.
=> fix: remove duplicate addition of fields

plugins/inputs/logparser/README.md
The plugin is deprecated, but resolves a community reported issue that
would improve the docs.
Fixes: #9065
=> fix: add comment to logparser

plugins/inputs/graylog/README.md, plugins/inputs/graylog/graylog.go
Primarily fix a few URLs and change the port to 9000
author: @BenoitPoulet
=> fix: graylog readme to use graylog 3 URLs

plugins/inputs/ipset/ipset.go
During init check for the ipset command before running. Prevents a panic from occurring after start.
Resolves: #7228
=> fix: check for ipset command during init

plugins/parsers/xpath/README.md
resolves #
Removes a link that leads to a 404 (I went through the file history and it never linked to anything that exsisted) and removes the section of the table as that was the only entry
=> fix: typo in docs

config/config.go, docs/developers/DEPRECATION.md, plugins/inputs/amqp_consumer/amqp_consumer.go
This PR updates the developers deprecation readme. It furthermore adds code to automatically print the deprecation info for sample-configs, taking away that monkey-work from the developer.
=> docs: Update deprecation readme

plugins/inputs/docker/docker_test.go, plugins/inputs/docker/stats_helpers.go
resolve: #10518
This updates the Docker input plugin memory statistics. Specifically, the `usage` measurement in `docker_container_mem` is updated so that it will match the value given by the Docker CLI tool version 20.10+.  The calculation used in the CLI tool can be seen [here](https://github.com/docker/cli/blob/6e2838e18645e06f3e4b6c5143898ccc44063e3b/cli/command/container/stats_helpers.go#L227-L249). In Docker 20.10, the memory stats available changed and the `cache` field is no longer present. Instead, depending on the version of cgroups used, either `total_inactive_file` or `inactive_file` will be present.
I've added a test of this functionality. The values chosen are odd because in order for the test to pass, the percentage calculation had to match exactly despite floating-point …
=> fix: update docker mem usage to match latest docker CLI

cmd/telegraf/telegraf.go
resolve: #9120
As stated in the issue `I! Starting Telegraf <version>` doesn't get written to a logfile if you specify one in the config, in the code this was happening because the logger gets setup after this log call is called so simply moving it after setup resolves this issue.
=> fix: move "Starting Telegraf" log

EXTERNAL_PLUGINS.md
As suggested by @sspaink in https://github.com/influxdata/telegraf/issues/5785 I added two of my plugins to the list.
But this leads me to a question. At [docs/EXTERNAL_PLUGINS.md](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) is a description what an external plugin should be. An important thing seems to be that it uses `execd`. This would mean that scripts in `bash`, `python`, `..` which depend on `exec` and a predefined interval are out of scope and not called as an `external plugin`. It seems like [EXTERNAL_PLUGINS.md](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md) was created to link plugins that are working with `execd` and are mostly binary files. Even if there are some other scripts the definition ​feels a bit wrong there. …
=> docs: add apt and knot to EXTERNAL_PLUGINS.md

.circleci/config.yml
When the macOS environment is attached to the package-consolidate
CircleCI job, there are two new files. These dot-underscore files are
hidden files for macOS that store metadata about files. These files are
not required and are not useful for our release process. In fact, they cause
issues when they show up.
This will remove any of these dot-underscore files before artifacts are
uploaded to CircleCI.
=> fix: remove dotfile artifacts

plugins/inputs/file/file.go, plugins/inputs/file/file_test.go, plugins/inputs/http/http.go, plugins/inputs/http/http_test.go
resolves #10366
Stateful parsers, like CSV, require a reset of the parser state for each new data chunk. In case of the CSV parser a reset is required whenever a chunk of data starts from the beginning with a header, skipped rows etc. To reset the parser we construct a new one for every new file in the file-plugin. More plugins might need to follow.
=> fix: Statefull parser handling

cmd/telegraf/telegraf.go, cmd/telegraf/telegraf_windows.go, docs/WINDOWS_SERVICE.md, internal/usage_windows.go
resolves #10522
The Windows service library used contains a list of known key value options: https://github.com/kardianos/service/blob/5c08916379a92cb1806764e911af33c55762a753/service.go#L190. I added the `--service-auto-restart` and `--service-restart-delay` flags to make the following options available:
```
//    - OnFailure               string ("restart" )   - Action to perform on service failure. (restart | reboot | noaction)
//    - OnFailureDelayDuration  string ( "1s" )       - Delay before restarting the service, time.Duration string.
```
=> feat: Add autorestart and restartdelay flags to Windows service

plugins/inputs/win_perf_counters/README.md, plugins/inputs/win_perf_counters/win_perf_counters.go
=> style: Add deprecated warning and version to win_perf_counters option

plugins/aggregators/histogram/histogram.go, plugins/aggregators/histogram/histogram_test.go
resolves #10517
Add an `expiration_interval` to aggregator histogram config. Setting this property allows deleting from cache outdated histogram older than `expiration_interval`.
=> feat: Histogram aggregator metric expiration

go.mod, go.sum
<!-- Finally, include a summary of the code change itself. This
description should tell reviewers how the issues were resolved.
azure-kusto-version until 0.5.2 had a critical bug that makes it impossible to ingest to two different clusters with two different ingestors.
This PR bumps the version to the fixed one.
=> fix: bump github.com/Azure/azure-kusto-go from 0.5.0 to 0.5.2

plugins/inputs/gnmi/README.md, plugins/inputs/gnmi/gnmi.go, plugins/inputs/gnmi/gnmi_test.go
Closes #7462 
Add the ability to specify gNMI subscriptions to be tag-only, storing them for application to other subscriptions with the exact same tagged "name".  The primary application of the author is to apply interface description tags to all other interface metrics, to ease search in Influx.
I am extremely open to suggestion on improvement for either the memory storage of the tags, or alternatives for additional aliasing of the dynamic tag naming.
=> feat: Add dynamic tagging to gnmi plugin

plugins/inputs/opcua/opcua_client.go, plugins/inputs/opcua/opcua_client_test.go
resolve: [#2932](https://github.com/influxdata/EAR/issues/2932) (this is an internal issue)
This pull request adds metric name and tags to the "status no OK" error logs. Copied the same output format as  validateOPCTags is using https://github.com/influxdata/telegraf/blob/opcuaimprovedlog/plugins/inputs/opcua/opcua_client.go#L394-L395.
=> fix(inputs.opcua): add more data to error log

.circleci/config.yml, Makefile, scripts/ci-1.17.docker, scripts/installgo_mac.sh, scripts/installgo_windows.sh
Release notes: https://go.dev/doc/devel/release
=> chore: update CI go to 1.17.6

scripts/installgo_windows.sh
We shouldn't break everyone's CI because the Windows image got updated and has a newer version of Go. This will allow a downgrade to occur.
=> chore: allow downgrade of go version in windows script

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/mongodb_data.go, plugins/inputs/mongodb/mongostat.go
resolves #10624
Allow to retrieve informations about fs size for mongo server.
I try to implement test in `mongostat_test.go` and `mongodb_data_test.go` but no success
=> feat(mongodb): add FsTotalSize and FsUsedSize informations

config/config_test.go
Will fix CI error in #10083.
The current parser tests in `config/config_test` is using `require.EqualValues()` which also checks on unexported fields of the parser to test. This leads to problems due to internal states (see [CI error in #10083](https://app.circleci.com/pipelines/github/influxdata/telegraf/8694/workflows/3f4b1bdd-64ff-4ced-956a-be6ebe4aa439/jobs/146415) or `xpath_*`) which cannot be ignored with the mentioned function.
As we do not want to check internal states anyway (but only check if the parsers are equally configured) we change the comparision in this PR to use `github.com/google/go-cmp/cmp`. By this we can flexibly ignore certain fields. By default, both unexported fields and `telegraf.Logger` are ignored. Additional fields can be specified by name in the `override` …
=> fix: Improve parser tests by using go-cmp/cmp

plugins/inputs/win_perf_counters/README.md, plugins/inputs/win_perf_counters/pdh.go, plugins/inputs/win_perf_counters/pdh_386.go, plugins/inputs/win_perf_counters/pdh_amd64.go, plugins/inputs/win_perf_counters/performance_query.go, plugins/inputs/win_perf_counters/win_perf_counters.go, plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go, plugins/inputs/win_perf_counters/win_perf_counters_test.go
Added support for reading raw values of performance counters.
Fixes #5198
=> feat(win_perf_counters): Added support for reading raw values

docs/LICENSE_OF_DEPENDENCIES.md
PR didn't run the full CI for some reason: https://github.com/influxdata/telegraf/pull/10589
Which led to the licenses doc to get outdated failing `make check-deps`, this adds the missing dependencies.
=> fix: license doc outdated causing CI failure

.circleci/config.yml
resolve: #8459
The `-race` flag wasn't working on the Windows CI job because GCC was missing, so I've updated the circle-ci config to install mingw. Also when migrating to use gotestsum to parallelize the builds the `-race` was accidentally dropped from the linux tests as well, now its been added back.
=> chore: add -race flag to go tests

plugins/inputs/deprecations.go
`plugins/inputs/http_listener_v2` is the recommended plugin for general purpose http listening input. It was added to the deprecated plugins list in df6bf48f8d by mistake. This PR removes it from the list.
=> fix: Revert deprecation of http_listener_v2

plugins/outputs/amqp/amqp.go
Recently added the logic to close the connection, but in some cases it
appears that the connection is already nil.
Fixes: #10634
=> fix: check for nil client before closing

agent/agent.go, agent/tick.go, agent/tick_test.go, config/config.go, docs/CONFIGURATION.md, models/running_input.go
resolves #1319
resolves #10406 
related to #10530
This PR addresses a long standing feature-request to be able to define an offset from the collection interval. This can be helpful in order to manually schedule data collection between agents, if the global option is used with multiple agents, or, if the plugin option is used, between plugins. The new `collection_offset` allows to define a time offset from the (rounded and unaligned) collection time. The option is valid in either the agent section or in any input-plugin section (as other interval parameters).
=> feat: Collection offset implementation

plugins/outputs/elasticsearch/README.md
=> docs: override reported OpenSearch version

go.mod, go.sum, plugins/common/proxy/socks5.go, plugins/common/proxy/socks5_test.go, plugins/outputs/kafka/README.md, plugins/outputs/kafka/kafka.go
=> feat: add socks5 proxy support to kafka

plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
Promethues sample timestamp is in milliseconds, and `time.Unit()` first param receive time in seconds.
=> fix(prometheusremotewrite): use wrong timestamp unit

plugins/inputs/vsphere/METRICS.md
=> docs: update VMWare doc links

go.mod, go.sum, internal/snmp/testdata/loadMibsFromPath/root/symlink, internal/snmp/translate.go, internal/snmp/translate_test.go, plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go, plugins/inputs/snmp_trap/snmp_trap.go
resolves #10548, resolves #10590, resolves #10603
The root folder was getting appended every time we loaded another folder, making root get appended exponential times. This pr should ensure that each folder only gets loaded once by checking symlinks and if it is a directory.
=> fix: ensure folders do not get loaded more than once

agent/accumulator.go, agent/agent.go, internal/http.go, logger/logger.go, logger/logger_test.go, models/log.go, models/running_aggregator.go, plugins/common/shim/example/cmd/main.go, testutil/metric.go, testutil/tls.go
```
agent/accumulator.go:12:13                                              revive       import-shadowing: The name 'metric' shadows an import name
agent/agent.go:26:15                                                    revive       import-shadowing: The name 'config' shadows an import name
internal/http.go:123:9                                                  revive       import-shadowing: The name 'net' shadows an import name
logger/logger.go:113:19                                                 revive       import-shadowing: The name 'config' shadows an import name
logger/logger.go:120:43                                                 revive       import-shadowing: The name 'config' shadows an import name
logger/logger.go:149:19 …
```
=> fix: Linter fixes for "import-shadowing: The name '...' shadows an import name"

plugins/processors/dedup/dedup.go, plugins/processors/dedup/dedup_test.go
Instead of swapping indexes, use the filter pattern to make sure all
items are properly iterated through.
This manifested with randomly duplicate data, or sometimes weird hangs in processing.
Added a unit test to cover the multiple input metrics test case, as it seems it hadn't been covered yet.
=> fix(dedup): Modifying slice while iterating is dangerous

plugins/outputs/groundwork/groundwork.go
To avoid GroundWork to invent a value like LastCheckTime + 5 minutes
=> fix(outputs.groundwork): Set NextCheckTime to LastCheckTime 

plugins/inputs/openweathermap/README.md, plugins/inputs/openweathermap/openweathermap.go, plugins/inputs/openweathermap/openweathermap_test.go
resolves #10695 
Added the necessary float data structure to hold the feels_like temperature data. 
Updated the test case to include the data during tests.
Ran locally and updated the README.md to include the actual data from the API.
=> fix: openweathermap add feels_like field

config/config.go, config/config_test.go
This PR was inspired by: https://community.influxdata.com/t/telegraf-config-failing-to-load/23905/3
Currently, if an environment variable inside a config isn't found it is skipped and not replaced and the user ends up with a misleading error `invalid TOML syntax`. TOML doesn't natively support non quoted environment variables (e.g. just ${INFLUX_SKIP_DATABASE_CREATION}) therefore it can't parse it. I thought it would be more helpful to track all configured environment variables not found and report it to the user like so: 
```sh
2022-02-18T21:55:01Z E! [telegraf] Error running agent: Error loading config file telegraf.conf: Error parsing data: failed to find the configured environment variables:INFLUX_URL INFLUX_SKIP_DATABASE_CREATION INFLUX_PASSWORD 
```
=> fix: error msg for missing env variables in config

plugins/outputs/websocket/README.md, plugins/outputs/websocket/websocket.go
Added socks5 proxy support to the websocket output plugin. No Issue was created for this.
=> feat: socks5 proxy support for websocket

plugins/inputs/memcached/README.md, plugins/inputs/memcached/memcached.go
This change adds support for client TLS origination to memcached, leveraging the common TLS plugin library in `plugins/common/tls`. I also added `toml` struct tags to make the TOML parsing behavior explicit, which seems to be more in line with other plugins as well.
Test and verification:
Collection with server TLS enabled, using the memcached test fixture certificates in [`t/server_crt.pem` et al.](https://github.com/memcached/memcached/blob/e9b28fe92898dda891bc78fb901ba15f834a24cd/t/server_crt.pem):
```
[[inputs.memcached]]
enable_tls = true
tls_ca = "/path/to/memcached/t/cacert.pem"
tls_cert = "/path/to/memcached/t/client_crt.pem"
tls_key = "/path/to/memcached/t/client_key.pem"
tls_server_name = "test.com"
```
```
$ ./memcached --enable-ssl --extended …
```
=> feat(inputs/memcached): Support client TLS origination to memcached

go.mod, go.sum, plugins/inputs/aerospike/README.md, plugins/inputs/aerospike/aerospike.go, plugins/inputs/aerospike/aerospike_test.go
resolves #10315 
The changes are listed below:
- Upgrading aerospike go client to 5.7.0.
- Removing SSL support from the aerospike telegraf plugin. `enable_ssl` option would no longer be available.
- Added an option in the aerospike input plugin config as `tls_name`, which should be set to the value of [`tls-name`](https://docs.aerospike.com/reference/configuration#tls-name) under `tls{}` stanza in the aerospike.conf if present.
- Fixed the value of `node_name` tag to return [Node.GetName()](https://pkg.go.dev/github.com/aerospike/aerospike-client-go/v5#Node.GetName) which now correctly returns node name, instead of the host:port which was incorrect.
=> feat: Bump github.com/aerospike/aerospike-client-go from 1.27.0 to 5.7.0

plugins/inputs/system/ps.go
=> fix: Remove verbose logging from disk input plugin

.golangci.yml, config/config.go
```
config/config.go:459:2      staticcheck  SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead
config/config.go:470:5      staticcheck  SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead
config/config.go:474:4      staticcheck  SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead
config/config.go:492:5      staticcheck  SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead
config/config.go:496:4      staticcheck  SA1006: printf-style function with dynamic format string and no further …
```
=> fix: Linter fixes for config/config.go

config/config.go, config/config_test.go, config/testdata/single_plugin_env_vars.toml
Resolve: https://github.com/influxdata/telegraf/issues/10723
As suggested in: https://github.com/influxdata/telegraf/pull/10726#issuecomment-1048921716 better to revert this change for now and create a new PR to address unset environment variables that takes into account comments.
=> fix: Revert "fix: error msg for missing env variables in config (#10681)"

plugins/inputs/http/http_test.go, plugins/parsers/csv/README.md, plugins/parsers/csv/parser.go, plugins/parsers/csv/parser_test.go, plugins/parsers/registry.go
resolves #10079
Added support to parse metadata for the CSV parser plugin.
=> feat(parsers/csv): Add metadata support to CSV parser plugin

plugins/aggregators/histogram/README.md, plugins/aggregators/histogram/histogram.go, plugins/aggregators/histogram/histogram_test.go
resolves #10043
Add a boolean flag to aggregator histogram config. Setting this flag to true allows pushing to output only updated histogram values and control metrics expiration inside output plugins. It allows increasing performance when there are a lot of metrics (for example during collect metrics from mobile devices as described in https://github.com/influxdata/telegraf/issues/10517)
=> fix: Histogram Aggregator break metric expiration inside Prometheus client output

internal/snmp/translate.go
Log the error when loading mibs. This will give us more information in logs and hopefully clear up why users are seeing the "Couldn't stat target" log message.
=> fix: log err when loading mibs

plugins/inputs/statsd/README.md, plugins/inputs/statsd/statsd.go, plugins/inputs/statsd/statsd_test.go
Per upstream, statsd does sanitization of names. This takes this same
set of rules and applies it when statsd is parsing out names.
Without these, the names were getting garbled or partially dropped.
Fixes: #10372
Fixes: #5662
=> fix: sanitize stasd names

config/config.go
=> docs: better specify agent precision is integer + unit

plugins/outputs/sql/README.md, plugins/outputs/sql/sql.go, plugins/outputs/sql/sql_test.go, plugins/outputs/sql/testdata/clickhouse/expected.txt, plugins/outputs/sql/testdata/mariadb/expected.sql, plugins/outputs/sql/testdata/postgres/expected.sql
=> fix: sql unsigned settings

etc/telegraf.conf, etc/telegraf_windows.conf, plugins/inputs/ravendb/README.md, plugins/inputs/ravendb/ravendb.go
Minor: Change default URI scheme from https to http. As default server uses http, not https. 
resolves #
=> change uri scheme for default RavenDB configuration (#10765)

plugins/inputs/docker/docker.go, plugins/inputs/docker/docker_test.go
Resolve: https://github.com/influxdata/telegraf/issues/8570
The field `tasks_desired` could change between int and uint64, which caused the issue `already exists as type` in #8570. Keeping it as uint64 seems like the best option because `tasksNoShutdown` which was an int that only increments up and should never be negative.
=> fix(inputs.docker): keep field type of tasks_desired the same

etc/telegraf.conf, etc/telegraf_windows.conf, plugins/outputs/newrelic/README.md, plugins/outputs/newrelic/newrelic.go
There has been some confusion about the kind of New Relic key to use in the NR output plugin config.  
This code attempts to clear it up some.  Note that the actual parameter name uses the term "insights_key" which was an older term.  For this PR we have simply updated the phrasing.   I am considering a PR in the near future to actually rename the parameter or preferably use some kind of alias if it's possible.
=> docs: Improve language related to the New Relic license key.

config/types.go, config/types_test.go
=> fix: update parsing logic of config.Duration

internal/snmp/translate.go, internal/snmp/translate_test.go
related #10674
This PR changes handling of symlinks to files when loading MIBs. Previously it would try to evaluate the parent directory's path as a symlink instead of the symlink's path.
This change should remove many "Couldn't stat target" warnings in logs like the following:
```
2022-02-17T18:06:33Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
```
=> fix: SNMP MIBs: use the correct path when evaluating symlink

plugins/inputs/nfsclient/README.md, plugins/inputs/nfsclient/nfsclient.go, plugins/inputs/nfsclient/nfsclient_test.go
This field will provide the calculation for round-trip time per
operation. The current rtt field is the total number of time taken,
which is not very useful.
=> feat: add new rtt per op field to nfsclient

config/config.go, config/types.go, config/types_test.go
In #10803, precision parsing was made more strict so that incorrect
values would be caught. The default precision value however is not
correct as an empty string.
fixes: #10813
=> fix: update the precision parameter default value

agent/agent.go, config/config.go, internal/snmp/config.go, internal/snmp/translator.go, plugins/inputs/snmp/README.md, plugins/inputs/snmp/gosmi.go, plugins/inputs/snmp/gosmi_test.go, plugins/inputs/snmp/netsnmp.go, plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_mocks_generate.go, plugins/inputs/snmp/snmp_mocks_test.go, plugins/inputs/snmp/snmp_test.go, plugins/inputs/snmp_trap/README.md, plugins/inputs/snmp_trap/gosmi.go, plugins/inputs/snmp_trap/netsnmp.go, plugins/inputs/snmp_trap/snmp_trap.go, plugins/inputs/snmp_trap/snmp_trap_test.go, plugins/processors/ifname/README.md, plugins/processors/ifname/ifname.go, plugins/processors/ifname/ifname_test.go
This PR adds back the ability to call netsnmp's snmptranslate and snmptable to translate names and OIDs.
Telegraf recently switched translation to use gosmi to address performance concerns. (see #9518, released in 1.21.0) This resulted in translation not being backward compatible with the previous release, 1.20.4.
This PR makes gosmi translation a config option, but defaults to netsnmp translation.
Users of 1.21.0 and later who have transitioned to gosmi will need to set `translator = "gosmi"` in their agent config. Users who have not upgraded past 1.20.4 in order to keep using netsnmp translation should be able to use this without config changes.
=> fix: Add option to select translator

plugins/inputs/consul_metrics/README.md
Wrong input pointing in toml configuration in README file.
Fixes https://github.com/influxdata/telegraf/issues/10870.
=> fix: consul_metrics input plugin docs

CHANGELOG.md, agent/agent.go, config/config.go, docs/CONFIGURATION.md
Change the name of snmp translator setting. This change hasn't been released yet so it's still safe to change. "translator" was too generic and "snmp_translator" is more clear.
Update the sample config and add a section in the configuration documentation.
Add a section to the changelog to draw attention to the new setting since it allows users to select one of the two previous defaults, and requires those who want to use gosmi to add the setting manually to their config file.
=> fix: Change name of snmp translator setting

plugins/inputs/cloud_pubsub_push/pubsub_push_test.go, plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry_test.go, plugins/inputs/uwsgi/uwsgi_test.go, plugins/outputs/signalfx/signalfx_test.go, plugins/processors/topk/topk_test.go
There are a number of tests with hard-coded sleep or timeouts that are
larger than they need to be. This reduces those times across the board
so that one test is not sitting and waiting any longer than it needs to
be.
=> chore: reduce timeouts and sleeps

.circleci/config.yml
The parallelism option will launch N systems and split the unit tests
across them. However, the entire test process involves a number of other
items: downloading go deps, make check, launching the VM/container
itself. These other items generally take longer than running the
tests themselves and as a result, other than spending more money on
CircleCI we are not getting a benefit from this option.
Furthermore, in order to start collecting coverage information it is
easier to not have this all split up.
=> chore: remove CircleCI parallelism

plugins/inputs/intel_pmu/intel_pmu_test.go
The makeEvents call is very expensive in terms of both memory usage and
compute time. In order to reduce pressure on a system during tests, this
reduces the number of events, but increases the number of total cores.
=> chore: fix slow running intel-pmu test

plugins/outputs/http/http_test.go, plugins/outputs/loki/loki_test.go
The HTTP 103 response code seems to add an artificial delay to tests
while the code waits for further details. As the point of these tests is
to handle any 100 HTTP code, this moves from 103 to 101.
=> chore: switch HTTP 100 test cases

internal/rotate/file_writer_test.go
The tests were hard-coding second-long sleeps. Where these can
safely be reduced down to milliseconds, make that change, otherwise
do not run the test with short.
=> chore: update slow file rotate tests

internal/process/process_test.go
This test takes multiple seconds to wait for the process group to stop.
This adds the skip if short flag given the length this test takes.
=> chore: remove slow process test

plugins/processors/topk/README.md, plugins/processors/topk/topk.go
The k and fields parameters in topk together determine the total number
of results. The current docs were not clear that there was a
relationship between the two that resulted in more than k results from
appearing.
Fixes: #10725
=> docs: clarify the k and fields topk params

plugins/outputs/azure_monitor/azure_monitor.go
=> fix: include body in error message

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
It's usually more readable when done so as user don't take into account the special characters in the logs will be converted to markup.
=> fix: Set log as text block in but reports

plugins/inputs/vsphere/endpoint.go
This message is very verbose and causes a lot of extra messages to get
printed out as-is. Having it can be helpful in debugging when a metric
does not show up, but it is not useful for general usage. This changes
the message to only show up with debug enabled.
Fixes: #10350
=> fix: update vsphere info message to debug

plugins/inputs/zfs/zfs_linux.go, plugins/inputs/zfs/zfs_linux_test.go
If a ZFS pool has multiple datasets it will show up in the ZFS pool list
that Telegraf maintains. When trying to produce the ZFS pools tag this
will result in a pool name showing up more than once. This creates a
unique set of pool names for the tag.
Fixes: #10837
=> fix: redundant zfs pool tag

config/config.go, config/types.go
The unit of 'd' is not a valid time.Duration unit. Due to the more
strict parsing of durations, this is now correctly failing. Previously
using a value of '1d' would fail silently. If a user wishes to use a
value of days, they need to convert to hours and use '24h' for example
of one day.
Fixes: #10882
=> fix: default value for logfile rotation interval

plugins/inputs/lustre2/README.md, plugins/inputs/lustre2/lustre2.go, plugins/inputs/lustre2/lustre2_test.go
When reading stats from files /proc/fs/lustre/<target_type>/<target_name>/exports/<client_nid>/stats
previously the target was not tagged, but  the client NID was tagged as 'name' and the metrics
from multiple targets were also 'mixed up' (not aggregated).
With this fix, the target name will be tagged as 'name' and the client NID will be tagged as 'client'.
The code detects whether there is an '/exports/' directory in the stat file path, 
and will create the tags correctly in that case.
=> feat: In Lustre input plugin, support collecting per-client stats.

plugins/outputs/elasticsearch/README.md, plugins/outputs/elasticsearch/elasticsearch.go, plugins/outputs/elasticsearch/elasticsearch_test.go
resolves #10852
The changes are listed below:
- Added healthcheck timeout for ES client: [SetHealthcheckTimeout](https://github.com/olivere/elastic/blob/v6.2.37/client.go#L607), setting the default healthcheck timeout to 1s
=> feat: (outputs.elasticsearch) Add healthcheck timeout

plugins/inputs/sqlserver/azuresqldbqueries.go, plugins/inputs/sqlserver/azuresqlmanagedqueries.go, plugins/inputs/sqlserver/sqlserverqueries.go
1. unified and fixed inconsistencies for sql*Requests queries for all types of input (on-prem, sqlDB and sqlMI)
- removed #blockingSessions and incorporated in the main query with a COUNT() OVER(), in order to avoid inconsistencies between the main query and the snapshot saved in the temp table.
- standardized the retrieval of session_db_name, blocking_session_id and request_id
2. added more precise version check for query "sqlServerDatabaseIO" in sqlserverqueries.go
Fixes: #10741
=> fix: inconsistencies in sql*Requests queries

.github/workflows/golangci-lint.yml, Makefile
The golanci-lint action recently updated to require an additional step: `actions/setup-go@v2`, documented in the main README.md: https://github.com/golangci/golangci-lint-action. This seems like it might have been a breaking change because the linter is behaving strangely (reporting issues were there aren't any, or ignoring issues) not obvious if this is directly related, but seems like the reason.
This PR adds this missing step to our github configuration, updates the version of golangci-lint to v1.45.2 as well.
=> chore: add actions/setup-go@v2 to linter config

plugins/aggregators/basicstats/README.md, plugins/aggregators/basicstats/basicstats.go, plugins/aggregators/basicstats/basicstats_sample_config.go, plugins/aggregators/derivative/README.md, plugins/aggregators/derivative/derivative.go, plugins/aggregators/derivative/derivative_sample_config.go, plugins/aggregators/final/README.md, plugins/aggregators/final/final.go, plugins/aggregators/final/final_sample_config.go, plugins/aggregators/histogram/histogram.go, plugins/aggregators/histogram/histogram_sample_config.go, plugins/aggregators/merge/README.md, plugins/aggregators/merge/merge.go, plugins/aggregators/merge/merge_sample_config.go, plugins/aggregators/merge/merge_test.go, plugins/aggregators/minmax/minmax.go, plugins/aggregators/minmax/minmax_sample_config.go, plugins/aggregators/quantile/README.md, plugins/aggregators/quantile/quantile.go, plugins/aggregators/quantile/quantile_sample_config.go, plugins/aggregators/starlark/README.md, plugins/aggregators/starlark/starlark.go, plugins/aggregators/starlark/starlark_sample_config.go, plugins/aggregators/valuecounter/README.md, plugins/aggregators/valuecounter/valuecounter.go, plugins/aggregators/valuecounter/valuecounter_sample_config.go
Depends on: https://github.com/influxdata/telegraf/pull/10886
This migrates all **aggregator plugins** to follow the new sample config format introduced in #10886.
This is a separate PR in an attempt to keep #10886 smaller and more easily reviewable.
The CI is expected to fail until #10886 is merged
=> feat: migrate aggregator plugins to new sample config format

plugins/inputs/prometheus/README.md, plugins/inputs/prometheus/kubernetes.go, plugins/inputs/prometheus/prometheus.go
Resolves:
#10148, #10878 and #10928
Issues:
- telegraf stops monitoring pods after 30 minutes 
- high CPU utilization
watcher has a default timeout of 30 minutes, leading to the above mentioned problems.
Fix:
- Replaced watcher with informer. Actions that are triggered for "add", "update/modify" and "delete" events remain same.
- Added a new config cache_refresh_interval that is used by informer to rebase its cache.
=> fix(inputs.prometheus): moved from watcher to informer

plugins/outputs/influxdb_v2/influxdb_v2.go
When sending metrics to all servers fails the last error message is also
sent to the agent to report. This results in duplicate error messages.
Instead of printing the last error message a second time, report that
sending to all configured servers failed.
Fixes: #10956
=> fix: update influxdb_v2 error message

plugins/inputs/conntrack/README.md, plugins/inputs/example/README.md, plugins/inputs/httpjson/README.md, plugins/inputs/influxdb_listener/README.md, plugins/inputs/mqtt_consumer/README.md, plugins/inputs/nats_consumer/README.md, plugins/inputs/postgresql/README.md, plugins/inputs/ras/README.md, plugins/inputs/sflow/README.md, plugins/inputs/snmp_legacy/README.md, plugins/inputs/snmp_trap/README.md, plugins/inputs/sql/README.md, plugins/inputs/sqlserver/README.md, plugins/inputs/suricata/README.md, plugins/inputs/tail/README.md, plugins/inputs/webhooks/README.md, plugins/inputs/win_eventlog/README.md, plugins/inputs/win_services/README.md
Related to:
* https://github.com/influxdata/telegraf/pull/10924
* https://github.com/influxdata/telegraf/pull/10926
This pull requests adds the first description comment to the configuration section for a handful of plugins that were overlooked in the above two mentioned PRs.
=> chore(inputs): add descriptions to config in README.md

plugins/parsers/csv/README.md, plugins/parsers/csv/parser.go
Metadata is stored in fields rather than tags by default as is already described in the doc. Metadata can still be used as tag via the `csv_tag_columns` option. Original feat #10083 hasn't been released yet. This will be a breaking change after it is in `v1.22` or `v1.21.5`!
Fixed misspelled optionnames and deleted unnecessary linebreak in the readme.
=> fix: metadata readme description csv parser

go.mod, go.sum, plugins/aggregators/starlark/README.md, plugins/processors/starlark/README.md
resolve: https://github.com/influxdata/telegraf/issues/10828
Updating go.starlark.net to latest version, the project doesn't use official releases but we are using the latest commit. As suggested by @Hipska updated the spec as well to point to the commit instead of master.
@Hipska could you test out this change? thanks!
=> fix: update starlark 7a1108eaa012->d1966c6b9fcd

plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
When messages are received from Cisco MDT devices the message is scanned
for the `keys` and `content` fields. If these are missing then there is
no parsable data for Telegraf. If lots of messages are coming in, this
message can spam the Telegraf log with lots of unnecessary messages on the
order of hundreds per second.
Fixes: https://github.com/influxdata/EAR/issues/3139
=> fix: remove overly verbose info message from cisco mdt

plugins/inputs/sqlserver/README.md
Tested today, without the clause "FROM WINDOWS", the comand returns an error.
Worked seamlessly with this change.
- [ x ] Updated associated README.md.
resolves #
Tested today, without the clause "FROM WINDOWS", the comand returns an error.
Worked seamlessly with this change.
=> fix:Update Readme.MD, missing keyword in sql command creating SID (Service Identity)

plugins/inputs/cisco_telemetry_mdt/README.md
The comment and the grpc library use 4,000,000 as a default. Our README
had a much larger value for an unknown reason. This aligns the default
message size.
=> fix: align the default value for msg size

.circleci/config.yml, plugins/inputs/vsphere/vsphere_test.go
go generate command is unfortunately a single-threaded, one at a time
command. There are no flags to change this. As a result it takes a long
time in our project due to the large number of plugins.
We run this command in CI twice, once during tests and again during
package build. The tests do not need this to be run and this removes it
to save some time on the overall CI process.
=> chore: remove go generate from CI tests

plugins/outputs/graylog/graylog_test.go
The TCP graylog tests are one of the most flaky tests we have. The
current scenario attempts to send two messages, then close the
connection, fail to send a third, and then correctly send a fourth.
I was unable to reproduce the failure after a couple dozen times in CI
and after running the tests >10,000 times locally. For now, this adds
some logging to stdout so we can see what might be going on at the time
of failure.
=> chore: add logging to graylog output tests

docs/LICENSE_OF_DEPENDENCIES.md, go.mod, go.sum, plugins/outputs/azure_data_explorer/azure_data_explorer.go
Version 0.6.0 of the go SDK, among other irrelevant changes, updates its azure blob library to a version that doesn't leak memory and solves upload failures.
Additionally, when serializing the timestamp to kusto, the granularity was increased from a second to a nanosecond, and the format is now hardcoded to be `time.RFC3339Nano`, which kusto accepts.
=> fix: bump github.com/Azure/azure-kusto-go from 0.5.0 to 0.60 and make timing more granular

plugins/inputs/aerospike/aerospike.go, plugins/inputs/aerospike/aerospike_test.go
resolves #10929
In the aerospike go client v5 onwards they moved RequestNodeStats to RequestInfo
https://github.com/influxdata/telegraf/pull/10604
During this PR, the "statistics" command wasn't passed [here](https://github.com/influxdata/telegraf/pull/10604/files/d3b2aefd0124e2edc73bdaa765464fa64acef577#diff-a8caf4914634b15870431f7a18f3c09854fe2da6fab7b3a3d40b28bac4119b64R234)
The same has been corrected in this PR.
=> fix(inputs/aerospike): Statistics query bug

go.mod, go.sum, plugins/inputs/aliyuncms/aliyuncms.go, plugins/inputs/aliyuncms/aliyuncms_test.go, plugins/inputs/aliyuncms/discovery.go
First, the aliyuncms plugin was not correctly parsing metrics with multiple dimensions. This was due to some bad if/else logic. Once fixed users can do the following in their config:
```
dimensions = '[{"instanceId": "rm-bp1zureya4l415lus"},{"instanceId": "rm-bp161628eanrceqz2"}]'
```
Second, the plugin can do some auto-discovery of the JSON response that is received and then determine how to parse the response. However, it appears that aliyun/alibaba has updated some of the responses. This adds a `responseRootKey` rather than trying to determine that as the logic was not correct and no longer consistent across services. We already have a hard-coded `responseObjectIDKey` that is used as part of that root key.
Finally, this updates the aliyun SDK.
Fixes: #10848
=> fix: ensure aliyuncms metrics accept array, fix discovery

internal/rotate/file_writer_test.go, logger/logger_test.go, plugins/inputs/ceph/ceph_test.go, plugins/inputs/conntrack/conntrack_test.go, plugins/inputs/directory_monitor/directory_monitor_test.go, plugins/inputs/linux_sysctl_fs/linux_sysctl_fs_test.go, plugins/inputs/logparser/logparser_test.go, plugins/inputs/postfix/postfix_test.go, plugins/inputs/procstat/procstat_test.go, plugins/inputs/socket_listener/socket_listener_test.go, plugins/inputs/suricata/suricata_test.go, plugins/inputs/syslog/nontransparent_test.go, plugins/inputs/syslog/octetcounting_test.go, plugins/inputs/syslog/rfc5426_test.go, plugins/inputs/syslog/syslog_test.go, plugins/outputs/file/file_test.go, plugins/outputs/influxdb/http_test.go, plugins/outputs/socket_writer/socket_writer_test.go, plugins/outputs/sql/sql_test.go, plugins/outputs/sql/sqlite_test.go, testutil/socket.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer require.NoError(os.RemoveAll(tmpDir))
// now
tmpDir := t.TempDir()
}
```
=> test: use `T.TempDir` to create temporary test directory

plugins/inputs/smart/smart.go, plugins/inputs/smart/smart_test.go
The smartctl output can vary based on the localization set in Windows.
This means that some numbers can show up comma-separated (English),
space-separated, or even apostrophe separated. There are probably
others.
This updates one function that was always assuming comma separated to
remove any non-numeric value and no longer split on white space, which
could be used as a separator.
Fixes: #10907
=> fix: correctly parse various numeric forms

plugins/inputs/mysql/README.md, plugins/inputs/mysql/mysql.go
=> fix: Add mariadb_dialect to address the MariaDB differences in INNODB_METRICS

plugins/inputs/gnmi/gnmi.go
When writing gNMI `tag_only` tags, use fmt.Sprint to convert the
value interface to a string.
resolves #11007
=> fix: use Sprint to cast to strings (#11007)

Makefile
The makefile runs some shell commands to collect version information
about the build. The changes currently fail on Windows becuase of some
unix only options and commands. This fixes the two specific lines with
commands to allow the build, testing, etc. to work as expected.
Fixes: #11014
=> fix: allow Makefile to work on Windows

cmd/telegraf/telegraf.go
The command help functions state that `--test-wait` does imply `--test` but behaviour is still different. Adding this extra check will make behaviour consistent. Maybe even better would be to set `fTest` to `true` if `fTestWait` is more than 0?
=> fix(cmd): Also allow 0 outputs when using test-wait parameter

plugins/inputs/gnmi/gnmi.go
resolves #11006 
Adds `sync.Mutex` for lookup map to avoid concurrent map read/writes
=> fix: add mutex to gnmi lookup map (#11006)

plugins/inputs/influxdb_listener/influxdb_listener.go
The influxdb_listener input plugin, when using the upstream parser had
bad logic that would write first using the new upstream parser and then
attempt to parse the data again with the internal parser right after.
This was leading to EOF errors on the internal parser because the data
had already been read.
Fixes: #10900
=>  fix: duplicate influxdb listener writes

plugins/inputs/disk/README.md, plugins/inputs/system/ps.go
The tracefs filesystem is showing up more and is not likely something a
user wishes to have enabled by default. This adds it to the ignore in
the config by default.
This also reduces the error message level from error to warning. This
was previously a debug message, but was bumped all the way to an error.
This message does not prevent any messages from getting read by Telegraf
and not an error that halts Telegraf. Users may still wish to address
the messages so reducing to a warning is better than hiding them.
Fixes: #10897
=> fix: add tracefs to ignore, reduce log level

.circleci/config.yml
The Darwin packaging step is timing out: https://app.circleci.com/pipelines/github/influxdata/telegraf/10247/workflows/d38aeeeb-f0e0-4678-a59d-20e97593e757/jobs/169092
Restarting the job occasionally fixes it seems, and then it runs in `4m 29s`. So something could actually be hanging but from the logs it seems it was just slow downloading the dependencies. Hopefully just increasing the timeout will help, it seems like a dirty fix open for suggestions if there is a better approach to fixing this.
=> chore: increase timeout for darwin packaging

plugins/common/http/config.go, plugins/outputs/http/README.md, plugins/outputs/http/http_test.go
resolves #10953 
- Adds inputs for `MaxIdleConns` and `MaxIdleConnsPerHost` in `HTTPClientConfig` to read from toml
- Let me know if it's a good idea to keep a default other than 2 for `MaxIdleConnsPerHost`
=> feat(outputs.http): Support configuration of `MaxIdleConns` and `MaxIdleConnsPerHost`

plugins/outputs/datadog/README.md, plugins/outputs/datadog/datadog.go
*No idea what unit tests would be appropriate. We tested this against a live production system...
resolves #6822 
resolves #10944 
Added typing to Datadog metrics; forced `interval` to be 1 for `count` typed metrics.
=> fix: datadog count metrics

config/config.go, plugins/inputs/diskio/diskio.go
The `io` input plugin was renamed differently compared to `cisco_telemetry_gnmi` and `KNXListener`. This PR aims to streamline this..
=> style: align plugin renaming

plugins/inputs/disk/disk.go
I found another deprecated plugin config option that wasn't showing a notice yet.
=> style(inputs/disk): Add deprecation notice to legacy mountpoints setting

scripts/telegraf.service
The current behavior for the systemd service file is to wait for the
network.target to activate. This does not mean that the network is
actually up or that a network device has an IP address. The
network-online.target instead waits for a functional network to be up.
A user recently saw issues with this when trying to use a remote config.
On boot, the network.target was hit, but the wireless network was not
ready yet, and telegraf failed to obtain the remote configuration and
never started.
=> fix: have telegraf service wait for network up

plugins/outputs/azure_monitor/azure_monitor.go
The context deadline exceeded error most commonly indicates that a
network related issues has occurred preventing the client from getting to
the server. Usually this means that there is something the user needs to
address. However, there appears to be a case where a network issue (e.g.
a down proxy) can occur and telegraf never recovers from the down
service.
This checks for the context deadline error and will re-create the HTTP
client if it is hit.
Fixes: #10950
=> fix: re-init azure monitor http client on context deadline error

plugins/inputs/statsd/statsd.go
Errors from the UDPListen function were previously not checked. In a
recent minor release we started checking them, which introduced more
visible errors to users. However, when statsd is run with the `--test`
option or when a user kills Telegraf with a ctrl-c, an error now shows
up as the read is still trying after a close has occurred.
The ReadFromUDP call blocks until something is received, so I don't
believe there is anything else for us to check to prevent. All other
non-connection-related errors are logged and we continue on (see
the above lines). This also does not hide issues when starting or
stopping the connection.
Fixes: #9867
=> fix: do not error when closing statsd network connection

plugins/inputs/http/http.go, plugins/inputs/postgresql_extensible/README.md, plugins/inputs/postgresql_extensible/postgresql_extensible.go
This config option makes the configuraiton of this plugin more complex
than it needs to be and the option's docs were not even correct to begin
with.
Fixes: #9735
=> fix: deprecate useless database config option

internal/process/process.go, internal/process/process_test.go, plugins/inputs/exec/README.md, plugins/inputs/exec/exec.go, plugins/inputs/exec/exec_test.go, plugins/inputs/execd/README.md, plugins/inputs/execd/execd.go, plugins/inputs/execd/execd_test.go, plugins/outputs/exec/README.md, plugins/outputs/exec/exec.go, plugins/outputs/execd/README.md, plugins/outputs/execd/execd.go, plugins/outputs/execd/execd_test.go, plugins/processors/execd/README.md, plugins/processors/execd/execd.go, plugins/processors/execd/execd_test.go
resolves #9281
adds support for environment variables for **execd** and **exec** plugins
example usage:
```toml
[[inputs.execd]]
command = [
"/opt/custom-plugins/my-custom-plugin",
"-config", "/opt/custom-plugins/my-custom-plugin.conf",
"-interval", "30s",
]
environment = ["LD_LIBRARY_PATH=/opt/app/lib64"]
```
=> feat(exec, execd): add an option to pass a custom environment to their child process

etc/telegraf.conf, plugins/inputs/disk/README.md, plugins/inputs/disk/disk.go, plugins/inputs/disk/disk_test.go, plugins/inputs/system/mock_PS.go, plugins/inputs/system/ps.go
resolves #10986 and #10897
Nomad (and possibly other software) will create bind mounts in locations that Telegraf running as a non-root user cannot inspect. This creates an `ignore_mount_opts` option to the disk plugin that can ignore these mounts, which are unlikely to generate useful metrics anyway.
=> feat: add mount option filtering to disk plugin

plugins/inputs/cloudwatch/cloudwatch.go
This PR resolve two problems:
1. Error message did not include the namespace causing trouble, making it difficult to figure out the issue with multiple namespaces queried.
2. A single erroneous namespace from AWS API will stop in-take of all subsequent metrics, so just log the error and skip over to the next namespace getting as much metrics as we can.
=> fix: Output erroneous namespace and continue instead of error out

docker-compose.yml, plugins/outputs/riemann_legacy/riemann_legacy_test.go
=> test: remove unused riemann from docker-compose

plugins/aggregators/basicstats/sample.conf, plugins/aggregators/derivative/sample.conf, plugins/aggregators/final/sample.conf, plugins/aggregators/histogram/sample.conf, plugins/aggregators/merge/sample.conf, plugins/aggregators/minmax/sample.conf, plugins/aggregators/quantile/sample.conf, plugins/aggregators/starlark/sample.conf, plugins/aggregators/valuecounter/sample.conf
To prepare for the new way to generate sample configurations, moving all of the sample configs to a separate file. This PR handles all the aggregator plugins migration.
=> chore(aggregators): migrate sample configs into separate files

plugins/inputs/http/http.go, plugins/inputs/http/http_test.go
The current http input plugin, when a body is specified, will produce
a NopCloser. I believe this is because the gzip compression function
returns a closer. However, this means that the HTTP request will not
include the content-length. For that to happen, the request body must
either be a string or bytes reader or bytes buffer.
The primary reason to use a closer over those readers is in the event of
a lot of data and trying to stay memory efficient. However, as the input
plugin sends little data over http, the size should generally be
small. Therefore, switch to bytes and string readers so that the http
requests will always include the content length.
fixes: #11034
=> fix: use readers over closers in http input

plugins/inputs/sysstat/sysstat.go
resolves #11135
Avoids the sysstat input plugin becoming "stuck" continuously using an invalid interval argument of 0 to sadc. https://github.com/sysstat/sysstat/blob/c5bb321b4e910b704b7ba4a600c7edfbd477b2cf/sadc.c#L1315
No changes to README.md , and as only able to reproduce with code injection, no unit tests added.
=> fix: avoid calling sadc with invalid 0 interval

plugins/inputs/burrow/burrow.go
The pull request https://github.com/influxdata/telegraf/pull/6948 unfortunately didn't have the CI run on it correctly, so the following issues weren't caught:
* `make fmt` needed to be run
* `cannot call pointer method DialContext on net.Dialer` error
This pull request resolves these issues.
=> fix(inputs.burrow): Move Dialer to variable and run `make fmt`

plugins/inputs/internet_speed/README.md, plugins/inputs/internet_speed/sample.conf
=> fix: doc interval setting for internet speed plugin

plugins/inputs/internet_speed/internet_speed_test.go
The file download test when enabled is significantly faster in terms of
total test time (45 sec vs 4 sec). In CI when running all these tests
in parallel we could hit limits or timeouts, so we want to limit our
need for external networking.
Running with the previous setting, while running other integration tests
can lead to timeouts and other networking hiccups, which cause this test
to fail.
fixes: #11123
=> test: switch internet speed to enable file download

plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
On a fast system, 5 seconds is not a long enough sleep to let
elasticsearch index the data used for the test. Instead, use
elasticsearch's own command to force the index to happen of the newly
added data and remove the sleep.
fix: #11124
=> test: force elasticsearch to index batch data

plugins/inputs/slab/slab.go, plugins/inputs/slab/slab_test.go, plugins/inputs/slab/testdata/slabinfo
This PR improved the `slab` plugin testing and allows to use non-sudo in tests.
=> fix: Improve slab testing without sudo.

EXTERNAL_PLUGINS.md
Added external input plugin for gathering smart home statistics from Hue Bridge devices.
=> feat: Add huebridge plugin

plugins/inputs/tcp_listener/tcp_listener_test.go
Avoid flaky/racy test in tcp-listener.
=> fix: avoid data race in tcp-listener test.

.github/workflows/readme-linter.yml, tools/readme_linter/assert.go, tools/readme_linter/main.go
Add a github actions workflow to run the readme linter.
The action finds plugin readme files changed in the PR and runs the linter on them.
The linter itself is built during the action (using "go run"). It is a small program with very few dependencies that doesn't take much time to build. The entire action takes about 20 seconds, including getting code, building, and running the linter.
In order for the workflow to know when the linter failed, I also changed the linter to exit with nonzero status if it finds anything.
Here is output of a failed job as an example:
```
go: downloading github.com/yuin/goldmark v1.4.1
plugins/inputs/file/README.md:3: long line in paragraph
plugins/inputs/file/README.md:1: missing required section 'Example Output'
plugins/inputs/file/README.md:1: missing …
```
=> chore: add readme linter to CI

plugins/inputs/cpu/README.md, plugins/inputs/cpu/cpu.go
potentially resolves #5949
Adds tags core_id and physical_id which contain information about physical CPU or cores in cases of hyper-threading. This is an opt-in setting to not generate tags for users that will not use them.
These tags are added only if they are available in the already used library github.com/shirou/gopsutil
=> feat(inputs/cpu): add tags with core id or physical id to cpus

docker-compose.yml, plugins/outputs/nats/nats_test.go
Moves the nats output integration test from expecting the docker-compose infrastructure to use test containers.
=> test: move nats to test-containers

docker-compose.yml, plugins/inputs/aerospike/aerospike_test.go
Also remove histogram tests as they require the container to be up for
over an hour before they are generated. This is just not practical for
integration tests unless there is a way to force their creation.
=> test: migrate aerospike to test-containers

plugins/outputs/event_hubs/README.md, plugins/outputs/event_hubs/event_hubs.go
This allows users to set the partition key value in data set to Azure.
This value gets hashed and that hash determines which of the available
partitions the event will get sent to. The hash values get split evenly
over the available partitions that exist in Azure.
Fixes: #10762
=> feat: add field key option to set event partition key

docker-compose.yml, plugins/inputs/opcua/opcua_test.go
One integration test was already using test containers, so this moved it to use our generic code for it and added it to the second integration test.
=> test: move opcua to test-containers

.github/workflows/golangci-lint.yml, Makefile
Bump the golangci linter to a new version to re-enable more checks on go 1.18.
=> fix: Bump golangci-lint from 1.45.2 to 1.46.2

plugins/inputs/mock/README.md, plugins/inputs/mock/mock.go, plugins/inputs/mock/mock_test.go, plugins/inputs/mock/sample.conf
This PR adds the possibility to define a field with a constant value (string, float, int, bool) in the `mock` input plugin. This is helpful when testing e.g. processors against known good/known bad values.
=> feat: Add constant 'algorithm' to the mock plugin

plugins/inputs/prometheus/README.md, plugins/outputs/prometheus_client/README.md
Remove recommendation for metric_version=2 and add a description of both versions so users can choose which is better for their use case.
=> docs: remove recommendation for prometheus metric_version=2

plugins/inputs/snmp/snmp_test.go
This test had a short skip added to it four years ago and a comment that
the test has random failures. While working on the integration tests,
which run all tests this test started showing up in the errors.
While the two asserts at the end could possibly be updated, it is worth
having someone look deeper into understanding why this change is
required.
In order to get integration tests running, this skips this test always.
=> test: actually skip flaky snmp test

plugins/inputs/aerospike/aerospike_test.go, plugins/inputs/memcached/memcached_test.go, plugins/inputs/mysql/mysql_test.go, plugins/inputs/opcua/opcua_test.go, plugins/inputs/openldap/openldap_test.go, plugins/inputs/pgbouncer/pgbouncer_test.go, plugins/inputs/redis/redis_test.go, plugins/inputs/redis_sentinel/redis_sentinel_test.go, plugins/inputs/zookeeper/zookeeper_test.go, plugins/outputs/cratedb/cratedb_test.go, plugins/outputs/mqtt/mqtt_test.go, plugins/outputs/nats/nats_test.go, plugins/outputs/nsq/nsq_test.go, testutil/container.go, testutil/container_test.go
Containers have at least three options when it comes to specifying the
port a container uses: 80, 80:80, 80/[tcp|udp]. The original logic was
naive and assumed only the first option would ever be used and only one
port was ever cared about.
The new mechanism creates a lookup table for easy use in tests while
also allowing for all the formats above.
=> test: refactor testcontainer port lookup

internal/snmp/wrapper.go, plugins/inputs/snmp/snmp.go, plugins/inputs/snmp/snmp_test.go, plugins/processors/ifname/ifname.go, plugins/processors/ifname/ifname_test.go
#11163 added TCP reconnection but also made some unneccesary changes. It changed the connection cache and many places in tests to expect a pointer to Gosnmpwrapper instead of a Gosnmpwrapper value.
The other Gosnmpwrapper methods that implement the snmpConnection interface use value receivers. This PR switches Reconnect to use a value receiver and undoes the changes to connection cache and tests.
=> fix(inputs/snmp): switch new Reconnect method to be a value receiver

go.mod, go.sum
fixes: influxdata/telegraf-internal#310
=> chore: update github.com/opencontainers/runc from v1.0.2 to v1.1.2

plugins/inputs/aerospike/aerospike_test.go, plugins/outputs/cratedb/cratedb_test.go, testutil/container.go
This collects the container logs and prints them if/when a test fails.
Very helpful when trying to debug or understand if a container actually
started.
When running with -race, caught a couple issues when creating containers
in a generic function in aerospike and cratedb plugins.
=> test: enable logging with testcontainers

plugins/inputs/prometheus/sample.conf, plugins/outputs/prometheus_client/sample.conf
This PR synchronizes the new `metric_version` description to the `sample.conf` file for both prometheus input and output.
=> fix: Update sample.conf for prometheus

plugins/inputs/modbus/README.md, plugins/inputs/modbus/modbus_test.go, plugins/inputs/modbus/request.go
=> fix(inputs/modbus): #11105 fix requests starting with an omitted field

plugins/inputs/mcrouter/mcrouter_test.go
missed this during the memcached transition
=> test: migrate mcrouter to testcontainers

go.mod, go.sum
partially implements https://github.com/influxdata/telegraf/issues/11164
Bump the dependency with the issue being fixed. This allows us to remove one of the replacements in go.mod.
=> chore: Bump apcupds and remove the replacement

plugins/serializers/splunkmetric/splunkmetric.go, plugins/serializers/splunkmetric/splunkmetric_test.go
Contrary to #8039, splunk documentation does require the event tag with
metric value. This reverts that previous change.
fixes: #8761
=> fix: re-add event to splunk serializer

.circleci/config.yml
We are on go1.18 and I would like to not have to update the executor
name after every go release. This calls it the same as the container
name itself.
=> chore: rename circleci executor

plugins/inputs/elasticsearch_query/elasticsearch_query_test.go, plugins/inputs/mysql/mysql_test.go, plugins/inputs/openldap/openldap_test.go, plugins/inputs/pgbouncer/pgbouncer_test.go, plugins/inputs/sql/sql_test.go, plugins/inputs/zookeeper/zookeeper_test.go, plugins/outputs/mongodb/mongodb_test.go, plugins/outputs/sql/sql_test.go, testutil/container.go
* migrates sql, mongodb to using internal testutil test-container code
* stops logging before terminating container due to known race
conditions in upstream logging
* adds additional wait for commands in various places
=> test: testcontainer hardening

.circleci/config.yml
The images used between testing (docker image) and integration testing
(ubuntu vm) are very different. The folders, layouts, and versions can
also be different. Therefore, take the small-time hit and not cache
integration tests for now.
=> test: remove restore integration test cache

go.mod, go.sum, plugins/parsers/json_v2/parser.go
resolves #11252
replaces #11023
Bump the GJSON library to the latest version and fix the issues arising from a new referencing scheme when it comes to node indices.
=> fix: bump github.com/tidwall/gjson from 1.10.2 to 1.14.1

plugins/inputs/ceph/ceph_test.go, plugins/inputs/directory_monitor/directory_monitor.go
In the directory_monitor and ceph tests, there are a number of places
where directories or test files were created with full permissions. This
is not the right thing to do in these cases. Instead, use the default
file (644) and folder (755) permissions that are commonly used.
=> fix: remove full access permissions

plugins/inputs/sql/drivers_sqlite.go, plugins/inputs/sql/drivers_sqlite_other.go, scripts/check-deps.sh
There were a couple of additional combinations of distro/arch that were
missing. These were discovered with running the `make check-deps`
command.
To make it easier to know which combination of distro/arch is failing
this also adds a printout of which is combination is currently
evaluated.
=> fix: add missing build constraints for sqlite

config/config.go, config/config_test.go, plugins/parsers/all/all.go, plugins/parsers/registry.go, plugins/parsers/registry_test.go, plugins/parsers/xpath/parser.go, plugins/parsers/xpath/parser_test.go
This PR migrates the `xpath` parser family to the new-style parser structure. The change is backward compatible.
=> feat: Migrate xpath parser to new style

Makefile
When cross-compiling telegraf, the tool for embedding the `sample.conf` into the READMEs always needs to be built for the host architecture. Furthermore, remove the embedding procedure from building telegraf and document the new `docs` makefile target.
=> fix: Always build README-embedder for host-architecture

.circleci/config.yml, docs/developers/PACKAGING.md, scripts/installgo_linux.sh
In order to ensure all our testing is using the same version of go
across all tests, add an install go for linux.
=> test: add install go for linux, use in integration tests

.circleci/config.yml
When creating a tag for release, this rebase causes the wrong `build_version.txt` to be used. Remove this step as it is only needed during testing to verify there are no merge conflicts.
=> fix: Don't rebase on master when building packages

plugins/parsers/xpath/parser.go
Option introduced in #11102 does produce a lot of debug messages when we are in a valid state. This PR aims to reduce this.
=> fix(parsers/xpath): Reduce debug messages when empty selection is allowed

plugins/outputs/groundwork/README.md, plugins/outputs/groundwork/groundwork.go, plugins/outputs/groundwork/groundwork_test.go
=> feat(outputs.groundwork): Add default appType as config option

config/config.go
resolve: https://github.com/influxdata/telegraf/issues/11308
Telegraf is panicking reporting the error "fatal error: concurrent map writes" because maps in Go are not safe for concurrent use. The method `missingTomlField` was writing to the map `c.UnusedFields` concurrently so this pull request wraps the write with a mutex to allow the map to be updated safely. This panic is easily reproducible with a config defining multiple similar inputs that have the data_format set as "csv". I think this bug was a side effect from [removing csv](https://github.com/influxdata/telegraf/pull/8791/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L1655-L1657) from the switch case to migrate it to the new parser. The function `missingTomlField` gets called "when the decoder …
=> fix: Prevent concurrent map writes to c.UnusedFields

plugins/inputs/mongodb/README.md, plugins/inputs/mongodb/sample.conf
By default, the mongo-driver library will attempt to use the primary
node of a cluster. For monitoring with Telegraf, users may specify a
secondary node that they want to monitor. In these cases, the user will
need to specify a direct connection to that node.
The library has a number of options for how it connects, which include
primary, primary preferred, secondary, secondary preferred, and closest.
None of these are options to ensure that the specified node is used.
fixes: #11275
fixes: #9555
=> docs: explain directly connecting to mongo node

.github/dependabot.yml
For Dependabot, updating the config to remove the prefix `fix:` in favor of using the default `chore(deps):`, you can see an example of this here: https://github.com/influxdata/influxdb_iox/pull/4861
=> chore: Remove prefix to use the default `chore(deps)`

plugins/inputs/postgresql/postgresql_test.go
The postgres docker image will start up and immediately shutdown the
service will the docker entrypoint starts configuration. This results in
the expected ready to accept connections log message to show up twice.
This generally happens within a tenth of a second, but in CI this can
get hit and the test will fail as the database is not yet up.
fixes: #11292
=> test: update wait for statement for postgres

plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go, plugins/inputs/leofs/leofs_test.go, plugins/inputs/sqlserver/azuresqldbqueries_test.go, plugins/inputs/sqlserver/azuresqlmanagedqueries_test.go, plugins/inputs/sqlserver/azuresqlpoolqueries_test.go, plugins/inputs/sqlserver/sqlserver_test.go, plugins/inputs/x509_cert/x509_cert_test.go, plugins/outputs/event_hubs/event_hubs_test.go, plugins/outputs/opentsdb/opentsdb_test.go, plugins/outputs/riemann_legacy/riemann_legacy_test.go, plugins/processors/ifname/ifname_test.go
In a number of cases integration tests were not named correctly
and/or were not skipped during unit testing.
This also adds a riemann integration test.
=> test: mark integration tests correctly

.circleci/config.yml
On amd64, linux unit test runs, code coverage will be collected and
uploaded to the coveralls coverage service on runs with the master
branch. This does not include forks or PRs from community members.
Currently, the coveralls service requires a token to be used to upload
all coverage reports. However, there is no safe/secure way with circle
ci to hide this with our current processes that we have in place.
This also removes the coverage for the parsers/influx/machine.go file as
it contains many "//line" comments which currently break reports. See
https://github.com/golang/go/issues/35781 for more details.
fixes: https://github.com/influxdata/telegraf/issues/10733
=> test: add coveralls coverage

plugins/common/proxy/connect.go, plugins/common/proxy/dialer.go, plugins/common/proxy/proxy.go, plugins/inputs/cloudwatch/README.md, plugins/inputs/cloudwatch/cloudwatch_test.go, plugins/inputs/x509_cert/README.md, plugins/inputs/x509_cert/x509_cert.go, plugins/inputs/x509_cert/x509_cert_test.go, plugins/outputs/datadog/README.md, plugins/outputs/websocket/README.md
resolves #9174
Adds proxy support for the `x509_cert` plugin. The supported proxy methods are HTTP CONNECT (TCP only) and SOCKS5.
~~**Note:** #9289 should be merged before this PR since all URLs are currently parsed as globs causing telegraf to fail to pull the certificate. Similarly, the `TestGatherTCPCert` test will fail because of this.~~ Rebased to master.
=> feat(x509_cert): add proxy support

plugins/aggregators/derivative/README.md, plugins/aggregators/derivative/sample.conf, plugins/inputs/cassandra/README.md, plugins/inputs/cassandra/sample.conf, plugins/inputs/kafka_consumer_legacy/README.md, plugins/inputs/kafka_consumer_legacy/sample.conf, plugins/inputs/logparser/README.md, plugins/inputs/logparser/sample.conf, plugins/inputs/riemann_listener/README.md, plugins/inputs/riemann_listener/sample.conf, plugins/inputs/snmp_legacy/README.md, plugins/inputs/snmp_legacy/sample.conf, plugins/inputs/vsphere/README.md, plugins/inputs/vsphere/sample.conf, plugins/outputs/logzio/README.md, plugins/outputs/logzio/sample.conf, tools/readme_config_includer/generator.go
This PR fixes a few broken `sample.conf` files that were broken during the initial migration to template-based generation. This concerns
- outputs/logzio           -- fix mismatch between README and in-code options
- inputs/riemann_listener -- fix type in section
- inputs/vsphere          -- restore config due to initial migrating of the wrong TOML section
- removal of superfluous `DEPRECATED` warnings in the `sample.conf`
Furthermore, this fixes an issue in the embedding tool that adds garbage to the README in cases where the sample.config was getting smaller. This is due to missing truncation keeping the "old" content of the README at the end.
=> fix: Restore sample configurations broken during initial migration

plugins/parsers/all/all.go, plugins/parsers/registry.go, plugins/parsers/wavefront/parser.go, plugins/parsers/wavefront/parser_test.go
resolves #11364  
This PR migrates the `wavefront` parser to the new-style parser structure. The change is backward compatible. Furthermore, we cleanup the parser a bit.
=> feat: Migrate wavefront parser to new style

go.mod, go.sum, scripts/check-deps.sh
partially addresses #11164
Remove the dependency as `github.com/satori/go.uuid` is not used anymore in the code.
=> chore: Remove 'github.com/satori/go.uuid' replacement

go.mod, go.sum
resolves #11164
Remove the dependency as the PR for `github.com/cisco-ie/nx-telemetry-proto` was merged just now and the replacement is not needed anymore.
=> chore: Remove 'github.com/cisco-ie/nx-telemetry-proto' replacement

plugins/inputs/jolokia2/common/gatherer.go, plugins/inputs/jolokia2/common/point_builder.go
=> fix: remove jolokia2 panic info

config/config.go, plugins/inputs/http_listener_v2/http_listener_v2_test.go, plugins/parsers/all/all.go, plugins/parsers/form_urlencoded/parser.go, plugins/parsers/registry.go
resolves #11355
This PR migrates the `form_urlencoded` parser to the new-style parser structure. The change is backward compatible. Furthermore, we cleanup the parser a bit.
=> feat: Migrate form_urlencoded parser to new style

plugins/outputs/wavefront/README.md, plugins/outputs/wavefront/sample.conf, plugins/outputs/wavefront/wavefront.go, plugins/outputs/wavefront/wavefront_test.go
The Wavefront golang SDK can send metrics via http(s) or tcp. In the case of http, the Wavefront SDK batches metrics internally, flushing them periodically or when they reach a maximum batch size. At present, configuring this batch size is not possible from the wavefront plugin output, so the sdk default value (10,000) is always used. In some cases smaller or larger batch sizes might be preferred, or users might want to match the wavefront client's batch size to the batch size configured for the telegraf output.
This pr exposes the wavefront internal batch size for configuration as `http_batch_size`.
I added a unit test validating that the intended default is set, although the `outputs.Outputs` map doesn't necessarily seem like an interface that wants to be used for this purpose.
=> feat(outputs/wavefront): make maximum http batch size configurable

plugins/inputs/exec/exec_test.go, plugins/inputs/http/http_test.go, plugins/inputs/kafka_consumer/kafka_consumer_test.go, plugins/parsers/all/all.go, plugins/parsers/registry.go, plugins/parsers/value/parser.go, plugins/parsers/value/parser_test.go
=> feat: migrate value parser to new style

config/config_test.go, plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_test.go, plugins/inputs/statsd/statsd.go, plugins/inputs/tcp_listener/tcp_listener_test.go, plugins/parsers/all/all.go, plugins/parsers/graphite/parser.go, plugins/parsers/graphite/parser_test.go, plugins/parsers/registry.go
resolves #11356  
This PR migrates the `graphite` parser to the new-style parser structure. The change is backward compatible. Furthermore, we cleanup the parser a bit.
=> feat: Migrate graphite parser to new style

config/deprecation.go, models/log.go, plugin.go, plugins/parsers/xpath/parser.go
resolves: #11336 
This PR brings back the old `xml`, `xpath_json`, `xpath_msgpack` and `xpath_protobuf` sections to fix a regression introduced in #11218. We also print deprecation notices and modify the infrastructure to be able to do so.
=> fix: Bring back old xpath section names

plugins/outputs/http/http_test.go
The testcase I provided for Batched/Unbatched output had confused parameters for `require.Equal`. This is fixed now.
=> test: exchange confused parameters (expected vs actual)

config/config.go, plugins/parsers/all/all.go, plugins/parsers/dropwizard/parser.go, plugins/parsers/dropwizard/parser_test.go, plugins/parsers/registry.go, plugins/parsers/registry_test.go
resolves #11354  
This PR migrates the `dropwizard` parser to the new-style parser structure. The change is backward compatible. Furthermore, we cleanup the parser a bit.
=> feat: Migrate dropwizard parser to new style

tools/package_lxd_test/container.go
Tests were run using dnf/yum update, which will not only check for
updates, but also make updates. This is not the behavior wanted on the
test, instead, the desire is only to update the package listings and
check for updates. This is done with check-update.
=> test: run check-update on dnf/yum

config/config_test.go, plugins/parsers/csv/README.md, plugins/parsers/csv/parser.go, plugins/parsers/csv/parser_test.go
resolves #11257
This PR adds a flag to allow the CSV parser to be reset on every call to `Parse`. This is required as, dependent on the input processing, the CSV parser needs to either keep track of the state (e.g. when parsing linewise) or needs to drop the state (e.g. when reading whole files). In the first case, you should set `csv_reset_mode = "none"` (default), while in the second case you should set `csv_reset_mode = "always"`.
**Please note:** Reset-mode `"always"` is ignored for `ParseLine` (which is not used in our codebase) as this implicitly requires keeping track of the state if used with skipped-rows, headers and/or metadata.
=> fix: Add reset-mode flag for CSV parser

plugins/inputs/exec/exec.go, plugins/parsers/all/all.go, plugins/parsers/nagios/parser.go, plugins/parsers/nagios/parser_test.go, plugins/parsers/registry.go
resolves #11360 
This PR migrates the `nagios` parser to the new-style parser structure. The change is backward compatible. Furthermore, we cleanup the parser a bit.
=> feat: Migrate nagios parser to new style

plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
Similar to #11309, need to wait for the second ready to accept
connections statement.
fixes: #11446
=> test: update wait statement for postgresql_extensible

config/config.go, plugins/parsers/all/all.go, plugins/parsers/prometheus/parser.go, plugins/parsers/registry.go
=> fix: Update prometheus parser to be a new style parser plugin

models/log.go, models/log_test.go
resolves #11459
Starting with v1.23.1 telegraf outputs strange deprecation warnings for non-deprecated plugins (and options) caused during a migration of the printing routines to `models/log.go`. This PR fixes the issue, restores the old behavior and adds tests to make sure we get the right deprecation warnings (or non) as expected.
=> fix: Deprecation warnings for non-deprecated packages

plugins/inputs/socket_listener/socket_listener.go, plugins/inputs/socket_listener/socket_listener_test.go
related: https://github.com/influxdata/telegraf/pull/11432#discussion_r914908764
The socket listener plugin has `SetParser` function defined, but also sets it within `init` which isn't what other plugins do and prevents us from handling errors because with the new parser structure an error could be returned.
=> chore(inputs.socket_listener): Remove parser from init

tools/package_lxd_test/container.go
yum/dnf return a non-zero return code if there are packages to update.
Ignore this value.
=> test: ignore return code on check-update

.circleci/config.yml
During a release it is possible for the Mac signing step to fail due to a manual step of having to agree to the updated license agreement. The idea is that if we start signing the nightly artifacts we can potentially detect if there are any failures earlier. There hasn't been an issue with the windows signing step, but I added it as well to be consistent.
Of course this depends on someone checking to make sure the nightly build has failed/passed everyday, future work could be to add an obvious notification if there is a failure (tiger bot send a slack message or something for example).
=> chore: Sign nightly artifacts to detect issues before release

plugins/inputs/rabbitmq/README.md, plugins/inputs/rabbitmq/rabbitmq.go, plugins/inputs/rabbitmq/rabbitmq_test.go, plugins/inputs/rabbitmq/testdata/set1/queues.json
resolves #11474
Adds support for the `head_message_timestamp` field to the `rabbitmq_queue` metric.
Note: This metric is only available from the API if there are messages in the queue, held in-memory by the broker, which have their timestamp metadata property set. The timestamp property can be set manually at time of message publication by the publisher, or it can be set automatically by the `rabbitmq_message_timestamp` plugin. Because the broker will not page messages in from disk just to read their timestamp, this metric is notably never present at the API for "lazy" queues (for which all messages are stored on disk and only loaded into memory briefly when a consumer grabs them). In cases where the `head_message_timestamp` field from the API is `null`, the `head_message_timestamp` field …
=> feat(inputs.rabbitmq): add support for `head_message_timestamp` metric

plugins/inputs/upsd/README.md, plugins/inputs/upsd/sample.conf, plugins/inputs/upsd/upsd.go
This PR moves `inputs.upsd`'s sample-configuration to a `sample.conf` file and embeds the data into both the code and the README. By doing so, we fix the missing `[[inputs.upsd]]` header when generating Telegraf's sample-configuration (see [comment](https://github.com/influxdata/telegraf/pull/9890#issuecomment-1176893362) in #9890).
=> fix(inputs.upsd): Move to new sample.conf style

plugins/common/cookie/cookie.go, plugins/inputs/http/README.md, plugins/inputs/http/sample.conf
This allows both a 200 and 201 response code when generating auth using
the cookie auth plugin. Additionally, this updates the docs for the
cookie headers to show a TOML map rather than a string.
fixes: #11134
=> fix: allow 201 for cookies, update header docs

plugins/inputs/smart/README.md, plugins/inputs/smart/smart.go, plugins/inputs/smart/smart_test.go
Adjusts the `smart` input plugin to collect SSD endurance information in more situations (for example, resolves #8701)
The `smart` plugin already collects endurance information if `attributes` is `true` **and** the NVME log contains the attribute `Percentage Used`.
However, this PR adjusts the plugin to also collect endurance information if it's available in the following locations
* in the NVME log with name `Percentage used endurance indicator`
* For SATA SSDs, in the SMART data labelled as one of `Percent_Lifetime_Remain`, `Wear_Leveling_Count` or `Media_Wearout_Indicator`
Because the SMART data fields are vendor specific, the ID cannot be relied on, so this PR introduces the ability to match rows by name rather than ID.
Additionally, for safety, it is not assumed that the value of any …
=> feat: collect SSD endurance information where available in smartctl

plugins/inputs/gnmi/README.md, plugins/inputs/snmp/sample.conf
Backport synchronization of sample.conf and README.md files from the v1.23.2 release.
(cherry picked from commit ccda9c5c5cd280e98b9984b46a0d9086a198778d)
=> fix: Backport sync sample.conf and README.md files

.circleci/config.yml
This is a proposal to skip building all the artifacts whenever a pull request is merged, except only building the windows and amd64 artifacts so that the updated configurations can be generated. The benefit would be faster builds on master branch. During a day lots of pull requests could be merged which would lead to a set of artifacts built for each, this seems like a waste as they will be lost in the pile. I don't know why users would use the artifacts from master opposed to the artifacts built in the nightly job,
=> chore: Skip building artifacts on master branch

plugins/outputs/cloudwatch/README.md, plugins/outputs/cloudwatch/cloudwatch.go, plugins/outputs/cloudwatch/sample.conf
resolves #11388
Used proxy code from inputs/cloudwatch to add proxy to outputs cloudwatch.
Did extensive (manual) testing to confirm functionality; will add details to issue.
=> feat: add proxy support for outputs/cloudwatch (#11388)

plugins/inputs/http/README.md, tools/readme_linter/rules.go
This pull request:
* Adds a `example output` section to the http plugin readme to resolve linter error I noticed here: https://github.com/influxdata/telegraf/runs/7306583417?check_suite_focus=true, this failing in an unrelated PR is probably something that needs to be fixed in the github action but I didn't address this.
* Make the linter more lenient and doesn't mark links against the long line rule, it looks like the logic is simpler now using the actual string to get the length as well. Still seems accurate when testing it locally.
=> docs: Add example output section to HTTP plugin 

plugins/inputs/modbus/configuration_request.go, plugins/inputs/modbus/modbus_test.go
Currently, the modbus request-based configuration accepts request sections with no fields defined. This setup does not make any sense, as subsequently no data is requested, and indicates a configuration error. To fail early and loudly, this PR will issue an error for these setups.
=> feat(inputs.modbus): Error out on requests with no fields defined.

plugins/parsers/prometheus/parser.go, plugins/parsers/prometheus/parser_test.go
In some cases the infinity bucked is not being parsed or generated from text prometheus input by the library **github.com/prometheus/common/expfmt**
I have not found the specifics, but it must be related to the version of libc because the same telegraf binary works on ubuntu with libc6:amd64 2.27-3ubuntu1.6, but does not work on debian with 2.28-10.
Because the infinity bucket has the same value as histogram sample count we can just enforce creation of this bucket if it is missing. They are doing basically the same thing in the underlying [library used to parse metrics](https://github.com/prometheus/common/blob/main/expfmt/text_create.go#L221) when generating text format from metrics.
resolves #11490
=> fix(parsers.prometheus): Histogram infinity bucket not being generated when using protobuf protocol

plugins/inputs/cisco_telemetry_mdt/README.md, plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go, plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go, plugins/inputs/cisco_telemetry_mdt/sample.conf
This PR adds configuration options for changing server-side GRPC keepalive/ping settings. We've found when some Cisco IOS-XE devices send telemetry data on GRPC-Dialout over a firewall, some timings on ping packets are affected so that pings arrive without data faster than the minimum ping interval time (5 minute default). This can also be exacerbated by using telemetry intervals longer than 5 minutes.
Each time this happens is a "strike", and if it happens more than 2 times the GRPC server in cisco_telemetry_mdt.go closes out the connection with a GRPC GOAWAY (ENHANCE_YOUR_CALM) error. Sometimes the telemetry device sets up a new connection to continue sending data; other times it fails and we lose data that should otherwise make it to Telegraf.
More information on the keepalive/strike …
=> feat(inputs.cisco_telemetry_mdt): Add GRPC Keepalive/timeout config options
